### ISSUE TITLE
Astro trigger generated by wizard does not work

### ISSUE THREAD

**Issue by cdaerr** [ioBroker/ioBroker.javascript#1000]
**Describe the bug**  
An astro trigger generated by the Cron or time wizard does not work

**To Reproduce**  
![grafik](https://user-images.githubusercontent.com/98185044/161832039-2452bfaa-6b9d-47c0-a2ff-0918a543edfe.png)

The yellow marked functions have schedules that were generated by the wizard and they are not triggered.

**Expected behavior**  
5 log entries.

**Versions:**  
 - Adapter version: v5.4.2
- JS-Controller version: 4.0.15
- Node version: v14.19.1
- Operating system: ubuntu 20.04 LTS

**Comment by winnyschuster** [comment]
currently, only **sunrise** and **sunset** are supported by js-adapter. not sure what the intention was for this behaviour.

**Comment by cdaerr** [comment]
I don't know exactly what you mean with "supported by js-adapter", but there is no difference in behavior when using sunrise or sunset. Dusk was only the example I choose because I did the documentation of the bug at this time.

When using sunset I get the same result:
![grafik](https://user-images.githubusercontent.com/98185044/162039358-3e865099-d3e3-4bf2-bdcb-a536c16b3f64.png)

For me it looks like the wizard generates something which does not work. But why there is no compile error on this?

In my scripts now I "manually" generate the astro tigger. Espacically for new users it is not nice, that generating with the wizard does not work correctly.

**Comment by winnyschuster** [comment]
i was just trying yesterday and it worked. However i was using 5.5.2(beta). Let me doublecheck this. I'll come back to you soon.
@Apollon77 if you don't have a solution in mind already for the enhancement, i'll be glad to get assigned to this

**Comment by cdaerr** [comment]
I think, I installed the adapter from the beta repository over adapters. Please tell me what's the best way to install a specific version. I can try a reinstall or a different version.

I'm not sure, that we have the same understanding on the behavior.
- Triggering on specified time, generated by the wizards works well. See the Example with 20:33 at the first post.
- Using the astro keyword (manually generated) works well. **Not only** sunrise and sunset are working. I also tested dusk (see first post) and solarNoon.
- Using **"exactTime":true,"start":"sunset"** generated by the wizard does not work, regardless of sunset, sunrise, dusk, solarNoon, ....

**Comment by winnyschuster** [comment]
no need to install a certain versionn, just upgrade the 'normal' way. And yes i was talking about the last point you described and that is working fine here for sunset.

mmmh, does your system a reboot at around midnight?

**Comment by Apollon77** [comment]
it feels to me that the "ExactTime:true" is wrong here. can you try to manually delete it please and check if it works as expected then? Then it would be an issue in the UI wof the Wizard

**Comment by winnyschuster** [comment]
can't see why it would be wrong when it is working well here. But anyway, omitting ExactTime, the script fires every minute...
```
javascript.0 | 2022-04-07 20:11:00.001 | info | script.js.schedule: triggered sunsetThu Apr 07 2022 20:11:00 GMT+0200 (Mitteleuropäische Sommerzeit)
javascript.0 | 2022-04-07 20:10:00.001 | info | script.js.schedule: triggered sunsetThu Apr 07 2022 20:10:00 GMT+0200 (Mitteleuropäische Sommerzeit)
javascript.0 | 2022-04-07 20:09:00.001 | info | script.js.schedule: triggered sunsetThu Apr 07 2022 20:09:00 GMT+0200 (Mitteleuropäische Sommerzeit)
javascript.0 | 2022-04-07 20:08:00.002 | info | script.js.schedule: triggered sunsetThu Apr 07 2022 20:08:00 GMT+0200 (Mitteleuropäische Sommerzeit)
javascript.0 | 2022-04-07 20:07:00.002 | info | script.js.schedule: triggered sunsetThu Apr 07 2022 20:07:00 GMT+0200 (Mitteleuropäische Sommerzeit)
```

```
schedule('{ "time": { "start": "sunset" }, "period": { "days": 1 } }', function () {
    log('triggered sunset' + new Date());
})
```

**Comment by cdaerr** [comment]
After update to v5.5.2 from beta repository:
![grafik](https://user-images.githubusercontent.com/98185044/162189924-4e8058df-5378-42a8-b1ba-f76aeed446c4.png)

The yellow marked ones did not trigger.

**Comment by cdaerr** [comment]
Same result:
![grafik](https://user-images.githubusercontent.com/98185044/162268100-a3b6c8fa-7d47-4fb0-8c4f-77dc2271dd95.png)

**Comment by winnyschuster** [comment]
that is really strange, but we'll get you there. code from wizard is definitely working well here when using sunrise or sunset, so it must be something else. I'll come back to you, meanwhile could you setup a schedule for sunrise please, just to be sure. If you don't mind could you provide a city name near your location, please?

**Comment by winnyschuster** [comment]
@cdaerr i think i found it. For now, please set your coordinates(to be found in System cofig) in js-Adapter astro settings again. You need to do this for each instance that is running. After that your wizard generated schedules schould work. Hopefully :-) But remember, only sunrise and sunset will work for now, if at all!. Let us know
![astroSettings](https://user-images.githubusercontent.com/7774086/162335345-b9c243ca-92f7-4771-b88d-d8f521e70bb7.PNG)

@Apollon77 this is way too much for me, in [function main, line 941](https://github.com/ioBroker/ioBroker.javascript/blob/b90d4bdf5982b724e9c05908a884ff09dcb77c87/main.js#L941)
when scheduler is initialized, there is no valid configuration yet for latitude and longitude which is done much later. I would not know how to force this to happen earlier. 

Enhancement is more or less ready though, sorry for all the spam in your sentry inbox, i forgot to disable sentry so everyone now knows what a lousy coder i am. PR will come once i have cleaned up new code. Hope that was the fault, especially when that worked here

**Comment by cdaerr** [comment]
I changed the Astro settings to local and I will try at sunset.

**Comment by Apollon77** [comment]
@winnyschuster interesting catch ... then move that line into the getData callback in https://github.com/ioBroker/ioBroker.javascript/blob/b90d4bdf5982b724e9c05908a884ff09dcb77c87/main.js#L949 ?!

**Comment by winnyschuster** [comment]
@Apollon77 thank you, that did the trick!

**Comment by cdaerr** [comment]
It works:
![grafik](https://user-images.githubusercontent.com/98185044/162497293-de17db9d-9485-4b32-8d1f-9dacdfd9c4a8.png)

**Comment by winnyschuster** [comment]
great, thanks for your feedback. enhancement for all other astro times provided by the wizard schould be available soon
