### ISSUE TITLE
lastchange in state wird gesetzt, obwohl keine Wertänderung

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.javascript#1005]
Hallo,
in der Version 5.5.4 ist mir aufgefallen, dass der Zeitstempel lc auch gesetzt wid bei setstate, obwohl der Wert sich nicht geändert hat!
Es wurde ack jeweils mit true verwendet.
MfG

**Comment by Apollon77** [comment]
Dann ist jetzt die Frage wie das genaue szenario ist ... wie schnell passieren hier welche Dinge?

**Comment by Hirsch-DE** [comment]
Bei mir wird regelmäßig ein Wert durch Statusmeldungen eines Gerätes ein State in bestimmten Bedingungen gesetzt. Dadurch wird oft ein gleicher Wert gesetzt. Dadurch ist es mir überhaupt aufgefallen, dass in der Admin-Seite beim state der Zeitstempel der letzten Änderung sich jedes mal auch ändert, obwohl der gleiche Wert gesetzt wurde!

24.04.2022 14:18:28 Ingo Fischer ***@***.***>:

**Comment by Apollon77** [comment]
kannst Du das Skript bitte mal zeigen?

**Comment by Apollon77** [comment]
ohne jetzt deinen exakten Use-Case zu kennen habe ich alles nochmal geprüft und einen edge case gefunden ... weiss nicht ob er dir hilft. Bitte versuche mal GitHub version.

Ansonsten wöäre es super eine "Step-by.step minimaler use case" Reproduktions-Info zu haben :-)

**Comment by Hirsch-DE** [comment]
Hallo,
einfach mal setstate mit einem festen Wert und ack = true setzen, dann das script noch einmal starten.
Bei jedem mal wird lc mit gesetzt.

24.04.2022 14:45:04 Ingo Fischer ***@***.***>:

**Comment by Apollon77** [comment]
Please try if GitHub version fixes your issue

**Comment by Hirsch-DE** [comment]
Hallo,

leider ohne Erfolg! Es hat sich nichts geändert.

**Comment by Apollon77** [comment]
Ich kann es nicht nachvollziehen, habe eine Skript was da dinge tut und so ... damit geht alles in allen Fällen (und nach Github install hast Du den javascript adapter neu gestartet?

**Comment by Hirsch-DE** [comment]
Ich hatte auch nochmal den Adapter hochgeladen und neu gestartet. Die main.js hat auch die aktuellen Änderungen drin!

Mir ist aufgefallen, dass der history-Adapter auch alle Werte aufnimmt, obwohl in der Konfiguration "nur Änderungen" aktiviert ist. Kann es sein, dass der history-Adapter sich den state.lc als Änderung heranzieht?

**Comment by Hirsch-DE** [comment]
Mir ist aufgefallen, dass das Problem auch nur auftritt, wenn in der Adapter-Instance die Option "Nicht alle Zustände beim Start abonnieren" aktiv ist!

**Comment by Apollon77** [comment]
1.) History ist bekannt und nein hat damit nichts zu tun, sollte im aktuellen Alpha History 2.0.0 (im Github test) behoben

2.) Passiert nur wenn "nicht" abonniert wird ... ok, das ist eine sehr wichtige Info .......

**Comment by Apollon77** [comment]
Please re-try GitHub version
