### ISSUE TITLE
state comment (state.c) and user (state.user) not available in triggers

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.javascript#1006]
**Describe the bug**  

When a script changes a state, the name of the script is stored in the state comment ``state.c``:

https://github.com/ioBroker/ioBroker.javascript/blob/e2b7ba8c0ab02d61e194ccbcf81fbb81727880bb/lib/sandbox.js#L401-L402

That works fine - the value is stored correctly:

``iobroker state get 0_userdata.0.test.myNumber``:

```json
{
  "val":11,
  "ack":false,
  "ts":1650812877192,
  "q":0,
  "c":"script.js.test.Object_Protection_Test",
  "from":"system.adapter.javascript.0",
  "user":"system.user.admin",
  "lc":1650810811819
}
```

But: This comment is not available in any script. A registered trigger on this id receives the following object as parameter:

```json
{
    "id": "0_userdata.0.test.myNumber",
    "newState": {
        "val": 15,
        "ts": 1650814142846,
        "ack": false,
        "lc": 1650814088015,
        "from": "system.adapter.javascript.0",
        "q": 0
    },
    "oldState": {
        "val": 15,
        "ts": 1650814117520,
        "ack": false,
        "lc": 1650814088015,
        "from": "system.adapter.javascript.0",
        "q": 0
    },
    "state": {
        "val": 15,
        "ts": 1650814142846,
        "ack": false,
        "lc": 1650814088015,
        "from": "system.adapter.javascript.0",
        "q": 0
    }
}
```

Where are ``c`` and ``user``?

**Versions:**  
 - Adapter version: 5.5.4
 - JS-Controller version: 4.0.21

**Comment by Apollon77** [comment]
> Where are c and user?

Seems they were allowed to go to long-time vacation :-))

GitHub version should add them. please check

**Comment by klein0r** [comment]
@Apollon77 That was fast 😮 Works as expected:

```javascript
on({id: "0_userdata.0.example_state", change: "any"}, async (obj) => {
    const state = obj.state;
    if (state.from == 'system.adapter.javascript.0') {
        console.log(`setState() of ${obj.id} in ${state.c} with value ${state.val}`);
    }
});

setState('0_userdata.0.example_state', false);
```

```
19:43:06.405 | info | javascript.0 (4813) script.js.test.Skript_1: setState() of 0_userdata.0.example_state in script.js.test.Skript_1 with value false
```

**Comment by klein0r** [comment]
@Apollon77 Please add the missing fields also here:

https://github.com/ioBroker/ioBroker.javascript/blob/b00a52cd52ccd4ad62a5a121aa058039cd87303c/src/public/google-blockly/own/blocks_trigger.js#L372-L392

**Comment by Apollon77** [comment]
Not sure about that. I just added the data fields. I did not added them as fields checked for subscription logic. Would need to check that. Question is if these are really trigger options.

**Comment by klein0r** [comment]
That is just a block to access properties of the obj (which is a parameter):

<img width="319" alt="Screenshot 2022-04-24 at 19 53 44" src="https://user-images.githubusercontent.com/1959049/164989775-a890a29f-28cb-4cf4-9b77-b1dd76b26078.png">

**Comment by Apollon77** [comment]
Ahhh then. I got it wrong only mobile. Will check later after kids in bed

**Comment by Apollon77** [comment]
see github

**Comment by gsicilia82** [comment]
First test worked fine with github v5.5.4. Attribute "c" is now included in callback object. Thx for fast implementation.
