### ISSUE TITLE
Maximale Anzahl von Instanz-Neustarts festlegen

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#101]
Wenn zB die Javascript-Instanz wegen eines Skript-Fehlers neu startet, wird das fehlerhafte Skript beim Neustart wieder ausgeführt und der Schleife beginnt von vorn. Das kostet viele Ressourcen. Ich bemerke so einen Fehler oft erst, weil der Lüfter des Servers anspringt.
Man sollte in den Instanz-Einstellungen festlegen können, wie häufig eine Instanz im Fehlerfall vom Controller neugestartet wird. Eine Benachrichtigung wäre dann auch schick ('maximum number of restarts').

Migrated from Trello

**Comment by BuZZy1337** [comment]
Wäre es nicht besser das betroffene Script automatisch deaktivieren zu lassen wenn ein Fehler auftritt damit es gar nicht erst wieder geladen wird?

**Comment by Apollon77** [comment]
Ist das noch relevant? Vor allem jetzt mit js-controller 3.2? Da sorgt der Controller für eine Limitierung der Restarts
