### ISSUE TITLE
After js-restart: RULEs-script not running

### ISSUE THREAD

**Issue by JayJay68** [ioBroker/ioBroker.javascript#1018]
**Describe the bug**  
After restart of the javascript-instance, all RULE-scripts are deactivated at objects-tab > javascript.0.scriptEnabled.common.*. But at the view (when you open the javascript-adapter) the RULE-scripts are visualized as "running"

**To Reproduce**  
1. Go to 'javacscript-adapter'
2. Create a new RULEs-script or identify a existent one
3. Activate the script
4. Check, if the datapoint    javascript.0.scriptEnabled.common.<NAME OF YOUR SCRIPT>  has the value  true
5. Go to the instance-tab of ioBroker and restart the javascript-instance
6. After Restart, check the datapoints again (like #4) and you will see, the the value is false. But if you go to the javascript-adapter they will show as running. But the RULEs-script are not working.
7. Info: This behavior is only with RULEs-script, not with the js-script.

Workaround: deactivate and then activate the RULEs-script each time after a javascript-instance-restart.

**Expected behavior**  
After a restart of the javascript-instance, the RULEs-script should be activated regulary.

**Screenshots & Logfiles**  
After restart of javascript-instance:
RULEs-script shown at the adapter-view
![grafik](https://user-images.githubusercontent.com/34628456/166269545-80b9797b-cd3a-45ce-9843-837372a9cf45.png)

But the datapoints are false:
![grafik](https://user-images.githubusercontent.com/34628456/166269810-631d9be1-f34a-4a08-a9b8-74b647a7e757.png)

**Versions:**  
 - Adapter version: javascript 5.2.21
 - JS-Controller version: 4.0.23
 - Node version: 12.22.4
 - Operating system: ARMBIAN 5.65 stable Debian GNU/Linux 10 (buster) 4.14.78-cubox

**Additional context**  
-

**Comment by Apollon77** [comment]
Known and already fixed in Beta ... coming to stabkle soon

**Comment by JayJay68** [comment]
OK, thank you. Maybe I have searched with wrong keywords.
