### ISSUE TITLE
2 selectors as trigger do not work properly

### ISSUE THREAD

**Issue by thomasklein1975** [ioBroker/ioBroker.javascript#1019]
Hi,

in case of usage of 2 selectors as triggers it would be great if it can be used without error/compile issue as shown below:

![grafik](https://user-images.githubusercontent.com/47893316/166271632-d5b8b1bd-6100-439e-a6ac-c51af70932f2.png)

thx in advance
Thomas

**Comment by Apollon77** [comment]
The current  blockly code did not expected that "two arrays" come in ... also array in general work kind of by chance :-)

Please try GitHub version

**Comment by thomasklein1975** [comment]
> The current blockly code did not expected that "two arrays" come in ... also array in general work kind of by chance :-)
> 
> Please try GitHub version

thx for very fast response/fixing. Now it*s working like expected.

**Comment by thomasklein1975** [comment]
> @thomasklein1975 Can you add the generated JavaScript as code?

no need because of being fixed but to have it completed
`javascript.0 (1142) script.js.common.Alarmanlage.Selektor_PIR_Alarm compile failed: at script.js.common.Alarmanlage.Selektor_PIR_Alarm:266`

**Comment by Apollon77** [comment]
5.6.1 on it's way

**Comment by quotschmacher** [comment]
just to mention it: i got v5.6.0 running and just tested a trigger in blockly with two selectors and it worked out of the box.
generated following js code:

```on({id: [Array.prototype.slice.apply($("state[id=hmip.0.devices.*.channels.1.windowState]")),Array.prototype.slice.apply($("state[id=hmip.0.devices.*.channels.0.sabotage]"))], change: "ne"}, async function (obj) {
  });```

and the snippet from the blockly is

```
<block type="on_ext" id="C:_U?,p`9suV$76QHa6Y">
                                <mutation xmlns="http://www.w3.org/1999/xhtml" items="2"></mutation>
                                <field name="CONDITION">ne</field>
                                <field name="ACK_CONDITION"></field>
                                <value name="OID0">
                                  <shadow type="field_oid" id="sQkc~iZa%3!L=km3z-bM">
                                    <field name="oid">default</field>
                                  </shadow>
                                  <block type="selector" id="j,Jc7e[_W0Qw(r!k[z9v">
                                    <field name="TEXT">state[id=hmip.0.devices.*.channels.1.windowState]</field>
                                  </block>
                                </value>
                                <value name="OID1">
                                  <shadow type="field_oid" id="$M,2H.emEln5F=)ZYJS+">
                                    <field name="oid">default</field>
                                  </shadow>
                                  <block type="selector" id=".9|W/FJ|Elq}{,=ErPZk">
                                    <field name="TEXT">state[id=hmip.0.devices.*.channels.0.sabotage]</field>
                                  </block>
                                </value>
                              </block>
```

**Comment by Apollon77** [comment]
@thomasklein1975 Can you please show the generated code with  the GitHub version  ... because if the code is that way then it will not work as I fixed it ... I was expecting something else ... need to rework it. I stopped 5.6.1 deployment

But also this @quotschmacher might not generate an error but will also not "work" as expected

**Comment by Apollon77** [comment]
Can someone please show me the generated code of such a block with a static state id? ( I can do tonight, but maybe you are faster)

**Comment by quotschmacher** [comment]
not sure if i got you right @Apollon77 

you mean this?
`on({id: [Array.prototype.slice.apply($("state[id=hmip.0.devices.*.channels.1.windowState]")),Array.prototype.slice.apply($("state[id=hmip.0.devices.*.channels.0.sabotage]"))], change: "ne"}, async function (obj) {
  });
on({id: ['hmip.0.groups.8b0d975a-0b11-4fc8-92e9-1f58923dbae8.boostMode','hmip.0.groups.8b0d975a-0b11-4fc8-92e9-1f58923dbae8.boostDuration'], change: "ne"}, async function (obj) {
  });`

generated by 
![image](https://user-images.githubusercontent.com/50583947/166435613-6392aca8-22ee-4068-af40-afaecb099c1d.png)

**Comment by thomasklein1975** [comment]
> @thomasklein1975 Can you please show the generated code with the GitHub version ... because if the code is that way then it will not work as I fixed it ... I was expecting something else ... need to rework it. I stopped 5.6.1 deployment
> 
> But also this @quotschmacher might not generate an error but will also not "work" as expected

sure:

on({id: [Array.prototype.slice.apply($("state[id=*](functions=pir_alarm_innen)")),Array.prototype.slice.apply($("state[id=*](functions=fenster_tuer_status)"))], change: "any"}, async function (obj) {
  });
Is that what you need?

**Comment by Apollon77** [comment]
Ok, please try GitHub version again and post the generated code (needed to do the chancge "Blind" because no test system acces, so could be good or not :-)

Code should now have an "array.concat" style ... 

ANd maybe also try top mix such an "$-selector" with a "static" id and such stuff

**Comment by Apollon77** [comment]
Ok, released in 5.7.0. STill thank you for feedback
