### ISSUE TITLE
Einstellungen Zusatzmodule optimieren (auch bei Tab akzeptieren)

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.javascript#102]
In den Einstellungen beim Javascript Adapter muss man nach dem Eintragen eines Zusatzmoduls die [Enter] Taste drücken.

Ich bin darüber gestolpert, da nach einem [TAB] das Feld verlassen wird, das Zusatzmodul aber nicht "eingeloggt" wird. Im Forum gibt es ebenfalls mehrere Fälle.

Verbesserungsvorschlag:

Wenn ein Modul eingetragen und mit [TAB] das Eingabefeld verlassen wird, sollte das Modul auch akzeptiert werden

**Comment by BuZZy1337** [comment]
Das ist im materialize js code so festgelegt.
Siehe:
https://github.com/Dogfalo/materialize/blob/master/js/chips.js#L163

Wenn wir das auf ioBroker Seite ändern, wird es spätestens mit dem nächsten Update von materialize wieder raus fliegen.

Du müsstest also bei https://github.com/Dogfalo/materialize/ ein Issue öffnen - und fordern, dass Chips auch beim drücken von TAB hinzugefügt werden.

**Comment by Apollon77** [comment]
Wurde das nicht im Forum schonmal diskutiert und angeblich gabs ne neuere materialize Version wo das schon drin ist?!

**Comment by BuZZy1337** [comment]
Wie gesagt, laut code von materialize wird "addChip" definitiv nur ausgeführt wenn Taste 13 (ENTER) gedrückt wird..?!
```js
        if (13 === e.which) {
          // Override enter if autocompleting.
          if (self.hasAutocomplete &&
              $chips.find('.autocomplete-content.dropdown-content').length &&
              $chips.find('.autocomplete-content.dropdown-content').children().length) {
            return;
          }

          e.preventDefault();
          self.addChip({tag: $target.val()}, $chips);
          $target.val('');
          return;
        }
```

um auch auf TAB anzusprechen (Taste 9) müsste es so aussehen:
```js
        if (13 === e.which || 9 === e.which) {
          // Override enter if autocompleting.
          if (self.hasAutocomplete &&
              $chips.find('.autocomplete-content.dropdown-content').length &&
              $chips.find('.autocomplete-content.dropdown-content').children().length) {
            return;
          }
          if (13 === e.which) {
            e.preventDefault();
          }
          self.addChip({tag: $target.val()}, $chips);
          $target.val('');
          return;
        }
```

**Comment by GermanBluefox** [comment]
Machen wir es rein. Ganze materialize Code ist im Admin repo.
https://github.com/ioBroker/ioBroker.admin/blob/master/src/materialize-css/js/chips.js#L263


Ich würde auch onblur aktivieren. Wer nachts?

чт, 19 апр. 2018 г., 11:15 BuZZy1337 <notifications@github.com>:

**Comment by BuZZy1337** [comment]
Wenn du mir sagst wie ich admin direkt von github installieren kann zum 
testen...

Ich bekomme immer ein "Admin muss via npm i iobroker.admin" installiert 
werden oder so wenn ich die Adapter settings nach einem github install von 
admin öffne.. :D

**Comment by BuZZy1337** [comment]
Ich kümmere mich. :relaxed:

**Comment by BuZZy1337** [comment]
PR https://github.com/ioBroker/ioBroker.admin/pull/249 is ready! :)
