### ISSUE TITLE
IDs vom Selektor - Listeneinträge mehrfach

### ISSUE THREAD

**Issue by AFPass** [ioBroker/ioBroker.javascript#1021]
Ich habe folgenden Blockly Code.
![image](https://user-images.githubusercontent.com/13101074/166635415-04b87b82-4e13-4a82-b549-00cfc72f3594.png)

`var v1;

v1 = null;
v1 = [Array.prototype.slice.apply($("channel[state.id=*.online]"))];
console.log(v1);
`
Ich möchte damit den Online Status von allen Geräten abfragen.
In der Liste erscheinen aber alle Geräte doppelt. Manchmal sogar dreifach.

**Versions:**  
 - Adapter version: 5.6.0
 - JS-Controller version: 4.0.23
 - Node version: v14.19.1
 - Operating system: Debian 11

**Comment by Apollon77** [comment]
Zeig doch mal bitte die Ausgabe

**Comment by AFPass** [comment]
4.5.2022, 09:38:47.807	[info ]: javascript.0 (365) Stop script script.js.common.VirtuelleObjekte.Skript_1
4.5.2022, 09:38:51.143	[info ]: javascript.0 (365) Start javascript script.js.common.VirtuelleObjekte.Skript_1
4.5.2022, 09:38:54.556	[info ]: javascript.0 (365) script.js.common.VirtuelleObjekte.Skript_1: [['alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oliver.Button.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','shelly.0.SHBDUO-1#664586#1.online','shelly.0.SHBTN-1#483FDA6EF8D6#1.online','shelly.0.SHBTN-1#483FDA700AD7#1.online','shelly.0.SHBTN-1#483FDA700AD7#1.online','shelly.0.SHGS-1#50029178B9F1#1.online','shelly.0.SHGS-1#50029178B9F1#1.online','shelly.0.SHPLG-S#01E162#1.online','shelly.0.SHPLG-S#01E162#1.online','shelly.0.SHPLG-S#0413BF#1.online','shelly.0.SHPLG-S#0413BF#1.online','shelly.0.SHPLG-S#3CF059#1.online','shelly.0.SHPLG-S#3CF059#1.online','shelly.0.SHPLG-S#7AE856#1.online','shelly.0.SHPLG-S#7AE856#1.online','shelly.0.SHPLG-S#B85D3F#1.online','shelly.0.SHPLG-S#B85D3F#1.online','shelly.0.SHPLG-S#B86109#1.online','shelly.0.SHPLG-S#B86109#1.online','shelly.0.SHPLG-S#B8610B#1.online','shelly.0.SHPLG-S#B8610B#1.online','shelly.0.SHPLG-S#B86146#1.online','shelly.0.SHPLG-S#B86146#1.online','shelly.0.SHPLG-S#B86510#1.online','shelly.0.SHPLG-S#B86510#1.online','shelly.0.SHPLG-S#B86FCB#1.online','shelly.0.SHPLG-S#B86FCB#1.online','shelly.0.SHPLG-S#EAE8F4#1.online','shelly.0.SHPLG-S#EAE8F4#1.online','shelly.0.SHPLG-S#EF627A#1.online','shelly.0.SHPLG-S#EF627A#1.online','shelly.0.SHRGBW2#6F82E4#1.online','shelly.0.SHRGBW2#6F82E4#1.online','shelly.0.SHSW-1#2C09F5#1.online','shelly.0.SHSW-1#2C09F5#1.online','shelly.0.SHSW-1#2C67D8#1.online','shelly.0.SHSW-1#2C67D8#1.online','shelly.0.SHSW-1#32C1F8#1.online','shelly.0.SHSW-1#32C1F8#1.online','shelly.0.SHSW-1#32C943#1.online','shelly.0.SHSW-1#32C943#1.online','shelly.0.SHSW-21#5A4B5D#1.online','shelly.0.SHSW-21#5A4B5D#1.online','shelly.0.SHSW-25#0094CA#1.online','shelly.0.SHSW-25#0094CA#1.online','shelly.0.SHSW-25#B92F2A#1.online','shelly.0.SHSW-25#B92F2A#1.online','shelly.0.SHSW-25#B94E8D#1.online','shelly.0.SHSW-25#B94E8D#1.online','shelly.0.SHSW-25#E098069542D5#1.online','shelly.0.SHSW-25#E098069542D5#1.online','shelly.0.SHSW-PM#008C55#1.online','shelly.0.SHSW-PM#008C55#1.online','shelly.0.SHSW-PM#00CF34#1.online','shelly.0.SHSW-PM#00CF34#1.online','shelly.0.SHSW-PM#76B27B#1.online','shelly.0.SHSW-PM#76B27B#1.online','shelly.0.SHSW-PM#76BB7E#1.online','shelly.0.SHSW-PM#76BB7E#1.online','shelly.0.SHSW-PM#A4CF12F3CEC2#1.online','shelly.0.SHSW-PM#A4CF12F3CEC2#1.online','shelly.0.SHSW-PM#D8BFC019C102#1.online','shelly.0.SHSW-PM#D8BFC019C102#1.online','shelly.0.SHSW-PM#D8BFC019C5EB#1.online','shelly.0.SHSW-PM#D8BFC019C5EB#1.online','shelly.0.SHSW-PM#E6244A#1.online','shelly.0.SHSW-PM#E6244A#1.online','shelly.0.SHSW-PM#E6793F#1.online','shelly.0.SHSW-PM#E6793F#1.online','shelly.0.SHSW-PM#E67B32#1.online','shelly.0.SHSW-PM#E67B32#1.online','worx.0.20203019xxxxxxxxx2CB.mower.online','worx.0.20203019xxxxxxxxx2CB.rawMqtt.online','worx.0.20203019xxxxxxxxx2CB.rawMqtt.raw.online']]
4.5.2022, 09:38:54.557	[info ]: javascript.0 (365) script.js.common.VirtuelleObjekte.Skript_1: registered 0 subscriptions and 0 schedules

**Comment by AFPass** [comment]
4.5.2022, 09:38:47.807	[info ]: javascript.0 (365) Stop script script.js.common.VirtuelleObjekte.Skript_1
4.5.2022, 09:38:51.143	[info ]: javascript.0 (365) Start javascript script.js.common.VirtuelleObjekte.Skript_1
4.5.2022, 09:38:54.556	[info ]: javascript.0 (365) script.js.common.VirtuelleObjekte.Skript_1: [['alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.037A87F723B7xxxxxxxx97A7A35AED72.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090LA0xxxx501WR.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U5xxxxxx0BA9.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.0.Echo-Devices.G090U61xxxx72807.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.2e893f9022dfxxxxxxxxxxx78336ee3d.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','alexa2.1.Echo-Devices.G090Uxxxxxx55232.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Garten.Rasenmäher.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Kueche.Schranklicht.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Schlafzimmer.Oxxx.Button.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','linkeddevices.0.Grundstueck.Haus.Terrasse.Licht.Überdachung.online','shelly.0.SHBDUO-1#664586#1.online','shelly.0.SHBTN-1#483FDA6EF8D6#1.online','shelly.0.SHBTN-1#483FDA700AD7#1.online','shelly.0.SHBTN-1#483FDA700AD7#1.online','shelly.0.SHGS-1#50029178B9F1#1.online','shelly.0.SHGS-1#50029178B9F1#1.online','shelly.0.SHPLG-S#01E162#1.online','shelly.0.SHPLG-S#01E162#1.online','shelly.0.SHPLG-S#0413BF#1.online','shelly.0.SHPLG-S#0413BF#1.online','shelly.0.SHPLG-S#3CF059#1.online','shelly.0.SHPLG-S#3CF059#1.online','shelly.0.SHPLG-S#7AE856#1.online','shelly.0.SHPLG-S#7AE856#1.online','shelly.0.SHPLG-S#B85D3F#1.online','shelly.0.SHPLG-S#B85D3F#1.online','shelly.0.SHPLG-S#B86109#1.online','shelly.0.SHPLG-S#B86109#1.online','shelly.0.SHPLG-S#B8610B#1.online','shelly.0.SHPLG-S#B8610B#1.online','shelly.0.SHPLG-S#B86146#1.online','shelly.0.SHPLG-S#B86146#1.online','shelly.0.SHPLG-S#B86510#1.online','shelly.0.SHPLG-S#B86510#1.online','shelly.0.SHPLG-S#B86FCB#1.online','shelly.0.SHPLG-S#B86FCB#1.online','shelly.0.SHPLG-S#EAE8F4#1.online','shelly.0.SHPLG-S#EAE8F4#1.online','shelly.0.SHPLG-S#EF627A#1.online','shelly.0.SHPLG-S#EF627A#1.online','shelly.0.SHRGBW2#6F82E4#1.online','shelly.0.SHRGBW2#6F82E4#1.online','shelly.0.SHSW-1#2C09F5#1.online','shelly.0.SHSW-1#2C09F5#1.online','shelly.0.SHSW-1#2C67D8#1.online','shelly.0.SHSW-1#2C67D8#1.online','shelly.0.SHSW-1#32C1F8#1.online','shelly.0.SHSW-1#32C1F8#1.online','shelly.0.SHSW-1#32C943#1.online','shelly.0.SHSW-1#32C943#1.online','shelly.0.SHSW-21#5A4B5D#1.online','shelly.0.SHSW-21#5A4B5D#1.online','shelly.0.SHSW-25#0094CA#1.online','shelly.0.SHSW-25#0094CA#1.online','shelly.0.SHSW-25#B92F2A#1.online','shelly.0.SHSW-25#B92F2A#1.online','shelly.0.SHSW-25#B94E8D#1.online','shelly.0.SHSW-25#B94E8D#1.online','shelly.0.SHSW-25#E098069542D5#1.online','shelly.0.SHSW-25#E098069542D5#1.online','shelly.0.SHSW-PM#008C55#1.online','shelly.0.SHSW-PM#008C55#1.online','shelly.0.SHSW-PM#00CF34#1.online','shelly.0.SHSW-PM#00CF34#1.online','shelly.0.SHSW-PM#76B27B#1.online','shelly.0.SHSW-PM#76B27B#1.online','shelly.0.SHSW-PM#76BB7E#1.online','shelly.0.SHSW-PM#76BB7E#1.online','shelly.0.SHSW-PM#A4CF12F3CEC2#1.online','shelly.0.SHSW-PM#A4CF12F3CEC2#1.online','shelly.0.SHSW-PM#D8BFC019C102#1.online','shelly.0.SHSW-PM#D8BFC019C102#1.online','shelly.0.SHSW-PM#D8BFC019C5EB#1.online','shelly.0.SHSW-PM#D8BFC019C5EB#1.online','shelly.0.SHSW-PM#E6244A#1.online','shelly.0.SHSW-PM#E6244A#1.online','shelly.0.SHSW-PM#E6793F#1.online','shelly.0.SHSW-PM#E6793F#1.online','shelly.0.SHSW-PM#E67B32#1.online','shelly.0.SHSW-PM#E67B32#1.online','worx.0.20203019xxxxxxxxx2CB.mower.online','worx.0.20203019xxxxxxxxx2CB.rawMqtt.online','worx.0.20203019xxxxxxxxx2CB.rawMqtt.raw.online']]
4.5.2022, 09:38:54.557	[info ]: javascript.0 (365) script.js.common.VirtuelleObjekte.Skript_1: registered 0 subscriptions and 0 schedules

**Comment by Apollon77** [comment]
Please Try GitHub version

**Comment by AFPass** [comment]
Sieht gut aus.

**Comment by Apollon77** [comment]
Kommt im nächsten release
