### ISSUE TITLE
Changing a script - Error in Log

### ISSUE THREAD

**Issue by SKB-CGN** [ioBroker/ioBroker.javascript#1023]
Hi,
currently, when i change some scripts, i get the following error inside the Log, after restarting the script:

`<html><body>

javascript.0 | 2022-05-09 09:23:51.609 | info | script.js.common.SolarEdge: registered 0 subscriptions and 0 schedules
-- | -- | -- | --
javascript.0 | 2022-05-09 09:23:51.581 | info | Start javascript script.js.common.SolarEdge
javascript.0 | 2022-05-09 09:23:51.560 | error | Error by canceling scheduled job "<Anonymous Job 9 2022-05-09T07:20:36.747Z>"
javascript.0 | 2022-05-09 09:23:51.559 | error | Error by canceling scheduled job "<Anonymous Job 8 2022-05-09T07:20:36.740Z>"
javascript.0 | 2022-05-09 09:23:51.558 | info | Stop script script.js.common.SolarEdge

</body>
</html>`

Script-Version: v5.2.21

**Comment by Apollon77** [comment]
Can you please try the lastest Beta 5.7.0 if it happens there too?

**Comment by SKB-CGN** [comment]
Thanks a lot.
Seems to work currently :)

**Comment by Apollon77** [comment]
Then please reopen if happens again
