### ISSUE TITLE
getAstroDate not working for 'night' and 'nightEnd'

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.javascript#1028]
**Describe the bug**  
Getting error **Cannot get astro date for "nightEnd"** when trying to get astro-date for 'night' and 'nightEnd' (Invalid date).

**To Reproduce**  
Use following code:
`getAstroDate('night').toLocaleTimeString()`
`getAstroDate('nightEnd').toLocaleTimeString()`

**Expected behavior**  
Getting a normal timestamp like '05:08:12' like it is by using getAstroDate('sunrise').toLocaleTimeString()

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/58532773/169465194-7cf34f86-b40d-4a5c-858d-e05d0d3b8818.png)

**Versions:**  
 - Adapter version: 5.7.0
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: Raspbian (Raspberry Pi OS)

**Comment by Apollon77** [comment]
Could it be that there is no night/nightEnd for your location these days? And yes this can really happen as more noth you are

**Comment by blackeagle998** [comment]
Where can I check this, if there is a "night" time for my location (100 Km south of Berlin)?
To my mind there should be one or am I wrong?

**Comment by Apollon77** [comment]
Setze die Daten mal hier ein http://suncalc.net/#/50.6252,12.9239,13/2022.05.20/23:29

**Comment by blackeagle998** [comment]
This is really a fact that I did not know until today, thank you!

**Comment by JBSullivan** [comment]
Bei mir passiert das gleiche, basierend auf dem Astro Skript.

https://www.kreyenborg.koeln/iobroker-astro-tageszeit-abfragen-und-in-datenpunkt-eintragen/

**Comment by Karatekid2407** [comment]
Ist es notwendig unbedingt einen error zu bringen oder wäre eine Ausgabe als NaN oder 0 nicht besser?
Ich kann es über Blockly leider nicht anders abfangen außer die Variable Nacht gar nicht abzurufen :/
Und eine Einschränkung über die Monate finde ich auch keine ideale Lösung.

**Comment by Apollon77** [comment]
Naja die Thematik ist ja das eine von Dir definierte Logik an der Stelle KEINE Zeit bekommt und damit ggf nicht korrekt tut ... solltest Du wissen als Entwickler oder?!

**Comment by Apollon77** [comment]
Die Farge ist ja auch ob "night" für dich das richtige dann ist ... gibt ja noch andere die es gibt und vllt ohne fehler laufen?

**Comment by Karatekid2407** [comment]
Dann habe ich mich glaube ich schlecht ausgedrückt.

Ich setze alle Astropunkte auf verschiedene Datenpunkt über Blockly. Soweit alles gut.
Jedoch sobald ich aktuell den Block "Aktuelle Zeit von Nacht ..." ins Script bringe kommt schon ein Error.

Dies kann ich über Blockly maximal so abfangen, dass ich diese Abfrage in den Sommermonaten nicht mache, da ansonsten mein Log immer einen Error bekommt.
Versuche meinen Log sauber zu halten.

z.B. dieses einfache Script bringt schon einen Error.
Darum war meine Frage ob man unbedingt diesen Error setzen muss.
Ich halte es nicht für notwendig, da der Output "Invalid Data" ist, welchen man über IF-Block abfangen könnte.

![Blockly](https://user-images.githubusercontent.com/38478308/178119599-fc8aba45-bbb4-423b-aba7-2e10d6ede2ae.jpg)
