### ISSUE TITLE
The script is not running on slave

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.javascript#1029]
**Describe the bug**  
I had a separate instance for the slave system. Previously worked. Unfortunately, I didn’t notice from which version it stopped, but it definitely doesn’t work on 5.7.0. What does the log for some reason display values ​​from 0, and 2 instances (they are on the master)

**Expected behavior**  
it is necessary that the instance that stands on the slave is performed on it.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/169707766-0d0e841f-a42d-45cb-9f9f-c9f4bf305522.png)

**Versions:**  
 - Adapter version: 5.7.0
 - JS-Controller version: 4.0.23
 - Node version: v14.19.2 - master. v14.19.1 - slave
 - Operating system: master on docker. Slave - rpi
___
update
___
I added one more instance, I run the script, but the values ​​in the log come from the first two instances that are on the master.
And then it seems like they start working only for the slave
![image](https://user-images.githubusercontent.com/37106885/169708187-39c95bae-ec5c-4a7b-9d34-6dee034d0c81.png)

**Comment by Apollon77** [comment]
Admin only shows the log frommthe selected host ... please check the real logfiles on disk on the hosts ... is it really not working or just "partially sjhown logs" confusion"?

**Comment by Apollon77** [comment]
no response, closed
