### ISSUE TITLE
[Done] add .toFixed(n) Block in Blockly

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.javascript#103]
Actual we only got Math.round(x) in Blockly - but Math.round always gives full number without decimal places..

Workaround (round to 2 decimal places):
![screenshot - 13 04 2018 13_58_05](https://user-images.githubusercontent.com/6979405/38734256-29bbf518-3f25-11e8-80cd-42f2c74cbd09.png)

.. EDIT: `parseFloat(x.toFixed(n))` is the right way to get a number (not a string) again.

**Comment by AlCalzone** [comment]
I think a `roundTo` function without converting to string and back would be more useful than `parseFloat(toFixed(...))`. Just like you posted as the block above:
```js
function roundTo(value, digits) {
	const exp = Math.pow(10, digits);
	return Math.round(value * exp) / exp;
}
```

**Comment by BuZZy1337** [comment]
I added it that way you suggested it @AlCalzone 
Blockly generates the code 
`Math.round(x * exp) / exp;`
with the new Block. :+1: 

PR https://github.com/ioBroker/ioBroker.javascript/pull/104 is ready. :smile:
