### ISSUE TITLE
BlocklyPlus Integration

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.javascript#1031]
Wäre es nicht sinnvoll BlocklyPlus https://github.com/excal-foley/ioBroker.blockly-plus hier mit zu integrieren?

Das Thema wurde schonmal gewollt, damals von dutchman https://github.com/ioBroker/ioBroker.javascript/issues/649

**Comment by Apollon77** [comment]
This could really make sense ... the devleoper can open a PR against JavaScript adapter and nwe will be happy to review ...

**Comment by duczz** [comment]
Passiert hierzu eig noch was?

**Comment by Apollon77** [comment]
Naja ist ein Enhancement, also wird daran gearbeitet wenn Zeit ist. PRs welcome

**Comment by skvarel** [comment]
Mit der Script Adapter Version 7.1.1 läuft der Blockly Plus Adapter nicht mehr und somit sind auch alle Scripte, die diese Blöcke enthalten unbrauchbar.

Es würde schon sehr helfen, wenn Blöcke für die Logik-Operatoren erweitert würden, um die && und II Blöcke nicht mehr verschachteln zu müssen.


![251938829-84a73e98-f1af-4503-b0ec-6ecc96c26ed3](https://github.com/ioBroker/ioBroker.javascript/assets/1114419/e5b2ce7f-cc58-48eb-8f5c-6ad61c4ba007)

**Comment by klein0r** [comment]
> Es würde schon sehr helfen, wenn Blöcke für die Logik-Operatoren erweitert würden, um die && und II Blöcke nicht mehr verschachteln zu müssen.

Das ist ja in den aktuellen Versionen im Standard enthalten. Daher mache ich hier zu.
