### ISSUE TITLE
Im LOG zum Script Aufteilung der Infos in zusätzliche Spalten Herkunft oder Auslöser mit Ausblendemöglichkeit

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.javascript#1033]
Im Protokolle-Log erscheint beim Logging Script-console.log() eine Darstellung, die es schwierig macht den eigentlich Text gut zu erkennen.
```
javascript.0 | 2022-05-24 11:47:46.178 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen: Aktuelle Temperatur von SZ_VORNE hat sich geändert auf: 21.5 °C von 21 °C
javascript.0 | 2022-05-24 11:47:45.620 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen: Aktuelle Temperatur von WZ_LINKS hat sich geändert auf: 21 °C von 20.5 °C
```
`Zusätzliche Spalte einführen Herkunft/Auslöser mit entsprechender Ausblendmöglichkeit oder Verkleinerung der Breite`
```
Quelle       | Zeit                    |debug |  Herkunft / Auslöser                     | Nachricht
javascript.0 | 2022-05-24 11:47:46.178 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen| Aktuelle Temperatur von SZ_VORN
```
Im Script-Log erscheint z.B. Script-console.log() Einträge:
![image](https://user-images.githubusercontent.com/84818934/170094627-0d748436-4535-4daf-9af4-b5a2f3b42780.png)
Hier werden immer wieder Eintragsinfos gezeigt, die nicht für jede Zeile notwendig sind. Um die wichtigen Logeinträge zu sehen, die man bei besserer Trennung/Aufsplittung und Verkleinerung/Ausblenden von Spalten dann effektiver darstellen kann.
Man braucht im Normalfall nur seine console.log() und die Zeit:

`IST:`
```
12:52:12.009 | info | javascript.0 (1648) script.js.JARVIS.System.Export_Import_Widgets: registered 8 subscriptions and 0 schedules
```
`SOLL:`  Durch Aufteilung in entsprechende Spalten mit Ausblendmöglichkeit
```
12:52:12.009 | registered 8 subscriptions and 0 schedules
```

**Comment by GermanBluefox** [comment]
Das wird HOCHWARCHEINLICH nie implementiert, da nicht zum Konzept passt.
