### ISSUE TITLE
getAstroDate not working with patterns like {astro: "sunrise", shift: +60}

### ISSUE THREAD

**Issue by lizardking** [ioBroker/ioBroker.javascript#1034]
According to the docs the `getAstroDate `function accepts the same patterns as the `schedule `method. The function works when the astro event and if needed the shift are specified as separate parameters, but the function returns an error when the specifications of the astro event is the same as in the schedule method, e.g. `{astro: "sunrise", shift: +60}`.

The following script reproduces the problem:
```
var working=getAstroDate( "sunrise",60);
log(working);
var notWorking=getAstroDate( { astro: "sunrise", shift: +60 });
log(notworking);
```

The log shows the following entries:
```
error: javascript.0 (32109) script.js.common.test.astroTest: TypeError: pattern.toLowerCase is not a function
error: javascript.0 (32109)     at getAstroDate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1348:65)
```

At least in my understanding of the docu `{astro: "sunrise", shift: +60}` should work as well. When using `schedule `and `getAstroDate `the inconsistent paras are confusing and require transformation between the para types.

**Comment by Apollon77** [comment]
I think here the documentation is wrong and should state that the same list of "astro event values" are supported as first parameter. I will adjust the documentation

**Comment by winnyschuster** [comment]
@lizardking your working example gives no error but returns sunrise at 1970-1-1 :-) shift parameter needs to be the third one, second one is a date or epoche time stamp
@Apollon77 doc is not mentioning third parameter though its explained in editor when hovering the function

**Comment by Apollon77** [comment]
@winnyschuster this is not really an order because it defined an object and the names are the keys
