### ISSUE TITLE
Blockly: incorrect javascript emit for update block with delay and

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#105]
See https://forum.iobroker.net/viewtopic.php?f=21&t=13517

Using the the update block in conjunction with delay produces an incorrect javascript emit when the "clear running" option is set. Example output for `clear running = false`:
```js
setStateDelayed("admin.0.ArZi-Deckenlampe"/*ArZi-Deckenlampe*/, (value == 'ON'), true, 100, false);
```

and with `clear running = true`:
```js
setStateDelayed("admin.0.ArZi-Deckenlampe"/*ArZi-Deckenlampe*/, (value == 'ON'), true, 100, false);
```
which is exactly the same. It should have `true` as the last parameter, like this:
```js
setStateDelayed("admin.0.ArZi-Deckenlampe"/*ArZi-Deckenlampe*/, (value == 'ON'), true, 100, true);
```

**Comment by BuZZy1337** [comment]
Done with https://github.com/ioBroker/ioBroker.javascript/commit/96be92353a40cb5997797ef2e43d0c28b0242b64

**Comment by fabian-barney** [comment]
Broken again in 3.6.4.
