### ISSUE TITLE
[Feature Request] Allow Message communication between scripts

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#106]
The idea is to allow a "sendToScript" functionality to communicate with messages inside the JavaScript adapter (inside one instance). A Script that consumes a message needs to define/subscribe and define a unique name for the messages he wants to receive. Other scripts can use a "sendToScript(messagename, messageobject)" method to send messages. Maybe also support "sendToScript(instancem messagename, messageobject)" to allow inter-instance messaging.

**Comment by GermanBluefox** [comment]
May be
```
// Send to very specific instance and script name
messageTo('instance', 'scriptname', 'messageName', data, {timeout: 1000}, result => console.log('result'));
```

```
// no matter which instance and what the script name
messageTo(null, null, 'messageName', data, {timeout: 1000}, result => console.log('result'));
```

```
// on some script
onMessage('messageName', (data, cb) => {console.log(data); cb(Date.now())});
```

**Comment by Apollon77** [comment]
yes. I would not really see the usecase for option 2, but why not :-))

**Comment by GermanBluefox** [comment]
Or just
```
messageTo({instanece: 'instance', script: 'scriptname', message: 'messageName'}, data, {timeout: 1000}, result => console.log('result')); ```
And it could be combined into:
```
messageTo('scriptname', data, {timeout: 1000}, result => console.log('result')); ```

**Comment by Apollon77** [comment]
makes sense

**Comment by GermanBluefox** [comment]
Done
