### ISSUE TITLE
Pls check deprecated dep to coffee-script -> coffeescript

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.javascript#1067]
CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

Please check if this dep can be updated to the correct dependency.

**Comment by Tombra1889** [comment]
Upgrade from 5.8.5 to 5.8.10:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/60692414/179290332-c4a9e2ed-0d02-4db6-9b07-838949069953.png">

**Comment by Grothesk242** [comment]
> Upgrade from 5.8.5 to 5.8.10:
> 
> <img alt="image" width="1232" src="https://user-images.githubusercontent.com/60692414/179290332-c4a9e2ed-0d02-4db6-9b07-838949069953.png">

Check 
```
cd /opt/iobroker
nechad@chet:/opt/iobroker $ npm ls coffee-script coffeescript
iobroker.inst@3.0.0 /opt/iobroker
└─┬ iobroker.javascript@5.8.10
  ├─┬ coffee-compiler@0.3.2
  │ └── coffee-script@1.12.7 deduped
  ├── coffee-script@1.12.7
  └── coffeescript@1.12.7pm ls coffee-script coffeescript
```
Should look like this: 

````

```

**Comment by Apollon77** [comment]
we continue in #1076
