### ISSUE TITLE
Fehleranzeige im Bereich Skripte

### ISSUE THREAD

**Issue by SteveWi-291** [ioBroker/ioBroker.javascript#1069]
Ich bekomme neuerdings Fehler im Skript - Teil, wie in den Bildern angezeigt. Dieser Fehler trat erst auf, als ich auf Admin 6.1.11 bzw die letzten Updates von iosocket etc. installiert habe...

System:
Node.js:  v16.15.1
NPM:  v8.11.0
JS: v5.8.5

![image](https://user-images.githubusercontent.com/71070045/178541576-7b3b6299-cb6f-44d4-bc11-e42af5298b45.png)
![image](https://user-images.githubusercontent.com/71070045/178541591-37ebb916-fd65-4890-9e03-76dda5aed769.png)
![image](https://user-images.githubusercontent.com/71070045/178541611-68e91c56-b608-4a02-82c5-cda67882811c.png)
![image](https://user-images.githubusercontent.com/71070045/178541635-19a31a8f-cdbb-4504-b6ec-29ba3322083b.png)
![image](https://user-images.githubusercontent.com/71070045/178541652-6ac74e93-2090-4bc7-9e8c-3132d81867ca.png)

**Comment by GermanBluefox** [comment]
@AlCalzone es ist doch irgendwas mit Typings. Oder?
