### ISSUE TITLE
Canceling of Anonymous Jobs

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#1071]
I get these log entries without any hint about what to check:

<html><body>

javascript.0 | 2022-07-13 07:45:39.195 | error | config production Use `--omit=dev` instead.
-- | -- | -- | --
javascript.0 | 2022-07-13 07:45:39.189 | error | WARN
javascript.0 | 2022-07-13 07:45:39.187 | error |  
javascript.0 | 2022-07-13 07:45:39.184 | error | npm
javascript.0 | 2022-07-13 07:45:30.379 | error | Error by canceling scheduled job "<Anonymous Job 9 2022-07-07T17:22:11.219Z>"
javascript.0 | 2022-07-13 07:45:30.379 | error | Error by canceling scheduled job "<Anonymous Job 8 2022-07-07T17:22:11.212Z>"
javascript.0 | 2022-07-13 07:45:30.378 | error | Error by canceling scheduled job "<Anonymous Job 7 2022-07-07T17:22:11.197Z>"
javascript.0 | 2022-07-13 07:45:30.378 | error | Error by canceling scheduled job "<Anonymous Job 6 2022-07-07T17:22:11.121Z>"
javascript.0 | 2022-07-13 07:45:30.376 | error | Error by canceling scheduled job "<Anonymous Job 5 2022-07-07T17:22:11.018Z>"
javascript.0 | 2022-07-13 07:45:30.376 | error | Error by canceling scheduled job "<Anonymous Job 4 2022-07-07T17:22:11.006Z>"
javascript.0 | 2022-07-13 07:45:30.376 | error | Error by canceling scheduled job "<Anonymous Job 3 2022-07-07T17:22:11.005Z>"
javascript.0 | 2022-07-13 07:45:30.376 | error | Error by canceling scheduled job "<Anonymous Job 2 2022-07-07T17:22:10.970Z>"
javascript.0 | 2022-07-13 07:45:30.373 | error | Error by canceling scheduled job "<Anonymous Job 1 2022-07-07T17:22:10.799Z>"

</body>
</html>

**Comment by Apollon77** [comment]
duplicate #1102
