### ISSUE TITLE
Syntax Hihlighting funktioniert nicht mehr

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/ioBroker.javascript#1074]
**Describe the bug**  
Seit Update auf 5.8.8 ist das Syntax Hihglighting verschwunden
![grafik](https://user-images.githubusercontent.com/9537962/178942816-bdac5bd2-d711-4bbf-86a4-e7090d140f2a.png)

**Versions:**  
 - Adapter version: 5.8.8
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: linux
 - Browser: Firefox + chrome on linux

**Comment by Diginix** [comment]
same here

**Comment by arteck** [comment]
5,8,9 same

**Comment by klein0r** [comment]
I planned to fix the issue today, but in my dev environment (build with ``craco``) everything works like expected. I have no idea why the production build doesn't work.

<img width="1488" alt="Screenshot 2022-07-15 at 08 07 58" src="https://user-images.githubusercontent.com/1959049/179161871-0a90dbdf-a677-4ce1-8e15-34dfa975d5b3.png">
