### ISSUE TITLE
use --omit=dev

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#1075]
New version 5,8.9 gives this error in the logfile:

<html><body>

javascript.0 | 2022-07-15 06:56:45.132 | error | WARN config production Use `--omit=dev` instead.
-- | -- | -- | --
javascript.0 | 2022-07-15 06:56:45.130 | error | npm

</body>
</html>

**Comment by Apollon77** [comment]
This seems to be nopm changes in general... I also have many such logs since update to a latest npm 8

**Comment by daniel-lo** [comment]
is there some magic to get rid of this?

**Comment by Apollon77** [comment]
not looked into it so far

**Comment by daniel-lo** [comment]
take your time :-)

**Comment by klein0r** [comment]
Duplicate of #1071 ?

**Comment by daniel-lo** [comment]
@klein0r 

Don't think so .. just happens to appear in that log but is not related to the topic
