### ISSUE TITLE
coffee-script modul wurde nicht gefunden

### ISSUE THREAD

**Issue by Revilo91** [ioBroker/ioBroker.javascript#1076]
Hallo, 

leider geht in der aktuellsten Version (5.8.10) gar nichts mehr:

![image](https://user-images.githubusercontent.com/39066472/179293803-6bf9f879-341a-452f-abcf-99eb07c04c6f.png)

**Comment by Knallix** [comment]
Habe die gleichen Fehler .
Bin zurück auf 5.8.7 läuft erstmal wieder.

**Comment by Grothesk242** [comment]
Kann ich nicht bestätigen, hier rennt alles wie immer. 
```
echad@chet:/opt/iobroker $ npm ls coffee-script coffeescript
iobroker.inst@3.0.0 /opt/iobroker
└─┬ iobroker.javascript@5.8.10
  ├─┬ coffee-compiler@0.3.2
  │ └── coffee-script@1.12.7 deduped
  ├── coffee-script@1.12.7
  └── coffeescript@1.12.7

echad@chet:/opt/iobroker $ npm -v
8.13.2
```

**Comment by Diginix** [comment]
With npm 6 and node 14 no problem on my system:
![image](https://user-images.githubusercontent.com/39678667/179369038-a2207959-8501-45ef-822f-39464893495f.png)

**Comment by CommanderXXL** [comment]
Ich schliesse mich mal den "läuft NICHT" reports an. Auch 5.8.9 ging bei mir nicht. Ich bin ebenfalls auf 5.8.7 zurück wie @Knallix und damit startet er wieder. Node is 14.20.

![image](https://user-images.githubusercontent.com/49292478/179371758-8121b3b9-547f-41ee-a396-1d4a228de991.png)

**Comment by tmycgn** [comment]
Kann ebenfalls selben Fehler sowie ein Funktionieren nach Downgrade auf 5.8.7 bestätigen. Danke für den Tipp.

**Comment by Grothesk242** [comment]
Vielleicht könnten die 'Hier geht nix'-Melder mal ihren npm tree bekannt machen. 
Ich vermute ja, da liegt einiges in der ersten Ebene.

**Comment by CommanderXXL** [comment]
Das wäre dann dieser hier: 
![image](https://user-images.githubusercontent.com/49292478/179391295-2be7e33b-2849-41a2-ba7a-1e531ede0692.png)

**Comment by Grothesk242** [comment]
Und mit der 5.8.10 schaut das wie aus? Denn bei diginix funktioniert es ja.

**Comment by CommanderXXL** [comment]
![image](https://user-images.githubusercontent.com/49292478/179391744-27819196-36ca-47b5-a8b0-dcaa43d32725.png)
Den Tree mit 5.8.10 kann ich erst heute Abend schicken da ich jetzt dringend aus dem Haus muss und das Update nicht mehr vorher schaffe. Sorry. Vielleicht kann es ja einer der anderen Reporter vorher machen.

**Comment by Anzic23** [comment]
5.8.10
Error: Cannot find module 'coffee-script'

**Comment by j1s2e3** [comment]
I have the same problem here.

I guess this is the problem:
**npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)**

iobroker.javascript depends on coffee-script, but the one with hyphen is deprecated. coffeescript without hyphen should be used, which in turn is already installed. So why iobroker.javascript depends on both, coffeescript **and** coffee-script???

**Comment by Grothesk242** [comment]
I'm sure you guys would face fewer problems if you would use the recommended nodejs16 / npm8 combination. 
npm>7 does manage peer deps. 

> So why iobroker.javascript depends on both, coffeescript and coffee-script???

It's a transgression.

**Comment by klein0r** [comment]
> So why iobroker.javascript depends on both, coffeescript **and** coffee-script???

Because the [coffee-compiler](https://github.com/alexgorbatchev/coffee-compiler) still uses ``coffee-script``. We should get rid of that dependency.

**Comment by Revilo91** [comment]
> Vielleicht könnten die 'Hier geht nix'-Melder mal ihren npm tree bekannt machen. Ich vermute ja, da liegt einiges in der ersten Ebene.

Hallo, 
sorry für die späte Rückmeldung. 

Hab manuell das `coffee-script` installiert, danach ging es auch wieder.


**_EN:_**

_Hello,_
_sorry for the late reply._

_Installed the `coffee-script` manually, after that it worked again._

**Comment by xdaamg** [comment]
Had same problem here with not working js-controller and errors about coffee-script/coffeescript with javascript-adapter. Downgrade to javascript-adapter 5.8.7 solved it at first. Then i updated again to javascript-adapter 5.8.10 and upgraded nodejs from 14 to 16 and npm from 6 to 8.  Javascipt-controller 4.0.23 and javascript-adapter 5.8.10 are working without problems now. No need to change/install coffeescript here.

**Comment by Grothesk242** [comment]
That's excactly what I was expecting. Running the recommended node/npm versions is the key.

**Comment by GermanBluefox** [comment]
Can we close it?

**Comment by Apollon77** [comment]
I would say yes ... with 6.0 it is gone in peace
