### ISSUE TITLE
JS-Controller startet nach Update auf 5.8.10 nicht

### ISSUE THREAD

**Issue by Kampfratte** [ioBroker/ioBroker.javascript#1077]
Guten morgen

habe gerade den JS-Controller auf die aktuellste Version 5.8.10 geupdatet und bekomme diesen dann nicht mehr zum laufen. Im Log habe ich folgende Meldungen:

host.iobroker | 2022-07-16 07:23:18.120 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: }
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: ]
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.javascript/main.js'
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: '/opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js',
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2022-07-16 07:23:18.120 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19) {
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js:7:10)
host.iobroker | 2022-07-16 07:23:18.119 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:746:27)
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.javascript/main.js
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: - /opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: Require stack:
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: Error: Cannot find module 'coffee-script'
host.iobroker | 2022-07-16 07:23:18.118 | error | Caught by controller[0]: ^
host.iobroker | 2022-07-16 07:23:18.117 | error | Caught by controller[0]: throw err;
host.iobroker | 2022-07-16 07:23:18.117 | error | Caught by controller[0]: internal/modules/cjs/loader.js:905

Bin dann wieder auf die 5.8.8 zurück und schon läuft der Adapter wieder.

**Comment by Apollon77** [comment]
duplicate #1076
