### ISSUE TITLE
Enhancement: Auto Completion 

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#108]
It would be a helpful feature to have an auto complete function in the JS Adapter

**Comment by Apollon77** [comment]
When you use js2fs Adapter and your own IDE it is very easy to achieve that with the typescript definition files and such, but for the web editor it will be hard I fear

**Comment by AlCalzone** [comment]
The [TypeScript playground](https://www.typescriptlang.org/play/) has such a feature, which uses the underlying TypeScript compiler features. It could be possible using the existing TypeScript infrastructure (now that we also have all definitions), but I have no clue how to combine that with the ACE editor.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/39673972-6774f8b4-5145-11e8-8e5b-a87d2f4abf66.png)

In the next version.

**Comment by AlCalzone** [comment]
Is that "just" a list of the predefined methods or more? Something like VSCode's IntelliSense would be super nice but as I said, no clue how to include that.

**Comment by AlCalzone** [comment]
Oh sh*t, Microsoft is awesome!
https://github.com/Microsoft/monaco-editor

**Comment by AlCalzone** [comment]
Related work in progress:
* https://github.com/AlCalzone/ioBroker.javascript/tree/better-editor
* #120, #121
