### ISSUE TITLE
Javascript Adapter - Ordner löschen.

### ISSUE THREAD

**Issue by hohmannc85** [ioBroker/ioBroker.javascript#1080]
Javascript Adapter - Ordner löschen.

Leider ist ein import fehlgeschlagen. es wurde nun ein ordner mit 2 Punkten am ende erstellt. ich kann ihn leider nicht löschen. auch umbenennen geht nicht, dann erstellte r nur einen zusätzlichen ordner. kann ich ihn irgendwie manuell in der ordner struktur löschen?

Danke!
![89220128-ACEF-4EB7-8FE0-BD4C98867751](https://user-images.githubusercontent.com/65295025/181928027-99ee50e5-01dd-442d-ab2e-db34bc8dafec.jpeg)
![CDECCFFE-6569-4CEB-86CE-4CF09B9554B8](https://user-images.githubusercontent.com/65295025/181928039-71c2a28b-5127-4762-a968-6f3e7a0c5ed3.jpeg)

**Comment by GermanBluefox** [comment]
You can manupulate scripts in objects
![image](https://user-images.githubusercontent.com/4582016/185594541-e1c51480-a082-4c64-9c9e-b1912be97d30.png)
Delete, rename should work

**Comment by hohmannc85** [comment]
It is a folder! 
i Had to edit objects.json to delete it manually
