### ISSUE TITLE
Changes in Blockly Script wont get saved.

### ISSUE THREAD

**Issue by ymurawski** [ioBroker/ioBroker.javascript#1100]
**Describe the bug**  
Hi, for days now, when i try to change something in my Blockly Scripts, it takes so long to get "saved". Most time it wont get saved and the values changes back to the old.
Already tried deleting cookies and node.js 16.... but always the same :(

here is a video where you can see that all the new Files changes back to the orignal ones after minutes of waiting and then loading the logs takes also so long.

[https://youtu.be/15ffp_nk6eY](url)

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
`<html>
<body>

javascript.0 | 2022-08-15 11:37:02.503 | info | Watch /home/iobroker/ioBroker-Scripts/
-- | -- | -- | --
javascript.0 | 2022-08-15 11:37:02.502 | info | Watch /home/iobroker/ioBroker-Scripts/Zigbee_Steuerung/
javascript.0 | 2022-08-15 11:37:02.500 | info | Watch /home/iobroker/ioBroker-Scripts/Telegram/
javascript.0 | 2022-08-15 11:37:02.498 | info | Watch /home/iobroker/ioBroker-Scripts/Datenpunkte/
javascript.0 | 2022-08-15 11:37:02.497 | info | Watch /home/iobroker/ioBroker-Scripts/Datenpunkte/Energiemessung/
javascript.0 | 2022-08-15 11:37:02.494 | info | Watch /home/iobroker/ioBroker-Scripts/Datenpunkte/Alexa_Shorts/
javascript.0 | 2022-08-15 11:37:02.491 | info | Watch /home/iobroker/ioBroker-Scripts/Beleuchtung/
javascript.0 | 2022-08-15 11:37:02.486 | info | Watch /home/iobroker/ioBroker-Scripts/Audio/
javascript.0 | 2022-08-15 11:37:02.362 | info | script.js.Datenpunkte.Alexa_Shorts.Musik_AUS_nach_45min: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.354 | info | Start javascript script.js.Datenpunkte.Alexa_Shorts.Musik_AUS_nach_45min
javascript.0 | 2022-08-15 11:37:02.353 | info | script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_Ventilator: registered 2 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.343 | info | Start javascript script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_Ventilator
javascript.0 | 2022-08-15 11:37:02.322 | info | script.js.Datenpunkte.Alexa_Shorts.Schlafzimmer_Routine_Ventilator: registered 2 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.314 | info | Start javascript script.js.Datenpunkte.Alexa_Shorts.Schlafzimmer_Routine_Ventilator
javascript.0 | 2022-08-15 11:37:02.313 | info | script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_TV: registered 2 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.303 | info | Start javascript script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_TV
javascript.0 | 2022-08-15 11:37:02.302 | info | script.js.Zigbee_Steuerung.Haustuer_Taster: registered 7 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.294 | info | Start javascript script.js.Zigbee_Steuerung.Haustuer_Taster
javascript.0 | 2022-08-15 11:37:02.292 | info | script.js.Telegram.Waschmaschine_Neu: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.284 | info | Start javascript script.js.Telegram.Waschmaschine_Neu
javascript.0 | 2022-08-15 11:37:02.283 | info | script.js.Telegram.Mikrowelle_Neu: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.276 | info | Start javascript script.js.Telegram.Mikrowelle_Neu
javascript.0 | 2022-08-15 11:37:02.275 | info | script.js.Telegram.Herd_Neu: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.267 | info | Start javascript script.js.Telegram.Herd_Neu
javascript.0 | 2022-08-15 11:37:02.266 | info | script.js.Telegram.Geschirspueler_Neu: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.259 | info | Start javascript script.js.Telegram.Geschirspueler_Neu
javascript.0 | 2022-08-15 11:37:02.258 | info | script.js.Telegram.Abwesenheit_Kamerabilder_Neu: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.250 | info | Start javascript script.js.Telegram.Abwesenheit_Kamerabilder_Neu
javascript.0 | 2022-08-15 11:37:02.250 | info | script.js.Datenpunkte.Energiemessung.Stromverbrauch_in_Euro: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.242 | info | Start javascript script.js.Datenpunkte.Energiemessung.Stromverbrauch_in_Euro
javascript.0 | 2022-08-15 11:37:02.241 | info | script.js.Datenpunkte.Energiemessung.Stromverbrauch_aktuell: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.207 | info | Start javascript script.js.Datenpunkte.Energiemessung.Stromverbrauch_aktuell
javascript.0 | 2022-08-15 11:37:02.206 | info | script.js.Datenpunkte.Energiemessung.Stromverbrauch_Gesamt: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.197 | info | Start javascript script.js.Datenpunkte.Energiemessung.Stromverbrauch_Gesamt
javascript.0 | 2022-08-15 11:37:02.196 | info | script.js.Beleuchtung.WZ_Deckenlicht_Dämmerung_bei_TV: registered 1 subscription, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2022-08-15 11:37:02.085 | info | Start javascript script.js.Beleuchtung.WZ_Deckenlicht_Dämmerung_bei_TV
javascript.0 | 2022-08-15 11:37:01.440 | info | received all states
javascript.0 | 2022-08-15 11:37:00.501 | info | received all objects
javascript.0 | 2022-08-15 11:36:52.330 | info | requesting all objects
javascript.0 | 2022-08-15 11:36:52.328 | info | requesting all states
javascript.0 | 2022-08-15 11:36:48.226 | debug | Loaded TypeScript definitions for request: ["node_modules/@types/request/package.json","node_modules/@types/request/index.d.ts"]
javascript.0 | 2022-08-15 11:36:48.193 | debug | Loaded TypeScript definitions for node: ["node_modules/@types/node/package.json","node_modules/@types/node/index.d.ts","node_modules/@types/node/assert.d.ts","node_modules/@types/node/assert/strict.d.ts","node_modules/@types/node/globals.d.ts","node_modules/@types/node/async_hooks.d.ts","node_modules/@types/node/buffer.d.ts","node_modules/@types/node/child_process.d.ts","node_modules/@types/node/cluster.d.ts","node_modules/@types/node/console.d.ts","node_modules/@types/node/constants.d.ts","node_modules/@types/node/crypto.d.ts","node_modules/@types/node/dgram.d.ts","node_modules/@types/node/diagnostics_channel.d.ts","node_modules/@types/node/dns.d.ts","node_modules/@types/node/dns/promises.d.ts","node_modules/@types/node/domain.d.ts","node_modules/@types/node/events.d.ts","node_modules/@types/node/fs.d.ts","node_modules/@types/node/fs/promises.d.ts","node_modules/@types/node/http.d.ts","node_modules/@types/node/http2.d.ts","node_modules/@types/node/https.d.ts","node_modules/@types/node/inspector.d.ts","node_modules/@types/node/module.d.ts","node_modules/@types/node/net.d.ts","node_modules/@types/node/os.d.ts","node_modules/@types/node/path.d.ts","node_modules/@types/node/perf_hooks.d.ts","node_modules/@types/node/process.d.ts","node_modules/@types/node/punycode.d.ts","node_modules/@types/node/querystring.d.ts","node_modules/@types/node/readline.d.ts","node_modules/@types/node/readline/promises.d.ts","node_modules/@types/node/repl.d.ts","node_modules/@types/node/stream.d.ts","node_modules/@types/node/stream/promises.d.ts","node_modules/@types/node/stream/consumers.d.ts","node_modules/@types/node/stream/web.d.ts","node_modules/@types/node/string_decoder.d.ts","node_modules/@types/node/test.d.ts","node_modules/@types/node/timers.d.ts","node_modules/@types/node/timers/promises.d.ts","node_modules/@types/node/tls.d.ts","node_modules/@types/node/trace_events.d.ts","node_modules/@types/node/tty.d.ts","node_modules/@types/node/url.d.ts","node_modules/@types/node/util.d.ts","node_modules/@types/node/v8.d.ts","node_modules/@types/node/vm.d.ts","node_modules/@types/node/wasi.d.ts","node_modules/@types/node/worker_threads.d.ts","node_modules/@types/node/zlib.d.ts","node_modules/@types/node/globals.global.d.ts"]
javascript.0 | 2022-08-15 11:36:48.061 | info | starting. Version 6.0.0 (non-npm: ioBroker/ioBroker.javascript) in /opt/iobroker/node_modules/iobroker.javascript, node: v18.7.0, js-controller: 4.0.23
javascript.0 | 2022-08-15 11:36:47.388 | debug | Plugin sentry Initialize Plugin (enabled=true)
javascript.0 | 2022-08-15 11:36:46.524 | debug | States connected to redis: 127.0.0.1:9000
javascript.0 | 2022-08-15 11:36:46.308 | debug | States create User PubSub Client
javascript.0 | 2022-08-15 11:36:46.305 | debug | States create System PubSub Client
javascript.0 | 2022-08-15 11:36:46.200 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
javascript.0 | 2022-08-15 11:36:46.048 | debug | Objects connected to redis: 127.0.0.1:9001
javascript.0 | 2022-08-15 11:36:46.037 | debug | Objects client initialize lua scripts
javascript.0 | 2022-08-15 11:36:45.666 | debug | Objects create User PubSub Client
javascript.0 | 2022-08-15 11:36:45.664 | debug | Objects create System PubSub Client
javascript.0 | 2022-08-15 11:36:45.552 | debug | Objects client ready ... initialize now
javascript.0 | 2022-08-15 11:36:45.180 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
javascript.0 | 2022-08-15 11:36:38.624 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
javascript.0 | 2022-08-15 11:36:38.624 | debug | Plugin sentry destroyed
javascript.0 | 2022-08-15 11:36:38.622 | info | terminating
javascript.0 | 2022-08-15 11:36:38.614 | info | Stop script script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_TV
javascript.0 | 2022-08-15 11:36:38.613 | info | Stop script script.js.Datenpunkte.Alexa_Shorts.Musik_AUS_nach_45min
javascript.0 | 2022-08-15 11:36:38.613 | info | Stop script script.js.Datenpunkte.Alexa_Shorts.Wohnzimmer_Routine_Ventilator
javascript.0 | 2022-08-15 11:36:38.612 | info | Stop script script.js.Datenpunkte.Alexa_Shorts.Schlafzimmer_Routine_Ventilator
javascript.0 | 2022-08-15 11:36:38.611 | info | Stop script script.js.Zigbee_Steuerung.Haustuer_Taster
javascript.0 | 2022-08-15 11:36:38.611 | info | Stop script script.js.Telegram.Waschmaschine_Neu
javascript.0 | 2022-08-15 11:36:38.610 | info | Stop script script.js.Telegram.Mikrowelle_Neu
javascript.0 | 2022-08-15 11:36:38.609 | info | Stop script script.js.Telegram.Herd_Neu
javascript.0 | 2022-08-15 11:36:38.608 | info | Stop script script.js.Telegram.Geschirspueler_Neu
javascript.0 | 2022-08-15 11:36:38.606 | info | Stop script script.js.Telegram.Abwesenheit_Kamerabilder_Neu
javascript.0 | 2022-08-15 11:36:38.606 | info | Stop script script.js.Datenpunkte.Energiemessung.Stromverbrauch_in_Euro
javascript.0 | 2022-08-15 11:36:38.605 | info | Stop script script.js.Datenpunkte.Energiemessung.Stromverbrauch_aktuell
javascript.0 | 2022-08-15 11:36:38.605 | info | Stop script script.js.Datenpunkte.Energiemessung.Stromverbrauch_Gesamt
javascript.0 | 2022-08-15 11:36:38.603 | info | Stop script script.js.Beleuchtung.WZ_Deckenlicht_Dämmerung_bei_TV
javascript.0 | 2022-08-15 11:36:38.600 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>`

**Versions:**  
 - Adapter version: 6.0.0
 - JS-Controller version: 4.0.23
 - Node version: 17.9.0
 - Ubuntu Raspberry Pi 4

**Comment by GermanBluefox** [comment]
Which javascript version is that? Node.js plays no role. It is important what is written in the browser console.

**Comment by tigerlampe** [comment]
hab fast das gleiche problem nur das es bei mir dann irgendwann der neu eingefügt block einfach verschwindet dauert aber auch teilweise bis zu 1 min   
Adapter: 6.0.3
Node.js v16.18.1
NPM: 8.19.2
JS-Controller 4.0.23
admin: 6.2.23
Ubuntu 20.04.5 LTS

**Comment by com1992** [comment]
gleiche hier bei mir
Adapter: 6.0.3
RAM: 3.7 GB
Node.js: v16.18.1
NPM: 8.19.2

**Comment by klein0r** [comment]
Not reproducible anymore (please report if the issue is still present in current versions)
