### ISSUE TITLE
global script with function crashes typescript compiler

### ISSUE THREAD

**Issue by dpolakovics** [ioBroker/ioBroker.javascript#1106]
**Describe the bug**  
When a function is declared in a global typescript, the compiler crashes with the following message:
`Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
Testing script is
`function test(): void {
    log("test global");
}`

**To Reproduce**  
1. Create a global typescript with a function declared
2. Save
3. Eventually restart adapter
4. Crash on compiling typescript

**Expected behavior**  
Typescript should be compiled and work.

**Screenshots & Logfiles**  
The complete errors:
`Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
`unhandled promise rejection: Debug Failure. Unhandled SyntaxKind: Unknown.`
`

  | Error: Debug Failure. Unhandled SyntaxKind: Unknown.     at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:113075:22)     at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:112608:17)     at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:116249:13)     at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:112548:13)     at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:112521:13)     at emitFunctionDeclarationOrExpression (/opt/iobroker/node_modules/typescript/lib/typescript.js:114272:13)     at emitFunctionDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:114267:13)     at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:112789:32)     at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:112608:17)     at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:116249:13)     at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:112548:13)     at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:112521:13)     at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:116742:9)     at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:115493:17)     at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:115411:17)     at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:115376:13)     at emitSourceFileWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:115062:13)     at emitBodyWithDetachedComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:116369:17)     at emitSourceFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:114981:17)     at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:112623:24)     at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:112608:17)     at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:112548:13)     at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:112484:13)     at writeFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:112468:13)     at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:112329:13)     at Object.printNode (/opt/iobroker/node_modules/typescript/lib/typescript.js:112313:62)     at transformScriptBeforeCompilation (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:442:31)     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:1033:67)     at processImmediate (internal/timers.js:466:21)
-- | --
`
`Debug Failure. Unhandled SyntaxKind: Unknown.`

**Versions:**  
 - Adapter version: 6.0.0
 - JS-Controller version: 4.0.23
 - Node version: 14.20
 - Operating system: linux

**Additional context**

**Comment by Apollon77** [comment]
@AlCalzone any idea?

**Comment by dpolakovics** [comment]
Just to clarify, i did a quick test with JavaScript in global folder and that works.
So it just applies to global typescript.

**Comment by AlCalzone** [comment]
I'll try to debug tomorrow. I've definitely written global TS scripts with functions before.

**Comment by dpolakovics** [comment]
Thanks, in the meanwhile just rewriting everything global to JavaScript worked for me.
For everyone with the same problem looking for a quick fix.

**Comment by AlCalzone** [comment]
This is caused by TypeScript 4.8. Downgrading the dependency to ~4.7 fixes the issue. I'll open a PR.

**Comment by Diginix** [comment]
Kann es sein dass auch globale Blocklys seit v6 die Instanz crashen?

**Comment by Apollon77** [comment]
bisher nichts bekannt

**Comment by Diginix** [comment]
Stimmt, eben bei mir nochmal getestet und funktioniert. Die Instanz wird nur initial neu gestartet damit das Skript überall bekannt ist. Das hatte mich kurz irritiert.
