### ISSUE TITLE
Debugger unter JS 6.0.0 nicht mehr aktiv

### ISSUE THREAD

**Issue by marian-t-web-de** [ioBroker/ioBroker.javascript#1129]
**Describe the bug**  
Nach JS Update zu ver. 6.0.0  lassen sich die Javascripts zwar in Debuggermodus versetzen, die Debugger-Funktionstasten (Start, nächste Zeile etc.) scheinen ohne Funktion zu sein, es können auch - z.B. mit Maus - keine Breakpoints gesetzt werden .

**To Reproduce**  
1. Go to Javascript
2. Click on Expertenmodus, dann "Käfer"
3. "Script läuft nicht" erscheint
4. Betätige eine der Debugger-Funktionstasten Start, nächste Zeile o.a.
5. Es folgt keine Aktion
6. Klick auf den linken Rand - es wird kein Breakpoint erstellt

**Expected behavior**  
Die Debugger funktioniert, die Breakpoints lassen sich setzen.

**Screenshots & Logfiles**  
Screenshot:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/37208979/188736307-ff9a2dd9-807e-4a71-b779-bb2ee3f7c334.png">

**Versions:**  
raspberrypi 
Betriebssystem linux
Architektur arm
Node.js v12.22.8 (Es gibt eine neuere Version: v12.22.12 - Empfohlene Version v16.17.0)
NPM 6.14.15
JS 6.0.0
**Additional context**  
Zurücksetzen des JS-Adaptes auf 5.8 endet mit fehlerhaften npm-Rebuild, sodass kann ich die JS-Version 5.8 nicht in dieser Hinsicht testen.

**Comment by marian-t-web-de** [comment]
Eine Neuinstallation von iObroker mit JS 6.0.0 auf einem zweitem Raspi bestätigt den Bug: Debbuger ist ohne Funktion.

**Comment by marian-t-web-de** [comment]
Hallo,

es sind über sieben Wochen vergangen, der Bug bleibt unangetastet.
 
Schade dass man die Software nicht mehr pflegt, nicht mal die gemeldeten Bugs werden angegangen.

Somit ist die JS 6.0.0 nicht nur für mich nur eine "Verschlimmbesserung"  ohne sichtbaren Vorteile.

Wirklich schade.

**Comment by Apollon77** [comment]
Schon mal auf die Idee gekommen das es noch andere Adapter gibt die betreut werden wollen und ggf andere Prioritäten der Open Source Entwickler die das in Ihrer Freizeit tun?

**Comment by GermanBluefox** [comment]
Please check 6.1.0

**Comment by marian-t-web-de** [comment]
Nach JS Update zu ver. 6.1.3 sind die Debugger-Funktionstasten inkl. Breakpoints funktionsfähig.

Allerdings ein erneutes Versetzen in Debugger-Modus endet mit "Fehler: invalid response code: 1". 
Das gilt dann für alle Scripts.

Erneutes Debuggen ist nach iObroker-Restart - einmalig - möglich, danach Fehlermeldung s.o.
