### ISSUE TITLE
TypeScript global functions crash again - TS was upgraded to 4.8 however it should stay 4.7

### ISSUE THREAD

**Issue by reztamas** [ioBroker/ioBroker.javascript#1132]
**Describe the bug**

TypeScript global functions crash again
It was described in this issue: https://github.com/ioBroker/ioBroker.javascript/issues/1106

It has been fixed on 28.9 with this commit by downgrading the TypeScript from 4.8 to 4.7:
https://github.com/ioBroker/ioBroker.javascript/pull/1107

However on 1.9 this modification upgraded from 4.7.4 to 4.8.2 again which caused the same failure with TypeScript global functions:
https://github.com/ioBroker/ioBroker.javascript/commit/36959b21ac0d4e54d4bd6b54ffb882c0b77358e1

**Expected behavior**

TypeScript global functions should not crash

**Suggested solution**

Downgrade TypeScript to 4.7

**Comment by Apollon77** [comment]
Yes fix will come soon ...

**Comment by Apollon77** [comment]
6.0.2 on it's way to Beta

**Comment by ScumbagSteve** [comment]
I think this could be unpinned
