### ISSUE TITLE
TS Definition compareTime is incomplete

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#114]
The current TS definition for compareTime only allows 4 parameter.

https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/en/javascript.md#comparetime

Docs say that last parameter is optional: 
> If timeToCompare is not given, so the actual time will be used.

**Comment by Apollon77** [comment]
@AlCalzone thank you for checking :-)

**Comment by AlCalzone** [comment]
Besides fixing the optional parameter, I also changed the definition of the params to 
```ts
string | number | Date | iobJS.AstroDate
```
Hope I did not miss another case this time.

**Comment by Hypnos3** [comment]
Wo wir gerade dabei sind:
Um eine Instanz eines Adapters zu starten/Stoppen, gibt es ja die Eigenschaft "enabled".

```
// Stop instance
extendObject('system.adapter.sayit.0', {common: {enabled: false}});
```
Die Eigenschaft finde ich leider nirgends in der javascript.d.ts.
```
/** Extend an object and create it if it might not exist */
	function extendObject(id: string, objPart: iobJS.PartialObject, callback?: iobJS.SetObjectCallback): void;
```

Ich bin mir leider auch nicht sicher was eine Instanz für ein Objekttyxyp ist:

`type PartialObject = PartialStateObject | PartialChannelObject | PartialDeviceObject | PartialOtherObject;`
