### ISSUE TITLE
Set state not able to set object data (example: common.name)

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.javascript#1147]
**Describe the bug**  
It is possible to get object.common.name via getObject. setState is not able to set object data (example: common.name).

**To Reproduce**  
1. open adapter
2. try to set object.common.name via setState

**Expected behavior**  
Set the state.

**Screenshots & Logfiles**  

![image](https://user-images.githubusercontent.com/113902279/191478847-cc0e89d6-f62a-4dec-aeb2-7249362c7626.png)

**Versions:**  
 - Adapter version: 6.0.3
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Debian 5.10.140-1

**Comment by Apollon77** [comment]
yes because to set object details you need to use setObject?! best post your issue in the scripting section in forum to get support

**Comment by pafade89** [comment]
Thank you very much for fast response. Sorry my fault, is of course self-explanatory.

Cheers
