### ISSUE TITLE
Skripte lassen sich nicht mehr löschen oder umbenennen

### ISSUE THREAD

**Issue by mbausm** [ioBroker/ioBroker.javascript#1151]
**Describe the bug** 

Skripte lassen sich nicht mehr löschen oder umbenennen. Es kommt eine Fehlermeldung:

Fehler Permission Error

**To Reproduce**  

- Im Adapter JS Skripte öffnen
- Skript anwählen
- Skript umbenennen
- Neuer Namen eingeben
- mit OK bestätigen

**Expected behavior**  

Adapter Updates:

	- Admin			        V 6.2.20	> V 6.2.22
	- SNMP			        V 2.1.7	> V 2.1.8
	- Alexa2		                V 3.11.2	> V 3.19.9
	- Cloud IoT-Verbindung	V 1.11.8	> V 1.11.9
	- JS Skript Adapter	        V 6.0.0	> V 6.0.3
	- Pushover		        V 3.0.2	> V 3.0.3

**Versions:**  

 - Adapter version: siehe oben
 - JS-Controller version: 4.0.23
 - Node version: 14.18.1
 - Operating system: Raspbian GNU Linux 10 (Buster)

**Additional context**  

Es haben scheinbar weitere User Probleme damit. Ein Downgrade auf V6.2.12 schafft scheinbar Abhilfe.
Siehe auch im Forum:

https://forum.iobroker.net/topic/58249/skript-l%C3%B6schen-geht-nicht-permissionerror/134?lang=de

**Comment by mbausm** [comment]
Hier noch ein Screenshot… 
![94D9F409-B66D-4BA4-9461-6C63EC32CFF7](https://user-images.githubusercontent.com/98892208/193330313-0f83c6b3-473f-4565-95b5-e7d3f9083b7f.jpeg)

**Comment by mbausm** [comment]
Schönen Guten Abend Zusammen,

ich habe eben auch mal getestet ein neues Objekt (Bool Variabel) anzulegen und anschließend wieder zu löschen. Auch hier kommt eine Fehlermeldung: **Cannot delete object: permissionError**

So haben auch einige User aus dem Forum berichtet.  Daher hatte ich auch ursprünglich den Beitrag unter dem ADMIN Adapter gepostet.

Hier noch ein Screenshot:

![2022 09 30 - Delete Object Permission Error](https://user-images.githubusercontent.com/98892208/193331652-eb9df272-12a3-4b55-9057-16a7c03e233a.PNG)

**Comment by mrjeschke** [comment]
Der Fehler kommt schon direkt nach einer Neuinstallation.
Getestet auf Proxmox LXC+VM
Außerdem nativ auf einem Raspi 3B+ mit Bullseye lite 32 und 64 Bit.
Keinerlei Fehler im Log oder im Browser-Log.
Beim Versuch ein State zu löschen, kommt im Browser-Log nur diese Fehler.
`<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(255, 255, 255); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://172.16.4.181:8081/static/node_modules/@sentry/src/instrument.ts:123" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">instrument.ts:123</span> <devtools-icon class="resource-links" title="Diese Nachricht im Web suchen" style="display: inline-block; white-space: nowrap; box-sizing: border-box; min-width: 0px; min-height: 0px; vertical-align: bottom; cursor: pointer;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/Images/edge-search-info.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--color-link));"></div></devtools-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color)  !important;">Cannot delete object: permissionError</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(255, 255, 255); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonym) | @ | instrument.ts:123
-- | -- | -- | --
  | window.alert | @ | App.jsx:294
  | (anonym) | @ | Objects.jsx:97
  | Promise.catch (asynchron) |   |  
  | onDelete | @ | Objects.jsx:97
  | onClick | @ | Objects.jsx:153
  | ga | @ | react-dom.production.min.js:54
  | ka | @ | react-dom.production.min.js:54
  | Sa | @ | react-dom.production.min.js:55
  | Po | @ | react-dom.production.min.js:105
  | To | @ | react-dom.production.min.js:106
  | (anonym) | @ | react-dom.production.min.js:117
  | ou | @ | react-dom.production.min.js:274
  | Ou | @ | react-dom.production.min.js:52
  | oi | @ | react-dom.production.min.js:109
  | Ql | @ | react-dom.production.min.js:74
  | ja | @ | react-dom.production.min.js:73
  | Z1 | @ | helpers.ts:95

</span></div>
</body>
</html>`

**Comment by mbausm** [comment]
Habe mal probeweise die Berechtigungen geändert:

![2022 09 30 - Permissions](https://user-images.githubusercontent.com/98892208/193333405-8a3324c9-7ba4-4b6b-8050-7d61cf84e44f.PNG)

Freigabe für Alle User:

![2022 09 30 - Permissions All User](https://user-images.githubusercontent.com/98892208/193333452-46d59d84-6a0b-47a1-8c01-bcc2b3211630.PNG)

Browserverlauf zuvor nochmals gelöscht. Trotzdem kann das Objekt nicht mehr gelöscht werden:

![2022 09 30 - Permissions Denied](https://user-images.githubusercontent.com/98892208/193333581-428a6e40-5949-43a9-97ca-215c3630ea95.PNG)

**Comment by mrjeschke** [comment]
Man kann aber ein Verzeichnis mit allen darin enthaltenen States löschen.

**Comment by mbausm** [comment]
Danke für den Hinweis, scheint ein Bug in der Berechtigungsverwaltung zu sein.

**Comment by lessthanmore1** [comment]
Gleiches gilt auch für die Aufzählungen. 
Ein Löschen einer Funktion (enum) ist nicht möglich. 
`Cannot delete enum: permissionError `

**Comment by klein0r** [comment]
Komisch, ich habe die gleichen Versionen im Einsatz und bei mir läuft alles.
Neu erstellen und löschen von Scripts, Enums usw. alles kein Problem.

Ich hatte es aber neulich auch in einer Neuinstallation (per Dev-Server), dass ich ein enum nicht löschen konnte.

**Comment by mrjeschke** [comment]
In meinem Produktivsystem habe ich auch keine Probleme. (Erst vor ca. 2 Wochen aus Backup neu installiert)
Alle Versionen aktuelle Beta.
Aber jeder Versuch einer Neuinstallation endet sofort mit diesem Fehler.
Getestet auf Proxmox, nativ Raspi und jetzt auch Docker.
Das mit der CLI kann ich erst später testen, bin noch auf Schicht.

**Comment by mrjeschke** [comment]
Löschen einen Objekts per CLI klappt.

**Comment by mrjeschke** [comment]
![1](https://user-images.githubusercontent.com/71946366/193672889-7d4a3739-4d0f-4d0e-8f06-2e424dd05177.png)

`
pi@testpi:~$ iobroker object del 0_userdata.0.TestState2

The object "0_userdata.0.TestState2" was deleted.
pi@testpi:~$
`

![2](https://user-images.githubusercontent.com/71946366/193673173-8f9b72ea-b34d-425b-9c0c-588dcfb1e164.png)

**Comment by mbausm** [comment]
Guten Morgen,

löschen von Objekten funktioniert bei mir auch im Command Line Interface:

![2022 10 04 - ioBroker del object at cli](https://user-images.githubusercontent.com/98892208/193765731-8839f6a8-1f5c-4a5b-aad3-5cb6668e6001.PNG)

**Comment by klein0r** [comment]
Dokumentation meiner Suche bisher:

Da das Problem sowohl den JavaScript-Adapter betrifft, als auch den Admin. Ging ich davon aus, dass Problem in der Library zu finden ist, welche beide verwenden: ``@iobroker/adapter-react-v5``

- Der JavaScript-Adapter nutzt in Version 6.0.3 die [Version 3.1.34](https://github.com/ioBroker/ioBroker.javascript/blob/16074faed20aa4b454533b8defec8b40919cc067/src/package.json#L7)
- Der Admin-Adapter nutzt in Version 6.2.22 die [Version 3.1.34](https://github.com/ioBroker/ioBroker.admin/blob/865602ac7d747c6784f7247ce73ab1cc0dd00346/src-rx/package.json#L10)

1. Version 6.0.1 vom JavaScript-Adapter nutzt noch [3.1.20](https://github.com/ioBroker/ioBroker.javascript/blob/9f30d43e14ff8e86d89860be50d1a4f4e15e2905/src/package.json#L7)
2. Version 6.2.20 vom Admin-Adapter nutzt noch [3.1.33](https://github.com/ioBroker/ioBroker.admin/blob/e57550171cb9acdb4742a242dc4fbc8024b31ba4/src-rx/package.json#L10)

**Leider wird das Problem auch mit einem Downgrade auf diese Versionen nicht behoben.** Es muss also wo anders liegen

----

### Objekte

Da es auf meinem Live-System geht und auf einer Neuinstallation nicht, habe ich die Objekte verglichen:

- ``system.group.administrator`` - identisch
- ``system.user.admin`` - identisch
- ``system.config``:

```json
    "defaultNewAcl": {
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator",
      "state": 1636
    }
```

Und produktiv:

```json
    "defaultNewAcl": {
      "object": 1636,
      "state": 1636,
      "file": 1632,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    },
```

Fehlen bei Euch in dem Objekt auch die Attribute ``object``, ``state`` und ``file``?

**Comment by klein0r** [comment]
**Habe das Problem gefunden!**

Es liegt an der Version von ``@iobroker/socket-classes``. 0.5.3 funktioniert, 0.5.4 nicht mehr!

https://github.com/ioBroker/ioBroker.socket-classes/compare/v0.5.3...v0.5.4

Habe ein Upgrade auf 0.5.4 gemacht und jetzt kann ich auch keine Objekte mehr löschen. Yeah 😄 

Wenn man sich Commits dort anschaut, dann findet man ``(bluefox) Fixed error in delObjects method``. Klingt ja schon verdächtig, oder? Und scheinbar ist eher das Gegenteil der Fall. Suche weiter und mache einen Issue im richtigen Repo auf.

@GermanBluefox @Apollon77

**Comment by mbausm** [comment]
Danke für Eure Unterstützung!

**Comment by FreunderNacht** [comment]
Hi,
bei mir das selbe Problem:

![Fehler Skript löschen](https://user-images.githubusercontent.com/69077006/194703351-8a991ae0-9a63-442f-98d9-f022c052f61d.jpg)

Admin Version 6.2.22
JavaScript 6.0.3
Node.js 14.20.1
NPM 6.14.17

**Comment by ftrueck** [comment]
Ich kann bestätigen das das Löschen von Objekten nicht geht. In [ioBroker.socket-classes v0.5.3...v0.5.4](https://github.com/ioBroker/ioBroker.socket-classes/compare/v0.5.3...v0.5.4)
erlaubt die Funktion delObject nur noch das löschen von flot objekten. Bei allen anderen Objekten gibt sie permissionError zurück.

Es gibt noch die funktion deleteFile welche dateien im FileSystem löscht. Diese Funktion wirft keinen permissionError.

Meine Vermutung: Die JavaScripte werden auch wie Objekte behandelt und es wird versucht die delObject Funktion aufzurufen welche dafür nicht funktionieren kann.

**Comment by klein0r** [comment]
> erlaubt die Funktion delObject nur noch das löschen von flot objekten.

Der Admin hat seine eigene Commands und überschreibt einige Funktionen. Der [Filter](https://github.com/ioBroker/ioBroker.socket-classes/blob/0c2c780d4a19d3d60affaef87679f6c2a9acbf32/lib/socketCommands.js#L1204) auf ``flot.`` ist nur in der Basis-Klasse enthalten. Aber nicht in den ``socketCommandsAdmin``

Aber hier ist der falsch Ort um das zu diskutieren.

**Comment by emmpee** [comment]
Moin allerseits,

Frage von einem Noob: Wie bekomme ich die 1.01 von Bluefox auf mein System?

**Comment by klein0r** [comment]
> Wie bekomme ich die 1.01 von Bluefox auf mein System?

Indem Du auf eine neue Stable-Version vom Admin-Adapter wartest und nicht irgendwelche Pakete npm selbst installierst 😄

**Comment by emmpee** [comment]
Ah ja, hab ich verstanden 😊. Danke Dir.



Von: Matthias Kleine
Gesendet: Dienstag, 11. Oktober 2022 09:43
An: ioBroker/ioBroker.javascript
Cc: emmpee; Comment
Betreff: Re: [ioBroker/ioBroker.javascript] Skripte lassen sich nicht mehr löschen oder umbenennen (Issue #1151)

Wie bekomme ich die 1.01 von Bluefox auf mein System?
Indem Du auf eine neue Stable-Version vom Admin-Adapter wartest und nicht irgendwelche Pakete npm selbst installierst 😄

**Comment by klein0r** [comment]
Nach Update auf Admin 6.2.23 funktioniert das löschen bei mir wieder.
Hier kann also dich gemacht werden 👍

**Comment by mbausm** [comment]
Ich möchte auf die `stable` Freigabe warten. Hab es daher bisher noch nicht getestet. Sollte aber dann funktionieren. Danke nochmals!

**Comment by ChrWieg** [comment]
Super Arbeit, danke vielmals!

**Comment by basti2015** [comment]
Wann kommt denn die Stable ?

**Comment by mbausm** [comment]
Hallo,

habe es gestern, nachdem ich ein komplettes Backup erstellt habe, die `6.2.23` auf meinem Live System installiert. Funktioniert wieder. Bisher keine Probleme festgestellt.

Dankeschön :-)
