### ISSUE TITLE
"echo" in exec() doesn't execute /bin/echo, but echo command of /bin/sh - confusing

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.javascript#1152]
### Test 1

When running ``echo -n -e "\x41"`` with bash, everything works like expected. Output is ``A``.

But if I use this script in JavaScript adapter (on the same system):

```javascript
exec(`echo -n -e "\\x41"`, async function (error, result, stderr) {
    console.log(result);
});
```

Output is ``-e \x41``

Why is the option -e added to the output and is not interpreted?!

----

### Test 2

When running ``/bin/echo -n -e "\x41"`` with bash, everything works like expected. Output is ``A``.

With this script in JavaScript adapter (on the same system):

```javascript
exec(`/bin/echo -n -e "\\x41"`, async function (error, result, stderr) {
    console.log(result);
});
```

The output is also ``A``. Whats the difference to Test 1? (``which echo`` returns ``/bin/echo`` in all cases)

----

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Debian Bullseye

**See:**

- https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processexeccommand-options-callback
- https://linux.die.net/man/1/echo

```
-n
    do not output the trailing newline
-e
    enable interpretation of backslash escapes
```

**Comment by Apollon77** [comment]
Also for security reasons you should always pass the full path to the executable you want to execute. In fact dependeing on the shell there might be the PATH env variable defined differently.

I'm not sure if this should be a "works as expected" :-)

**Comment by Apollon77** [comment]
I will update the documentation

**Comment by Apollon77** [comment]
And honestly ... we can also allow access to "options"
