### ISSUE TITLE
enabled property is missing

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.javascript#116]
Um eine Instanz eines Adapters zu starten/Stoppen, gibt es ja die Eigenschaft "enabled".
[Aus der Dokumentation:](https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/en/javascript.md#extendObject)
```
// Stop instance
extendObject('system.adapter.sayit.0', {common: {enabled: false}});
```

Die Eigenschaft "enabled" finde ich leider nirgends in der javascript.d.ts, daher lässt sich sowas in Typescript nicht definieren.

```
/** Extend an object and create it if it might not exist */
	function extendObject(id: string, objPart: iobJS.PartialObject, callback?: iobJS.SetObjectCallback): void;
```

Ich bin mir leider auch nicht sicher was eine "Instanz" für ein Objekt-typ ist, also wo das enabled hingehören würde:
`type PartialObject = PartialStateObject | PartialChannelObject | PartialDeviceObject | PartialOtherObject;`

**Comment by AlCalzone** [comment]
Das sollte unter `PartialOtherObject` zusammengefasst sein. Hatte einen Copy&Paste-Fehler, bei dem das zugehörige common-Objekt nicht mit verknüpft war.

**Comment by Hypnos3** [comment]
Danke!
