### ISSUE TITLE
directory from script within the hover tip of script

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.javascript#1162]
Is it possible to get the script directory (whole directory path)  from the script within the hover tip:
![image](https://user-images.githubusercontent.com/84818934/193393377-5bdf5bf5-cf60-40d7-a120-a7ad82fa3990.png)
With a lot scripts in different directories sometimes i have to search a lot.
![image](https://user-images.githubusercontent.com/84818934/193393429-deda1698-0713-400a-91f5-37408f2ef77b.png)

Thank you.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/199687917-14dae64b-f963-4b8c-a870-73d63f203a5b.png)
Fixed in 6.1.1

**Comment by mcuiobroker** [comment]
Super. Passt. Danke.
