### ISSUE TITLE
start / stop script on the script TAB

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.javascript#1163]
left Script side
![image](https://user-images.githubusercontent.com/84818934/193393526-c507085c-016f-4c87-b3bf-d6edd046e42d.png)

TAB script
![image](https://user-images.githubusercontent.com/84818934/193393573-e8ded13b-945f-4229-a8b0-5ede85b4b4dd.png)

**Comment by Apollon77** [comment]
For my understanding: YOu have a feature reqwiuest to also add the option to pause the script and start the script to the Tab of the script in the editor? Right? (More context and description is always helpful beside images ...because sometimes images do not say 1000 words)

So the "restart script" Button that you have in the script tab is not sufficient? why?

**Comment by mcuiobroker** [comment]
The Problem ist, that i have 5 scripts parallel in the editor. Now, i want t stop one script, but i don't know directly where it is, because too much directories. So it would be helpful to have an button directly to script TAB, so i don't have to look at the directories, to stop there the right script.
TAB script
![image](https://user-images.githubusercontent.com/84818934/193412470-36adecdc-661e-4bd1-a3ee-42da8d30c630.png)
Folder (directories)
![image](https://user-images.githubusercontent.com/84818934/193412497-8ee210c0-097e-4588-8c4d-4500c27c9b96.png)

**Comment by Apollon77** [comment]
<img width="403" alt="Bildschirmfoto 2022-10-01 um 21 19 56" src="https://user-images.githubusercontent.com/11976694/193424996-5a128c20-721f-4ca7-a0f4-d67635f029d8.png">


The restart button (the arrow as circle) is exactly on the tab content ...

**Comment by mcuiobroker** [comment]
And to stop?

**Comment by Apollon77** [comment]
there only restart rught now ... but if I would think it makes sense to add also start/stop then this would be the place :-)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/199696469-1537d193-55d7-40cc-9266-6635bab6d033.png)
Added in 6.1.1

**Comment by mcuiobroker** [comment]
Super. Passt. Danke.
