### ISSUE TITLE
Error: Error on worker #1: Error: Debug Failure. Unhandled SyntaxKind: Unknown. at pipelineEmitWithHintWorker

### ISSUE THREAD

**Issue by RiturajKandiyal** [ioBroker/ioBroker.javascript#1165]
**Describe the bug**  
I am upgrading my Angular project from version 10.2.x to version 11. As per official angular update guide, when I run the command: -

> ng update @angular/core@11 @angular/cli@11 --allow-dirty --force

it throws following error: -

> Error: Error on worker #1: Error: Debug Failure. Unhandled SyntaxKind: Unknown.
> at pipelineEmitWithHintWorker (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:113127:22)
> at pipelineEmitWithHint (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112660:17)
> at pipelineEmitWithComments (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:116301:13)
> at pipelineEmit (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112600:13)
> at emit (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112573:13)
> at emitParameter (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:113364:13)
> at pipelineEmitWithHintWorker (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112709:32)
> at pipelineEmitWithHint (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112660:17)
> at pipelineEmitWithComments (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:116301:13)
> at pipelineEmit (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\typescript\lib\typescript.js:112600:13)
> at ClusterMaster.onWorkerMessage (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
> at C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
> at ClusterMaster. (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
> at step (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\tslib\tslib.js:140:27)
> at Object.next (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\tslib\tslib.js:121:57)
> at C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\tslib\tslib.js:114:75
> at new Promise ()
> at Object.__awaiter (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules\tslib\tslib.js:110:16)
> at EventEmitter. (C:\Reach code\Reach\Angular Upgrade\helix-responsive-app-FOR v11 NEW\reach-app\node_modules@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
> at EventEmitter.emit (events.js:315:20)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! reach-app@0.0.1 postinstall: ngcc
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the reach-app@0.0.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\rituraj.kandiyal\AppData\Roaming\npm-cache_logs\2022-09-30T13_19_55_670Z-debug.log
> × Packages installation failed, see above.

My package.json file looks like below after running the above update command: -

> "private": true,
> "dependencies": {
> "@agm/core": "3.0.0-beta.0",
> "@angular/animations": "11.2.14",
> "@angular/cdk": "11.2.13",
> "@angular/common": "11.2.14",
> "@angular/compiler": "11.2.14",
> "@angular/core": "11.2.14",
> "@angular/flex-layout": "9.0.0-beta.31",
> "@angular/forms": "11.2.14",
> "@angular/localize": "11.2.14",
> "@angular/material": "11.2.13",
> "@angular/platform-browser": "11.2.14",
> "@angular/platform-browser-dynamic": "11.2.14",
> "@angular/router": "11.2.14",
> "@ng-idle/core": "9.0.0-beta.1",
> "@ng-idle/keepalive": "9.0.0-beta.1",
> "@ngx-formly/core": "5.9.3",
> "@ngx-formly/material": "5.9.3",
> "@reachplatform/core": "1.0.0",
> "@types/googlemaps": "3.39.12",
> "angular2-moment": "1.9.0",
> "classlist.js": "1.1.20150312",
> "compression": "1.7.4",
> "concurrently": "5.3.0",
> "core-js": "3.6.5",
> "deprecated-decorator": "0.1.6",
> "dotenv": "8.2.0",
> "express": "4.17.1",
> "hammerjs": "2.0.8",
> "helmet": "4.1.0",
> "html2canvas": "1.0.0-rc.5",
> "jspdf": "2.3.1",
> "mime": "2.4.6",
> "morgan": "1.10.0",
> "ng-recaptcha": "5.0.0",
> "ngx-cookie-service": "10.0.1",
> "ngx-mask": "9.1.2",
> "ngx-pagination": "5.0.0",
> "ngx-trim-directive": "1.0.11",
> "nocache": "2.1.0",
> "rxjs": "6.6.2",
> "rxjs-compat": "6.6.2",
> "tslib": "^2.0.0",
> "web-animations-js": "2.3.2",
> "zone.js": "0.10.3"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "0.1102.19",
> "@angular-eslint/eslint-plugin": "0.0.1-alpha.32",
> "@angular/cli": "11.2.19",
> "@angular/compiler-cli": "11.2.14",
> "@angular/language-service": "11.2.14",
> "@compodoc/compodoc": "^1.1.11",
> "@types/jest": "^26.0.15",
> "@types/node": "^14.6.7",
> "@typescript-eslint/eslint-plugin": "^3.9.1",
> "@typescript-eslint/eslint-plugin-tslint": "^3.9.1",
> "@typescript-eslint/parser": "^3.9.1",
> "codelyzer": "^6.0.0",
> "eslint": "^7.7.0",
> "eslint-plugin-import": "^2.22.0",
> "jest": "^26.6.1",
> "jest-canvas-mock": "^2.3.0",
> "jest-preset-angular": "^8.3.2",
> "jest-sonar": "^0.2.11",
> "protractor": "~7.0.0",
> "ts-jest": "^26.4.3",
> "ts-node": "^9.0.0",
> "tslint": "~6.1.0",
> "typescript": "^4.1.6"
> }
> }

The command did upgrade required dependencies to version 11 but threw error too. I tried looking for a solution on internet, but didn't find much. After this when I run the mentioned command to upgrade angular-material, I see the version upgraded but also the same error again.

#bug #angular

**Expected behavior**  
Update command shall execute successfully without any errors.

**Versions:**  
 - Node version: 14.15
 - Operating system: Windows

**Comment by Apollon77** [comment]
What does this have to do with the ioBroker Javascript Adapter? Normally we do not use Angular atall here??
