### ISSUE TITLE
Double spaces are replaced.

### ISSUE THREAD

**Issue by Elke61** [ioBroker/ioBroker.javascript#1166]
The times should be sent to the thermostat via Blockly. To do this, I compile the times and temperatures by creating text. The thermostat requires two spaces between the individual switching processes (times). These are now replaced by a space in Blockly. The thermostat does not recognize this. What can I do?

**Comment by Apollon77** [comment]
Please provide more information because your description is very abstract.
Please show the Blockly as screenshot and also klick on the "JS/Blockly" icon in the UI and post the generated javascript you see then

**Comment by Apollon77** [comment]
no response, no details, closed
