### ISSUE TITLE
make configurable max io for adapter

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#1167]
i need a message or restart or anything when adapter has io > 3000 (maybe configurable in admin like threshold value )
![grafik](https://user-images.githubusercontent.com/6681528/194467883-7d1d9983-eb1f-455b-a2b9-09dbe537c497.png)

**Comment by Apollon77** [comment]
I would propose to add a counter per script that e.g. counts changes per minute or such and then add a limit for that configurable... maybe even configurable via a method inside the script to allow single scripts to break out of that if it is known thatr it generates a lot.
