### ISSUE TITLE
Skript Inhalt verschwindet nach dem starten / Script content disappears after launch

### ISSUE THREAD

**Issue by Sebastian-Bindler** [ioBroker/ioBroker.javascript#1168]
**Describe the bug**  

Ich habe gestern und heute ein neues Skript angelegt. Nach dem ich es gespeichert habe und dann starten wollte war der Inhalt einfach verschwunden. Dachte das war gestern nur einmalig aber ich hatte es leider heute wieder. Es tritt aber auch nicht immer auf.

I created a new script yesterday and today, after I saved ist and tried to start the skript it dissipiert. 
Thought that was only once yesterday but unfortunately I had it again today, it doesn't always happen either.

**To Reproduce**  
1. Neues Skript mit Blockly angelegt / Created a new script with Blockly
2. Gespeichert / Saved
3. Skript gestartet / Script started

**Expected behavior**  
/

**Screenshots & Logfiles**  
/

**Versions:**  
 - Adapter version: 6.0.3
 - JS-Controller version: 4.0.23
 - Node version: v14.20.1
 - Operating system: Debian GNU/Linux 11 (Raspberry Pi 4)

**Additional context**  
/

**Comment by Apollon77** [comment]
I can not reproduce it

**Comment by tigerlampe** [comment]
ich hab leider selbiges problem, bin mir aber nicht sicher ob es am javascript adapter liegt, da ich es in der vis auch immer wieder habe das neu eingefügte elemente auf einmal verschwinden, sieht eher nach einen timeout problem aus

**Comment by Sebastian-Bindler** [comment]
Hatte auch überlegt ob eventuell kurz die WLAN Verbindung abbricht. Mein Pi hängt jetzt per LAN im Netzwerk. Hab aber seit damals auch keine neuen Skripte eingefügt.

**Comment by com1992** [comment]
Ich habe genau das gleiche Problem

Raspberry
Adapter: 6.0.3
RAM: 3.7 GB
Node.js: v16.18.1
NPM: 8.19.2

Nach dem Speichern des Skriptes sind die letzten neuen Teile einfach so weg
