### ISSUE TITLE
NPM Error bei Javascript

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.javascript#1169]
|Systemdata| Bitte Ausfüllen|
|--|--|
|Hardwaresystem:| Mini PC|
|Arbeitsspeicher:| 16GB |
|Festplattenart:| SSD |
|Betriebssystem:| Ubuntu |
|Node-Version:| 16.15.1 |
|Nodejs-Version:| 16.15.1 |
|NPM-Version:| 8.11.0 |

Hallo

Ich hab folgende NPM-Module im JS-Adapter installiert.

![1665344612154-b3ef74f9-5f9f-45c5-918f-c97860b7ba5a-image](https://user-images.githubusercontent.com/45309436/194777725-04bc6fdd-63f0-4606-a724-7817cc7c7946.png)
![1665344580904-84efdc17-81bd-4573-9225-d33b0a077268-image](https://user-images.githubusercontent.com/45309436/194777734-ede52b64-cad2-41d9-8f27-aadbbab5d8c9.png)
![1665344546373-1c0337f2-574c-493d-917d-3aeb9c5f9a4b-image](https://user-images.githubusercontent.com/45309436/194777735-6954a5c8-3497-4793-a013-c57e5ec744af.png)

Gerade fiel mir auf, dass hier Fehler im Log auftauchen.
Wie weiß ich, welches Modul betroffen ist und wie kann ich es beheben?

```
javascript.0 2022-10-09 21:33:57.994	error	WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
javascript.0 2022-10-09 21:33:57.993	error	npm
javascript.0 2022-10-09 21:33:53.222	error	WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
javascript.0 2022-10-09 21:33:53.222	error	npm
javascript.0 2022-10-09 21:33:53.191	error	WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
javascript.0 2022-10-09 21:33:53.191	error	npm
javascript.0 2022-10-09 21:33:53.050	error	WARN deprecated har-validator@5.1.5: this library is no longer supported
javascript.0 2022-10-09 21:33:53.049	error	npm
```

**Comment by Apollon77** [comment]
Keine Fehler, nut earnungen von npm beim Installieren der Zusatzmodule. Ignore
