### ISSUE TITLE
Adapter rot und Fehler im Log

### ISSUE THREAD

**Issue by shabo85** [ioBroker/ioBroker.javascript#1192]
Hallo,
seit kurzen habe ich folgenden Fehler im Log:
Meine Java instanz bleibt rot.
Ich habe in letzter Zeit nichts verändert, daher kann ich den Fehler nicht so ganz nachvollziehen

**Screenshots & Logfiles**  
<html>
<body>

host.ubuntu | 2022-11-04 14:25:13.488 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/coffeescript/lib/coffee-script/coffee-script.js:426:4)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/coffeescript/lib/coffee-script/coffee-script.js:309:15)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:868:12)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1033:32)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1119:27)
host.ubuntu | 2022-11-04 14:25:13.487 | error | Caught by controller[0]: at wrapSafe (node:internal/modules/cjs/loader:1084:15)
host.ubuntu | 2022-11-04 14:25:13.486 | error | Caught by controller[0]: at Object.compileFunction (node:vm:360:18)
host.ubuntu | 2022-11-04 14:25:13.486 | error | Caught by controller[0]: SyntaxError: Unexpected end of input
host.ubuntu | 2022-11-04 14:25:13.486 | error | Caught by controller[0]:
host.ubuntu | 2022-11-04 14:25:13.486 | error | Caught by controller[0]: if (this.extern
host.ubuntu | 2022-11-04 14:25:13.486 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/node_modules/coffeescript/lib/coffee-script/nodes.js:1782

</body>
</html>

**Versions:**  
 - Adapter version: <v6.0.3>
 - JS-Controller version: <4.0.23>node -v
 - Node version: <v16.18.0> 
 - Operating system: <ubuntu 21.04>

**Comment by Apollon77** [comment]
is this really the full error message? WHich version you had before? Is this really a coffeescript?

**Comment by Apollon77** [comment]
No response assume fixed
