### ISSUE TITLE
[Request] ECONNRESET log-level to "warn" instead of "error"

### ISSUE THREAD

**Issue by sargonphin** [ioBroker/ioBroker.javascript#1195]
**Is your feature request related to a problem? Please describe.**
We have power switches controlling various sockets in our home (GUDE Expert Power Control 1000 & 8000 series) and the way we switch the sockets is by hitting a link with PHP options (see the screen capture below). The problem is, there's no page update at this point (or whatever) so the javascript adapter sees a connection reset, even though it worked and switched the socket on or off.

![image](https://user-images.githubusercontent.com/85966195/201418103-7bce35c7-7187-48c2-8288-3e6efbd29e65.png)

**Describe the solution you'd like**
Fine-tunning the log-levels to ignore such error in very specific cases, for instance setting ECONNRESET to be "warn" instead of "error", thus ignoring this ECONNRESET error which is actually a false-positive

**Describe alternatives you've considered**
The alternative is to use the block "system command" instead of "request link" in Blockly to use cURL instead, but this has no output at all in the adapter which is not ideal for troubleshooting

**Additional context**
Although right now the error is not doing much wrong, in the future I would like to setup error management & handling and this false-positive could come in the way

**Comment by Apollon77** [comment]
This is very simply. use a callback function as last parameter and you will get the error there and no logging occurs
