### ISSUE TITLE
Javascript Editor - Log Output displayed in wrong "Tab"

### ISSUE THREAD

**Issue by mrfenyx** [ioBroker/ioBroker.javascript#1197]
In certain cases, the log output of the currently executed script are displayed in another "tab", i.e. in the log window of another script. It happens if there are 2 files open, whereas the second file has the first part of the name identical with the first one. In this case the log output of file 2 is displayed in the "tab" of file 1.

**NOTE:** the issue does not occur if the second file (with the longer name) is opened first

How to reproduce:
1. create a new script and call it "test".
2. enter only one line: `console.log("This is test");`
3. save the file , start the script -> "This is test" is displayed in the log **[OK]**
4. create a second new script and call it "testing" (or anything you like that starts with "test").
5. enter only one line: `console.log("This is testING");`
6. save the file , start the script -> "This is testING" is NOT displayed in the log **[Not OK]**
7. switch to the file called "test" -> "This is testING" IS displayed in the log of "test", instead of "testing" **[Not OK]**

![image](https://user-images.githubusercontent.com/2023454/202870757-8a552d79-a0f0-45c3-87c1-e26fd4a3da31.png)

**Comment by GermanBluefox** [comment]
I could improve the log, but it still possible that some logs lands in wrong tabs. Because the GUI does not know where the text comes from and it just analyses the text in messages.
