### ISSUE TITLE
sendToAsync always returns error state

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.javascript#1198]
**Describe the bug**  
The "sendToAsync" function returns an error, even when the function is correctly executed.
The error contains the result of the function.

**Screenshots & Logfiles**  
```
async function sum2(id,timestart,timeend,db) {
    var return_value
    var query = 'SELECT * FROM "autogen"."' + id + id +'"'
    try {
            return_value = await sendToAsync(db, 'query', query);
            log("Return Value:" + JSON.stringify(return_value))
    } 
    catch (error) {
        console.error("Error Message: " + JSON.stringify(error))
    }         
    return ;
}

(async ()  => {
    await sum2(path2db + 'Auto_Ex.Tag_Energie',firstdayofyear + seach_time_start,yesterday +seach_time_end ,endless)
 })();
```
LogFile 
```
script.js.common.Energie: Error Message: {"result":[[]],"ts":1669200882840,"error":null}
```

**Versions:**  
 - Adapter version: 6.0.3
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Debian Bullseye

**Comment by Marty56** [comment]
Mir erscheint, dass in Zeile in dem File javascript/lib/tools.js in Zeile 82 die Parameter "error" und "result" vertauscht sind..

also
            fn.apply(context, [...args, (error, result) => {
muss in

fn.apply(context, [...args, (result, error,) => {

geändert werden.

**Comment by Apollon77** [comment]
Please try GitHub version if fixed

**Comment by Marty56** [comment]
Seems to work now. Thanks for the fix.

**Comment by Apollon77** [comment]
Lets leave open until released :-)
