### ISSUE TITLE
Script Editor öffnet nicht (Admin Adapter 6.2.23)

### ISSUE THREAD

**Issue by Plumpaquatsch69** [ioBroker/ioBroker.javascript#1199]
Hallo,
Beim Versuch den Skript Editor zu starten ist nur das ioBroker Logo (animiert) zu sehen aber der Editor öffnet sich nicht (genau wie in #861 beschrieben)

**Versions:**  
 - Adapter version: 6.2.23
 - JS-Controller version: 4.0.23
 - Node version: v14.19.0 NPM: 6.14.16
 - Operating system: Windows 10
 - Browser: Edge, Firefox, Chrome

Das Problem ist erst aufgetreten, nachdem ich heute viel an den Skripten gearbeitet habe. Auch mit anderen Browsern hat es dann nicht mehr funktioniert.

Hier die Ausgabe der Browser Konsole (Edge):

Translate: You cannot delete host, when it is alive
instrument.ts:123 Translate: Copy
bootstrap.jsx:26 iobroker.javascript@6.0.3 using theme "colored"
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:66 [2022-11-25T15:44:34.235Z] Try to connect
fetch.ts:23 
        
      
        
        
      
        
      
       
        
       POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.12.1 403
m @ fetch.ts:23
v5 @ base.ts:70
e1 @ promisebuffer.ts:49
d1 @ base.ts:85
_sendEnvelope @ baseclient.ts:703
sendSession @ baseclient.ts:311
captureSession @ baseclient.ts:202
_sendSessionUpdate @ hub.ts:462
captureSession @ hub.ts:387
z2 @ sdk.ts:245
B3 @ sdk.ts:277
Z5 @ sdk.ts:120
(anonym) @ GenericApp.js:233
Promise.then (asynchron)
onReady @ GenericApp.js:217
(anonym) @ Connection.js:444
Promise.then (asynchron)
(anonym) @ Connection.js:408
value @ Connection.js:377
value @ Connection.js:388
value @ Connection.js:339
(anonym) @ Connection.js:243
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212
instrument.ts:123 Detected custom blockly: cloud
instrument.ts:123 Detected custom blockly: email
instrument.ts:123 Detected custom blockly: pushover
instrument.ts:123 Detected custom blockly: telegram
instrument.ts:123 Detected custom blockly: whatsapp-cmb
instrument.ts:123 
        
       TypeError: Cannot read properties of undefined (reading 'length')
    at Editor.jsx:782:34
    at Array.map (<anonymous>)
    at fr.getTabs (Editor.jsx:765:37)
    at fr.render (Editor.jsx:1384:18)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:123
Hi @ react-dom.production.min.js:189
Cs.t.callback @ react-dom.production.min.js:189
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:262
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
react-dom.production.min.js:283 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Editor.jsx:782:34
    at Array.map (<anonymous>)
    at fr.getTabs (Editor.jsx:765:37)
    at fr.render (Editor.jsx:1384:18)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ Editor.jsx:782
getTabs @ Editor.jsx:765
render @ Editor.jsx:1384
Wi @ react-dom.production.min.js:204
Rs @ react-dom.production.min.js:203
oa @ react-dom.production.min.js:292
ra @ react-dom.production.min.js:280
Jc @ react-dom.production.min.js:280
ml @ react-dom.production.min.js:280
iu @ react-dom.production.min.js:271
bs @ react-dom.production.min.js:268
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
fetch.ts:23 
        
      
        
        
      
        
      
       
        
       POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.12.1 403
m @ fetch.ts:23
v5 @ base.ts:70
e1 @ promisebuffer.ts:49
d1 @ base.ts:85
_sendEnvelope @ baseclient.ts:703
sendSession @ baseclient.ts:311
captureSession @ baseclient.ts:202
_updateSessionFromEvent @ baseclient.ts:363
(anonym) @ baseclient.ts:658
(anonym) @ syncpromise.ts:79
(anonym) @ syncpromise.ts:182
_executeHandlers @ syncpromise.ts:176
(anonym) @ syncpromise.ts:97
V1 @ syncpromise.ts:58
then @ syncpromise.ts:69
_processEvent @ baseclient.ts:650
_captureEvent @ baseclient.ts:581
captureEvent @ baseclient.ts:182
(anonym) @ hub.ts:241
_withClient @ hub.ts:476
captureEvent @ hub.ts:240
w @ globalhandlers.ts:248
(anonym) @ globalhandlers.ts:103
c4 @ instrument.ts:95
P1.Q2.onerror @ instrument.ts:588
error (asynchron)
P1 @ instrument.ts:587
X5 @ instrument.ts:65
W5 @ instrument.ts:84
q @ globalhandlers.ts:78
setupOnce @ globalhandlers.ts:69
(anonym) @ integration.ts:68
xt @ integration.ts:64
setupIntegrations @ baseclient.ts:258
bindClient @ hub.ts:123
j2 @ sdk.ts:35
Z5 @ sdk.ts:117
(anonym) @ GenericApp.js:233
Promise.then (asynchron)
onReady @ GenericApp.js:217
(anonym) @ Connection.js:444
Promise.then (asynchron)
(anonym) @ Connection.js:408
value @ Connection.js:377
value @ Connection.js:388
value @ Connection.js:339
(anonym) @ Connection.js:243
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212
fetch.ts:23 
        
      
        
        
      
        
      
       
        
       POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.12.1 403
m @ fetch.ts:23
v5 @ base.ts:70
e1 @ promisebuffer.ts:49
d1 @ base.ts:85
_sendEnvelope @ baseclient.ts:703
sendEvent @ baseclient.ts:301
sendEvent @ client.ts:135
(anonym) @ baseclient.ts:661
(anonym) @ syncpromise.ts:79
(anonym) @ syncpromise.ts:182
_executeHandlers @ syncpromise.ts:176
(anonym) @ syncpromise.ts:97
V1 @ syncpromise.ts:58
then @ syncpromise.ts:69
_processEvent @ baseclient.ts:650
_captureEvent @ baseclient.ts:581
captureEvent @ baseclient.ts:182
(anonym) @ hub.ts:241
_withClient @ hub.ts:476
captureEvent @ hub.ts:240
w @ globalhandlers.ts:248
(anonym) @ globalhandlers.ts:103
c4 @ instrument.ts:95
P1.Q2.onerror @ instrument.ts:588
error (asynchron)
P1 @ instrument.ts:587
X5 @ instrument.ts:65
W5 @ instrument.ts:84
q @ globalhandlers.ts:78
setupOnce @ globalhandlers.ts:69
(anonym) @ integration.ts:68
xt @ integration.ts:64
setupIntegrations @ baseclient.ts:258
bindClient @ hub.ts:123
j2 @ sdk.ts:35
Z5 @ sdk.ts:117
(anonym) @ GenericApp.js:233
Promise.then (asynchron)
onReady @ GenericApp.js:217
(anonym) @ Connection.js:444
Promise.then (asynchron)
(anonym) @ Connection.js:408
value @ Connection.js:377
value @ Connection.js:388
value @ Connection.js:339
(anonym) @ Connection.js:243
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212

**Comment by mrMuppet** [comment]
Hallo, ich hab genau das gleiche Problem. Bei mir ist allerdings noch nicht mal das Logo zu sehen. Der rechte Bereich in dem dem Blockly-Blöcke erscheinen sollen, ist einfach leer. Der Titel des Skripts wird oben noch angezeigt, darunter die Symbole "Datei zeigen" bis "Debug Optionen" sind auch da und Ausgabefenster unten ist auch da.
Drücke ich "Blöcke prüfen" erscheint eine Meldung "Keine Blöcke vorhanden". Wenn ich mir den Skript in JS anzeigen lasse, dann wird er mir auch in ReadOnly angezeigt.

Versions:

AdminAdapter: 6.2.23
JS-Controller version: 6.1.4
Node version: v16.18.1 NPM: 8.19.2
Operating system: linux x64
Browser: Edge, Chrome

Im Browser finde ich ein paar Fehlermeldungen, vielleicht helfen die: 
```
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:66 [2022-12-10T16:49:24.185Z] Try to connect
DevTools failed to load source map: Could not load content for http://192.168.1.20:8081/adapter/min-maps/vs/editor/editor.main.nls.de.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
fetch.ts:35          POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.19.0 403
l @ fetch.ts:35
Nt @ base.ts:70
T @ promisebuffer.ts:49
e1 @ base.ts:85
_sendEnvelope @ baseclient.ts:729
sendSession @ baseclient.ts:312
captureSession @ baseclient.ts:203
_sendSessionUpdate @ hub.ts:461
captureSession @ hub.ts:387
zn @ sdk.ts:242
Jn @ sdk.ts:271
F4 @ sdk.ts:118
(anonymous) @ GenericApp.js:234
Promise.then (async)
onReady @ GenericApp.js:218
(anonymous) @ Connection.js:448
Promise.then (async)
(anonymous) @ Connection.js:412
value @ Connection.js:381
value @ Connection.js:392
value @ Connection.js:343
(anonymous) @ Connection.js:247
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212
instrument.ts:124 Detected custom blockly: cloud
instrument.ts:124 Detected custom blockly: enigma2
instrument.ts:124 Detected custom blockly: iot
instrument.ts:124 Detected custom blockly: pushover
instrument.ts:124 Detected custom blockly: sayit
blockly_compressed.js:159 Uncaught (in promise) Error: textToDom was unable to parse: <xml id="toolbox" style="display:none"><category name="System" colour="210"><block type="debug">     <value name="TEXT">         <shadow type="text">             <field name="TEXT">test</field>         </shadow>     </value></block><block type="comment">     <value name="COMMENT">     </value></block><block type="control">     <value name="OID">     </value>     <value name="VALUE">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="toggle">     <value name="OID">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="update">     <value name="OID">     </value>     <value name="VALUE">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="direct">     <value name="OID_SRC">         <shadow type="field_oid">             <field name="oid">Object ID 1</field>         </shadow>     </value>     <value name="OID_DST">         <shadow type="field_oid">             <field name="oid">Object ID 2</field>         </shadow>     </value>     <value name="ONLY_CHANGES">     </value></block><block type="control_ex">     <value name="OID">         <shadow type="field_oid">             <field name="oid">Object ID</field>         </shadow>     </value>     <value name="VALUE">         <shadow type="logic_boolean">             <field name="BOOL">TRUE</field>         </shadow>     </value>     <value name="TYPE">     </value>     <value name="DELAY_MS">         <shadow type="math_number">             <field name="NUM">0</field>         </shadow>     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="create">     <value name="NAME">     </value>     <value name="VALUE">     </value>     <value name="COMMON">     </value>     <value name="STATEMENT">     </value></block><block type="get_value">     <value name="ATTR">     </value>     <value name="OID">     </value></block><block type="get_value_var">     <value name="ATTR">     </value>     <value name="OID">         <shadow type="text">             <field name="OID">zigbee.0.1234</field>         </shadow>     </value></block><block type="get_value_async">     <value name="ATTR">     </value>     <value name="OID">     </value>     <value name="STATEMENT">     </value></block><block type="field_oid">     <value name="TEXT">     </value></block><block type="field_oid_meta">     <value name="TEXT">     </value></block><block type="field_oid_script">     <value name="TEXT">     </value></block><block type="get_attr">     <value name="PATH">         <shadow type="text">             <field name="PATH">attr1.attr2</field>         </shadow>     </value>     <value name="OBJECT">     </value></block><block type="regex">     <value name="TEXT">     </value></block><block type="selector">     <value name="TEXT">     </value></block><block type="logic_switch_case">     <value name="CONDITION">     </value>     <value name="CASECONDITION0">     </value>     <value name="CASE0">     </value>     <mutation with_statement="false" items="parameter1"></mutation></block></category><category name="Aktionen" colour="330"><block type="exec">     <value name="COMMAND">         <shadow type="text">             <field name="TEXT">text</field>         </shadow>     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false"></mutation></block><block type="request">     <value name="URL">         <shadow type="text">             <field name="TEXT">text</field>         </shadow>     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false"></mutation></block></category><category name="Sendto" colour="310"><block type="sendto_custom">     <value name="INSTANCE">     </value>     <value name="COMMAND">     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false" items="parameter1"></mutation></block><block type="sendto_otherscript">     <value name="NAME">     </value>     <value name="INSTANCE">     </value>     <value name="OID">         <shadow type="field_oid_script">             <field name="oid">Script Object ID</field>         </shadow>     </value>     <value name="MESSAGE">     </value>     <value name="DATA">         <shadow type="math_number">             <field name="NUM">1</field>         </shadow>     </value></block><block type="sayit">     <value name="    at Blockly.Xml.textToDom (blockly_compressed.js:159:158)
    at me.<anonymous> (BlocklyEditor.jsx:476:55)
    at Generator.next (<anonymous>)
    at n (62.0f665a2f.chunk.js:2:23844)
Blockly.Xml.textToDom @ blockly_compressed.js:159
(anonymous) @ BlocklyEditor.jsx:476
n @ 62.0f665a2f.chunk.js:2
Promise.then (async)
l @ 62.0f665a2f.chunk.js:2
(anonymous) @ 62.0f665a2f.chunk.js:2
ma @ 62.0f665a2f.chunk.js:2
componentDidUpdate @ BlocklyEditor.jsx:461
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
blockly_compressed.js:159 Uncaught (in promise) Error: textToDom was unable to parse: <xml id="toolbox" style="display:none"><category name="System" colour="210"><block type="debug">     <value name="TEXT">         <shadow type="text">             <field name="TEXT">test</field>         </shadow>     </value></block><block type="comment">     <value name="COMMENT">     </value></block><block type="control">     <value name="OID">     </value>     <value name="VALUE">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="toggle">     <value name="OID">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="update">     <value name="OID">     </value>     <value name="VALUE">     </value>     <value name="WITH_DELAY">     </value>     <mutation delay_input="false"></mutation>     <value name="DELAY_MS">     </value>     <value name="UNIT">     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="direct">     <value name="OID_SRC">         <shadow type="field_oid">             <field name="oid">Object ID 1</field>         </shadow>     </value>     <value name="OID_DST">         <shadow type="field_oid">             <field name="oid">Object ID 2</field>         </shadow>     </value>     <value name="ONLY_CHANGES">     </value></block><block type="control_ex">     <value name="OID">         <shadow type="field_oid">             <field name="oid">Object ID</field>         </shadow>     </value>     <value name="VALUE">         <shadow type="logic_boolean">             <field name="BOOL">TRUE</field>         </shadow>     </value>     <value name="TYPE">     </value>     <value name="DELAY_MS">         <shadow type="math_number">             <field name="NUM">0</field>         </shadow>     </value>     <value name="CLEAR_RUNNING">     </value></block><block type="create">     <value name="NAME">     </value>     <value name="VALUE">     </value>     <value name="COMMON">     </value>     <value name="STATEMENT">     </value></block><block type="get_value">     <value name="ATTR">     </value>     <value name="OID">     </value></block><block type="get_value_var">     <value name="ATTR">     </value>     <value name="OID">         <shadow type="text">             <field name="OID">zigbee.0.1234</field>         </shadow>     </value></block><block type="get_value_async">     <value name="ATTR">     </value>     <value name="OID">     </value>     <value name="STATEMENT">     </value></block><block type="field_oid">     <value name="TEXT">     </value></block><block type="field_oid_meta">     <value name="TEXT">     </value></block><block type="field_oid_script">     <value name="TEXT">     </value></block><block type="get_attr">     <value name="PATH">         <shadow type="text">             <field name="PATH">attr1.attr2</field>         </shadow>     </value>     <value name="OBJECT">     </value></block><block type="regex">     <value name="TEXT">     </value></block><block type="selector">     <value name="TEXT">     </value></block><block type="logic_switch_case">     <value name="CONDITION">     </value>     <value name="CASECONDITION0">     </value>     <value name="CASE0">     </value>     <mutation with_statement="false" items="parameter1"></mutation></block></category><category name="Aktionen" colour="330"><block type="exec">     <value name="COMMAND">         <shadow type="text">             <field name="TEXT">text</field>         </shadow>     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false"></mutation></block><block type="request">     <value name="URL">         <shadow type="text">             <field name="TEXT">text</field>         </shadow>     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false"></mutation></block></category><category name="Sendto" colour="310"><block type="sendto_custom">     <value name="INSTANCE">     </value>     <value name="COMMAND">     </value>     <value name="LOG">     </value>     <value name="WITH_STATEMENT">     </value>     <mutation with_statement="false" items="parameter1"></mutation></block><block type="sendto_otherscript">     <value name="NAME">     </value>     <value name="INSTANCE">     </value>     <value name="OID">         <shadow type="field_oid_script">             <field name="oid">Script Object ID</field>         </shadow>     </value>     <value name="MESSAGE">     </value>     <value name="DATA">         <shadow type="math_number">             <field name="NUM">1</field>         </shadow>     </value></block><block type="sayit">     <value name="    at Blockly.Xml.textToDom (blockly_compressed.js:159:158)
    at me.<anonymous> (BlocklyEditor.jsx:476:55)
    at Generator.next (<anonymous>)
    at 62.0f665a2f.chunk.js:2:23986
    at new Promise (<anonymous>)
    at ma (62.0f665a2f.chunk.js:2:23806)
    at me.componentDidUpdate (BlocklyEditor.jsx:461:32)
    at Zs (react-dom.production.min.js:261:316)
    at Gs (react-dom.production.min.js:260:446)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
Blockly.Xml.textToDom @ blockly_compressed.js:159
(anonymous) @ BlocklyEditor.jsx:476
(anonymous) @ 62.0f665a2f.chunk.js:2
ma @ 62.0f665a2f.chunk.js:2
componentDidUpdate @ BlocklyEditor.jsx:461
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
fetch.ts:35          POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.19.0 403
l @ fetch.ts:35
Nt @ base.ts:70
T @ promisebuffer.ts:49
e1 @ base.ts:85
_sendEnvelope @ baseclient.ts:729
sendSession @ baseclient.ts:312
captureSession @ baseclient.ts:203
_updateSessionFromEvent @ baseclient.ts:364
(anonymous) @ baseclient.ts:663
(anonymous) @ syncpromise.ts:79
(anonymous) @ syncpromise.ts:183
_executeHandlers @ syncpromise.ts:176
(anonymous) @ syncpromise.ts:97
m1 @ syncpromise.ts:58
then @ syncpromise.ts:69
_processEvent @ baseclient.ts:655
_captureEvent @ baseclient.ts:582
captureEvent @ baseclient.ts:183
(anonymous) @ hub.ts:241
_withClient @ hub.ts:475
captureEvent @ hub.ts:240
F @ globalhandlers.ts:248
(anonymous) @ globalhandlers.ts:149
Ot @ instrument.ts:96
lt.onunhandledrejection @ instrument.ts:612
fetch.ts:35          POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.19.0 403
l @ fetch.ts:35
Nt @ base.ts:70
T @ promisebuffer.ts:49
e1 @ base.ts:85
_sendEnvelope @ baseclient.ts:729
sendEvent @ baseclient.ts:302
sendEvent @ client.ts:126
(anonymous) @ baseclient.ts:687
(anonymous) @ syncpromise.ts:79
(anonymous) @ syncpromise.ts:183
_executeHandlers @ syncpromise.ts:176
(anonymous) @ syncpromise.ts:97
m1 @ syncpromise.ts:58
then @ syncpromise.ts:69
_processEvent @ baseclient.ts:655
_captureEvent @ baseclient.ts:582
captureEvent @ baseclient.ts:183
(anonymous) @ hub.ts:241
_withClient @ hub.ts:475
captureEvent @ hub.ts:240
F @ globalhandlers.ts:248
(anonymous) @ globalhandlers.ts:149
Ot @ instrument.ts:96
lt.onunhandledrejection @ instrument.ts:612
fetch.ts:35          POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.19.0 403
l @ fetch.ts:35
Nt @ base.ts:70
T @ promisebuffer.ts:49
e1 @ base.ts:85
_sendEnvelope @ baseclient.ts:729
sendEvent @ baseclient.ts:302
sendEvent @ client.ts:126
(anonymous) @ baseclient.ts:687
(anonymous) @ syncpromise.ts:79
(anonymous) @ syncpromise.ts:183
_executeHandlers @ syncpromise.ts:176
(anonymous) @ syncpromise.ts:97
m1 @ syncpromise.ts:58
then @ syncpromise.ts:69
_processEvent @ baseclient.ts:655
_captureEvent @ baseclient.ts:582
captureEvent @ baseclient.ts:183
(anonymous) @ hub.ts:241
_withClient @ hub.ts:475
captureEvent @ hub.ts:240
F @ globalhandlers.ts:248
(anonymous) @ globalhandlers.ts:149
Ot @ instrument.ts:96
lt.onunhandledrejection @ instrument.ts:612
```

**Comment by mrMuppet** [comment]
Nachdem ich den Enigma-Adapter gelöscht habe, funktioniert plötzlich die Block-Darstellung wieder.

**Comment by marian-t-web-de** [comment]
Gleiches Problem nach Update von Javascript Adapter von 6.1.0 zu 6.1.4: die Maske Scripte erscheint leer, Debugger (Chrome):

![image](https://user-images.githubusercontent.com/37208979/210374422-a2fd76ba-4f35-406b-bfa4-ca4e1ad6238b.png)

**Systeminfo**
raspberrypi
Plattform linux
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 1500 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 3.75 GB
System-Betriebszeit 24 T. 23:07:17
Node.js v12.22.12 (Empfohlene Version v16.19.0)
time 1672755278233
timeOffset -60
Anzahl der Adapter 450
NPM 6.14.16
Datenträgergröße 6.87 GB
freier Festplattenspeicher 1.09 GB
Betriebszeit 00:37:12
Aktive Instanzen 19
Weg /opt/iobroker/
Hostname raspberrypi

Habe kein Enigma-Adapter, nach Javascript-Adapter Downgrade zu 6.1.0 funktioniert es wieder.

**Comment by Apollon77** [comment]
Diese Felhler können nicht die URsache sein ... ist noch mehr in der Fehlerkonsole?

**Comment by marian-t-web-de** [comment]
Die Ursache liegt ja im fehlerhaften Javascript-Adapter, das Protokollaussschitt sagt nur das die Scripte-Seite - hinter GET - nicht erreichbar ist, was sich als leere Maske  darstellt. Ich werde das 6.1.4 erneut einspielen, um die Protokolle ausführlicher darzustellen. Auf welche Protokolleinträge soll ich achten?

**Comment by Apollon77** [comment]
Also eine variante ist "iob upload javascript" ...

**Comment by marian-t-web-de** [comment]
Wie gewünscht:
`$ iobroker upgrade javascript@6.1.4

Update javascript from @6.1.0 to @6.1.4

NPM version: 6.14.16

Installing iobroker.javascript@6.1.4... (System call)

> iobroker.javascript@6.1.4 postinstall /opt/iobroker/node_modules/iobroker.javascript> node ./install/installTypings.js

Installing NodeJS typings...

latest @types: 18, installed node: 12

+ iobroker.javascript@6.1.4updated 2 packages in 130.125s

120 packages are looking for funding run `npm fund` for details

Update "system.adapter.javascript.0"

Update "system.adapter.javascript.1"

upload [261] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript

upload [250] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg

upload [200] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/uk.js google-blockly/own/msg/uk.js application/javascript

upload [150] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Amplifier.6f5d18048328386033f8.svg static/media/Amplifier.6f5d18048328386033f8.svg image/svg+xml

upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Heater.b53bccc334bbb9238a36.svg static/media/Heater.b53bccc334bbb9238a36.svg image/svg+xml

upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Light.21f1a5dfcc93f8ba1214.svg static/media/Light.21f1a5dfcc93f8ba1214.svg image/svg+xml

upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Office.7e6a38218390b655e270.svg static/media/Office.7e6a38218390b655e270.svg image/svg+xml

upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Receiver.26b5ae166395a6dcb83f.svg static/media/Receiver.26b5ae166395a6dcb83f.svg image/svg+xml

upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Speaker.db548379676317470c4f.svg static/media/Speaker.db548379676317470c4f.svg image/svg+xml

upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Toilet.83604dd2daafb67067dd.svg static/media/Toilet.83604dd2daafb67067dd.svg image/svg+xml

upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Water.f50411984c5c24fa574d.svg static/media/Water.f50411984c5c24fa574d.svg image/svg+xml

upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/names.e7efb5283d98000c74ac.txt static/media/names.e7efb5283d98000c74ac.txt text/plain

upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.js vs/editor/editor.main.js application/javascript

upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.de.js vs/editor/editor.main.nls.de.js application/javascript

upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.es.js vs/editor/editor.main.nls.es.js application/javascript

upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.ko.js vs/editor/editor.main.nls.ko.js application/javascript

upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.ru.js vs/editor/editor.main.nls.ru.js application/javascript

upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.zh-cn.js vs/editor/editor.main.nls.zh-cn.js application/javascript

upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.zh-tw.js vs/editor/editor.main.nls.zh-tw.js application/javascript

upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/json/jsonMode.js vs/language/json/jsonMode.js application/javascript

upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/json/jsonWorker.js vs/language/json/jsonWorker.js application/javascript

upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsMode.js vs/language/typescript/tsMode.js application/javascript

upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsWorker.js vs/language/typescript/tsWorker.js application/javascript

upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/loader.js vs/loader.js application/javascript

upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/monaco.d.ts vs/monaco.d.ts video/mp2t

Process exited with code 0`

**Comment by marian-t-web-de** [comment]
Seltsamerweise ist der Editor diesmal heil - für mich erledigt.
