### ISSUE TITLE
Instanz stürzt ab / Änderungen werden nicht gespeichert

### ISSUE THREAD

**Issue by Trrw** [ioBroker/ioBroker.javascript#1210]
Nach dem speichern eines Scripts, stürzt regelmäßig der Adapter ab. So ändert sich das refresh-icon als Instanz nicht aktiv. Bei der Instanz wird der grüne Kreis zum roten. Nach ca. einer halben Minute ist der ioBroker wieder aufrufbar.

Des Weiteren, was jedoch öfter passiert, werden meine Änderungen nicht übernommen. Nach dem speichern erscheint die vorige Version meines Scripts. Oder es dauert ca. 30-60 Sekunden bis die Änderung übernommen wird welches dann (wie gehabt) unter dem Script das stoppen und starten bestätigt wird. Häufig passiert dies jedoch nicht und der Adapter stürzt ab.

Gerne kann ich mein Log mitteilen, wenn ihr mir sagt wie das geht. Wenn ich den Adapter auf Debuggen stelle wird mir im ioBroker leider kein Fehler ausgegeben, wenn der Adapter abstürzt.

Vielen Dank!

Javascript Adapter Version 
```
6.0.3
```

js controller 
`4.0.23`

ioBroker
```
Plattform linux
Betriebssystem linux
Architektur x64
CPUs 4
Geschwindigkeit
2300 MHz
Modell
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM 8 GB
System-Betriebszeit 13:02:56
Node.js v16.18.1 (Es gibt eine neuere Version: v16.19.0)
Anzahl der Adapter 448
NPM 8.19.2
Datenträgergröße 24.44 GB
freier Festplattenspeicher 6.31 GB
Betriebszeit 13:02:50
Aktive Instanzen 56

```

**Comment by Apollon77** [comment]
"Stürzt ab" ... Im log? Restart der Adapter? Oder "stürzt" der Browser ab? Mehr Details bitte. Logs aus Logfile von ioBroker bzw Browser Fehelrkonsole

**Comment by Apollon77** [comment]
Ebenso bitte sicherstellen das ggf im "Objekte Tab" nicht zuviele bereiche aufgeklappt sind ...

**Comment by Trrw** [comment]
> Ebenso bitte sicherstellen das ggf im "Objekte Tab" nicht zuviele bereiche aufgeklappt sind ...

Danke daran lag es. Es waren zu viele Bereiche aufgeklappt.
