### ISSUE TITLE
Error by canceling scheduled job "<Anonymous Job X date time>"

### ISSUE THREAD

**Issue by michaelshgr** [ioBroker/ioBroker.javascript#1211]
At every stop of a script with a schedule, javascript adapter logs an error message 'Error by canceling scheduled job "Anonymous Job X date time"'. When restarting javascript adapter, it shows for all scripts with schedules this error message.

 - Adapter version: 6.03
 - JS-Controller version: 4.0.23
 - Node version: 14.21.1
 - Operating system: Ubuntu 20.04.5 LTS

**Comment by Apollon77** [comment]
Already fixed in javascript 6.1.0, just only Beta ... will go into stable soon
