### ISSUE TITLE
existsState() not always working for initially created objects without setting a value

### ISSUE THREAD

**Issue by Acgua** [ioBroker/ioBroker.javascript#1213]
**Issue:**
The function `existsStateAsync()` is returning false for certain existing state objects initially created by adapters (e.g., deconz) and not yet set values, or by main ioBroker installation, e.g. `0_userdata.0.example_state`.

Example state object, which was created on Dec-23-2021 through ioBroker installation on Debian:
```
{
  "_id": "0_userdata.0.example_state",
  "type": "state",
  "common": {
    "name": "Example state",
    "role": "indicator",
    "def": false,
    "type": "boolean"
  },
  "acl": {
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "object": 1604
  },
  "from": "system.host.ioBroker.cli",
  "ts": 1640294850004
}
```

For this state object example above, `existsStateAsync()` returns `false`, while `true` is expected.

**Versions:**  
 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.24
 - Node version: 16.18.1
 - Operating system: debian

**Comment by Acgua** [comment]
My quick workaround (TS):
``` 
async function existsStateAsync2(id: string): Promise<true|false> {
    if (! await existsObjectAsync(id)) return false;
    const obj = await getObjectAsync(id);
    if (obj && 'type' in obj && obj.type === 'state') {
        return true;
    } else {
        return false;
    }
}
```

**Comment by Apollon77** [comment]
No this is a clear" work as expected" ... a State is the value. This means that "existsState" checks if there is a state! If a stete was never set then this is not the case

Please do not confuse it with "existsObject" ... This checks if an object is defined (but do not care if it has a state or not. So what you want to use it "existsObjectAsync"
