### ISSUE TITLE
Does it make sense to store compiled scripts?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#122]
Currently we compile global scripts (CoffeeScript and TypeScript) on every adapter restart. My upcoming changes will also generate declarations for global JavaScripts on restart, so the upgraded editor provides syntax help for global functions.
"Normal" scripts are compiled when they are started and (I believe) on every script restart.

I think it would make sense to store the generated/compiled sources along with the original ones in the script common object:
```js
common: {
    source: "...", // original JS/TS/Coffee sources (like it is currently)
    compiled: "...", // compiled TS/Coffee => JS sources
    declarations: "...", // generated declarations for global scripts (so the editor provides syntax help)
}
```
The compiled sources should not change drastically, even when there's a new compiler version. This means we're doing a lot of unnecessary work. By storing the output, we would only need to recompile when saving changed scripts. 

@GermanBluefox @Apollon77 What do you think?

**Comment by Hypnos3** [comment]
Great idea. Would reduce overhead drastically!

**Comment by GermanBluefox** [comment]
It is depend on how much time the compiling takes in count. If 2 seconds...
I don't see the need, if more : it is reason to save it.

пт, 25 мая 2018 г., 12:49 Hypnos <notifications@github.com>:

**Comment by Apollon77** [comment]
But if we store the compiled then directly on save. Else a Second objects change will restart the script. 

In general I’m with Bluefox answer but depending on number of scripts also 2 seconds per script can be a long time at adapter start. 
I alone have over 40 scripts ...

**Comment by AlCalzone** [comment]
> It is depend on how much time the compiling takes in count.

Depends on the system. I just have a few scripts, but on my Raspberry Pi 3, the startup of the JS adapter takes about 20 seconds, half of which is compiling the scripts. During that time, the CPU load is 150% (according to `htop`).

> I don't see the need

What's the downside in your opinion?

> But if we store the compiled then directly on save. Else a Second objects change will restart the script.

Good point!

**Comment by GermanBluefox** [comment]
@AlCalzone  Status?

**Comment by AlCalzone** [comment]
Nothing done yet
