### ISSUE TITLE
JavaScript Editor doesn't open

### ISSUE THREAD

**Issue by IchBinSmart** [ioBroker/ioBroker.javascript#1220]
Dear Sir or Madam,

after upgrade to newest version of javascript adapter (v6.0.3) my javascripts work at all. After re-installation of adapter + iobroker fixer tool, the scripts are now back running, but I can't access the "javascript tab" any longer. 

When I try to access it (http://raspberrypi:8081/#tab-javascript) I only get a white page that states:

File tab.html not found. Any idea how to fix this?

The javascript adapter is set on debug mode and there is nothing critical in the log that could relate to that error.

Thanks for your support,
 Rainer

**Comment by IchBinSmart** [comment]
... weird thing - in section instances it says v6.0.3 - but in section adapters it says v6.1.4 is installed. I tried to install that version again with the following result:
----
$ iobroker upgrade javascript@6.1.4 --debug

Update javascript from @6.1.4 to @6.1.4

NPM version: 8.19.3

Installing iobroker.javascript@6.1.4... (System call)

npm ERR! code ENOTEMPTY

host.raspberrypi Cannot install iobroker.javascript@6.1.4: 217

ERROR: Process exited with code 25
----

**Comment by Apollon77** [comment]
please try to execute "iob upload javascript"
