### ISSUE TITLE
Rules - Im Register Aktionen werden im Protokolltext die Variablen %s und %id nicht korrekt übersetzt

### ISSUE THREAD

**Issue by LK1976** [ioBroker/ioBroker.javascript#1224]
Im Register Aktionen werden im Protokolltext die Variablen %s und %id nicht korrekt übersetzt. Lt. Anleitung soll %s für den aktuellen Triggerwert stehen und %id für die ID des ausgelösten Objekts.

In der Protokolldatei steht: "My device %id triggered", somit ist %id nicht übersetzt worden.

![grafik](https://user-images.githubusercontent.com/121298651/210858866-8983d66b-94f7-4018-9ff8-233a97b2fb3a.png)

![grafik](https://user-images.githubusercontent.com/121298651/210858758-fc8a5436-a464-4366-8ee5-7719738a2c34.png)

 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: linux

Kann das Problem gelöst werden? Liegt es an mir?

**Comment by Apollon77** [comment]
Bitte mal das Rules als screenshot zeigen

**Comment by LK1976** [comment]
Hallo Apollon77,

hier das relativ einfache Rules:

![grafik](https://user-images.githubusercontent.com/121298651/210865725-2265e17b-2d32-4b28-b742-e2ae310fed8e.png)

Im Protokolltext %s und %id zu verwenden, so wie es hinter dem "Fragezeichen" angeboten wird.

Hast Du eine Lösung?

**Comment by GermanBluefox** [comment]
Das geht nur mit Trigger vom Zustand.
![image](https://user-images.githubusercontent.com/4582016/220085674-7cba4a9a-ed39-44fc-bfcb-f82842a066b0.png)

**Comment by GermanBluefox** [comment]
Aber ich habe erweitert, dass man auch vom Condition einen Wert sehen kann (Nur vom ersten)
