### ISSUE TITLE
Rules - Pushover funktioniert nicht

### ISSUE THREAD

**Issue by LK1976** [ioBroker/ioBroker.javascript#1225]
Ich habe ja die Möglichkeit, mir eine Nachricht aufs Handy zuschicken via Pushover. Leider funktioniert es unter Rules nicht:

![grafik](https://user-images.githubusercontent.com/121298651/210868260-7428ee15-ebc4-485e-b040-59d28308aee9.png)

![grafik](https://user-images.githubusercontent.com/121298651/210868662-28c9f5b7-ac0c-42d6-963d-dfb0d8303fc4.png)

Hat jemand eine Lösung?

**Comment by LK1976** [comment]
Es liegt am "`" in Zeile 14. Entfernt man dieses Zeichen, dann funktioniert das Skript.

Nur warum wird es immer wieder maschinell gesetzt? Kann das in RULES bitte gefixt werden?!

Vorab vielen Dank!

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.pushover/issues/112
