### ISSUE TITLE
Blockly: "the case of" problem with "state value" object

### ISSUE THREAD

**Issue by TDCroPower** [ioBroker/ioBroker.javascript#1226]
something is not quite right with the "the case of" object.
If you add "state value" directly to the port it works so far.

![Bildschirm­foto 2023-01-06 um 17 10 40](https://user-images.githubusercontent.com/6634116/211056273-772ab671-65ce-4ba0-801f-ada2693e8207.png)

But if you try to add "not" + "state value" or "state value" = "true"/"false" you get the following error messages...

logic_switch_case: (obj.state ? obj.state.val : "") == false is not a variable name
logic_switch_case: (obj.state ? obj.state.val : "") == true is not a variable name

... with "not" + "state value" object comes...

logic_switch_case: !(obj.state ? obj.state.val : "") is not a variable name

![Bildschirm­foto 2023-01-06 um 17 11 27](https://user-images.githubusercontent.com/6634116/211056278-8dc350ff-6e90-4c26-ac8d-ae91bb2a0e03.png)

![Bildschirm­foto 2023-01-06 um 17 38 04](https://user-images.githubusercontent.com/6634116/211056560-a458588c-575b-4267-8169-8a8499900541.png)

**Comment by Apollon77** [comment]
Why you use "in case of" at all for boolean values? Is "if/ekse" not suited better?

**Comment by TDCroPower** [comment]
I have had an understanding error!
In "the case of" only a variable may be inserted which can be queried later with "in case of" and no values in itself what happens with "not" + "state value" or "state value" = "true".
