### ISSUE TITLE
ERR_REQUIRE_ESM require() of ES Module "got"

### ISSUE THREAD

**Issue by axi92** [ioBroker/ioBroker.javascript#1228]
**Describe the bug**  
I just installed got from npm in the javascript settings of the adapter. But I can't use it.

At first I tried with import as ES6  but  that did not work ("SyntaxError: Cannot use import statement outside a module")

Then I changed it to a CommonJS module with require but id did not work either:

```
const got = require('got')
got.get('https://random-data-api.com/api/v2/users?size=1&is_xml=true').json().then((data) => {
  console.log(data);
})
```

**To Reproduce**  
1. Install "got"
2. run code above

**Expected behavior**  
To run the code.

**Screenshots & Logfiles**  
Error: javascript.0 (5584) script.js.common.Script_1: Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/iobroker/node_modules/iobroker.javascript/node_modules/got/dist/source/index.js from /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js not supported.

**Versions:**  
 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.23
 - Node version: v16.19.0
 - Operating system: windows wsl2 ubuntu 22.04 inside docker

**Additional context**

**Comment by Apollon77** [comment]
Please downgrade got for now or use the drop-in replacement from https://github.com/esm2cjs/got ...
