### ISSUE TITLE
Neue Variable "isDaylightSaving"

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/ioBroker.javascript#1231]
Unterhalb von `javascript.0.variables` gibt es z.B. bereits `isDayTime`.
Als Ergänzung könnte ich mir gut vorstellen, dass hier zusätzlich etwas wie `isDaylightSaving` angeboten wird, um (z.B. in Blockly) einfach ermitteln zu können, ob gerade Sommer- oder Winterzeit ist.
In JS ist das einfach, in Blockly natürlich mit 'ner JS-Funktion auch.

Wenn's nicht passt oder nicht so einfach zu implementieren ist ... auch kein Beinbruch ;-)

**Comment by Diginix** [comment]
Bei mir ist javascript.0.variables.isDaylightSaving bisher permanent "null".
Wann wird diese Variable denn true/false gesetzt?

**Comment by Diginix** [comment]
If is only set correctly at this 2 days per year, it is useless in the meantime until it is set once.
My solutions checks DST every night at 03:01 a.m. and on each script restart. Maybe to often, but better then never. This new variable should be checked and set correct on each adapter restart and obviously initially.
