### ISSUE TITLE
Errors "cannot find name" and "Property does not exist on type"

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.javascript#1233]
I have a problem with the following errors shown in the script tab:
![error_array_length](https://user-images.githubusercontent.com/58532773/212467532-dfef1830-ebb2-4cae-98ea-7c1489353edd.PNG)

![error_JSON](https://user-images.githubusercontent.com/58532773/212467542-fd9ff228-2ac6-4337-9245-eec54db45994.PNG)

![error_parseInt](https://user-images.githubusercontent.com/58532773/212467544-99582a02-6c88-437a-a23c-b731b0fc4de2.PNG)

Nevertheless every script seems to be working fine without errors in the log.
I don't know how to reproduce these errors, sometimes they are shown/visible and sometimes these things are not marked as error, but I don't know why...

Anybody have the same issue and is there a fix for that?

Thanks in advance!

**Versions:**  
 - Adapter version: 6.1.4 (beta repository)
 - JS-Controller version: 4.0.24
 - Node version: 16.17.1
 - NPM: 8.15.0
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Comment by Apollon77** [comment]
These are type checker/Typeing errors ... we need to check

**Comment by klein0r** [comment]
Please test with the latest beta (since a lot of type definitions have been changed)

**Comment by blackeagle998** [comment]
Updated to 7.8.0 and it seems to be fixed, no error messages anymore.
Thank you very much!
