### ISSUE TITLE
Verzögerte Ausführungen / Reaktion

### ISSUE THREAD

**Issue by backfisch88** [ioBroker/ioBroker.javascript#1236]
Hallo

Ich habe seit einiger Zeit das Problem, dass einige Sachen im Adapter nicht Zeitnah ausgeführt werden. Ich scheine (zumindest laut Facebook gruppe) auch nicht der einzige zu sein mit diesem Problem, deswegen mache ich einfach mal ein Issue auf.
Ich habe zb ein Script was das Flurlicht steuert. Einfaches Script

Trigger BWM
     falls wahr
             Licht an
     sonst
             Licht aus

das klappt auch normal <1 Sekunde also Praktisch ohne Verzögerung. Jetzt ist es aber manchmal so, dass es mal 10 Sekunden, mal 20 Sekunden braucht oder auch bestimmt 45 Sekunden. Da es nicht die einzige Ausführung ist die so funktioniert, schließe ich Komponenten mal aus, weil es vollkommen egal ist mit was man das macht. In dem Falle Aqara Zigbee - iobroker javascript Adapter - Shelly)
Man kann es leider nicht Provozieren, sodass der Fehler auftritt, aber "während des hängens" kommen alle Befehle normal im IOBroker an.

Habe mich natürlich damit beschäftigt und wollte das Problem eingrenzen, also habe ich absolut ALLES gestoppt und hab mich aufs minimale beschränkt.
Ich habe alle Adapter gestoppt (Ausser SHelly, Zigbee und Javascript) und nur das Script laufen lassen. Problem tritt auf.
Habe mir nur Datenpunkte schalten lassen und beobachtet (Zeitstempel), wird trotzdem Verzögert ausgeführt. 
Jetzt passiert das nicht alle 5 Minuten. Manchmal tritt das Problem (bemerkt zumindest) 2-3 Tage gar nicht auf, dann aber wieder 5 mal am Tag. Beim BWM fällt es natürlich schneller auf wie bei was anderem.
Wenn ich den Auftrittszeitsraum einschränken müsste würde ich den auf 2 Monate abstecken.

Mein System selber ist ein
Raspberry Pi 4 (4gb)
RaspberryOS 64 bit (neuster stand)
SSD (auch schon gewechselt zu anderer SSD)
Adapter (neuster stand)
Node.js: v16.19.0
NPM: 8.19.3

Ich schließe wie gesagt das System aus, da es Praktisch dauerhaft nahezu im Standby läuft. Ram ist unter normalen umständen 3/4 voll und CPU Last 0-40%.
Alle Adapter die sich neu starten sind auseinander gezogen (Minute Versatz). Keinerlei Intervalle die dauerhaft laufen (Habe insgesamt 4-5 Stück die aber 5 Minuten oder 10 Minuten sind)

Im LOG ist leider nichts dazu zu finden.

**Comment by Apollon77** [comment]
Also am allerbesten mal entweder mit einem Kleinen Javascript die relevanten staes mit "change:any" subscriben und loggen das man mal sieht was genau wann als Werte wie war und auch das skript was schalten sollte loggen lassen. dann kann man mal den flow durch die adapter ggf sehen.

Alternativ per History adapter weil man auch dann genauere zeistempel hat wann was war.

Weil die Magie ist herauszufinden was denn genau verzögert ist .. sendet JS nicht direkt raus, konsumiert ein adapter nicht? Ist es immer mit zigbee oder auch andere adapter und und und

**Comment by Apollon77** [comment]
PS: > nahezu im Standby läuft

... das hoffe ich doch nicht ... ich hoffe eher das System läuft einfach ganz normal :-)

**Comment by backfisch88** [comment]
> Also am allerbesten mal entweder mit einem Kleinen Javascript die relevanten staes mit "change:any" subscriben und loggen das man mal sieht was genau wann als Werte wie war und auch das skript was schalten sollte loggen lassen. dann kann man mal den flow durch die adapter ggf sehen.
> 
> Alternativ per History adapter weil man auch dann genauere zeistempel hat wann was war.
> 
> Weil die Magie ist herauszufinden was denn genau verzögert ist .. sendet JS nicht direkt raus, konsumiert ein adapter nicht? Ist es immer mit zigbee oder auch andere adapter und und und

werde ich mal machen. Lasse das alles mal in ne TXT loggen mit Uhrzeit.

Das Problem ist ja, wenn der Adapter verzögert reagiert, loggt er es ja falsch mit xD also werde ich paralell noch histroy loggen lassen

**Comment by Apollon77** [comment]
Deswegen vllt parallel noch mit history mitloggen, dann sieht mal vllt besser woran es liegt.

Wenn aber der Javascript adapter verzögert reagiert kann es auch sehr gut an einem anderen Skript liegen was einfach viele Daten verarbeitet (zb ein groses Logfile durchparst) ... das blockiert dann - je nachdem wie es geschrieben ist, auch andere Skripte! hast Duhier vllt irgendwas?

**Comment by backfisch88** [comment]
> Deswegen vllt parallel noch mit history mitloggen, dann sieht mal vllt besser woran es liegt.
> 
> Wenn aber der Javascript adapter verzögert reagiert kann es auch sehr gut an einem anderen Skript liegen was einfach viele Daten verarbeitet (zb ein groses Logfile durchparst) ... das blockiert dann - je nachdem wie es geschrieben ist, auch andere Skripte! hast Duhier vllt irgendwas?

daran habe ich auch gedacht. Es passiert aber auch, wenn ALLE Skripte aus sind, bis auf das Relevante

ich logge es einfach mal mit und wir sind mal gespannt :D 

2023.01.19 18:01:07.217 - zigbee.0.00158d0006c38ddd.occupancy - true
2023.01.19 18:01:07.848 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - true
logge das jetzt so im File per Java mal mit und per influx. Im normalfall (so wie jetzt) liegt die Zeit beim History 100ms vorher, was ja ok ist.
Ich werde berichten. Habe mal zur Vollständigkeit jetzt ALLES ausser Zigbee, Java, Shelly Adapter und das BWM Script wie das Log Script ausgeschaltet.

**Comment by backfisch88** [comment]
Also ist gerade wieder passiert und habe gesehen, dass Java Instanz deaktiviert war zu dem Zeitpunkt

![image](https://user-images.githubusercontent.com/7542512/213515326-ba793784-f237-4525-ac0f-ecbc701f3a67.png)
![image](https://user-images.githubusercontent.com/7542512/213515371-b175a40a-a328-4043-83b8-9568744d577c.png)
hier mal zwei Screenshots... Javascript hat davon nichts mitbekommen, dass was geaschaltet wurde. Laut Log wurde es aber auch nicht neugestartet

![image](https://user-images.githubusercontent.com/7542512/213515772-63c9313f-5bf8-4713-b456-ee328378fb76.png)



Das Script1 (ist das für das Logging) habe ich ca. 20 Sekunden davor gespeichert eigentlich


![image](https://user-images.githubusercontent.com/7542512/213515986-54201a53-6852-4271-90ad-7abbde07d4c4.png)

auch nichts Spektatkuläres

**Comment by backfisch88** [comment]
habe auch jetzt nochmal alles Deaktiviert... waren wohl Adapter durchgerutscht... ich verfolge das mal :)

**Comment by backfisch88** [comment]
Also erste Ergebnisse
jedes mal erst den Log den ich selber erstelle (Zeit der Ausführung im Adapter, Gerät, Änderung, Änderungszeitpunkt, Versatz zur Änderung im IOBroker) und dann Auszug ausm Log von Iobroker

2023.01.19 19:43:11.195 - zigbee.0.00158d0006c38ddd.occupancy - false - (IOBroker: 2023.01.19 19:43:07.570 - 3625ms)
2023.01.19 19:43:16.367 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - false - (IOBroker: 2023.01.19 19:43:16.196 - 171ms)
------
2023-01-19 19:42:09.183 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 19:43:16.327 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 19:43:17.175 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 19:44:13.157 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0

------------------------------------------------------------------------------------------------------------------------------

2023.01.19 21:14:47.439 - zigbee.0.00158d0006c38ddd.occupancy - true - (IOBroker: 2023.01.19 21:14:42.080 - 5359ms)
2023.01.19 21:14:47.657 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - true - (IOBroker: 2023.01.19 21:14:47.439 - 218ms)
------
2023-01-19 21:13:03.231 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 21:14:08.378 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 21:14:49.094 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 21:16:54.986 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 21:18:37.297 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31

------------------------------------------------------------------------------------------------------------------------------

2023.01.19 21:57:53.475 - zigbee.0.00158d0006c38ddd.occupancy - false - (IOBroker: 2023.01.19 21:57:50.804 - 2671ms)
2023.01.19 21:58:05.212 - zigbee.0.00158d0006c38ddd.occupancy - true - (IOBroker: 2023.01.19 21:58:05.206 - 6ms)
------
2023-01-19 21:56:51.992 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 21:57:58.543 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 21:57:59.346 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 21:58:56.188 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 22:00:04.274 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31

------------------------------------------------------------------------------------------------------------------------------

2023.01.20 00:22:16.887 - zigbee.0.00158d0006c38ddd.occupancy - true - (IOBroker: 2023.01.20 00:22:14.718 - 2169ms)
2023.01.20 00:22:17.108 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - true - (IOBroker: 2023.01.20 00:22:16.887 - 221ms)
------
2023-01-20 00:22:00.266 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-20 00:22:22.097 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-20 00:23:27.960 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-20 00:23:28.830 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-20 00:24:25.969 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0






Jetzt ist natürlich socket.io erst mal auffällig ABER
23.01.19 21:41:28.295 - zigbee.0.00158d0006c38ddd.occupancy - true - (IOBroker: 2023.01.19 21:41:28.289 - 6ms)
2023.01.19 21:41:28.467 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - true - (IOBroker: 2023.01.19 21:41:28.295 - 172ms)
------
2023-01-19 21:41:30.913 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31
2023-01-19 21:42:28.720 - info: socketio.0 (1722) <== Disconnect system.user.admin from ::ffff:192.168.178.31 vis.0
2023-01-19 21:42:30.437 - info: socketio.0 (1722) ==> Connected system.user.admin from ::ffff:192.168.178.31




hoffe das ist Hilfreich

**Comment by backfisch88** [comment]
`2023.01.20 08:30:09.400 - zigbee.0.00158d0006c38ddd.occupancy - false - (IOBroker: 2023.01.20 08:30:09.398 - 2ms)
2023.01.20 08:30:23.774 - shelly.0.SHSW-1#68C21E#1.Relay0.Switch - false - (IOBroker: 2023.01.20 08:30:18.108 - 5666ms)
`


kein Log Eintrag in dem Zeitraum. wurde demnach schnell Verarbeitet, aber gesteuert wurde das Relais erst 5,5 Sekunden Später

**Comment by Apollon77** [comment]
Bitte logge mal alles (also nicht nur "geändert") und logge bitte auch das "ack/bestätigt flag mit

**Comment by Apollon77** [comment]
Deswegewn besser logging per hostory adapter zu mchen, da ist alles automatisch da

**Comment by backfisch88** [comment]
> Bitte logge mal alles (also nicht nur "geändert") und logge bitte auch das "ack/bestätigt flag mit

![image](https://user-images.githubusercontent.com/7542512/213716443-8c5276a1-0514-4a45-bde6-59a2b8ab93fa.png)


heir ein auszug vom loggen per iobroker

**Comment by Apollon77** [comment]
Naja nur die reinen logdaten ohne semantik und info vom Skript ist schwierig auszuwerten. Das müstest du genauer aufbereiten, sorry.

Ok, tue mir biotte einen gefallen: logge mal den state system.adapter.javascript.0.eventLoop mit  (siehst du mit expertenmodus). Dann schauen ob zu den zeiten wo das länger dauert die zahl dort nach oben geht ... Falls ja dann blockiert irgendeins deiner anderen Skripte den javascript adapter!! Ebenso vllt CPU usage states loggen und ansehen zu den zeitpunkten

Alternativ lagere mal das relevante skript ggf in eine eigene instanz aus und schaue ob es da auch passiert.

**Comment by backfisch88** [comment]
> Naja nur die reinen logdaten ohne semantik und info vom Skript ist schwierig auszuwerten. Das müstest du genauer aufbereiten, sorry.
> 
> Ok, tue mir biotte einen gefallen: logge mal den state system.adapter.javascript.0.eventLoop mit (siehst du mit expertenmodus). Dann schauen ob zu den zeiten wo das länger dauert die zahl dort nach oben geht ... Falls ja dann blockiert irgendeins deiner anderen Skripte den javascript adapter!! Ebenso vllt CPU usage states loggen und ansehen zu den zeitpunkten
> 
> Alternativ lagere mal das relevante skript ggf in eine eigene instanz aus und schaue ob es da auch passiert.

es sind aktuell ALLE Skripte aus

skript ist:
Trigger BWM
falls wahr
Licht an
sonst
Licht aus


ich logge das alles mal mit

**Comment by backfisch88** [comment]
`2023.01.20 18:14:15.939 - zigbee.0.00158d0006c38ddd.occupancy - true - (IOBroker: 2023.01.20 18:13:50.666 - 25273ms)`


CPU LOAD
![image](https://user-images.githubusercontent.com/7542512/213763384-5d56800a-c828-43fc-8a1e-e9021ffdf3ca.png)



Event Loop
![image](https://user-images.githubusercontent.com/7542512/213763621-90ab3413-7255-46cd-ae88-57034e607b21.png)


im normalen LOG steht nichts um die Uhrzeit


es geht alles hoch, es wird aber nichts verarbeitet... auf dem PI läuft ausschließlich IOBroker

es läuft ausschliesslich das script:
![image](https://user-images.githubusercontent.com/7542512/213764282-9515b5e5-dd40-4655-a7a0-17ce62418038.png)


und das was Dokumentiert
![image](https://user-images.githubusercontent.com/7542512/213764402-1381d4fc-1b3a-4a70-b76f-e29914de4c7a.png)

**Comment by pafade89** [comment]
Hallo Zusammen,
wie @backfisch88 schreibt habe auch ich das gleich Problem. Wenn der Sonoff Mini per Schalter betätigt wird, ändert sich der State in den Objects des Sonoff-Adapter innerhalb weniger Millisekunden. Bis der der Javaskript-Adapter diese Änderung allerdings erfasst, vergehen teilweise bis zu 10 Sekunden. Ich benutze allerdings auch keinen Pi, sondern einen Intel Celeron N4100 (4x 2,4 GHz) mit 8 Gb RAM. 

Dieser Fehler tritt meist nach ca. 2 Tagen JavaScript Adapter Betrieb auf und lässt sich auch wieder für 2 Tage durch einen Neustart beheben. Außerdem steigt die CPU Auslastung in HTOP im Fehlerzeitraum für den javascript.io Prozess alle 5 Sekunden auf 100 bis 140% an. 
Ein Deaktivieren oder Neustarten einzelner bzw. aller Skripts bringt keine Änderung mit sich, lediglich ein Neustart des Adapters bringt den gewünschten Erfolg. 

Nach dem Neustart des Adapters sinkt die CPU Auslastung wieder auf Normalniveau (ca. 10 % für zwei Tage).

Ob der Prozess schleichend in der CPU Auslastung steigt oder schlagartig habe ich noch nicht geprüft, werde ich die Tage aber nachholen. 

System:

Debian 11 Bullseye 
IoBroker Controller: 4.0.24
JS Adapter: 6.1.4
NPM: 8.19.2
NodeJS: 16.18.1

VG P

**Comment by Apollon77** [comment]
@backfisch88 Also du hast definitiv ein Skript welches im Javascript Adapter blockiert! Siehe der eine "Event loop Eintrag" der 24.851ms hat -> das sind grob 25s blockiert! Also irgendwo hast Du eine sehr große Schleife in deinem Code die kontinuierlich Dinge tut. Die beiden gepostete blocklies können da an sich nicht dran schuld sein, but poste mal wie die in Javascript Code aussehen (im JS Fenster beidem Skript oben auf das JS|Blockly Icon klicken , dann schaltet er die Anzeige um.

**Comment by Apollon77** [comment]
@pafade89 Dann klingt das im ersten Schritt auch bei dir nach einem Skript was Amok läuft ... also bitte mal Daten mitloggen, Skripte in Instanzen separieren und ggf so suchen welches Skript die Ursache sein kann

**Comment by backfisch88** [comment]
> @backfisch88 Also du hast definitiv ein Skript welches im Javascript Adapter blockiert! Siehe der eine "Event loop Eintrag" der 24.851ms hat -> das sind grob 25s blockiert! Also irgendwo hast Du eine sehr große Schleife in deinem Code die kontinuierlich Dinge tut. Die beiden gepostete blocklies können da an sich nicht dran schuld sein, but poste mal wie die in Javascript Code aussehen (im JS Fenster beidem Skript oben auf das JS|Blockly Icon klicken , dann schaltet er die Anzeige um.

Ich schaue nochmal nach, aber es ist alles pausiert 😅
Gibts die Möglichkeit von „unsichtbaren“
Scripten?

Habe auch den Adapter komplett gelöscht / neu installiert und alle Scripts frisch importiert. 

Werde da nochmal nachforschen

**Comment by Apollon77** [comment]
Also wenn du sicher gehen willst dann beende alle Skripte manuell. Dann starte den adapter neu und aktiviere nur die die du willst. Ansonsten wäre ein" debug log" vom javascript adapter interessant wenn es dann immer noch passiert.

Ansonsten die Fragehndie ich ausgelassen hab ist wieviel RAM die kiste hat, wie es der geht, was sagt "free -m" und so weiter um auszuschliessen das die Ursache dort liegt und gar nicht im Adapter (zb weil ram knapp kommt kiste in swapping und swappt 25s fröhlich vor sich hin und blockt deswegen alles)

Generell ist das Thema besser fürs Forum geeignet als im GitHub

**Comment by backfisch88** [comment]
> Also wenn du sicher gehen willst dann beende alle Skripte manuell. Dann starte den adapter neu und aktiviere nur die die du willst. Ansonsten wäre ein" debug log" vom javascript adapter interessant wenn es dann immer noch passiert.
> 
> Ansonsten die Fragehndie ich ausgelassen hab ist wieviel RAM die kiste hat, wie es der geht, was sagt "free -m" und so weiter um auszuschliessen das die Ursache dort liegt und gar nicht im Adapter (zb weil ram knapp kommt kiste in swapping und swappt 25s fröhlich vor sich hin und blockt deswegen alles)
> 
> Generell ist das Thema besser fürs Forum geeignet als im GitHub

Danke schon mal für deine Zeit. Hört sich tatsächlich nicht nach Adapter an 😅
Werde nochmal alles auf links machen 😃
Und ansonsten Forum.

**Comment by Apollon77** [comment]
mentione mich gern auch im forum, dann lese ich mit und stelle meine "dummen fragen" da :-)

**Comment by pafade89** [comment]
Hey @Apollon77 vielen Dank schonmal für deine Zeit. 

Habe gerade mal ein Skript mit einer Pause von 1 ms in einer Loop laufen lassen und hatte dann eine Prozess CPU Auslastung von io.javascript von ca. 20 %. Eventlooplag lag weiterhin bei 1 ms. Danach Skript wieder ausgeschaltet und CPU Prozess für io.javascript wieder bei unter 5 %. Dieses Verhalten konnte im Fehlerfall durch ausschalten aller Skripte nicht behoben werden, die CPU Last lag periodisch weiterhin bei teilweise 140% Auslastung.

Es sieht so aus, als würde etwas mit dem aktualisieren der States nicht stimmen. Außerdem gab es den Fehler nicht bevor ich das Update 6.1.4 gemacht habe. Ich habe das Update von einer Version vor 6.0.3 gemacht. Ich meine sogar es war noch eine Version mit 5.x.
Leider kann ich das nicht mehr genau sagen.

VG P

**Comment by backfisch88** [comment]
> Also wenn du die "schleife" mit "setTimeout" gebaut hast dann ist das genau korrekt und ja in dem Fall ist die eventloop uch genau so korrekt. Bei JavaScript geht alles um "Asynchronität" und ein setTimeout gibt den anderen Dingen die in der "eventloop" laufen zeit ausgeführt zu werden. 1ms ist dennoch eine sehr kurze Zeit un daher sind 20% CPU ok ... (hätte eher mehr erwartet ... aber ok) Ansonsten wre cool wenn du mal versionsweise zurückgeghen könntest um zu sehen wann es genau dazugekommen ist ... dann hätte ich weniger code zum checken :-) (falls es wirklich kein skript ist)

Also ich beobachte mal weiter, scheint sich aber gelöst zu haben...

habe ungefähr 1000 mal den Adapter deinstalliert und alle ordner gelöscht die es so von gab... dann ist nach ner Neuinstallation ein Script drin gewesen (woher auch immer)... das ist n UrAlt Script von mir was getriggert auf n DP hat und ne Liste estellt der exakt jede Minute Triggert.... hoffe das war es

vergleich eventLoopLag jetzt (ab 17:15)
![image](https://user-images.githubusercontent.com/7542512/214351868-38d156c0-543a-469e-b695-c8de2764340b.png)

vergleich eventLoopLag vorher;
![image](https://user-images.githubusercontent.com/7542512/214352002-aaa0d090-7c3d-41a8-96f7-188dea6d1e9b.png)

**Comment by Apollon77** [comment]
Danke für die Rückmeldug und ja solche "grosse schleife die ohne async dinge tut" die blockiert
