### ISSUE TITLE
Adapter Javascript not starting any more, message: Cannot find view "script" for search "javascript"

### ISSUE THREAD

**Issue by andreasbehnke** [ioBroker/ioBroker.javascript#1247]
**Describe the bug**  
I have removed all my scripts, but the adapter does not start.
The log only shows up this message:

Cannot find view "script" for search "javascript"

**To Reproduce**  
It suddenly happend

**Expected behavior**  
Adapter should start correctly

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/5552434/217185558-0fc73b1f-c53b-42f1-b6ae-70e11f3be577.png)

**Versions:**  
 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.24
   - Node version: v16.16.0
 - Operating system: debian

**Additional context**  
Normal scripts do work, but the global constants and scripts are not loaded

**Comment by Apollon77** [comment]
Did anything happen to you syytem in general? Please try to execute "iob upload javascript"

**Comment by andreasbehnke** [comment]
No, nothing special. Yesterday evening I was coding a script using vs code with the iobroker extension of vs code. I could successfully update the scripts, everything was working as expected. When uploading a global script, the adapter did a restart - as expected.

Today I just tried to upload a change of a global script again, and always got the message shown above. I then did the following:

- Removed all my scripts
- Removed adapter instance
- reinstalled adapter
- restarted debian system
- turned on DEBUG logging of adapter

My problem is, that the error message is missing an exception stack trace to dig any deeper. I did a fulltext search for this special message, but could not find anything in the adapter code.

**Comment by Apollon77** [comment]
The thing is that this "missing script" is contained in the io-package of the adapter itself

https://github.com/ioBroker/ioBroker.javascript/blob/master/io-package.json#L262-L269

so a reinstallation or upload should in any case re-register it "if there is anything else).

Is the system lse ok? Filesystem not full? and such? Please try a restar of iobroker itself, pot with stop, "iob fix" and start

**Comment by andreasbehnke** [comment]
I can say, even after reinstalling the adapter, that I do not have 

_design/script

in the object tree.

AND: 
I can remember that I "cleaned" up the object tree and removed exactly this object yesterday, I think this was really stupied ... :-(

Thank you for pointing in the right direction!
What can I do to recreate this "view"?

**Comment by andreasbehnke** [comment]
Hi Appollon77,

I managed to fix the problem. I did a reinstall of the adapter (not only the instance of the adapter..) and the missing
object "_design/script" had been recreated.

Thank you very much for your support!

**Comment by Apollon77** [comment]
Glad you fixed it

> I think this was really stupid ... 

SOrry but yes .. you should not do such cleanups while in "admin mode"
