### ISSUE TITLE
Blockly: Additional options for attributes of object

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/ioBroker.javascript#1249]
It would be great if you could implement reading more than the currently available attributes of an object.
![image](https://user-images.githubusercontent.com/95883579/218452523-9589b82a-fb5f-4eea-896a-14f9b404b667.png)
Especially getting the name would be handy. Currently it's only possible to get the name of an object with a JavaScript function.

**Comment by DEV2DEV-DE** [comment]
As @Paul53 mentioned in the forum, the block shown above is only able to get the available states.
Therefore, a new block element using "getObject()" internally could be the solution.

**Comment by paul53** [comment]
"Kommentar" wäre noch nützlich.

Für Namen und weitere common-Attribute wäre ein Block für getObject(Id) oder getObject(id).common wünschenswert.

**Comment by Diginix** [comment]
letzte und vorletzte Änderung (timestamp) wäre auch super.
Im Prinzip alles was im Object ID Block geht:
![image](https://user-images.githubusercontent.com/39678667/218456852-4e275747-a8da-46f5-b239-b63d6c9b26b5.png)

**Comment by paul53** [comment]
"vorherige" Attribute sind bei geState(id) nicht verfügbar.

**Comment by DEV2DEV-DE** [comment]
> letzte und vorherige letzte Änderung (timestamp) wäre auch super.

Die "vorherige letzte Änderung" sowieso nicht.

Ich stecke da nicht so tief drin, aber in dem Moment wo der Trigger feuert, kenne ich den neuen und den aktuell noch vorhandenen Zustand. Mehr nicht

**Comment by Diginix** [comment]
Ja, wahrs. existiert dieses Wissen nur im Moment der letzten Änderung und nicht rückwirkend, da nicht am Objekt gespeichert.
Aber falls nötig kann man das ja selbst im Skript in Variablen parken.

**Comment by paul53** [comment]
_oldState_ ist eine Variable, die bis zum nächsten Ereignis erhalten bleibt.

**Comment by Diginix** [comment]
Aber die gibt es nicht als Blockly Block per default?

**Comment by GermanBluefox** [comment]
Es ist implementiert, aber es ist nur Name, Zustandskommentar, Beschreibung, Einheit, Beschreibbar, Lesbar, Rolle, Objekttype, Zustandstyp, möglich zu lesen.
