### ISSUE TITLE
existsStateAsync and "Do not subscribe all states on start" = false

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.javascript#1250]
**Describe the bug**  
`await existsStateAsync` is false, if option `Do not subscribe all states on start` = false

**To Reproduce**  
1. deactivate `Do not subscribe all states on start` in adapter settings
2. write a script (JS / TS) with `await existsStateAsync()` that point to an existing state.

**Expected behavior**  
`await existsStateAsync` should return true

**Versions:**  
 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.24
 - Node version: 16.x
 - Operating system: ubuntu 22.04

**Additional context**

**Comment by GermanBluefox** [comment]
Good finding! Thank you!

**Comment by Scrounger** [comment]
successful tested with v7.0.0, thank you!

**Comment by Scrounger** [comment]
Have to reopen it.
Now there is an error message in th log, if state not exists:
`2023-02-21 21:39:33.082 - error: javascript.0 (2061) script.js.test: error: Alias alias.0.Sensoren.Fenster.fuuu has no target, stack: Error: Alias alias.0.Sensoren.Fenster.fuuu has no target`

Is that the way it's supposed to be? Before there was no message in the log

**Comment by GermanBluefox** [comment]
> Have to reopen it. Now there is an error message in th log, if state not exists: `2023-02-21 21:39:33.081 - warn: javascript.0 (2061) Alias alias.0.Sensoren.Fenster.fuuu has no target 9 2023-02-21 21:39:33.082 - error: javascript.0 (2061) script.js.test: error: Alias alias.0.Sensoren.Fenster.fuuu has no target, stack: Error: Alias alias.0.Sensoren.Fenster.fuuu has no target`
> 
> Is that the way it's supposed to be? Before there was no message in the log
> 
> Edit: This log message only shown if id is an alias. In my opinion, there should be no log output here, since you are checking for existence.

This log is done by js-controller and not javascript

**Comment by Scrounger** [comment]
Ok i created an issue at js-controller side:
https://github.com/ioBroker/ioBroker.js-controller/issues/2112
