### ISSUE TITLE
After Upgrade to 6.2.0 - JSON Ausdruck dosn't work any more

### ISSUE THREAD

**Issue by str3000** [ioBroker/ioBroker.javascript#1253]
value return "null" or "{}"
Worked correctly with previson version 6.1.4

Blockly:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/48569357/219936164-820f8d4d-d1ea-40da-a5c7-a0513f29cccb.png">

Data:
```
javascript.0 (95347) script.js.Haus-UG.Volkszaehler: {'Time':'2023-02-19T08:59:25','Power':{'Meter_Number':'','ELZ_PV_1_8_0':9410.7244,'Power_curr':191,'ELZ_PV_2_8_0':13065.1732}}
```

**Comment by winnyschuster** [comment]
i can confirm this. looks like the new version of jsonata.evaluate() (2.0.1 vs 1.8.6) is now returning a Promise so it must be invoked with **await** . Once done in a javascript it is working as expected

**Comment by heckmic** [comment]
same problem here. No value for calculating with json history data.

**Comment by GermanBluefox** [comment]
the new version 7.0 was released:

### 7.0.0 (2023-02-21)
* (bluefox) Breaking change: all usages of `jsonata` must be rewritten to use promises.
* (bluefox) Breaking change: all blockly scripts with `jsonata` blocks must de changed (just move some blocks) and saved anew.

**Comment by Diginix** [comment]
![image](https://user-images.githubusercontent.com/39678667/220403021-f3670518-9e7c-4ded-9a33-5af4ea41427e.png)

Even with v7.0.0 the result is empty. With 6.1.4 or on https://try.jsonata.org/ it is working as shown in my screenshot.

**Comment by heckmic** [comment]
I can confirm - Version 7 still not working.

**Comment by GermanBluefox** [comment]
> ![image](https://user-images.githubusercontent.com/39678667/220403021-f3670518-9e7c-4ded-9a33-5af4ea41427e.png)
> 
> Even with v7.0.0 the result is empty. With 6.1.4 or on https://try.jsonata.org/ it is working as shown in my screenshot.
> 
> ![image](https://user-images.githubusercontent.com/39678667/220403393-aacd6308-3e75-4df0-9982-e2378034df11.png)

You cannot apply JSONata to string. Please please JSON2obj block:
![image](https://user-images.githubusercontent.com/4582016/220616486-a74d88f1-600c-4c1d-ab5a-c17e84582af7.png)

**Comment by GermanBluefox** [comment]
> I can confirm - Version 7 still not working.

Please show you blockly and generated JS code

**Comment by heckmic** [comment]
> > I can confirm - Version 7 still not working.
> 
> Please show you blockly and generated JS code

Now its working with 7.0.1

**Comment by Diginix** [comment]
@GermanBluefox I have tried all combinations of "convert to" with my JSON text object. None worked with v7 and all even without converting are working with 6.1.4.
But I will give 7.0.1 a new try, even the issue is not marked as fixed. But @heckmic comment lets me hope.

**Comment by winnyschuster** [comment]
not sure what you guys did with your code, for me v7.0.0 resolved the problem and v7.0.1 is working well too

**Comment by Diginix** [comment]
v6.1.4:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/39678667/220735096-e8288352-006f-486e-8d11-f7448f761458.png">

Blockly:
```
<block xmlns="https://developers.google.com/blockly/xml" type="debug" id="T7|xH0$)i|eeMQnjh(Pq" x="13" y="13">
  <field name="Severity">log</field>
  <value name="TEXT">
    <shadow type="text">
      <field name="TEXT"></field>
    </shadow>
    <block type="convert_jsonata" id="vL7kBHYZIqRt^!;L3qyJ">
      <value name="EXPRESSION">
        <shadow type="text" id="}6uGou-KzXg}-1(@bDnN">
          <field name="TEXT">value.IrLights.state</field>
        </shadow>
      </value>
      <value name="TARGET">
        <block type="convert_json2object" id="OW]mW{Dr9hE7s^zs6/tu">
          <value name="VALUE">
            <block type="text_multiline" id="EIEUI4,$+Rgk]0FkD4z7">
              <field name="TEXT">[&#10;   {&#10;      "cmd" : "GetIrLights",&#10;      "code" : 0,&#10;      "value" : {&#10;         "IrLights" : {&#10;            "state" : "Off"&#10;         }&#10;      }&#10;   }&#10;]</field>
            </block>
          </value>
        </block>
      </value>
    </block>
  </value>
</block>
```

Javascript:
```
console.log(jsonataExpression((function () { try {return JSON.parse(('[' + '\n' +
'   {' + '\n' +
'      "cmd" : "GetIrLights",' + '\n' +
'      "code" : 0,' + '\n' +
'      "value" : {' + '\n' +
'         "IrLights" : {' + '\n' +
'            "state" : "Off"' + '\n' +
'         }' + '\n' +
'      }' + '\n' +
'   }' + '\n' +
']'));} catch(e) {return {};}})(),'value.IrLights.state'));
```

Identical JS Code and Blockly in v7.0.1
<img width="518" alt="image" src="https://user-images.githubusercontent.com/39678667/220735417-e0f6fc8a-5eca-4800-ab78-ca3c71ecf7fc.png">

**Comment by Diginix** [comment]
![image](https://user-images.githubusercontent.com/39678667/220736458-5acbd436-a921-42b4-905d-b0e05d68236c.png)

Sample from @GermanBluefox doesn't work as well with v7.0.1

**Comment by winnyschuster** [comment]
i'd bet that update of JS-Adapter wasn't successful. V7.xx puts **await jsonataExpression()** which cannot be seen in your code(**await** is missing). Can you please double check in Adaper-TAB which version it shows?

**Comment by winnyschuster** [comment]
@Diginix if you like we can solve this in Forum, thats a better place. V7 definitely works well in my opinion

**Comment by Diginix** [comment]
@winnyschuster 
CLI:

> iobroker upgrade javascript -y
> Update javascript from @6.1.4 to @7.0.1
> NPM version: 8.19.3
> Installing iobroker.javascript@7.0.1... (System call)
> 
> removed 871 packages, and changed 8 packages in 53s
> 
> 92 packages are looking for funding
>   run `npm fund` for details
> Update "system.adapter.javascript.0"
> upload [261] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript
> upload [250] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg
> upload [200] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/uk.js google-blockly/own/msg/uk.js application/javascript
> upload [150] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Amplifier.6f5d18048328386033f8.svg static/media/Amplifier.6f5d18048328386033f8.svg image/svg+xml
> upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Heater.b53bccc334bbb9238a36.svg static/media/Heater.b53bccc334bbb9238a36.svg image/svg+xml
> upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Light.21f1a5dfcc93f8ba1214.svg static/media/Light.21f1a5dfcc93f8ba1214.svg image/svg+xml
> upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Office.7e6a38218390b655e270.svg static/media/Office.7e6a38218390b655e270.svg image/svg+xml
> upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Receiver.26b5ae166395a6dcb83f.svg static/media/Receiver.26b5ae166395a6dcb83f.svg image/svg+xml
> upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Speaker.db548379676317470c4f.svg static/media/Speaker.db548379676317470c4f.svg image/svg+xml
> upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Toilet.83604dd2daafb67067dd.svg static/media/Toilet.83604dd2daafb67067dd.svg image/svg+xml
> upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/Water.f50411984c5c24fa574d.svg static/media/Water.f50411984c5c24fa574d.svg image/svg+xml
> upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/media/names.e7efb5283d98000c74ac.txt static/media/names.e7efb5283d98000c74ac.txt text/plain
> upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.js vs/editor/editor.main.js application/javascript
> upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.de.js vs/editor/editor.main.nls.de.js application/javascript
> upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.es.js vs/editor/editor.main.nls.es.js application/javascript
> upload [17] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.fr.js vs/editor/editor.main.nls.fr.js application/javascript
> upload [16] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.it.js vs/editor/editor.main.nls.it.js application/javascript
> upload [15] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.ja.js vs/editor/editor.main.nls.ja.js application/javascript
> upload [14] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.js vs/editor/editor.main.nls.js application/javascript
> upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.ko.js vs/editor/editor.main.nls.ko.js application/javascript
> upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.ru.js vs/editor/editor.main.nls.ru.js application/javascript
> upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.zh-cn.js vs/editor/editor.main.nls.zh-cn.js application/javascript
> upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.zh-tw.js vs/editor/editor.main.nls.zh-tw.js application/javascript
> upload [9] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/css/cssMode.js vs/language/css/cssMode.js application/javascript
> upload [8] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/css/cssWorker.js vs/language/css/cssWorker.js application/javascript
> upload [7] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/html/htmlMode.js vs/language/html/htmlMode.js application/javascript
> upload [6] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/html/htmlWorker.js vs/language/html/htmlWorker.js application/javascript
> upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/json/jsonMode.js vs/language/json/jsonMode.js application/javascript
> upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/json/jsonWorker.js vs/language/json/jsonWorker.js application/javascript
> upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsMode.js vs/language/typescript/tsMode.js application/javascript
> upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsWorker.js vs/language/typescript/tsWorker.js application/javascript
> upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/loader.js vs/loader.js application/javascript
> upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/monaco.d.ts vs/monaco.d.ts video/mp2t
> 

/opt/iobroker/package.json says: 
`"iobroker.javascript": "7.0.1",`

Admin:
![image](https://user-images.githubusercontent.com/39678667/220845771-36e8d1d3-c78a-4190-b011-772f6ca5dce6.png)

Commit ist auch im Code angekommen: https://github.com/ioBroker/ioBroker.javascript/commit/a1a422b9881d651e6ad11132df950f043bc489de

Und trotzdem liefert @GermanBluefox Bsp weiterhin:
![image](https://user-images.githubusercontent.com/39678667/220846585-f6f2dc19-6a36-44c7-999b-81feaff9b075.png)

Ich habe keine Idee wo da was individuell falsch sein soll. Vor allem weil JSONata nach jedem Rollback auf 6.1.4 sofort wieder in allen Skripten funktioniert.

**Comment by Apollon77** [comment]
Hast Du mal das Blockly "angefast" ... also einen block vershcoben und zurück geschoben oder so? Dann wird das JS neu generiert. Gehts danach?

**Comment by Diginix** [comment]
ja klar, immer. Skript_1 Blockly mit dem Test habe ich jedes mal komplett neu erstellt. Nun extra noch mal um 100% sicher zu sein.
Habe neue Blocks rein, das JSON im Text geändert usw.
JS bleibt:
`console.log(jsonataExpression((function () { try {return JSON.parse('{"a":[1, 2, 3]}');} catch(e) {return {};}})(),'a[0]'));`

Obwohl in Zeile 370 /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/blocks_convert.js steht:
```
Blockly.JavaScript.convert_jsonata = function (block) {
    return ['(await jsonataExpression(' + Blockly.JavaScript.valueToCode(block, 'TARGET', Blockly.JavaScript.ORDER_ATOMIC) + ',' + Blockly.JavaScript.valueToCode(block, 'EXPRESSION', Blockly.JavaScript.ORDER_ATOMIC) + '))', Blockly.JavaScript.ORDER_ATOMIC];
};
```

**Comment by winnyschuster** [comment]
> Vor allem weil JSONata nach jedem Rollback auf 6.1.4 sofort wieder in allen Skripten funktioniert.

Die 6.1.4 verwendet eine ältere Version von JSONata, welche kein await benötigt. JSONata wird durch diese Umstellung erheblich schneller

Da Blockly im Browser läuft könnte ich mir noch ein Cache Problem vorstellen, bewege mich da aber auf dünnem Eis. In den Dev-Tools deines Browsers (F12) mal den Cache deaktivieren und die Seite neu laden könnte helfen. Danach die Blöcke bewegen bis zum Speichern aufgefordert wird. Danach sollte das await aber auftauchen

**Comment by Diginix** [comment]
@winnyschuster Du bist mein Held!
Nach "clear site data" funktioniert es nun.

**Comment by str3000** [comment]
I updated. It works fine now. Thanks a lot.
