### ISSUE TITLE
setStateAsync: id not exists -> instance crash

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.javascript#1255]
**Describe the bug**  
If i use setStateAsync without await with a not existing id, the whole instance crash.

**To Reproduce**  
Try the following script:
```
    startScript();
    async function startScript() {

        try {
            setStateAsync("0_userdata.0.fuuu", true);

        } catch (err) {
            console.error(`error: ${err.message}, stack: ${err.stack}`);
        }
    }
```

**Expected behavior**  
instance should not crash, only an info / warn / error should shown in the log

**Screenshots & Logfiles**  
```
host.ioBroker-Dev | 2023-02-21 14:44:13.211 | warn | Do not restart adapter system.adapter.javascript.0 because restart loop detected
-- | -- | -- | --
host.ioBroker-Dev | 2023-02-21 14:44:13.211 | info | Restart adapter system.adapter.javascript.0 because enabled
host.ioBroker-Dev | 2023-02-21 14:44:13.211 | error | instance system.adapter.javascript.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
javascript.0 | 2023-02-21 14:44:12.673 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
```

**Versions:**  
 - Adapter version: 6.1.4
 - JS-Controller version: 4.0.24
 - Node version: 16.x
 - Operating system: ubuntu

**Comment by GermanBluefox** [comment]
Fast solution is:
```
startScript();
async function startScript() {

    setStateAsync("0_userdata.0.fuuu", true)
        .catch(err => console.error(`error: ${err.message}, stack: ${err.stack}`));
        
}
```
But yes, you are right and the instance should not crash. But just now I don't know how to catch unhandled rejection in node.js

**Comment by Apollon77** [comment]
@Scrounger The solution is easy!! if you call an async method use await !! then also your try/catch will work as expected

**Comment by Scrounger** [comment]
@Apollon77 
It is clear that you should use await. But there are use cases where you want to execute something asynchronously. Here you can use setState or setStateAsync.
Since I got used to use only the async methods, I stumbled over it.

I am of the same opinion as @GermanBluefox. The instance should not crash. At least not if you use try{} catch{}.
Wouldn't it be better to leave the issue open even if you don't have a solution at the moment? Think that this bug should be fixed in the long term?

**Comment by Apollon77** [comment]
The problem is that Nodejs 16 changed the default, so an unhandled rejhection will ALWAYS end the instance, even if catched ... we still search for options
