### ISSUE TITLE
TS checks do not know existing "request" module (and others ?)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#126]
According to https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/en/javascript.md#require---load-some-module some modules are already existing, and especially reuest is also unneeded to be required at all and exists as "request" variable.

TS checks currently show an error/unknown info

**Comment by AlCalzone** [comment]
`request` is exposed by default, the remaining modules are only accessible through `require`.
