### ISSUE TITLE
Can't update from 6.0.3 to 6.1.4

### ISSUE THREAD

**Issue by binarious** [ioBroker/ioBroker.javascript#1261]
**Describe the bug**  
I can't update the adapter from 6.0.3 to 6.1.4.

**To Reproduce**  
Click on "Update" in the adapters view.

**Expected behavior**  
Successful update.

**Screenshots & Logfiles**  
```
$ iobroker upgrade javascript@6.1.4 --debug
Update javascript from @6.0.3 to @6.1.4
NPM version: 8.19.3
Installing iobroker.javascript@6.1.4... (System call)
npm ERR! code ENOTEMPTY
host.0f8d211e0d52 Cannot install iobroker.javascript@6.1.4: 217
ERROR: Process exited with code 25
```

**Versions:**  
 - Adapter version: 6.0.3
 - JS-Controller version: 4.0.23
 - Node version: 16.19.1
 - Operating system: Docker: buanet/iobroker:latest-v7 @9d287b1e42304d9fcfe7b06ecd891b61c6578e86cfaae1ad2ec5853f9c628bec

**Comment by Apollon77** [comment]
see Forum https://forum.iobroker.net/topic/57337/fehler-25-217-oder-enotempty-bei-adapter-install-update
