### ISSUE TITLE
Blockly 7.01: Objekttyp und Zustandstyp sind vertauscht

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1262]
Die Auswahl "Zustandstyp" (besser "Datenpunkttyp") erzeugt den Code für den Objekttyp.
"Objekttyp" erzeugt den Code für den Datenpunkttyp.
Anstelle von "Zustands-Einheit" besser "Maßeinheit" verwenden.

**Comment by klein0r** [comment]
Kann ich in der aktuellen Beta (7.0.3) nicht reproduzieren. Passt alles.

**Comment by paul53** [comment]
Wurde inzwischen korrigiert.
