### ISSUE TITLE
System --> Object ID shown 3 times

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.javascript#1265]
Using 7.0.1 JS version.
The Object ID Block is shown 3 times in the System tab, which for me doesn't make sense.
Just a small issue, but probably a quick fix.

![grafik](https://user-images.githubusercontent.com/8447146/221714476-0fa3edc8-d221-4200-b807-be68299b2679.png)

**Comment by Diginix** [comment]
With v6 it was the same. Has nothing to do with the update. I was confused the first time as well, but don't care since then. ;-)

**Comment by ScumbagSteve** [comment]
Yeah that’s correct. I used the new major update as an occasion to create an issue, as it’s still not fixed. As you said, not so important, but still a bug I guess and I have not found an issue so far. Am 28.02.2023 um 07:45 schrieb Diginix ***@***.***>:﻿
With v6 it was the same. Has nothing to do with the update. I was confused the first time as well, but don't care since then. ;-)

**Comment by klein0r** [comment]
I've fixed it in #1313
