### ISSUE TITLE
allow createState not only in 0_userdata.0

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#1288]
I need it under mqtt.0.* to be able to create new topics for a device that supports this officially.

**Comment by mcm1957** [comment]
Should this feature not better implemented by those (I think few) adapters who really need to create states from "outside" ? The adapter must be prepared to recognize such states anyway.

Personally I think creating states at random places (at foreign adapters) should not be possible.

**Comment by Diginix** [comment]
I don't care how and where. I have tried Blockly "SendTo" with mqtt.0 and topic, but doesn't work.
Maybe I don't understand the whole mqtt stuff yet.
I need "mqtt.0.*.custom" and then "mqtt.0.*.custom.foo","mqtt.0.*.custom.bar" etc. (* stands for the device, that supports custom topics). https://blueforcer.github.io/awtrix-light/#/api?id=add-custom-app
If there is another (official) way to solve this, please let me know.

**Comment by Diginix** [comment]
Problem is very old: 
https://github.com/ioBroker/ioBroker.mqtt/issues/240
https://github.com/ioBroker/ioBroker.admin/issues/1067

**Comment by mickym2** [comment]
I just created how to create topics with blockly. 

![image](https://user-images.githubusercontent.com/58858526/230664806-87c4e83d-acb1-49a7-8035-ad3d5b5c9553.png)

You need to user mqtt.0 instead.

**Comment by Diginix** [comment]
@mickym2 didn't work for me with js-controller 4.0.24, admin 6.4.3, javascript 7.0.3 and mqtt 4.1.1
I have import your blockly and changed it to mqtt.0 and I have created the same blockly from scratch.

**Comment by mickym2** [comment]
You see on my screen shot - that it should work. So I can say it should work in principle. Why it didn't - I cant tell you.

**Comment by Diginix** [comment]
What are you software versions?
And for sure I need it not directly below mqtt.0 but inside an already existing device. But I've tried your path and one level deeper below my device. And can you please show your mqtt instance settings?

![image](https://user-images.githubusercontent.com/39678667/230671830-4fcf72a4-56f0-4595-be08-b4e2a03fe94f.png)

**Comment by mickym2** [comment]
your mqtt settings are correct - I would switch of all options. However I use the adapter not as broker - i use it as mqtt-client

JS it is also 7.0.3, all other adapter versions are stable not beta versions. mqtt: 4.0.7 and admin 6.3.5

**Comment by mickym2** [comment]
In each case you can create the topics manually - go to a folder and then create a new data topic - you need to switch to expert mode.

**Comment by Diginix** [comment]
I will try it with an mqtt.1 instance as client. Maybe this is the important point! Only clients can publish states.
Lets see.
The manually way I go at the moment, but I don't like such workarounds. If you start from scratch then I want that all my scripts create all needed objects automatically.

**Comment by Diginix** [comment]
With an additional instance as client I can create own topics in the server instance below real devices!
Many thanks to @mickym2

**Comment by GermanBluefox** [comment]
You always can use setObject, but only with javascript and not blockly
