### ISSUE TITLE
setState stores wrong variable

### ISSUE THREAD

**Issue by etv99** [ioBroker/ioBroker.javascript#1292]
Hi,
I have found a problem when storing variables in a script.
In the attached script I calculate some power consumption variables and store them to use it in VIS and in a sum-up script to calc daily, weekly and monthly consumptions (the old Betriebsstundenzähler Script by looxer).

I have wondered why the sum-up script will do fancy things and found this:

When I monitor the sql logging of this object, I will get the wrong "summe2" value stored in this object and 3 ms later the right "summe3" value. So no problem for sql, since you can filter them with the "Entprellzeit" - so no wrong values are in the database.

summe2 is calculated in line 83 (this are the smaller values with 4xx or 3xx 
summe 3 is calculated in line 91 (and logged correctly in line 92!) this are the larger values with 73xx
but stored wrong in line 97.

BUT, the other script is triggered via the on.... command, and so will be triggered two times - first with the wrong value and then again with the right value. Since this script is checking the difference of the values and sum them up, it "counts wrong"!

Why is javascript storing first the wrong value???

[script.txt](https://github.com/ioBroker/ioBroker.javascript/files/11199516/script.txt)
![sql_values](https://user-images.githubusercontent.com/35922626/231138929-66edc5bc-1684-4823-96eb-12fa5e68fd6b.jpg)

**Comment by Apollon77** [comment]
It does that because:

> var id_Verbrauch_akt_ges = '0_userdata.0.Energie.Verbrauch_gesamt';
> var id_Verbrauch_ges_heute = '0_userdata.0.Energie.Verbrauch_gesamt';

>         setState(id_Verbrauch_akt_ges, summe2, true);
>         setState(id_Verbrauch_ges_heute, summe3, true);

So all as intended by your script ... you simply store it in the same OD

**Comment by etv99** [comment]
🙈...sorry!!
*Thomas Exel*
*ETV Bewegtbild Manufaktur*
Ahornweg 3/2
8144 Tobelbad
www.etv-bewegtbild-manufaktur.at
Mob.: +43 676 / 636-18-81


Am Mi., 12. Apr. 2023 um 08:49 Uhr schrieb Ingo Fischer <
***@***.***>:
