### ISSUE TITLE
Astrofunktion geht nicht immer oder nur teilweise

### ISSUE THREAD

**Issue by tommyMX** [ioBroker/ioBroker.javascript#1296]
Hallo,

ich habe zwei Blockly mit Astrofunktion.

Bei dem hier gehts:

<img width="485" alt="Bildschirm­foto 2023-04-24 um 20 21 59" src="https://user-images.githubusercontent.com/36209886/234082995-3704e67a-6394-4cfd-924b-9d77a33fe280.png">

Bei dem hier nicht:

<img width="451" alt="Bildschirm­foto 2023-04-24 um 20 20 46" src="https://user-images.githubusercontent.com/36209886/234083002-ea9f283f-6503-409a-902b-b82d85aecf4d.png">

Woran kann das liegen?

Danke

**Comment by klein0r** [comment]
Please provide more information (like a debug log, exact versions of the javascript adapter and adapter config).
