### ISSUE TITLE
Definiert man Variablen mit `var` anstatt mit `let` öfter, so wird kein Fehler erkannt

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.javascript#1308]
javascript v7.0.3
https://forum.iobroker.net/topic/65258/result-funktion-von-influxdb-adapter-richtig-nutzen

**Comment by mcm1957** [comment]
As far as I know this is the standard behavior of javascript and NO problem.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var?retiredLocale=de

```
Re-Declaring JavaScript Variables
If you re-declare a JavaScript variable declared with var, it will not lose its value.

The variable carName will still have the value "Volvo" after the execution of these statements:

Example
var carName = "Volvo";
var carName;
```

So you should drop using the old "var" keyword and start using the upo to date syntax let / const.

**Comment by GermanBluefox** [comment]
standard behavior of javascript
