### ISSUE TITLE
Astrofunktion im Norden

### ISSUE THREAD

**Issue by Karzk** [ioBroker/ioBroker.javascript#1309]
Guten Abend,

lt. Recherche gibt es aktuell im Norden Deutschlands keine Nacht und demzufolge auch kein Nachtende. Angeblich soll diese Fehlermeldung seit 2017 Geschichte sein. Gibt es hierzu eine Lösung? 
Bin von v.6.1.4 auf 7.0.3 hoch. Der Fehler bleibt vorhanden.

![image](https://github.com/ioBroker/ioBroker.javascript/assets/34375820/2b0c4ecc-427f-45b9-a112-f2c1c5e2db74)

**Comment by Apollon77** [comment]
Naja, nee "geschichte" ist sie nicht -- wie denn auch? Wenn Du "Night end verlangst es aber kein night end gibt dann ist hier alles korrekt. die Frage wäre eher ob es sinn macht im Skript etwas anderes zu nutzen

**Comment by Apollon77** [comment]
hm ... something is triggering the error ...

**Comment by Karzk** [comment]
thanks found it :-)

**Comment by mcm1957** [comment]
>Wenn Du "Night end verlangst es aber kein night end gibt dann ist hier alles korrekt. 

Na ja, ich würde in den Fall erwarten, dass z.B. 'null' o.ä. als Ergebnis geliefert wird, also "existiert nicht". Einen Eintrag im Log hätte ich nicht erwartet. Will aber die Diskussion nicht unnötigt aufblähen.

@Karzk 
Könntest kurz sagen was das Problem war?

**Comment by Karzk** [comment]
Ich habe tatsächlich in einem Skript auf Night End getriggert, ich konnte Night End mit einer Uhrzeit ersetzen und die Meldung war weg.

**Comment by mcm1957** [comment]
Ok
Wär für mich aber auch kein Grund für mehr alsxeine debug meldung. Kein nightend heisdt dann einfach kein trigger ...
Aber ist ne pers Meinung.

**Comment by Apollon77** [comment]
ALsoja lower auf info level macht sinn

**Comment by Dreistein19** [comment]
Der Vorteil ist ja, das die nervige Meldung nach ein paar Wochen wieder verschwindet wenn die Sonne bei uns im Norden wieder Tiefer steht.
Bis dahin müllt sie halt das Log voll bis es Platzt.
