### ISSUE TITLE
Don't turn on/off script by set state when option 'Do not subscribe all states on start' is true.

### ISSUE THREAD

**Issue by om2804** [ioBroker/ioBroker.javascript#1311]
**Describe the bug**  
Don't turn on/off script by set state 'javascript.0.scriptEnabled.*' when option 'Do not subscribe all states on start' is true.

**To Reproduce**  
1. Go to setting adapter
2. Set option 'Do not subscribe all states on start' as true.
3. Go to Objects section
3. Set state 'javascript.0.scriptEnabled.*' as false
4. script is not stopped.

**Expected behavior**  
set state 'javascript.0.scriptEnabled.*' false - turn off script
set state 'javascript.0.scriptEnabled.*' true- turn on script

**Screenshots & Logfiles**  
![Screenshot_1](https://github.com/ioBroker/ioBroker.javascript/assets/2576620/142b5bcd-4624-40be-8aad-6ba898f12956)
![Screenshot_2](https://github.com/ioBroker/ioBroker.javascript/assets/2576620/05648641-35ec-42eb-b439-c0d746ca56f6)

**Versions:**  
 - Adapter version: 6.4.1

**Comment by klein0r** [comment]
Tested with 7.1.0 and works like expected. Please check

**Comment by Hartmut-vonBerg** [comment]
just installed 7.1.1 - still same issue as described by [om2804]

**Comment by om2804** [comment]
last stable 7.0.3, same bug

**Comment by klein0r** [comment]
Please test with 7.1.4
