### ISSUE TITLE
Blockly Trigger gestaucht

### ISSUE THREAD

**Issue by Fichte79** [ioBroker/ioBroker.javascript#1323]
Hallo zusammen

Ich habe der Version 7.0.4 und 7.0.5 das Problem das der Trigger im Blockly gestaucht ist (siehe Bild).

![image](https://github.com/ioBroker/ioBroker.javascript/assets/107550931/8bbdda66-9bbb-4350-b4af-8235bef761fd)
![image](https://github.com/ioBroker/ioBroker.javascript/assets/107550931/2bce70e9-13eb-4ef0-8193-b66923074e6f)

Ich Arbeite mit Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)
Im Firefox ist das selbe Problem.
Habe schon System Neugestartet, alles an Updates und Version geprüft (Node & NPM).
Cache geleert und Cookies gelöscht.
Node.js v18.16.0
NPM 9.5.1

Bis Version 7.0.3 Funktioniert alles reibungslos.

Mit freundlichen Gruß

**Comment by klein0r** [comment]
Dann gibt es einen Fehler im Browser / JavaScript. Bitte mal in die Entwickler-Console vom Browser schauen was genau da falsch läuft bzw. die Fehlermeldung (inkl. Stack) hier rein kopieren.

**Comment by Fichte79** [comment]
Die Kategorien "Sonstige", "Eigene", "Entwicklung" und "Muster" kommen aus dem Blockly Plus.
Den habe ich auch schon Deinstalliert und gedacht das es daran liegt. Aber leider ist der Fehler immer noch.

Meinst du diese Fehler?

![image](https://github.com/ioBroker/ioBroker.javascript/assets/107550931/cc13ee3b-d310-4a21-840a-457f591c6fa5)

**Comment by klein0r** [comment]
Ah, habe den Fehler. Gibts gleich einen PR.

**Comment by klein0r** [comment]
> Das heisst?

Dass das in der nächsten Version nicht mehr passiert. Siehe commit oben
