### ISSUE TITLE
V 7.0.5: Extract-Code-Fehler bei eigenen Blockly-Funktionen

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.javascript#1328]
Nach dem Update auf Version 7.0.5 erhalte ich bei allen Scripts, die eine eigene Funktion enthalten, beim Öffnen die Fehlermeldung "Cannot extract Blockly code!".
Das Erstellen neuer Blockly-Funktionen ist kein Problem.

Nach Rückkehr zu V 7.0.3 ist die Script-Welt wieder in Ordnung, auch die in 7.0.5 erstellten eigenen Funktionen funktionieren.

Vielen Dank,
Achim

**Comment by Menne01** [comment]
Hallo,
bei mir sind in der Version 7.0.5 die Trigger kaputt.

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/89869516/998a4289-002c-44ae-aa60-b0f4fa94461c)

und folgende Fehlermeldung beim Schießen eines Blockly Scriptes

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/89869516/c115fab5-d9d0-48be-8446-5516376fe83a)

Grüße

**Comment by jocker545** [comment]
Ich habe das gleiche Problem.     v: 7.0.5
Plattform: docker
Node.js: v18.16.0
NPM: 9.5.1

**Comment by OberfragGER** [comment]
Hier,

bei mir genau das gleiche Verhalten.

**Comment by de3d0300** [comment]
Kann/Muss mich anschliessen. Gleiches Fehlerbild.

**Comment by AlfredSch** [comment]
Hallo zusammen,
bei mir genau das gleiche Verhalten.

**Comment by Menne01** [comment]
Hi,
in der Versiuon 7.1.0 ist bei mir der Bug behoben.
Das Issue kann meinetwegen geschlossen werden.

Grüße

**Comment by backfisch88** [comment]
> Hi, in der Versiuon 7.1.0 ist bei mir der Bug behoben. Das Issue kann meinetwegen geschlossen werden.
> 
> Grüße

bei mir seit 7.1.0 wieder existent :D

**Comment by Eistee82** [comment]
Bekomme den Fehler immer noch mit Adapter 7.1.1
Hier der Javascript code des Blockly der mit 7.0.3 noch funktioniert
Export aus 7.0.3: https://gist.github.com/Eistee82/c18164233810a1a2631b199a1e9d46a4
Javascript Code der mir in 7.1.1 angezeigt wird wenn ich oben rechts umschalte: https://gist.github.com/Eistee82/55620e28ba96ac44873a8783278b8244

**Comment by Eistee82** [comment]
Adapter 7.1.4 still has the Problem:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/1881217/86213804-0fd5-4990-b447-64b4c6deb4d9)

I'm going back to 7.0.3 wich is working fine.

**Comment by backfisch88** [comment]
> Adapter 7.1.4 still has the Problem: ![image](https://user-images.githubusercontent.com/1881217/260224581-86213804-0fd5-4990-b447-64b4c6deb4d9.png)
> 
> I'm going back to 7.0.3 wich is working fine.

Das Problem ist blockly plus. Deinstallieren. Geht. 
Musst halt alle Blöcke ersetzen und selber bauen in JavaScript

**Comment by Eistee82** [comment]
> Das Problem ist blockly plus. Deinstallieren. Geht. Musst halt alle Blöcke ersetzen und selber bauen in JavaScript

Danke. Genau das war das Problem. Aber so sieht Blockly nun total unübersichtlich aus. Warum können die logischen Verknüpfungen immer nur 2 Operanden in iobroker? Kann man das nicht mal variabel machen?

**Comment by backfisch88** [comment]
Steht 

> > Das Problem ist blockly plus. Deinstallieren. Geht. Musst halt alle Blöcke ersetzen und selber bauen in JavaScript
> 
> Danke. Genau das war das Problem. Aber so sieht Blockly nun total unübersichtlich aus. Warum können die logischen Verknüpfungen immer nur 2 Operanden in iobroker? Kann man das nicht mal variabel machen?


Steht wohl auf der todo Liste. Habe mit eigene Blöcke per Java Script gebaut

**Comment by firebowl** [comment]
> > Adapter 7.1.4 still has the Problem: ![image](https://user-images.githubusercontent.com/1881217/260224581-86213804-0fd5-4990-b447-64b4c6deb4d9.png)
> > I'm going back to 7.0.3 wich is working fine.
> 
> Das Problem ist blockly plus. Deinstallieren. Geht. Musst halt alle Blöcke ersetzen und selber bauen in JavaScript

Hab kein Blockly Plus installiert und trotzdem das Problem mir der Version 7.0.3

**Comment by firebowl** [comment]
Gleicher Fehler auch mit der 7.1.4

**Comment by Menne01** [comment]
Kann ich alles nicht nach vollziehen. V 7.1.4 
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/89869516/4d9b8b8c-5bc0-4d6c-ac8b-b9fbb6276392)

**Comment by firebowl** [comment]
Passiert auch nicht bei allen Scripts. Ich habe mehrere sehr ähnliche und bei einigen tritt es auf und bei anderen nicht. 
Kann gern zwei Varianten zum Vergleich zur Verfügung stellen.

**Comment by Menne01** [comment]
Ich bitte drum

**Comment by firebowl** [comment]
Das ist jetzt mehr als schräg.
Hab die betroffenen Scripte jetzt mehrmals geöffnet und den Baum links auf- und zugeklappt und irgendwann ist das Blockly erschienen und nach dem speichern kann ich es normal öffnen.
Allerdings kann ich jetzt keines meiner Scripte mehr bearbeiten, die Bausteine docken einfach nicht mehr an.
Wenn ich einen bereits angedocketen Baustein rausziehe und zurückschiebe dann dockt er auch nicht mehr an.
Manchmal sieht es so aus als ob er andocken möchte und dann springen die Bausteine umher.

**Comment by Menne01** [comment]
Sichere deine Scripte, deinstalliere den Javascript Adapter und installiere ihn neu. 
Sollte dann noch der Fehler kommen, würde ich neu aufsetzen. Da ist irgendwas krum. Mit Backitup geht das ja Ratz Fatz.
