### ISSUE TITLE
[Question] Mehrfachaufruf von Callbacks

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.javascript#1330]
Ist es extra so gewollt, dass callbacks in der messageTo / onMessage Funktion nur lediglich einmal aufgerufen werden können?

Diese Zeilen ergeben bei mir nur die Logausgabe "Aufruf"

`onMessage('testcallback', (data,callback) =>{
    callback("Aufruf");
        callback("zwei");
            callback("drei");
});

messageTo("testcallback",1,(dp)=>{
    log(dp)
});`

Woraus ich schließe, dass der Callback nur einmal aufgerufen wird.

**Comment by Apollon77** [comment]
Korrekt. Auf EINE Message die gesendet wird gibt es genau EINE Antwort
