### ISSUE TITLE
Nacht und Nachtende geben kein Date mehr aus

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.javascript#1331]
Astro Trigger funktionieren ebenfalls bei Nacht und Nachtende nicht mehr.
![image](https://github.com/ioBroker/ioBroker.javascript/assets/1881217/70002f5e-6b74-4789-8108-f4c1aa32b1a0)
Adapter 7.0.3
Controller 4.0.24

**Comment by Apollon77** [comment]
Naja ... du wohnst voraussichtlich nördlich von der Mitte von Deutschland, korrekt? Dann ist das zu dieser Zeit ggf durchaus normal. ... https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#schedule hast dazu eine noteb ...

Note: On some places sometimes it could be so, that no night/nightEnd exists. Please read https://github.com/mourner/suncalc/issues/70 about it.

Is maybe this the reason?

**Comment by Eistee82** [comment]
Sorry bin gerade im Urlaub Werd es nach meiner Rückkehr mal prüfen. Ich wohne ziemlich mittig in Nordhessen. Ich weiß gerade nur das es letztes Jahr noch funktionierte. Ich habe bei Nacht beginn immer eine Insektenfalle ausgeschaltet die nun immer an bleibt. Die sollte ab Dämmerung bis es dunkel ist an sein.

**Comment by Eistee82** [comment]
Liegt tatsächlich daran das es bei mir gerade keine Nacht gab. Ein Fehler über den man leicht stolpern kann...
