### ISSUE TITLE
V 7.0.8: Register 'Logik' - keine Elemente auswählbar

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.javascript#1333]
In dem Register 'Logik' scheinen alle Elemente oben übereinander zu liegen, kein Element ist auswählbar.
(getestet mit Edge und Firefox)

![iobroker_err_logik](https://github.com/ioBroker/ioBroker.javascript/assets/51128844/de845360-77fb-43c5-af83-e35cb0e0bb0c)

**Comment by AlfredSch** [comment]
Sieht bei mir auch so aus.

**Comment by stmb-100** [comment]
Bei mir auch

**Comment by klein0r** [comment]
Bitte mit 7.1.1 (bzw. der letzten beta) testen
