### ISSUE TITLE
V 7.0.8 Blockly Trigger-Block mit Einfachzuweisung: Anweisungen werden nicht in JS übersetzt

### ISSUE THREAD

**Issue by matthias81** [ioBroker/ioBroker.javascript#1339]
seit Version 7.0.8
Der Trigger-Block mit Einfachzuweisung wird nicht korrekt in JS übersetzt, der Anweisungsblock bleibt leer, es wird nur NaN übergeben:
Blockly:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/4223222/c3673fb2-d042-40ce-af9c-d8af0f4e2721)
Erzeugtes JS:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/4223222/fa2f257a-4b0c-4c80-9a2f-803da54ecbd5)
Trigger mit Mehrfachzuweisung funktionieren.
Somit werden alle bestehenden Scripte unbrauchbar, sobald man sie bearbeitet und nicht alle Trigger gegen welche mit Mehrfachzuweisung ersetzt.

**Comment by klein0r** [comment]
Please test with 7.1.0
