### ISSUE TITLE
Export all scripts does not work since v7.0.5

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.javascript#1340]
As written in the title, after updating from v7.0.3 to v7.0.5 or higher, the "Export all scripts" button no longer works. Only the following error is displayed in the interface: **File zip/system.host.Debian-PVEK/2023-06-13-scripts.zip not found**.

In version 7.0.3 the button "Export all scripts" still works fine, the file window for saving is opened normally. After updating to a higher version up to the latest 7.1.0 only this mentioned error occurs, exporting is not possible.

My test systems: 
Debian 11 and 12, OS everything up to date
repository latest, all iobroker adapters up to date except info and spotify-premium adapter
javascript: one instance (javascript.0)
js-controller v4.0.24
admin v6.5.8

Here are 2 additional screenshots for easier understanding

![javascript-1-640](https://github.com/ioBroker/ioBroker.javascript/assets/56516310/60a83856-8a68-4aa6-8484-0fa3aab7aaae)
![javascript-2-640](https://github.com/ioBroker/ioBroker.javascript/assets/56516310/413ccc66-f67f-40e9-aa2a-f712ddcb4b49)

**Comment by winnyschuster** [comment]
evtl. hängt das mit js-controller 5.x zusammen? da wird nicht mehr ins Dateisystem geschrieben sondern in die Datenbank. Entsprechend findet sich dein Output unter dem Tab Dateien/Admin.0/zip/2023-06-14-scripts.zip und kann von da ins Dateisystem geladen werden. Danach verschwindet der Eintrag! Ein direkter Download kann auch durch die Eingabe [dieses Links direkt im Browser](http://localhost:8081/files/admin.0/zip/2023-06-14-scripts.zip) erreicht werden. Dies nur als Workaround bis die Fehlermeldung gefixt ist

**Comment by Diginix** [comment]
Auch mit JS 7.1.1 und Controller 4.0.24 kann ich nicht mehr alle Skripte exportieren
bekomme ein 404 für "/adapter/javascript/zip/system.host.iobroker/2023-06-20-scripts.zip"

**Comment by Ilovegym66** [comment]
Mit Admin 6.5.9, Js-Controller 5.0.5, Javascript 7.1.1 funktioniert hier wieder!
Node 18.16.0, NPM 9.5.1, Debian Bullseye.

**Comment by winnyschuster** [comment]
> Auch mit JS 7.1.1 und Controller 4.0.24 kann ich nicht mehr alle Skripte exportieren bekomme ein 404 für "/adapter/javascript/zip/system.host.iobroker/2023-06-20-scripts.zip"

kann ich bestätigen, mit 4.0.24 funktioniert kein Scriptexport

**Comment by sigi2345** [comment]
Fehler:
![Screenshot (119)](https://github.com/ioBroker/ioBroker.javascript/assets/41079106/2d9bc111-fa27-4821-ba96-c9dc07bc63d3)

**Comment by Apollon77** [comment]
fixed 7.1.1

**Comment by Diginix** [comment]
Not with JS-Controller 4 ;)
see comment: https://github.com/ioBroker/ioBroker.javascript/issues/1340#issuecomment-1598773725

**Comment by GermanBluefox** [comment]
Js-Controller 4 is in the past.

**Comment by Eistee82** [comment]
Bekomme den Fehler immer noch mit Adapter 7.1.1
Hier der Javascript code des Blockly der mit 7.0.3 noch funktioniert
https://gist.github.com/Eistee82/55620e28ba96ac44873a8783278b8244

**Comment by Eistee82** [comment]
Its not fixed! all is up to date from beta repository except javascript which is only working in 7.0.3. All later versions have this bug.

**Comment by Eistee82** [comment]
Adapter 7.0.3: 
![image](https://github.com/ioBroker/ioBroker.javascript/assets/1881217/67f81ed6-6567-49b0-813d-719a620a61e2)

Adapter 7.1.1:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/1881217/0ddf55d7-351f-45dd-a033-750a1e045e05)

**Comment by GermanBluefox** [comment]
> Its not fixed! all is up to date from beta repository except javascript which is only working in 7.0.3. All later versions have this bug.

Which js-controler do you use?
