### ISSUE TITLE
Neue Blocks ala Blockly Plus

### ISSUE THREAD

**Issue by backfisch88** [ioBroker/ioBroker.javascript#1344]
Hallo

durch das Core Update funktioniert anscheinend Blockly Plus nicht mehr. Ist es Möglich zumindest die Multi UND ODER Blöcke zu übernehmen? Diese sind echt Hilfreich, anstatt mehrere UND ineinander zu schieben

Viele Grüße

**Comment by backfisch88** [comment]
doppelt

**Comment by klein0r** [comment]
Duplicate of #1031 and #649
