### ISSUE TITLE
Start and stop a script by another one

### ISSUE THREAD

**Issue by RaBu60** [ioBroker/ioBroker.javascript#1346]
I have the following problem:
I want to stop and / or restart from one JS- Script another.
This should work under Javascript.0.scriptEnabled... by setting the corresponding datapoint to false or true.

The corresponding datapoint was created automatically by the JS-Adapter.

The command
`setState("javascript.0.scriptEnabled.Hydrawise.Hydrawise", false, true);`

generates the following log entry:
`Own states should not be used in javascript.X.scriptEnabled.*! Please move the states to 0_userdata.0.*`

The version of my JS-Adapter is 7.0.3

**Comment by klein0r** [comment]
1. It's not best practice to start and stop scripts dynamically
2. If you set a state with `ack: true` nothing will happen (see last parameter)

**Comment by RaBu60** [comment]
> 1. Es ist keine bewährte Vorgehensweise, Skripte dynamisch zu starten und zu stoppen
> 2. Wenn Sie einen Status mit festlegen, `ack: true`passiert nichts (siehe letzter Parameter).
> 3. Bitte testen Sie mit der neuesten Beta – ich erhalte diese Warnung nicht

@klein0r 
Sorry für die späte Reaktion.
Es handelt sich hier um ein Script, welches alle <n> Minuten über schedule einen Web Request absetzt. Es gibt Datenpunkte unter 0_userdata.0... u.a. mit sog. Settings. Diese beinhalten z.B. UserId, bestimmte Keys u.a. 
Auch die Zeit der Abfragen <n> ist hier definiert.
Wenn nun diese Zeit geändert wird, muss das Script neu gestartet werden um die Minuten einzulesen.

Ich habe das Ganze nun über stopScript bzw. startScript gelöst. Ist m.E. nach auch die bessere Lösung.

Vielen Dank für Ihren Kommentar

**Comment by klein0r** [comment]
Okay, aber auch dann startet man Scripts nicht neu, sondern löscht den alten Trigger und registriert einen neuen Zeitplan.

> Ich habe das Ganze nun über stopScript bzw. startScript gelöst. Ist m.E. nach auch die bessere Lösung.

Wird nur (wie gesagt) von abgeraten.

**Comment by klein0r** [comment]
Weil ich gerade alle Issues durchgehe: Warum verwendest Du nicht

- `startScript` https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#startscript
- `stopScript` https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#stopscript
