### ISSUE TITLE
Blockly:: no editor tools when system is switch into Polish language

### ISSUE THREAD

**Issue by MaaG-dA** [ioBroker/ioBroker.javascript#1348]
**Describe the bug**  
Blockly editor not work when system is in polish language (and only in Polish)

**To Reproduce**  
1. Switch system language:
https://forum.iobroker.net/assets/uploads/files/1684534675732-blockly-problem1.png
2. select javascript edytor
3. add blockly script:
https://forum.iobroker.net/assets/uploads/files/1684534145178-blockly-problem.png

no tools for blockly :(

**Comment by klein0r** [comment]
Which adapter version?

**Comment by MaaG-dA** [comment]
Latest stable (7.0.3 ? - i check it today evening... if needed).

**Comment by MaaG-dA** [comment]
7.0.3

**Comment by MaaG-dA** [comment]
I downloaded the version and it looks much worse.. total lack of access to scripts
[https://forum.iobroker.net/assets/uploads/files/1689893334671-c0800fd9-be61-4e86-b923-d5694140a372-image.png](url)

**Comment by klein0r** [comment]
> I downloaded the version

There is no version which contains this fix right now
