### ISSUE TITLE
After updating to JS-Controller 5.0.7 we had a restart and weird SIGTERM messages

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.javascript#1363]
**Describe the bug**  

host.iobroker | 2023-07-12 09:43:25.740 | warn | instance system.adapter.web.0 terminated due to SIGTERM
-- | -- | -- | --
host.iobroker | 2023-07-12 09:43:25.648 | warn | instance system.adapter.parser.1 terminated due to SIGTERM
host.iobroker | 2023-07-12 09:43:25.647 | warn | instance system.adapter.echarts.0 terminated due to SIGTERM
host.iobroker | 2023-07-12 09:43:25.647 | warn | instance system.adapter.ping.1 terminated due to SIGTERM
host.iobroker | 2023-07-12 09:43:25.646 | warn | instance system.adapter.mqtt.0 terminated due to SIGTERM
host.iobroker | 2023-07-12 09:43:25.645 | warn | instance system.adapter.whatsapp-cmb.0 terminated due to SIGTERM
host.iobroker | 2023-07-12 09:43:25.643 | warn | instance system.adapter.telegram.0 terminated due to SIGTERM

And no other messages appear in the log.

Checking the adapter.web.0: It is NOT terminated, it seems to be running.

**To Reproduce**  
-

**Expected behavior**  
No SIGTERM messages but normal system messages in the log

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: web.0  5.5.3
 - JS-Controller version: 5.0.7  
 - Node version: v18.16.1  
 - Operating system: Debian 10

**Additional context**  
-

**Comment by Apollon77** [comment]
SIGTERM means that the OS killed the controller - or the controller killed not ending proceses. In fact only with more logs this is possible to find out. if it happened only once ... ignore ... if more often please provide more logs in Forum

**Comment by MichaelSchaaf999** [comment]
It seemed to have happened only once.
But since then no usual messages can be seen in the log, only a few:

<img width="1154" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/53481090/7c36c5cd-2c6f-4eb8-9b82-a4b057160983">

So this behaviour has changed: We expected to see many more messages as before.
So: Unfortunately more logs are not available. The log seems to be very quiet.
