### ISSUE TITLE
Sicherung aus dem Adapter heraus funktioniert nicht mehr - 

### ISSUE THREAD

**Issue by mamsis** [ioBroker/ioBroker.javascript#1366]
Wenn ich im Adapter auf alle Skripte exportieren gehe, bekomme ich als Fehlermeldung :
"File zip/system.host.raspberrypi/2023-07-25-scripts.zip not found"
Vorher sind die Skripte in einer "x.zip" downgeloaded worden und ich war auch in der Lage, ein einzelnes Script wiederherzustellen...
Was kann ich tun, damit dies wieder funktioniert?

**Comment by Ilovegym66** [comment]
Version von Admin, Javascript-Adapter und js-Controller, ohne diese Angaben supported die Glaskugel garnix.. :-)

**Comment by mamsis** [comment]
Hallo, ziehe den Einspruch zurück :)

Habe lange gescheut, den Host upzudaten, da es beim letzten Mal massive Probleme mit meinem Zigbee Adapter waren, habe es aber jetzt doch gewagt. Und was soll ich sagen, es klappt wieder. Sorry, hätte ich eher machen sollen :(

 

Von: Ilovegym66 ***@***.***> 
Gesendet: Dienstag, 25. Juli 2023 12:56
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: mamsis ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] Sicherung aus dem Adapter heraus funktioniert nicht mehr - (Issue #1366)

 

Version von Admin, Javascript-Adapter und js-Controller, ohne diese Angaben supported die Glaskugel garnix.. :-)
