### ISSUE TITLE
Restart Adapter bei requests mit Put oder Post

### ISSUE THREAD

**Issue by Snigga** [ioBroker/ioBroker.javascript#1377]
Adapter startet neu wenn ein request mit Post ausgeführt wird. Der Post wird nicht ausgeführt.

**Comment by klein0r** [comment]
Hast Du ein Beispiel-Script?

**Comment by Snigga** [comment]
war an mir gelegen hatte vor dem post in einer Schleife ein 'channel[state.id= gesetzt. dadurch war der Adapter dann überlastet und hat neu gestartet.
