### ISSUE TITLE
Block "der Fall ist" gibt Fehler "logic_switch_case: getState('select_any_state').val is not a variable name"

### ISSUE THREAD

**Issue by isi07** [ioBroker/ioBroker.javascript#1380]
Beim Verwenden des Blocks "der Fall ist" kommt es zu einer Fehlermeldung, wenn man einen beliebigen object state als input in "der Fall ist" verwendet.
Fehler "logic_switch_case: getState('select_any_state').val is not a variable name"

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/65848350/9f103bcc-3983-4826-907d-caa0383af66c)

Bei der Verwendung einer Variable oder des rigger-Wertes gibt es keinen Fehler.

**To Reproduce**  
1. Neues Blockly Script anlagen
2. Block "der Fall ist" einfügen
3. Block Block "Wert vom Objekt ID" einfügen
4. beliebige Objekt ID im Block "Wert vom Objekt ID" auswählen
5. Block "Wert vom Objekt ID" an den Block "Der Fall ist" an den Anschluss "der Fall ist" verbinden
6. es kommt zu der beschriebenen Fehlermeldung

**Expected behavior**  
Es sollte keine Fehlermeldung kommen, sondern der Wert eines Objektes solltes als input für den Block "der Fall ist" akzeptiert werden.

**Versions:**  
JS 7.1.4
JS-Controller 4.0.24
Admin 6.7.2
Node 18.17.1
NPM 9.6.7

**Comment by ScumbagSteve** [comment]
Da bin ich auch schon öfters drüber gestolpert (gestern zuletzt). Wäre super, wenn man das fixen könnte. 
Zwischendurch kann man den umweh gehen, eine Variable auf den Wert des DP zu setzen und dann die Case Anweisung auf die variable zu machen. 
Ist aber ein Workaround.

**Comment by isi07** [comment]
Es muss auch mal funktioniert haben. Alte Blockly-Scripte kann ich aufgrund dieser Fehlermeldung nicht mehr bearbeiten.

**Comment by florian1984** [comment]
yep hatte mal funktioniert. Habe bei mir gleiches Problem, komme leider nicht mal mehr ins script rein weils ständig wieder zu geht :(

**Comment by uob5** [comment]
Hallo zusammen, habe in einem bisher problemlos laufenden Blockly-Script plötzlich auch diese Fehlermeldung.
![image](https://github.com/ioBroker/ioBroker.javascript/assets/130152665/2cb49429-627a-4199-b143-d444e1e15409)
Komme an das Blockly nicht mehr ran, da sofort diese Fehlermeldung aufpoppt. 
Hat jemand einen Tipp wie man dies fixen kann?

**Comment by AngelArtur** [comment]
Bei mir auch so, seit dem letzte Update des script-adapters.

**Comment by LukyLuke1976** [comment]
Moin. Mich hats jetzt auch erwischt. Ich wollte ein neues script anlegen mit "der Fall ist" Funktion. Bei der Anheftung der Variablen sofort Fehlermeldung:
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/54706515/b5f6ddc3-e07d-46af-9fe2-c3649188301c)
Wenn nicht gespeichert ist alles weg.

**Comment by ScumbagSteve** [comment]
Ist zwar nur ein Workaround, aber ihr könnt den Adapter bis zum fix erst mal downgraden. Dann könnt ihr zumindest die Skripte anpassen. 

Wenn jemand die letzte funktionierende Version gefunden hat, kann er es ja kurz hier in die Kommentare packen.

**Comment by savek-cc** [comment]
@GermanBluefox dadurch sind viele Scripte aktuell nicht mehr editierbar - und neue können nicht angelegt werden. Gibt es schon eine Idee woran es liegt?

**Comment by bambi-arch** [comment]
Hab das gleiche Problem in Blockly. Bei 7.0.8 geht noch alles. Was super nervig ist, dass die Fehlermeldung das Skipt immer wieder neu läd. Dadruch ist keine Bearbeitung möglich!

**Comment by klein0r** [comment]
Got it... changed double quotes to single quotes, which is missing in the expression of the switch statement 😭 

7.0.8 Code

https://github.com/ioBroker/ioBroker.javascript/blob/d797b3b91f85fbd476f8a79b651dae44e3e7a638/src/public/google-blockly/own/blocks_switch.js#L203-L212

https://github.com/ioBroker/ioBroker.javascript/blob/d797b3b91f85fbd476f8a79b651dae44e3e7a638/src/public/google-blockly/own/blocks_system.js#L687-L695

----

7.1.6 Code

https://github.com/ioBroker/ioBroker.javascript/blob/6e37178ae4dafffca406b17c859cd03550bf5334/src/public/google-blockly/own/blocks_switch.js#L192-L201

https://github.com/ioBroker/ioBroker.javascript/blob/6e37178ae4dafffca406b17c859cd03550bf5334/src/public/google-blockly/own/blocks_system.js#L796-L805

**Comment by solar0x** [comment]
I do still have this issue with 7.1.6

<img width="604" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/95849152/c068c271-dc3e-4ebf-b8da-867607f1e1dc">

**Comment by klein0r** [comment]
@solar0x Of course - see changelog

https://github.com/ioBroker/ioBroker.javascript/blob/8d61e6d11f4895a163df71cef09ef72f20228c2c/README.md?plain=1#L49-L59

**Comment by MPTrixi** [comment]
> Fixed in 7.2.0

Hi, installed just adapter version 7.8.0  - still have this issue. Is there something else to update?
