### ISSUE TITLE
schedule does not accept a date

### ISSUE THREAD

**Issue by Giraffe1979** [ioBroker/ioBroker.javascript#1381]
Hey,
if I understand [this](https://www.iobroker.net/docu/index-81.htm?page_id=5809&lang=en#schedule) correctly, I can directly pass a date (typeof date) to the schedule function:

let switchOff:Date = new Date();
schedule(switchOff, function(obj){});

See:
![1691920790572-0c795701-0b45-4f17-a9e7-8d31acbe390b-grafik](https://github.com/ioBroker/ioBroker.js-controller/assets/138315064/3d5bba11-7c6c-4596-966d-77eed7c02559)

Unfortunately that doesn't work. a bug?

Thanks
giraffe

**Comment by klein0r** [comment]
Maybe related to #1374

**Comment by klein0r** [comment]
@Giraffe1979 Can you provide an example which is NOT working?

https://github.com/ioBroker/ioBroker.javascript/blob/51c5d45dcc9b20881180bf12d7a811d8826816cb/docs/en/javascript.md?plain=1#L514
