### ISSUE TITLE
Blockly - Implement "AND" with n inputs

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.javascript#1387]
It would be great to have a cog wheel that enables the "AND" blockly to have n (multiple) inputs.
Right now we have to put "and block" behind "and block", which becomes a bit messy after a few iterations.

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/8447146/186d5639-abf5-41bc-837e-1c050861aeae)

**Comment by Eistee82** [comment]
Pls with "Dynamic Connection Blocks" https://google.github.io/blockly-samples/

**Comment by ldittmar81** [comment]
Das wäre echt ein Segen, denn diese horizontale Zeilen, mit ewig lange Bedingeungen, sind einfach nicht mehr handelbar.

**Comment by klein0r** [comment]
See 7.7.0

**Comment by ScumbagSteve** [comment]
Danke, ich habe bereits geupdated und die Skripte umgestellt. Läuft schon seit ein paar Tagen stabil, sieht also gut aus. 👍🏻
