### ISSUE TITLE
getIdByName liefert zwei identische Werte

### ISSUE THREAD

**Issue by pepp86** [ioBroker/ioBroker.javascript#14]
Seit Version 3.0.10 liefert getIdByName bei manchen Aktoren zwei mal den gleichen Wert in einem Array.

Testskript:
`log(getIdByName("RL Arbeit"));`

Log:
`javascript.4 script.js.Test.Skript11: hm-rpc.0.LEQ1020140.1,hm-rpc.0.LEQ1020140`

**Comment by pepp86** [comment]
Beim Absenden den Fehler entdeckt. Mit der neuen Version findet die Funktion anscheinend alle Kanäle mit dem Namen.

Namen in der CCU korrigiert und nun läuft es wieder sauber.

**Comment by SPITZGITHUB** [comment]
Heute (11.,02.2024) wieder diesen Fehler 
log(getIdByName("RL Arbeit"));
Log:
javascript.4 script.js.Test.Skript11: hm-rpc.0.LEQ1020140.1,hm-rpc.0.LEQ1020140

Bekomme nun im JAVA-Script seit dem 29.01.2024 

**_console.log ("ID: " + getIdByName(R_ID_Name));
setState(getIdByName(R_ID_Name), R_Werte);_**

immer den Error:
State "hm-rega.0.1481,hm-rega.0.1481" not found, da der Name zweimal bei getIdByName zurückgegeben wird.!
Die Lösung oben: Name in der CCU korrigiert? Wie korrigiert???




</body>
</html>

**Comment by mcm1957** [comment]
> Heute (11.,02.2024) wieder diesen Fehler log(getIdByName("RL Arbeit")); Log: javascript.4 script.js.Test.Skript11: hm-rpc.0.LEQ1020140.1,hm-rpc.0.LEQ1020140
> 
> Bekomme nun im JAVA-Script seit dem 29.01.2024
> 
> **_console.log ("ID: " + getIdByName(R_ID_Name)); setState(getIdByName(R_ID_Name), R_Werte);_**
> 
> immer den Error: State "hm-rega.0.1481,hm-rega.0.1481" not found, da der Name zweimal bei getIdByName zurückgegeben wird.! Die Lösung oben: Name in der CCU korrigiert? Wie korrigiert???

Bist du dir bewußt dass du auf einen GESCHLOSSENES Issue aus dem Jahre 2016 (!) antwortest?

Bitte öffne für eine aktuelles Problem ein neues Issue. Ein Verweis auf das alte Issue ist ok - aber ob jemand Einträge hier sieht / liest ist nicht so wahrscheinlich.
