### ISSUE TITLE
V 7.1.4 Blockly: "setze timeout auf null" fügt zweite Variable timeout hinzu 

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1400]
In früheren Versionen (7.0.3) war es nicht der Fall. 
`var timeout, timeout;

timeout = setTimeout(async () => {
  timeout = null;
  timeout = null;
}, 1000);`
Die Funktion ist trotzdem gegeben.

**Comment by klein0r** [comment]
Ich kann nicht so richtig folgen. Wurde da eine separate Variable mit dem Namen `timeout` angelegt? Wenn ja: wozu?
