### ISSUE TITLE
Blockly: Falsche Darstellung eines Zeit-Bausteins nach dem Kopieren

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.javascript#1404]
JS-Adapter: 7.1.4
JS-Controller: 5.0.12
NodeJS: 18.16.0
OS: Buanet-Docker

Kopiert man den unten gezeigten Baustein, wird er solange falsch angezeigt, bis man das Skript neu lädt.

![blockly-zeit](https://github.com/ioBroker/ioBroker.javascript/assets/62850183/2e3c4c9a-fd72-4e71-a7b2-89253b61951c)

**Comment by Diginix** [comment]
Das ist schon seit Ewigkeiten so, also nichts neues durch v7.x. Ist auch nur ein rein kosmetischer Fehler.
Speichert und Öffnet man das Skript erneut, passt die Darstellung auch. Funktional passt es jederzeit.
Dennoch ist es nat. ein berechtigtes Issue. ;-)

**Comment by RP70DP** [comment]
Thanks a lot! Seems to be okay with v7.3.0. 
(I don't tested the functionality)
