### ISSUE TITLE
TypeScript: onMessage compilation failed using messageToAsync

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.javascript#1405]
**Describe the bug**  
using the messageToAsync example from the docs https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#messagetoasync throws an compilation failed error.

```
onMessage('myTopic', async (data, callback) => {
    console.log(data);

    if (!data.myPayload) {
        // return error (promise reject)
        callback({ error: 'something went wrong!!' });
    } else {
        // return result (promise resolve)
        callback({ result: 'ok' });
    }
});
```
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6370451/a86c50fc-3b55-4e31-8353-73465156fbce)

log:
```
2023-09-23 17:03:41.956  - error: javascript.2 (251355) script.js.test2: TypeScript compilation failed:
--
onMessage('myTopic', async (data, callback) => {
^
ERROR: Argument of type '(data: any, callback: any) => Promise' is not assignable to parameter of type 'SimpleCallback'.
Target signature provides too few arguments. Expected 2 or more, but got 1.
```

**Expected behavior**  
compilation should work

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 7.1.4
 - JS-Controller version: 5.0.12
 - Node version: 16
 - Operating system: ubuntu

**Comment by uwe72** [comment]
I have exactly the same problem. Can anybody help?

In einem JavaScript funktioniert der Code aus der Anleitung, in TypeScript nicht. Kann mir hier bitte jemand helfen?
```
onMessage('message1', (data, callback) => {
    console.log(`Received data: ${data}`); callback({ result: Date.now() });
});
```

```
javascript.0 (80776) script.js.common.Test2: TypeScript compilation failed: onMessage('message1', (data, callback) => { ^ ERROR: Argument of type '(data: any, callback: any) => void' is not assignable to parameter of type 'SimpleCallback<any>'. Target signature provides too few arguments. Expected 2 or more, but got 1.
```

**Comment by ticaki** [comment]
Soweit ich das sehe ist der Typ hier falsch: https://github.com/ioBroker/ioBroker.javascript/blob/8f2b1ae32c689070ee3fc91e5c19d1b1d682f135/lib/javascript.d.ts#L9
