### ISSUE TITLE
Latitude / Longitude werden nicht gespeichert

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.javascript#1406]
Hallo,

unter: system.adapter.javascript.0
bei native
wurden bisher o.g. Werte gespeichert:
Jetzt ist da nichts mehr drin.
![image](https://github.com/ioBroker/ioBroker.javascript/assets/25694404/8db69925-5003-41f1-b42e-67ae69ea34b5)

Bitte berichtigen und die Werte wieder abgreifen.

**Comment by Apollon77** [comment]
Ich glaube das wurde vor langem umgestellt das das System die Werte aus der Systemkonfiguration nutzt! lso den ioBroker Haupteinstellungen

**Comment by Apollon77** [comment]
Was meinst du mit "Übertragen"? In der konfig steht da nichts drin, dann lädt die Instanz das automatisch aus dem System. Das wirdf nichts an der Javascript konfig geändert, sondern beim start einfach das andere geladen und steht den skripten zur verfügung.

Was genau ist denn dein problem?

**Comment by bahnuhr** [comment]
Die Daten sind im System drin (Schraubenschlüssel oben). Lat und Long sind eingetragen.
Wenn ich in der Instanz nun den Haken setze bei: Systemeinstellungen verwenden müsste die Daten kommen bei:
javascript.0.native ....
Da kommt aber nichts an. Und somit funktionieren die Skripte natürlich nicht.

Hab ich mich einigermaßen verständlich ausgedrückt.

**Comment by winnyschuster** [comment]
> Da kommt aber nichts an

Das soll so. Nur wenn der Haken NICHT gesetzt ist werden da Werte reingeschrieben und das ist schon immer(tm) so.
```
if (getObject("system.adapter.javascript.0").native.useSystemGPS) {
    log("System " + getObject("system.config").common.latitude)
} else {
    log("Instance " + getObject("system.adapter.javascript.0").native.latitude)
}
```

**Comment by bahnuhr** [comment]
> das ist _schon immer(tm)_ so.

Nein, das stimmt definitiv nicht.

Ich musste in der Instanz Javascript noch nie was eingeben.
Dies wurde sich immer gezogen von der Systemeingabe.

Nun steht aber (trotz haken) bei javascript nichts mehr drin.

Und dies ist halt falsch.

**Comment by Apollon77** [comment]
ich wiederhole: Systemeinstellungen verwenden sorgt NICHT (und noch nie!) dafür das die Daten ins javascript objekt kopiert werden, sondern nur das sie intern genutzt werden. Wenn Du in "Native" von der JavaScript Instanz was haben willst musst du es da eintragen. Warum sollte man denn diese Daten duplizieren? Man würde dann ggf eigene Werte die man nur mal kurz deaktivieren will überschreiben. Sowas macht an sich keinen Sinn.

**Comment by Apollon77** [comment]
PS: Ok mein" war noch nie so" ist bitte als "ich kann mich nicht daran erinnern das es mal so was" zu verstehen .. ich werde da jetzt nicht im Code suchen ... in meiner Welt macht so ein vorhene aber auch keinen Sinn, von daher ist es jetzt wie es ist "as designed":

**Comment by bahnuhr** [comment]
Kein weiterer Input von mir.
Habe das Script "Sonne, Mond" geändert auf die Systemeinstellungen.
Vermute aber, dass ich nicht der Einzige bin, bei dem dies nicht mehr läuft.
