### ISSUE TITLE
on function is triggered, but newState, oldState and state are all with val false

### ISSUE THREAD

**Issue by pzystorm** [ioBroker/ioBroker.javascript#1418]
**Describe the bug**  
I have iobroker with the javascript and hm adapter. I own the device HmIP-BSM which I use to switch on a light.

The javascript code is this:
```
on({id: 'hm-rpc.1.000858A98A464D.5.STATE' }, function (obj) {
  log("hallotest " + JSON.stringify(obj));
});
```

The on function is triggered when I switch on/off the light (channel 5 is the light, not the button).

But the output from the log function is this:
```
javascript.0 (25741) script.js.test: hallotest {"id":"hm-rpc.1.000858A98A464D.5.STATE","newState":{"val":false,"ts":1696326367942,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"oldState":{"val":false,"ts":1696325467637,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"state":{"val":false,"ts":1696326367942,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"}}
```

Why is newState, oldState and state all "false"?
It does not matter whether I switch on or off - its always everything "false".

**To Reproduce**  
1. Use the script from above
2. Switch on the light
3. See newState, oldState and state as false in the log

**Expected behavior**  
If I switch on the light, the newState should be true.

**Versions:**  
 - Adapter version: 7.1.4
 - JS-Controller version: 4.0.23
 - Node version: v18.16.0
 - Operating system: Debian 11

**Comment by Apollon77** [comment]
The timestamps are different. between state/newState (which are same because of backward compatibility reasons) and oldState. Please see https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state

> Notice: Please note, that by default "change" is equal to "any", except when only id as string is set (like on("id", function (){});). In last case change will be set to "ne".

So "Works" as designed

**Comment by pzystorm** [comment]
Oh, thanks, good to know.
What is then the best practise in such cases how to determine from which state to which state is has changed?

**Comment by Apollon77** [comment]
Just use "ack: true" notifications because these are officially acknowledged by the device ... and then compare the values

**Comment by pzystorm** [comment]
Sorry, it does not work for me. Can you maybe help again? :) 

My script:
```
on({id: 'hm-rpc.1.000858A98A464D.5.STATE', ack: true }, function (obj) {
  log("obj: " + JSON.stringify(obj));
  log("val: " + getState('hm-rpc.1.000858A98A464D.5.STATE').val);
});
```

Light on:
javascript.0 (25741)  script.js.test: obj:  {"id":"hm-rpc.1.000858A98A464D.5.STATE","newState":{"val":false,"ts":1696381578241,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"oldState":{"val":false,"ts":1696381550993,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"state":{"val":false,"ts":1696381578241,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"}}
javascript.0 (25741) script.js.test: val: false

you see, every val is "false", in state, newState AND oldState

Light off:
javascript.0 (25741) script.js.test: obj: {"id":"hm-rpc.1.000858A98A464D.5.STATE","newState":{"val":false,"ts":1696381581988,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"oldState":{"val":false,"ts":1696381578241,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"},"state":{"val":false,"ts":1696381581988,"ack":true,"lc":1664652210947,"from":"system.adapter.hm-rpc.1","q":0,"user":"system.user.admin"}}
javascript.0 (25741) script.js.test: val: false

and here also every val is "false"

**Comment by Apollon77** [comment]
Maybe try with "change: "any"" first ... then you see all state changes that happen ... then it might be easier to see the reason for this behaviour

**Comment by pzystorm** [comment]
Oh, I've found the error.
The light for a HmIP-BSM is not channel 5, but channel 4 :(

After correcting to:
```
on({id: 'hm-rpc.1.000858A98A464D.4.STATE', ack: true }, function (obj) {
  log("obj: " + JSON.stringify(obj));
  log("val: " + getState('hm-rpc.1.000858A98A464D.4.STATE').val);
});
```
it works as expected.

Sorry, sorry, sorry, and thanks again for your help :)
