### ISSUE TITLE
Combine totalMileage with renault.0.xxxxx.charges.chargeDATE or calculate consumption per 100km

### ISSUE THREAD

**Issue by zImage-de** [ioBroker/ioBroker.javascript#1420]
**Is your feature request related to a problem? Please describe.**
I want to calculate the consumption per 100 km

**Describe the solution you'd like**
Per charge event a datapoint will added at renault.0.XXX.charges.DATE 
-> at that moment the consumed electricity get stored under: renault.0.XXX.charges.2023xxxxxxxxx.chargeEnergyRecovered
-> total milage is also available in totalMileage -> if you also store the actual totalMileage in the charge folder -> this will enable us to calculate the consumption per 100 km...

**Comment by mcm1957** [comment]
This request is most likely NOT related to the javascript adapter but should be addressed to renault Adapter.
Please recheck.

**Comment by zImage-de** [comment]
sorry ...
