### ISSUE TITLE
Fehler beim Abspeichern von Blockly´s

### ISSUE THREAD

**Issue by KarstenRaasch** [ioBroker/ioBroker.javascript#1423]
Hallo, dies ist mein erster Kontakt zu github. Hoffe ich mache alles richtig ;-) 
Ich bekomme folgenden Fehler beim abspeichern von Blockly´s:

`instrument.ts:144 ChunkLoadError: Loading chunk 2887 failed.
(timeout: http://192.168.178.76:8081/static/js/2887.4368cb86.chunk.js)
    at t.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at t.e (ensure chunk:5:56)
    at App.jsx:79:36
    at P (react.production.min.js:18:161)
    at Ei (react-dom.production.min.js:291:292)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at ss (react-dom.production.min.js:273:245)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:144
fo @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
Ua @ react-dom.production.min.js:144
wi @ react-dom.production.min.js:261
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Ss @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14`

Das einfache abspeichern eines bereits vorhandenen Blockly (mit einem jetzt geänderten Datenpunkt) führt dazu, das das gesamte ioBroker-Sytem hängen bleibt. VIS bleibt zwar sichtbar, bekommt aber keine Daten mehr von den Adaptern und ist auch nicht mehr nutzbar. Den Admin kann ich ebenso nicht mehr neu laden. Erst wieder nach einer gewissen Zeit, von vielleicht 5 Minuten. Die restlichen vorhandenen Scripte verweigern während der Zeit ebenso die Arbeit. Unter Hosts ist die Synology-Installation nicht mehr sichtbar. Also gehe ich davon aus, das der ioBroker komplett neustartet?!

Habe den ioBroker in einem Docker auf 218+ mit 16GB RAM (buanet)
Zusätzlich einem Raspy als Slave für Stromzähler auslesen. 

Node -v = v18.17.1 auf DS
                 v18.17.2 auf Raspy

iobroker.admin@6.10.1

![iobroker fehler3](https://github.com/ioBroker/ioBroker.admin/assets/33736965/cd514145-bbc6-4ba5-a9d2-f14a7b1fd3b6)
![iobroker fehler4](https://github.com/ioBroker/ioBroker.admin/assets/33736965/4fa41060-3637-4570-a1a5-c6b0e0acd5d8)
![iobroker ](https://github.com/ioBroker/ioBroker.admin/assets/33736965/0e00e700-4581-4c2f-bc0c-5f3b68a0be58)
![iobroker fehler5](https://github.com/ioBroker/ioBroker.admin/assets/33736965/d728e1a1-39d2-441b-9ee6-f28f83ffabe0)

Habe dieses Problem schon länger, (das geänderte Blockly´s sich nicht speichern lassen), wozu auch im Forum eine menge geschrieben wurde. Diese Meldung, das man es auf Github posten soll, habe ich aber erst jetzt, nach meinem Update der Controller bekommen... 

Würde mich freuen, wenn mir hier jemand helfen könnte. Wenn noch was fehlen sollte, bitte nicht schimpfen nur bescheid geben, dann suche ich´s raus ;-) 

Daaaanke :-)

**Comment by klein0r** [comment]
@KarstenRaasch Kannst Du mal ein Script mit dem Problem teilen?
