### ISSUE TITLE
getIdByName() not stable working in 7.1.4 (worked in 7.0.3)

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.javascript#1424]
**Describe the bug**  
I am using a kind of initialization script as global script incl.
```
const buttonKaffeeID = getIdByName('ButtonKaffee');
if (!buttonKaffeeID || Array.isArray(buttonKaffeeID)) { log('buttonKaffeeID (ButtonKaffee) not found / not unique', 'error') };

```
In other scripts (not global ones) I am refering to `buttonKaffeeID`  which worked fine in previous versions of the adapter.
With 7.1.4 it works right after installation also fine but after few hours, when I change a script where `buttonLadeGeraetID` is used it fails (so the if statement is no longer true).

I got the ID not once but super often as array (always the same ID)
`shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1,shelly.1.SHDW-2#E8DB84D4FDE3#1`

After restarting the global sript it works again for a while. No state changes are done in between.

But it is not global script related.
In a tiny local script
```
let iDs = getIdByName('ButtonKaffee');
log(iDs + ''); 
```
the reuslt is the same.

**To Reproduce**  
see above
I bumped from last stabe adapter version (7.0.3 ?) to current stable version (7.1.4).

**Versions:**  
 - Adapter version: 7.1.4
 - JS-Controller version: 5.0.12
 - Node version: 18.18.2
 - Operating system: Ubuntu

**Comment by Apollon77** [comment]
In your global code there is not "buttonLadeGeraetID" variable defined?

**Comment by Apollon77** [comment]
Ok then also: what you mean with "restarting the global script"? In fact global scripts do not run themself! The source code of a global script is prepended to each and every normal script source code when they are executed. SO "restarting global script" ... no idea what that means ... ALso then ... we would need more details and ideally a minimum reproducable example

**Comment by HGlab01** [comment]
if I change/save the global script the behavior looks like a restart, isn't it?

Szenario:
1. Name a state so that it is unique
2. use getIdByName() for this name
```
let iDs = getIdByName('nameOfState');
log(iDs + ''); 

```
3. Expected: one ID as the name is unique --> is also whtat log shows --> ok
4. Schedule a cron job for this two lines of code
5. after a couple of hours a array with multiple times is retrieved instead of a single item
6. restarting javascript adapter will result in single item again for a coupe of hours

**Comment by Apollon77** [comment]
Try to let javascript run (maybe extra instance) with debug loglevel and post full losg... ,aybe we see anything about what happened "before it went wrong"

**Comment by HGlab01** [comment]
wow! It is getting tricky!
If you like we can switch to Discord, makes life easier...   --> hglab01

The issue appears as soon as a bunch of states are updated/insert simultaneously under one node (like a device).
I was able to reproduce it with 3 adapters: Tado, Shelly and followthesun
Tado and followthesun after a restart of the adapter; shelly when a battery-device wakes up again or when adapter is restartet

**Easiest way to reproduce is to install iobroker.followthesun. This one has no need of any devices etc.**
1. Install adapter; no need for config
2. restart javascript adapter
3. Script:
```
let iDs = getIdByName('Next year');
log('NEXT YEAR: ' + iDs);

```
4. Expected behavior: one ID --> ok
5. restart followthesun adapter
6. execute script again: on my end the ID is now shown 2times
7. restart javascript adapter
8. execute script again --> now it shows the1time again

I hope this helps!

**Comment by Apollon77** [comment]
so you start the script manually? via javascript ui?

**Comment by HGlab01** [comment]
I use the javascript editor. Can be startet manually or run in a cron job - same result

**Comment by HGlab01** [comment]
Hi @Apollon77, anything in addition where I can support?

**Comment by Apollon77** [comment]
I did not found any time to look into this so far ... when I scanned over the changes there was nothing obvious. YOu could try to install different versions out of the range you posted and maybe get a more details "from version A->B it broke" info

**Comment by HGlab01** [comment]
works in 7.1.1 but not  (always) in 7.1.2 and never in 7.1.3
It is really strange, but it depends on the version installation chronology. As I could not believe my own observation I retried it 3times with the same result.

First installation chronology:
7.1.1 --> 7.1.2 --> 7.1.3  ==> works in 7.1.1 and 7.1.2 but not in 7.1.3

Second installation chronology:
7.1.3 --> 7.1.2 --> 7.1.1 ==> works in 7.1.1 but not in 7.1.2 and 7.1.3

Nice challenge for an expert? &#x1F609;

**Comment by klein0r** [comment]
> It is really strange, but it depends on the version installation chronology.

There was a bug when the same object id changed (e.g. updated by the shelly adapter in your example). Good catch 👍 Will be fixed in the next version
