### ISSUE TITLE
Syntax error in main.js:1810:21 "missing ) after argument list"

### ISSUE THREAD

**Issue by seb2010** [ioBroker/ioBroker.javascript#1439]
**Describe the bug**  
I got a iobroker.javascript error showing:
`<html>
<body>

javascript.0 | 2023-11-11 17:42:56.382 | error | at processImmediate (node:internal/timers:478:21)
-- | -- | -- | --
javascript.0 | 2023-11-11 17:42:56.382 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/main.js:1636:17)
javascript.0 | 2023-11-11 17:42:56.382 | error | at /opt/iobroker/node_modules/iobroker.javascript/main.js:2161:17
javascript.0 | 2023-11-11 17:42:56.382 | error | at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:2063:37)
javascript.0 | 2023-11-11 17:42:56.381 | error | at createVM (/opt/iobroker/node_modules/iobroker.javascript/main.js:1810:21)
javascript.0 | 2023-11-11 17:42:56.381 | error | at new Script (node:vm:94:7)
javascript.0 | 2023-11-11 17:42:56.381 | error | SyntaxError: missing ) after argument list
javascript.0 | 2023-11-11 17:42:56.381 | error | ^
javascript.0 | 2023-11-11 17:42:56.380 | error | }
javascript.0 | 2023-11-11 17:42:56.380 | error | script.js.common.jsVacuumQueue_oben compile failed: at script.js.common.jsVacuumQueue_oben:60

</body>
</html>`
when trying to save a javascript. 

main.js indeed seems to have a syntax error in line 1810:
`1810:  script: new vm.Script(source, options),` <--------- i might read it wrong, but the comma should not be there imo

**Expected behavior**  
run without syntax error

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: v7.1.6
 - JS-Controller version: 5.0.16
 - Node version: v18.17.1
 - Operating system: debian bullseye

**Comment by klein0r** [comment]
That's not the issue, code is correct.

https://github.com/ioBroker/ioBroker.javascript/blob/939b0b0a70dd857684afc10be6732467fb3a5208/main.js#L1809-L1811

Please share the script which causes the error.

**Comment by seb2010** [comment]
I already correct it and can not produce the faulty syntax anymore, since I am not sure in what sequence I changed what.
I think we can close this then

**Comment by Apollon77** [comment]
@seb2010 I would propose a Filesystem check to make sure it is not about to get damaged
