### ISSUE TITLE
V 7.1.5 Blockly: Auswahl "Objekttyp" macht keinen Sinn

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1445]
Die Auswahl "Objekttyp" im Block "Attribut vom Objekt ID" macht keinen Sinn, da der ID-Selektor nur Datenpunkte zulässt.

**Comment by klein0r** [comment]
Welchen "Objekttyp" meinst Du?

<img width="350" alt="Screenshot 2023-11-23 at 08 55 09" src="https://github.com/ioBroker/ioBroker.javascript/assets/1959049/cf52ba72-0614-4c7c-a48c-4d187ac26323">

**Comment by klein0r** [comment]
Bilder einfach per Drag and Drop in das Textfeld ziehen. Wie im Forum auch

**Comment by klein0r** [comment]
Ist jetzt der Wunsch, den Objekttyp zu entfernen, oder alle Objekt-Typen zuzulassen

**Comment by paul53** [comment]
Ich würde "Objekttyp" entfernen, da das Zulassen aller Objekttypen im ID-Selektor an anderen Stellen Probleme bereiten würde.
