### ISSUE TITLE
error during update in iobroker docker container Update socketio from @6.5.5 to @6.6.0

### ISSUE THREAD

**Issue by ausbremen** [ioBroker/ioBroker.javascript#1446]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
$ ./iobroker upgrade socketio
Update socketio from @6.5.5 to @6.6.0
NPM version: 9.8.1Installing iobroker.socketio@6.6.0... (System call)
Try to solve ENOTEMPTY error automatically
ERROR: host.iobroker deleted npm temp directory: ".is-arrayish-qBglV5Z1")
Installing iobroker.socketio@6.6.0... (System call)
ERROR: npm ERR! code ENOTEMPTYnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/type-is/node_modules/media-typernpm ERR! dest /opt/iobroker/node_modules/type-is/node_modules/.media-typer-MzLqYgHInpm ERR! errno -39npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/type-is/node_modules/media-typer' -> '/opt/iobroker/node_modules/type-is/node_modules/.media-typer-MzLqYgHI'npm ERR! A complete log of this run can be found in: /opt/iobroker/.npm/_logs/2023-11-25T11_08_13_063Z-debug-0.log
ERROR: host.iobroker Cannot install iobroker.socketio@6.6.0: 217
ERROR: process exited with code 25

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by klein0r** [comment]
1. Wrong repository: https://github.com/ioBroker/ioBroker.socketio
2. code 25 - use `iobroker fix`
