### ISSUE TITLE
V 7.1.5 Blockly: Timeout setzt bei Ablauf Timervariable auf null

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1447]
Das automatische Rücksetzen der Timervariablen auf null bei Ablauf führt in einigen Fällen zu fehlerhaftem Verhalten.

**Comment by klein0r** [comment]
Beispiel?

**Comment by paul53** [comment]
[Siehe Forum](https://forum.iobroker.net/post/1088410)

**Comment by klein0r** [comment]
Sehe das Problem nicht.
Der Timeout ist doch dann durchgelaufen und wird zurückgesetzt (weil der Timeout ja nicht mehr existiert). Was sollte denn dann noch in der Variablen stehen?

**Comment by paul53** [comment]
Die Variable darf nur durch "stop timeout" oder durch explizites "setze timeout auf null" zurück gesetzt werden. Im Forumsbeispiel wird sonst nach jedem Rücksetzen bei Ablauf der Timeout neu gestartet und wiederholt deshalb die Aktionen in der Callback-Fnktion.

**Comment by klein0r** [comment]
> Die Variable darf nur durch "stop timeout" oder durch explizites "setze timeout auf null" zurück gesetzt werden.

Timeout gelaufen = Timeout existiert nicht mehr.
Die Timeout ID (das ist der Rückgabewert der Funktion `setTimeout` zeigt also quasi ins leere.
Egal ob ein Timeout gelaufen ist oder manuell gestoppt wurde: Die Timeout-Variable wird geleert.

Ist aus meiner Sicht so richtig. Erklärung auch im Forum.

**Comment by paul53** [comment]
Ich verwende die Timervariable auch als Sperre solange sie nicht durch eigene Programmierung auf null gesetzt wird. In Javascript kein Problem - in Blockly nicht mehr möglich (Abwärtskompatibilität!).

**Comment by klein0r** [comment]
Zusammenfassung:

- In Blockly war es noch nie möglich einen Timeout zurückzusetzen - außer mit dem "Stop"-Block, welcher aber einen komischen Namen hätte, wenn man damit bereits gelaufene Timeouts "zurücksetzen" möchte (= null).
  - Der Workaround eine Variable mit gleichem Namen zu erstellen und diese dann zu nutzen wurde nie im Adapter hier dokumentiert.
- Das Ganze wurde mit Version 7.0.5 (2023-06-06) geändert und in PR #1313 von Bluefox gemerged
- Das Verhalten ist aus meiner Sicht nun leichter zu verstehen, da eine Prüfung auf die Variable bedeutet, ob ein Timeout wirklich gerade noch läuft / wartet. Vorher war es eher undurchsichtig, da eine Prüfung heißen würde "falls ein Timeout mit diesem Namen läuft oder irgendwann in der Vergangenheit mal lief". **Daher sehe ich das als Bugfix / Feature!**
- Die meisten Installationen laufen schon auf einer Version >= 7.0.5 (2023-06-06)

<img width="1043" alt="Screenshot 2023-11-29 at 21 57 44" src="https://github.com/ioBroker/ioBroker.javascript/assets/1959049/7e15da0c-250c-4bb3-9aa9-a259f6c3b7e1">

Problematisch ist aktuell nur:

- das Changelog wird oft nicht gelesen - ein Breaking Change (für ältere Scripts) wäre sinnvoll gewesen. *Geht auf meine Kappe.*
- Im Forum gibt es jetzt ein paar "ungültige" Posts (aber das ist ja bei jedem Thema so, wenn die Entwicklung weiter geht). *Gibt ja auch viele, welche noch erklären dass man eine Variable anlegen sollte, um darauf dann zu prüfen.*
- Man muss ggf. erklären, dass sich das Verhalten in Versionen >= 7.x geändert hat

----

Das Thema "zurückzurollen" hätte auch viele Konsequenzen:

1. Hätte man wieder einen Breaking-Change für einen Großteil der Nutzer
2. Müsste man erklären, dass das Verhalten in Version 7.x anders ist, als in allen anderen - auch nicht unbedingt einfach
3. Bräuchte man einen weiteren Block, um Timeouts zurück setzen zu können. Das macht das Thema nicht gerade leichter verständlich.
4. Finde ich es schwierig zu erklären, wie der "falls ein Timeout mit diesem Namen läuft oder irgendwann in der Vergangenheit mal lief"-Block funktioniert

Für mich überwiegen die Vorteile des aktuellen Verhaltens.

**Comment by paul53** [comment]
Dann warten wir mal ab, wieviele User sich damit melden werden, dass ein Skript, das lange Zeit funktioniert hat, plötzlich nicht mehr fnktioniert.

**Comment by klein0r** [comment]
Tag mich gerne, dann erkläre ich das...

Scheinen ja bisher recht wenige zu sein, da die Version mit der Änderung seit fast 6 Monaten draußen ist und weit über 35.000 Nutzer hat.
