### ISSUE TITLE
weekday number for Sunday different in German Blocky

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#1457]
![image](https://github.com/ioBroker/ioBroker.javascript/assets/39678667/87e32744-c2f1-4eda-825c-e7880b9d0ff2)

Warum wird der Sonntag mal korrekt mit 0 und mal mit 7 ausgegeben?

```
console.log(formatDate(new Date(), 'WW', 'de'));
console.log((new Date().getDay() === 0 ? 7 : new Date().getDay()));
console.log(formatDate(getDateObject((new Date().getTime())), "WW", "de"));
console.log(getDateObject((new Date().getTime())).getDay());
```

Ich habe viele Skripte in denen ich auf Sonntag = 0 teste, weil man es ja bei dem zweiten Code simulieren kann. Aber wenn dann der aktuelle Tag Sonntag ist und man den ersten Block zur Prüfung dafür nutzt, ist es nie wahr, weil SO=7.

Adapter: 7.4.0
NodeJS: 18.17.1
JS-Controller: 5.0.17

**Comment by klein0r** [comment]
Die Frage ist, was wir hiermit machen. Es gibt jetzt zwei Blöcke die sich unterschiedlich verhalten. Jetzt das Verhalten anzugleichen (egal in welche Richtung) wird das Verhalten in vielen Scripts ändern. Wobei die zweite Variante wahrscheinlich seltener genutzt wird.

`getDay()` gibt für Sonntag eigentlich 0 zurück - das wäre der JavaScript-Standard. Nur hat man wohl gedacht, dass es für die User leichter zu verstehen ist, wenn die Woche Montag = 1 bis Sonntag = 7 ist (statt Sonntag = 0 bis Samstag = 6). Leider fehlt dieser Workaround in der zweiten Funktion.

Wäre also so oder so ein Breaking Change für viele Scripts.

**Comment by klein0r** [comment]
Documentation says 1 to 7 is correct (comment is 6 years old):

https://github.com/ioBroker/ioBroker.javascript/blob/21a1ddd66912fa34cc919779bd8ea99f2c35fbe1/docs/en/blockly.md?plain=1#L1199

Fixed in 21a1ddd66912fa34cc919779bd8ea99f2c35fbe1 - I will add a upgrade notice

**Comment by Diginix** [comment]
Nun hatte ich extra alle Skripte auf die zweite Variante mit SO=0 umgestellt. Nun ändert der Fix genau das :-D
Schwieriger sind nun eher die Skripte wo ich als Bedingung zB weekday>4 hatte um FR+SA aber SO nicht dabei zu haben. Da fällt nun auch der SO rein. Wird unschön das alles erstmal zu finden. Aber bin ja selber schuld :-P

**Comment by klein0r** [comment]
Naja - das aktuelle Verhalten vom zweiten Block widerspricht der Dokumentation. Man könnte noch ein "ist Wochenende"-Block einfügen.

**Comment by Baenker** [comment]
Wäre es nicht besser gewesen man ändert die Dokumentation? Ich habe 57 Jascripte mit getDay. Die muss ich alle überprüfen ob ich dort auf eine 0 abfrage. Ok mein Pech aber vom Standard abweichen finde ich irgendwie mehr als komisch. 

Dokumentation anpassen = Aufwand für eine Person
Standard ändern = Aufwand für tausende von Leuten, die ioBroker schon Jahre nutzen

**Comment by klein0r** [comment]
@Baenker Die Frage ist ja eher, warum Du das nicht als Bug gemeldet hast, als es dir damals aufgefallen ist, dass einige Bausteine von der Dokumentation abweichen...

Das Problem ist ja, dass es nur ein Baustein ist und diese sich anders verhält als andere. Nur der untere ist von dem Problem betroffen - und den nutzen sicherlich deutlich weniger Leute als den oberen.

<img width="482" alt="Screenshot 2023-12-16 at 09 24 26" src="https://github.com/ioBroker/ioBroker.javascript/assets/1959049/f7e45122-f04b-43d6-a7bc-52f079f0a4c3">

**Comment by Baenker** [comment]
Ich nutze Blockly nicht. Gilt das nur für Blockly?

In Javascript ist es für mich kein Fehler wenn getDay eine 0 zurück gibt, da es nunmal in JavaScript überall so ist.

**Comment by mcm1957** [comment]
Es geht offensichtlich NICHT um die Funktion getDay() sondern um EINEN Blockly-Block der nicht den Wert retournierte der in der BLOCKLY Doku steht ...

**Comment by Baenker** [comment]
@mcm1957 wieso offensichtlich?

Aus dem Changelog:

7.5.0 (2023-12-15)

(klein0r) Day of week as number always returns 1 (monday) to 7 (sunday)

Da steht also nicht das es nur Blockly betrifft!

**Comment by mcm1957** [comment]
Ok, changelog ist da ein wenig ungenau - allerdinsg heißt die javascript Funktion ja getDay() und der Block eben "Day of week as number". Ein JS Funktion mit dem Namen gibt es nicht.

Das offensichtlich bezog sich auf die Diskussion hier in diesem Issue.

**Comment by klein0r** [comment]
> Ich nutze Blockly nicht. Gilt das nur für Blockly?

Ja, natürlich. Daher ja der Hinweis die BLOCKLY-Scripts zu kontrollieren...

https://github.com/ioBroker/ioBroker.javascript/blob/56a591d5b2a7d45400a44df2c77b7759b1756e33/io-package.json#L284-L309

**Comment by Baenker** [comment]
@klein0r 

Aus dem Changelog:

7.5.0 (2023-12-15)

(klein0r) Day of week as number always returns 1 (monday) to 7 (sunday)

Da steht also nicht das es nur Blockly betrifft! 

Den Hinweis habe ich zwar gelesen aber eben auch den Changelog und der ist eindeutig für mich. „always“ also immer nicht „alsways in Blockly“.

**Comment by klein0r** [comment]
@Baenker Bitte formuliere das mal neu - dann aktualisiere ich das Changelog.

**Comment by Baenker** [comment]
@klein0r 

(klein0r) Day of week as number always returns 1 (monday) to 7 (sunday) only in Blockly

Ob das richtig ist, kann ich aber nicht beurteilen. Mein Satzaufbau ist, wie meine Grammatik  im deutschen schon bescheiden glaube nicht das es dadurch in englischen besser wird :-)
