### ISSUE TITLE
V7.5 Astrozeiten unter javascript in allen Instanzen

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.javascript#1459]
Mit der aktuellen Version vom Adapter wurden Astro Variablen unter den Objekten javascript.0 javascript.1 und javascript.2 eingefügt.

Das halte ich für sehr unglücklich.

1. zum einen sind die Zeiten dort nur im Format hh:mm und nicht hh:mm:ss eingetragen und somit für Leute die es gerne genau nehmen nicht nutzbar. Es ist halt ein Unterschied ob einen Sonneaufgang um 17:00:01 ist oder 17:00:59.  
2. Dort werden Werte gespeichert die wahrscheinlich nur ein sehr kleiner Bruchteil der User nutzt z. B. die nautical Zeiten
3. Die Variablen werden mehrfach abgespeichert wo es doch bisher einen Ordner variables dafür gab z. B. für daytime. Dieser Wert ist auch umgezogen und nun mehrfach vorhanden

Nachteil: Das System wird unnötig belastet. Da ich z. B. die Sekunden brauche, benötige ich weiterhin das Script welches ich schon seit vielen Jahren nutze. Wie vermutlich die meisten alten Hasen. Das ganze erzeugt unnötige Schreibvorgänge auf Festplatten (weniger problemmatisch) aber für SD-Karten eher nicht so richtig gut.

Sinnvoll wäre entweder eine Option zu schaffen, ob man selber die Daten in seiner eigenen Struktur selber ablegen will oder das System es machen soll. Falls System wäre es dann noch sinnvoll nach dem Format zu fragen. Generell sollten die Daten nicht redundant abgelegt werden. Es würde ein Ordner dafür reichen.

**Comment by Diginix** [comment]
Die werden nur einmal am Tag geschrieben. Also i/o kann man vernachlässigen. Aber ich fände es auch gut wenn man die in der Instanz optional deaktivieren könnte. Ich brauche sie nicht und versuche tatsächlich den Objektbaum so schlank wie möglich zu halten.
