### ISSUE TITLE
console.log >>> Property 'log' does not exist on type 'Console'.(2339)

### ISSUE THREAD

**Issue by ETGermany** [ioBroker/ioBroker.javascript#1462]
**Describe the bug** 
Beim Kommando **console.** erscheint _log_ nicht mehr in der Auswahl

**To Reproduce**  
javascript 7.1.5 ist installiert console.log ist okay
upgrade auf javascript 7.1.6 console. log erscheint nicht mehr in der Auswahl
downgrade auf javascript 7.1.5 Problem bleibt bestehen !!!
downgrade auf javascript 7.1.0 Problem bleibt bestehen !!!
upgrade auf javascript  7.5.0 (github) Problem bleibt bestehen !!!
downgrade auf javascript 7.1.6 Problem bleibt bestehen !!!

**Expected behavior**  
console.log() wieder okay

**Screenshots & Logfiles**  
<img width="416" alt="console log okay" src="https://github.com/ioBroker/ioBroker.javascript/assets/132834418/7c921401-0495-4aa1-8894-3fcb70a43dfa">
<img width="410" alt="console log error" src="https://github.com/ioBroker/ioBroker.javascript/assets/132834418/f9b49459-ba67-4386-aec8-40c501167411">

**Versions:**  
javascript 7.1.6
js-controller 5.0.17
node  v20.10.0
npm 10.2.3
Ubuntu 22.04.3 LTS

Used repository: stable
Adapter    "admin"        : 6.12.0   , installed 6.12.0
Adapter    "backitup"     : 2.8.7    , installed 2.8.7
Adapter    "discovery"    : 4.2.0    , installed 4.2.0
Adapter    "email"        : 1.2.0    , installed 1.2.0
Adapter    "fiat"         : 0.0.8    , installed 0.0.8
Adapter    "fritzdect"    : 2.5.9    , installed 2.5.9
Adapter    "icons-mfd-svg": 1.1.0    , installed 1.1.0
Adapter    "influxdb"     : 3.2.0    , installed 3.2.0
Adapter    "javascript"   : 7.1.6    , installed 7.1.6
Controller "js-controller": 5.0.17   , installed 5.0.17
Adapter    "linkeddevices": 1.5.5    , installed 1.5.5
Adapter    "modbus"       : 5.0.11   , installed 5.0.11
Adapter    "mqtt"         : 5.1.0    , installed 5.1.0
Adapter    "shelly"       : 6.6.1    , installed 6.6.1
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "sma-em"       : 1.0.0    , installed 1.0.0
Adapter    "socketio"     : 6.6.0    , installed 6.6.0
Adapter    "sonoff"       : 3.0.3    , installed 3.0.3
Adapter    "tibberlink"   : 1.6.1    , installed 1.6.1
Adapter    "toyota"       : 0.0.3    , installed 0.0.3
Adapter    "vis"          : 1.4.16   , installed 1.4.16
Adapter    "vis-bars"     : 0.1.4    , installed 0.1.4
Adapter    "vis-hqwidgets": 1.4.0    , installed 1.4.0
Adapter    "vis-icontwo"  : 1.0.0    , installed 1.0.0
Adapter    "vis-inventwo" : 3.3.3    , installed 3.3.3
Adapter    "vis-material-advanced": 1.7.4, installed 1.7.4
Adapter    "web"          : 6.1.10   , installed 6.1.10
Adapter    "ws"           : 2.5.8    , installed 2.5.8

**Additional context**  
console.log() generiert dennoch normal die Ausgaben in der Console.

**Comment by Apollon77** [comment]
Console !== console ... ?! This is known or?

**Comment by fischl3r** [comment]
Es wird immer der Fehler " Property 'log' does not exist on type 'typeof console'. "
Überall steht es soll **console.log** verwendet werden. Allerdings schmeißt der Javascript Adapter im Editor diesen Fehler aus. 

Die Ausgabe funktioniert aber im Editor ist es immer rot unterstrichen.

**Comment by ticaki** [comment]
> Es wird immer der Fehler " Property 'log' does not exist on type 'typeof console'. " Überall steht es soll **console.log** verwendet werden. Allerdings schmeißt der Javascript Adapter im Editor diesen Fehler aus.

Wo ist das überall, ich war der Meinung das log(), die bevorzugtes Methode ist?! Hast du einen Link für mich?

**Comment by klein0r** [comment]
@ticaki Hier sind ein paar Beispiele enthalten, wo console.log verwendet wird: https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md

Ich weiß auch nicht genau, warum hier `log()` fehlt:

https://github.com/ioBroker/ioBroker.javascript/blob/7924c95ed2e87de08b3e366d11d061e0ace05def/lib/javascript.d.ts#L1261-L1272

**Comment by ETGermany** [comment]
@klein0r Dir zunächst mal ein gutes Neues Jahr - den anderen aus diesem Thread natürlich auch.
Ich habe gerade mal bei meinem Kumpel, er hat noch 7.1.4 als 'funktionierende' javascript-Version installiert nachgeschaut, da sieht es genau so aus:

![console functions](https://github.com/ioBroker/ioBroker.javascript/assets/132834418/8402db73-31eb-4285-80b4-7ebdfa56718f)

Ist ja eigentlich auch klar, denn wenn mal 7.1.6 oder höher installiert ist, bringt man das Problem nicht mehr weg, auch wenn man eine Version kleiner 7.1.6 installiert, habe ich ja bereits geschrieben.
Bei der Installation vom javascript-Adapter muss also irgendwo in den Tiefen des Systems etwas manipuliert werden, was nicht mehr zurück genommen wird.

**Comment by klein0r** [comment]
> Bei der Installation vom javascript-Adapter muss also irgendwo in den Tiefen des Systems etwas manipuliert werden

Das klingt aber dramatisch 😄 Ich denke mal das hat mit irgendeiner TypeScript-Dependency zu tun. Ich frage mich ja auch, warum die `console` überhaupt in der Datei steht (mit dem Hinweis auf einen Konflikt mit den node types). Um tiefer einzusteigen hat mir bisher die Zeit gefehlt.

**Comment by fischl3r** [comment]
Bei 
`console.info ('Hallo Welt'); `
gibt es als Rückmeldung dann auch nur 
` TypeError: console.info is not a function`
Obwohl die Funktion aufgeführt ist.

**Comment by ticaki** [comment]
> @ticaki Hier sind ein paar Beispiele enthalten, wo console.log verwendet wird: https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md
> 
> Ich weiß auch nicht genau, warum hier `log()` fehlt:

Soll ich mal mit Find&Replace drüber rennen und console.log() gegen log() tauschen und ne PR machen?

**Comment by klein0r** [comment]
> Obwohl die Funktion aufgeführt ist.

Stimmt, info ist nicht implementiert. Fixed.

> console.log() gegen log() tauschen

Hab ich gerade schon gemacht
