### ISSUE TITLE
JavaScript instance crash with $ - Selector

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.javascript#1467]
**Describe the bug**  
If I use the $ - Selector with a lot of entries the, JavaScript instance crash. The instance restarts and the output of the Selector will be shown.

**To Reproduce**  
This is an example with a all states, but the crash with less selected states too.

```
let test = $('channel[state.id=*]');
test.each((id, i) => {
    log(id);
});
```
Error in ioBroker Log:
`JavasScript: Terminated (NO_ERROR): Without reason`

**Expected behavior**  
The JavaScript instance does not crash

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 7.5.1
 - JS-Controller version: 5.0.17 
 - Node version: v18.16.0 
 - Operating system: Linux iobroker 5.4.0-169-generic  # 187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by Apollon77** [comment]
Please post the full log

**Comment by schmupu** [comment]
There are no entries in the iobroker.log file. The JavaScript Instance gets red and the JavaScript instance restarts and the scripts will restart. 
On my development system I do not have the problem. But there are less objects. 
Is it possible, that the iobroker state/object db ist corrupted (I am not using the reddis db)? 
I tried already `iobroker fix`. But that did not help.

**Comment by Apollon77** [comment]
Bitte bitte poste doch edas Log ... einfach 5 mins drum herum, danke

**Comment by schmupu** [comment]
Ich habe das Problem gefunden. Der Unifi Adapter bzw. Instanz hat im Laufe der Zeit über 70.000 Objekte angelegt (unifi.0.default.alarm.*).  Insgesamt, gab es 105.000 Objekte im System (+ selbe Anzahl States). 
Damit scheint der JavaScript Selector nicht zurechtzukommen. Selbst als ich den Selector in der Suche eingeschränkt hatte (z.B. *.battery).  Da wurde auch über die 70.000 Objekte gesucht und der JavaScript Adapter ist ohne Logfile Meldung abgestürzt (Instanz wird rot und startet im besten Fall neu). Ich hatte die Objekt u. States DB auf Redis umgestellt. Das hat  nicht geholfen.
Ich habe jetzt die 70.000 Objekte in der Unify Instanz gelöscht. Seit dem läuft der JavaScript Adapter wieder einwandfrei.

Auf das Phänomen könnten auch andere Benutzer stoßen und nach der Ursache suchen. 
Vielleicht gibt es eine Möglichkeit, diese Problematik im JavaScript Adapter abzufangen.

**Comment by Ilovegym66** [comment]
Das Problem hatte ich auch.. 
der Unifi Adapter liegt seit Monaten auf der "intensiv Station", wird gerade so am Leben gehalten aber richtig vorwärts geht's in der Entwicklung leider nicht...

**Comment by mcm1957** [comment]
> nein, sinnvoll ist das sicherlich nicht. Aber es fällt einem ja nicht auf, dass ein Adapter ständig Objekte anlegt. Besonders dann nicht, wenn man nicht sonderlich Technik affin ist. Mir ist der Fehler auch erst aufgefallen, alls die Familie unser Smarthome System verflucht hat und mich bat alles zurück zubauen ;-) Vielleicht kann man das irgendwie technisch verhindern oder irgendwo eine Warnung/Fehler ausgeben wenn ein Adapter mehr als x Objekte anlegt. Dann muss man nicht lange suchen.

OK, habs so erwartet
Dann leg doch bitte ein Issue beim Adapter unify an und gib dort an
- welche Adapterversion installiert ist
- welche Objekte bei dir rumgekugelt sind (damit man finden kann woher die kommen, mindestesn IDs soweit du sie erinnerst
- ev. Zeitraum in dme sie entstanden sind

**Comment by schmupu** [comment]
wäre es vielleicht eine idee, eine Meldung im iobroker fixer adapter mit vielen Objekten ausgeben?
ich werde ein issue für den unifi adapter erstellen.

**Comment by mcm1957** [comment]
Danke
Hab gestern gesehn dass es bei unifi schon ein issue gibt. Titel war nur nicht eindeutig - hab ich angepasst.. ev ergänz dort Infos die su zusätzlich hast

**Comment by klein0r** [comment]
Ich mache hier mal zu. Mit so vielen Objekten braucht man wahrscheinlich sehr viele Ressourcen - gerade, wenn "Nicht alle Zustände beim Start abonnieren" deaktiviert ist (Standard). Denn dann wird alles nochmal in den JavaScript-Adapter kopiert. Also 70.000+ States im Arbeitsspeicher der Instanz.
