### ISSUE TITLE
Unable to create a production build

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.javascript#1478]
The github action builds failed since 7.5.1 - e.g. https://github.com/ioBroker/ioBroker.javascript/actions/runs/7385464584

Reason

```
[11:58:29] Finished '2-npm' after 57 s
[11:58:29] Starting '3-build'...
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '@mui/x-date-pickers' in '/home/runner/work/ioBroker.javascript/ioBroker.javascript/src/node_modules/@iobroker/json-config/build/JsonConfigComponent'
```

Any idea @foxriver76 ? The jsonConfigComponent dependency in adapter-react-v5 is not that old.

Works again after adding `@mui/x-date-pickers` to `/src` 417306c8ac16cb105c82a496c3509cd674cc59ab (revert?)

**Comment by foxriver76** [comment]
It could be that json config module is missing it as prod dependency

**Comment by klein0r** [comment]
But `adapter-react-v5` has it as a prod dependency: https://github.com/ioBroker/adapter-react-v5/blob/3b9feab24657ece7845ed41e2f06f068de822451/package.json#L50
