### ISSUE TITLE
404 Oops! The page you're looking for can't be found. File tab.html not found

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#1479]
Version 7.6.2 can't be used to create/edit scripts.

![image](https://github.com/ioBroker/ioBroker.javascript/assets/39678667/7fc7a756-b4c4-42b7-9e15-dfe244b6d38e)

In filesystem it exists: /opt/iobroker/node_modules/iobroker.javascript/admin/tab.html

Edit: a manual upload solves it.

**Comment by klein0r** [comment]
Was soll ich sagen? Ich arbeite ja schon die ganze Zeit mit der Version.

Mach nochmal ein Upload des JavaScript-Adapters.

**Comment by Diginix** [comment]
Nachdem ich die tab.html gefunden habe, habe ich genau das gemacht und er funktioniert nun. Danke für die schnelle Reaktion.
