### ISSUE TITLE
blockly German translation "trigger on states changed"

### ISSUE THREAD

**Issue by peperoni60** [ioBroker/ioBroker.javascript#1480]
**Describe the bug**  
Wrong German UI-translation in blockly.

**Versions:**  
 - Adapter version: 7.1.6

In https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/de/blockly.md#trigger-on-states-change the plural form "Event: if objects", not "Event: if object" is used whereas in blockly the singular "Falls Objekt" is used an not "Falls Objekte":
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/15870106/4f7cf882-9031-41c6-9888-abc54a663e1d)
"Objekte" would be correct as you can provide a list of objects in "Objekt ID default".
I found this by accident when I read the docs and found out that I can omit loops if I want to register a list of triggers. 

Btw: Also the old version "falls Objekt" (first word lower case and singular form!) (English: "Event: if object") should be marked as deprecated as it is provided for downwards compatibility only.
> This is the same block as "Trigger on states change", but with no possibility to use multiple object IDs for triggering (for versions compatibility).

**Comment by klein0r** [comment]
> "Objekte" would be correct as you can provide a list of objects in "Objekt ID default".

To use the correct terms, it must be `Event: State changed`. Since it's not possible to register a trigger for object changes via Blockly. But I wont't update that term, because it is widely used in thousands of screenshots and documentations.

**Comment by peperoni60** [comment]
Of course, the English text may be incorrect, too. But the German translation is textually wrong. In English it is plural, in German it is singular.
Is there an option to have blockly in English while the rest of iobroker is in German? 

btw. I have subscribed your "ioBroker Master Kurs" and you use the "old" *falls Objekt* block (the singular one, which is for version compatibility only) instead of the *Falls Objekt* block. If you could change that and also mention that you can provide a list of objects (i.e. states) this would be great.

**Comment by klein0r** [comment]
> you use the "old" _falls Objekt_ block (the singular one, which is for version compatibility only) instead of the _Falls Objekt_ block

There are no deprecated blocks. Both are still valid and generate valid code.
