### ISSUE TITLE
String.replaceAll is not recognized as valid command in TypeScript

### ISSUE THREAD

**Issue by neopholus** [ioBroker/ioBroker.javascript#1485]
**Describe the bug**  
`String.replaceAll` is not recognized as valid command in TypeScript Editor but compiles and works correctly.
If you use it, `replaceAll` has a red line below it and the following error is shown:
`Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.(2550)`

But codes compiles and executes correctly, see below.

**To Reproduce**  
1. Create a new type script file
2. Enter the code
```
let text:string = 'I think my dog is cuter than your dog';
log(text.replaceAll('dog', 'monkey'));
// Expected output: "I think my monkey is cuter than your monkey"
```
3. Start script
4. Find in log the line `I think my monkey is cuter than your monkey`

**Expected behavior**  
Editor should accept replaceAll as correct code, see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)

**Versions:**  
- JS-Controller version: 5.0.17
- Node version: v18.17.1
- Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by klein0r** [comment]
> This is because replaceAll function is only available starting from Node version 15.

I will raise the supported version to es2021 (since nodejs 16 is required for the latest adapter versions)
