### ISSUE TITLE
[Bug]: Can't see script text

### ISSUE THREAD

**Issue by MaaG-dA** [ioBroker/ioBroker.javascript#1487]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Javascript

### The problem

In polish language system I can't see text of my scripts. After switch into english - are is ok.
polish:
![1706136581427-error](https://github.com/ioBroker/ioBroker.javascript/assets/87951504/b08749db-4e2a-4572-b375-8f666c30c692)

### Version of nodejs

v18.17.1

### Version of ioBroker js-controller

v7.1.6

### Version of adapter

v7.1.6

**Comment by klein0r** [comment]
Can you share the output of the browser console? Any errors? I'm not able to reproduce this issue.
Please test with the latest beta (7.7.0) instead of stable.

**Comment by MaaG-dA** [comment]
console snapshot (my stable version):
![error](https://github.com/ioBroker/ioBroker.javascript/assets/87951504/e92c8d11-c7e1-42de-9129-33d6d598ecbe)

**Comment by MaaG-dA** [comment]
beta 7.8.0 look ok:
![error](https://github.com/ioBroker/ioBroker.javascript/assets/87951504/86020723-a472-454b-9180-f6d73dc3c7db)

**Comment by MaaG-dA** [comment]
It was a stupid idea. Mixing beta and stable versions... I have to reinstall the program :(

**Comment by klein0r** [comment]
> It was a stupid idea. Mixing beta and stable versions...

1. That makes no difference
2. There was no need to install beta versions of all adapters
