### ISSUE TITLE
Show ObjectID on mouseover

### ISSUE THREAD

**Issue by TDCroPower** [ioBroker/ioBroker.javascript#1499]
Is it possible to display the object ID of a selected object in the context menu when mousing over it?
This would allow you to quickly check whether you have selected the correct data point for a device.
In my example, I have installed a lot of Shelly Plus 2PM and query the same data points for all of them.
At first glance, you can't tell whether the correct device has been selected.
I only had the problem recently when I had to replace all the Shelly 2.5 with the Plus 2PM that I selected a data point from the wrong device and didn't realize it.

here a example of the "Position" objects...
![Bildschirmfoto 2024-02-09 um 17 13 52](https://github.com/ioBroker/ioBroker.javascript/assets/6634116/17e60092-50de-4a62-ba4f-97278a9a9673)

and the context menu...
![Bildschirmfoto 2024-02-09 um 17 19 38](https://github.com/ioBroker/ioBroker.javascript/assets/6634116/0c6b9ec2-8daa-40f1-b653-54d84306e0bf)

**Comment by rtwl21** [comment]
That would be a great feature 👍

**Comment by klein0r** [comment]
<img width="414" alt="Screenshot 2024-03-21 at 13 17 42" src="https://github.com/ioBroker/ioBroker.javascript/assets/1959049/40a98782-9b20-4e74-9559-5782942129ff">

**Comment by TDCroPower** [comment]
@klein0r great work !
