### ISSUE TITLE
Cannot extract Blockly code

### ISSUE THREAD

**Issue by Smarti15** [ioBroker/ioBroker.javascript#150]
Hi, ich hab das jetzt schon dreimal gehabt und diese Meldung nur durch ein einspielen eines älteren Backups von ioBrocker wieder wegbekommen. Ich weiss nicht wieso es kommt und was ich da falsch machen, aber kann man das Problem auch ohne ein Backup zurückspielen beheben? Hab gelesen das die Version 3.5.1 besser laufen soll, wie kann ich die manuell einspielen im ioBroker?

**Comment by Smarti15** [comment]
Dankeschön, ab es ausgeführt. Mal schauen ob der Fehler jetzt nicht mehr kommt. 
Einen schönen Samstagabend noch :)

**Comment by grritvrij** [comment]
habe dasselbe problem und stelle fest das alle pushover bloecke fehlen (daher stammt denke ich mal auch die meldung).
ausfuehren der befehle hat leider nichts gebracht, sowohl fuer javascript als pushover adapter

**Comment by grritvrij** [comment]
die Sprache ändert dies auf Englisch und die Nachricht ist weg (Blockcode kann nicht extrahiert werden!) Das Schwundproblem ist immer noch da

**Comment by FRYYYYYY** [comment]
Habe das selbe Problem - jedoch mit der 4.0.5 Version. Ich erhalte die Fehlermeldung immer, wenn ich einen Blockly Code offen hatte und dann später wieder mit einem "neuen" Browser in die Scripte gehe. Schließe ich das Script, welches als erstes offen ist und schließe es, geht es wieder.

**Comment by Leviathan09** [comment]
`cd /opt/iobroker`
`npm i https://github.com/iobroker/iobroker.javascript/tarball/master --production`
`iobroker u javascript`
`iobroker restart javascript`

Habe das selbe Problem, Veriosn 4.0.7 ist installiert.
Die oben aufgeführte Anleitung habe ich auch ausgeführt.
Bringt leider auch keine Besserung

**Comment by GermanBluefox** [comment]
Please retest with 4.1.5 and if still problem, open a new issue with Example code

**Comment by Curtis777** [comment]
> ```
> cd /opt/iobroker
> npm i https://github.com/iobroker/iobroker.javascript/tarball/master --production
> iobroker u javascript
> iobroker restart javascript
> ```

Danke hatte nach einem crash und backup das selbe problem Danke die Lösung half
