### ISSUE TITLE
Blockly: Nachricht and andere Script - Meldung als Variable

### ISSUE THREAD

**Issue by Voodoo2man** [ioBroker/ioBroker.javascript#1500]
In Blockly muss ich den Block "Nachricht an anderes Skript" mehrfach in einem Script mit verschiedenen Meldungen verwenden.

Der Wert Meldung sollte im Block als Variable einsetzbar sein, sodass man ihn in Funktionen verwenden kann.

![image](https://github.com/ioBroker/ioBroker.javascript/assets/62031459/4bf14a5c-0703-460c-b64f-3b52fd3494fd)

**Comment by klein0r** [comment]
Ich habe das bewusst fix definiert, damit man das einmalig korrekt auf "beiden Seiten" eingeben muss und man so weniger Fehler machen kann.

_Von mir kommt an dieser Stelle keine Änderung - aber eventuell hat ja jemand anders Lust auf die Erweiterung._
