### ISSUE TITLE
 getIdByName liefert zwei identische Werte #14 [Bug]: 

### ISSUE THREAD

**Issue by SPITZGITHUB** [ioBroker/ioBroker.javascript#1501]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

Bekomme nun im JAVA-Script, das einige Jahre lief

**console.log ("ID: " + getIdByName(R_ID_Name));
setState(getIdByName(R_ID_Name), R_Werte);**

immer den Error:
**State "hm-rega.0.1481,hm-rega.0.1481" not found**

da der Name zweimal bei getIdByName zurückgegeben wird.!**

### Version of nodejs

 5.0.12

### Version of ioBroker js-controller

v16.20.2

### Version of adapter

7.1.6

**Comment by klein0r** [comment]
> [x] There is no other (open) issue with the same topic (use the search!)

see https://github.com/ioBroker/ioBroker.javascript/issues/1424

> [x] This issue is still present in the **current beta version** of this adapter

nope, fixed

https://github.com/ioBroker/ioBroker.javascript/blob/e41b680eab27695e8312996a3c52532c9289f1e0/README.md?plain=1#L54-L58

**Comment by klein0r** [comment]
> da der Name zweimal bei getIdByName zurückgegeben wird.

Das kann aber generell passieren, wenn zwei Objekte im System den gleichen Namen haben.

**Comment by SPITZGITHUB** [comment]
Hallo Matthias,

 

und warum lief dieses Programm einige Jahre bis zum 29.01 und dann nicht mehr? Diese Variable habe ich nicht geändert bzw. neu hinzugefügt oder das Skript geändert.

 

Und was heisst zwei Objekte im System (welchem?) den gleichen Namen?

 

Die Variable liegt im HOMEMATIC System. Wie kann ich feststellen, das zwei Objekte den selben Namen haben?

 

Danke für Deine Hilfe

 

Gruss

 

Peter

 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 12. Februar 2024 09:24 Uhr
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: SPITZGITHUB ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] getIdByName liefert zwei identische Werte #14 [Bug]: (Issue #1501)

 

da der Name zweimal bei getIdByName zurückgegeben wird.

Das kann aber generell passieren, wenn zwei Objekte im System den gleichen Namen haben.

**Comment by SPITZGITHUB** [comment]
Hi,

 

ich habe das mit einer Variablen, die sicher nur einmal im System ist gemacht und bekommen auch zwei mal den gleiche Wert!

Variable in HomeMatic:

 



 

Variable im IOBROKER:

 



 

Blocky:



 

Javascript:



Ergebnis:



 

 

 

 

 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 12. Februar 2024 09:24 Uhr
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: SPITZGITHUB ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] getIdByName liefert zwei identische Werte #14 [Bug]: (Issue #1501)

 

da der Name zweimal bei getIdByName zurückgegeben wird.

Das kann aber generell passieren, wenn zwei Objekte im System den gleichen Namen haben.

**Comment by klein0r** [comment]
Bitte nicht auf die Mails antworten, sondern auf GitHub die Screenshots hochladen. Du teilst hier gerade nur unverständliche Inhalte 😄
