### ISSUE TITLE
Anregung zur Verbesserung

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#151]
Ich hätte vielleicht eine Anregung zur Verbesserung. Ob es sinnvoll ist, oder nicht sei einmal dahin gestellt. Mir persönlich würde es viel helfen.
Es ist ja nun einmal so, dass wenn man an einem Script arbeitet ( ich arbeite momentan als Anfänger mit Blockly ) muss man ja immer zwischen zwei Fenster springen. Das heißt man arbeitet in einem Fenster an dem Script und muss zur Kontrolle der Werte immer im zweiten Fenster unter den Objekten kucken.
Jetzt wäre es vielleicht sinnvoll und hilfreich, wenn man die aktuellen Werte gleich im Script sieht, sobald man den "Play-Button" drückt. Wäre für mich persönlich eine sehr schöne Errungenschaft, die aktuellen Zustände und Werte der benutzen States neben, oder über den Verbindungen zu sehen. Ich hoffe es ist Verständlich geschrieben was ich meine.

Zudem ist mir aufgefallen, dass das Mausrad im Blockly - Modus zum hoch/runter Scrollen nicht funktioniert.

**Comment by Apollon77** [comment]
Der Adapter hat einen debug Modus und verbose log. Das sind zwei Einstellungen die jedes Skript über dem editorfenster hat. 

Hast du die schonmal versucht? 

Verbose log ( keine Ahnung gerade wie es in der deutschen UI heißt): viel log Ausgaben. Unter anderem zu allen Änderungen und lesen und so.

**Comment by quorle** [comment]
Die zwei Modus kenne ich und nutze ich auch bei der Scriptentwicklung. Wenn man aber mehrere Trigger hat, mit mehreren Routinen darin wird es irgendwann sehr unübersichtlich. 
Also ich finde alles am iobroker ja sehr gut, bin auch vollkommen zufrieden und ziehe meinen Hut vor den Entwicklern. Aber vielleicht wäre es ja eine Überlegung wert, Anzeigekästchen in die jeweiligen Blocks von Blockly einzubauen. 
Will wirklich keinen zu großen Aufwand an die Entwickler bringen. Vielleicht überlegt man sich das ganze ja einmal.

**Comment by GermanBluefox** [comment]
So ein Modus ist fast unmöglich... 
Es ist ist natürlich alles möglich nun aber so VIEL Zeit habe ich nicht.
