### ISSUE TITLE
[Bug]: "Falls Objekte" speichert Bedingung nicht beim bearbeiten

### ISSUE THREAD

**Issue by rtwl21** [ioBroker/ioBroker.javascript#1517]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Der Trigger-Block "Falls Objekte" ändert die Auslöse Bedingungen zurück auf standard beim Klicken auf das blaue Zahnrad.

Aus "ist gleich oder kleiner als letztes" ...
![image](https://github.com/ioBroker/ioBroker.javascript/assets/100233609/89db6adb-5228-4e7e-8db9-9617d229c854)

wird beim klick auf das blaue Zahnrad wieder "wurde geändert"
![image](https://github.com/ioBroker/ioBroker.javascript/assets/100233609/a862eead-2abf-4ed7-a841-93007f6a228e)

Die Bedingung wird also zurückgesetzt und kann übersehen werden.

### Version of nodejs

v18.19.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

7.8.0

**Comment by klein0r** [comment]
Habe ich schon behoben und ist in der nächsten Version enthalten
