### ISSUE TITLE
[Bug]: Script is calling setState more than 1000 times per minute! 

### ISSUE THREAD

**Issue by svenna1980** [ioBroker/ioBroker.javascript#1518]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

After updating js controller to 5.0.19 the error occurs "Script is calling setState more than 1000 times per minute! Stopping Script now! Please check your script!". Ram and CPU utilization are normal. The script ran without an error message before the update. It has not been changed for approx. 1.5 years.

### Version of nodejs

v16.19.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

v7.8.0

**Comment by klein0r** [comment]
> The script ran without an error message before the update.

Okay, but it's still possible that setState has been called 1000+ times per minute before. The info has been added.
I'll close this issue since no further information have been provided (like the script or a debug log)

**Comment by svenna1980** [comment]
Hello, that is the problem. The script doesnt calls state more than 1000times. I increased the value from 1000 to 10000. After that the error messages came again saying "Script is calling setState more than 10.000 times per minute! 
I query the 3 power values of a Shelly and use them to calculate the grid reference. The query is in a 1000ms inverall. Cant image why there should be 1000 or 10000 state calls in a minute.

**Comment by svenna1980** [comment]
Is it possible to deactivate the function so that the error message no longer appears? Increasing the value to 10,000 does not seem to work either.

**Comment by Ilovegym66** [comment]
The fault is in your blockly, it's a trigger in a trigger!

Correct it and the fault is gone. It's definitly not the adapter.

**Comment by klein0r** [comment]
> Is it possible to deactivate the function so that the error message no longer appears?

Yes, fix your scripts and don't create 3 new triggers every second 😄

**Comment by svenna1980** [comment]
Asche über mein Haupt!  
Ashes over my head!
Thank you for your help and your time. I didn't realize that I had a trigger in the trigger.
I would like to hope that the next version works properly. Not that I have to report another error here. :-)
