### ISSUE TITLE
Create block for http post data

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.javascript#152]
At the moment we only have a request block.

**Comment by BuZZy1337** [comment]
Maybe something for you @thewhobox? :relaxed:

**Comment by thewhobox** [comment]
Please add your suggestions in the [Forum Thread](https://forum.iobroker.net/topic/20845/wunschliste-blockly-elemente/11).
Also add a description how the block should be like (which parameters, how you want the response?)

**Comment by BuZZy1337** [comment]
That "http post data" block was not my idea.. I just created this issue here long time ago because the user which posted that at the forum did not have a Github Account..

I am not using Blockly at all and have this "issue" here on my ToDo List - but with lowest priority..
And because i saw that you are doing some work on blockly i just mentioned you here.. :smile:
