### ISSUE TITLE
[Bug]: request blockly block is deprecated - please use "http get" instead

### ISSUE THREAD

**Issue by zaphod2** [ioBroker/ioBroker.javascript#1520]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Seid neuestem werden Fehler gemeldet mit ` request blockly block is deprecated - please use "http get" instead`
Ich versuche über Blockly request http://192.168.xxx.xxx/cm?cmnd=counter1%200 zusenden und es kommt zu Fehlermeldungen. Vorher ging es definitiv. Ich bin schon bis 7.6.0 zurück aber geht nicht. Ich habe auch sonst nichts geändert und nun weiß ich nicht weiter.
Mit "http get" kommt `ReferenceError: httpGet is not defined`

### Version of nodejs

18.19.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

7.8.0

**Comment by zaphod2** [comment]
Alles mal neu gestartet und geht wieder.

**Comment by zaphod2** [comment]
ist doch nicht weg.

**Comment by klein0r** [comment]
> Seit neuestem werden Fehler gemeldet mit ` request blockly block is deprecated - please use "http get" instead`
> 7.8.0

Kann es sein, dass Du mehrere Instanzen auf einem Multihost-System hast? Es ist technisch nicht möglich, dass Du den Blockly-Block für http (GET) verwenden kannst, aber die Funktion dann nicht existiert.

Zumal es die Blöcke erst seit 7.9.0 gibt: https://github.com/ioBroker/ioBroker.javascript/commit/e51a239f31974893afbbba70a6545105d0d58286

**Comment by zaphod2** [comment]
Nein, keine mehrere Instanzen auf einem Multihost-System.

**Comment by zaphod2** [comment]
Das ist das Blockly

`<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="on_ext" id="J|)93{$Qyd@0;k2Opp-j" inline="true" x="-450" y="772">
    <mutation xmlns="http://www.w3.org/1999/xhtml" items="1"></mutation>
    <field name="CONDITION">ne</field>
    <field name="ACK_CONDITION"></field>
    <value name="OID0">
      <shadow type="field_oid" id="Vl4Iid?O54fFOVn.]y-4">
        <field name="oid">hm-rpc.2.00021BE99E2EFA.3.STATE</field>
      </shadow>
    </value>
    <statement name="STATEMENT">
      <block type="controls_if" id=".qF[`du=-|!D(sujHe_F">
        <value name="IF0">
          <block type="logic_compare" id="m$jIUiCG(;A@GNw8T)l2">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="get_value" id="Q;!?A.(pS_o{Az:);=9P">
                <field name="ATTR">val</field>
                <field name="OID">hm-rpc.2.00021BE99E2EFA.3.STATE</field>
              </block>
            </value>
            <value name="B">
              <block type="logic_boolean" id="?d!3~PgpgJG(q;!?m{=_">
                <field name="BOOL">TRUE</field>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="control" id="Wl[kQRIukaHbD`l8@Czu">
            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="true"></mutation>
            <field name="OID">hm-rpc.2.00021BE99E2EFA.3.STATE</field>
            <field name="WITH_DELAY">TRUE</field>
            <field name="DELAY_MS">5</field>
            <field name="UNIT">min</field>
            <field name="CLEAR_RUNNING">FALSE</field>
            <value name="VALUE">
              <block type="logic_boolean" id="FH+3hjIcDd^+^NZ*ak$N">
                <field name="BOOL">FALSE</field>
              </block>
            </value>
          </block>
        </statement>
        <next>
          <block type="controls_if" id=":a.BF6kCJ`@Pp;3(*.T-">
            <value name="IF0">
              <block type="logic_operation" id="N2(Oi{FhIN.d39+j(jV}">
                <field name="OP">AND</field>
                <value name="A">
                  <block type="logic_compare" id="yZ${*r{xFRl]b*_b)xKM">
                    <field name="OP">EQ</field>
                    <value name="A">
                      <block type="get_value" id="xyRJp^]$G$2c8+v8sAua">
                        <field name="ATTR">val</field>
                        <field name="OID">hm-rpc.2.00021BE99E2EFA.3.STATE</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="logic_boolean" id="N==X@V_6z2_PTBC]eTVi">
                        <field name="BOOL">FALSE</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_compare" id="5-.u=p`ZLyLY/r6qbU2c">
                    <field name="OP">GTE</field>
                    <value name="A">
                      <block type="get_value" id="?~|ZtYZxAeemVNL{F~qS">
                        <field name="ATTR">val</field>
                        <field name="OID">sonoff.0.Warmwasser.COUNTER_C1</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="math_number" id="Xb/n501E4}/[Q[$GL7(x">
                        <field name="NUM">20</field>
                      </block>
                    </value>
                  </block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="request" id="/:3k?O/K/2$01T}SP{XL">
                <mutation xmlns="http://www.w3.org/1999/xhtml" with_statement="false"></mutation>
                <field name="WITH_STATEMENT">FALSE</field>
                <field name="LOG"></field>
                <value name="URL">
                  <shadow type="text" id="z9ywo8ck;,SSVin7.:t2">
                    <field name="TEXT">http://192.168.178.122/cm?cmnd=counter1%200</field>
                  </shadow>
                </value>
              </block>
            </statement>
          </block>
        </next>
      </block>
    </statement>
  </block>
</xml>`

**Comment by klein0r** [comment]
> Nein, keine mehrere Instanzen auf einem Multihost-System.

Dann ist es nicht möglich, dass Du die Blöcke mit Version 7.8.0 überhaupt zur Verfügung hast.
Blockly bitte als Screenshot einfügen.

**Comment by zaphod2** [comment]
Fehler bleibt.

![Screenshot 2024-03-22 171517](https://github.com/ioBroker/ioBroker.javascript/assets/96678159/6865f983-4d0c-4228-ab61-68c21978c632)

**Comment by zaphod2** [comment]
Der Zähler wird ja in Tasmota trotzdem zurück gesetzt.

![Screenshot 2024-03-22 171734](https://github.com/ioBroker/ioBroker.javascript/assets/96678159/2774e7eb-fa02-4ada-8d75-f0cf165659d7)

**Comment by zaphod2** [comment]
So geht`s jetzt.

![Screenshot 2024-03-23 103153](https://github.com/ioBroker/ioBroker.javascript/assets/96678159/e43bbe26-2ec3-4850-a099-77e9d2699ffb)

**Comment by klein0r** [comment]
> So geht`s jetzt.

Ich verstehe den ganzen Issue hier nicht. Genau das stand doch in der Warnung?!

**Comment by zaphod2** [comment]
Vorher ging es auch ohne Fehlermeldung und mit http (GET) ging es irgendwie auch nicht und nun gehts. Ich habe doch auch keine Ahnung.

**Comment by klein0r** [comment]
> Vorher ging es auch ohne Fehlermeldung

Das ist eine Warnung, welche ja genau darauf hinweisen soll, dass man die neuen Blöcke verwendet. Damit wir das alte request-Modul irgendwann endlich mal loswerden... Immerhin ist es schon seit über 4 Jahren aus dem Support gelaufen.

**Comment by nhet** [comment]
Hallo,
ich habe die Warnugen nun auch bekommen. Gibt es irgendwo eine Übersicht / Erklärung wie die neuen http Blöcke jetzt zu nutzen sind? Die Response ist leider nicht identisch. Danke.

**Comment by klein0r** [comment]
@nhet Klar,

- https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/upgrade-guide.md
- und ausführlicher als Video hier: https://haus-automatisierung.com/iobroker-kurs/
