### ISSUE TITLE
Blockly email block with dynamic amount of attachments

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#1522]
The current email block supports only 2 attachments. I have scripts where I need 3 up to 6 attachments in one mail.
As workaround I use a javascript function block with 
```
sendTo("email", {
   to: to,
   subject: subject,
   text: text,
   attachments: [
     {path: att1},
     {path: att2},
     {path: att3},
     {path: att4},
     {path: att5},
     {path: att6},
   ]
});
```
But I wasn't able to implement conditions in this to have only 3 or 4 attachment keys with path if 5 and 6 is false or empty.
The best way would be to have the standard email block enhanced for dynamic amount of attachments.

**Comment by klein0r** [comment]
The email-Block is created by the email adapter: https://github.com/iobroker-community-adapters/ioBroker.email

https://github.com/iobroker-community-adapters/ioBroker.email/blob/master/admin/blockly.js

**Comment by Diginix** [comment]
Ah I see, 2019 I've created a feature request in email adapter. As it seems no one else needs this.
https://github.com/iobroker-community-adapters/ioBroker.email/issues/11

**Comment by klein0r** [comment]
> As it seems no one else needs this.

The problem is, that more experienced users (and developers) use JavaScript instead of Blockly and are not interested in improving Blocks
