### ISSUE TITLE
debug-Ausgabe unabhängig vom Log-Level

### ISSUE THREAD

**Issue by jenskaschub** [ioBroker/ioBroker.javascript#1524]
Mich stört (und andere verwirt's), dass wenn man in der javascript-Instanz das Log-Level auf error setzt, in der debug-Ausgabe keine infos oder warnings mehr angezeigt werden.
Das eine ist ja die Protokollierung für's Gesamtsystem, das andere Infos für das Script an dem man grade bastelt. Ich fände eine Checkbox (alle Debugsausgaben anzeigen / Log-Level übernehmen) hier ganz hilfreich.

**Comment by jenskaschub** [comment]
Wenn ich Blockly ein Script erstelle, benötige ich in der Schaffensphase den "debug output"-Block um zu sehen was wann wo in welchen Datenpunkten oder Variablen o.ä. steht. Diese "Info" wird aber nicht angezeigt, wenn ich in der Instanz des Adapters das LOG-Leverl beispielsweise auf "Error" setze.
Ich finde es sollte unterschieden werden zwischen dem Protokoll und den Debugausgaben im Scriptbereich

**Comment by mcm1957** [comment]
Wenn du mehr als error sehen willst dann stell den loglevel einfach nicht auf error...

Der debug block schreibt nun mal nen debug log. Wenn du den sehen willst ist wohl level debug ganz hilfreich.

**Comment by jenskaschub** [comment]
Ich will aber im javascript-Adapter in der Script-Oberfläche mehr sehen und nicht im Protokoll des iobrokers.
Natürlich weiss ich wie ich das umgehen kann, aber das hier ist ein Feature-Request.
Nach deiner Argumentation bräuchte wir nicht mal Blockly, denn javascript-code reicht ja auch.

**Comment by klein0r** [comment]
> in der Script-Oberfläche mehr sehen und nicht im Protokoll des iobrokers.

Das ist 1:1 das gleiche Log, nur dass die Ausgabe im Script gefiltert wird (also genauso, wie man das Log im Protokoll-Tab filtern kann). Momentan kann man doch alles erreichen, was man möchte. Was fehlt?

Man könnte eventuell über eine verbose-Option für den Debug-Baustein nachdenken, sodass die Logzeile nur geschrieben wird, wenn im Script "Ausführliche Protokollausgaben" aktiv ist.
