### ISSUE TITLE
[Bug]: Can't install specific npm package ( node-fetach@2.6.6 )

### ISSUE THREAD

**Issue by TrackerTheCode** [ioBroker/ioBroker.javascript#1526]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/119059805/3b0218c8-cdef-4987-a282-9c07120f6663)

This version will not be installed. The current version is still installed.

### Version of nodejs

v18.19.1

### Version of ioBroker js-controller

?

### Version of adapter

v7.8.0

**Comment by klein0r** [comment]
No information provided ...

**Comment by TrackerTheCode** [comment]
@klein0r what additional information do you requiere?

**Comment by klein0r** [comment]
I've tested it with the latest 2.x version and it worked `node-fetch@2.6.13`
Please attach a debug log.
