### ISSUE TITLE
[Feauture request] Add variable object functionality in Blockly

### ISSUE THREAD

**Issue by flyceo** [ioBroker/ioBroker.javascript#154]
It would be great if all the blocks in "system" where an object id is expected would also take a variable as valid object id.
Currently theres's no easy way to set or get values of an object when the ID of this object is stored in a variable.

**Comment by GermanBluefox** [comment]
If you want to implement something like this, so you are advanced user and you can use Javascript :)

**Comment by Homoran** [comment]
I also would like a possibility like this.

I'm not an advanced user, and if you will call me such, my personal issue is that I cannot remember all possible commands and their syntax.
At every Line I have to search again any docus etc.
Blockly really helps me a lot to do any programming at all

**Comment by AlCalzone** [comment]
> I'm not an advanced user, and if you will call me such, my personal issue is that I cannot remember all possible commands and their syntax.

At least for the possible commands, there's [auto-completion](https://github.com/ioBroker/ioBroker.javascript/pull/124) :stuck_out_tongue_winking_eye: 
But I get your point.

**Comment by thewhobox** [comment]
I added the new Block-Element with an text Input as ObjectId localy.
I will make a Pull Request soon, so everybody kann use it as they Need.
![image](https://user-images.githubusercontent.com/45664417/53653897-b5fdc900-3c4c-11e9-9493-e0d3e18a49a4.png)

**Comment by GermanBluefox** [comment]
It is merged

**Comment by Rantanplan01** [comment]
Warum ist es wieder rausgenommen worden?
[https://forum.iobroker.net/post/235309](url)

**Comment by Rantanplan01** [comment]
in v4.1.12 übernommen. Funktioniert gut.
Vielen Dank an thewhobox.
Könnte geschlossen werden.
