### ISSUE TITLE
[Bug]: Muss mit F5 aktualisiert werden

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.javascript#1546]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Getestet mit Blockly, Rules

### The problem

Plattform: Win64
Browser: Chrome / Firefox

Hallo.

Unter Admin/Skripte möchte ich einen neuen Ordner bzw. neues Skript erzeugen. Dieses wird aber erst dann Angezeigt, wenn ich die Anzeige des Browsers mit F5 aktualisiere.

	- + Auswählen zum erzeugen eines neuen Scriptes
<img width="424" alt="01 Plus wählen" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/f36f19d1-34d8-46a2-a3d6-4ed3bc4a2eae">

	- Blockly Hinzufügen

<img width="186" alt="02 Blockly hinzufügen " src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/87153d6c-4001-41fe-9c0b-bf503470e981">

	- Auswahldialog für das Blockly mit ok
 
<img width="705" alt="03 Neues Script" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/d2420122-8cfc-4ef0-81db-c647182f381a">

	- Neues Script wird scheinbar nicht erzeugt
 
<img width="517" alt="04 Script nich da" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/83ba42e1-0784-4789-8f7f-7679bb339108">

	- Browser mit F5 aktualisieren

	- Skript erscheint
<img width="391" alt="05 Script wird Angzeigt" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/841eb0c3-f267-452e-aef8-d74a60749949">

### Version of nodejs

18.20.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.0

**Comment by UweRP** [comment]
Ist in Adapter Version 8.0.2 behoben.

**Comment by klein0r** [comment]
See https://forum.iobroker.net/topic/73946/javascript-adapter-8-0-0/

Issue: https://github.com/ioBroker/socket-client/issues/23
