### ISSUE TITLE
[Bug]: Alle Texte auf Englisch in 8.0.2

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.javascript#1547]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Plattform: Win64
Browser: Chrome

Hallo.

Ich möchte ein Blockly bearbeiten.

Es erscheint der SPEICHERN / ABBRECHEN Button und das rote Quadrat.
<img width="326" alt="01 Buttons und Qudrat" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/871d94b9-a094-4568-a14c-1ae2664fb963">

Ich klicke SPEICHERN und die Buttons verschwinden das Qudrat bleibt
<img width="333" alt="02 Buttons verschwinden Qudrat bleibt" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/25b95201-6703-46d4-be98-cd92d8e58f5c">

Will ich die Script Bearbeitung durch X verlassen erhalte ich eine Meldung
<img width="722" alt="03 Meldung" src="https://github.com/ioBroker/ioBroker.javascript/assets/17329042/29e66a57-04c6-425b-a65e-94172581693a">

### Version of nodejs

18.20.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.0

**Comment by UweRP** [comment]
Ist in Adapter Version 8.0.2 behoben, Allerdings ist nun alles in englisch

**Comment by klein0r** [comment]
> Allerdings ist nun alles in englisch

Ja, leider hat die letzte Version des Frameworks einen Bug, weswegen ich auf eine ältere zurück musste. Ich warte auf einen Fix hier https://github.com/ioBroker/socket-client/issues/23 und gebe dann eine neue Version frei - mit dieser funktionieren die Übersetzungen dann wieder.

**Comment by klein0r** [comment]
Sollte in 8.0.3 behoben sein

**Comment by UweRP** [comment]
Oh ja, alles wieder deutsch :relaxed:
Vielen Danke für den Support :+1:
