### ISSUE TITLE
[Bug]: script start/stop toggle dont work

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#1548]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly, Rules, JavaScript, TypeScript, ...

### The problem

cant start stop the script

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6681528/ea5c12b5-293a-46d5-bdb7-23131c3d194d)

save status ist also buggy
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6681528/01bd9bb3-fbd2-444e-80b2-78aa38f661e4)

### Version of nodejs

18.19.1

### Version of ioBroker js-controller

5.019

### Version of adapter

8.0.1

**Comment by arteck** [comment]
8.0.2 works

**Comment by klein0r** [comment]
See https://forum.iobroker.net/topic/73946/javascript-adapter-8-0-0/

Issue: https://github.com/ioBroker/socket-client/issues/23
