### ISSUE TITLE
Implement syncronous methods incl. sleep and such

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#155]
Idea see https://forum.iobroker.net/viewtopic.php?t=6175#p63581

**Comment by GermanBluefox** [comment]
deasync: https://www.npmjs.com/package/deasync
But it is VERY ineffective

**Comment by GermanBluefox** [comment]
use async awayt.... But from node.js 8

**Comment by AlCalzone** [comment]
We should do this for all adapter APIs that are currently using a callback - just like we did in adapter.js with the xyzAsync methods.
