### ISSUE TITLE
Position von Block pass nach rückgängig machen nicht mehr

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.javascript#1550]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Ausgangslage:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/50423935/730df298-cbae-410e-921e-0e03d7da4875)

Verschieben:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/50423935/ce70a54d-459f-4234-8712-5b51e40a4755)

Strg+Z (Rückgängig)
![image](https://github.com/ioBroker/ioBroker.javascript/assets/50423935/40ba94c5-5291-451c-88cd-77740fc7cb95)

(Position zu weit unten)

### Version of nodejs

18.20.2

### Version of ioBroker js-controller

5.0.19

### Version of adapter

7.9.1

**Comment by klein0r** [comment]
Was ist denn das gewünschte Ergebnis? Ich weiß nicht, ob Blockly sich die vorige Position überhaupt merkt.

**Comment by klein0r** [comment]
Blockly ist ein Produkt von Google und wir setzen hier eine relativ alte Version ein (v9.3.3). Ich würde nun also ungern Features in Blockly einbauen (falls das überhaupt geht), welche von Google in neueren Versionen längst behoben sind oder geändert wurden.

**Comment by unstressable** [comment]
Okay, das wusste ich nicht.
