### ISSUE TITLE
[Bug]: Baustein aktivieren / deaktivieren

### ISSUE THREAD

**Issue by ABU1201** [ioBroker/ioBroker.javascript#1553]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Problem tritt nach dem letzten Javascript Update (V7.8.0) auf.
Einfach einen einfachen Baustein ohne irdendwelche Werte in Blockly zur Demonstration generieren.
![Bild1](https://github.com/ioBroker/ioBroker.javascript/assets/149869011/9fb85b7c-7fc3-4583-a9af-8c9e77344183).
Jetzt einen Baustein deaktivieren
![Bild2](https://github.com/ioBroker/ioBroker.javascript/assets/149869011/49378f2e-5a39-4cc6-9700-7d595edd36c6)
Dann das Blockly Script speichern und den Editor schliessen.
Dann erneut das Script in den Editor laden und versuchen den vorher deaktivierten Baustein zu aktivieren.
![Bild3](https://github.com/ioBroker/ioBroker.javascript/assets/149869011/8927c654-976b-4b8e-93e8-bc5dfe3aa7c9)
Der Baustein bleibt jetzt trotz aktivieren grau und im Menü kann ich ihn jetzt auch wieder deaktivieren obwohl er bereits deaktiviert ist.
![Bild4](https://github.com/ioBroker/ioBroker.javascript/assets/149869011/a9db8738-5db0-4c4a-a430-a3591d97fcf7)
Wenn ich jetzt den grauen Block erneut deaktiviere und anschliessend aktiviere ist alles wieder in Ordnung.
Leider muss der Vorgang jetzt immer 2 mal ausgeführt werden, damit es wieder sauber ist.

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

7.8.0

**Comment by Diginix** [comment]
Kann ich bestätigen.

**Comment by klein0r** [comment]
Bitte mit der aktuellen beta 8.0.3 testen - da sind wir schon deutlich weiter als in 7.8.0

**Comment by Diginix** [comment]
Hatte nur die Ver. vergessen, aber ich bin auf 8.0.3 und habe das Problem dort weiterhin.

**Comment by MichaelSchaaf999** [comment]
Bestätigt, halte ich für einen Bug.

**Comment by zaphod2** [comment]
Auch mit 8.1.1 vorhanden.

**Comment by klein0r** [comment]
> Der Baustein bleibt jetzt trotz aktivieren grau und im Menü kann ich ihn jetzt auch wieder deaktivieren obwohl er bereits deaktiviert ist.

- Das Script ändert sich (man kann erneut speichern)
- Im Blockly-Export ist der Block aktiv
- Beim Umschalten zu JavaScript und zurück ist der Block aktiv

Es scheint also alles zu klappen - außer, dass der Block die Darstellung ändert. Seltsam.
Danke, muss ich mir in Ruhe anschauen.

**Comment by sansonifabio** [comment]
....ich hatte das selbe Problem auch schon länger, aber mit der Version 8.4.0 tritt das nicht mehr auf.;-)
Grüße
Fabio

**Comment by Diginix** [comment]
Bei mir funktioniert mit 8.4.1 das de-/aktivieren von Blöcken auch wieder korrekt.

**Comment by klein0r** [comment]
@Diginix Ich mag irgendwie keine Probleme, welche spontan kommen und dann spontan wieder gehen. Habe nichts geändert. Völlig unerklärlich für mich.

**Comment by Diginix** [comment]
> @Diginix Ich mag irgendwie keine Probleme, welche spontan kommen und dann spontan wieder gehen. Habe nichts geändert. Völlig unerklärlich für mich.

Hatte mich auch schon gewundert, da nichts davon im changelog stand. Aber nachdem @sansonifabio hier schrieb, dass es bei ihm wieder geht, habe ich auch mal getestet. Scheint also bei allen betroffenen wieder zu gehen. Spontane Selbstheilung kommt doch immer wieder mal vor. Muss man wohl mit leben. Irgend ein commit bei 8.4.0 scheint da ja involviert zu sein.

**Comment by klein0r** [comment]
> Spontane Selbstheilung kommt doch immer wieder mal vor.

Eigentlich nicht. Also muss es mit irgendwelchen Dependencies einen komischen Seiteneffekt gegeben haben, ... gerade in adpater-react-v5 hat sich ja sehr viel getan in letzter Zeit.

**Comment by MichaelSchaaf999** [comment]
Ich fürchte, es ist browserabhängig. Beobachtet mal unter Firefox, dann unter Chrome aber alles okay. 
Ich hab das nicht weiter vertieft und keine Testreihen angestrengt.
