### ISSUE TITLE
Use js-controller v6 methods to manage node modules

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#1554]
**Is your feature request related to a problem? Please describe.**
Currently when installing user defined node modules, npm will clean them at every operation, leading to the module not being available until a restart of javascript adapter. 

**Describe the solution you'd like**
js-controller v6 introduces new methods with https://github.com/ioBroker/ioBroker.js-controller/pull/2650 to install and require node modules without running into this issue

**Describe alternatives you've considered**
None

**Additional context**
Code needs to check if methods available if yes use this method else stick to old behavior

**Only for implementing developer:** To test the feature locally with the js-controller v6, simply install `iobroker.js-controller@dev`

**Comment by klein0r** [comment]
> **Only for implementing developer:** To test the feature locally with the js-controller v6, simply install `iobroker.js-controller@dev`

`@dev` is `5.0.20-alpha.0-20240502-e03492751` instead of 6.x ?

**Comment by foxriver76** [comment]
Yes, at development time there is no v6

**Comment by klein0r** [comment]
@foxriver76 Please review 3bc5b19d35c7ca7f38eb17b99d9deaf899abc007

**Comment by foxriver76** [comment]
I think this should be awaited too https://github.com/ioBroker/ioBroker.javascript/commit/3bc5b19d35c7ca7f38eb17b99d9deaf899abc007#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR1813

Do you know if there is also code somewhere to remove the node modules?

**Comment by klein0r** [comment]
> Do you know if there is also code somewhere to remove the node modules?

At the moment: no.

Can you provide some function to get all installed packages for the current namespace? In that case I could remove all packages which are not in the packages list of the instance.

**Comment by foxriver76** [comment]
Yes, so we need something like a `adapter.listInstalledNodeModules()` returning a string with the package names. I can implement no problem.

**Comment by foxriver76** [comment]
Please have a look if this will be suitable for you: https://github.com/ioBroker/ioBroker.js-controller/pull/2723
