### ISSUE TITLE
[Bug]: Logging below the script stopped working a while ago

### ISSUE THREAD

**Issue by simplest-circuits** [ioBroker/ioBroker.javascript#1561]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

I recall that the output from the "console.log()" function used to appear below the script for debugging or informational purposes. However, there has been no output in the area below (indicated by the red box) since then. While the output displays correctly in general debug mode, it doesn't show up when I run the script normally; this behavior is consistent in the extended protocol output as well.

I'm not certain when this issue started, but it was likely over a year ago (I'm unsure of the exact version). I exclusively use JavaScript and cannot confirm if this behavior is the same in Blockly or TypeScript, as I have never used those.

![image](https://github.com/ioBroker/ioBroker.javascript/assets/9512751/c46eb835-340f-4190-a5a4-fc430f56f5fc)

### Version of nodejs

v18.19.0

### Version of ioBroker js-controller

 5.0.19

### Version of adapter

8.0.3

**Comment by klein0r** [comment]
- Which browser (and version)?
- Which version of socketio adpater?

**Comment by simplest-circuits** [comment]
Using Chrome (latest Version 124.0.6367.118)
Socketio Adapter: 6.7.0

Same behavior on MS edge.

I remember that it worked a long time ago without any issues. In the meantime I updated iobroker periodically (using buanet docker (latest)). All adapters and also iobroker self is updated to the latest available versions.

**Comment by klein0r** [comment]
Do you have any errors/warnings in the developer tools / console of your browser?
