### ISSUE TITLE
Monaco: localization

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.javascript#157]
https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html

**Comment by AlCalzone** [comment]
To do so, we need to switch to the requirejs way of loading the editor. I implemented it with a custom webpack build (https://github.com/AlCalzone/ioBroker.javascript-editor) but the webpack version of the editor does not seem to have localized files.

**Comment by AlCalzone** [comment]
I'll probably do this together with https://github.com/ioBroker/ioBroker.javascript/issues/164
