### ISSUE TITLE
[Bug]: set cronjob is buggy

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#1571]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

cronjob definition

### The problem

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6681528/55222e12-b797-4d00-a538-4fd2aa6e1bb8)
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6681528/6bd9a325-c731-4c01-b337-c59b6f0d03b4)

check cronjob definitions .. i cant set day and hour

### Version of nodejs

18

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.3.0

**Comment by klein0r** [comment]
That dialog is a component of https://github.com/ioBroker/adapter-react-v5

**Comment by Apollon77** [comment]
hm .. I can not transfer the issue ... @GermanBluefox @foxriver76

**Comment by arteck** [comment]
https://github.com/ioBroker/ioBroker.javascript/assets/6681528/21fdecc2-8a43-4f83-88c6-ff3d727d949b
