### ISSUE TITLE
[Bug]: Error bei Astrozeiten nachts im Sommer im Norden

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1575]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

all

### The problem

Die Datenpunkte "variables.astro.night" und  "variables.astro.night" sollten nur für Breitengrade <= 48.56 ° erstellt werden.
Die Datenpunkte "variables.astro.nauticalDust" und  "variables.astro.nauticalDawn" sollten nur für Breitengrade <= 54.56 ° erstellt werden. 
Siehe [Dämmerung](https://de.wikipedia.org/wiki/D%C3%A4mmerung)

### iobroker.current.log (in debug mode!)

javascript.0
2024-05-23 06:49:25.093	error	[sunTimeSchedules] Unable to set state for astro time "night"
 
javascript.0
2024-05-23 06:49:25.092	error	[sunTimeSchedules] Unable to set state for astro time "nightEnd"

### Version of nodejs

20.13.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.3.1

**Comment by klein0r** [comment]
Already fixed in https://github.com/ioBroker/ioBroker.javascript/commit/cbfbb2534d238e0a0efcbdf05edd7040a9b21008
