### ISSUE TITLE
[Bug]: npm modules in javascript instance are broker after update to newer version

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#1576]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

dont care

### The problem

In the Javascript instance v8.0.3 on my production system, the npm modules are correctly displayed individually.
On my test system, Javascript is on 8.3.1 and there it now also looks like everything is in one item

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/25422320/ed21ef4a-a9d1-4499-a478-2d1bdea5020b)

Native-Objekt of Instanz-Object:
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/25422320/6861b5df-f39d-4fc0-949c-b6408cfbbd77)

Problem:
libraries is not an array
"libraries": "xml2js moment moment-timezone moment-duration-format mathjs",

### Version of nodejs

18.20.3

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.3.1

**Comment by tt-tom17** [comment]
Mir sind noch zwei Sachen aufgefallen.
Wenn die Syntaxhilfe der npm-Module leer ist, sehe ich nicht die Auswahl für die Instanz Spiegelung.

<img width="2378" alt="Bildschirmfoto 2024-05-25 um 11 07 36" src="https://github.com/ioBroker/ioBroker.javascript/assets/101348966/abd220b2-f171-4920-bb05-63e6a6f44910">

Erst wenn ich ein Buchstabe ins Feld Syntaxhilfe setze, erscheint das Auswahlfeld
<img width="2378" alt="Bildschirmfoto 2024-05-25 um 11 08 05" src="https://github.com/ioBroker/ioBroker.javascript/assets/101348966/c927520f-46b5-4399-868e-7eb2decb5c43">

Ich kann auch keine Module in die Syntaxhilfe eintragen, heißt mit Enter wurde der Name übernommen und man konnte das nächste Modul eintragen. Sah dann so aus. 

<img width="344" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/101348966/7fdbf5b3-ddf7-40bc-92a4-af12582fb92b">

**Comment by klein0r** [comment]
Fixed in 8.4.0

**Comment by Feuer-sturm** [comment]
Nach Update auf 8.4.0 werden die Module in der Instanz richtig dargestellt
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/25422320/e4ba5736-dc0e-47ac-ad11-426f42cf531d)
