### ISSUE TITLE
JS 8.4.0: Keine Astroeinstellungen in Konfiguration möglich

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#1578]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

n/a

### The problem

Im Tab "ASTRO-EINSTELLUNGEN" gibt es nur noch den Haken für "Erstelle Zustände für alle Astrozeiten".
Getestet unter Admin 6.15.2 / 6.17.14

### Version of nodejs

20.13.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.4.0

**Comment by klein0r** [comment]
@GermanBluefox Please check why the custom component isn't displayed anymore. I've no idea what's wrong

**Comment by winnyschuster** [comment]
> @GermanBluefox Please check why the custom component isn't displayed anymore. I've no idea what's wrong

Durch die `gulpfile.js` wird gesteuert welche Dateien letztlich nach `admin/static` und `admin/custom/static` kopiert werden. In Zeile 52 + 53 wird das beschränkt. 
ab Zeile 54 folgendes einfügen und es funktioniert wieder:
``` 
gulp.src(['src-admin/build/static/js/vendors-node_modules_leaflet_dist_leaflet_css-node_modules_mui*ThemeProvider*.js']).pipe(gulp.dest('admin/custom/static/js')),
gulp.src(['src-admin/build/static/js/vendors-node_modules_leaflet_dist_leaflet_css-node_modules_mui*ThemeProvider*.map']).pipe(gulp.dest('admin/custom/static/js')),
gulp.src(['src-admin/build/static/js/vendors-node_modules_mui*esm*.js']).pipe(gulp.dest('admin/custom/static/js')),
gulp.src(['src-admin/build/static/js/vendors-node_modules_mui*esm*.map']).pipe(gulp.dest('admin/custom/static/js')),
```

Achtung, es werden dadurch etwas mehr als nur die fehlenden Dateien kopiert. Wenn das ein Problem ist in den dev tools schauen welche Dateien genau fehlen(3 ohne die .map) und meine 4 Zeilen anpassen.
Nach `npm run build` mit `npm pack` packen und lokal zum Testen installieren(`npm i *.tgz`)

Hoffe es hilftt dir

**Comment by klein0r** [comment]
@winnyschuster Besten Dank, ich hab die build-Verzeichnisse / grunt-Tasks gar nicht verglichen - ich dachte da hat sich irgendetwas in adapter-react-v5 geändert, was man anpassen müsste (weil ich die Dependency aktualisiert hatte und es danach nicht mehr ging).

**Comment by klein0r** [comment]
> Nach `npm run build` mit `npm pack` packen und lokal zum Testen installieren(`npm i *.tgz`)

Schau Dir mal den `dev-server` an - damit ist vieles sehr viel einfacher 👍 

- https://github.com/ioBroker/dev-server
- https://www.youtube.com/watch?v=A9UETXyAmL4
- https://www.youtube.com/watch?v=Glx4kd3eX70
