### ISSUE TITLE
[Blockly] Neuer Block: "Bestätige"

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.javascript#1582]
Manche Datenpunktänderungen im Userdata Ordner verarbeite ich anschließend im Blockly. Dabei setze ich die Werte zuerst unbestätigt, um sie dann im Blockly Skript nach Verarbeitung auf "bestätigt" zu setzen. Damit weiß ich, dass mein Blockly Skript durchgelaufen ist. (Standard ioBroker Logik).
Leider gibt es derzeit keine schöne Möglichkeit dieses von Adaptern bekannte Verhalten im Blockly logisch fortzuführen. Die beste mir bekannte Lösung ist wohl:
<img width="208" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/8447146/46808dd1-d0ca-4818-b0ed-73d9ec62ee7c">
So ist allerdings erst auf den zweiten Blick erkennbar, was damit eigentlich erreicht werden soll.

Hierfür könnte ich mir einen Block unter "System" vorstellen, der "Bestätige" durchführt. Einziger Input wäre die ObjektID.
Der Block würde dann nur den "bestätigt-Status" ändern.

**Comment by Diginix** [comment]
Mache ich auch so und reicht für mich bisher.
Wenn du nicht einzelne Trigger auf Objekte haben willst, kannst du auch einen mit zB regex nutzen, der auf alles unterhalb von `0_userdata\.(.*)` lauscht.

**Comment by Diginix** [comment]
Ok, du willst dann im Skript innerhalb eines einzelnen Objekttriggers den Block und dabei weder ObjektID noch Wert explizit definieren? D.h. was und wo muss durch den Umgebenden Triggerblock klar sein. Ansonsten fehlt der Kontext.

**Comment by ScumbagSteve** [comment]
Ja genau. ObjektID hatte ich ja vorgeschlagen als Input zu machen. In den meisten Fällen würde ich da dann den Block "ObjektID" aus dem Trigger nehmen. So wird immer die getriggerte ObjektID bestätigt.

Den Wert möchte ich ja eben nicht ändern, sondern nur bestätigen, daher bräuchte es keinen "Wert" Input (sonst wäre es ja das selbe, wie der vorhandene Block).

**Comment by Diginix** [comment]
Ich glaube man kann einen state nicht "nur" bestätigen, ohne ihm auch den Wert erneut zu geben. Habe es zumindest selbst in JS noch nicht anders gesehen. Daher ist der von dir gezeigte Block eigentlich genau richtig. Dein Wunschblock würde dann im JS auch nur den bekannten Wert erneut nutzen, ohne dass man es in Blockly sieht. Aber vllt. geht es ja doch auch anders...

**Comment by ScumbagSteve** [comment]
Ja das hatte ich mich auch schon gefragt. Wäre aber auch okay wenn im Hintergrund einfach nochmal der aktuelle Wert ermittelt und dieser dann gesetzt+bestätigt wird.

**Comment by ScumbagSteve** [comment]
@klein0r danke ☺️
