### ISSUE TITLE
Javascript log output is somtimes empty

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.javascript#159]
Somtimes in the javascript editor window the log area under the script window doesn't show log output. Tested with Firefox 61.0.1 and Chrome 67.0.3396.99. Restart of the javascript-Adapter might help, but not every time.

See https://forum.iobroker.net/viewtopic.php?f=21&t=15646

**Comment by AlCalzone** [comment]
Can confirm. I think it has something to do with the admin adapter or the js tab subscribing/unsubscribing to the logs

**Comment by GermanBluefox** [comment]
It has something to do with 2 or more browser tabs with admin

**Comment by AlCalzone** [comment]
Can we fix that somehow?

**Comment by AlCalzone** [comment]
I often use two tabs/windows to debug something - objects in one, scripts in another

**Comment by GermanBluefox** [comment]
And guess it has something to do with 2 tabs. Only one has logs

ср, 25 июл. 2018 г., 16:56 AlCalzone <notifications@github.com>:

**Comment by Thisoft** [comment]
Sorry, I cant confirm that it has to do with 2 tabs. I never opened ioBroker-admin in 2 tabs and nevertheless sometimes I have the log and sometimes no log in the javascript editor.

**Comment by stabilostick** [comment]
Same Chrome Browser, Two different ioBroker systems. Javascript. Windows works, Raspi doesn't.

**Comment by Marty56** [comment]
Same behavior on Safari. 
Also I see that even in the log Tab, the log file does not refresh automatically.
I always have to click the reload button.

The log windows under the script editor only works very exceptionally and if it is working only for very short time. E.g. after two time saving a script and restarting it the log window stops working.

**Comment by surumadurum** [comment]
same here with me on Opera :(

**Comment by michaelrummel** [comment]
I have this problem with the 'Log' tab. In the script editor it is ok.
I also tried with just one open tab open and with Firefox, Chrome and Edge. Always the same. The log file is written but nothing shown in the corresponding window.
At least I can upload the file from the Raspi for checking it.

**Comment by Mihaeru2110** [comment]
I have this problem with the 'Log' tab. In the script editor it is ok.
I also tried with just one open tab open and with Firefox, Chrome and Edge. Always the same. The log file is written but nothing shown in the corresponding window.
At least I can upload the file from the Raspi for checking it.

**Comment by GermanBluefox** [comment]
Must be fixed with admin 3.5.9

**Comment by GermanBluefox** [comment]
Please reopen, if still relevant
