### ISSUE TITLE
Fehler mit der Astrozeit

### ISSUE THREAD

**Issue by zaphod2** [ioBroker/ioBroker.javascript#1595]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Allgemein

### The problem

<img width="530" alt="Screenshot 2024-06-01 100307" src="https://github.com/ioBroker/ioBroker.javascript/assets/96678159/06e2c4b2-c6f5-4802-8cb3-b68e52ad7b8f">

Das kommt auch um 12:00 Uhr.

### Version of nodejs

20.13.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.4.2

**Comment by zaphod2** [comment]
sorry, ich sehe gerade wo der Fehler sitzt.

**Comment by klein0r** [comment]
Gerne auch die Suche nutzen (auch in den geschlossenen Issues): Hatten wir hier erst #1580

**Comment by IOGogo** [comment]
Wie wurde der Punkt gelöst?

**Comment by mcm1957** [comment]
In den nördlichen Gebiezen gibt es "night 'im Sommer nicht. Da sich die Sonne nicht kooperativ zeigt wird sich das auch nicht ändern.

**Comment by IOGogo** [comment]
Okay , danke für die schnelle Rückmeldung.. Trifft das für den Südwesten Raum Frankfurt zu ?
-------- Ursprüngliche Nachricht --------Von: "Martin M." ***@***.***> Datum: 03.06.24  12:15  (GMT+01:00) An: "ioBroker/ioBroker.javascript" ***@***.***> Cc: IOGogo ***@***.***>, Comment ***@***.***> Betreff: Re: [ioBroker/ioBroker.javascript] Fehler mit der Astrozeit (Issue
  #1595) 
In den nördlichen Gebiezen gibt es "night 'im Sommer nicht. Da sich die Sonne nicht kooperativ zeigt wird sich das auch nicht ändern.

**Comment by Ilovegym66** [comment]
Schau mal hier, da kann man alles nachlesen:
https://de.wikipedia.org/wiki/D%C3%A4mmerung  und so weiter .. 

Und check mal deine location settings in iobroker, wenn du im Raum FFM/Main keine Nacht bekommst, dann steht da was falsches drin..

**Comment by klein0r** [comment]
> Und check mal deine location settings in iobroker, wenn du im Raum FFM/Main keine Nacht bekommst

???

**Comment by klein0r** [comment]
> Okay , das Blockly läuft seit einem Jahr problemlos. Jetzt soll es an den Einstellungen liegen .. ?

Liegt es nicht. Grund wurden oben genannt. In ein paar Wochen läuft es ja auch wieder (wenn die Tage kürzer werden).

**Comment by IOGogo** [comment]
Okay , danke Matthias für deine Arbeit und Unterstützung 
-------- Ursprüngliche Nachricht --------Von: Matthias Kleine ***@***.***> Datum: 03.06.24  14:48  (GMT+01:00) An: "ioBroker/ioBroker.javascript" ***@***.***> Cc: IOGogo ***@***.***>, Comment ***@***.***> Betreff: Re: [ioBroker/ioBroker.javascript] Fehler mit der Astrozeit (Issue
  #1595) 

Okay , das Blockly läuft seit einem Jahr problemlos. Jetzt soll es an den Einstellungen liegen .. ?

Liegt es nicht. Grund wurden oben genannt. In ein paar Wochen läuft es ja auch wieder (wenn die Tage kürzer werden).
