### ISSUE TITLE
[Bug]: Warnung/ Error Astro Blockly  script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx

### ISSUE THREAD

**Issue by IOGogo** [ioBroker/ioBroker.javascript#1596]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Astro Blockly

### The problem

Bei der Ausführung vom Astro Blockly bekomme ich folgende Meldung → script.js.Meine_Skripte.TestSkipte.Skript_1: Cannot calculate "nightEnd" for XXXXXXXXXX, XXXXXXXXXXXX
In den Systemeinstellungen ist der Längen- und Breitengrad hinterlegt.

### iobroker.current.log (in debug mode!)

script.js.Meine_Skripte.TestSkipte.Skript_1: Cannot calculate "nightEnd" for XXXXXXXXXX, XXXXXXXXXXXX

### Version of nodejs

18.20.3

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.3.1

**Comment by mcm1957** [comment]
https://github.com/ioBroker/ioBroker.javascript/issues/1580

8.3.1 is not the current beta Version. Did you really check with 8.3.4? Or did youbonly Mark the checkbox?

**Comment by IOGogo** [comment]
Hallo Martin,

die von Dir genannte V 8.3.4 kann ich unter Beta  nicht finden.

 



 

Unter Beta werden aus meiner Sicht ältere Versionen angezeigt :

 

 



 

 

 

 

Ich habe die V 8.4.2 über die Katze installiert und hatte das gleiche Fehlerbild.

 

Danke im Voraus für Deine Untersützung

 

 

 

 

 

 

Von: Martin M. ***@***.***> 
Gesendet: Montag, 3. Juni 2024 08:08
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

#1580 <https://github.com/ioBroker/ioBroker.javascript/issues/1580> 

8.3.1 is not the current beta Version. Did you really check with 8.3.4? Or did youbonly Mark the checkbox?

**Comment by klein0r** [comment]
> Ich habe die V 8.4.2 über die Katze installiert

Bitte nie Adapter über GitHub installieren, nur über npm

**Comment by IOGogo** [comment]
3.6.2024, 08:50:03.558          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:03.643          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:03.645          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:11.183          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:11.228          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:11.230          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:17.439          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:17.482          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:17.484          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:22.980          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:23.023          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:23.025          [warn ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: Cannot calculate "night" for XXXXXXX, XXXXXX

3.6.2024, 08:50:23.025          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:44.691          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:45.534          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:45.536          [warn ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: Cannot calculate "night" for XXXXXXX, XXXXXXX

3.6.2024, 08:50:45.536          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:51.784          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:51.868          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:51.870          [warn ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: Cannot calculate "nightEnd" for XXXXXX, XXXXXXX

3.6.2024, 08:50:51.870          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

3.6.2024, 08:50:57.379          [info ]: javascript.0 (452) Stopping script script.js.common.Eigene_.Skript_1

3.6.2024, 08:50:57.422          [info ]: javascript.0 (452) Start JavaScript script.js.common.Eigene_.Skript_1 (Blockly)

3.6.2024, 08:50:57.424          [info ]: javascript.0 (452) script.js.common.Eigene_.Skript_1: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions

 

Von: Martin M. ***@***.***> 
Gesendet: Montag, 3. Juni 2024 08:08
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

#1580 <https://github.com/ioBroker/ioBroker.javascript/issues/1580> 

8.3.1 is not the current beta Version. Did you really check with 8.3.4? Or did youbonly Mark the checkbox?

**Comment by IOGogo** [comment]
Hallo Martin,

die Warnung wird nur bei der Auswahl Nacht und Nachtende angezeigt.

 

Von: Martin M. ***@***.***> 
Gesendet: Montag, 3. Juni 2024 08:08
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

#1580 <https://github.com/ioBroker/ioBroker.javascript/issues/1580> 

8.3.1 is not the current beta Version. Did you really check with 8.3.4? Or did youbonly Mark the checkbox?

**Comment by IOGogo** [comment]
Danke, okay melde mich gleich

 

 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 3. Juni 2024 08:50
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

Ich habe die V 8.4.2 über die Katze installiert

Bitte nie Adapter über GitHub installieren, nur über npm

**Comment by IOGogo** [comment]
Es besteht das gleiche Problem wie bereits berichte.

Betroffen von der Warnung ist nur Nacht und Nachtende ..

 



 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 3. Juni 2024 08:50
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

Ich habe die V 8.4.2 über die Katze installiert

Bitte nie Adapter über GitHub installieren, nur über npm

**Comment by IOGogo** [comment]
Sorry, hatte ich nicht gesehen 

 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 3. Juni 2024 09:23
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

Duplicate of #1580 <https://github.com/ioBroker/ioBroker.javascript/issues/1580>  #1595 <https://github.com/ioBroker/ioBroker.javascript/issues/1595>

**Comment by IOGogo** [comment]
Zaphod 2 hat zwar mitgeteilt, dass er den Fehler gefunden hat ? Aber nicht was die mögliche Ursache gewesen ist.

 

Von: Matthias Kleine ***@***.***> 
Gesendet: Montag, 3. Juni 2024 09:23
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: IOGogo ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] [Bug]: Warnung/ Error Astro Blockly script.js. Cannot calculate "night" for xxxxxxxxx, xxxxxxxxxx (Issue #1596)

 

Closed #1596 <https://github.com/ioBroker/ioBroker.javascript/issues/1596>  as completed.

**Comment by klein0r** [comment]
Welchen Fehler denn genau? Das arbeitet alles korrekt so. Die Tage sind aktuell so kurz, dass die Sonne nie den Punkt unterschreitet, welcher die "Nacht" definiert. Also kann der auch nicht berechnet werden.
