### ISSUE TITLE
[Bug]: Object-Browser in Blockly-Blocks don't work

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.javascript#1607]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Probably all blocks with Object-Browser are affected.

### iobroker.current.log (in debug mode!)

TypeError: s is undefined
    getObjectName Utils.js:119
    onAfterSelect ObjectBrowser.js:2596
    loadAllObjects ObjectBrowser.js:2550
    expandAllSelected ObjectBrowser.js:2585
    loadAllObjects ObjectBrowser.js:2550
    React 7
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
react-dom.production.min.js:188:119
Uncaught TypeError: s is undefined
    getObjectName Utils.js:119
    onAfterSelect ObjectBrowser.js:2596
    loadAllObjects ObjectBrowser.js:2550
    expandAllSelected ObjectBrowser.js:2585
    loadAllObjects ObjectBrowser.js:2550
    React 7
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
Utils.js:119:18

### Version of nodejs

v18.20.3

### Version of ioBroker js-controller

v5.0.19

### Version of adapter

v8.5.2

**Comment by MichaelSchaaf999** [comment]
@klein0r 
Hi Matthias,

Is this the same issue I encountered here?

1. Open a new Blockly script.
2. Save it.
3. Get a trigger block...
<img width="513" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/53481090/04a5eee5-9b13-4688-8b78-8c724514d72f">

4. Click on "ID auswählen"...  the process seems to start:
<img width="1373" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/53481090/e3cc369a-7e6b-428d-93ed-25925a31b56a">

5. A second later the window is empty:
<img width="1383" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/53481090/0eb714d6-bd3c-4c5b-b8db-7a50b3fd5117">
...and the process seems to stop.

6. Refreshing the browser windows works.
But the ID selector is not responding (in my poor words).

**Comment by itwegner72** [comment]
I Have the same Problem and Downgradet to 8.4.2     There is no Problem.

**Comment by Voyagermanie** [comment]
Same problem here... :-(

**Comment by itwegner72** [comment]
Not fixed. Problem is same

**Comment by klein0r** [comment]
@itwegner72 v8.6.0 installed via npm?

**Comment by RP70DP** [comment]
v8.6.0 fixed the problem. Thanks a lot!

**Comment by MichaelSchaaf999** [comment]
@klein0r Matthias: Any suggestions how to install v8.6.0?

**Comment by itwegner72** [comment]
v8.6.0 fixed the problem. THX
(Installed over IOB Adapter Page)

**Comment by MichaelSchaaf999** [comment]
Had to refresh the adapter tab first but then saw the 8.6.0. Installed via IOB adapter page as well.
8.6.0 fixed the problem.
THX a lot @klein0r Matthias

**Comment by klein0r** [comment]
> Any suggestions how to install v8.6.0?

As always: via npm (in expert mode), via beta repository and never via GitHub url.

**Comment by MichaelSchaaf999** [comment]
> As always: via npm (in expert mode), via beta repository and never via GitHub url.

Expert mode is on, but which buttons to click for NPM-installation?

**Comment by mcm1957** [comment]
I suggest to use the BETA / LATEST Repository as this provides a normal GUI Basedow Installation flow. ƁUT you should be aware that using Beta / Latest / npm Installation installs a BETA and not fully testen Software. So you should know what you do an do it at own risk if used at a Produktion System.

Installation from npm can be done using cat symbol and select install from npm. 

But again ...
If you are not sure what you are doing I recommend to wait for stable release.

P.S. Our forum https://forum.iobroker.net would be better Suiten for suchvquestions.
