### ISSUE TITLE
Blockly: längere Kommentare

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.javascript#1608]
Fügt man einen Kommentarblock mit längerem Inhalt ein, wird der Text oft mit 3 Punkten (...) abgeschnitten. 

Ich wäre sehr dankbar, wenn dies nicht geschehen würde, oder aber zumindest später passiert.

Sollte unbegrenzt nicht möglich oder gewünscht sein, dann würde ich als Kompromiss vorschlagen, dass der Text 3x so lang sein darf, wie bisher, bis er abgeschnitten wird.

**Comment by klein0r** [comment]
Duplicate of #398
