### ISSUE TITLE
[Bug]: Dependencies installed from GitHub repo need now to be required by their URLs instead of module names (js-controller v6)

### ISSUE THREAD

**Issue by Black-Thunder** [ioBroker/ioBroker.javascript#1611]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

any

### The problem

Follow-up issue to https://github.com/ioBroker/ioBroker.js-controller/issues/2796

Thanks to the quick implementation in js-controller v6 adding custom modules from a GitHub URL now works again. 👍 
The only remaining small "issue" is that in scripts you need to require the module by its full URL instead of its module name, as it used to be.

Example:

![image](https://github.com/ioBroker/ioBroker.javascript/assets/972581/c26cc671-7cc5-42e0-8b8a-b43849d6914d)

``` javascript
// Does NOT work anymore -> Error: Cannot find module 'node-mihome'
const mihome = require("node-mihome");

// Does work now
const mihome = require("git+https://github.com/Black-Thunder/node-mihome.git");
```

Probably because of this line where it is stored in "context.mods" by its "depName" instead of its "moduleName":
https://github.com/ioBroker/ioBroker.javascript/blob/3330827ddd24c642955d47bda3a50ba2f4f5ae0e/main.js#L1873

Is this the intended behaviour now? If so, maybe this should be added to the docs.

### Version of nodejs

20.14.0

### Version of ioBroker js-controller

6.0.4

### Version of adapter

latest GitHub version as of now (commit 3330827)

**Comment by klein0r** [comment]
> Is this the intended behaviour now?

No, i'll fix that
