### ISSUE TITLE
[Bug]: Can't select any objects (for example.. shelly device) within any script

### ISSUE THREAD

**Issue by Roellen** [ioBroker/ioBroker.javascript#1614]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

By adding a "falls object" and selecting the ID (to put in a device which works as a trigger... for example a Shelly 1) then the objects window opens... tries to load... then... white screen. Nothing happens anymore. 
Impossible to select something. Nothing works. Blockly=useless

### iobroker.current.log (in debug mode!)

nothing is beeing logged in this situation

### Version of nodejs

18.19.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.6.1

**Comment by peer69** [comment]
Fixed for me after installing v8.6.0 today. You sure 8.6.1 is the version you're using?

**Comment by mcm1957** [comment]
8.6.0 is the newest Version at npm ...
