### ISSUE TITLE
[Bug]: second parameter of httpPost() - Usage of JSON (conforming to documentation) leads to strange behaviour

### ISSUE THREAD

**Issue by MartinP1** [ioBroker/ioBroker.javascript#1633]
### I'm sure that

- [x ] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

Behavior: 
It seems, that the examples concerning the httpPost() call are misleading. 
In my example, queries for lua pages of fritzbox are issued. I was not able to construct a JSON-pattern, that is working. A raw passing of body text was successful.

I think it would be helpful, either to correct the documentation, or to change the behaviour of the API-call to be conform with the documentation.

httpPost replacement of the following code:

```
    var options = {
        url: docsisURL,
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: 'xhr=1&sid=' + sid + '&lang=de&page=docInfo&xhrId=all&no_sidrenew='
    };
    request(options, function(error, response, body) {
....

```

this code works (adoptation of url to an "Echo Server" for http-posts)

```

httpPost('https://httpbin.org/post',
      'xhr=1&sid=12345678&lang=de&page=docInfo&xhrId=all&no_sidrenew=', 
        {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
    },
        (error, response) => {
.....

```

this does not:

```
httpPost('https://httpbin.org/post',
       {
           form : {
               'lang' : 'de',
               "no_sidrenew" : "",
               "page" : "docInfo",
               "sid" : "12345678",
               "xhr" : "1",
               "xhrId" : "all",
           }

       },
        {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
    },
        (error, response) => {
....

```

It seems, that there is an internal "Jsonification" of second parameter 

Response of echo server to first variant (working):

```
script.js.Spielwiese.Ressourcentest: data: { "args": {}, "data": "", "files": {}, "form": { "lang": "de", "no_sidrenew": "", "page": "docInfo", "sid": "12345678", "xhr": "1", "xhrId": "all" }, "headers": { "Accept": "application/json, text/plain, */*", "Accept-Encoding": "gzip, compress, deflate, br", "Baggage": "sentry-environment=production,sentry-release=iobroker.javascript%408.3.1,sentry-public_key=f3b9740caaee4ee69eb68019d71526ff,sentry-trace_id=4e9d2599655c4da3ba2864550274d0a8", "Content-Length": "62", "Content-Type": "application/x-www-form-urlencoded", "Host": "httpbin.org", "Sentry-Trace": "4e9d2599655c4da3ba2864550274d0a8-83cbd8953e002594", "User-Agent": "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0", "X-Amzn-Trace-Id": "Root=1-6689283a-429cceaf45d9ae7e459c9e1d" }, "json": null, "origin": "1xxxxxxxxxxxx3", "url": "https://httpbin.org/post" } 
```

Response of echo server to second variant (not working with fritzbox)

```
script.js.Spielwiese.Ressourcentest: data: { "args": {}, "data": "", "files": {}, "form": { "form[lang]": "de", "form[no_sidrenew]": "", "form[page]": "docInfo", "form[sid]": "12345678", "form[xhrId]": "all", "form[xhr]": "1" }, "headers": { "Accept": "application/json, text/plain, */*", "Accept-Encoding": "gzip, compress, deflate, br", "Baggage": "sentry-environment=production,sentry-release=iobroker.javascript%408.3.1,sentry-public_key=f3b9740caaee4ee69eb68019d71526ff,sentry-trace_id=4e9d2599655c4da3ba2864550274d0a8", "Content-Length": "122", "Content-Type": "application/x-www-form-urlencoded", "Host": "httpbin.org", "Sentry-Trace": "4e9d2599655c4da3ba2864550274d0a8-9d6cc91120f1be44", "User-Agent": "Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0", "X-Amzn-Trace-Id": "Root=1-668929cd-775f6c7671de680b3ea28670" }, "json": null, "origin": "17xxxxxxxxxxxx43", "url": "https://httpbin.org/post" } 
```

### Version of nodejs

20.15.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

v8.3.1 and 8.6.0

**Comment by MartinP1** [comment]
I have not tested the behaviour with current beta version!
Will remove the check in the issue above

**Comment by mcm1957** [comment]
Please Test with current beta. Thats the pirpose of the check.

Otherwise the issue might be closed.

**Comment by MartinP1** [comment]
I have only one instance of ioBroker (the "productive" one), and do not want to bring instability to my system by beta adapters.

Is it possible to install a second "beta" instance of javascript adapter to my system?

That is the only thing I am able to offer ...

**Comment by winnyschuster** [comment]
this issue also exists in newest beta, per the doku [2nd param](https://github.com/ioBroker/ioBroker.javascript/blob/bdfc9031a32b4f7c7b08203a389e968961aa73cb/lib/sandbox.js#L1254) could be an object, but this is not working, only strings lead to a succesful result

**Comment by klein0r** [comment]
> I was not able to construct a JSON-pattern, that is working. A raw passing of body text was successful.

It depends what the other side expects. You set the http header to form. Which means

> application/x-www-form-urlencoded: the keys and values are encoded in key-value tuples separated by '&', with a '=' between the key and the value.

But: This has nothing to do with JSON?! I don't understand the issue.

**Comment by MartinP1** [comment]
I think, there are not enough examples given in the documentation, or some words should be added concerning the variety of formattings allowed for second parameter https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#httppost. My interpretation of documentation was, that as second parameter there MUST be used JSON.

Spent some time to translate the urlencoded parameter in the old variant of my script passed to discontinued "request" variant to JSON, as I thought it is necessary for httpPost() ;-)

If it is helpful I would try to write something to integrate to ../master/docs/en/javascript.md

**Comment by klein0r** [comment]
> My interpretation of documentation was, that as second parameter there MUST be used JSON.

But you haven't used JSON in your examples. JSON is always a string. You provided an object (which also works, because it will be serialized / strigified internally).

> Spent some time to translate the urlencoded parameter in the old variant of my script passed to discontinued "request" variant to JSON

Okay, but why? Looks like the server side cannot handle json payloads.

**Comment by winnyschuster** [comment]
> this does not:
> 
> ```
> httpPost('https://httpbin.org/post',
>        {
>            form : {
>                'lang' : 'de',
>                "no_sidrenew" : "",
>                "page" : "docInfo",
>                "sid" : "12345678",
>                "xhr" : "1",
>                "xhrId" : "all",
>            }
> 
>        },
>         {
>         headers: {
>             'Content-Type': 'application/x-www-form-urlencoded'
>         },
>     },
>         (error, response) => {
> ```

the object is not what is expected, change it like so and it will work
 ```
{
       'lang' : 'de',
       "no_sidrenew" : "",
       "page" : "docInfo",
       "sid" : "12345678",
       "xhr" : "1",
       "xhrId" : "all",
}
```

**Comment by MartinP1** [comment]
@klein0r Perhap my roots in C/C++ programming are a burdon in this case... If I see something looking similar to a C function prototype I assume, the prototype is covering the types of the parameters. But Javascript type system is not as strict, as the one of C.

That is one part of the problem.

The other part is, that I guessed - after reading the github documentation of httpPost() -, that the ONLY option for passing parameter#2 is using JSON fornat, and was not able to get it working with any of my permutations of JSON-formatted parameter#2.

Conclusion: IMHO It is not an issue in code but in documentation. 

Off topic:

Last Question: my working solution is the following:

`    httpPost(docsisURL,
      'xhr=1&sid=' + sid + '&lang=de&page=docInfo&xhrId=all&no_sidrenew=', 
       // { form:    'xhr=1&sid=' + sid + '&lang=de&page=docInfo&xhrId=all&no_sidrenew='}, 
        {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
    },
        (error, response) => {
`
Is this an solution that is "stable" and "good style" or will it be better to correct it according to the findings of @winnyschuster?
I am a little bit afraid, that my "frickellösung"(?) will not  work over modifications of httpPost().

**Comment by klein0r** [comment]
> Is this an solution that is "stable" and "good style"

I prefer template literals instead of string concatenation with +:

```js
httpPost(
  docsisURL,
  `xhr=1&sid=${sid}&lang=de&page=docInfo&xhrId=all&no_sidrenew=`,
  {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
  },
  (error, response) => {
    // ..
  }
);
```

> Conclusion: IMHO It is not an issue in code but in documentation.

Feel free to provide a PR.
