### ISSUE TITLE
[Bug]:  es wid auf den Ordnernamen getriggert UND auf das Object

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#1639]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

ich trigger auf den DP
![1720804845346-182d3be9-fd8c-4cb2-8fd3-c11494ff2ee8-grafik](https://github.com/user-attachments/assets/c4ea4d6c-874f-45e8-b357-9b410572052b)
shelly.0.SHWT-1#485519F09804#1.sensor.flood

im Telegram kommt x fache Nachricht
![1720804761931-meldung](https://github.com/user-attachments/assets/8a534f17-ff4a-4480-a84f-dd819373adec)
von dem dadrüberliegenden Ordner so zumindest der Object tree
![1720804882439-sensor](https://github.com/user-attachments/assets/64d8512e-3deb-47f8-90f4-92058e9d0e50)

es is ein Problem des Javascript adapter in der Verion 8.6.0
davor tritt es nicht auf

### Version of nodejs

20.x

### Version of ioBroker js-controller

6.0.6

### Version of adapter

8.6.0

**Comment by klein0r** [comment]
> im Telegram kommt x fache Nachricht

Und wo im Script wird diese Meldung versendet?

**Comment by arteck** [comment]
das ist es ja .. niergends.. der Trigger läuft auf den DP flood..
so wie es aussieht zieht der den Ordner sensor (Channel sensor) mit.

**Comment by klein0r** [comment]
Ich sehe in deinem Telegram Adapter nur "Channel Sensor wurde geöffnet" und nicht einmal etwas mit "Küchenfenster" (nur den Auszug sehe ich ja aus dem Script). Die Fehlerbeschreibung ist unvollständig.

Nichts im Script kann diese Meldungen auslösen?!
