### ISSUE TITLE
[Bug]: Importieren der Skripte geht nicht

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.javascript#1669]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

all

### The problem

Beim Importieren der Skripte kommt nach dem Klicken nicht mehr das Auswahlfenster sondern ein weißer Bildschirm 
![Screenshot_2024-08-05-05-36-06-537_com android chrome](https://github.com/user-attachments/assets/f9a052d5-6eff-437c-bd0d-75c44c3d9f54)
![Screenshot_2024-08-05-05-35-55-297_com android chrome](https://github.com/user-attachments/assets/8b331268-19e6-4d9e-ab19-af5e4bb57add)

### iobroker.current.log (in debug mode!)

No log

### Version of nodejs

v20.16.0

### Version of ioBroker js-controller

6.0.9

### Version of adapter

8.7.6

**Comment by MubiTec** [comment]
Getestet mit Chrome,Opera und der iobroker  Visu app

**Comment by Pandia22** [comment]
Ich habe nach dem Upgrade auf die Version V8.7.6 das gleiche Problem festgestellt. Es ist browserunabhängig.

**Comment by Pandia22** [comment]
Neue Version wurde bereitgestellt. Nach dem Einspielen der Version V8.7.7 funktioniert das Importieren der Skripte wieder. Vielen Dank für den Support. :-)

**Comment by klein0r** [comment]
Duplicate of #1651

**Comment by MubiTec** [comment]
Danke!
