### ISSUE TITLE
[Feature idea] Allow having multiple open scripts in a tab view

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#167]
like VSCode and other IDEs do:
![unbenannt](https://user-images.githubusercontent.com/17641229/43516300-78083d24-9585-11e8-99e4-4dea74561788.PNG)
https://github.com/Microsoft/monaco-editor/issues/604#issuecomment-344214706 explains how to keep multiple scripts in memory and switch between them.

**Comment by AlCalzone** [comment]
See also: https://github.com/Microsoft/monaco-editor/issues/990
The basic idea would be to have multiple models (one per script) and switch between them using `editor.setModel`.

This should also allow referencing the global scripts without having to load their declarations in the browser.

**Comment by GermanBluefox** [comment]
Done
