### ISSUE TITLE
[Bug]: Nach Update auf 8.7.6 fehlen SendTo Blöcke in Blockly mit Aktion

### ISSUE THREAD

**Issue by Subnum12** [ioBroker/ioBroker.javascript#1672]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Nach Update auf 8.7.6 fehlen SendTo Blöcke in Blockly mit Aktion

![grafik](https://github.com/user-attachments/assets/3fffd912-7754-476c-8ed6-8f3b6ffafec7)

ähnliches Problem war schonmal da: https://github.com/ioBroker/ioBroker.javascript/issues/209

Beispiel: Import von https://github.com/joBr99/nspanel-lovelace-ui/wiki/ioBroker-Card-Definitionen-(Seiten)#blockly-f%C3%BCr-influx-20 fehlen alle Inhalte des SendTo Blocks.

### Version of nodejs

v20.16.0

### Version of ioBroker js-controller

6.0.9

### Version of adapter

8.7.6

**Comment by klein0r** [comment]
Was genau fehlt?! Auf den ersten Blick ist doch alles da

**Comment by Subnum12** [comment]
![grafik](https://github.com/user-attachments/assets/5c0c0a65-6d49-42bb-b614-925e8328b525)
na das in dem Link oben verwendete sendto mit Aktionsliste...

**Comment by klein0r** [comment]
Der ist doch ganz oben auf deinem Screenshot

**Comment by Diginix** [comment]
@Subnum12 Du musst "mit Ergebnissen" anhaken damit der Block sich "öffnet"

![image](https://github.com/user-attachments/assets/fcd4406c-9492-4ca8-9c3b-52154cc79843)

**Comment by klein0r** [comment]
@Diginix Das war aber schon immer so (auch in den früheren Versionen). In 8.7.6 gibt es allerdings noch einen Bug, wenn man keine Parameter hat (also den Parameter-Text leer setzt). Ist in 8.8.0 behoben. Siehe #1667

**Comment by Diginix** [comment]
Ja, wollte nur unmissverständlich klar machen was von @Subnum12 ggf. übersehen wurde. Das hat nichts mit der neuen Adapterver. zu tun.

**Comment by Subnum12** [comment]
@klein0r OK, kann bestätigen das Problem bei mir war in der Tat https://github.com/ioBroker/ioBroker.javascript/issues/1667 

> @Subnum12 Du musst "mit Ergebnissen" anhaken damit der Block sich "öffnet"

ja das hatte ich beim nachbauen übersehen und dache der Block fehlt...
