### ISSUE TITLE
Astro - Funktion, Zeit um 2 Stunden falsch

### ISSUE THREAD

**Issue by ThomasTom86** [ioBroker/ioBroker.javascript#1682]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Zeit bei Astro - Baustein 2Std. verschoben.  

![IMG_1985](https://github.com/user-attachments/assets/7239ce09-6259-4c26-9de7-884cdf1464fe)
![IMG_1986](https://github.com/user-attachments/assets/5f17aa3a-f3a6-4f76-bc7b-86d33347a7d7)

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

8.7.6

### Version of adapter

7.0.22

**Comment by klein0r** [comment]
Dich stört, dass die Logmeldungen in UTC sind? Ist doch sonst alles richtig.

> ### Version of adapter
> 7.0.22

Die Version gibt es nicht.

**Comment by Apollon77** [comment]
@ThomasTom86 Server time of the hist where ioBroker runs on is set to the correct timezone?
