### ISSUE TITLE
[Bug]: "Skripte importieren" funktioniert nicht

### ISSUE THREAD

**Issue by cichlied** [ioBroker/ioBroker.javascript#1684]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

Bei der Version 8.7.6 lassen sich keine Skripte importieren, wenn man auf "Skripte importieren" tippt, kommt ein leeres Fenster.
Die Version 8.6.0 scheint die letzte zu sein, bei der es funktioniert.

### Version of nodejs

20.16.0

### Version of ioBroker js-controller

6.0.9

### Version of adapter

8.7.6

**Comment by cichlied** [comment]
Bug wurde schon behandelt

**Comment by klein0r** [comment]
Duplicate of #1651 #1669
