### ISSUE TITLE
[Bug]: variablen im selector block

### ISSUE THREAD

**Issue by backfisch88** [ioBroker/ioBroker.javascript#1688]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Hey 

habe die latest installiert (8.8.2). Seit der Version gehen keine variablen mehr in selector Blocks (Bild 1) wie in Bild zwei geht es. Sie werden (wenn man oben auf blokcly -> js geht escaped als String. 
gibt es dort jetzt eine andere Möglichkeit? Oder ist das ein bug?

![IMG_4713](https://github.com/user-attachments/assets/1592c28c-bd2b-437e-8268-8cc307c61d8d)
![IMG_4714](https://github.com/user-attachments/assets/b74e358c-0b42-44e7-ac9e-fd47a6027ca3)

### Version of nodejs

20.x

### Version of ioBroker js-controller

6.0.11

### Version of adapter

8.8.2

**Comment by klein0r** [comment]
> Seit der Version gehen keine variablen mehr in selector Blocks (Bild 1)

Das sind ja auch einfache Text-Eingabefelder. Dort kann man keinen Code einfügen und den String einfach unterbrechen. Das war nie so gedacht und ein Bug, welcher seit v8.7.0 behoben ist.

Code Injection sollte da nicht möglich sein. Sonst könnte man ja auch `'; const bla =123;` reinschreiben.

Das Problem war, dass einzelne single quotes zu ungültigem Code geführt haben. Dadurch ist das aufgefallen.
War nie ein Feature, sondern vorher ein Bug dass das ging.
