### ISSUE TITLE
[Bug]: several blocky scripts are empty - if I switch to js code view code is viewable

### ISSUE THREAD

**Issue by mac89muc** [ioBroker/ioBroker.javascript#1690]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Several of my Blockly Scripts are Empty if I open them. If I switch to JS-Code View via the button in the right corner I can see that the code is still in the script and the script is working as expected - only changes via blockly are not possible.
scrolling doesn't show the blocky blocks either - nor does changing the browser.

![blockly](https://github.com/user-attachments/assets/309df49e-97b8-4efa-a28f-f32b353323e8)

view after switching to JS-Code View

![jscode](https://github.com/user-attachments/assets/5f906551-bd9d-4022-b0f2-484e5d4f3a10)

when I try to place a blocky block e.g. debug block to the empty blockly view (first picture) and switch to the jscode view all the js code is gone and only the debug block is visible `console.info('test');` 

### iobroker.current.log (in debug mode!)

no infos at the debug log..

### Version of nodejs

18.20.4

### Version of ioBroker js-controller

6.0.9

### Version of adapter

8.7.7

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by MaaG-dA** [comment]
@mac89muc
I found similar behavior with the javascript adapter. Change the system language to English. This helps sometimes.
Second thing - install (for test) an older version of admin.adapter (v.6.17.7). It helped me. I'm waiting for corrections...
(see: https://github.com/ioBroker/ioBroker.javascript/issues/1497)

**Comment by mac89muc** [comment]
Thanks- for the last weeks it's working as expected..

**Comment by MaaG-dA** [comment]
In my opinion, the problem is as results changes made in admin.adapter v7. When I tested the old version admin.adapter -  there were no problems with using another language (german, polish or other).
But using admin.adapter v.6 permanently is also not a good solution currently - because it has other errors. It's easier to switch to the English version... and wait for the improved version of javascript.adapter.
