### ISSUE TITLE
[Bug]: Rules script can't be edited anymore

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.javascript#1691]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Rules

### The problem

If i try to modify a Rules script the script disappears. Tested with Chrome and FF

![DDD11361-2CA8-4A49-987E-AA7B98FCE82F](https://github.com/user-attachments/assets/7dd458ab-49f1-4388-9783-fce2a15a5efc)

Forum: https://forum.iobroker.net/topic/76305/problem-mit-rules-js?_=1724834723699

https://forum.iobroker.net/topic/76315/rules-seit-update-auf-8-7-6-nicht-mehr-editierbar?_=1724834723697

### iobroker.current.log (in debug mode!)

iobroker log doesn't show anything.

This is from browser if i click the Object selector

react-dom.production.min.js:188 TypeError: Cannot read properties of undefined (reading 'palette')
    at Array.cellIdIconFolder (ObjectBrowser.js:260:22)
    at f.getStyle (Utils.js:1580:44)
    at pe.render (ObjectBrowser.js:5489:51)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)

### Version of nodejs

20.16.0

### Version of ioBroker js-controller

6.0.10

### Version of adapter

8.8.2

**Comment by sjfm-design** [comment]
same here. 
want to create a new one, no objects to see, only white screen.
everything at latest.

**Comment by koburg** [comment]
same error here also dark screen. have been this since serval updates now.

**Comment by GermanBluefox** [comment]
Please retest with 8.8.3

**Comment by wendy2702** [comment]
I'm on vacation. Can test next week but updated the forum threads

**Comment by wendy2702** [comment]
Solved!

Thanks!!!
