### ISSUE TITLE
httpGet / httpPut - Errormeldung deaktivieren oder konfigurierbar 

### ISSUE THREAD

**Issue by Blockmove** [ioBroker/ioBroker.javascript#1709]
Bei httpGet und httpPut werden Fehlermeldungen automatisch ins Log geschrieben.
Ich würde mir wünschen, dass dies deaktiviert wird oder konfigurierbar wird.

- Verwendet man die Funktionen in Javascript, dann funktioniert das normale Errorhandling mit try-catch. Die interne Fehlermeldung ist hier eigentlich nicht notwendig. 
- Benutzt man Blockly wäre eine Lösung wie bei der bisherigen request-Funktion aus meiner Sicht vorstellbar.

**Comment by Diginix** [comment]
Duplicate #1599
