### ISSUE TITLE
Use cursor position when pasting a block

### ISSUE THREAD

**Issue by vowill** [ioBroker/ioBroker.javascript#1715]
Thx for continuously improving blockly in ioBroker!

Issue:
When copying a block and pasting it in the same blockly, the insertion is located near the original position. If that pasted block is needed at another location in the same blockly, you have to move it to the edge of the drawing area, then scroll the drawing area, move the pasted block again and so on.

Feature request:
The paste command puts the block exactly where the cursor is positioned.

Result:
The user can copy (or cut) the block, scroll to the relevant area in the same blockly and then paste it there.

**Comment by klein0r** [comment]
Yes, that's a Blockly issue: https://github.com/google/blockly/issues/6848 https://github.com/google/blockly/issues/8099

Has already been fixed in Blockly 11: https://github.com/google/blockly/pull/8123
But we are still using Blockly 10 (and it's not that easy to upgrade).
