### ISSUE TITLE
[Bug]: sendTo Parameter wird gelöscht

### ISSUE THREAD

**Issue by matrose18** [ioBroker/ioBroker.javascript#1721]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Ich möchte mit dem sendTo Block eine query an die mysql-Datenbank senden:
![Bildschirmfoto 2024-09-22 um 10 46 30](https://github.com/user-attachments/assets/be01c0b9-ac14-4d20-ab62-6aec81c2d329)
Mit dieser Syntax wird der Fehler "Error: No query provided" ausgegeben. 

Daher habe ich die Bezeichnung "parameter" gelöscht:
![Bildschirmfoto 2024-09-22 um 10 48 28](https://github.com/user-attachments/assets/6f4d789b-0ba9-4583-b81e-c0cbef790d44)
Damit funktioniert die Abfrage und liefert die gewünschten Ergebnisse. 

Schließe ich das Script nach dem Speichern und öffne es wieder für die Bearbeitung, sind nahezu alle Inhalte des Blocks gelöscht: 
![Bildschirmfoto 2024-09-22 um 10 50 30](https://github.com/user-attachments/assets/29d02550-1b89-4eed-a083-8dc3d3306368)

Der Fehler ist in verschiedenen Browsern reproduzierbar. 
Der Fehler tritt nur auf, wenn die Bezeichnung "Parameter" vollständig gelöscht wird. Wird "Parameter" durch ein Leerzeichen oder einen anderen Begriff ersetzt, tritt der Fehler nicht auf - allerdings lässt sich dann auch keine Query an den Adapter senden.

### Version of nodejs

18.20.4

### Version of ioBroker js-controller

6.0.11

### Version of adapter

8.7.6

**Comment by klein0r** [comment]
> ### Version of adapter
> 8.7.6

https://github.com/ioBroker/ioBroker.javascript/blob/840d03855636c4271971afc202532d008c22d264/README.md?plain=1#L35-L37
