### ISSUE TITLE
Reconnection to DB

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.javascript#174]
Hello,

i have in more or less regular time steps (between 3-6 Mins) a reconnecction to my DB (sql.0 on a NAS)
What can i do / change / check ?

The Log file says:
`

javascript.0 | 2018-08-12 12:22:19.732 | warn | Reconnection to DB.
-- | -- | -- | --
javascript.0 | 2018-08-12 12:22:19.714 | warn | Reconnection to DB.

`

Sometimes i get also:
`

host.RaPi03-Prod | 2018-08-12 12:29:25.588 | info | instance system.adapter.javascript.0 started with pid 25849
-- | -- | -- | --
host.RaPi03-Prod | 2018-08-12 12:28:55.512 | info | Restart adapter system.adapter.javascript.0 because enabled
host.RaPi03-Prod | 2018-08-12 12:28:55.506 | error | instance system.adapter.javascript.0 terminated with code 7 (Adapter already running)

`

**Comment by GermanBluefox** [comment]
Reconnections are mostly because of cpu load

вс, 12 авг. 2018 г., 12:31 Seqway <notifications@github.com>:

**Comment by Apollon77** [comment]
Check your scripts!! This happens when one script is using full resources/cpu for >20s ...

**Comment by smartboart** [comment]
Hallo habe das Selbe Problem mit der Javascript Instanz auf meinem Slave Host... Dort laufen nur noch 2 Scripte, welche nur aktiv werden wenn ich sie per Tastendruck in der Vis auslöse...Alle anderen habe ich schon runter geschmissen ..Dennoch reconnect to DB.
Der Master läuft stabil und CPU des Slave ist immer auf 600Mhz .Das Problem habe ich nur mit der Java Instanz auf dem Slave. Habe uach schon alle Adapter deaktiviert oder runter geschmissen.. Ich würde gerne auf die 2. Instanz verzichten, dann hätte ich das Problem nicht. Dazu müsste aber sendToHost funktionieren...

**Comment by Apollon77** [comment]
Wie schon im Forum Thread gesagt: "Reconnection to DB" bedeutet das der JavaScript Prozes von einem der Skripte für mehr als 20 Sekunden blockiert war ODER der Master die verbindung gekillt hat.

Ersteres wäre ein Skript Schuld. zweiteres wäre es der Master oder Netzwerk, müsste dann aber mehr Adapter betreffen.

**Comment by smartboart** [comment]
Ja es ließ sich aber nichts dergleichen feststellen... Letztendlich hat eine Image Neuinstallation mit backup restore geholfen... Weil das ja reibungslos auch im multihost Verbund funktioniert haette ich das schon eher tun sollen...
