### ISSUE TITLE
[Bug]: Blockly Aussprechen mit Sayit funktioniert nicht richtig

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.javascript#1757]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

der "aussprechen" mit Sayit Block funktioniert nicht richtig. Ich habe dieses einfache Blockly:

![grafik](https://github.com/user-attachments/assets/ead1e7ff-0c76-498e-b4e5-b7b324cda626)

Dazu aktuell zwei Sayit Instanzen installiert, Wenn ich im Blockly auswähle das die Instanz sayit.0 verwendet werden soll erfolgt keine Ansage und es erscheint scheinbar kein Aufruf von Sayit:

Im log erscheint bei trigger nur das:

```
2024-11-02 11:17:42.926  - info: javascript.0 (40896) script.js.common.Ansagen.Voice_Feedback_Garagentor_Rechts: Garagentor rechts zu
```

Wähle ich "alle Instanzen" erhalte ich eine Ansage über sayit.2 und das im Log, gleiches wenn ich sayit.2 auswähle:

```
2024-11-02 11:19:28.278  - info: javascript.0 (40896) script.js.common.Ansagen.Voice_Feedback_Garagentor_Rechts: Garagentor rechts auf
2024-11-02 11:19:28.382  - info: sayit.2 (43069) saying: Garagentor rechts auf
```

Instanz Einstellungen Sayit.0

![grafik](https://github.com/user-attachments/assets/f408c864-d432-4293-a7ce-38690bcf00a1)
![grafik](https://github.com/user-attachments/assets/e77ebc31-362b-4bd5-9039-6f355f75d9e8)

sayit.2

![grafik](https://github.com/user-attachments/assets/ae6d52fb-5a33-434b-b3bc-faaf4e7f96e6)
![grafik](https://github.com/user-attachments/assets/802c8192-1dfd-4679-bc33-4f4c67671aaa)

Ansagen über sayit.0 funktionieren über andere Scripte und Polly.

### Version of nodejs

20.18.0

### Version of ioBroker js-controller

7.0.2

### Version of adapter

8.8.3

**Comment by klein0r** [comment]
Issue is related to adapter https://github.com/ioBroker/ioBroker.sayit

**Comment by wendy2702** [comment]
Kannst du mir kurz erklären wieso das ein Sayit Problem ist wenn doch scheinbar bei Auswahl von Sayit.0 die Sayit Instanz gar nicht angesprochen wird?

**Comment by klein0r** [comment]
Weil sowohl die Blockly-Bausteine, als auch der damit generierte Code komplett vom SayIt-Adapter kommen.

**Comment by wendy2702** [comment]
OK. Dann mache ich mal dort ein Issue auf.

Danke
