### ISSUE TITLE
[Bug]: Nach Update auf 7.0.3 Zusätzliche npm Module werden nicht installiert

### ISSUE THREAD

**Issue by Erwin40** [ioBroker/ioBroker.javascript#1774]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

Fehlermeldungen beim Adapter Start: 
Cannot install custom npm package "ping@latest"
Cannot install custom npm package "onoff@latest"
Cannot install custom npm package "systeminformation@latest"

Meine Konfiguration:
![391487489-841b9262-5e35-4e78-9094-ff49013d99a8](https://github.com/user-attachments/assets/fbed1d62-9045-4cb2-b62b-b2d2d41c052d)

### iobroker.current.log (in debug mode!)

`<html><body>

javascript.0 | 2024-12-02 11:38:19.329 | info | requesting all objects
-- | -- | -- | --
javascript.0 | 2024-12-02 11:38:19.327 | info | requesting all states
javascript.0 | 2024-12-02 11:38:18.354 | debug | Loaded TypeScript definitions for audio: ["node_modules/@types/audio/index.d.ts"]
javascript.0 | 2024-12-02 11:38:18.351 | debug | Loaded  TypeScript definitions for onoff:  ["node_modules/onoff/package.json","node_modules/@iobroker-javascript.0/onoff/onoff.d.ts"]
javascript.0 | 2024-12-02 11:38:18.349 | debug | Loaded  TypeScript definitions for systeminformation:  ["node_modules/systeminformation/package.json","node_modules/@iobroker-javascript.0/systeminformation/lib/index.d.ts"]
javascript.0 | 2024-12-02 11:38:18.346 | debug | Loaded TypeScript definitions for request: ["node_modules/@types/request/package.json","node_modules/@types/request/index.d.ts"]
javascript.0 | 2024-12-02 11:38:18.323 | debug | Loaded  TypeScript definitions for node:  ["node_modules/@types/node/package.json","node_modules/@types/node/index.d.ts","node_modules/@types/node/globals.typedarray.d.ts","node_modules/@types/node/buffer.buffer.d.ts","node_modules/@types/node/assert.d.ts","node_modules/@types/node/assert/strict.d.ts","node_modules/@types/node/globals.d.ts","node_modules/@types/node/async_hooks.d.ts","node_modules/@types/node/buffer.d.ts","node_modules/@types/node/child_process.d.ts","node_modules/@types/node/cluster.d.ts","node_modules/@types/node/console.d.ts","node_modules/@types/node/constants.d.ts","node_modules/@types/node/crypto.d.ts","node_modules/@types/node/dgram.d.ts","node_modules/@types/node/diagnostics_channel.d.ts","node_modules/@types/node/dns.d.ts","node_modules/@types/node/dns/promises.d.ts","node_modules/@types/node/domain.d.ts","node_modules/@types/node/dom-events.d.ts","node_modules/@types/node/events.d.ts","node_modules/@types/node/fs.d.ts","node_modules/@types/node/fs/promises.d.ts","node_modules/@types/node/http.d.ts","node_modules/@types/node/http2.d.ts","node_modules/@types/node/https.d.ts","node_modules/@types/node/inspector.d.ts","node_modules/@types/node/module.d.ts","node_modules/@types/node/net.d.ts","node_modules/@types/node/os.d.ts","node_modules/@types/node/path.d.ts","node_modules/@types/node/perf_hooks.d.ts","node_modules/@types/node/process.d.ts","node_modules/@types/node/punycode.d.ts","node_modules/@types/node/querystring.d.ts","node_modules/@types/node/readline.d.ts","node_modules/@types/node/readline/promises.d.ts","node_modules/@types/node/repl.d.ts","node_modules/@types/node/sea.d.ts","node_modules/@types/node/sqlite.d.ts","node_modules/@types/node/stream.d.ts","node_modules/@types/node/stream/promises.d.ts","node_modules/@types/node/stream/consumers.d.ts","node_modules/@types/node/stream/web.d.ts","node_modules/@types/node/string_decoder.d.ts","node_modules/@types/node/test.d.ts","node_modules/@types/node/timers.d.ts","node_modules/@types/node/timers/promises.d.ts","node_modules/@types/node/tls.d.ts","node_modules/@types/node/trace_events.d.ts","node_modules/@types/node/tty.d.ts","node_modules/@types/node/url.d.ts","node_modules/@types/node/util.d.ts","node_modules/@types/node/v8.d.ts","node_modules/@types/node/vm.d.ts","node_modules/@types/node/wasi.d.ts","node_modules/@types/node/worker_threads.d.ts","node_modules/@types/node/zlib.d.ts","node_modules/@types/node/globals.global.d.ts"]
javascript.0 | 2024-12-02 11:38:18.289 | info | Removed custom npm package: "ping"
javascript.0 | 2024-12-02 11:38:17.078 | warn | Cannot install custom npm package "audio@latest"
javascript.0 | 2024-12-02 11:38:15.844 | debug | Found custom library in config: "audio@latest"
javascript.0 | 2024-12-02 11:38:15.844 | warn | Cannot install custom npm package "onoff@latest"
javascript.0 | 2024-12-02 11:38:14.612 | debug | Found custom library in config: "onoff@latest"
javascript.0 | 2024-12-02 11:38:14.611 | warn | Cannot install custom npm package "systeminformation@latest"
javascript.0 | 2024-12-02 11:38:13.329 | debug | Found custom library in config: "systeminformation@latest"
javascript.0 | 2024-12-02 11:38:13.328 | debug | Found installed libraries: ["audio","onoff","ping","systeminformation"]
javascript.0 | 2024-12-02 11:38:13.297 | debug | Custom libraries in config: "systeminformation,  onoff  audio": ["systeminformation","onoff","audio"]
javascript.0 | 2024-12-02 11:38:13.287 | debug | config.subscribe (Do not subscribe all states on start): false
javascript.0 | 2024-12-02 11:38:13.256 | info | starting. Version 8.8.3 in /opt/iobroker/node_modules/iobroker.javascript, node: v20.18.1, js-controller: 7.0.3
javascript.0 | 2024-12-02 11:38:13.050 | debug | Plugin sentry Do not initialize Plugin (enabled=false)
host.RaspberryPi4-Ede | 2024-12-02 11:38:10.081 | info | instance system.adapter.javascript.0 in version "8.8.3" started with pid 11437
host.RaspberryPi4-Ede | 2024-12-02 11:38:06.400 | info | instance system.adapter.javascript.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

</body>
</html>`

### Version of nodejs

20.18.1

### Version of ioBroker js-controller

7.0.3

### Version of adapter

8.8.3

**Comment by mcm1957** [comment]
Da die Fehler erst nach dem Update auf js-controller 7.0.3 beobachtet wurden wäre es interessant welche js-controller Version vor dem Upgrade installiert war. 6.x.x oder noch 5.x.x ?

**Comment by Erwin40** [comment]
Ich glaube es war der 6x 
Was war denn die offizelle Vorgängerversion? (Ich bin eigentlich immer Up2Date)
Ich arbeite übrigens per SSH Login, immer mit dem User `pi`

Habe jetzt die Einträge rausgeschmissen und mal nach onoff gesucht und versucht das zu deinstallieren.
Ergebnis von `sudo find / -iname "onoff"`
`/opt/iobroker/node_modules/@iobroker-javascript.0/onoff`
Wechsel ins Verzeichnis: `cd /opt/iobroker/node_modules/`
Versucht zu deinstallieren: `npm uninstall onoff`
Ausgabe im Log: 
`npm error code EOVERRIDE
npm error Override for @iobroker/adapter-core@^3.1.6 conflicts with direct dependency
npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-02T11_49_26_007Z-debug-0.log`
Mit dem `adapter-core` bin ich etwas auf Kriegsfuss, da der irgendwann mal gefehlt hatte und manuell nachinstalliert wurde.

**Comment by mcm1957** [comment]
> Ich glaube es war der 6x 

Danke. 

> Habe jetzt die Einträge rausgeschmissen und mal nach onoff gesucht und versucht das zu deinstallieren. 

>  `npm uninstall onoff` Ausgabe im Log: `npm error code EOVERRIDE npm error Override for @iobroker/adapter-core@^3.1.6 conflicts with direct dependency npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-02T11_49_26_007Z-debug-0.log` Mit dem `adapter-core` bin ich etwas auf Kriegsfuss, da der irgendwann mal gefehlt hatte und manuell nachinstalliert wurde.

NIE NIE NIE Irgendwas am ioBroker system manuell mittels npm installieren / deinstallieren.

Wart mal ab was von einem Maintainer zum Problem hier geantwortet wird oder mach ein Topic im Forum ("https://forum.iobroker.net") auf. Du bist sicher nicht der Einzige der eigene Packages verwendet.

**Comment by Erwin40** [comment]
Naja, wenn ich aber so Sachen wie `ping` `systeminformation` oder `onoff` innerhalb der ioBroker Scripte brauche?
Was wäre denn korrekt gewesen?

**Comment by Erwin40** [comment]
Und den uninstall habe ich nur versucht weil die Dinger immer noch drin sind, obwohl ich sie aus der Konfig genommen habe und auch mit Reboot.
Werd sie jetzt einfach nicht mehr los ;-)

**Comment by Erwin40** [comment]
Ich habe mittlerweile ein neues System auf einem Pi5 aufgesetzte und alles neu (und möglichst ohne Sudo) installiert.
Hier musste und konnte ich ohne Fehler im Log, obige Module in der Konfig angeben und alles funktioniert wie erhofft.
Da die Ursache nur schwer nachzuvollziehen ist, schließe ich erst mal :-)
