### ISSUE TITLE
Reference Error: monaco is not defined

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#178]
See #168

**Comment by AlCalzone** [comment]
@GermanBluefox How do you reproduce the error? I installed iobroker.javascript from github, did an upload and the script tab is working for me, except for #175 
Admin 3.5.8
Javascript github/master
JS-Controller 1.4.2

**Comment by GermanBluefox** [comment]
@AlCalzone https://github.com/ioBroker/ioBroker.javascript/commit/5605be825c6b346e4447bcc075ef4f4232263895

**Comment by AlCalzone** [comment]
Hmm, then for some reason the loader does not pick up the changed path on your system while it does on mine.

**Comment by GermanBluefox** [comment]
REDIS interpret the the path as a string.
For File system "folder/file.txt" and "folder//file.txt" is possibly the same.

I store all Objects and Files experimentally in REDIS.
