### ISSUE TITLE
Need help. Deleted script is still active

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.javascript#179]
I had a blockly script that writes a state every minute for testing purpose. I deleted it, it disappeared out of the script windows (no where to be seen) but it still writes the state... 
Where are the scripts saved? Can I just delete the file when I find it?

**Comment by Xyolyp** [comment]
I've searched through the objects.json file and I can't find the script in there. Do they get compiled to some place where I can delete that?

**Comment by AlCalzone** [comment]
They are stored as an object. If it’s not in there it does not exist anymore. However the process might still be running. Have you tried stopping the adapter and then killing the corresponding process if it’s still running? Or restarting the entire machine?

**Comment by Xyolyp** [comment]
I restaret my docker container once before asking this question. Rebooting the entiry server fixed the issue. Thank you.
