### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.javascript#18]
Hallo,

ich würde gerne Objekte anhand des Namens filtern - aber es klappt nicht. Versucht habe ich es z.B. wie folgt:
var fensterZustand= $('channel[name=*Fenster*, state.id=*.State]'); (da sind Sternchen vor/hinter "Fenster", die man leider nicht sieht)

Ich habe mehrere andere Möglichkeiten ausprobiert; hat aber alles nicht geklappt. Siehe auch Forum: http://forum.iobroker.net/viewtopic.php?p=56724#p56724

**Comment by Apollon77** [comment]
Wenn es im Forum ist dann mache ich das hier mal zu, weil ist ja ne Frage und kein Issue

**Comment by Goersch** [comment]
ok 😀 ich hoffe, mir kann jemand helfen ...

**Comment by Apollon77** [comment]
kriegen wir schon hin :-)
