### ISSUE TITLE
Cannot extract Blockly code!

### ISSUE THREAD

**Issue by xXHamtaroXx** [ioBroker/ioBroker.javascript#180]
Bekomme immer wieder diese Meldung...was hat es damit aufsich?
Habe die neuste Javascript Adapter Version installiert...

Kann mir Jemand helfen?
Ist diese Meldung irgendwie "schlimm"?

Mit freundlichem Gruß

Hamtaro

**Comment by xXHamtaroXx** [comment]
Hallo, hat sich erledigt.
Hab den Adapter neu Hochgeladen..bis jetzt kam keine meldung mehr

**Comment by BuZZy1337** [comment]
Danke für die Rückmeldung.
Falls das Problem doch nochmal auftauchen sollte einfach hier nochmal melden. :relaxed:
