### ISSUE TITLE
Add switch/case block

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.javascript#182]
I would like to see a switch case block. Googleing around a bit I found this link where someone posted code for a switch case and said it would work. https://groups.google.com/forum/#!topic/blockly/djhO2jUb0Xs

**Comment by DutchmanNL** [comment]
Interesting suggestion, +1
Handling outputs based on cases is more simple and better visualised than nesting if, else if etc

**Comment by GermanBluefox** [comment]
We need a predefined license from this buddy.

пн, 17 сент. 2018 г., 20:39 Xyolyp <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Request running. If no answer in 2 month I will close issue

**Comment by Xyolyp** [comment]
I'd still appreciate a switch/case block but I can't find a working one
with the required license information provided. If this won't be
implemented please add the according tag and close the request.

Bluefox <notifications@github.com> schrieb am Di., 26. Feb. 2019, 22:37:

**Comment by GermanBluefox** [comment]
If some one wants to write it, you are welcome. For now I will not take a code into ioBroker without license.
