### ISSUE TITLE
Odd behaviour of getAstroDate()

### ISSUE THREAD

**Issue by Gieskanne** [ioBroker/ioBroker.javascript#186]
Between 00:00 and 01:00 every day the following statement is true, which shouldn't be:
`compareTime(getAstroDate("sunsetStart", undefined, -179), '21:00', "between", null)`

I have two ideas in my mind what could go wrong:
a) The astro package is not using summertime, so it's still the day before.
b) The offset is taken into account to find the current date in getAstroDate().

I am using the Script Engine version 3.6.4.

**Comment by GermanBluefox** [comment]
Should be fixed
