### ISSUE TITLE
Filter Name of Scripts

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.javascript#187]
Name filter in tab "Scripts" does not work with more than one character.
Tab "Objects" works perfect.
![bildschirmfoto 2018-09-30 um 10 16 10](https://user-images.githubusercontent.com/8090989/46255158-ea047080-c499-11e8-8694-be176a366c82.jpg)

**Comment by AlCalzone** [comment]
Fixed in 4.0.1?

**Comment by RK62** [comment]
In version V3.6.4 the search is always performed with lowercase letters.
So "Ad" will find "Re**ad**er" but not "**Ad**apter"

**Comment by foxriver76** [comment]
with 4.1 it works flawlessly
