### ISSUE TITLE
Blockly: error handling on URL request which gives no answer 

### ISSUE THREAD

**Issue by mtk64** [ioBroker/ioBroker.javascript#189]
Hi
my Blockly script is requesting a simple URL to get some state of my motioneye server.
Sometimes it is causing errors which will restart the JS engine:

host.aio	2018-09-30 14:58:18.289	error	instance system.adapter.javascript.0 terminated with code 0 (OK)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Socket.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Socket.socketErrorListener (_http_client.js:314:9)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at ClientRequest.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request.onRequestError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:877:8)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:101:20)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request._callback (script.js.MTK.MotionServices:129:19)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: TypeError: Cannot read property 'length' of undefined
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at Socket.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at Socket.socketErrorListener (_http_client.js:314:9)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at ClientRequest.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request.onRequestError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:877:8)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at emitOne (events.js:101:20)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request._callback (script.js.MTK.MotionServices:96:21)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: TypeError: Cannot read property 'length' of undefined

Debug from my script:

Log
15:01:18.259	[error]	Caught by controller[0]: at Request._callback (script.js.MTK.MotionServices:96:21)
15:01:18.260	[error]	Caught by controller[1]: at Request._callback (script.js.MTK.MotionServices:129:19)
[/quote]

Showing the lines of code within blockly is showing this code:

try {
require("request")((String('http://pn2.fritz.box:7999') + String('/1/detection/status')), function (error, response, result) {
if (!!result.length) {
setState("javascript.0.Services.MotionServer.detectionState.3"/detectionState.3/, (result.slice(((result.indexOf('Detection status') + 1) - 1), result.length - 17)), true);
}
}).on("error", function (e) {console.error(e);});
} catch (e) { console.error(e); }

I was expecting some handling when a server is not responding. Any Idea where the problem resides?
Maybe problems in try/catch in Blockly or JS engine?

**Comment by mtk64** [comment]
maybe this can help to improve the adapter, check if there is any resulting answer from request:

if(error) log('Fehlertext', 'warn');
else if (result && !!result.length) {

**Comment by DutchmanNL** [comment]
As i see the error handling is already in the blockly as your code output provides an try/catch function.

Question remains why this fails

**Comment by mtk64** [comment]
But not the part in bold which will check existance of result, means will catch null pointer ... ??? 
if (**result &&** !!result.length) {
Got this hint from here:  
[https://forum.iobroker.net/viewtopic.php?f=21&t=17307&p=181445#p181445](url)

**Comment by GermanBluefox** [comment]
How you check the result.length ?? Can you show blockly?

**Comment by mtk64** [comment]
it's german but you should get it from the grafical representation

![grafik](https://user-images.githubusercontent.com/8484647/46919954-7ad56300-cfe7-11e8-8e30-0210b8ca3bd6.png)

**Comment by GermanBluefox** [comment]
You should check yourself if result != null

**Comment by mtk64** [comment]
THX, meanwhile I learned how to do that in Blockly itself, in simple javascript it was very easy ...
So now I will know how to do manage usual error handling. Even in Blockly ;-)

![grafik](https://user-images.githubusercontent.com/8484647/51334304-d77d6980-1a7f-11e9-9311-9e2a3b26aed0.png)
