### ISSUE TITLE
CRASH of ioBroker if using WHILE function

### ISSUE THREAD

**Issue by Evil-Error** [ioBroker/ioBroker.javascript#190]
Always when I try to use a WHILE function -  it doesn't matter with which dependencies or "to do's", the whole system crashes and ioBroker (all instances) is/are restarting. 

I tried with just a really simple test code - the same issue (I also tried with a timeout inside the WHILE function):

`var timeout, timeout2;
on({id: "javascript.0.Hilfsobjekte.Testtrigger1"/*Testtrigger1*/, change: "gt"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  console.warn('Start TEST');
  timeout = setTimeout(function () {
    console.warn('A Nach 2 Sekunden');
    timeout2 = setTimeout(function () {
      console.warn('B Nach 5 Sekunden nach A - Start Schleife');
      while (!(getState("javascript.0.Hilfsobjekte.Testtrigger2").val == true)) {
        console.warn('checking');
      }
      console.warn('Schleife BEENDET');
      setStateDelayed("javascript.0.Hilfsobjekte.Testtrigger1"/*Testtrigger1*/, false, 2000, false);
    }, 5000);
  }, 2000);
});`

Here a cut of the log some seconds before the crash:

_2018-10-03 13:37:33.776 - warn: javascript.0 script.js.Templates.WHILE_EXAMPLE: Start TEST
2018-10-03 13:37:33.776 - info: javascript.0 script.js.Templates.WHILE_EXAMPLE: setTimeout(ms=2000)
2018-10-03 13:37:35.798 - warn: javascript.0 script.js.Templates.WHILE_EXAMPLE: A Nach 2 Sekunden
2018-10-03 13:37:35.798 - info: javascript.0 script.js.Templates.WHILE_EXAMPLE: setTimeout(ms=5000)
**2018-10-03 13:37:40.796 - warn: javascript.0 script.js.Templates.WHILE_EXAMPLE: B Nach 5 Sekunden nach A - Start Schleife**
2018-10-03 13:38:37.789 - info: sonoff.0 Client [DVES_717989] reconnected. Old secret *. New secret 15X8566716784_XXX
2018-10-03 13:38:37.986 - info: sonoff.0 Client [DVES_2DE6FF] reconnected. Old secret *. New secret 153X566716823_XXX
2018-10-03 13:38:37.991 - info: sonoff.0 Client [DVES_71D49A] reconnected. Old secret *. New secret 153X566716933_XXX
2018-10-03 13:38:38.056 - info: sonoff.0 Client [DVES_71D49A] connection closed: closed
2018-10-03 13:38:38.098 - info: sonoff.0 Client [DVES_2DE6FF] connection closed: closed
2018-10-03 13:38:38.119 - info: sonoff.0 Client [DVES_717989] connection closed: closed
2018-10-03 13:38:45.385 - error: cloud.0 Ping timeout_

**Comment by Apollon77** [comment]
Was genau crasht da? Das log zeigt keinen Crash ... oder ich zu blind.

**Comment by Apollon77** [comment]
Aber unabhängig davon sind while schleifen in JavaScript böse weil sie blocken. Nodejs ist single threaded ... eine while Schleife lässt keine Zeit um Updates von werten zu bekommen. Das musst du anders machen.

**Comment by Apollon77** [comment]
Wenn du wissen willst wann sich der Wert ändert mache eine neue „on“ Methode dafür und dann wenn du es nicht mehr brauchst nutze „unsubscribe“. Mehr support dazu bitte per Forum.

**Comment by Evil-Error** [comment]
Danke für die schnelle Rückmeldung. 
Richtig erkannt - im Log steht nichts weil sich der komplette "Server" verabschiedet. 
Den Neustart aller Instanzen inkl. Nicht-Erreichbarkeit der Oberfläche könnte ich dir im späteren Verlauf des Logs jedoch Problemlos zeigen ;) 

Das WHILE-Schleifen bei js "böse" sind ist mir zwar neu...bei anderen Scripten außerhalb io hatte ich solche Probleme noch nicht! Dass es die Funktion ins besondere in Blockly gibt ist dann aber in jedem Fall "ungünstig" wenn sie zu abstürzen führt.

Aber ich werde mir dann einen Workaround suchen, das Problem zu umschiffen. 
Danke

**Comment by AlCalzone** [comment]
Du erstellst in deiner Schleife im millisekundentakt neue Timeouts, die aufgrund ihrer schieren Anzahl den Host in die Knie zwingen. Wenn die dann ausgeführt werden läuft der callback ebenfalls millionenfach ab. Das wird in jeder Programmiersprache und jedem System problematisch, wenn du ähnliche Dinge treibst.

**Comment by Apollon77** [comment]
Ok dann sage ich es so:

Deine Art while loop ist böse ;-)

in deinem Fall hast du eine Endlosschleife gebaut. Die Schleife in de du wartest das sich der eine wert ändert blockiert die sog. Event Loop und selbst wenn sich der Wert ändert hat der Prozess keine Zeit um den neuen Wert zu bekommen. Damit bekommt deine Schleife nie die Werteänderung mit und läuft und läuft. 

Das blockt auch alle anderen Skripte. 

Nodejs ist single threaded!!! Es gibt keine parallel laufende Logik. Das ist wichtig!

**Comment by Evil-Error** [comment]
Hi Jungs 
danke für die Rückmeldungen. 
vorweg: Falls meine letzte Antwort etwas trotzig klang - **sorry**, war nicht beabsichtigt. 
Ich war wahrscheinlich nur ein weeenig gefrustet. Das mit dem Timeout sehe ich ein.
Ich war zugegebener Maßen der Meinung damit die Schleife auszubremsen um ein "Überlaufen" zu verhindern. 

Was ich allerdings nach wie vor nicht begreife ist, dass ich selbst mit einer "leeren" Schleife die nur einen Wert abfragt und mit der Bedingung vergleicht gegen die Wand fahre. 
Sprich: Loop solange bis der Wert erreicht ist. 


`on({id: "javascript.0.Hilfsobjekte.Testtrigger1"/*Testtrigger1*/, change: "any"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  console.warn('START');
  console.warn('check');
  sleep(5000);
  console.warn('Sleeptest 5 Sekunden');
  while (getState("javascript.0.Hilfsobjekte.Testtrigger2").val === false) {
     //console.warn('check');
    //sleep(1000);
  }
  console.warn('ENDE');
});`

Stimmt die Bedingung des Testwertes, läuft das Script durch - auch die Sleep-Funktion funktioniert so wie sie soll.

javascript.0	2018-10-04 09:59:17.056	warn	script.js.Templates.Skript3: ENDE
javascript.0	2018-10-04 09:59:17.056	warn	script.js.Templates.Skript3: Sleeptest 5 Sekunden
javascript.0	2018-10-04 09:59:12.651	warn	script.js.Templates.Skript3: check
javascript.0	2018-10-04 09:59:12.651	warn	script.js.Templates.Skript3: START


Stimmt die Bedingung jedoch NICHT kommt io nicht weiter als "START". 

javascript.0	2018-10-04 09:59:59.846	warn	script.js.Templates.Skript3: START

Ab dem Moment bleibt mir nur auf Linuxebene per Kill den Prozess komplett abzuschießen. 
Auch wenn ich den Testtrigger auf den Zielwert setze - keine Veränderung. 

Auch unter Verwendung einer Variablen für den Datenpunkt das gleiche Spiel:

`  while (temp === true) {
    console.warn('check');
    if (getState("javascript.0.Hilfsobjekte.Testtrigger2").val === false) {
      temp = true;
    } else {
      temp = false;
    }}`


**Mir ist es so stand jetzt unmöglich in einem Ablauf auf einen Wert zu warten - oder?**

Die Auslagerung funktioniert, auf jeden Fall demnach was ich mit meinem Wissen jetzt Umsätzen würde, nicht weil das Script i.d.R. nur einmal Laufen soll und in Abhängigkeit von bestimmten Werten wartet oder weiter läuft. Ich müsste somit mindesten 3 Scripte anstelle von einem nutzen um das Gleiche zu erreichen.

**Comment by AlCalzone** [comment]
Wie Apollon geschrieben hat, nein. Du blockiert den Event Loop. Stattdessen nimm ein interval mit niedriger Wartezeit (30-100 ms) und prüfe darin. Sauberer wäre allerdings direkt auf die Änderung des Wertes zu triggern. 
Fast alle Logiken bei der auf einen Wert gewartet werden, können ohne schleifen oder Intervalle abgebildet werden. 
Frag wie gesagt am besten mal im Forum da finden sich schnell Leute die dir helfen können das Skript auf den richtigen Weg zu bringen.

**Comment by AlCalzone** [comment]
In deinem letzten Fall, drehe die Abfrage um. Triggere auf Änderung der Variablen und prüfe innerhalb des triggers ob die Variable true ist.
