### ISSUE TITLE
Colors in Blockly for Logic are different

### ISSUE THREAD

**Issue by Schurik23** [ioBroker/ioBroker.javascript#193]
Die Farben für Menu und die Logik Blöcke selbst sind unterschiedlich.

**Comment by GermanBluefox** [comment]
Done in 4.0. Please verify
![image](https://user-images.githubusercontent.com/4582016/49223281-9ef5d380-f3de-11e8-85dc-715a11291f4e.png)

**Comment by Schurik23** [comment]
Works fine in 4.0.1. Thank you
