### ISSUE TITLE
Bug in Blockly "Text"

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.javascript#194]
![clipboard 1](https://user-images.githubusercontent.com/429883/48070725-d7880000-e1d8-11e8-9883-aafd46b00374.jpg)

Bei Bild 3 wird kein Wert angezeigt / gespeichert.
Egal was man eingibt.
Bei Bild 1 und 2 funktionieren die Werte

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren:
![image](https://user-images.githubusercontent.com/4582016/49027724-1f2ef580-f1a1-11e8-9735-0fb48c8f39e3.png)

**Comment by DutchmanNL** [comment]
Ich benutze diese Blöcke auch und kan ebenso nicht reproduzieren oder verstehe den Fehler falsch?

**Comment by elzershark** [comment]
Code:
`<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="variables_set" id="_QYPus7N-VJHoNDNsXh)" x="-487" y="113">
    <field name="VAR">value</field>
    <value name="VALUE">
      <block type="text" id="@f0Y{q=[D@hL98xU:My}">
        <field name="TEXT">1234567890</field>
      </block>
    </value>
    <next>
      <block type="control" id="jT+tB*U(.zQcsm+*GLFd">
        <mutation delay_input="false"></mutation>
        <field name="OID">Meine_Geräte.0.Test</field>
        <field name="WITH_DELAY">FALSE</field>
        <value name="VALUE">
          <block type="text_getSubstring" id="C{d}Ta+PLVmHp)Z[|#pq">
            <mutation at1="true" at2="true"></mutation>
            <field name="WHERE1">FROM_START</field>
            <field name="WHERE2">FROM_START</field>
            <value name="STRING">
              <block type="variables_get" id="k!f=q.DH#[#*aMkk=Bdd">
                <field name="VAR">value</field>
              </block>
            </value>
            <value name="AT1">
              <block type="math_number" id="%ufxc.i70sI]MxxpB*qk">
                <field name="NUM">0</field>
              </block>
            </value>
            <value name="AT2">
              <block type="math_number" id="m,Olm^,zI-ml^2Ikj!K5">
                <field name="NUM">5</field>
              </block>
            </value>
          </block>
        </value>
      </block>
    </next>
  </block>
</xml>`

Test = Zahl oder Gemischt stellen bei "type"

Was wird bei euch angezeigt unter Objekte (Test).. bei mir steht nichts drin

**Comment by AlCalzone** [comment]
Was bekommst du raus wenn du "ab hinten [0] bis [1]" einträgst? => Sollte "0" sein.
Was bekommst du raus, wenn du "ab hinten [0] bis [5]" einträgst? => Sollte "67890" sein.

**Comment by elzershark** [comment]
Sollte??? Bekommst Du das raus oder ist das jetzt eine Vermutung? Hast Du das so getestet?

**Comment by AlCalzone** [comment]
Anhand der JS-Funktion die dahinter steckt, **sollte** das rauskommen. Wenn nicht, ist es möglicherweise ein Bug. Habe hier kein Blockly zum testen, deswegen frage ich.

**Comment by elzershark** [comment]
Musst Du Testen. Bei mir würde nichts passieren. Keinerlei Ausgaben

**Comment by GermanBluefox** [comment]
Blockly **zählt von 1** und nicht von 0!
Dann stimmt alles.

**Comment by elzershark** [comment]
Dann bin ich der einzige wo das nicht geht. Und bei meinen 3 anderen neu aufgespielten raspy's

**Comment by GermanBluefox** [comment]
> Dann bin ich der einzige wo das nicht geht. Und bei meinen 3 anderen neu aufgespielten raspy's

Was nicht geht?

**Comment by elzershark** [comment]
Sec. 10 min. Ich mach ein Film. Der "nim Teil ab von hinten" ist verbugt. Nicht nutzbar

**Comment by AlCalzone** [comment]
Nur so am Rande: Nutze nächstes Mal eine Log-Ausgabe, dann musst du nicht immer zwischen den Ansichten hin und her springen.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/49089231-5eba1800-f25b-11e8-8fe4-9efed52773b4.png)
Das ist falsche Denkweise.  Fange von Hinten und gehe bis fünfte element **nach vorne.** Wenn du von hinten nach vorne gehst, da gibt es nichts.

**Comment by AlCalzone** [comment]
@GermanBluefox Das Blockly in deinem Beispiel ist im Video auch drin, Ausgabe ist `""`

**Comment by elzershark** [comment]
Testet es doch einfach. Oben hab ich extra ein code dafür. Einfach kopieren und im blockly einfügen. Dann hier schreiben ob das anders bei euch ist. Ganz einfach zu machen.

**Comment by elzershark** [comment]
https://www.youtube.com/watch?v=2mgbpW8iwVc

**Comment by elzershark** [comment]
slice muss negative Zahl sein.  Das Script schreibt die Zahl in positiv. Setzt negativ davor und es geht.
xxx.slice(-5).charAt(0); 5 ist die Eingabe wie von Bluefox. slice muss die 5 in negativ wandeln.

**Comment by elzershark** [comment]
> Blockly **zählt von 1** und nicht von 0!
> Dann stimmt alles.

nope. Falsch.

**Comment by elzershark** [comment]
Blockly Zählt von Anzahl der Wörter/Zahlen zu Zahl.
Dann stimmt alles.

**Comment by AlCalzone** [comment]
Du musst in beiden Dropdowns "von hinten" auswählen, dann wird auch von hinten gezählt. Allerdings gilt dann wie du richtig sagst, dass Start größer als Ende sein muss.
![unbenannt](https://user-images.githubusercontent.com/17641229/49102277-b2872a00-f278-11e8-8425-559d99cf63e4.PNG)
Ausgabe: "67890"

**Comment by elzershark** [comment]
Jup. So geht es. In der Mitte hast Du "nimm Teil ab" genommen. Bei "nimm Teil von hinten" würde es nicht funktionieren. Das ist aber egal.
Somit kein Bug... Weiter machen.. :)

**Comment by AlCalzone** [comment]
Richtig, das würde Regel 3 missachten
