### ISSUE TITLE
Hilfe Link im Script Editor hat falsches Ziel

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [ioBroker/ioBroker.javascript#195]
Im Script Editor hat der Link, der bei den globalen Scripten hinterlegt ist  (**Globales Skript (klicke hier für Hilfe**)) ein falsches Ziel.
Ist: https://github.com/ioBroker/ioBroker.javascript#global-functions
Soll https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/en/javascript.md#global-functions

**Comment by GermanBluefox** [comment]
Ist mit JS 4.0 nicht mehr aktuell.
