### ISSUE TITLE
4.0: Global scripts folder not shown

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#199]
Global scripts folder is missing but scripts seem to run. 
Also no logging that global scripts are started but functions I have defined in global scripts are working so they are running.

Example where I use a self created class (in global) and auto completion shows the correct methods of the class, but the global folder is missing.
![bildschirmfoto von 2018-11-22 13-26-42](https://user-images.githubusercontent.com/25484431/48902905-4d879a80-ee5a-11e8-9984-6effa632115f.png)

**Comment by foxriver76** [comment]
Have to activate expert mode.

**Comment by AlCalzone** [comment]
Finally this beginner-trap is hidden!

**Comment by foxriver76** [comment]
Yes, perfect. :+1:
