### ISSUE TITLE
4.0: CRON select minutes has no zero

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#200]
CRON selector for minutes shows 60 for selection but a 0 is needed instead.
![cron](https://user-images.githubusercontent.com/25484431/48916420-86d40080-ee82-11e8-850e-745c1e1caed3.PNG)

Also if you select an hour e. g. 4 you will get '* 4 * * *' and then you deselect all in tab minutes you will get a cron job with 4t minute of every hour '4 * * *' but under hours 4 is still selected. So deselct all shouldnt remove the whole star of the cron expression.

**Comment by GermanBluefox** [comment]
Fixed
