### ISSUE TITLE
4.0: Scripts list - folder icons are confusing

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.javascript#201]
The folder icons used in the list of scripts are not compliant to their general use.
Here the icon `arrow down` is used to indicate that there is a closed folder to be opened. So any script that is listed below a folder with an `arrow down` icon is **not** part of that folder. That is confusing (see screenshots: _CCH_schlaeft_EIN_AUS_ and _Fritzbox_Meldung_ are not part of _Anwesenheit_ as they all live in the same directory `common`).
![bildschirmfoto 2018-11-26 um 00 41 13](https://user-images.githubusercontent.com/8090989/48986344-02001580-f114-11e8-90de-b3e3ecb6367f.jpg)

Generally the icon `arrow down` shows an open folder. A closed folder should be indicated by an `arrow right`

**Comment by AlCalzone** [comment]
An open folder should probably also be indicated by an open folder symbol

**Comment by GermanBluefox** [comment]
Changed. Please verify

**Comment by foxriver76** [comment]
![bildschirmfoto von 2018-11-28 11-40-02](https://user-images.githubusercontent.com/25484431/49146442-726c8980-f302-11e8-9d30-3e6ff20ae0ef.png)
![bildschirmfoto von 2018-11-28 11-40-10](https://user-images.githubusercontent.com/25484431/49146444-74364d00-f302-11e8-97a9-205075b58d0c.png)

IMHO the arrow down should indicate an open folder and the arrow right should indicate closed folder?

**Comment by foxriver76** [comment]
Like in Ubuntu:
![bildschirmfoto von 2018-11-28 11-43-24](https://user-images.githubusercontent.com/25484431/49146632-d98a3e00-f302-11e8-941b-c68a3b4e05a9.png)

![bildschirmfoto von 2018-11-28 11-43-04](https://user-images.githubusercontent.com/25484431/49146638-dc852e80-f302-11e8-9c24-6d30ef521a68.png)

**Comment by AlCalzone** [comment]
Or in Windows:
![unbenannt](https://user-images.githubusercontent.com/17641229/49147285-8e712a80-f304-11e8-9ac1-180efd572a9f.PNG)

**Comment by Pix---** [comment]
Or finally OS X
![bildschirmfoto 2018-11-28 um 12 36 36](https://user-images.githubusercontent.com/8090989/49149433-5c62c700-f30a-11e8-92a2-2b3c6c6509b3.jpg)

**Comment by Pix---** [comment]
Now it looks correctly. Thank you
