### ISSUE TITLE
4.0: Select ID Folder Icon is missing

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.javascript#202]
![bildschirmfoto 2018-11-26 um 08 57 39](https://user-images.githubusercontent.com/8090989/49000336-7dd08100-f159-11e8-9be3-18aa16365466.jpg)
The question mark is indicating a missing folder icon (column "Name")

**Comment by GermanBluefox** [comment]
I understand. :) Fixed yet but fix will be ready compiled tomorrow

Am Mo., 26. Nov. 2018, 09:00 hat Pix <notifications@github.com> geschrieben:

**Comment by Pix---** [comment]
Works great, icons are visible now. Thank you
