### ISSUE TITLE
4.0.1: Found a redundant character in editor

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.javascript#205]
![bildschirmfoto 2018-12-02 um 09 06 45](https://user-images.githubusercontent.com/8090989/49337302-caaccf80-f611-11e8-8453-c1f400db02e6.jpg)
Above the editor a `(` is shown. It seems to have no purpose.

Browser: Safari (OS X)

**Comment by GermanBluefox** [comment]
Are other browsers OK?

**Comment by GermanBluefox** [comment]
Fixed in 4.0.2
