### ISSUE TITLE
Symbole im dunklen Modus nur noch sehr schlecht zu erkennen

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.javascript#206]
![grafik](https://user-images.githubusercontent.com/36501310/49337762-912b9280-f618-11e8-92e3-95e0c50ebfb8.png)

**Comment by AlCalzone** [comment]
Duplicate of #222
(Marking this as a duplicate because the other issue has one more detail)

**Comment by GermanBluefox** [comment]
Fixed in 4.0.2
