### ISSUE TITLE
Nach Update von 3.7 auf 4.01 keine Scripte mehr sichtbar

### ISSUE THREAD

**Issue by erichsch** [ioBroker/ioBroker.javascript#207]
JS-Controller 1.5.2
Admin 3.5.10
Downgrade auf 3.6.4 und alle Scripte sind wieder sichtbar.
P.S. 3.7.0 wurde nicht gefunden.

**Comment by Brainbug01** [comment]
Hast du einen Doppelklick auf die Scripte gemacht? Die Scripte laden nicht mehr nur durch einfaches anklicken.

**Comment by erichsch** [comment]
Ich meine wenn ich das Update mache, werden mir KEINE skripte mehr angezeigt. 
Das Fenster ist leer. Wo sollte ich da doppelklicken?

Skripte (Links im Frame) ===>> Fenster Rechts leer

**Comment by erichsch** [comment]
sorry verklickt, wollte nicht closen

**Comment by erichsch** [comment]
![image](https://user-images.githubusercontent.com/9766119/49338891-ecfe1780-f628-11e8-8ca4-d3080f6423a5.png)

**Comment by Apollon77** [comment]
Mal bitte Shift reload machen und ggf Browser cache löschen.. was sagt die browser konsole?

**Comment by erichsch** [comment]
`unreachable code after return statement[Learn More] tabs.js:199
unreachable code after return statement[Learn More] tabs.js:358
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] 192.168.0.230:8081
Subscribe logs Connection.js:227:30
Detected custom blockly: cloud BlocklyEditor.js:90:57
Detected custom blockly: sayit BlocklyEditor.js:90:57
Detected custom blockly: telegram BlocklyEditor.js:90:57
TypeError: t.find(...) is undefined; can't access its "index" property[Learn More] SideMenu.js:214:17
TypeError: "t.find(...) is undefined; can't access its "index" property"

    	Ze SideMenu.js:214
    	Ze SideMenu.js:209
    	value SideMenu.js:361
    _o10React

    	value App.js:190
    	onReady App.js:136
    	e Connection.js:60
    	value Connection.js:220

react-dom.production.min.js:3744
Detected custom blockly: cloud BlocklyEditor.js:90:57
Detected custom blockly: sayit BlocklyEditor.js:90:57
Detected custom blockly: telegram`

**Comment by Diginix** [comment]
Hatte das Problem auch. Funktionierte in keinem Browser, auch nicht nach Cache leeren usw.
Nachdem ich im Adaptermenü dann einfach mal auf das Upload Icon vom javascript Adapter geklickt habe, wurde das Userinterface geladen. K.a. ob da ein kausaler Zusammenhang besteht.
Da 4.0.1 bei mir noch weitere Bugs hat, versuche ich gerade ein Downgrade auf 3.6.4.

**Comment by erichsch** [comment]
auch das upload Icon funktioniert bei mir nicht.
ich verstehe nur nicht, warum ich nicht auf die 3.7.0 downgraden kann.
diese version hat immer gut funktioniert.
3.6.4 ist möglich. ich bleibe jetzt mal dabei.

danke für eure mühe!

**Comment by Diginix** [comment]
3.7.0 wurde mir nie angeboten, trotz latest channel. War bis zum heutigen Updateangebot auf 3.6.4 und da bin ich nun wieder. Denke auch dass der Trick mit dem Upload Button nur Zufall war.

**Comment by Kunibert-007** [comment]
Same problem - habe heute kurz die neue Oberfläche gesehen, seit ich dann ein neues Skript angelegt habe ist sie von zwei verschiedenen PCs aus nicht mehr erreichbar, ich bekomme das gleiche leere Fenster wie oben abgebildet. Werde wohl auch ein Downgrade machen müssen :-(

**Comment by GermanBluefox** [comment]
> Same problem - habe heute kurz die neue Oberfläche gesehen, seit ich dann ein neues Skript angelegt habe ist sie von zwei verschiedenen PCs aus nicht mehr erreichbar, ich bekomme das gleiche leere Fenster wie oben abgebildet. Werde wohl auch ein Downgrade machen müssen :-(

Wirklich "same" ???
`TypeError: t.find(...) is undefined; can't access its "index"`

Wenn nicht, dann bitte nicht alles in einen Eimer rein werfen. Drück mal F12 und berichte.

**Comment by Kunibert-007** [comment]
@GermanBluefox 
Es sieht bei mir genauso aus wie bei Erisch im Screenshot weiter oben.
Im Console-Log mit Einschränkung auf Fehlerlevel "Error" und "Warnings" steht folgendes:

`7vendor.js:1 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
c @ vendor.js:1
1.39997a33.chunk.js:1 TypeError: Cannot read property 'index' of undefined
ai @ 1.39997a33.chunk.js:1
1.39997a33.chunk.js:1 Uncaught TypeError: Cannot read property 'index' of undefined
1.39997a33.chunk.js:1 TypeError: Cannot read property 'index' of undefined
    at main.53582959.chunk.js:1
    at Array.forEach (<anonymous>)
    at Ze (main.53582959.chunk.js:1)
    at t.value (main.53582959.chunk.js:1)
    at _o (1.39997a33.chunk.js:1)
    at Xo (1.39997a33.chunk.js:1)
    at ti (1.39997a33.chunk.js:1)
    at Ti (1.39997a33.chunk.js:1)
    at Di (1.39997a33.chunk.js:1)
    at da (1.39997a33.chunk.js:1)
ai @ 1.39997a33.chunk.js:1
1.39997a33.chunk.js:1 Uncaught TypeError: Cannot read property 'index' of undefined
    at main.53582959.chunk.js:1
    at Array.forEach (<anonymous>)
    at Ze (main.53582959.chunk.js:1)
    at t.value (main.53582959.chunk.js:1)
    at _o (1.39997a33.chunk.js:1)
    at Xo (1.39997a33.chunk.js:1)
    at ti (1.39997a33.chunk.js:1)
    at Ti (1.39997a33.chunk.js:1)
    at Di (1.39997a33.chunk.js:1)
    at da (1.39997a33.chunk.js:1)`

HIlft dir das weiter? Mir sagt es leider überhaupt nix...

**Comment by Kunibert-007** [comment]
![iobroker-skripte](https://user-images.githubusercontent.com/35669927/49473505-8ccac980-f812-11e8-9aa7-1b5230d70e9b.PNG)

**Comment by AlCalzone** [comment]
Es ist  jedenfalls nicht der gleiche Fehler

**Comment by GermanBluefox** [comment]
Please retest with 4.0.2

**Comment by erichsch** [comment]
Der Anzeigefehler ist weg. Danke schön!
