### ISSUE TITLE
Nach Update auf 4.01 keine SendTo Blöcke mehr in Blockly sichtbar

### ISSUE THREAD

**Issue by mlapp** [ioBroker/ioBroker.javascript#209]

**Comment by winterson0** [comment]
@same problem

**Comment by vepman** [comment]
Ja, das gleiche Problem bei mir auch.

**Comment by BuZZy1337** [comment]
Was sagt die Console vom Browser?
Fehlermeldungen?

**Comment by sigi2345** [comment]
![screenshot 1337](https://user-images.githubusercontent.com/41079106/49430341-0b8c1c00-f7ab-11e8-91b4-59ce9394ac72.png)

**Comment by GermanBluefox** [comment]
Please test cloud adapter from git

**Comment by mlapp** [comment]
No change. Cloudadapter 2.7.1 is installed but Telegramm-Block is not available.

**Comment by GermanBluefox** [comment]
Fixed in 4.0.2

**Comment by Rantanplan01** [comment]
Noch nicht ganz gefixt.
Getestet in Firefox und Chrome.

Ausgangszustand: Alle SendTo Bausteine vorhanden.

Ein Blockly öffen. Egal welches.
Dann im Admin von "Scripte" auf "Log" wechseln.
Und wieder zurück auf "Scripte" --> SendTo Bausteine fehlen.

Und so bekommt man die SendTo Bausteine zurück.
Alle geöffneten Blocklys schließen!!
Dann die Tasten Strg + F5 drücken

**Comment by Rantanplan01** [comment]
4.0.3 Bei mir bleiben die SendTo Bausteine erhalten.

**Comment by GermanBluefox** [comment]
Fixed.
