### ISSUE TITLE
nadir Problem

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.javascript#21]
Wie schon im Forum angemeldet funktioniert die Astro-Funktion nadir nicht!

1. Grund: Bei astroList und AstroListLow fehlt 'nadir' komplett, vielleicht aus dem Grund da es nicht funktioniert hat wegen der suncalc Probleme damit!

2. Grund suncalc kalkuliert den nadir der leider immer in der Vergangenheit liegt da es indirekt einen Tag abzieht. 

Lösung: 
                if (pattern == 'nadir')
                    date = new Date(date.getTime() + 1000 * 60 * 60 * 24);
                var ts = mods.suncalc.getTimes(date, adapter.config.latitude, adapter.config.longitude)[pattern];

wenn nach nadir gefragt wird muss ein Tag dazugezählt werden damit nadie nicht in der Vergangenheit liegt und das nächste nadir zurückgegeben wird!

Diese 2 patches machten nadir verfügbar.

LG
Frank

**Comment by frankjoke** [comment]
new Date(date.getTime() + 1000 * 60 * 60 * 24); ....
Keine Ahnung warum git das nicht richtig weitergibt

**Comment by frankjoke** [comment]
Mit diesem patch hab ich meinen javascript

**Comment by frankjoke** [comment]
I deleted an comment and have no glue why it closed the issue!

**Comment by Jey-Cee** [comment]
@frankjoke do you know if this Bug is gone or is it still there?

**Comment by frankjoke** [comment]
Yes, it's still there.

**Comment by Jey-Cee** [comment]
#https://github.com/mourner/suncalc/issues/113

**Comment by xmace** [comment]
javascript adaptor has still issue with "NADIR" Astro trigger. It seems not working completely...

**Comment by GermanBluefox** [comment]
Must be fixed with suncalc2
