### ISSUE TITLE
4.0.1 Cannot extract Blockly code!

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.javascript#210]
Manche Scripte werden mit der Fehlermeldung:

Cannot extract Blockly code!

nicht geladen.

**Comment by GermanBluefox** [comment]
>Manche Scripte 

Welche? Beispiel?

**Comment by Brainbug01** [comment]
Z.B. das hier:

<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="on" id="k-4Gr2;%EY.M`20N?h?|" x="0" y="0">
    <field name="OID">mihome.0.devices.magnet_158d0001bf87cd.state</field>
    <field name="CONDITION">ne</field>
    <field name="ACK_CONDITION"></field>
  </block>
  <block type="controls_if" id="8O.T-2^nty4`5UMNzbOX" x="0" y="0">
    <value name="IF0">
      <block type="logic_compare" id=")p)B9]iD+wrj[C!;?^}?">
        <field name="OP">EQ</field>
        <value name="A">
          <block type="get_value" id="7JGZJbVTz[[%hWIk7=ze">
            <field name="ATTR">val</field>
            <field name="OID">mihome.0.devices.magnet_158d0001bf87cd.state</field>
          </block>
        </value>
        <value name="B">
          <block type="logic_boolean" id="Pj]oz`w{-CQz@OOC_x_q">
            <field name="BOOL">TRUE</field>
          </block>
        </value>
      </block>
    </value>
  </block>
  <block type="controls_if" id="uNQs7+p!J6SH0NH)ZcS)" x="0" y="0">
    <value name="IF0">
      <block type="time_compare_ex" id="B+p+m.8J]`7=oie}v*/o">
        <mutation end_time="true" actual_time="true"></mutation>
        <field name="USE_ACTUAL_TIME">TRUE</field>
        <field name="OPTION">between</field>
        <value name="START_TIME">
          <shadow type="text" id="}~Mht93mXUWaq(}=g1O)">
            <field name="TEXT">09:30</field>
          </shadow>
        </value>
        <value name="END_TIME">
          <shadow type="text" id="qyM8CpUKrzsx|{GM(BLh">
            <field name="TEXT">20:00</field>
          </shadow>
        </value>
      </block>
    </value>
  </block>
  <block type="telegram" id=")j4/r;Mcq4l@{N`[9w^r" x="0" y="0">
    <field name="INSTANCE">.0</field>
    <field name="LOG"></field>
    <field name="SILENT">FALSE</field>
    <field name="PARSEMODE">default</field>
    <value name="MESSAGE">
      <shadow type="text" id="uIXLX%4svM!hg2W0_1_L">
        <field name="TEXT">Post im Briefkasten</field>
      </shadow>
    </value>
  </block>
  <block type="telegram" id="q2Fc4@_s/1i#u}./t41:" x="0" y="0">
    <field name="INSTANCE">.1</field>
    <field name="LOG"></field>
    <field name="SILENT">FALSE</field>
    <field name="PARSEMODE">default</field>
    <value name="MESSAGE">
      <shadow type="text" id="Y44sD.)sL)/j=(;Ymga~">
        <field name="TEXT">Post im Briefkasten</field>
      </shadow>
    </value>
  </block>
  <block type="sayit" id="ac9V7n{YneTSfQpCH0-)" x="0" y="0"></block>
</xml>

In welchem Format hättest du die gerne?

**Comment by AlCalzone** [comment]
> In welchem Format hättest du die gerne? Wie bekomm ich denn das XML hier richtig dargestellt?

Drei Backticks ( \` ) (<kbd>SHIFT</kbd> + <kbd>´</kbd>)
XML-Code
wieder drei Backticks ( \` )

z.B.
````
```xml
<a> text </a>
```
````
wird zu
```xml
<a> Text </a>
```

**Comment by Brainbug01** [comment]
Danke, nun ist oben ein Blockly welches nicht geladen wird. Ich hätte noch mehr...

**Comment by Rantanplan01** [comment]
Bei mir scheint es so zu sein, dass es mit den fehlenden SendTo Bausteinen zu tun hat.
Scripte laufen aber alle. (Gott sei Dank)

**Comment by Brainbug01** [comment]
Ich hab andere Blocklys wo Telegram und Pushover drin ist und das wird geladen ohne Fehlermeldung.

**Comment by GermanBluefox** [comment]
Ich brauche das Object und nicht extrahierten XML
![image](https://user-images.githubusercontent.com/4582016/49478345-d5d54a80-f81f-11e8-86e1-b022b9e40493.png)

**Comment by Brainbug01** [comment]
4.0.2 geht es, Danke.

**Comment by Brainbug01** [comment]
Ich muss es wieder öffnen. Beim ersten öffnen wird das Script korrekt geladen und angezeigt. Wechselt man z.B. auf der Reiter Adapter und wieder zurück aus Scripte kommt wieder die Meldung:
Cannot extract Blockly code!

[javascript.0.scriptEnabled.MiHome.Text_Ansagen.Briefkasten.zip](https://github.com/ioBroker/ioBroker.javascript/files/2649299/javascript.0.scriptEnabled.MiHome.Text_Ansagen.Briefkasten.zip)

**Comment by Ilovegym66** [comment]
ja, hier auch, ist mir am Anfang gar nicht aufgefallen, da ich nur Javascripte im Editor hatte :-) 
Und wenn man den damit startet, gibts keine Fehlermeldung, aber beim ersten Blockly dann. 
Script schliessen und neu öffnen, dann gehts und die Fehlermeldung kommt solange der Editor offen ist, auch nicht wieder.

**Comment by GermanBluefox** [comment]
Please retest with 4.0.3

**Comment by Brainbug01** [comment]
It works without an error! Thanks.
