### ISSUE TITLE
Javascript 4.01 FS Funktionen nicht eingebunden

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.javascript#213]
die funktion fs.fs.existsSync steht nicht mehr zur Verfügung.

Sieht so aus, dass mit der neuen JS Version die FS Funktionen gesondert installiert werden muessen.
Da ich einige Programme der Community zur Verfügung gestellt haben, die FS Funktionen nutzen werden daher viele Fehlermeldungen in den Scripten zu erwarten sein.
Folgende Fehlermeldung wird ausgegeben:

javascript.0 | 2018-12-02 12:23:20.212 | error | Error in callback: TypeError: fs.existsSync is not a function

vG Looxer

**Comment by Thisoft** [comment]
Die FS-Funktionen pauschal funktionieren aber noch. Zumindest fs.readFileSync und einige andere die ich getestet habe.

Allerdings kann ich den Fehler bei "existsSync" bestätigen. Gleiche Meldung wie oben.

**Comment by looxer01** [comment]
Hi,
Ich habe den Code nun austauscht durch FileRead. Allerdings wäre es trotzdem gut zu wissen, ob hier ein Statement generell nicht mehr zur Verfügung steht.

**Comment by AlCalzone** [comment]
Ist garantiert ein unerwünschter Nebeneffekt, da `existsSync` ein Core-Bestandteil von NodeJS ist. Gib Bluefox etwas Zeit, er ist gefühlt 1000 Dinge am Fixen.

**Comment by looxer01** [comment]
na klar. Ich weiss ja selber wie das ist :)

**Comment by smartboart** [comment]
Kann ich bestätigen. bekomme nach dem Update auf 4.0.1 folgende Meldung im log: 
TypeError: fs.statSync is not a function

gibts ein workaround für das Problem?

**Comment by GermanBluefox** [comment]
fixed in 4.0.2
