### ISSUE TITLE
Nach Update auf 4.0.1 Probleme mit Anmeldung, SSL und Aussehen

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#214]
Ich habe heute mal das Update ausgeführt und habe einige Probleme.

1. Wenn man die Anmeldung und SSL aktiviert hat, ladet der Scriptadapter nur noch und es werden keine Scripte angezeigt. ( SSL und Anmeldung habe ich jetzt einmal aktiviert, nun funktioniert es )
2. Die Tabellen in der "Infozentrale -Protokoll" unter dem Script ist kaum zu lesen.
3. Kein Global mehr vorhanden für Globale Scripte.

Mehr Fehler konnte ich auf die kurze Zeit nicht finden

**Comment by AlCalzone** [comment]
Zu 3.: Globale Skripte sind gottseidank im Expertenmodus versteckt.

**Comment by GermanBluefox** [comment]
1. Ich kann das nicht reproduzieren.
