### ISSUE TITLE
Version 4.0.1: Blockly noch nicht vollständig auf Deutsch übersetzt

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#215]
Leider ist Blockly noch nicht vollständig auf Deutsch übersetzt. Dies bitte noch aufholen. Danke

**Comment by GermanBluefox** [comment]
Was genau?
Dies bitte noch aufholen. Danke

**Comment by GermanBluefox** [comment]
Done in 4.0.3
