### ISSUE TITLE
Version 4.0.1: Blockly läuft nicht / Cannot extract Blockly code

### ISSUE THREAD

**Issue by rasiegfr** [ioBroker/ioBroker.javascript#216]
Seit dem Update laufen sämtliche Skripte (Blocklys) nicht mehr. Ein Downgrade hat leider auch keine änderungen gebracht.
Zuerst waren ebenfalls keine Skripte mehr vorhanden, nach längerem hin und her waren die Skripte wieder vorhanden, allerdings mit der Meldung "Cannot extract Blockly code".
Nun bin ich wieder auf Version 3.6.4. Von der Bedienung her funktioniert alles, es werden nur keine Skripte mehr ausgeführt. Die Log Datei ist durchgehend "rot".
![log_datei](https://user-images.githubusercontent.com/45539407/49342411-5eef5480-f65b-11e8-9ccb-194fec4299c5.JPG)

**Comment by AlCalzone** [comment]
Duplicate of #210

**Comment by rasiegfr** [comment]
fehler gefunden. beim java adapter ist ein haken gesetzt gewesen welcher nicht sein durfte. ob ich das nun gemacht habe oder dieses automatisch beim update geschehen ist kann ich nicht mehr nachvollziehen.
der haken darf nicht gesetzt sein. vielen dank für die hilfe im iobroker forum!

![fehler](https://user-images.githubusercontent.com/45539407/49420484-f8b61f00-f78b-11e8-912e-16b0487b56a2.JPG)
