### ISSUE TITLE
V4.0.1 Crown Time cannot be changed

### ISSUE THREAD

**Issue by Einklaus** [ioBroker/ioBroker.javascript#217]
Mein Englisch ist zu schlecht deshalb auf deutsch.....
Blockly -> Trigger -> Zeitplan
Beim Zeitplan definieren werden beim betätigen mit OK die Änderungen nicht mit Übernommen.
Zeiteingaben bei Blockly ->Datum und Zeit -> Aktuelle >Zeit ist  auch nicht möglich 

Grüße
Einklaus
und immer noch geniale Arbeit von euch

**Comment by GermanBluefox** [comment]
Fixed in 4.0.2
