### ISSUE TITLE
Fehlende bisherige Funktionen in Version 4.0.1

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.javascript#218]
Hallo,

mir fehlen die bisher gewohnten Funktionen zum 
- Kopieren von Scripten
- Löschen von Ordnern

Ach ja, aufgefallen ist mir nebenbei ein
- Übersetzungsfehler im Reiter"Blöcke importieren", der Button wurde mit "exportieren" benannt.

Grüße
Fabian

**Comment by GermanBluefox** [comment]
Added in 4.0.2
You can delete only empty folder
