### ISSUE TITLE
Version 4.0.1 keine Javascriptfunktion in Blockly mehr möglich

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#220]
Nach dem Update kann ich zwar die Funktion Javascript bei Blockly hinzufügen, jedoch kann ich die Texteingabe der Javascript-Funktion nicht mehr öffnen.

**Comment by Rantanplan01** [comment]
Den Fehler kann ich bestätigen.

**Comment by GermanBluefox** [comment]
In Arbeit

**Comment by GermanBluefox** [comment]
Done in 4.0.3

**Comment by Rantanplan01** [comment]
Funktioniert jetzt
