### ISSUE TITLE
4.0.1 Blockly Thema

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#222]
Im "hellen" Thema ist die Protokoll-Ausgabe fast nicht zu lesen.
Im "dunklen" Thema sind im Edit-Bereich "zentrieren", "vergrößern", "verkleinern" und "Papierkorb" nicht mehr zu erkennen.
Im Menü zum Umschalten des Themas bleibt immer "Dunkles Thema" stehen. Auch wenn wann schon auf "Dunkles Thema" umgeschaltet hat. Sollte dann da nicht "helles Thema" stehen?

**Comment by Rantanplan01** [comment]
Habe noch etwas vergessen. 
Wenn man zwischen dunklen und hellen Thema umschaltet. Bleibt der Edit-Bereich hell.

**Comment by AlCalzone** [comment]
Related: #206

**Comment by GermanBluefox** [comment]
>Sollte dann da nicht "helles Thema" stehen?

Nein. Denke man kann schon merken, ob dunkles Theme an ist? Oder?

**Comment by GermanBluefox** [comment]
> Bleibt der Edit-Bereich hell.

Vielleicht blockly und nicht editor?

**Comment by AlCalzone** [comment]
Wenn das Thema dunkel ist fände ich auch besser wenn der Button "helles Thema" heißt.

**Comment by Rantanplan01** [comment]
@Bluefox Ja, nur im Blockly "Editor"

**Comment by GermanBluefox** [comment]
> @bluefox Ja, nur im Blockly "Editor"

Dagegen, weiß noch nicht was zu machen ist. Javascript file anklicken und zurück, dann geht

**Comment by Rantanplan01** [comment]
Bis auf den kleinen Schönheitsfehler im Blockly Editor alles nun alles gut
