### ISSUE TITLE
4.0.1 Blockly - Keine Warnung mehr bei nicht gespeicherten Script

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#223]
Nun hat man ja die "tolle" Möglichkeit mehrere Scripts gleichzeitig geöffnet zu halten.

Es kommt aber keine Warnung mehr, wenn man noch ein geändertes und nicht gespeichertes Script hat und z. B. in ioBrocker auf "Log" wechselt.

Dadurch das man nun mehrere Script geöffnet halten kann, erhöht sich dadurch die Gefahr von Arbeitsverlust.

**Comment by Rantanplan01** [comment]
Kann man das Öffnen von mehreren Scripts nicht wieder abstellen?
Jetzt beim Durchschauen/Fehlersuche musste ich hinterher fast 70 Scripte manuell schließen :(

**Comment by Rantanplan01** [comment]
Wenn dann die Warnung vor "nicht gesicherten" Scripts wieder klappt. ;)

**Comment by GermanBluefox** [comment]
> Kann man das Öffnen von mehreren Scripts nicht wieder abstellen?

Nein. Das wollten die anderen haben.

**Comment by Rantanplan01** [comment]
(4.0.2) Beim schließen eines Blockly kommt eine Wahrmeldung. 
(Die rote Markierung im Reiter ist sehr praktisch.)

Wenn man aber ein **geändertet** Blockly hat und im Admin von "Scripte" auf "Log" wechselt gibt es je nach Browser unterschiedliche Reaktionen.
Chrome zeigt gar nichts an und wechselt die Seite.
Firefox fragt: "Seite verlassen" oder "Auf Seite bleiben". Egal was man anwählt, die Seite wird verlassen.

Dann kommt es zu den Phänomenen wie unter #209 beschrieben.
Zusätzlich kommt dann sehr häufig "Cannot extract Blockly code"

**Comment by Rantanplan01** [comment]
v4.1.0
Warnung bei nicht gesicherten Script klappt jetzt.
Getestest mit Firefox und Chrome.
Prima! Danke!
