### ISSUE TITLE
4.0.1 Blockly - Ordner

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#224]
Es ist nicht mehr möglich den Ordner eines Scripts zu ändern!!!

Es ist nicht mehr möglich einen Ordner zu löschen!!!

**Comment by GermanBluefox** [comment]
>Es ist nicht mehr möglich einen Ordner zu löschen!!!

Nur wenn Ordner lehr ist.

>Es ist nicht mehr möglich den Ordner eines Scripts zu ändern!!!

![image](https://user-images.githubusercontent.com/4582016/49478225-7aa35800-f81f-11e8-85ab-845fbb73926a.png)

**Comment by Rantanplan01** [comment]
Ok! Gruppe ändern geht.

"Ordner löschen" läuft noch komisch. (4.0.2)
Getestet in Firefox und Chrome.

a) Neuer Ordner "Mappe 1" -> Root-Verzeichnis
b) Neues Script in "Mappe 1" -> Script 1

Dann "Script 1" löschen -> ok
Dann "Mappe 1" löschen -> ok

Nochmals Scritte a und b durchführen.

Jetzt erst "Mappe 1" löschen -> "Mappe 1" wird nicht gelöscht. Aber als letzter Ordner einsotiert.
Wenn man nun "Script 1" aus "Mappe 1"  löscht, wird auch gleichzeitig "Mappe 1" gelöscht,

**Comment by GermanBluefox** [comment]
Changed in 4.0.3

**Comment by Rantanplan01** [comment]
Klappt jetzt prima
