### ISSUE TITLE
subscribe mit value:true wird als fehler angezeigt

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.javascript#225]
![2018-12-03_19h36_49](https://user-images.githubusercontent.com/6328382/49393920-e65bc700-f732-11e8-9f9b-67e6146ed4e7.png)

**Comment by AlCalzone** [comment]
Was ist denn der Fehler? Bitte mouseover zeigen.

**Comment by Apollon77** [comment]
Yes it is an error because val:true is correctly!!

**Comment by AlCalzone** [comment]
Ich würde trotzdem gerne den Fehler sehen, denn eigentlich müsste `value:true` unterkringelt sein.

**Comment by Apollon77** [comment]
Interessanterweise ist ja "id:test" unterkringelt

**Comment by AlCalzone** [comment]
Es lag an der Reihenfolge der Überladungssignaturen. Habe diese jetzt in eine einzige kombiniert, da beim Tausch der Reihenfolge das gleiche Problem auftritt, wenn in `{astro: ...}` falsche Eigenschaften drin sind.
