### ISSUE TITLE
4.0.1 Script Warnungen seit update

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.javascript#226]
Hi

Ich schalte per Blockly und den Harmony adpater (es betriff aber auch zB den Milight adapter) meinen Tv,Hifi etc. Mit der alten Version (3.6.4) hatte ich folgende Warnungen

warn: at Object.<anonymous> (script.js.Scripte.TV.TVOben.HarmonyHub.Aktion.TV_UPC_AN_AUS:5:5)
warn: javascript.0 Wrong type of harmony.0.m0rph-Harmony.Cisco-DVR.PowerOn: "boolean". Please fix, while deprecated and will not work in next versions.

Mit der 4.0.1 Version siehe Upload (ist leider ein riesen Text)
[Warnungen 4.0.1](https://github.com/ioBroker/ioBroker.javascript/files/2641244/Warnungen.4.0.1.txt)

Sobald ich wieder 3.6.4 Installiere kommt die erste kurze Warnung. Aber egal ob kurz oder lange Warnung funktionieren tut es bei beiden

npm 4.6.1
nodejs 8.12.0

LG

**Comment by AlCalzone** [comment]
Warum geschlossen?

**Comment by m0rph2k** [comment]
Dachte der Fehler wäre weg, musste dann aber feststellen das ich immer noch den Fehler bekomme. Komischerweise aber nicht von anfang an

**Comment by m0rph2k** [comment]
Kann man hier irgendwas machen, bzw habe ich was falsch gemacht ?

**Comment by Seraphis411** [comment]
@m0rph2k 
In deinem Skript "Scripte.TV.TVUnten.HarmonyHub.Aktion.TV_UPC_AN_AUS" scheinst du den State "harmony.0.Unten-Harmony.UPC-DVR.PowerToggle" mit einem "boolean"-Wert (also true bzw. false) zu beschreiben, die Warnung gibt's deshalb weil der State wohl einen anderen Typ hat (z.B. "number" oder "string").
Prüfe den tatsächlichen Typ deines States TV_UPC_AN_AUS im Objekte-Tab und passe dein Skript entsprechend an, dann sollte die Warnung nicht mehr auftauchen.
