### ISSUE TITLE
Change message "cannot use sync getState()"...

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#227]
... to include a reference to the adapter settings (do not subscribe all states on start).
Users don't understand that those two are related:
https://forum.iobroker.net/viewtopic.php?p=199471#p199471

**Comment by GermanBluefox** [comment]
What to do?

**Comment by AlCalzone** [comment]
Provide a better error message 😁

**Comment by AlCalzone** [comment]
Example: 
```
The "getState" method cannot be used synchronously, because the adapter setting "do not subscribe to all states on start" is enabled. Please disable that setting or use "getState" with a callback.
```
