### ISSUE TITLE
Wunsch: Default-Enginetyp in der Adapter-Einstellung

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.javascript#23]
Wunsch: Einstellmöglichkeit des Default-Enginetyps.

Derzeit wird immer Blockly zuerst aufgeführt und man kann sich einen Klick sparen, wenn man pro Instanz ein Default einstellen kann.

**Comment by GermanBluefox** [comment]
Es gibt das Problem dass man vom js auf blockly nicht umschalten darf. Dann
wenn js als default steht, kannst du kein blockly mehr wählen

22 Апр 2017 г. 13:31 пользователь "Michael" <notifications@github.com>
написал:

**Comment by paul53** [comment]
Ich hätte kein Problem damit, kein blockly mehr wählen zu können.

**Comment by GermanBluefox** [comment]
No more relevant with 4.x.
