### ISSUE TITLE
ERROR: Cannot find io-package.json in null

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#231]
Wollte so eben die Version 4.0.2 installieren. Jedoch wurde die Installation mit Fehler abgebrochen: 

Log:

$ ./iobroker upgrade javascript
Update javascript from @4.0.1 to @4.0.2
NPM version: 6.4.1
npm install iobroker.javascript@4.0.2 --production --save --prefix "/opt/iobroker" (System call)
npm
 ERR! 
code
 ETARGETnpm ERR! notarget No matching version found for @types/node@11
npm
 ERR!
 notarget
 In most cases you or one of your dependencies are requestingnpm 
ERR!
 notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm 
ERR!     /root/.npm/_logs/2018-12-05T08_15_54_641Z-debug.log
npm WARN react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@5.0.7 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-beautiful-dnd@8.0.7 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@5.0.7 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLEnpm ERR! errno 1
npm ERR! iobroker.javascript@4.0.2 postinstall: `node ./install/installTypings.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.javascript@4.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-05T08_16_04_984Z-debug.log

ERROR: Cannot find io-package.json in null
ERROR: process exited with code 10

**Comment by AlCalzone** [comment]
1. Das ist ein Fehler, wird behoben.
2. Du hast NodeJS 11 (Entwicklerversion) installiert, was nicht empfohlen ist und teilweise auch nicht unterstützt.

**Comment by quorle** [comment]
Danke für die schnelle Rückmeldung. 

2. den Fehler meinerseits habe ich schon bemerkt und beseitige ich heute Abend.

**Comment by AlCalzone** [comment]
PR #232 erstellt :)
