### ISSUE TITLE
Infrastructure: linebreak style, Windows and ESLint

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#233]
Currently, ESLint enforces the linebreak style to be LF, but on Windows the default option of git for `autocrlf` changes the line-endings to CRLF on checkout and back to LF on commit.

We should add a `.gitattributes` file that enforces LF endings on windows, so those 2 tools don't fight :)

**Comment by GermanBluefox** [comment]
@AlCalzone  Done?

**Comment by AlCalzone** [comment]
Yup
