### ISSUE TITLE
4.0.2 Ladeicon - unter 3.x schneller

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#234]
Das Ladeicon, welches seit der 4er Version ist, irritiert mich. In der 3er Version lies sich die Ansicht sofort ohne Wartezeit öffnen.

**Comment by GermanBluefox** [comment]
Was kann ich damit anfangen?

**Comment by FRYYYYYY** [comment]
Dass es jetzt langsamer ist...? Wenn es vorher direkt da war und nun läd, dann ist es doch keine Verbesserung...?

**Comment by Apollon77** [comment]
Die Technologie hat sich im Vergleich zu vorher geändert und daher ist der Ladekringel nötig. Bitte akzeptieren
