### ISSUE TITLE
4.0.2 Anzeige der Scriptnamen abgeschnitten - Spalte zu klein

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#235]
Meine Scripte sind manchmal etwas länger - hier kann ich den ganzen Namen des Scripts nicht mehr in der Übersicht lesen. So muss ich nun jedes Script durchgehen, damit ich es finde. Die Spalte lässt sich auch nicht verbreitern.

**Comment by GermanBluefox** [comment]
>Die Spalte lässt sich auch nicht verbreitern. 

Doch

**Comment by FRYYYYYY** [comment]
Nein. Aber du kannst mir gerne sagen, wo ich die Spalte vergrößern kann.

![image](https://user-images.githubusercontent.com/13643787/49532804-a4ab5780-f8bd-11e8-9215-cf183812a7cf.png)

**Comment by Ilovegym66** [comment]
hab mal ein Script mit extra langen Namen angelegt, siehe Screenshot, der Namen wird nach 22 Zeichen abgeschnitten, wie es aussieht:
![screenshot_2018-12-05 javascript - iobroker](https://user-images.githubusercontent.com/36229898/49534545-12f21900-f8c2-11e8-98e5-4524bca89c55.png)

**Comment by GermanBluefox** [comment]
OK. Wird geändert:
![image](https://user-images.githubusercontent.com/4582016/49547352-bfdc8e00-f8e2-11e8-8613-f5d111b31c1f.png)

**Comment by Ilovegym66** [comment]
with 4.05 problem solved, very good! can be closed.
