### ISSUE TITLE
4.0.2 Objekt-Browser

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#236]
1) Im Objekt-Browser werden manche Namen zweizeilig. Ab dreizeilig kann ich die erste und dritte Zeile des Scripts nicht mehr erkennen

2) Die Optik der normalen Scriptübersicht mit den Ordnern finde ich schön. Die im Objekt-Browser ist ganz anders, andere Farben, anderes Verhalten. Hier muss man zum Öffnen des Ordners auf den Ordner klicken. In der Scriptübersicht finde ich es charmanter und einfacher.

3) Wenn hier Elemente ein .0 am Anfang beinhalten, wird dies als eigener "Ordner" angezeigt. Das war vorher nicht so und übersichtlicher (z. B. customobjects.0.irgendwas = 2 Ordner vorher, jetzt 3 Ordner)

**Comment by GermanBluefox** [comment]
Zu 1. => Screenshot?
Zu 2. => Lässt sich streiten.
Zu.3. => Wurde so entschieden und wird auch irgendwann in Admin umgebaut.

**Comment by FRYYYYYY** [comment]
Zu 1.: Screenshot

![image](https://user-images.githubusercontent.com/13643787/49532907-de7c5e00-f8bd-11e8-82d1-3fe57179963e.png)

Zu 2.: Korrekt. War nur meine Meinung :-)

Zu 3.: Okay, ist ein Statement.

**Comment by GermanBluefox** [comment]
Better now?

**Comment by FRYYYYYY** [comment]
Yes!

![image](https://user-images.githubusercontent.com/13643787/63654834-ecda1500-c77f-11e9-899e-c691caa45d7e.png)
