### ISSUE TITLE
4.0.2: Clicking a script tab should automatically select the corresponding file

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#238]
Most editors do it like this anyways, so this is expected behavior. And we don't need that "locate" button.

**Comment by GermanBluefox** [comment]
![enums](https://user-images.githubusercontent.com/4582016/49546819-6a53b180-f8e1-11e8-9cf8-06043ff0df77.gif)

**Comment by AlCalzone** [comment]
Ok maybe add an option for that? 
VSCODE selects the files and it is very irritating that the JS editor doesn't.

**Comment by AlCalzone** [comment]
I'll have to reinforce on my argument. The tabs and list view not being in sync is very confusing:
![unbenannt](https://user-images.githubusercontent.com/17641229/50733715-faac3d00-1192-11e9-9684-ae8289624c13.PNG)

In the highlighted case I would assume that clicking the delete button on the highlighted script deletes the script that is currently open in the tab view - which is entirely wrong in this case.

I propose that clicking a list item should also highlight the corresponding tab and switching tabs should also select the corresponding list item. 
This way we can also remove the "open script" button, which is not necessary.

**Comment by Apollon77** [comment]
See it the same

**Comment by GermanBluefox** [comment]
if the menu on left is hidden, so I require the button for restart.
![image](https://user-images.githubusercontent.com/4582016/53368706-beeb5380-3949-11e9-862b-9517970ad2f3.png)

I reproduce the behavior of IDE WebStorm at this point.

**Comment by AlCalzone** [comment]
Ok I understand the restart button. The selection of tabs is still very confusing and gets me every time. Please consider changing that behavior.

**Comment by Maja61** [comment]
i go with that ... will be nice to have it. 
Same behaviour in VIS Editor, maybe you can change it too 
[https://github.com/ioBroker/ioBroker.vis/issues/198](url)

**Comment by GermanBluefox** [comment]
No changes for actual vis. vis will be rewritten with react.

**Comment by GermanBluefox** [comment]
> i go with that ... will be nice to have it.

Have you tried WebStorm????

**Comment by GermanBluefox** [comment]
I will close it. Please reopen if needed
