### ISSUE TITLE
Wunsch: Prüfung bei Instanzänderung, ob gespeichert wurde

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.javascript#24]
Derzeit passiert es mir immer wieder, dass ich ein Skript anlege, die Engine ändere den Namen eintrage und mir dann einfällt, dass ich es in einer anderen Instanz anlegen will.

Wenn man nun ohne zu speichern die Instanz ändert, darf man alles die Schritte wieder von Vorne beginnen.

Hilfreich wäre, wenn eine Instanzänderung prüft, ob das Speichern schon durchgeführt wurde und wenn nicht, nachfragt.

**Comment by Jey-Cee** [comment]
@ruhr70 for me it is not possible to change the Instance while i am editing a script. JS Adapter version 3.6.4.
If you can confirm this, we can close this issue.

**Comment by GermanBluefox** [comment]
No more relevant with 4.x.
