### ISSUE TITLE
4.0.3 Editor not loading

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.javascript#241]
Moin,

seit dem update auf 4.0.3 läd der Editor nicht mehr. Es kommt nur das animierte ioBroker Logo.
Der Adapter schmeißt keinen Fehler und funktioniert auch.

Getestet mit Chrome, Firefox und Edge. Cache geleert. Ohne Erfolg.

In der Webconsole finde ich nur dienen Fehler:

```
blockly.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

BlocklyEditor.js:62 GET http://192.168.2.24:8081/adapter/places/blockly.js net::ERR_ABORTED 404 (Not Found)

value | @ | BlocklyEditor.js:62
-- | -- | --
  | value | @ | BlocklyEditor.js:76
  | (anonymous) | @ | BlocklyEditor.js:77
  | setTimeout (async) |   |  
  | (anonymous) | @ | BlocklyEditor.js:76
  | load (async) |   |  
  | value | @ | BlocklyEditor.js:58
  | value | @ | BlocklyEditor.js:76
  | value | @ | BlocklyEditor.js:96
  | value | @ | App.js:194
  | onReady | @ | App.js:138
  | (anonymous) | @ | Connection.js:60
  | (anonymous) | @ | Connection.js:221
  | setTimeout (async) |   |  
  | (anonymous) | @ | Connection.js:204
  | n.onack | @ | socket.io.js:4
  | n.onpacket | @ | socket.io.js:4
  | (anonymous) | @ | socket.io.js:4
  | n.emit | @ | socket.io.js:3
  | n.ondecoded | @ | socket.io.js:2
  | (anonymous) | @ | socket.io.js:4
  | r.emit | @ | socket.io.js:2
  | s.add | @ | socket.io.js:2
  | n.ondata | @ | socket.io.js:2
  | (anonymous) | @ | socket.io.js:4
  | n.emit | @ | socket.io.js:3
  | n.onPacket | @ | socket.io.js:3
  | (anonymous) | @ | socket.io.js:3
  | n.emit | @ | socket.io.js:3
  | n.onPacket | @ | socket.io.js:3
  | n.onData | @ | socket.io.js:3
  | ws.onmessage | @ | socket.io.js:4

```

**Comment by andiling** [comment]
Ja, ich habe selbiges Problem! 
Es scheint daran zu liegen dass Blockly.js nicht geladen wird! Entwicklertool bringt Status Code 404 = Not Found!

![image](https://user-images.githubusercontent.com/20771598/49609048-af87ea00-f99a-11e8-9b71-1f4aa2778608.png)

**Comment by GermanBluefox** [comment]
Bitte _system.adapter.places_ und _system.adapter.places.0_ Objekte modifizieren, so, dass `common.blockly=false` ist

**Comment by vr6syncro** [comment]
weiß leider nicht genau wo ich dass machen soll. im iobroker habe ich nichts gefunden. die datein selber habe ich mir nicht vorgenommen. Ich benötigte den Adapter eh momentan nicht mehr. Habe ich deinstalliert. Es geht nun wieder.

**Comment by andiling** [comment]
Hallo Bluefox, klär uns mal bitte auf warum das etwas mit dem Places Adapter zu tun hat und wie man darauf kommt. Die Doku müsste dringendst weitergeschrieben werden! Ich würde gerne meinen Heliotherm Adapter fertigstellen aber solange ich das mit den States und den Objects nicht verstanden habe geht es leider nicht weiter. Die Kommunikation klappt aber ohne Datenpunkte...! Es gibt bei eurem Projekt für mich so viel Neuland wie Git, Testing, Javascript, HTML und CSS. Ich würde Euch ja wirklich gerne helfen aber ohne schnellen Einstieg wird das ein Ewichkeitsprojekt für mich!

**Comment by andiling** [comment]
Guten Morgen Bluefox! Danke für die Aufnahme ins Entwicklerteam! Was muss ich machen bzw. welche infos benötigst Du? Ja, Telegram habe ich?
