### ISSUE TITLE
4.0.4 Cron block error

### ISSUE THREAD

**Issue by Midyr2** [ioBroker/ioBroker.javascript#242]
Hi, 

after update to 4.0.4 I get for the Blockly funktion:

```
  RollZuSched = schedule('('' + Minute).trim() + ' ' + ('' + Stunde).trim() + ' ' + '*'.trim() + ' ' + '*'.trim() + ' ' + '*'.trim()', function () {
    setStateDelayed(Aktor, unwahr, false, parseInt(0, 10), true);
    sendTo("telegram.0", "send", {
        text: (['Template Schaltung jetzt',Stunde,':',Minute].join('')),
        user: 'Fr'
    });
    (function () {if (RollZuSched) {clearSchedule(RollZuSched); RollZuSched = null;}})();
  });
```

This error:

```
> 
> javascript.0 | 2018-12-06 21:57:52.780 | error | SyntaxError: missing ) after argument list
> -- | -- | -- | --
> javascript.0 | 2018-12-06 21:57:52.780 | error | ^^^
> javascript.0 | 2018-12-06 21:57:52.780 | error | RollZuSched = schedule('('' + Minute).trim() + ' ' + ('' +  Stunde).trim() + ' ' + '*'.trim() + ' ' + '*'.trim() + ' ' +  '*'.trim()', function () {
> javascript.0 | 2018-12-06 21:57:52.780 | error | at script.js.common.Lampe_zufällig_neu:22
> javascript.0 | 2018-12-06 21:57:52.780 | error | script.js.common.Lampe_zufällig_neu compile failed:
```

Thanks for hints

Frank

**Comment by GermanBluefox** [comment]
Can you show me screenshot von blockly?

**Comment by Midyr2** [comment]
![screenshot_blockly](https://user-images.githubusercontent.com/45671567/49663667-a573f300-fa4f-11e8-8356-66de019613f3.png)

**Comment by Midyr2** [comment]
I also get an error "Cannot extract Blockly code!", if I switching into the script window

**Comment by JoJ123** [comment]
schedule = schedule(''*/5 * * * *'' 
When you look in the JavaScript Code, I think here is the error, the '' is not a double quotation marks, they are two single quotation marks

**Comment by Midyr2** [comment]
Hi,
it's not 2 quoatation, but double quotation in 3.0.5:
schedule("* * * * *", function () {
});
3.6.4:

schedule('* * * * *', function () {
});

**Comment by JoJ123** [comment]
@GermanBluefox If you give me some hints, how to fix this. I would give it a try.

**Comment by GermanBluefox** [comment]
Fixed
