### ISSUE TITLE
FileSystem

### ISSUE THREAD

**Issue by Psens666** [ioBroker/ioBroker.javascript#243]
Hello,

i have a probem with fs.createwritestream, see my following Code:

`const fs = require('fs');
const request = require('request');

request("http://192.168.66.12/cgi-bin/snapshot.cgi",function(error,response,body){
    console.warn("FERTIG");
})
.auth("admin","admin",false)
.pipe(fs.createWriteStream("/mnt/bildergarten/latest.jpg"));`

This code returns an Error: "TypeError: fs.createWriteStream is not a function"

can anyone help me??

Greatings Dominic

**Comment by ArneDoe** [comment]
No solution, but a hint:
The same script (only adapted requeststring) works perfect for me.
So, it´s probably not an issue with the script.
But possibly with the installation?

**Comment by GermanBluefox** [comment]
Fixed in 4.1.5
