### ISSUE TITLE
4.0.5 Blockly Baustein Zeitplan

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#244]
Dahrstellungsfehler im Wizard / Zeitraum. (Ich gehe mal davon aus, das dies ein Fehler ist)
Sehr bunt und im "dunklen Modus" kaum zu lesen. Im "hellen Modus" geht es.

Im Cron Modus steht "Daten" anstatt "Tage".
Auch bei der Auswahl: "jeden Tag / alle N Tag / bestimmte Daten"
Bei "alle N Tag" könnte man besser "alle N Tag(e)" schreiben.

**Comment by mlapp** [comment]
Bei mir wird der bestehende Cron-String aus dem Baustein nicht in den Wizard übernommen und muss jedes mal neu erstellt werden.

**Comment by ihavenonick** [comment]
Hier mal ein Beispiel für die Darstellung im dunklen Modus:

![2018_12_08_10_56_04_javascript_iobroker](https://user-images.githubusercontent.com/36501310/49684735-0e9f4900-fad8-11e8-8f78-89c4ff4b722f.png)

**Comment by FRYYYYYY** [comment]
Bei mir auch das Problem, dass die bestehenden Cron Zeiten nicht ausgelesen werden und der Wizard bei jedem Öffnen alles nullt.

**Comment by Rantanplan01** [comment]
v4.1.0 Darstellungsfehler sind behoben. 
Daten sind bei erneutem Aufruf noch vorhanden
Unter CRON steht leider immer noch "Daten" anstatt "Tage".

Soweit sehe ich es als gelöst.
