### ISSUE TITLE
4.0.4 Scripte per ID nicht mehr verfügbar

### ISSUE THREAD

**Issue by Midyr2** [ioBroker/ioBroker.javascript#250]
Hallo,

ich kann per Blockly  vorhandene  Scripte nicht mehr als ID auswählen. z.B.
javascript.0.scriptEnabled.common.xxxx

Version 4.0.3. s.U.
Um den Status zu steuern

Unter Objekte sind die Scripte sichtbar

Durch manuelles Umkopieren der iobroker.javascript.admin Directorys(wg Cron issue), ist, denke ich die Versionsanzeige nicht mehr korrekt. Kann ich iirgenswo in deinem Code sehen, welche Version tatsächlich installiert ist?

**Comment by Apollon77** [comment]
Warum sind deine States unter scriptEnabled? Das ist falsch!!

Die gehören direkt unter JavaScript.0

**Comment by Midyr2** [comment]
Es geht um scripte, die ich aus anderen Scripten heraus starte und stoppe

**Comment by AlCalzone** [comment]
Warum machst du sowas? Wenn du nur Aktionen ausführen willst, solltest du States verwenden, auf die das andere Skript lauscht.

**Comment by Midyr2** [comment]
Es werden mehrere Scripte gesteuert, deswegen erschien es mir einfacher, die Scripte direkt zu steuern, statt in jedem Script auf  mehrere States zu lauschen

**Comment by Brainbug01** [comment]
Gehört es auch hier her das bei einem neu erzeugten Script unter den Objekten bei enabledScript kein Objekt angelegt wird? Oder muss ich dafür ein neues Issue ausmachen?

**Comment by GermanBluefox** [comment]
Sollte gefixt sein.
