### ISSUE TITLE
import all scripts does not work

### ISSUE THREAD

**Issue by naesle** [ioBroker/ioBroker.javascript#253]
with new version I can not import scripts anymore which I exported in the past.

**Comment by fnsign** [comment]
I have this issue, too. When clicking on the "Import scripts" button in the menu, nothing happens (no dialog or similar).

Also a manual import via cut and paste is not working.
- Copy blockly XML from host A (via export)
- Paste XML into host B (via import): Block diagram becomes visible
- Switching to JS view on host B: no code visible
- Switching back to Block view on host B: block diagram disappears.

**Comment by chucky2002** [comment]
I have the same problem

**Comment by MubiTec** [comment]
Me, too

**Comment by dimaiv7** [comment]
I have the same problem

**Comment by Phoenix0815** [comment]
I have the same problem

**Comment by kugelkopf123** [comment]
Same here

**Comment by ihavenonick** [comment]
Tut sich hier noch was?

**Comment by AlCalzone** [comment]
Könnt ja nen PR erstellen...

**Comment by ihavenonick** [comment]
War nur ne einfache Frage auf ein gemeldetes Problem, warum man da den Daumen runter posten muss, versteh ich nicht.
Warum ein PR, ist doch eher ein Bug und hier richtig. Egal, Ihr macht das schon. Warten wir eben noch so lange.

**Comment by AlCalzone** [comment]
Wirkt halt etwas patzig. Ich meinte, ihr könnt euch ja selbst auf Fehlersuche begeben und zur Lösung einen PR erstellen, falls es nicht schnell genug geht.

**Comment by ihavenonick** [comment]
War aber so nicht gemeint. Liegt vielleicht auch daran, dass Ihr normal so was in ein paar Stunden richtet und daran gewöhnt man sich eben. Problem melden und am nächsten Tag gibts ein Update.
Ihr seit dran und wir warten.

**Comment by totti1171** [comment]
4.0.12 (2019-01-20) - leider geht es auch mit dieser Version nicht.

**Comment by ltsalvatore** [comment]
is there any other workaround which can be used to import scripts until problem is fixed. 
I'm currently switching to a new iobroker server and it would really be a pain in the arse recreating round about 50 scripts 🤷‍♀️

**Comment by ihavenonick** [comment]
do a downgrade to 3.6.4 and export your scripts. Than import your Scripts with the same version und do and update back to 4.0.12

**Comment by GermanBluefox** [comment]
Should be fixed in 4.1.4

**Comment by ltsalvatore** [comment]
> Should be fixed in 4.1.4

i can confirm, that it is already fixed with 4.1.0

**Comment by naesle** [comment]
Gut Ding braucht Weile -:)
Problem fixed - works again!
Thanks a lot
