### ISSUE TITLE
4.0.5 Blockly "Objekt ID "  auswählen

### ISSUE THREAD

**Issue by Knallix** [ioBroker/ioBroker.javascript#255]
Leider kann ich keine "Objekt ID" im Blockly mehr auswählen.
Es taucht kurz ein Fenster auf geht dann wieder weg, dann bleibt die Seite Weiß.
Chrom Player

Gruß
Kevin

**Comment by Knallix** [comment]
4.0.7 Installiert leider läuft es immer noch nicht in dem Chrome :-(.....
Bitte um eine Lösung 
Cash ist geleert, alles schon mehrfach neu Installiert und neu gestartet.

**Comment by AlCalzone** [comment]
Was sagt die browser Konsole?

**Comment by Knallix** [comment]
Hier ein Bild von der Console
![unbenannt1](https://user-images.githubusercontent.com/42406048/50857339-9ef9d380-138d-11e9-9c15-aa07fcff3d17.JPG)

**Comment by GermanBluefox** [comment]
Should be fixed in 4.1.4
