### ISSUE TITLE
4.0.5: Debug-Mod

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#258]
Hallo, wird es in Blockly einen Debug-Modus geben? Den vermisse ich leider bei Blockly

**Comment by GermanBluefox** [comment]
Gibt es jemand, wer das benutzt hat?

**Comment by Ilovegym66** [comment]
oft braucht man den nicht, sollte aber vorhanden sein, so wie es jetzt ist, ist es ok.

**Comment by GermanBluefox** [comment]
Added in 4.1.6
