### ISSUE TITLE
4.0: Layout broken after saving script (Firefox)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#259]
This happens in Firefox when the JS tab is inactive for a while and then one switches back there
![unbenannt](https://user-images.githubusercontent.com/17641229/50017918-e2029a00-ffcd-11e8-9b03-dcb4e0524cdf.PNG)

**Comment by AlCalzone** [comment]
Also happens when a new script is created or any other dialog is closed

**Comment by GermanBluefox** [comment]
I don't know how to fix and reproduce this error

**Comment by AlCalzone** [comment]
Here you go:
![grafik](https://user-images.githubusercontent.com/17641229/53391717-8d997480-3997-11e9-86dd-406defe8f6d2.png)

**Comment by AlCalzone** [comment]
@GermanBluefox You can fix it by adding a CSS definition:
```
.monaco-aria-container {
    top: 0;
}
```

**Comment by GermanBluefox** [comment]
In Firefox: 
![animation](https://user-images.githubusercontent.com/4582016/53414156-5d20fd00-39ce-11e9-8736-888b12a0cd9c.gif)

But I will add CSS

**Comment by GermanBluefox** [comment]
Done
