### ISSUE TITLE
Kein Javascript.0 unter Objekte

### ISSUE THREAD

**Issue by willhoh** [ioBroker/ioBroker.javascript#262]
Seit dem Update von 3.7.0 zu 4.0.5, wird das Objekt javascript.0 nicht mehr angezeigt. Es werden die Scripts auf nicht mehr ausgefügt wenn man z.B. über text2command diesen true übergibt. Kann ich irgendwie - zum Test - downgraden?

**Comment by willhoh** [comment]
Hab nun auch den Expertenmodus ausprobiert. Wenn dieser aktiv ist werden die Scripte angezeigt. Daraufhin hab ich danach gegoogled und gefunden, dass man diesen über die "Objekt bearbeiten">"Allgemein">expert ausschalten kann. Dann sieht man die auch im text2command. Würde es dennoch begrüßen es wie in v3.7.0 wieder zu haben.

**Comment by FRYYYYYY** [comment]
> Seit dem Update von 3.7.0 zu 4.0.5, wird das Objekt javascript.0 nicht mehr angezeigt. Es werden die Scripts auf nicht mehr ausgefügt wenn man z.B. über text2command diesen true übergibt. Kann ich irgendwie - zum Test - downgraden?

https://iot-blog.net/2018/08/24/iobroker-verwahrungsorte-und-adapterversionen/

Hier ist der Downgrade beschrieben ab 5:40

**Comment by FRYYYYYY** [comment]
Nee, bei mir auch nicht. M. E. ist das wie es jetzt ist aber nicht tragbar. Ich kann keine Scripte mehr per text2command auswählen. Ein downgrade auf die ältere javascript-version geht auch nicht. Änderungen an meinen Scripten funktionieren in Kombination mit text2command auch nicht, da text2command die alten Scripte aus javascript.0 ausliest.

Kann hier Jemand abhilfe schaffen?

**Comment by FRYYYYYY** [comment]
Lösch mal die Instanz, den Adapter und installiere ihn wieder. Dann baut er JavaScript.0 neu auf. 
Die von mir vorher nicht funktionierenden Änderungen merkt er nun wieder. 

Bleibt das Problem, dass alle Scripte unter JavaScript.0 nun das Experten-Flag gesetzt haben. 

Bei Text2command kann man den Pfad eingeben - dann klappt’s. 

Trotzdem noch ein bug.

**Comment by GermanBluefox** [comment]
Sollte mit der letzte JS version gefixt sein.
