### ISSUE TITLE
4.05 Update - Blockly Scripte nicht mehr darstellbar - Cannot extract Blockly code

### ISSUE THREAD

**Issue by Kandy84** [ioBroker/ioBroker.javascript#263]
Hallo zusammen,
nach dem Update auf Script Engine 4.05 sind all meine Scripte nicht mehr mit der Blockly Ansicht darstellbar, obwohl ich diese ursprünglich in Blockly erstellt habe.

Es erscheint die Fehlermeldung:
"Cannot extract Blockly code"

Leider habe ich in den bisherigen Issues keine Lösung gefunden.

Bitte im Hilfe

Hier mal ein ganz einfaches:
+++++++++++++++++++++++++
var Intervall;

Intervall = setInterval(function () {
  getState("rpi2.0.gpio.17.state", function (err, state) {
      setState("rpi2.0.gpio.17.state"/*GPIO 17*/, state ? !state.val : true);
  });
}, 1000);

//JTNDeG1sJTIweG1sbnMlM0QlMjJodHRwJTNBJTJGJTJGd3d3LnczLm9yZyUyRjE5OTklMkZ4aHRtbCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMnRpbWVvdXRzX3NldGludGVydmFsJTIyJTIwaWQlM0QlMjJaaGklMkNBRGl3UE9yTyU1QmslN0JDJTIzVDlKJTIyJTIweCUzRCUyMjE2MiUyMiUyMHklM0QlMjIxMzglMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJOQU1FJTIyJTNFSW50ZXJ2YWxsJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJJTlRFUlZBTCUyMiUzRTEwMDAlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMlVOSVQlMjIlM0VtcyUzQyUyRmZpZWxkJTNFJTNDc3RhdGVtZW50JTIwbmFtZSUzRCUyMlNUQVRFTUVOVCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMnRvZ2dsZSUyMiUyMGlkJTNEJTIyJTNEJTdELnp3di53TFBuNEZqV2k1UFMpJTIyJTNFJTNDbXV0YXRpb24lMjBkZWxheV9pbnB1dCUzRCUyMmZhbHNlJTIyJTNFJTNDJTJGbXV0YXRpb24lM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0VycGkyLjAuZ3Bpby4xNy5zdGF0ZSUzQyUyRmZpZWxkJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyV0lUSF9ERUxBWSUyMiUzRUZBTFNFJTNDJTJGZmllbGQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnN0YXRlbWVudCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGeG1sJTNF

+++++++++++++++++++++++++

**Comment by Kandy84** [comment]
Deat Community,
my issue  is gone :smile:

solution: delete adapter -> reboot -> install adapter 4.05 again
observed behavior during presence of the issue: Blockly -> Tigger blocks were not visible, others e.g. System or Action were!

Cheers Kandy84 and nice chistmas time :christmas_tree:

**Comment by FRYYYYYY** [comment]
Problem seit Version 4.0.7 wieder vorhanden. Erstes Blockly, welches geöffnet wird, schlägt fehl. Deinstallation und Neuinstallation brachten keine Veränderung.

Fehler:
![image](https://user-images.githubusercontent.com/13643787/50553506-6af52300-0ca8-11e9-8fbf-36bec20d9b41.png)

Im Anschluss leeres Script:
![image](https://user-images.githubusercontent.com/13643787/50553508-71839a80-0ca8-11e9-8c30-0029ef5cdf0b.png)

Nach "x" und nochmal öffnen ist das Script ordnungsgemäß geladen. Nach Refresh der Seite ist der Fehler sofort wieder vorhanden.
