### ISSUE TITLE
Text "Klicken Sie auf dieses Symbol X zum bearbeiten oder erstellen eines Skripts"

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.javascript#264]
Version 4.0.5 zeigt in Deutsch folgendes:
![image](https://user-images.githubusercontent.com/39859059/50376412-c8d09d80-060c-11e9-9e04-e24a2fec3228.png)

Stimmt so nicht ganz, da zur Erstellung eines neuen Scripts in der linken Symbolleiste auf "+" zu klicken ist. 
Folgende Anpassung wäre natürlich viiiieeel zu lang:
> Um ein neues Skript zu erstellen, in der linken Symbolleiste auf "+" klicken. Zum Bearbeiten eines bestehenden Skripts, dieses doppelklicken oder auf das Symbol "->" neben dem Skriptnamen klicken.

Vielleicht einfach ganz weglassen?

**Comment by GermanBluefox** [comment]
Es sollte sein "... oder erstellen Sie ein neues Skript"
