### ISSUE TITLE
V4.05: TypeError: fs.readdir is not a function

### ISSUE THREAD

**Issue by stmiko** [ioBroker/ioBroker.javascript#265]
From Update 3.6.4 to 4.0.5 I got an error when using the function fs.readdir.

See Topic in iobroker forum:
https://forum.iobroker.net/viewtopic.php?f=22&t=19504

The following error wwill be thrown in the log:
javascript.0	2018-12-13 14:37:00.009	error	at Timer.listOnTimeout (timers.js:290:5)
javascript.0	2018-12-13 14:37:00.009	error	at tryOnTimeout (timers.js:323:5)
javascript.0	2018-12-13 14:37:00.009	error	at ontimeout (timers.js:498:11)
javascript.0	2018-12-13 14:37:00.009	error	at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/schedule.js:501:7)
javascript.0	2018-12-13 14:37:00.009	error	at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/schedule.js:543:11
javascript.0	2018-12-13 14:37:00.009	error	at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/schedule.js:173:10)
javascript.0	2018-12-13 14:37:00.009	error	at Job.nodeSchedule.scheduleJob [as job] (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:920:34)
javascript.0	2018-12-13 14:37:00.009	error	at Object.<anonymous> (script.js.Produktiv.Foscam:346:9)
javascript.0	2018-12-13 14:37:00.009	error	at handleSnapshot (script.js.Produktiv.Foscam:92:12)
javascript.0	2018-12-13 14:37:00.008	error	Error in callback: TypeError: fs.readdir is not a function

Ich binde natürlich im Script "fs" mit ein (var fs = require('fs')).

**Comment by GermanBluefox** [comment]
Ja. Der Fehler ist bekannt und schon auf dem github. Dann werde ich
vielleicht heute oder morgen neue Version pushen.

вт, 25 дек. 2018 г., 12:56 stmiko notifications@github.com:

**Comment by stmiko** [comment]
Fehler war in der 4.0.7 gelöst, ist aber leider in der 4.0.11 wieder vorhanden!
