### ISSUE TITLE
Upgrade to latest version leads to empty screen in ioBroker

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.javascript#266]
I tried with firefox and chrome: After I upgraded javascript to 4.0.5, there was an empty screen in iobroker. No scripts where shown.
See also thread https://forum.iobroker.net/viewtopic.php?f=8&t=19945&p=208541#p208541
After i downgraded to the latest stable version, I could see my scripts again.

Regards Ralf

**Comment by GermanBluefox** [comment]
Can you next time check the errors in browser console?

вт, 25 дек. 2018 г. в 22:07, derrapf <notifications@github.com>:

**Comment by derrapf** [comment]
Can you give me a short description how to do that?
Can't you reproduce that issue?

**Comment by Apollon77** [comment]
Depending on your browser there should some "Web Developer Tools" in the menus of the browser and there you find the Console.
Other options are:
* do "iobroker upload javascript"
* force reload your browser or kill the browser cache

**Comment by derrapf** [comment]
Hi Ingo
How urgently do you need those logs? Because currently I am pretty happy that iobroker runs again. I would rather not like to update it and have issues again.
Regards Ralf

**Comment by GermanBluefox** [comment]
No investigation possible, so closed
