### ISSUE TITLE
keine Hochkommata in Version 4.0.6

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.javascript#267]
Ich bekomme eine Fehlermeldung, wenn ich ein simplen CRON Trigger mit Blockly anlege

Post von paul53 dazu aus dem IOBroker Forum

 javascript.0 2018-12-26 15:30:26.869 error schedule(0 12 * * *, function () {

Während in den Vorgängerversionen (4.0.x) doppelte Hochkommata erzeugt wurden, fehlen jetzt die Hochkommata komplett. Da muss wohl @Bluefox noch mal ran.

[https://forum.iobroker.net/viewtopic.php?f=20&t=19981](url)

**Comment by liv-in-sky** [comment]
ich habe die selben probleme wie ihavenonick

**Comment by ihavenonick** [comment]
mach ein Downgrade auf 3.6.4 bis das gefixt ist

**Comment by liv-in-sky** [comment]
der fehler tritt nur auf, wenn man einen trigger einrichtet oder einen bestehenden ändert -  das kann ich aber mal für eine woche aussetzen - die alten scripts laufen ja alle - glaubst du das dauert längere zeit um dies zu fixen?

**Comment by Apollon77** [comment]
Sind alle diese Dinge als issues hier gemeldet?

**Comment by liv-in-sky** [comment]
vielen dank 

ich lass mal- falls ich in den nächsten tagen etwas ändern muss, kann ich immer noch umstellen - bei mir lauft der adapter schneller  - ist mir lieber als der alte

**Comment by liv-in-sky** [comment]
@Apollon77 
das blockly problem mit dem iot adapter - wo muss ich das den melden - ist das ein js-adapter problem? ich glaube ich habe es im iot adapter gemeldet

**Comment by ihavenonick** [comment]
@Apollon77 
Also was die Optik Sache betrifft gibts ein Issues #244 mit Bild

**Comment by JoJ123** [comment]
@Apollon77 
This should be the same issue:
https://github.com/ioBroker/ioBroker.javascript/issues/242

**Comment by Smarti15** [comment]
Ein Downgrad funktoniert lieder nicht über die ioBroker Oberfläche. Kann ich irgendwie per Linuxbefehle die 3.6.4 installieren?

**Comment by StrayDog2205** [comment]
Hier ein Workaround bis das Problem gefixt ist.
Damit ein ein Downgrade nicht nötig.

![grafik](https://user-images.githubusercontent.com/45132233/50537202-2f017700-0b5d-11e9-9941-b91e32499c0e.png)

**Comment by liv-in-sky** [comment]
super tipp  danke

**Comment by GermanBluefox** [comment]
Muss jetzt gefixt sein.
