### ISSUE TITLE
4.0.6: Move script into another folder

### ISSUE THREAD

**Issue by IO-Link** [ioBroker/ioBroker.javascript#269]
Within 4.0.6 it is not possible to move a script into another folder. There is no function, button, menue or something like that.

**Comment by FRYYYYYY** [comment]
Yes, it’s missing while editing the name of a script.

**Comment by RK62** [comment]
Realy a bug? On my installation 4.0.6 there ist a button to reanrrange scripts:
![2018-12-31 11_40_50-javascript - iobroker-esk01](https://user-images.githubusercontent.com/39200469/50558777-348fc600-0cf1-11e9-8501-57b2fea4db86.png)

**Comment by FRYYYYYY** [comment]
Yes, you are right... but I think it was easier before... before you were able to move scripts while editing its name. I do have a lot of scripts and this is much more confusing :-)

**Comment by FRYYYYYY** [comment]
+ It's not possible to move folders.

**Comment by IO-Link** [comment]
> Realy a bug? On my installation 4.0.6 there ist a button to rearrange scripts:
> ![2018-12-31 11_40_50-javascript - iobroker-esk01](https://user-images.githubusercontent.com/39200469/50558777-348fc600-0cf1-11e9-8501-57b2fea4db86.png)

ok - you're right. Didn't recognized, that that icon can be even used to move scripts to another folder. I'll close that issue
