### ISSUE TITLE
Unsubscribe funktioniert nicht, wenn Adapter auf "Nicht auf alle Zustände beim Start abonnieren" konfiguriert ist

### ISSUE THREAD

**Issue by thovid** [ioBroker/ioBroker.javascript#27]
Wenn der javascript Adapter auf "nicht auf alle Zustände beim Start abonnieren" konfiguriert ist, führt der Aufruf von unsubscribe() mit einer handler-Instanz zu einem TypeError.

Fehler aus Log:

```
at sandbox.unsubscribe (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:1409:29)
at unsubscribePattern (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:684:34)
TypeError: Cannot read property 'undefined' of undefined
uncaught exception: Cannot read property 'undefined' of undefined
```

Ist die obige Konfiguration nicht gesetzt, tritt der Fehler nicht auf.
Mit folgendem Test-Skript kann ich den Fehler zuverlässig reproduzieren:

```
createState("test1", false, true)
var sub = on("test1", function(obj) {
    unsubscribe(sub)
})

setStateDelayed("test1", true, 1000)
```

Ich verwende die Version 3.3.6 der js Engine.

**Comment by Apollon77** [comment]
@GermanBluefox Im Code wird hier auf script.subscribes zugegriffen. Kann es sein das sandbox.script.subscribes sinnvoller/nötig ist? Ist aber nur Vermutung

**Comment by softice24** [comment]
once({ id: "test" }) bringt bei obiger Konfiguration den selben Fehler.
Tut sich hier noch was, oder gibt es einen "Work arround"?
