### ISSUE TITLE
4.0.6: Scripte unter javascript.0 haben Expert-Flag

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#272]
Die Scripte unter javascript.0 haben nun standardmäßig das Expert-Flag gesetzt. 

Problem hier:
1. Text2Command sieht das Script nicht mehr
2. Blockly sieht das Script nicht mehr

Bei 1. kann ich mir mit dem Pfad helfen. Bei 2. nicht, da Blockly. 

Expert-Flag ausschalten ist keine Option, da dann von normalen Scripten die Zeilenumbrüche verschwinden und das Script in einer Zeile angezeigt wird im Editor (auch ein Bug?)

**Comment by msiemers** [comment]
Das gleiche Problem habe ich auch festgestellt. In Blockly kann man den Expertenmodus aber noch aktivieren. In Text2Command geht das definitiv nicht. Ich gehe hier auch con einem Bug aus.
![2018-12-29 00_04_56-javascript - iobroker](https://user-images.githubusercontent.com/34999079/50530431-a0a9d880-0afd-11e9-85a8-554b09c1ef7f.png)

**Comment by AlCalzone** [comment]
Ob es jetzt ein Bug ist oder nicht:  
Die empfohlene/gewollte Variante eine Script-Aktion zu triggern ist es immer laufen zu haben und darin mit einem Trigger auf einen State zu lauschen. Direktes Benutzen von `scriptEnabled` sollte ein Ausnahmefall bleiben. Warum es scheinbar überall benutzt wird, ist mir ein Rätsel.

**Comment by msiemers** [comment]
Wenn ich aber zum Beispiel in Text2Command ein Script auswählen möchte, wird dieses nicht angezeigt. Hier kann ich nur eine Auswahl treffen.

**Comment by AlCalzone** [comment]
Siehe mein Post im Forum. Scripte sind nicht dazu gedacht, ständig gestoppt und gestartet zu werden. Lass deine Skripte dauerhaft laufen, lass sie auf einen Trigger-Datenpunkt lauschen und beschreibe diesen Datenpunkt mit Text2Command.

**Comment by FRYYYYYY** [comment]
Grundsätzlich verstehe ich es, ist m. E. aber einfach viel mehr Aufwand, als einfach ein Script mit true zu starten. Ich denke für viele ist es einfacher einfach nur die Scripte zu starten/stoppen als für alle Scripte noch Datenpunkte einzurichten.

**Comment by AlCalzone** [comment]
Mag sein, das war aber nie so gedacht und hat in der Vergangenheit schon oft zu problemen geführt. Scriptenabled ist schlicht und einfach ein interner Ordner des js Adapters und war nie offiziell dokumentiert bzw unterstützt.

Der zusätzliche Aufwand ist ein createState block und ein trigger pro Skript, das ist ne sache von 20/30 Sekunden.

**Comment by FRYYYYYY** [comment]
Guter Hinweis. Gibt es jemanden, der createstate mit Blockly (Zustand erzeugen) erfolgreich einsetzt? Mir fehlt die Idee, wie es funktioniert.

**Comment by RK62** [comment]
In der Anlage ein Muster für den CreateState in BLOCKLY.
Unter den "..." bei der Funktion Create State können die benötigten States hinterlegt werden.
[CreateState.txt](https://github.com/ioBroker/ioBroker.javascript/files/2718231/CreateState.txt)

**Comment by FRYYYYYY** [comment]
Danke... aber zunächst auch sorry, vllt. steh ich auf dem Schlauch. Kannst du einen Screenshot des Blockly Codes mit hochladen? Oder soll man es mit Scripts importieren importieren können? Das geht irgendwie nicht, da nach Klick auf Scripts importieren einfach gar nichts passiert...

**Comment by DanielWeeber** [comment]
Neuen Datenpunkt erstellen (z.B. custom.0.scripts.mein_script; boolean).
>on({id:` "custom.0.scripts.mein_script", val:true}, function (obj) {
>    log("Script ist gestartet");
>    setState("custom.0.scripts.mein_script", true, true);
>    //hier tolle Sachen machen
>    setState("custom.0.scripts.mein_script", false);
>});

**Comment by FRYYYYYY** [comment]
Danke.. und per Blockly? :-)

**Comment by AlCalzone** [comment]
Schauen wir doch mal in die [Doku](https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/de/blockly.md#create-state):
![unbenannt](https://user-images.githubusercontent.com/17641229/50599710-24bde080-0eaf-11e9-8bbf-3fb6eab7a8aa.PNG)

**Comment by FRYYYYYY** [comment]
Super, danke. Hatte ich wohl übersehen. Frohes neues!

**Comment by FRYYYYYY** [comment]
Die Idee ist im Grunde nicht schlecht, für text2command aber tatsächlich nicht umsetzbar. Ich habe bei text2command z. B. ein Befehl, der im Wechsel einen Wert auf true oder false setzt. Also z. B. klassisches Ein- und Ausschalten einer Lampe.

Wenn an, dann aus
Wenn aus, dann an

Bei Text2Command als Wert, der geschrieben wird "true" auf den Start des Scripts, welches das obige abfragt und dann wieder stoppt.

Mit createState ist das m. E. nicht umsetzbar, da ich ja immer nur ein true per text2command schreiben lasse und ein Trigger hier auf "false" gar nicht reagieren würde.

So würde ich also hier 2x createState machen müssen:
1. text2command schreibt und aktualisiert einfach den Wert mit z. B. true
2. Wenn der erste Zustand aktualisiert wird, setze den zweiten Wert auf true wenn false und false wenn true.

Vllt. habe ich auch einen Denkfehler, aber mir scheint der Aufwand 2er createStates ggü. des Start/Stopps eines Scripts aufwendiger als auch zeichenintensiver.

Gerne nehme ich Tipps entgegen :-)

**Comment by DanielWeeber** [comment]
Das Blockly war ja auch nur ein Beispiel. Das createState braucht nur einmalig ausgeführt werden.
Ich kenne text2command nicht, aber mit Javascript (also auch Blockly) ist das alles locker umsetzbar.

Blödes Beispiel:

setState(object, (getState(object).val == true?false:true));

**Comment by AlCalzone** [comment]
> Die Idee ist im Grunde nicht schlecht, für text2command aber tatsächlich nicht umsetzbar. Ich habe bei text2command z. B. ein Befehl, der im Wechsel einen Wert auf true oder false setzt. Also z. B. klassisches Ein- und Ausschalten einer Lampe.
> 
> Wenn an, dann aus
> Wenn aus, dann an

Verstehe ich dich richtig? Du schreibst mit text2command immer true in einen bestimmten Datenpunkt und dein Skript soll dann einen anderen Datenpunkt von true auf false und umgekehrt umschalten?

Dann geht das einwandfrei:
![unbenannt](https://user-images.githubusercontent.com/17641229/50733683-4dd1c000-1192-11e9-9044-bc20a0132125.PNG)

**Comment by FRYYYYYY** [comment]
Erst einmal Danke für deine ganze Mühe! Ein guter Ansatz! :-) das merke ich mir. 

Per Text2Command schreibe ich aktuell halt ein „true“ auf das Script, damit es ausgeführt wird. Dieses Script wechselt bei jeder Ausführung den Status eines Datenpunkts von true/false.

Ich schau mal, wie ich es am besten umsetze :-)

**Comment by AlCalzone** [comment]
Ok dann funktioniert mein Skript so wie es soll. Du musst dann halt den triggerstate beschreiben anstatt Scriptenabled

**Comment by FRYYYYYY** [comment]
Danke! Habe alle Scripte geändert, jetzt nur noch trigger! :-)
Kann geschlossen werden!
