### ISSUE TITLE
4.0.6: Trigger Zeitplan sofort Fehler und funktioniert nicht

### ISSUE THREAD

**Issue by Sn4k3E4t3r** [ioBroker/ioBroker.javascript#273]
Hallo zusammen,

heute testweise einen neuen ioBroker aufgesetzt und javascript 4.0.6 installiert. Neues Script Blockly angelegt und gespeichert (ohne Inhalt). Das Script editiert und einen Zeitplan Objekt eingezogen. Speichern: Fehler kommen sofort im Log und im Log von Javascript.
![javascript4 0 6_1](https://user-images.githubusercontent.com/46231040/50530467-144be580-0afe-11e9-98b2-2ed1336f453e.PNG)
![javascript4 0 6_2](https://user-images.githubusercontent.com/46231040/50530468-144be580-0afe-11e9-98f9-dba0c740eed0.PNG)

**Comment by AlCalzone** [comment]
Duplicate of #267 

Das Problem ist bekannt. Die Lösung besteht momentan darin, eine ältere Version des Adapters zu verwenden.

**Comment by FRYYYYYY** [comment]
Die Lösung von @Sn4k3E4t3r funktioniert. Danke für den Workaround.

**Comment by AlCalzone** [comment]
Habe auch gelesen dass es mit 4.0.7 inzwischen geht.

**Comment by FRYYYYYY** [comment]
Ja, scheint behoben zu sein!
