### ISSUE TITLE
4.06 Debug Modus lässt sich nicht ein-/ausschalten

### ISSUE THREAD

**Issue by msiemers** [ioBroker/ioBroker.javascript#274]
Ich hatte gerade das Problem, das ich unter Blockly in der Version 3.6.4 bei einem Script über einen Klick den DebugModus eingeschaltet hatte. Nachdem ich dann auf die aktuelle Version 4.06 gewechselt bin, hatte ich in Blockly keine Möglichekeit mehr den Debug Modus wieder mit einem Klick in die Schaltfläche zu entfernen.

**Comment by GermanBluefox** [comment]
Da debug Modus beinah nie verwendet war, habe ich das erstmal von der Oberfläche aufgeräumt.
Man kann über ObjektEditor das wieder deaktivieren:
![image](https://user-images.githubusercontent.com/4582016/53352154-913ee400-3922-11e9-83d5-f93044f5ca10.png)


![image](https://user-images.githubusercontent.com/4582016/53352093-79676000-3922-11e9-8797-0540fd799cd9.png)

**Comment by Ilovegym66** [comment]
die Lösung find ich gut, oft brauch ich den nicht, aber sollte vorhanden sein...
