### ISSUE TITLE
Stop block fehler script engine 4.05

### ISSUE THREAD

**Issue by rogni38** [ioBroker/ioBroker.javascript#275]
Wenn ein stop block in blockly integriert ist, kommt „can not extrakt blockly code“ und die instanz wird gestoppt.
Siehe: 
https://forum.iobroker.net/viewtopic.php?f=21&t=20082

**Comment by FRYYYYYY** [comment]
Das habe ich sogar jedes Mal, wenn ich die Scripte Sektion öffne:

![image](https://user-images.githubusercontent.com/13643787/50560878-57c47080-0d05-11e9-9cf7-29092b30b443.png)

Danach sieht der Code wie folgt aus:

![image](https://user-images.githubusercontent.com/13643787/50560887-66ab2300-0d05-11e9-8bc4-d324fc87da46.png)

**Comment by GermanBluefox** [comment]
Kann mit 4.1.0 nicht reproduzieren
