### ISSUE TITLE
"clear running" in UPDATE-Blocks has no effect

### ISSUE THREAD

**Issue by fabian-barney** [ioBroker/ioBroker.javascript#277]
This issue has already been reported and fixed in the past. (see #105 )
At least with iobroker-javascript 3.6.4 it is an issue again and does not work.

The generated Javascript is the same regardless "clear running" is checked or unchecked.

**Comment by BuZZy1337** [comment]
I cannot reproduce this issue..?

![image](https://user-images.githubusercontent.com/6979405/50573067-02ec2d00-0dcd-11e9-9b3c-ffcc277bdcd0.png)
Generated JS Code:
```js
setStateDelayed("Object ID", true, 1000, false);
```

![image](https://user-images.githubusercontent.com/6979405/50573083-27480980-0dcd-11e9-8f8e-a24c204d63f3.png)
Generated JS Code:
```js
setStateDelayed("Object ID", true, 1000, true);
```

**Comment by fabian-barney** [comment]
For CONTROL-Blocks it works. It does not work for UPDATE-Blocks.

**Comment by GermanBluefox** [comment]
Cannot reproduce error:

![image](https://user-images.githubusercontent.com/4582016/53353938-137cd780-3926-11e9-93ba-5612cd3429b8.png)
=>
```setStateDelayed("admin.0.info.lastUpdateCheck"/*Timestamp of last update check*/, 0, true, 1000, false);```




![image](https://user-images.githubusercontent.com/4582016/53354005-30190f80-3926-11e9-8360-b58cb84db75a.png)
=>
```setStateDelayed("admin.0.info.lastUpdateCheck"/*Timestamp of last update check*/, 0, true, 1000, true);```
