### ISSUE TITLE
getAstroDate() doesn't know 'night' and 'nightEnd' anymore?!?

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.javascript#28]
Something has recently changed to the astro functions as the following script doesn't return valid times for "night" and "nightEnd" anymore:

```
var night = getAstroDate("night");
var nightEnd = getAstroDate("nightEnd");
log("night starts today at " + night.toLocaleTimeString());
log("night ends today at " + nightEnd.toLocaleTimeString());
```

Result is:

```
09:28:29.783	[info]	javascript.0 script.js.Licht.Lichtsteuerung: night starts today at Invalid Date
09:28:29.783	[info]	javascript.0 script.js.Licht.Lichtsteuerung: night ends today at Invalid Date
```

This is with the latest version of ioBroker.javascript (v3.3.8)

**Comment by GermanBluefox** [comment]
It was changed nothing in the last versions concerning astro.

Except longer days... Are you in the near of north pole?

**Comment by jens-maus** [comment]
Nope, dresden is definitly not at the north pole ;)

**Comment by jens-maus** [comment]
Please note, I just checked the 'suncalc' nodejs module you are using and found the following:

```
> var suncalc = require('suncalc');
> suncalc.getTimes(new Date(), 51.05, 13.73);
{ solarNoon: Fri May 26 2017 13:03:35 GMT+0200 (CEST),
  nadir: Fri May 26 2017 01:03:35 GMT+0200 (CEST),
  sunrise: Fri May 26 2017 05:02:41 GMT+0200 (CEST),
  sunset: Fri May 26 2017 21:04:29 GMT+0200 (CEST),
  sunriseEnd: Fri May 26 2017 05:06:52 GMT+0200 (CEST),
  sunsetStart: Fri May 26 2017 21:00:18 GMT+0200 (CEST),
  dawn: Fri May 26 2017 04:19:20 GMT+0200 (CEST),
  dusk: Fri May 26 2017 21:47:51 GMT+0200 (CEST),
  nauticalDawn: Fri May 26 2017 03:17:51 GMT+0200 (CEST),
  nauticalDusk: Fri May 26 2017 22:49:19 GMT+0200 (CEST),
  nightEnd: Invalid Date,
  night: Invalid Date,
  goldenHourEnd: Fri May 26 2017 05:53:40 GMT+0200 (CEST),
  goldenHour: Fri May 26 2017 20:13:30 GMT+0200 (CEST) }
```

So it seems the 'suncalc' nodejs module have to be blamed somewhat.

**Comment by jens-maus** [comment]
Please also note that as soon as you change the coordinates to, e.g. `50.05, 13.73` suncalc is able to calculate the night and nightEnd times.

**Comment by jens-maus** [comment]
After some more investigation I found out that night/nightEnd can be indeed NaN/Invalid Date (which I didn't know). Please see here:

https://github.com/mourner/suncalc/issues/70

Thus, it seems to be normal that at summer times there can be areas even within central Europe where there is no official night and thus no nightEnd. So sorry for all the fuzz, but I think this should at least be documented in our astro function documentation.

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.javascript/commit/c682b52a91acfb67f89127865dfcc679b418588b

**Comment by mgossmann** [comment]
Although I do understand why this is happening, the error handling in the java script adapter is kinda unfortunate. It gets the iobroker log flooded with error messages. To be frank I'm not overly fond of disabling the adapter logging to cope with it.

Since this is not supposed to be an error at all Is there any other way to handle this just as a warning or even less? A solution here would be really really great because it will come back every year. At least for some of us :-)

The only thing I'm not getting is I can't recall having this problem last year and I did not move. 
kinda weird.
