### ISSUE TITLE
4.0.7 Scripts importieren geht nicht

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.javascript#280]
Beim klick auf die drei Punkte und dann "Scripts importieren" passiert nichts.

**Comment by homecineplexx** [comment]
Ziemlich störend

**Comment by Brainbug01** [comment]
Auch mit 4.0.11 ist nichts passiert das es geht.

**Comment by dimaiv7** [comment]
Auch mit 4.0.12 ist nichts passiert, das es geht.

**Comment by AlCalzone** [comment]
Danke, wir brauchen keine Erinnerung
