### ISSUE TITLE
4.0.5 - 4.0.7 Filterfunktion unter Objekt-ID einfügen hat Fehler

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.javascript#281]
Wenn man in einem Script das Objekt-ID einfügen klickt und im Anschluss die Filterfunktion "Name" nutzt um bspw. Hm-Geräte zu durchsuchen werden diese komplett ausgeblendet und nur noch die Javascript Instanz durchsucht.

**Comment by GermanBluefox** [comment]
Kannst du screenshot zeigen? Es ist nicht klar was gemeint ist.

**Comment by Rantanplan01** [comment]
#338
