### ISSUE TITLE
4.0.7: Zeitplan fehlerhaftes Verhalten

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#282]
Ich hätte einen BUG, wenn man als Trigger den Zeitplan nimmt und diesen auf: "jedes Jahr auf 1 von Januar um 23:59" stellt, wird er jeden Tag ausgeführt. 
So sollte es doch nur am 31.12 um 32.59Uhr auslösen?
Hier die Einstellungen:

![unbenannt](https://user-images.githubusercontent.com/38273154/50702694-f9bfc200-1051-11e9-95b3-66f6eebe95a9.png)

**Comment by Rantanplan01** [comment]
Fehler kann ich bestätigen.
Habe ich mit der v4.1.6 nachgestellt.

Bestimmte Zeit: 23:59
Zeitraum: Jährlich / Jedes Jahr am 1 Januar

Der Trigger löst **jeden** Tag um 23:59 aus

**Comment by GermanBluefox** [comment]
Please test with 4.1.9 (And do not wait till 31 Dec, try something like tomorrow)
