### ISSUE TITLE
Deleted, but open scripts stay in the tab view

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#283]
![unbenannt](https://user-images.githubusercontent.com/17641229/50733752-ee74af80-1193-11e9-8930-94538d934b37.PNG)
See screenshot - deleted scripts should vanish from the tab view.

**Comment by GermanBluefox** [comment]
Should be fixed now with 4.1.4

**Comment by AlCalzone** [comment]
Nope, still there (4.1.5):
![ezgif com-crop 1](https://user-images.githubusercontent.com/17641229/53393648-36969e00-399d-11e9-9dcc-f707e616e7ae.gif)

**Comment by GermanBluefox** [comment]
Ok. Will fix. Thank you

**Comment by GermanBluefox** [comment]
Please reopen if still there
