### ISSUE TITLE
Values bei der Objektauswahl sichtbar machen

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.javascript#285]
Wenn man im Blockly die Values und nicht bloß die Objektstruktur bei der Auswahl sehen könnte, wäre das meines Erachtens extrem hilfreich.
So könnte ich direkt auf den Datentyp schließen (boolean/string/integer) außerdem bei booleans den aktuellen Wert direkt sehen, ohne in der Ansicht immer zwischen Skripte und Objekte hin- und herspringen zu müssen.

**Comment by GermanBluefox** [comment]
Done in 4.1.6

**Comment by passuff** [comment]
Thx
