### ISSUE TITLE
setBinaryState is missing

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.javascript#286]
setBinaryState is missing in javascript adapter!!

**Comment by Apollon77** [comment]
and I assume getBinaryState too? :-)

**Comment by GermanBluefox** [comment]
> and I assume getBinaryState too? :-)

yes. Will fix tonight.

**Comment by AlCalzone** [comment]
Fixed, isn't it?

**Comment by homecineplexx** [comment]
Yes it's fixed and work correct.

**Comment by homecineplexx** [comment]
Yes it's fixed and work correct.
