### ISSUE TITLE
Script wird mehrfach getriggert bei Aktualisierung

### ISSUE THREAD

**Issue by ingod68** [ioBroker/ioBroker.javascript#288]
Bei "falls Objekt wurde aktualisiert" in Blockly 
bzw bei "on...change: any" in Javascript 
wird das Script mehrfach getriggert wenn der Datenpunkt aktualisiert wurde.

**Comment by AlCalzone** [comment]
Zufällig 1x mit bestätigt = falsch und 1x mit bestätigt = wahr?

**Comment by ingod68** [comment]
Nein, passiert wenn ich den Datenpunkt manuell bei den Objekten ändere/aktualisiere aber auch wenn der über den Schalter in der Vis oder per Echo aktualisiert wird. Script wird dann 2-3 mal getriggert. 
Habe das jetzt erstmal durch eine Entprellung im Script beheben können.

https://forum.iobroker.net/viewtopic.php?f=21&t=20942

**Comment by GermanBluefox** [comment]
Es kann sein, dass 3 javascript instances laufen. Man muss ```ps -A  | grep io``` schauen
