### ISSUE TITLE
exec funktioniert nicht bei shell script 

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#292]
Exec ansich funktioniert - es wird jeder Befehl - ob reboot oder sonstiges ausgeführt.
Sobald ich aber ein .sh Script ausführen will passiert nichts. Und egal in welcher Kombination. Ob
- mit sudo oder ohne
- mit ./ oder ohne
- volle Pfadangabe oder nicht

Ja, das Script ist ausführbar :-)

Führe ich den Befehl auf der Shell aus, funktioniert es.
Führe ich das Script auf der Shell aus, funktioniert es.

Nur keine Chance über den JavaScript Adapter. 

Da ich einige Foreneinträge gelesen habe vermute ich, dass es sich hier ggf um einen Bug handelt.

Siehe Forum: https://forum.iobroker.net/viewtopic.php?t=12449

Eine Debug-Ausgabe ergibt leider nichts - sie ist leer.

Es macht keinen Unterschied ob Blockly oder JavaScript direkt.

**Comment by Apollon77** [comment]
Hast Du versucht "bash meinskrip.js" auszuführen? Das Skript braucht jaggf einen Interpreter

**Comment by FRYYYYYY** [comment]
Soeben versucht - funktioniert auch beides leider nicht.

**Comment by AlCalzone** [comment]
In welchem Ordner liegt das Skript? Hat der User `iobroker` Lese/Ausführ-Berechtigungen?

**Comment by FRYYYYYY** [comment]
Das liegt wahlweise im /root, im /home/pi, eigentlich egal. Meine Javascript-Instanz führt sich als root aus, ausführbar ist die Datei. Der Kollege im Forum schildert exakt das Phänomen, was ich auch habe.
Berechtigung ist:
-rwxr-xr-x
Owner, group: pi & pi

**Comment by AlCalzone** [comment]
> Meine Javascript-Instanz führt sich als root aus

Sicher? Neuere Installationen laufen unter dem user `iobroker`, der weder auf /root, noch /home/pi zugreifen kann.

**Comment by FRYYYYYY** [comment]
Wahnsinn. Stimmt! Läuft als iobroker user. auf /home/iobroker hat der User die Rechte.
Danke! Solved!
