### ISSUE TITLE
Instanz ist deaktiviert

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.javascript#293]
Moin, bei mir werden mit der Version 4.0.11 die Javascripte nicht mehr ausgeführt.
Im Editor wenn ich ein Script aufmache steht dann Instanz ist deaktiviert. Die Instanz läuft aber auch werden keinerlei Fehler geschmissen. Bin jetzt erstmal wieder auf die Version 4.0.7 zurück dort geht alles.

https://forum.iobroker.net/viewtopic.php?f=20&t=21052&p=220935

**Comment by GermanBluefox** [comment]
Besteht das Problem immer noch?

**Comment by vr6syncro** [comment]
aktuell scheint es nicht mehr da zu sein. alles auf latest außer js-controller (ist auf 1.42)

**Comment by benziman88** [comment]
Bei mir läuft v 4.1.12, Skripte werden nicht ausgeführt. Beim öffnen des Skriptes wird mir angezeigt Instanz ist deaktiviert.
