### ISSUE TITLE
4.0.12 breaks external module uses (again)

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.javascript#295]
I just updated from version 4.0.11  to version 4.0.12 of ioBroker.javascript and my ioBroker instance outputs various error pointing at my own scripts where I use certain third-party modules which it cannot find anymore:

```
javascript.0	2019-01-21 10:53:48.033	error	script.js.vis-Scripts.dvbjs: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/lib/../../dvbjs'
```

This error says that the "dvbjs" node modules is missing in `/opt/iobroker/node_modules/iobroker.javascript/lib/../../dvbjs` however, I can perfectly find it in `/opt/iobroker/node_modules/iobroker.javascript/node_modules/dvbjs` which is obviously a completely different place.

After downgrade to 4.0.11 it however doesn't work anymore again. Has 4.0.12 moved the node modules somehow?!?!

**Comment by AlCalzone** [comment]
How are you importing the module? With a relative path (`"../../dvbjs"`)? I can't imagine why there are two leading `"../"` otherwise

**Comment by AlCalzone** [comment]
If so, you should use `require("dvbjs")` without any relative path segements.

**Comment by jens-maus** [comment]
I am of course doing this:
```
const dvb = require('dvbjs'); 
```

However, looking at the `/opt/iobroker/node_modules/iobroker.javascript/node_modules` directory I see the following:

```
dvbjs -> ../../../../../home/damato/projekte/linux/dvbjs/
```

How come that this suddenly references outside /opt/iobroker? I don't know if this was previously the case but to me this seems to be wrong (This directory is my development directory of dvbjs).

**Comment by jens-maus** [comment]
... and everytime I restart this dvbjs link (as well as another link to another nodes project I also develop for) is recreated... Why is ioBroker.javascript node correctly grabbing from nom here but creating links to my development directories?!?! Don't get why.

**Comment by AlCalzone** [comment]
Maybe you did a local install or npm linked it somehow? This seems to be related to some npm configuration as the JS adapter only uses the normal require

**Comment by jens-maus** [comment]
doing a manual "npm list" outputs the following regarding dvbjs

```
npm ERR! missing: dvbjs@file:../../../../home/damato/projekte/linux/dvbjs, required by iobroker.javascript@4.0.12
npm ERR! extraneous: dvbjs-root@ /opt/iobroker/node_modules/iobroker.javascript/node_modules/dvbjs
[...]
│ ├── UNMET DEPENDENCY dvbjs@file:../../../../home/damato/projekte/linux/dvbjs
│ ├── dvbjs-root@ -> /home/damato/projekte/linux/dvbjs extraneous
```

Never seen this and I don't know how this happened? Before upgrading to 4.0.12 everything was working fine...

**Comment by jens-maus** [comment]
.. after some more investigation I found that in my `/opt/iobroker/node_modules/iobroker.javascript/package.json` there were "dvbjs" entries in the "dependencies" sections which link to a local directory path rather than a `^X.X.X` version. After having removed these entries and clearing `/opt/iobroker/node_modules/iobroker.javascript/node_modules` the 4.0.12 adapter version started to work fine again. However, I really don't know how these entries were added to the `package.json` file in first place?!?!

**Comment by AlCalzone** [comment]
If iobroker is running on your dev machine, I expect a misplaced `npm install dvbjs` or something weird like `npm link`

**Comment by AlCalzone** [comment]
So can we close this? @jens-maus

**Comment by jens-maus** [comment]
Yep, however, I still don't know how this actually happened. But I solved it myself now like I explained above.

**Comment by AlCalzone** [comment]
Daamn that was fast :laughing:
