### ISSUE TITLE
Mutihost update auf 2ter Instanz funkt scheinbar nicht

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.javascript#296]
Hallo 
Ich habe ein Multihostsystem 
Master:RPI3B+
Slave1: RPI3B+
Slave2 RPI3B+

auf Master und Slave1 hab ich jeweils eine Javascript Instanz am laufen (Version 4.0.11)
Jetzt hab ich über die AdapterMaske ein update auf 4.0.12 gemacht, allerdings wurde scheinbar nur die Master Instanz auf 4.0.12 gebracht und die SLave1 Instanz nicht.

Sieht man im Log wenn man einen Restart der beiden Instanzen macht.
javascript.1 | 2019-01-23 19:36:49.850 | info | starting. Version 4.0.11 in /opt/iobroker/node_modules/iobroker.javascript, node: v8.14.0

javascript.1 | 2019-01-23 19:36:49.850 | info | starting. Version 4.0.11 in /opt/iobroker/node_modules/iobroker.javascript, node: v8.14.0

Was tun?

**Comment by Apollon77** [comment]
Bitte in Admin unter Adapter oben den Sölave auswählen. Dann sollte das Update nochmal verfügbar sein. Adapter Seite zeigt die aktuellen Versionen nach dem oben gewählten Host an.

**Comment by homecineplexx** [comment]
So einfach kann die Lösung oft sein...dankeschön
