### ISSUE TITLE
exec funktioniert nicht bei ssh Befehl

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.javascript#297]
Ich habe ein Script erstellt um per ssh Befehl mit von einem anderen Rechner einen Wert (temperatur) auszulesen.
per Konsole funktioniert dies einwandfrei und public / private key wurden übermittelt.

mache ich dies per Script kommt immer folgender Fehler:

`script.js.UserDefined.Tests.Skript1: Permission denied, please try again`

oder dieser hier

`script.js.UserDefined.Tests.Skript1: Permission denied (publickey)`

**Comment by AlCalzone** [comment]
> Permission denied (publickey)

Wenn du relativ frisch installiert hast, läuft ioBroker unter dem User `iobroker`, nicht deinem eigenen.
D.h. die SSH-Keys müssen also für diesen User hinterlegt werden, damit die Authentifizierung funktioniert.

Mit `node-ssh` solltest du die ganze Authentifizierung aber auch komplett im Skript durchführen können.

**Comment by Locke** [comment]
Gerade die zweite Meldung klingt als ob der ioBroker Prozess den private Key nicht findet.

Mit den "verbose" flags wird SSH mitteilsamer und sollte ausgeben an welchen Stellen nach dem private Key gesucht wird. Versuche es mal mit `ssh -v otherHost ...` oder `ssh -vv otherHost ...`

**Comment by Seqway** [comment]
Das ist genau das wo ich scheitere, denn ich benutze die Oberfläche mit admin (Standardeinstellung) aber anscheinend wird der Benutzer iobroker benutzt bei dem Absetzen der Befehle.

Ich komme noch nicht einmal mit dem user iobroker per ssh auf den Rechner, deswegen kann ich auch keinen key generieren. Da der user iobroker anscheinend vom Installationsprozess angelegt wird, weiss ich grad nciht weiter wie ich das anstellen soll ?

**Comment by Seqway** [comment]
Auf dem entfernten System ist der user iobroker natürlich auch nciht "installiert".

aber der user root sowie meinusername --> diese sind auf beiden Systemen bekannt.
Muss ich den user iobroker auch auf dem entfernten System anlegen ? Wenn ja wie und mit welchen Rechten, da dies ja von dem Installationsprozess gemacht wird ?

**Comment by AlCalzone** [comment]
Ich würde ja vermuten, dass im Verzeichnis `/home/iobroker/.ssh` nach den Keys gesucht wird.

**Comment by Apollon77** [comment]
Also Absolute Pfade angeben!

**Comment by GermanBluefox** [comment]
Falls das Problem weiter besteht, bitte noch mal aufmachen.

**Comment by nick21-11** [comment]
Versuche über sshpass einen zweiten Rapsberry Pi zu steuern. 
Müsste daher den Key unter dem user iobroker erstmal akzeptieren. Wie kann ich mich denn unter dem user iobroker am pi anmelden? Finde das Passwort nicht.

**Comment by AlCalzone** [comment]
Es gibt kein Passwort. Warum meldest du dich nicht mit einem anderen User an und kopierst die Keys ins entsprechende Verzeichnis des Users iobroker?

Oder mit https://www.npmjs.com/package/node-ssh
