### ISSUE TITLE
zus. npm Module werden nicht installiert

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.javascript#299]
Hallo,

habe nun auf die aktuellste Version upgedatet - 4.0.12. Ich habe die neueste npm Version 6.7.0
die zusätzlichen Module können nun anscheinend nicht mehr installiert werden und es kommen Fehler wie:

`
javascript.0 | 2019-01-27 10:39:42.196 | error | Cannot install npm packet: ssh2
-- | -- | -- | --
javascript.0 | 2019-01-27 10:39:42.195 | error | Cannot install npm packet: node-ssh
javascript.0 | 2019-01-27 10:39:42.195 | error | Cannot install npm packet: simple-ssh
javascript.0 | 2019-01-27 10:39:42.195 | error | Cannot install npm packet: xml2js
`
`

javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!   syscall: 'access',
-- | -- | -- | --
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!   code: 'EACCES',
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!   errno: -13,
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!    'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.javascript/node_modules\'',
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!   stack:
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR!  { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules']
javascript.0 | 2019-01-27 10:39:42.161 | error | npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules'

`

**Comment by Jey-Cee** [comment]
Schau mal hier rein: [Hinweis](https://forum.iobroker.net/viewtopic.php?f=8&t=19209)

**Comment by AlCalzone** [comment]
Da deine Berechtigungen anscheinend durcheinander sind, wäre Interessant zu wissen von wann deine Installation ist, bzw als welcher user iobroker läuft. Dazu auf der Konsole `ps aux | grep io.` eingeben und die Ausgabe posten.
Der User sollte der gleiche sein, dem das iobroker verzeichnis gehört (`ls -la /opt/iobroker`)

**Comment by Seqway** [comment]
Hier das Ergebnis:
`root         9  0.0  0.0      0     0 ?        S    11:06   0:00 [migration/0]
root        15  0.0  0.0      0     0 ?        S    11:06   0:00 [migration/1]
root        21  0.0  0.0      0     0 ?        S    11:06   0:00 [migration/2]
root        27  0.0  0.0      0     0 ?        S    11:06   0:00 [migration/3]
root        42  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        93  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        94  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        95  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        96  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        97  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        98  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root        99  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root       100  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root       117  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
root       120  0.0  0.0      0     0 ?        S<   11:06   0:00 [bioset]
iobroker   617  0.1  5.8 1262588 120764 ?      Ssl  11:06   0:22 iobroker.js-controller
message+   626  0.0  0.1  45124  3700 ?        Ss   11:06   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
iobroker   677  0.1  4.9 1171468 101356 ?      Sl   11:06   0:15 io.admin.0
iobroker   687  0.2  6.3 1070296 129608 ?      Sl   11:06   0:29 io.javascript.0
iobroker   693  0.1  2.6 1021516 54168 ?       Sl   11:06   0:18 io.hm-rpc.0
iobroker   718  0.1  3.8 1020532 78460 ?       Sl   11:06   0:16 io.hm-rega.0
iobroker   728  0.8  2.6 1023468 54908 ?       Sl   11:06   1:51 io.hm-rpc.1
iobroker   738  0.0  2.6 994944 54924 ?        Sl   11:06   0:05 io.simple-api.0
iobroker   755  0.0  2.8 999476 59032 ?        Sl   11:07   0:06 io.terminal.0
iobroker   769  0.0  2.6 993912 54964 ?        Sl   11:07   0:05 io.info.0
iobroker   779  0.2  3.7 1015812 77120 ?       Sl   11:07   0:28 io.history.0
dirk      1094  0.0  0.0  12784   940 pts/0    S+   14:48   0:00 grep io
`

und das hier

`drwxrwxr-x+   7 iobroker iobroker   4096 Jan 27 10:22 .
drwxr-xr-x    3 root     root       4096 Jan 20 18:10 ..
drwxrwxr-x+   5 iobroker iobroker   4096 Jan 20 18:11 install
-rw-rwxr--+   1 iobroker iobroker     91 Jan 20 18:10 INSTALLER_INFO.txt
-rwxrwxr-x+   1 iobroker iobroker     67 Jan 20 18:15 iob
-rwxrwxr-x+   1 iobroker iobroker     67 Jan 20 18:15 iobroker
drwxrwxr-x+   5 iobroker iobroker   4096 Jan 27 10:22 iobroker-data
-rw-rwxr--+   1 iobroker iobroker     92 Jan 20 18:12 killall.sh
drwxrwxr-x+   2 iobroker iobroker   4096 Jan 20 18:11 lib
-rw-rwxr--+   1 iobroker iobroker   1137 Jan 20 18:11 LICENSE
drwxrwxr-x+   2 iobroker iobroker   4096 Jan 27 01:15 log
drwxrwxr-x+ 476 iobroker iobroker  20480 Jan 27 10:22 node_modules
-rw-rwxr--+   1 iobroker iobroker     19 Jan 20 18:12 .npmrc
-rw-rwxr--+   1 iobroker iobroker    813 Jan 27 10:22 package.json
-rw-rwxr--+   1 iobroker iobroker 164520 Jan 20 18:15 package-lock.json
-rw-rwxr--+   1 iobroker iobroker   6101 Jan 20 18:11 README.md
-rw-rwxr--+   1 iobroker iobroker    709 Jan 20 18:12 reinstall.sh`

**Comment by AlCalzone** [comment]
Ok das sieht erst mal gut aus. Das Problem scheint im Adapter-Ordner zu liegen.
Bitte die Ausgabe von `ls -la /opt/iobroker/node_modules/iobroker.javascript` posten.

Hast du irgendwelche npm-Module in letzter Zeit von Hand installiert?

**Comment by AlCalzone** [comment]
Da ist das Problem. Ein Teil der Dateien gehört root. Das bedeutet, dass mindestens 1x in diesem Ordner was per `sudo` installiert wurde. Und da dein Name auch noch auftaucht deutet das für mich darauf hin, dass du selbst die Finger im Spiel hattest.

Dein Problem kannst du vorerst beheben:
`sudo chown -R iobroker:iobroker /opt/iobroker/node_modules/iobroker.javascript`

Bitte vermeide in Zukunft, selbst im ioBroker-Ordner npm-Pakete von Hand zu installieren. Und wenn du es tust, halte dich an den Link, den JeyCee dir gepostet hat.

**Comment by Seqway** [comment]
Ich kann mich zwar nicht erinnern dass ich dort was manuelles installiert hatte, aber gut muss ja irgendwie sein.
Befehl abgefeuert und es geht.

DANKE

**Comment by Erwin40** [comment]
Hi.
Ich weiß der Issue ist eigentlich geschlossen, aber ich habe selbigen Fehler.
Das ist meine Konfig:
![grafik](https://github.com/user-attachments/assets/841b9262-5e35-4e78-9094-ff49013d99a8)

Und das die Meldungen im Log:
`<html><body>

javascript.0 | 2024-12-02 10:32:30.852 | warn | Cannot install custom npm package "audio@latest"
-- | -- | -- | --
javascript.0 | 2024-12-02 10:32:29.630 | warn | Cannot install custom npm package "ping@latest"
javascript.0 | 2024-12-02 10:32:28.299 | warn | Cannot install custom npm package "onoff@latest"
javascript.0 | 2024-12-02 10:32:27.054 | warn | Cannot install custom npm package "systeminformation@latest"


</body>
</html>`

Obige Berechtigungen habe ich geprüft und `sudo chown -R iobroker:iobroker /opt/iobroker/node_modules/iobroker.javascript
ausgeführt`

**Comment by mcm1957** [comment]
> Hi. Ich weiß der Issue ist eigentlich geschlossen, aber ich habe selbigen Fehler. 

Und was erwartest du dann von deinem Comment hier?
Hast du auch noch die Versionen wie in diesem Issue aus 2019 (!) installiert? Dann bitte zuerst mal dein System aktualisieren.

**Comment by Erwin40** [comment]
Danke für die schnelle Antwort.
Welchen Issue meinst du genau? 2019 war es ja ziemlich viele.
System ist Top-Aktuell.
Die Fehler kommen definitiv erst seit dem letzten Update auf 7.0.3

**Comment by mcm1957** [comment]
Dieser Issue hier in dem du Kommentra hinterlassen hast ist aus 2019 !

**Comment by klein0r** [comment]
> Die Fehler kommen definitiv erst seit dem letzten Update auf 7.0.3

Dann hängt es eventuell auch mit dem js-controller zusammen. Gern eine genaue Fehlerbeschreibung in einem NEUEN Issue erstellen.
