### ISSUE TITLE
Too many warnings - state not set

### ISSUE THREAD

**Issue by angelnu** [ioBroker/ioBroker.javascript#30]
I have an script where I looks for homematic states that have not been ACKnowledge yet so I can retry them.

I use `$('channel[state.id=hm-rpc.0.*]').each()` to get all states but then I get a lot of warnings for all objects that do not have states. For example: `State "hm-rpc.0.FEQ0081419.4.PRESS_LONG" not found`

Is there a way to avoid this warning? I get the log full of them.

**Comment by GermanBluefox** [comment]
>Is there a way to avoid this warning?

To create states?

**Comment by angelnu** [comment]
I do not longer see this warning: maybe no the rpc adapter is setting states for all objects?

**Comment by GermanBluefox** [comment]
I implemented something like this, but forgot. 
Please reopen if will be caught again.
