### ISSUE TITLE
still problems with "cannot extract blockly code" @4.0.12

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.javascript#300]
![photo_2019-01-27_10-47-26](https://user-images.githubusercontent.com/11257222/51799688-8c541b00-2224-11e9-8365-b9a9119bc0dc.jpg)
Also in 4.0.12 I have the issue that when opening the Blockly-scripts in the Editor an Alert popup arises with "cannot extract blockly code".
In the top left also appears "Instanz ist deaktiviert"
klicking ok, the blockly window remains empty.
Closing this window and reopening it, all is ok.

Closing the scripts tab and reopening it one of the both alerts appear. If it is teh "Instanz ist deaktiviert", the message will disappear after a few seconds

**Comment by FRYYYYYY** [comment]
Da schließ ich mich an.

**Comment by FRYYYYYY** [comment]
Siehe #284

**Comment by GermanBluefox** [comment]
Should be fixed in 4.1.5
