### ISSUE TITLE
4.0.12 Kein Einfügen beim erstellen eines Skript mehr

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.javascript#302]
Hallo,

Gibt es kein **Einfügen** beim erstellen eines Skript mehr?

![screenshot 1685 _li](https://user-images.githubusercontent.com/41079106/51801969-085e5b00-2245-11e9-804a-c03da08db874.jpg)

**Comment by GermanBluefox** [comment]
Wegen Browser, gibt es nicht. Das ist aber das Problem in Monaco Editor. 
https://github.com/Microsoft/monaco-editor/issues/391#issuecomment-312237052
