### ISSUE TITLE
Objektfenster öffnet sich nicht -  Blockly

### ISSUE THREAD

**Issue by amnesia106** [ioBroker/ioBroker.javascript#304]
Blockly:
Beim klick auf "ID auswählen" passiert nichts. 

(Browser Cache gelöscht)

**Comment by FRYYYYYY** [comment]
Welche Version? Anderen Browser getestet?

**Comment by amnesia106** [comment]
Ja, auch mit Edge getestet, leider ohne Erfolg. Javascript 3.6.4

**Comment by amnesia106** [comment]
#305
