### ISSUE TITLE
Blockly - Importierte Blocklys speichern nicht

### ISSUE THREAD

**Issue by amnesia106** [ioBroker/ioBroker.javascript#305]
Beim Importieren von Blockly-Scripts ist das speichern nicht möglich.

**Comment by FRYYYYYY** [comment]
Speichern oder hochladen? M. E. funktioniert das hochladen schon nicht - es öffnet sich kein Fenster. 
Ist aber bekannt.

**Comment by amnesia106** [comment]
Importieren klappt, das importierte blockly wird angezeigt, lässt sich jedoch nicht als neuen Script abspeichern.

**Comment by amnesia106** [comment]
Fehler gefunden! Es liegt bei mir zumindest an der Admin 3.6.0 - ein downgrade auf 3.4.1 behob den Fehler.
