### ISSUE TITLE
Missing Icon for Javascript instance

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.javascript#307]
Unknown Icon in 4.0.12: /adapter/javascript/js.jpeg

**Comment by GermanBluefox** [comment]
iobroker update javascript

**Comment by JayVee2** [comment]
So I did. Version 0.1.5 installed.
iobroker restarted.
Still: File not found "<ip>/adapter/javascript/js.jpeg"

**Comment by Apollon77** [comment]
0.1.5?
Ich denke das oben sollte eher

iobroker upload javascript

heissen

**Comment by JayVee2** [comment]
"iobroker upload javascript"
und die Icons sind da. Danke.
Ja V 0.1.5. Kam mit einer kompletten Neuinstallation von iobroker. Sehr cool...
