### ISSUE TITLE
different sort of scripts.

### ISSUE THREAD

**Issue by saykl** [ioBroker/ioBroker.javascript#309]
Add a different sort of scripts. The most important thing is sorting by execution type: running / stopped.

Russian:
Добавьте различную сортировку скриптов. Самое главное это сортировка по типу выполнения: выполняется/остановлен.

**Comment by Apollon77** [comment]
Why this is "the most important thing" for you?

**Comment by saykl** [comment]
> 
> 
> Why this is "the most important thing" for you?

Sorting by type of execution is the most important among possible sorts. But for me it would be a useful feature.

**Comment by GermanBluefox** [comment]
Sort is too complex, but filter should work
![image](https://user-images.githubusercontent.com/4582016/52906432-07b95300-324c-11e9-89e3-68e87f2c9311.png)
