### ISSUE TITLE
big timer issue !!!

### ISSUE THREAD

**Issue by einarmiger0815** [ioBroker/ioBroker.javascript#310]
After updating to version 4, all previously programmed, reliably running timers no longer work.

Even creating new timers (no matter what kind) doesn't solve the problem. 

Please fix this, pleeeease !!!

**Comment by Apollon77** [comment]
Example code please?

**Comment by einarmiger0815** [comment]
Schicke ich dir morgen früh, bin ausser Haus heute Abend!

Danke!












Sent from iPhone.


Am 02.02.2019 um 19:58 schrieb Ingo Fischer <notifications@github.com<mailto:notifications@github.com>>:


Example code please?

**Comment by AlCalzone** [comment]
It would be very good to know **what** you did and **how** exactly it didn't work.

"It doesn't work" is not a helpful description.

**Comment by Ilovegym66** [comment]
my standard answer for "something broken" is everytime: "something fixed". :-)

**Comment by einarmiger0815** [comment]
Hallo.

Hier mal der Beispielcode, wo die timergesteuerte Abschaltung nicht mehr funktioniert. Kurioserweise schaltet der Astro-Timer weiterhin ein, aber die "normale" Zeitschaltung nicht aus.

[cid:image001.png@01D4BBB6.0397F7C0]



Hier der Script-Text:

// Balkonlicht schalten Wochentag
schedule({astro: "sunset", shift: 0}, function () {
  setState("sonoff.0.Balkonlicht.POWER"/*Balkonlicht POWER*/, true);
});
schedule("30 21 * * 0-4", function () {
  setState("sonoff.0.Balkonlicht.POWER"/*Balkonlicht POWER*/, false);
});

// Balkonlicht schalten Wochenende
schedule({astro: "sunset", shift: 0}, function () {
  setState("sonoff.0.Balkonlicht.POWER"/*Balkonlicht POWER*/, true);
});
schedule("30 22 * * 5,6", function () {
  setState("sonoff.0.Balkonlicht.POWER"/*Balkonlicht POWER*/, false);
});

//JTNDeG1sJTIweG1sbnMlM0QlMjJodHRwJTNBJTJGJTJGd3d3LnczLm9yZyUyRjE5OTklMkZ4aHRtbCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmNvbW1lbnQlMjIlMjBpZCUzRCUyMi4lM0YlMkZuV3ZmJTVEZiUzQURvRHZmTSUyQyElMkJkJTIyJTIweCUzRCUyMjMzJTIyJTIweSUzRCUyMi00NDglMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJDT01NRU5UJTIyJTNFQmFsa29ubGljaHQlMjBzY2hhbHRlbiUyMFdvY2hlbnRhZyUzQyUyRmZpZWxkJTNFJTNDbmV4dCUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmFzdHJvJTIyJTIwaWQlM0QlMjJIdFklMkNPWSl6a3BNRTdXeSU3QnZwTiklMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJUWVBFJTIyJTNFc3Vuc2V0JTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPRkZTRVQlMjIlM0UwJTNDJTJGZmllbGQlM0UlM0NzdGF0ZW1lbnQlMjBuYW1lJTNEJTIyU1RBVEVNRU5UJTIyJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIyY29udHJvbCUyMiUyMGlkJTNEJTIyM0NTTkl4eUNqTHUlMjVhQTcwUGQ0RSUyMiUzRSUzQ211dGF0aW9uJTIwZGVsYXlfaW5wdXQlM0QlMjJmYWxzZSUyMiUzRSUzQyUyRm11dGF0aW9uJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT0lEJTIyJTNFc29ub2ZmLjAuQmFsa29ubGljaHQuUE9XRVIlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMldJVEhfREVMQVklMjIlM0VGQUxTRSUzQyUyRmZpZWxkJTNFJTNDdmFsdWUlMjBuYW1lJTNEJTIyVkFMVUUlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJsb2dpY19ib29sZWFuJTIyJTIwaWQlM0QlMjJEMUcyJTVEaEQlMjN6RiU3RGwlN0NvUSUzQnhaNDQlMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJCT09MJTIyJTNFVFJVRSUzQyUyRmZpZWxkJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZ2YWx1ZSUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGc3RhdGVtZW50JTNFJTNDbmV4dCUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMnNjaGVkdWxlJTIyJTIwaWQlM0QlMjJOZGd6bSU2MEMtdzIlMkJHejJJRVAyJTVESiUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMlNDSEVEVUxFJTIyJTNFMzAlMjAyMSUyMColMjAqJTIwMC00JTNDJTJGZmllbGQlM0UlM0NzdGF0ZW1lbnQlMjBuYW1lJTNEJTIyU1RBVEVNRU5UJTIyJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIyY29udHJvbCUyMiUyMGlkJTNEJTIybV9SJTNGOUgpX095JTVCMF8lNUQ4JTJCMCUzRCUzQVIlMjIlM0UlM0NtdXRhdGlvbiUyMGRlbGF5X2lucHV0JTNEJTIyZmFsc2UlMjIlM0UlM0MlMkZtdXRhdGlvbiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMk9JRCUyMiUzRXNvbm9mZi4wLkJhbGtvbmxpY2h0LlBPV0VSJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJXSVRIX0RFTEFZJTIyJTNFRkFMU0UlM0MlMkZmaWVsZCUzRSUzQ3ZhbHVlJTIwbmFtZSUzRCUyMlZBTFVFJTIyJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIybG9naWNfYm9vbGVhbiUyMiUyMGlkJTNEJTIyLUNEflYwJTdDJTdCJTJDY0tGZS4yVHhCckglMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJCT09MJTIyJTNFRkFMU0UlM0MlMkZmaWVsZCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGdmFsdWUlM0UlM0MlMkZibG9jayUzRSUzQyUyRnN0YXRlbWVudCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGbmV4dCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGbmV4dCUzRSUzQyUyRmJsb2NrJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIyY29tbWVudCUyMiUyMGlkJTNEJTIyc34lN0RXKEMhd2chaDF3a1glN0QlNUV6dXglMjIlMjB4JTNEJTIyMzglMjIlMjB5JTNEJTIyLTIxMiUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMkNPTU1FTlQlMjIlM0VCYWxrb25saWNodCUyMHNjaGFsdGVuJTIwV29jaGVuZW5kZSUzQyUyRmZpZWxkJTNFJTNDbmV4dCUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmFzdHJvJTIyJTIwaWQlM0QlMjJuM3ZsU1lWNyU1RGQlNUVYbClOaEs0JTJDOSUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMlRZUEUlMjIlM0VzdW5zZXQlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMk9GRlNFVCUyMiUzRTAlM0MlMkZmaWVsZCUzRSUzQ3N0YXRlbWVudCUyMG5hbWUlM0QlMjJTVEFURU1FTlQlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJjb250cm9sJTIyJTIwaWQlM0QlMjI2YihpX0ZMUSpyLiUyRnElM0IlMjNGejNaViUyMiUzRSUzQ211dGF0aW9uJTIwZGVsYXlfaW5wdXQlM0QlMjJmYWxzZSUyMiUzRSUzQyUyRm11dGF0aW9uJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT0lEJTIyJTNFc29ub2ZmLjAuQmFsa29ubGljaHQuUE9XRVIlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMldJVEhfREVMQVklMjIlM0VGQUxTRSUzQyUyRmZpZWxkJTNFJTNDdmFsdWUlMjBuYW1lJTNEJTIyVkFMVUUlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJsb2dpY19ib29sZWFuJTIyJTIwaWQlM0QlMjJOUUFHZXclM0J3WV90WE81fmlWTnlFJTIyJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyQk9PTCUyMiUzRVRSVUUlM0MlMkZmaWVsZCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGdmFsdWUlM0UlM0MlMkZibG9jayUzRSUzQyUyRnN0YXRlbWVudCUzRSUzQ25leHQlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJzY2hlZHVsZSUyMiUyMGlkJTNEJTIyMiU0MDB+QSU1RSU3Qjg1azlORHQlNjBZTXMyLiUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMlNDSEVEVUxFJTIyJTNFMzAlMjAyMiUyMColMjAqJTIwNSUyQzYlM0MlMkZmaWVsZCUzRSUzQ3N0YXRlbWVudCUyMG5hbWUlM0QlMjJTVEFURU1FTlQlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJjb250cm9sJTIyJTIwaWQlM0QlMjI0bkFoN0p+Q3ZEVCUyQmhLRWpjbWN5JTIyJTNFJTNDbXV0YXRpb24lMjBkZWxheV9pbnB1dCUzRCUyMmZhbHNlJTIyJTNFJTNDJTJGbXV0YXRpb24lM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0Vzb25vZmYuMC5CYWxrb25saWNodC5QT1dFUiUzQyUyRmZpZWxkJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyV0lUSF9ERUxBWSUyMiUzRUZBTFNFJTNDJTJGZmllbGQlM0UlM0N2YWx1ZSUyMG5hbWUlM0QlMjJWQUxVRSUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmxvZ2ljX2Jvb2xlYW4lMjIlMjBpZCUzRCUyMnN1JTVFNFNzbmVyIVJLJTdCKlklM0JEVkEhJTIyJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyQk9PTCUyMiUzRUZBTFNFJTNDJTJGZmllbGQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnZhbHVlJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZzdGF0ZW1lbnQlM0UlM0MlMkZibG9jayUzRSUzQyUyRm5leHQlM0UlM0MlMkZibG9jayUzRSUzQyUyRm5leHQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnhtbCUzRQ==


Wie bereits geschrieben, mit der 3er Version des Adapters lief das Schript …


Sorry für die Störung.



Von: Ingo Fischer [mailto:notifications@github.com]
Gesendet: Samstag, 2. Februar 2019 19:59
An: ioBroker/ioBroker.javascript <ioBroker.javascript@noreply.github.com>
Cc: Thomas Stark <thomas@stark.cx>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.javascript] big timer issue !!! (#310)


Example code please?

**Comment by Apollon77** [comment]
Da ist das schedule kaputt und fehlt ein * oder?!

**Comment by einarmiger0815** [comment]
Das kann gut sein - aber das hat das Blockly so gesetzt.

Ich vergleiche dann mal. Aber wenn Blockly das falsch setzt, stimmt da doch was nicht ...











Sent from iPhone.


Am 03.02.2019 um 12:45 schrieb Ingo Fischer <notifications@github.com<mailto:notifications@github.com>>:


Da ist das schedule kaputt und fehlt ein * oder?!

**Comment by AlCalzone** [comment]
Könnte auch an der markdown Formatierung liegen, da der Code nicht in backticks ist.

**Comment by einarmiger0815** [comment]
So, ich habe es gerade noch einmal getestet:

ich habe einen neuen Timer mit Blockly erstellt.
![unbenannt-1](https://user-images.githubusercontent.com/47278855/52178811-fcd5db80-27d2-11e9-8aaf-96117c1cefba.jpg)

Eingetragen sieht das so aus:

![unbenannt-3](https://user-images.githubusercontent.com/47278855/52178831-2989f300-27d3-11e9-964a-ee6b6bfbd052.jpg)


Wenn ich dann aber in den Cron klicke, um ihn anzusehen, geht dieses Fenster auf - das ist dann so, als wäre der Job neu, leer. Die bisher eingetragenen Daten werden nicht angezeigt.

![unbenannt-4](https://user-images.githubusercontent.com/47278855/52178858-6b1a9e00-27d3-11e9-97b5-59705e9b5e2d.jpg)

Dieses Phänomen gab es in der Adapterversion vor der 4.x nicht.

Nach der Aktivierung läuft der Timer auch nicht, auch wenn ich abbrechen drücke und die Werte im Block stehen bleiben.

**Comment by einarmiger0815** [comment]
Sorry, falsch abgesendet.

**Comment by Apollon77** [comment]
Welche Version? Es gab eine JavaScript 4.x Version wo schedules in blockly kaputt waren. Die 4.0.12 sollte das Problem aber nicht haben. 

Ggf muss am blockly was geändert werden das es neu generiert wird

**Comment by einarmiger0815** [comment]
Das ist 4.0.12 - war direkt so installiert.

Die Scripte wurden nach Neuinstallation per Copy & Paste vom alten Broker übertragen, da alle Geräte, welche gesteuert werden, durch Mqtt-Anbindung identisch zur alten Installation eingebunden wurden.

**Comment by einarmiger0815** [comment]
Danke - Update und läuft!
