### ISSUE TITLE
Blocky Spalten verschieben nicht möglich

### ISSUE THREAD

**Issue by dieter78** [ioBroker/ioBroker.javascript#311]
Spalten verschieben oder vergrössern bei der Auswahl der Objekte in Blockly funktioniert nicht.

![grafik](https://user-images.githubusercontent.com/47296525/52177352-e70aeb00-27bf-11e9-8895-868d8eb96a10.png)

**Comment by hoaloha** [comment]
Als workaround funktioniert bei mir die Zoomstufe im Browser (Safari)  zu verkleinern. Dann sind die Spalten zumindest komplett lesbar und man kann den richtigen Datenpunkt wählen.

**Comment by GermanBluefox** [comment]
It is not planned to write scripts on Mobile phone.
