### ISSUE TITLE
Blockly - Blöcke nicht auswählbar

### ISSUE THREAD

**Issue by Schany79** [ioBroker/ioBroker.javascript#313]
Hallo!
Bei den Sendto Blöcken kommt es bei mir zu dem Fehler das die Blöcke übereinander liegen und ich keinen davon auswählen kann.

- Das Problem habe ich im Google Chrome und im Edge Browser.
- Mein ioBroker läuft auf einem Raspi 2.
- Reboot hat keinerlei Auswirkung.
- Ich hatte das Problem in 3.6.4 und auch nach upgrade auf 4.0.12 liegt es leider immer noch vor.

![blockly-fehler](https://user-images.githubusercontent.com/43196833/52194551-aad59a00-2854-11e9-95d5-6f4ffaec56e8.JPG)

Gruß
Sascha

**Comment by BuZZy1337** [comment]
Dann hast du vermutlich irgendeinen Adapter der nicht up to date ist und zu dem keine Instanz existiert.

Siehe:
https://forum.iobroker.net/viewtopic.php?f=21&t=16999&p=179326#p178524

**Comment by Schany79** [comment]
Jo, das war´s! 
Danke!!
