### ISSUE TITLE
4.0.12 create new folder issue

### ISSUE THREAD

**Issue by Maja61** [ioBroker/ioBroker.javascript#315]
Hi,

in vers. 4.0.12 it is not possible to create a folder which has the same name like an already existing script, vise versa the same issue.

**Comment by GermanBluefox** [comment]
I do not understand, why do you need that:
script.js.common.script1 => script
script.js.common.script1 => folder
script.js.common.script1.anotherScript => script

It is valid, that such a constellation is not possible.

**Comment by GermanBluefox** [comment]
Closed, while no reaction.
