### ISSUE TITLE
compareTime: 'between' doesn't seem to be legal

### ISSUE THREAD

**Issue by rgwch** [ioBroker/ioBroker.javascript#32]
Hi and thanks for ioBroker!

I tried the following after reading this: https://github.com/ioBroker/ioBroker.javascript#comparetime 

var abend=compareTime('sunset','nadir','between')

Which gives: "warn - invalid operator: between".
Do I miss something?

Thanks for any hint!

**Comment by Apollon77** [comment]
Yes, one line under the example you find:

Following values are possible: 'sunrise', 'sunset', 'sunriseEnd', 'sunsetStart', 'dawn', 'dusk', 'nauticalDawn', 'nauticalDusk', 'nightEnd', 'night', 'goldenHourEnd', 'goldenHour'. See Astro for detail.

"nadir" is not part of the current allowed list!
