### ISSUE TITLE
Bestehender Cron-String wird im "Zeiplan definieren..." manchmal nicht übernommen

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.javascript#322]
Wenn ich in Blockly das Modul Zeitplan verwende öffnet sich "Zeitplan definieren" mit den Möglichkeiten "Wizard" - "Einfach" - "CRON". Wenn die Zeiten gewählt und mit OK übernommen wurden, dann stehen Sie im Modul im Cron-String. Wenn ich am Cron-String etwas ändern möchte, dann wird der vorhandene Inhalt im "Zeitplan definieren..." nur übernommen, wenn er zuvor mit "CRON" erzeugt wurde. Im Menü "Einfach" wird der Cron-String auf Ausgangsdaten gesetzt.

**Comment by GermanBluefox** [comment]
Hast einen Beispiel, womit ich das reproduzieren kann?

**Comment by XxJooO** [comment]
Hallo Bluefox,

 

ich weiß nicht, ob in der letzten Version etwas geändert wurde, jetzt im Moment funktioniert es wie erwartet. Version 4.1.4

 

Von: Bluefox <notifications@github.com> 
Gesendet: Montag, 25. Februar 2019 20:48
An: ioBroker/ioBroker.javascript <ioBroker.javascript@noreply.github.com>
Cc: XxJooO <j.urmersbach@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.javascript] Bestehender Cron-String wird im "Zeiplan definieren..." manchmal nicht übernommen (#322)

 

Hast einen Beispiel, womit ich das reproduzieren kann?
