### ISSUE TITLE
4.1.0 Cron Wizard Blockly

### ISSUE THREAD

**Issue by zer0point** [ioBroker/ioBroker.javascript#324]
Ein Cron über Blockly Wizard einrichten, der z.B. alle 2 Wochen was auslöst, erzeugt einen Fehler.

**Quellcode erzeugt von Blockly:**
`schedule('{"time":{"exactTime":true,"start":"00:00"},"valid":{"from":"17.02.2019"},"period":{"weeks":2,"dows":"[0]"}}', function () {
  console.log('test');
});`

**Fehlermeldung aus dem Logfile:**
`javascript.0	2019-02-17 11:09:14.374	error	at ContextifyScript.Script.runInContext (vm.js:59:29)
javascript.0	2019-02-17 11:09:14.374	error	at script.js.common.test.cron:1:1
javascript.0	2019-02-17 11:09:14.374	error	at schedule (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1089:52)
javascript.0	2019-02-17 11:09:14.374	error	at Scheduler.add (/opt/iobroker/node_modules/iobroker.javascript/lib/scheduler.js:275:62)
javascript.0	2019-02-17 11:09:14.374	error	TypeError: Cannot read property 'y' of undefined
javascript.0	2019-02-17 11:09:14.374	error	^
javascript.0	2019-02-17 11:09:14.373	error	sch.valid.fromDate = new Date(sch.valid.from.y, sch.valid.from.M, sch.valid.from.d);
javascript.0	2019-02-17 11:09:14.373	error	script.js.common.test.cron: /opt/iobroker/node_modules/iobroker.javascript/lib/scheduler.js:275`

Script Engine: Verfügbare Version: 3.6.5; Installierte Version: 4.1.0
Node.js: v8.14.0
NPM: 6.4.1

**Comment by GermanBluefox** [comment]
Sollte gefixt sein
