### ISSUE TITLE
schedule Date object not working

### ISSUE THREAD

**Issue by allofmex** [ioBroker/ioBroker.javascript#325]
Using schedule() with a Date Object as argument does not work. Scheduled function runs every minute.
```
var date = new Date(Date.now() + 180000);
console.log("expected "+date);
schedule(date, function () {
    console.log("run "+new Date());
});
```
It should be run once, three minutes after script was startet, but it runs every full minute instead:
```

15:12:30.699 ... Start javascript script.js.Script_1
15:12:30.699 ... script.js.Script_1: expected Tue Feb 19 2019 15:15:30 GMT+0100 
15:12:30.699 ... script.js.Script_1: registered 0 subscriptions and 1 schedule
15:13:00.005 ... script.js.Script_1: run Tue Feb 19 2019 15:13:00 GMT+0100
15:14:00.005 ... script.js.Script_1: run Tue Feb 19 2019 15:14:00 GMT+0100
15:15:00.003 ... script.js.Script_1: run Tue Feb 19 2019 15:15:00 GMT+0100 
```

Also tried `schedule({rule: date}, function...`, same result.
It should work according to docu:
> Pattern can be a Javascript Date object (some specific time point) - in this case only it will be triggered only one time.

(Script Engine 4.1.0)

**Comment by GermanBluefox** [comment]
Why do you think, that schedule can accept Date object as parameter?
https://github.com/ioBroker/ioBroker.javascript/blob/master/doc/en/javascript.md#schedule

**Comment by AlCalzone** [comment]
Because it is written in the section you linked to
> Pattern can be a Javascript Date object (some specific time point) - in this case only it will be triggered only one time.

**Comment by GermanBluefox** [comment]
> @GermanBluefox Because it is written in the docs section you linked to
> 
> > Pattern can be a Javascript Date object (some specific time point) - in this case only it will be triggered only one time.

:(

**Comment by GermanBluefox** [comment]
https://github.com/node-schedule/node-schedule/issues/467

**Comment by GermanBluefox** [comment]
Seems node-schedule the project is dead. :( 
Does someone know another scheduler lib?

**Comment by Garfonso** [comment]
This bug is still happening in version 4.4.3.
