### ISSUE TITLE
4.1.0: Blockly: "Anerkannt ist" bleibt bei "egal" leer

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.javascript#327]
Das Blockly-Feld bleibt bei "Anerkannt ist", wenn Wert "egal", leer.
Bei Update oder Befehl ist es korrekt.

Beim Erstellen:

![image](https://user-images.githubusercontent.com/13643787/53094792-68ca7a80-351b-11e9-886e-c0af577dfaa6.png)

Nach Speichern und neu öffnen:

![image](https://user-images.githubusercontent.com/13643787/53094821-80a1fe80-351b-11e9-9f62-a26de49a1f5d.png)

**Comment by FRYYYYYY** [comment]
Gleiches gilt für Block Telegram mit "Loglevel". Wenn "keins", dann leer.

**Comment by GermanBluefox** [comment]
Gefixt
