### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.javascript#329]
I upgrade now from 4.0.12 to the newest but in both version i have the problem that it seems to be that the script is working (e.g. Polleninfo as a truetype script) and the datapoints are filled BUT in the LOG there are many many warning.
After checking i found that the adapter seems not longer to find the "request" module:

Cannot find module 'request'

In the forum also other people have this issue. Can you double check ?

If you need further information please let me know.

**Comment by GermanBluefox** [comment]
Can you give me the link to forum. I cannot reproduce the error

**Comment by Seqway** [comment]
okay here is the link from the forum:

[
https://forum.iobroker.net/post/180671](url)

**Comment by GermanBluefox** [comment]
> okay here is the link from the forum:
> 
> https://forum.iobroker.net/post/180671

It was 7.10.2018 and at this time there was an error. But now the error is fixed (in November or so)

**Comment by Seqway** [comment]
Yes i know, but further like here:

[
https://forum.iobroker.net/post/229946](url)

it seems to work but many warnings are in the LOG. Please double check

**Comment by AlCalzone** [comment]
The warnings are there because your script is assigning a variable of a wrong type to a state:
> Wrong type of javascript.0.wetter.pollenvorhersage.d4.beifuﬂ: "undefined". Please fix, while deprecated and will not work in next versions

And please just copy the links here without using markdown (or use it correctly). The way you do it they lead to a non-existant page here on github.

**Comment by Seqway** [comment]
Okay i will check with developer of the script.

Info:
I used only the LINK button here and copied the url in it. the signs that were done automaticly by clicking onto this button - this is coming automatic --> [](url)

**Comment by Seqway** [comment]
Okay i correct myself. Main reason is here in the Log if i start the truetype script; the module is set in the javascript adapter REQUEST but it seems not be installed:


08:28:04.229 | info | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: compiling TypeScript source...
-- | -- | --
08:28:04.229 | warn | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: TypeScript compilation had errors: import request = require("request"); ^ ERROR: Cannot find module 'request'.
08:28:04.229 | info | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: registered 0 subscriptions and 1 schedule
08:28:05.206 | warn | javascript.0 at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:276:21)
08:28:05.210 | warn | javascript.0 at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:276:21)
08:28:05.212 | warn | javascript.0 at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:276:21)

**Comment by AlCalzone** [comment]
> I used only the LINK button here and copied the url in it. the signs that were done automaticly by clicking onto this button - this is coming automatic --> "[ ] (url) "

Yes, but you need to put the link instead of "url" and not into the free text field [ ]. If you only want to add a link without a different text, pasting it is fine.

> TypeScript compilation had errors: import request = require("request"); ^ ERROR: Cannot find module 'request'.

Might also be an error in the declaration files. Or declaration files that are not provided. As far as i know, 
the line `import request = require("request");` is not even necessary, because the `request` variable is already predefined. Can you try deleting the line altogether?

**Comment by Seqway** [comment]
Okay, understood with the link :-)

Now i deleted the "import request" and the error message is gone. So it seems to work.
There are still issues with warnings but this is related to the script and not to the javascript adapter.

So Thank you very much !
