### ISSUE TITLE
4.1.2 Blockly uralter Bug wieder drin

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#330]
![bug](https://user-images.githubusercontent.com/22603034/53177724-d09ec500-35f0-11e9-9a6f-86832ac1e4ae.gif)

**Comment by darkiop** [comment]
Ist mir gestern auch aufgefallen, lies sich wieder korrigieren in dem man kurz auf die Code Ansicht umschaltet.

Gruß Thorsten

**Comment by Rantanplan01** [comment]
@darkiop Ok, das ist ein workaround, aber keine Lösung.

**Comment by darkiop** [comment]
Absolut - so war meine Antwort auch gedacht :D

**Comment by Rantanplan01** [comment]
behoben in 4.1.3
