### ISSUE TITLE
Anzeige ID Name seit 4.1 geändert

### ISSUE THREAD

**Issue by hoaloha** [ioBroker/ioBroker.javascript#331]
Seit 4.1 wird die ID im Script bei mir angezeigt und nicht mehr der Name. 

![84f516df-e921-43c0-9222-3f55a90fed44](https://user-images.githubusercontent.com/47867028/53224761-194c9180-3676-11e9-85ac-991618c3a0f9.jpg)
<img width="500" alt="id" src="https://user-images.githubusercontent.com/47867028/53224770-1f427280-3676-11e9-913a-f04dbb4e6b2a.png">

**Comment by FRYYYYYY** [comment]
Ja, ist mir auch aufgefallen. Hatte damals alles extra auf Kurznamen geändert bei meinen eigenen Objekten. M. E. ein Bug.

**Comment by Diginix** [comment]
Ist bei mir seit 4.1.3 auch so. Bei 4.1.2 war es noch nicht. Die eigenen Namen sind imho sinnvoller, weil sprechend. Die IDs sind bei meinen Fensterkontakten nur UIDs anhand derer ich nicht sehe welcher Sensor es nun ist. Außerdem nehmen die Objekt IDs viel mehr Platz in den Blöcken ein, was unübersichtlicher ist.

**Comment by heitec11** [comment]
Ich benötige auch die Namen wieder zurück.

**Comment by Rantanplan01** [comment]
Ist auch noch in der 4.1.5 so.
![id_name](https://user-images.githubusercontent.com/22603034/53485611-eeec4100-3a86-11e9-8c94-63bf8bfea831.png)

**Comment by GermanBluefox** [comment]
Fixed in 4.1.6
