### ISSUE TITLE
4.1.3 blockly importieren geht nicht

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#332]
4.1.3 Blockly importieren hängt, folgendes Blockly
[blockly.txt](https://github.com/ioBroker/ioBroker.javascript/files/2893208/blockly.txt)

und hier das logfile
[logfile.txt](https://github.com/ioBroker/ioBroker.javascript/files/2893214/logfile.txt)

Das ist auch ein blockly, bei dem auch immer noch der Fehler "cannot extract" kommt...

**Comment by vr6syncro** [comment]
kann den Fehler bestätigen.
Habe extre eine neue Installation gemacht und nur js adapter und alles was standart war auf latest geupdatet,

Blockly hat diverse Fehlfunktionen.
im/export und createstate wollte bei mir heute auch nicht

**Comment by xFroop** [comment]
Also bei mir funktioniert das importieren leider auch nicht. Wenn ich auf Import gehe erscheind das Feld. Dann gebe ich dort den Code ein und klicke auf importieren. Das Bild geht weg und bleibt leer. Anschließend muss ich nochmal raus gehen wieder rein. Klicke auf das Script und tadaaaa es ist leer :( 

Was kann das sein?

**Comment by GermanBluefox** [comment]
Bei mir funktioniert einwandfrei. Allerdings in blockly.txt ist xml block zwei mal drin.
Wenn ich die Hälfte lösche, dann geht alles.
Und telegram muss installiert sein.
Wenn der Fehler immer noch da ist, dann bitte noch mal aufmachen

**Comment by Ilovegym66** [comment]
in 4.1.4 behoben! Danke
