### ISSUE TITLE
Java Script Engine v.4.1.3 - Blockly - Timeout - timeout is not defined

### ISSUE THREAD

**Issue by Reelfan** [ioBroker/ioBroker.javascript#334]
Bei der Nutzung von Timeout  in einem Blockly Script "fehlt" am Anfang eine Definition für Timeout, das wiederum führt zum Fehler "Error in callback: ReferenceError: timeout is not defined".

Anbei ein Muster:
![grafik](https://user-images.githubusercontent.com/37248793/53288451-64ef6000-3788-11e9-81e1-b611f3793908.png)

```
on({id: 'shelly.0.SHSW-1#32786F#1.Relay0.Switch', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("shelly.0.SHSW-1#32786F#1.Relay0.Switch").val == true && getState("zigbee.0.00158d0001ad6a7d.occupancy").val == true) {
    (function () {if (timeout) {clearTimeout(timeout); timeout = null;}})();
  } else if (getState("zigbee.0.00158d0001ad6a7d.occupancy").val == false) {
    (function () {if (timeout) {clearTimeout(timeout); timeout = null;}})();
    timeout = setTimeout(function () {
      setState("shelly.0.SHSW-1#32786F#1.Relay0.Switch"/*Switch*/, false);
    }, 60000);
  }
});
```

**Comment by S401967** [comment]
In den alten (vorhandenen) Blockly's ist das Timeout noch als Variable deklariert.
-----------------------------

**var timeout;**

on({id: "sonoff.0.Treppenlicht.POWER"/*Treppenlicht POWER*/, change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("sonoff.0.Treppenlicht.POWER").val == true) {
    (function () {if (timeout) {clearTimeout(timeout); timeout = null;}})();
    timeout = setTimeout(function () {
      if (getState("sonoff.0.Treppenlicht.POWER").val == true) {
        setState("sonoff.0.Treppenlicht.POWER"/*Treppenlicht POWER*/, false);
      }
    }, 600000);
  }
});

**Comment by S401967** [comment]
In der Version 4.1.4 funktioniert es wieder

**Comment by Reelfan** [comment]
Danke habe auch gerade den fix gesehen, hast Du vom github installiert ?

**Comment by Reelfan** [comment]
Kann auch bestätigen 4.1.4  löst das Problem

**Comment by S401967** [comment]
Ja nach dem installieren der Version von github, (4.1.4) war der Eintrag der Variable wieder vorhanden.
