### ISSUE TITLE
fs.createReadStream is not a function

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.javascript#335]
### In der JS-Version 4.1.x bekomme ich folgende Fehlermeldung:

`
javascript.0	2019-02-22 00:30:46.193	error	at FSReqWrap.oncomplete (fs.js:135:15)
javascript.0	2019-02-22 00:30:46.193	error	at script.js.Kameras.Kamera_Haustuer_Motion:126:6
javascript.0	2019-02-22 00:30:46.193	error	script.js.Kameras.Kamera_Haustuer_Motion: TypeError: fs.createReadStream is not a function
`

### Die Fehlermeldung kommt durch ein Kamerascript von mir, mit folgender Funktion:

`
.
..
....

request.get({url: source_url, encoding: 'binary'}, function (err, response, body) {
fs.writeFile(dest_path_tmp + 'Haustuer-2.jpg', body, 'binary', function(err) {
fs.createReadStream(dest_path_tmp + 'Haustuer-2.jpg').pipe(fs.createWriteStream(dest_path + timeLastData() +"_Haustuer.jpg"));
exec('bash /usr/local/bin/haustuer-motion.sh');
if (err) {
if (logging) log('Fehler beim Bild speichern: ' + err, 'warn');
} else {
if (logging) log('Webcam Bild Nr.2 gespeichert');
if ((AlarmAussen === false) || (AlarmAussen === 'false') || (AlarmAussen === 0) || (AlarmInnen === false) || (AlarmInnen === 'false') || (AlarmInnen === 0)) {
sendImage(dest_path_tmp + 'Haustuer-2.jpg',  getState('javascript.0.Kameraaufnahmen.EventMessage').val, false);
} else {
sendImage(dest_path_tmp + 'Haustuer-2.jpg','', true);
}
}
});
});

.....
...
..
.
`

in der JS-Version 3.6.5 klappt alles ohne Probleme.

Gruß
Johnny

**Comment by GermanBluefox** [comment]
Fixed in the latest version.

**Comment by PrinzEisenherz1** [comment]
Fixed in Version 4.1.4?

**Comment by AlCalzone** [comment]
Probably 4.1.5 (which is on npm) or the next one.

**Comment by PrinzEisenherz1** [comment]
Thanks.
I will test it tonight.

**Comment by PrinzEisenherz1** [comment]
Problem is fixed in version 4.1.5!!!
Thanks
