### ISSUE TITLE
Error restart adapter 4.1.4

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.javascript#336]
> `
Caught | 2019-02-24 21:40:01.133 | error | by controller[1]:
-- | -- | -- | --
Caught | 2019-02-24 21:40:01.133 | error | by controller[1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Caught | 2019-02-24 21:40:01.132 | error | by controller[1]: at maybeClose (internal/child_process.js:920:16)
Caught | 2019-02-24 21:40:01.131 | error | by controller[1]: at ChildProcess.emit (events.js:191:7)
Caught | 2019-02-24 21:40:01.131 | error | by controller[1]: at emitTwo (events.js:106:13)
Caught | 2019-02-24 21:40:01.130 | error | by controller[1]: at ChildProcess.g (events.js:292:16)
Caught | 2019-02-24 21:40:01.129 | error | by controller[1]: at ChildProcess.<anonymous> (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\ping-promise.js:76:12)
Caught | 2019-02-24 21:40:01.128 | error | by controller[1]: at Function._.each._.forEach (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\node_modules\underscore\underscore.js:186:9)
Caught | 2019-02-24 21:40:01.127 | error | by controller[1]: at C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\node_modules\underscore\underscore.js:76:21
Caught | 2019-02-24 21:40:01.127 | error | by controller[1]: at WinParser.parser.eat (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\parser\base.js:125:14)
Caught | 2019-02-24 21:40:01.126 | error | by controller[1]: at WinParser._processBody (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\parser\win.js:56:42)
Caught | 2019-02-24 21:40:01.125 | error | by controller[1]: 2019-02-24 21:40:00.237 - error: javascript.0 TypeError: Cannot read property '1' of null
Caught | 2019-02-24 21:40:01.125 | error | by controller[1]: 2019-02-24 21:40:00.235 - javascript.0 uncaught exception: Cannot read property '1' of null
Caught | 2019-02-24 21:40:01.124 | error | by controller[1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
Caught | 2019-02-24 21:40:01.123 | error | by controller[1]: at maybeClose (internal/child_process.js:920:16)
Caught | 2019-02-24 21:40:01.121 | error | by controller[1]: at ChildProcess.emit (events.js:191:7)
Caught | 2019-02-24 21:40:01.120 | error | by controller[1]: at emitTwo (events.js:106:13)
Caught | 2019-02-24 21:40:01.118 | error | by controller[1]: at ChildProcess.g (events.js:292:16)
Caught | 2019-02-24 21:40:01.117 | error | by controller[1]: at ChildProcess.<anonymous> (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\ping-promise.js:76:12)
Caught | 2019-02-24 21:40:01.116 | error | by controller[1]: at Function._.each._.forEach (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\node_modules\underscore\underscore.js:186:9)
Caught | 2019-02-24 21:40:01.115 | error | by controller[1]: at C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\node_modules\underscore\underscore.js:76:21
Caught | 2019-02-24 21:40:01.114 | error | by controller[1]: at WinParser.parser.eat (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\parser\base.js:125:14)
Caught | 2019-02-24 21:40:01.112 | error | by controller[1]: at WinParser._processBody (C:\ioBroker\node_modules\iobroker.javascript\node_modules\ping\lib\parser\win.js:56:42)
Caught | 2019-02-24 21:40:01.109 | error | by controller[1]: TypeError: Cannot read property '1' of null

`

**Comment by Ilovegym66** [comment]
genau das gleiche hab ich mit V4.1.4 auch. Bei den Blocklys keine Probleme (bis jetzt).
