### ISSUE TITLE
4.1.5 Blockly Chron Optik

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#337]
Hier noch zwei Kleinigkeiten.
Chron Wizard in dunkler Ansicht.
![chron-wizard](https://user-images.githubusercontent.com/22603034/53484716-b8152b80-3a84-11e9-9516-c8ad1e13fc5d.png)

Chron Anzeige Daten -> Tage.
![cron_tage](https://user-images.githubusercontent.com/22603034/53484847-104c2d80-3a85-11e9-9198-abdaf1c1876b.png)

**Comment by GermanBluefox** [comment]
Dark optic in 4.1.7 must look better.

**Comment by ldittmar81** [comment]
https://gfds.de/datum-plural-von/ - Daten ist zwar grammatikalisch korrekt, aber man könnte sich hier vielleicht auf "bestimmte Datumsangaben" einigen, denn bei Tage, könnte sich ja auch ein Verwechslung mit Wochentage ergeben.

**Comment by Rantanplan01** [comment]
Ist das nun ein Einwand?
Ich finde, in dem Zusammenhang "Minuten/Stunden/***Daten***/Monate/Wochentag", den Plural von 
Datum fehl am Platz.

> Ahh... dann würde ich auch bei Gelegenheit "alle N Tag" in "alle N Tage" ändern

Hatte ich übersehen.

**Comment by Rantanplan01** [comment]
Optik in "Dark" ist in v4.1.7 besser.

Thema "Daten" -> "Tage" noch nicht erledigt.
Soll ich dafür ein eigenes "issue" anlegen?

**Comment by GermanBluefox** [comment]
> Soll ich dafür ein eigenes "issue" anlegen?

Habe ich schon auf git gefixt. Wird in der nächsten Version auftauchen.

**Comment by Rantanplan01** [comment]
Geändert ja, aber nicht korrekt.
Der Begriff "Daten" ist falsch.
Die Auswahl: "bestimmte Datumsangaben" ist auch falsch.
Es wird kein "bestimmtes Datum" ausgewählt.
Ein bestimmtes Datum ist z.B. der "11.11.2019" 
Hier wird aber ein "bestimmter Tag" ausgewählt. Zum Beispiel immer der 10. eines Monats.

Mir ist dabei noch ein kleiner Fehler aufgefallen.
Bei "ALLE ABWÄHLEN" bleibt immer der 1. aktiv. Den muss man immer manuell deaktivieren.

**Comment by GermanBluefox** [comment]
Tag ist morgen, heute oder Wochentag.... Odr?

**Comment by Rantanplan01** [comment]
Ja, auch. Heute, morgen, übermorgen..., Monatag, Dienstag.... SInd alles Tage.
Wobei man heute, morgen, übermorgen schlecht mit Cron abbilden kann.
Und Montag, Dienstag....wird im Cron über "Wochenag" abgebildet

Aber auch.
Am 1. TAG eines Monats gibt'es Geld und am 30. TAG eines Monats ist wieder alles weg. :)

**Comment by Rantanplan01** [comment]
in v4.1.12 fixed
