### ISSUE TITLE
4.1.5 Blockly ID Auswahl Filter "Name" sucht nicht in "hm-rpc"

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#338]
Die Geräte aus "hm-rpc" werden über den Namen-Filter nicht gefunden.

Filter "WZ" im Namen
![filter_name1](https://user-images.githubusercontent.com/22603034/53486370-cfeeae80-3a88-11e9-89e6-a37b67e3e686.png)

Geräte in "hm-rpc" mit "WZ" im Namen. die nicht gefunden werden.
![filter_name2](https://user-images.githubusercontent.com/22603034/53486488-2360fc80-3a89-11e9-9849-b8c17ef61746.png)

**Comment by GermanBluefox** [comment]
Fixed in 4.1.6

**Comment by Rantanplan01** [comment]
bestätigt!
