### ISSUE TITLE
Trigger is not working at 4.1.6

### ISSUE THREAD

**Issue by heitec11** [ioBroker/ioBroker.javascript#341]
I change the trigger vom "aktualisiert" to "geändert" in a Blockly and the result was the lost of trigger function.
I changed is back and also test other trigger icons, but no more trigger any more.

**Comment by GermanBluefox** [comment]
Can you please show the generated code for both cases?
And the blockly screenshots?

**Comment by heitec11** [comment]
I test an other older function.
Only a toggle live bit to homematic.
I save without changings and now it is still not working.
![grafik](https://user-images.githubusercontent.com/44260876/53578263-9a74be80-3b77-11e9-970d-0345757ac683.png)

**Comment by heitec11** [comment]
The sricpt for the first item:
![grafik](https://user-images.githubusercontent.com/44260876/53578423-f63f4780-3b77-11e9-8974-961e439370a8.png)

Variables from MQTT:
![grafik](https://user-images.githubusercontent.com/44260876/53578530-2686e600-3b78-11e9-885d-0f7394e817f9.png)

Needs transfer to Homematic:
![grafik](https://user-images.githubusercontent.com/44260876/53578645-53d39400-3b78-11e9-987d-ab6b1b2685de.png)

**Comment by heitec11** [comment]
Code from LiveBit:
![grafik](https://user-images.githubusercontent.com/44260876/53578786-a01ed400-3b78-11e9-8352-38fc976268e9.png)

Code from ETA25PE_Mqtt2HM:
![grafik](https://user-images.githubusercontent.com/44260876/53578882-cf354580-3b78-11e9-9173-d6a6a65c3cca.png)

**Comment by heitec11** [comment]
Maybe is it not the trigger: (The LOG shows that the variable is not reachable)


javascript.0 | 2019-02-28   18:51:10.014 | warn | at TCP.onread (net.js:601:20)
-- | -- | -- | --
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Socket.Readable.push (_stream_readable.js:208:10)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   readableAddChunk (_stream_readable.js:250:11)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at addChunk (_stream_readable.js:263:12)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Socket.emit (events.js:211:7)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at emitOne   (events.js:116:13)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at Socket._ultron.on   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:138:22)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Receiver.add   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:139:10)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Receiver.startLoop   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:165:16)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Receiver.getData (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:330:12)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at Receiver.dataMessage   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:389:14)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at   Receiver._receiver.onmessage   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:141:47)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at WebSocket.emit (events.js:211:7)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at emitOne   (events.js:116:13)
javascript.0 | 2019-02-28   18:51:10.014 | warn | at WebSocket.onMessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/EventTarget.js:99:16)
javascript.0 | 2019-02-28   18:51:10.013 | warn | at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
javascript.0 | 2019-02-28   18:51:10.013 | warn | at WS.Transport.onData   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:137:8)
javascript.0 | 2019-02-28   18:51:10.013 | warn | at   WS.Transport.onPacket   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at WS.Emitter.emit   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   WS.<anonymous>   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:273:10)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Socket.onPacket   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:456:14)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Socket.Emitter.emit   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Socket.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Manager.ondata   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:335:16)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-parser/index.js:251:12)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at Decoder.Emitter.emit   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Decoder.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Manager.ondecoded   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at Manager.Emitter.emit   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at   Socket.onpacket   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at Socket.onack   (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
javascript.0 | 2019-02-28   18:51:10.011 | warn | at Socket.<anonymous> (script.js.common.LiveBit-Toggle:3:7)
javascript.0 | 2019-02-28   18:51:10.010 | warn | at setState   (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1256:20)
javascript.0 | 2019-02-28   18:51:10.010 | warn | State   "LiveBit_iobroker" not found

**Comment by heitec11** [comment]
SOLUTION: The link to all variables was wrong.
I downgrad to 3.6.5 and make new links to the varables.

It looks for my like a bug in the save routine.

**Comment by GermanBluefox** [comment]
Sorry: your text is very confusing.
I still do not understand what the trigger do you mean. 
What do you mean with "link was wrong"? What the link?
Why you showed me CRON trigger and then "on Change Trigger"?
MQTT???? What does it to do with trigger?

The only error what I could see is 
```State "LiveBit_iobroker" not found```
And this means that your variable "javascript.0.LiveBit_iobroker" just does not exists, because was deleted.
And I could not see where you call ```createState("LiveBit_iobroker") ```, what you normally should do by the start of the script.


Vielleicht auf Deutsch beschreiben?

**Comment by DavidPasch** [comment]
... the generated Javacode for a trigger is missing the adapter.instance Info in front of the object. Currently its "abc.variable" instead of "javascript.0.abc.variable". Old Script have the second one and are working. Scripts created with 4.1.6 are like the first once.

**Comment by GermanBluefox** [comment]
Install 4.1.7 and reassign the IDs.

**Comment by DavidPasch** [comment]
Top! Läuft wieder!

**Comment by heitec11** [comment]
Danke. Mit 4.1.7 läuft es auch bei mir wieder korrekt.
Entschuldigung für die verwirrende Meldung, da ich zwei unterschiedliche Scripte hatte, die vorher gelaufen hatten. Nur beim zweiten gabe es die Warnung, dass die Variable angeblich nicht vorhanden ist. War sie aber... Der erste Fehler hatte in der Wahrnehmung nur ein Triggerproblem. Beim zweiten wurden dann klar, dass die Zuordnung der Variablen nicht mehr korrekt ist. Das ganze aber nur bei Scripten die unter 4.1.6 abgespeichert wurden.
Vielen Dank für die schnelle Reaktion.
