### ISSUE TITLE
[bug] Blockly nach Javascript: keine id's mehr im Javascript

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.javascript#343]
Werden in Blockly Object ID's ausgewählt, erscheint im Blockly der Name, aber auch im Javascript, d.h. die ID's werden nicht genutzt und das Blockly / Skript funktioniert nicht mehr. Bin jetzt auf javascript@3.6.5 zurück, da funktioniert noch alles richtig. Ab welcher 4'er-Version es schief läuft konnte ich noch nicht verifizieren.

**Comment by GermanBluefox** [comment]
>Ab welcher 4'er-Version es schief läuft konnte ich noch nicht verifizieren.

Ab 4.1.6. D.h. 4.1.5 läuft

**Comment by FRYYYYYY** [comment]
Dito, auch bei mir funktioniert nichts mehr.

**Comment by GermanBluefox** [comment]
Bitte dringend 4.1.7 installieren. UNd keine Skripte mit 4.1.6 anfassen

**Comment by FRYYYYYY** [comment]
Mit 4.1.7 funktioniert wieder alles! Super!
