### ISSUE TITLE
get state not working in 4.1.6

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.javascript#344]
I get multiple errors relating to get state. Nearly all variables/objects can't be found.

`

avascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:29:11
-- | -- | -- | --
javascript.0 | 2019-02-28 21:19:23.577 | warn | getState "Diff_On" not found (3)
javascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:28:12
javascript.0 | 2019-02-28 21:19:23.577 | warn | getState "Diff_avg" not found (3)
javascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:27:9
javascript.0 | 2019-02-28 21:19:23.577 | warn | getState "Diff2" not found (3)
javascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:26:9
javascript.0 | 2019-02-28 21:19:23.577 | warn | getState "Diff1" not found (3)
javascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:25:9
javascript.0 | 2019-02-28 21:19:23.577 | warn | getState "Temp1" not found (3)
javascript.0 | 2019-02-28 21:19:23.577 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:24:9
javascript.0 | 2019-02-28 21:19:23.576 | warn | getState "Temp2" not found (3)
javascript.0 | 2019-02-28 21:19:23.576 | warn | at script.js.common.Heizung_Kamin.Zirkulationssteuerung_2:23:9
javascript.0 | 2019-02-28 21:19:23.576 | warn | getState "Temp3" not found (3)

`

**Comment by GermanBluefox** [comment]
Between 4.1.5 and 4.1.6 nothing was changed concerning backend.

**Comment by Apollon77** [comment]
Is the state ID really correct with "Temp2" e.g.?

**Comment by Diginix** [comment]
Ich habe das selbe Problem seit 4.1.6 wieder die Namen statt der UID in Blockly anzeigt werden aber im eigentlichen JS Code auch nur noch die Namen genutzt. Es wird also versucht Datenpunkte zu lesen/schreiben nur mit ihrem Namen. Betrifft aber nur Blockly Skripte die mit 4.1.6 erzeugt oder geändert wurden.
Der Block für die Debugausgabe eines Objektes sieht so aus:
`console.log(getState("Indicator if new adapter updates are available").val);`

**Comment by GermanBluefox** [comment]
Fixed in 4.1.7. Aber die Variablen muss man wieder festlegen. Leider.
