### ISSUE TITLE
Object not referenced correctly

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#345]
Could have been the case before but now with 4.16 I notice this:
I check a TR064 Object for active state and all that is written in the blockly is:

on({id: 'active', change: "ne"}, function (obj) { ...

So there is actually no reference to the adapter that the object belongs to.
Ultimately .. the script isn't working.

**Comment by Apollon77** [comment]
Pleas einstall latest 4.1.7 and reassign the object s

**Comment by daniel-lo** [comment]
Thanks .. but I still have to remarks:

-I cannot identify the selected object in my blockly. All I see is "active" three times. I checked if there might be a hover text but to no avail. So it would be good to have some clarity if the correct object has been selected.
-The object tree formerly didn't collapse after you selected an object for a blockly. Now the tree collapses and it is very inconvenient e.g. to pic three active states from the TR064 adapter because you always have to start from the root folder.

**Comment by daniel-lo** [comment]
The latter could have to do with the original problem .. so I will have to review this. Still the only way to identify which active belongs to which object is to look into the JS code ore click the object and look in the object tree.

Not sure if I have to reassign all objects in all scripts now .. after updating to 4.17?!
