### ISSUE TITLE
Blocks disappear after saving

### ISSUE THREAD

**Issue by peer69** [ioBroker/ioBroker.javascript#348]
Using Version 4.1.7 after saving a blockly script every block seems to have disappeared except for the trigger block. Switching to the code everything still seems to be there but it isn't displayed in block-mode. 

This behaviour seems to be somewhat depending on the object I choose for the trigger starting the script with. If I choose a datapoint from deconz-adapter the blocks disappear, If i chose a custom datapoint created in the javascript folder the blocks remain. 

This only happens with versions > 4.0.12. Reverting to the old version fixed the problem for me. I even tried several browsers (FF, Chrome, Safari on a Mac) but it's the same for all of them.

**Comment by GermanBluefox** [comment]
I should check the browser console. It must be an errors there.
