### ISSUE TITLE
4.1.7 - filter ..?? 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#350]
In 4.1.5 and 4.16 there was a nice filter option ( script enabled, etc..) in 4.1.7 is away..?
Bug or changed?

**Comment by Reelfan** [comment]
It is there 4.1.7 in the footer
![grafik](https://user-images.githubusercontent.com/37248793/53685685-48ba6880-3d1e-11e9-8bb4-dd7e4385b0a1.png)

**Comment by Ilovegym66** [comment]
ahh. in dark theme I see it.. ;-) okay..
