### ISSUE TITLE
4.1.8 install not working

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.javascript#351]
`$ ./iobroker upgrade javascript
Update javascript from @4.1.7 to @4.1.8
NPM version: 6.4.1
npm install iobroker.javascript@4.1.8 --production --save --prefix "/opt/iobroker" (System call)
npm
 
WARN
 deprecated
 coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm
 
WARN
 
checkPermissions
 Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/moment
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/moment-timezonenpm WARN 
checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/object-keysnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/define-properties
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/is-nan
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/cron-parser
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/sorted-array-functions
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types/node
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types

npm
 
WARN
 react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.
npm
 WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.npm WARN react-redux@5.1.1 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

npm
 
ERR!
 path
 /opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeoutnpm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout'
npm ERR!  { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm
 
ERR!
 A complete log of this run can be found in:npm
 ERR!     /home/iobroker/.npm/_logs/2019-03-03T19_04_36_694Z-debug.log
ERROR: host.IoBroker-VM-Debian Cannot install iobroker.javascript@4.1.8: 243
ERROR: process exited with code 25`

**Comment by Apollon77** [comment]
Da ist bei Dir mit Rechten etwas nicht in Ordnung. Bitte ggf den Installations Fixer (siehe Forum in Announcements, wenn nicht Docker!!) nutzen und neu versuchen. Oder anderweitig Rechte vorher fixen!

**Comment by passuff** [comment]
Fixer ist schon wegen dem start stop issue installiert worden. Vl war es der fixer? 4.1.7 konnte ich noch installieren, den Fixer hatte ich danach ausgeführt..

**Comment by Apollon77** [comment]
Platz genug ist noch? Filesystem geht es gut?

**Comment by passuff** [comment]
Nach einem reboot und erneutem ausführen des install fixers klappt nun alles wieder. Ich hoffe es bleibt dabei. Danke für den support!
