### ISSUE TITLE
Javascrip console visualisation not working properly

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.javascript#352]
console output:

2:49:44.255 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
-- | -- | --
22:49:44.255 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:44.255 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:44.255 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:44.255 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:45.256 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:45.257 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:46.256 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:46.257 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:47.259 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:47.260 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:48.261 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:48.261 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:48.261 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:48.261 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:49.262 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:48.261 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:49.262 | info | javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
22:49:49.262 | info | javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
22:49:50.088 | info | javascript.0 Stop script script.js.common.Heizung_Kamin.Test

real output:

3.3.2019, 22:49:34.244	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:35.245	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:35.246	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:36.246	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:36.247	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:37.248	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:37.248	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:38.248	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:38.248	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:39.249	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:39.249	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:40.251	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:40.251	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:41.251	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:41.252	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:42.253	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:42.253	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:43.253	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:43.254	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:44.255	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:44.255	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:45.256	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:45.257	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:46.256	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:46.257	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:47.259	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:47.260	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:48.261	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:48.261	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:49.262	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: 37.2
3.3.2019, 22:49:49.262	[info ]: javascript.0 script.js.common.Heizung_Kamin.Test: Zeit aktiv
3.3.2019, 22:49:50.088	[info ]: javascript.0 Stop script script.js.common.Heizung_Kamin.Test

**Comment by GermanBluefox** [comment]
I cannot reproduce it. How can I do that?
