### ISSUE TITLE
problemScripts - confusion what's wrong

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.javascript#353]
hi - I'm confused about the "problemScripts" entries under the javascript-objects v4.1.7)

we have already a discussion in the forum - maybe someone could join: 

https://forum.iobroker.net/topic/20574/script-wurden-in-einen-neuen-ordner-scriptproblem-verschoben-warum/5

overall: most of my scripts (they all working) are under problem scripts - only a couple of them are in the enabledScripts-folder

in addition - I have 3 js-adapter running. a couple of scripts are shown in nearly every adapter 
one file is under : (only in  js.0.scriptEnabled - there is no entry  
js.0.scriptEnabled..
js.0.scriptProblem..
js.1.scriptEnabled..
js.1.scriptProblem..
js.2.scriptProblem..
**is this mormal ?** 

also deleted files are shown under the objects

**Comment by GermanBluefox** [comment]
See forum.
