### ISSUE TITLE
$Selector doesn't work properly

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#354]
[Forum](https://forum.iobroker.net/topic/20543/gel%C3%B6st-k%C3%B6nnte-mir-bitte-jemand-bei-dem-script-helfen/8)

**Comment by paul53** [comment]
Test mit Version 4.1.10 funktionierte.

**Comment by GermanBluefox** [comment]
> Test mit Version 4.1.10 funktionierte.

Obwohl nichts geändert wurde...

**Comment by paul53** [comment]
Ich habe es mit mit Version 4.1.10 mit Erfolg getestet. Andere Versionen 4.x habe ich nicht getestet. Bei @Hicks funktioniert es mit keiner 4.x Version. Er muss auf 3.6.4 downgraden, damit es funktioniert.

**Comment by GermanBluefox** [comment]
Ich habe jetzt auch getestet und bei mir ging es. D.h. ich kann nicht reproduzieren oder Problem existiert nicht mehr.
