### ISSUE TITLE
Aufruf von Objekten der Instanz "Modbus" seit Version > 4.0.12 nicht mehr möglich

### ISSUE THREAD

**Issue by Kunibert-007** [ioBroker/ioBroker.javascript#355]
Wenn ich in einem Blockly-Script einen Datenpunkt auswählen möchte öffnet sich regulär das Fenster zur Ordnerauswahl und ich kann z. B. aus der Instanz HM-Rega, Javascript etc. alle Objekte auswählen.
Wenn ich aber den Modbus-Adapter auswähle und auf "Holding Register" klicke stürzt die Session ab und ich muss die Webseite neu laden. Damit kann ich keine Blockly-Objekte aus dem Modbus-Adapter mehr auswählen. Das Problem tritt erst seit kurzem auf, jedoch auch in der aktuellsten Version 4.1.9. Habe auf die Version 4.0.12. downgegradet, damit funktioniert der Aufruf von Modbus-Objekten.

Hier die funktionierende Auswahl in Version 4.0.12:
![version 4 0 12](https://user-images.githubusercontent.com/35669927/53830492-dc8c6e80-3f82-11e9-8bb5-de96151085d4.PNG)

Hier die Auswahl in Version 4.1.9:
![version 4 1 9 i](https://user-images.githubusercontent.com/35669927/53830757-718f6780-3f83-11e9-85a3-9458ad133625.PNG)
Und hier kommt nur noch ein weißer Frame:
![version 4 1 9 ii](https://user-images.githubusercontent.com/35669927/53830758-718f6780-3f83-11e9-91b4-f92b0af5c18b.PNG)

**Comment by AlCalzone** [comment]
Wenn der editor verschwindet, wird es einen Fehler in der Browserkonsole geben. Den bitte hier posten

**Comment by Kunibert-007** [comment]
Ich hoffe das hilft weiter:
`1.a5154afe.chunk.js:1 SyntaxError: Invalid regular expression: /modbus\.0\.holdingRegisters\.200_Actual_battery charge (-) / discharge (+) current/: Nothing to repeat
fa @ 1.a5154afe.chunk.js:1
1.a5154afe.chunk.js:1 Uncaught SyntaxError: Invalid regular expression: /modbus\.0\.holdingRegisters\.200_Actual_battery charge (-) / discharge (+) current/: Nothing to repeat
3tab.html:1 Uncaught (in promise) AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
8vendor.js:1 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
c @ vendor.js:1
react-dom.production.min.js:4406 SyntaxError: Invalid regular expression: /modbus\.0\.holdingRegisters\.200_Actual_battery charge (-) / discharge (+) current/: Nothing to repeat
    at new RegExp (<anonymous>)
    at e.value (Connection.js:100)
    at t.value (SelectID.js:886)
    at t.value (SelectID.js:953)
    at t.value (ColumnWrapper.js:45)
    at Ti (react-dom.production.min.js:3783)
    at Mi (react-dom.production.min.js:3774)
    at ji (react-dom.production.min.js:3958)
    at Ga (react-dom.production.min.js:5512)
    at $a (react-dom.production.min.js:5534)
fa @ react-dom.production.min.js:4406
react-dom.production.min.js:5938 Uncaught SyntaxError: Invalid regular expression: /modbus\.0\.holdingRegisters\.200_Actual_battery charge (-) / discharge (+) current/: Nothing to repeat
    at new RegExp (<anonymous>)
    at e.value (Connection.js:100)
    at t.value (SelectID.js:886)
    at t.value (SelectID.js:953)
    at t.value (ColumnWrapper.js:45)
    at Ti (react-dom.production.min.js:3783)
    at Mi (react-dom.production.min.js:3774)
    at ji (react-dom.production.min.js:3958)
    at Ga (react-dom.production.min.js:5512)
    at $a (react-dom.production.min.js:5534)`

**Comment by Kunibert-007** [comment]
![console](https://user-images.githubusercontent.com/35669927/53832016-6b4eba80-3f86-11e9-9bee-393c71fbd9ab.PNG)

**Comment by AlCalzone** [comment]
Da werden ein paar Zeichen im regulären Ausdruck nicht escaped. @GermanBluefox

**Comment by GermanBluefox** [comment]
> Da werden ein paar Zeichen im regulären Ausdruck nicht escaped. @GermanBluefox

Wer kommt auf die Idee die Objekte mit Klammern zu nennen.....
