### ISSUE TITLE
Script Tab: Show Folders above scripts

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#357]
At the moment, all files no matter if they are scripts or folders are listed in alphabetic order. IMHO we should show the folders in alphabetic order and below the scripts in alphabetic order. In most OS this is the default setting for listing files. Example:
![Bildschirmfoto von 2019-03-11 20-18-23](https://user-images.githubusercontent.com/25484431/54151328-dd1d7d00-443a-11e9-85be-20d8a86f3a55.png)

and: 

![Bildschirmfoto von 2019-03-11 20-19-17](https://user-images.githubusercontent.com/25484431/54151403-06d6a400-443b-11e9-8897-8acf853259b0.png)

**Comment by GermanBluefox** [comment]
Done in 4.8.5
