### ISSUE TITLE
Schedule wird nicht erkannt/ausgelöst

### ISSUE THREAD

**Issue by CrazyOrange** [ioBroker/ioBroker.javascript#358]
`
schedule('{"time":{"exactTime":true,"start":"sunrise"},"period":{"days":1}}'
, function () 
{
    log("WakeUp Schedule");
});
`

Versionen:
* admin: 3.6.0
* Script Engine: 4.1.12
* js-controller: 1.5.7
* npm: 3.10.10
* node: 6.14.4

Ich hatte schon immer das Problem, dass nach dem Starten des Script im Log
> registered 0 subscriptions and 0 schedules

steht. Als ich anstatt "sunrise" eine feste Uhrzeit benutzt habe wurde das Script aber trotzdem zur richtigen Uhrzeit ausgelöst (trotz der registered 0 subscriptions Meldung).
Seitdem ich allerdings auf "sunrise" umgestellt habe wird das Script nicht mehr gestartet.

Meine Astrodaten sind im JavaScript Adapter eingetragen (in den Systemeinstellungen sind keine vorhanden).

**Comment by Apollon77** [comment]
I'm very surprised about the schedule definition ...is this really allowed?!

https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#schedule

**Comment by CrazyOrange** [comment]
That is what the assistent is suggesting me.
It worked with
`'{"time":{"exactTime":true,"start":"00:00"},"period":{"days":1}}'`
bofore. But as said it still staid 0 schedules.

**Comment by GermanBluefox** [comment]
> I'm very surprised about the schedule definition ...is this really allowed?!
> 
> https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#schedule

This is a new feature.

**Comment by Ropdepil** [comment]
Hab das gleiche Problem mit Zeitplan und astro. Wenn ich bestimmt zeiten nutze funktioniert der Zeitplan. Wenn ich einen die normalen Astrotrigger (nicht schedule) nutze funktioniert es auch. Nur in verbindung mit dem Zeitplan leider nicht
