### ISSUE TITLE
4.1.12 Fehler in "Zeitplan definieren - Wizard"

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.javascript#361]
Es gibt hier gleich drei Probleme im unteren Teil bei "Gültigkeit von"

- Gibt man ein Datum aus 2018 ein, was ich zur Erinnerung machen wollte, dann ist das zwar technisch möglich (wird angezeigt und ist auswählbar) aber es wird nicht mit OK übernommen

- wenn man von Hand das Feld tt.mm.jjjj beschreiben möchte, dann gibt man ein z.B. 17 08 2019. Wenn das Feld mm mit 03 für März vorbelegt ist, dann wird tt gelöscht wenn man die 0 von 08 eingibt, weil dann ja in mm 00 stehen würde. Gleiches passiert wenn man 2019 eingibt, dann werden tt und mm gelöscht

- Wenn man dann auf Abbrechen klickt ist der gesamte Baustein gelöscht.

**Comment by GermanBluefox** [comment]
>Gibt man ein Datum aus 2018 ein

Das Datum wird weg optimiert.

> Punkt2

Das verhalten wurde bissl verändert... Aber man muss schnell eingeben.

> Punkt 3 

Ich kann nicht reproduzieren
