### ISSUE TITLE
Vorhandene ID's in enum.functions.xxx werden vom Skript ignoriert - v4.1.12

### ISSUE THREAD

**Issue by StopAndG0** [ioBroker/ioBroker.javascript#364]
Folgendes Skript funktioniert seit Version 4.x.x nicht, mit Version 3.6.4/5 läuft es einwandfrei. Das Skript soll alle Xiaomi Sensoren im Gewerk Fenster (“enum.functions.Fenster“) erkennen. Die Xiaomi's über Zigbee müssen nativ vorhanden sind, nur so tritt der Fehler auf. Mit virtuell angelegten devices/ID's funktioniert das Skript.

```
const miFenster = $('state[id=*.opened](functions="Fenster")');

miFenster.each(function(id, i) {
    log(id);
    log(getObject(id).common.name);
});
```

Das Log unter v4.1.12, hier werden die ID's ignoriert: 

```
15:04:59.397	info	javascript.0 Stop script script.js.Test
15:04:59.478	info	javascript.0 Start javascript script.js.Test
15:04:59.479	info	javascript.0 script.js.Test: registered 0 subscriptions and 0 schedules

```

Und Log unter v3.6.4 mit erkannter ID:

```
14:45:52.986	[info]	javascript.0 Stop script script.js.Test
14:45:54.156	[info]	javascript.0 Start javascript script.js.Test
14:45:54.157	[info]	javascript.0 script.js.Test: zigbee.0.00158d0002d4882e.opened
14:45:54.158	[info]	javascript.0 script.js.Test: Test-TFK01
14:45:54.158	[info]	javascript.0 script.js.Test: registered 0 subscriptions and 0 schedules
```

ID ist vorhanden in "enum.functions.Fenster / members":

```
{
  "_id": "enum.functions.Fenster",
  "common": {
    "name": "Fenster",
    "members": [
      "zigbee.0.00158d0002d4882e.opened"
    ],
    "icon": "",
    "color": false
  },
  "type": "enum",
  "from": "system.adapter.admin.0",
  "ts": 1553003729001,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```

**Comment by peoples0815** [comment]
Bei mir genau das gleiche Verhalten.
Nur nebenbei die info dass eine direkte subscription via `on({id: 'zigbee.0.XXXXXXX.occupancy'/*Occupancy*/, change: "ne"}, function (dp) {` funktioniert bestens.

**Comment by Apollon77** [comment]
Geht es wenn sie Objekt Verknüpfung neu hergestellt wird?

**Comment by peoples0815** [comment]
Nein, das war das erste was ich versucht habe, hatte die betroffenen Zigbee-Geräte aus dem "Gewerk" entfernt und neu eingelesen. Keine Änderung.

**Comment by Squelsh** [comment]
Also ich habe das Verhalten (auch mit Mi Sensoren von Xiaomi) auch in Version 3.6.7
Ich kann nicht auf Ereignisse in der functions Aufzählung reagieren und die IDs sind bei mir auch leer.

**Comment by Apollon77** [comment]
please check with js 4.5.0 (Now on GitHub)
