### ISSUE TITLE
Falscher Wert im Datenpunkt

### ISSUE THREAD

**Issue by Cytron1980** [ioBroker/ioBroker.javascript#367]
![blockly](https://user-images.githubusercontent.com/37205346/55619006-20e47780-5798-11e9-9fc6-0656a733d83c.jpg)
Habe per Blockly das Script erstellt, welches mir einen Datenpunkt auf 75 schreiben soll. dieses wird auch ausgeführt. Allerdings schreibt er mir anstatt die 75 eine 1 auf den Datenpunkt. Dieses Verhalten kam ohne eine Änderung des Scriptes. Aufgefallen ist es bei der JavaScript Version 3.6.4, die ich aber auch nicht bewusst geupdated habe.
Schreibe ich den Wert 75 in den Datenpunkt und führe dann das Script aus wird tatsächlich wieder eine 1 rein geschrieben.

**Comment by paul53** [comment]
Kann es sein, dass der Datenpunkt die Eigenschaft common.max = 1 hat ?

**Comment by Apollon77** [comment]
EWas ist es denn für ein Gerät (Dein Rollladen)? Homematic? Was anderes? Es gibt generell 0..100 oder 0..1 definitinen bei "Levels" je nach Adapter. ggf muss Du 0.75 setzen.

**Comment by Cytron1980** [comment]
Hallo und danke für eure Hilfe. Habe mittlerweile herausgefunden, dass durch Eingabe der Zahl 75 die Funktion nicht mehr funktioniert wie früher. Schreibt man die 75 in ein Textfeld klappt wieder alles wie bisher. Der Grund ist mir nicht bekannt. Aber so klappt es wieder in jedem Fall.
