### ISSUE TITLE
Cannot Import Script 

### ISSUE THREAD

**Issue by virgin09** [ioBroker/ioBroker.javascript#368]
4.1.12 Import Script under chrome doesn’t work. Please fix. Thx

**Comment by olli0815** [comment]
Gott ist das ein Krampf, lieber Dev. bitte erst solche major bugs ausmerzen, bevor 100erte Leute Ärger haben
Danke

**Comment by Apollon77** [comment]
Ja dieser Ton von Dir ist ein großer Krampf, lieber User. Sehr schade :-(

Wenn der Bug in Chrome existiert dann mal nen anderen Browser versucht?

Downgrade gehen easy im Admin. Unter Adapter einfach beim relevanten Adapter ganz rechts das Icon nehmen, andere Version auswählen und downgraden. Gar kein Krampf.

**Comment by olli0815** [comment]
Der Ton "liest" sich wohl schärfer als er ist....
Downgrade ging, andere Browser nicht...

**Comment by GermanBluefox** [comment]
lieber @olli0815 du hast die Möglichkeit selbst den Fehler zu fixen. Code liegt doch offen.
