### ISSUE TITLE
Javascript Script Tab öffnet nur manchmal

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.javascript#373]
Bei click auf den Script tab in Admin öffnet sich der Adapter nur in seltenen fällen. Meistens hängt das System bei der Anzeige mit dem Kreisel. Version Javascript adapter 4.1.12, Admin Version 3.6.0. Im Browser log (F12) finde ich folgende Meldungen... 
`universalModuleDefinition:3 WebSocket connection to 'wss://xxxxx/socket.io/?EIO=3&transport=websocket&sid=Zo4D6TeEKV7M4bulAAAR' failed: Error during WebSocket handshake: Unexpected response code: 400
n.doOpen @ universalModuleDefinition:3
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}.
socket.io.js:4 WebSocket connection to 'wss://xxxxx/socket.io/?ws=true&EIO=3&transport=websocket&sid=vgsOORSOt2Yub62aAAAS' failed: Error during WebSocket handshake: Unexpected response code: 400
n.doOpen @ socket.io.js:4
n.open @ socket.io.js:3
n.probe @ socket.io.js:3
n.onOpen @ socket.io.js:3
n.onHandshake @ socket.io.js:3
n.onPacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:3
n.onPacket @ socket.io.js:3
r @ socket.io.js:3
(anonymous) @ socket.io.js:3
e.decodePayloadAsBinary @ socket.io.js:3
e.decodePayload @ socket.io.js:3
n.onData @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:3
i.onData @ socket.io.js:3
i.onLoad @ socket.io.js:3
hasXDR.r.onreadystatechange @ socket.io.js:3
Connection.js:250 Subscribe logs
DevTools failed to parse SourceMap: https://xxxxx/js/app.js.map`

**Comment by RipdEaTh** [comment]
Moin,

ich habe das selbe Phänomen. Dies bereits seit längerem und über verschiedene Adapterversionen hinweg. Was ich festgestellt habe: Installiere ich den Javascript-Adapter neu (egal welche Version), kann ich den Tab einmalig aufrufen. Danach ist dies nicht mehr möglich, es erscheint immer nur der Kreisel.

Cache im Browser bereits geleert, verschiedene Browser und Rechner ausprobiert. 

In der Console sind ebenfalls die Warnings zu den fehlenden "message strings" vorhanden. Sonst keine weiteren Einträge..

**Comment by nkleber78** [comment]
Das problem scheint der user zu sein. Ich verwende einen User der zu der Administrator Gruppe gehört, aber nicht den Admin der fix angelegt ist. Wenn ich den Admin verwende geht es problemlos, verwende ich meinen User geht es nicht. Werde weiter testen ob das wirklich der Grund ist oder nur derzeit so ein effekt ist

**Comment by RipdEaTh** [comment]
Ich kann die Aussage bestätigen - mit dem Admin-Benutzer läuft es ohne erkennbare Probleme. Nutze ich den selbst angelegten Account mit Administrator-Rechten so lädt der Script-Tab nicht!

**Comment by quorle** [comment]
Kann ich auch so bestätigen.
Mit einem "angelegtem user" gibt es Probleme beim laden.
Mit dem Admin-User gibt es keine Probleme. 

Vielleicht kann dies jemand fixen?

Hier Consolen LOG mit (F12) unter Chrome Version: 74.0.3729.169 (Offizieller Build) (64-Bit)
```
jquery.fancytree-all.js:113 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
v @ jquery.fancytree-all.js:113
Connection.js:250 Subscribe logs
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}.
BlocklyEditor.js:94 Detected custom blockly: cloud
BlocklyEditor.js:94 Detected custom blockly: telegram
BlocklyEditor.js:94 Detected custom blockly: iot
i18n.js:41 Translate: Show only running scripts
i18n.js:41 Translate: Show only paused scripts
i18n.js:41 Translate: Show only scripts with problems
i18n.js:41 Translate: Expand all
i18n.js:41 Translate: Collapse all
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Debug options
i18n.js:41 Translate: Change layout
i18n.js:41 Translate: Show only running scripts
i18n.js:41 Translate: Show only paused scripts
i18n.js:41 Translate: Show only scripts with problems
i18n.js:41 Translate: Expand all
i18n.js:41 Translate: Collapse all
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Debug options
i18n.js:41 Translate: Change layout
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Debug options
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Debug options
i18n.js:41 Translate: Show only running scripts
i18n.js:41 Translate: Show only paused scripts
i18n.js:41 Translate: Show only scripts with problems
i18n.js:41 Translate: Expand all
i18n.js:41 Translate: Collapse all
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Debug options
i18n.js:41 Translate: Change layout
admin.js:1486 clear
Connection.js:250 Subscribe logs
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}.
```

**Comment by Spegeli** [comment]
So jetzt hat es mich auch erwischt. 
Bisher konnte ich Problemlos auf die Scripte über einen selbst angelegten Admin User zugreifen.
Seit heute erscheint allerdings wie bei den anderen Usern hier nur noch das ioBroker Logo und dann geht nix mehr. Über den Standard Admin lassen sich die Scripte weiterhin Problemlos aufrufen.

**Comment by GermanBluefox** [comment]
please retest with js-controller 2.0 and latest javascirpt adapter

**Comment by nkleber78** [comment]
Bei mir klappt es soweit mal auch mit dem anderen User. Mal schauen ob das so bleibt... Danke fürs prüfen!

**Comment by ginvibe** [comment]
bei mir klappt es nur mit dem Admin User mit einem selbst angelegten nicht.
