### ISSUE TITLE
Problem with getEnums()

### ISSUE THREAD

**Issue by xolom** [ioBroker/ioBroker.javascript#374]
If I use following code: `getEnums('rooms')` i get following error:
![Screen Shot 2019-04-29 at 4 59 59 PM](https://user-images.githubusercontent.com/1269774/56926234-80048600-6ad1-11e9-9223-33219af9f79c.png)

Usually this should work, right?

**Comment by Apollon77** [comment]
How is the enum "rooms" looking in your system?

**Comment by schreda** [comment]
I checked, that there is no empty entry
![Screen Shot 2019-04-29 at 11 04 25 PM](https://user-images.githubusercontent.com/1269774/56926982-3f0d7100-6ad3-11e9-8d2e-ef7f64468aba.png)

**Comment by schreda** [comment]
I would like to refer to this issue
https://github.com/ioBroker/ioBroker.javascript/issues/123

After restarting the adapter, the error is gone!

**Comment by GermanBluefox** [comment]
Should be fixed in 4.1.16.
