### ISSUE TITLE
Schedule function not working

### ISSUE THREAD

**Issue by ChristianH99** [ioBroker/ioBroker.javascript#382]
Unfortunately I still have problems with the schedule function in 4.1.12
Nothing happens when runing this code.

Code:
```
schedule("*/2 * * * * *", function () {
    log("Will be triggered every 2 seconds!");
});
```

**Comment by Apollon77** [comment]
The schedule is incomplete. Please provide a full schedule string. „*/2 * * * * *“ ( but please check if this is correct number of elements. Written Out of my head.

**Comment by AlCalzone** [comment]
He did provide one. You don't see it on mobile apps because he did not put the code inside a code block.

**Comment by Apollon77** [comment]
Ahhhh ;-))

**Comment by paul53** [comment]
Tested under version 4.1.13:
`
17:37:10.008 | info | javascript.1 script.js.common.Test: Will be triggered every 2 seconds!
17:37:12.002 | info | javascript.1 script.js.common.Test: Will be triggered every 2 seconds!
17:37:14.001 | info | javascript.1 script.js.common.Test: Will be triggered every 2 seconds!
17:37:16.008 | info | javascript.1 script.js.common.Test: Will be triggered every 2 seconds!
`

**Comment by GermanBluefox** [comment]
Cannot reproduce it too.
![image](https://user-images.githubusercontent.com/4582016/63643510-513e9b00-c6d2-11e9-96c9-5ceb46cef74c.png)
