### ISSUE TITLE
In Blockly, change position of Logfile in dark  layout

### ISSUE THREAD

**Issue by IOmountain** [ioBroker/ioBroker.javascript#384]
In Dark Layout you can not see the Icon for Changing Layout to switch the psition of the Logfile when using Blockly
![Bildschirmfoto vom 2019-06-02 17-36-39](https://user-images.githubusercontent.com/49717472/58763608-2c1c0f80-855d-11e9-823c-b3d2915d3154.png)

**Comment by GermanBluefox** [comment]
Fixed?
