### ISSUE TITLE
Blockly: Auswahlfunktion "Send To " funktioniert nicht

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#385]
Habe gerade mal die Javascriptadapterversion 4.1.12 installiert.
JS-Controller: 1.5.11
Node.js: v8.16.0
NPM: 6.4.1

Ich habe festgestellt, dass man im Blockly unter dem Reiter "Send To" nichts mehr auswählen kann. Ich habe den Telegram-Adapter installiert, jedoch lässt sich in Blockly dieser nicht einfügen.

**Comment by BuZZy1337** [comment]
https://forum.iobroker.net/post/176725

Bitte Rückmeldung ob das dein Problem gelöst hat..

**Comment by quorle** [comment]
> https://forum.iobroker.net/post/176725
> 
> Bitte Rückmeldung ob das dein Problem gelöst hat.. Und wenn ja, welchen Adapter du komplett entfernt hast.

Das Problem ist gelöst. Nun geht alles wieder. Aber beim löschen der einzelnen Adapter gibt es Fehler:

```

host.ioBroker | 2019-08-13 10:33:47.289 | error | Cannot write files: /opt/iobroker/iobroker-data/files/systeminfo.admin/_data.json: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/systeminfo.admin/_data.json'
-- | -- | -- | --
```
Oder kann man dies getrost ignorieren? Da immer noch ein paar Adapter ohne Zahl vorran stehen.

**Comment by Apollon77** [comment]
yu can ignore this error
