### ISSUE TITLE
v4.1.12/13 Blockly Scripts importieren funktioniert nicht.

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#388]
Ist mir schon in der v4.1.12 aufgefallen.
Scripte lassen sich weder über Datei-Dialog noch über Datei-Ablage importieren.
Getestet mit Chrome und Firefox.
![Error ScriptImport](https://user-images.githubusercontent.com/22603034/59036084-ed44cd00-886e-11e9-8fbc-0b337fee6985.png)

**Comment by ihavenonick** [comment]
läuft einwandfrei

**Comment by Rantanplan01** [comment]
mit v4.1.14 erledigt.
