### ISSUE TITLE
setTimeout marked as error

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.javascript#389]
The version 4.1.13 of the script engine marks setTimeout as wrong in the editor. The function works and it was also not marked as an error in previous versions.

**Comment by mcdhrts** [comment]
same by my installation. Also console and clearTimeout is marked

![image](https://user-images.githubusercontent.com/37240726/60756814-94e62400-a002-11e9-80f1-d1adef03ac5b.png)

**Comment by AlCalzone** [comment]
Seems that the nodejs typings are not properly loaded

**Comment by AlCalzone** [comment]
Fixed by #418
