### ISSUE TITLE
.toLocaleTimeString() gibt US Zeiten aus

### ISSUE THREAD

**Issue by Pittini** [ioBroker/ioBroker.javascript#390]
Hi,
bisher (node.js 8.16) konnte man

   let today = new Date();
    console.log(today.toLocaleTimeString());

verwenden. Seit update auf Node.js 10 gibt diese Anweisung AM/PM Zeiten aus. Abhilfe scheint:

   let today = new Date();
    console.log(today.toLocaleTimeString('de-DE',{ hour12: false }))

zu sein. Ist aber eher ein workaround denk ich.

**Comment by GermanBluefox** [comment]
Da kann man nicht viel machen. Node.JS mach das selbst und man muss suchen, wie es in node.js oder System eingestellt werden kann.

**Comment by GermanBluefox** [comment]
Und es sollte `new Date().toLocaleTimeString('de')` reichen

**Comment by Pittini** [comment]
> Und es sollte `new Date().toLocaleTimeString('de')` reichen

Ja, sollte. Tuts aber nicht nach meinen Tests. Abgesehen davon dürften damit alle älteren Scripte Probleme bekommen welche die Funktion nutzen. Aber ich akzeptiere natürlich dass Du es nicht ändern kannst. Ich hab Artikel zu dem Thema gefunden und es gibt wohl nen Weg um das wieder richtig zu machen, nur hab ich die Anleitung nicht wirklich verstanden. Evtl. sind ja die beiden Artikel hilfreich:
[https://stackoverflow.com/questions/53885354/date-tolocaledatestring-not-working-on-nodejs-v10-14-2](url)
[https://github.com/unicode-org/full-icu-npm](url)
