### ISSUE TITLE
objektbaum wird nicht geladen

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#391]
aus Blockly wird der Objektbaum nicht geladen
![grafik](https://user-images.githubusercontent.com/6681528/59556715-a3bf5500-8fc7-11e9-9a49-cf9551350af3.png)

sollte das ergeben
![grafik](https://user-images.githubusercontent.com/6681528/59556716-ade15380-8fc7-11e9-9380-ffddffec5357.png)

mit der adminversion 3.6.2 und javascript 4.1.12 (4.1.13) bekommt man eine leere seite mit dem consolen Fehler

![grafik](https://user-images.githubusercontent.com/6681528/59556727-d701e400-8fc7-11e9-89a5-4cd38ab7a797.png)

mit admin 3.6.2 und javascript 4.0.7 funktioniert es

**Comment by GermanBluefox** [comment]
PLease test with 4.1.16
