### ISSUE TITLE
[Feature Request] Blacklist and Whitelist for JS errors like "cannot find name"

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.javascript#393]
There are certain commands, which are being underlined red in the script editor, but work as intended. Example (adapter version 4.1.13):
![error](https://user-images.githubusercontent.com/39859059/60830806-54c8a200-a1b8-11e9-9f6a-f5114362978f.png)

Suggestion is to add a blacklist and whitelist to the adapter options to be able to add commands and the JavaScript editor would either ignore these as errors (whitelist) or would underline as error (blacklist).

**Comment by AlCalzone** [comment]
That is not possible unfortunately. 

We need to fix the errors that shouldn't be any. I didn't have the time yet to check why this broke.

**Comment by AlCalzone** [comment]
Duplicate of: #389
