### ISSUE TITLE
Blockly Variablen

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#394]
Bei Einfügen eines Datenpunkt-Triggers sollten die Variablen _value_ und _oldValue_ unter Variablen verfügbar sein. Das Gleiche sollte für die Timer-Variablen bei Einfügen von "Ausführen timeout" und "Ausführen Intervall" gelten.

**Comment by paul53** [comment]
Schön wäre auch, wenn sich die Farbe der Variablen von der Farbe der Trigger unterscheiden würde (Variablenfarbe z.B. wie Timer).

**Comment by GermanBluefox** [comment]
EIn paar Bilder werden helfen. Ich verstehe nicht was "Datenpunkt-Triggers" ist.
Nicht das ?
![image](https://user-images.githubusercontent.com/4582016/63642779-ed61a580-c6c4-11e9-8449-ba12fa60d978.png)

**Comment by paul53** [comment]
Ja, das (im Gegensatz zum Schedule-Trigger).
Bei Verwendung des Trigger-Blockes werden automatisch die lokalen Variablen _value_ und _oldValue_ erstellt, sind aber in Blockly nicht sichtbar, sondern müssen erst als globale Variablen erstellt werden, damit man sie (lokal) verwenden kann.

**Comment by GermanBluefox** [comment]
> Schedule-Trigger

Schedule-Trigger hat kein value/oldValue

**Comment by TDCroPower** [comment]
Ich glaub was hier gemeint ist, dass die Variablen value/oldValue die für den Trigger Block gesetzt werden auch ausserhalb des Blocks erreichbar sind?

Hier als Bild was gemeint ist, innerhalb des Triggers kann man die variablen verwenden aber ausserhalb nicht.

<img width="352" alt="Bildschirmfoto 2021-05-20 um 02 19 04" src="https://user-images.githubusercontent.com/6634116/118900735-f8854c00-b911-11eb-8599-d4f8f0f79f61.png">

Schaut man sich dazu den Javascript Code an, wird einem sehr schnell bewusst warum...
```
on({id: 'default', change: "ne"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  console.log((obj.state ? obj.state.val : ""));
  console.log((obj.oldState ? obj.oldState.val : ""));
});

(obj.state ? obj.state.val : "");
```
Es werden zwar die Variablen value und oldValue innerhalb des Blocks erstellt aber zu keiner Zeit verwendet, sondern wird bei der Verwendung vom Trigger Object "Variablen" zu "obj.state..." und "obj.oldState..." gegriffen.
Man könnte sich daher die Erstellung der 2 lokalen Variablen sparen um weniger Verwirrung zu generieren!?
Oder werden die an einer anderen Stelle verwendet die ich bislang noch nicht gesichtet habe?

**Comment by paul53** [comment]
Die Timer-Variablen sind seit Version 5.8.10 verfügbar.

**Comment by klein0r** [comment]
Hier ist alles gelöst, oder?
