### ISSUE TITLE
4.1.14 - Anzeigefehler

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.javascript#396]
Hallo,
beim verschieben laufen die Icons ineinander:

![Screenshot (3671)](https://user-images.githubusercontent.com/41079106/61251537-0472b680-a75b-11e9-8ec3-ded80c1e3bd5.png)

**Comment by AlCalzone** [comment]
Könnte daran liegen, dass der Bereich zu schmal ist.

**Comment by sigi2345** [comment]
> Könnte daran liegen, dass der Bereich zu schmal ist.

Ja, aber das war vorher nicht so.........
Auch das X geht ineinander:

![Screenshot (3692)_LI](https://user-images.githubusercontent.com/41079106/61370961-e8befb80-a893-11e9-9212-7da461a86798.jpg)

**Comment by xXBJXx** [comment]
ja kann ich bestätigen ist bei mir auch so das die Icons ineinander laufen in der 4.1.13 war das nicht so.
V. 4.1.14
![Anmerkung 2019-07-17 132211](https://user-images.githubusercontent.com/32600934/61371815-ed84af00-a895-11e9-96f7-15cd2c37aee2.png)
V.4.1.13
![Anmerkung 2019-07-17 131839](https://user-images.githubusercontent.com/32600934/61371633-7d762900-a895-11e9-891e-703c62b68fef.png)

**Comment by GermanBluefox** [comment]
Please test

**Comment by xXBJXx** [comment]
Mit der Version 4.1.16 funktioniert es so wie es soll
