### ISSUE TITLE
4.1.14 Probleme im Dunklen Modus

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.javascript#397]
Wen man im Dunklen Modus einen Datenpunkt auswählen möchte siecht man die schrift im auswahl Fenster nicht.
Wurde schon mit 3 Browser ausprobiert 
[hier die post im Forum mit Bildern](https://forum.iobroker.net/topic/23863/scriptengine-4-1-14-probleme-im-dunklen-modus/4)

**Comment by ihavenonick** [comment]
Ist da schon einer dran?

**Comment by GermanBluefox** [comment]
Please test 4.1.16

**Comment by xXBJXx** [comment]
mit 4.1.16 ist alles sichtbar danke
![Screenshot_1](https://user-images.githubusercontent.com/32600934/63726759-7fe97c80-c85e-11e9-9d65-910290cd91b1.png)
