### ISSUE TITLE
Import own modules in another typescript file

### ISSUE THREAD

**Issue by githtz** [ioBroker/ioBroker.javascript#399]
Hi there everyone. I've written a helper class that I'd like to use in some of my other typescript files, but it seems I can not import it. Any help?

**state-push-service**
```typescript
/**
 * Single push state
 */
export interface PushState {
    stateId: string;
    value: any;
}

/**
 * Service that executes multiple state changes without causing conflicts 
 */
export class StatePushService {
    constructor(){ }

    /**
     * Push a single or multiple states for a single device
     */
    public pushState = (pushState: PushState | PushState[]) => {
        // TODO
    }
}
```

**other-service**
```typescript
// does not work
import { StatePushService, PushState } from "services/state-push-service"; 
```

Error message looks like
```bash
Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/lib/../../services/state-push-service'
```

Of cource the module will not be found in the `node_modules`directory, because it's not part of that at all. But how can I import my own scripts?

Thanks you very much in advance!

**Comment by Apollon77** [comment]
Define it as global script and it will be prepended to all other scripts

**Comment by githtz** [comment]
@Apollon77 Morning, thanks for helping me out. I've tried that and it sort of worked after I removed the `export` modifiers from my module code.
It though looks like this solution sort of defeats the purpose of using typescript, since the editor does not recognize that module in the other files.
![image](https://user-images.githubusercontent.com/15327800/62345953-9406bc00-b4f4-11e9-916e-a99c264fb5cc.png)
Is there anything I can do about that?

**Comment by Apollon77** [comment]
@AlCalzone Any ideas on this one?

**Comment by AlCalzone** [comment]
It should recognize it... It works for me in 4.1.5 and I have global TypeScripts.

**Comment by githtz** [comment]
@AlCalzone Looks like my editor had some kind of hiccups. I just modified the module and after that it worked like a charm. :+1: 
Thanks for your help! I'll close this issue then.

**Comment by uwe72** [comment]
Can anybody help me with my (in my view similar) problem:
https://forum.iobroker.net/topic/49279/hilfe-bei-strukturierung-von-klassen-in-typescript

(sorry just in German)

**Comment by theknut** [comment]
But the problem is, whenever scripts under `global` are modified the js-adapter restarts and rebuilds all scripts. Isn't there a way to just import it like any other `*.ts` file? I want to write tests for my modules and therefore import those files into my tests. Putting them into `global` would mean there is a great overhead whenever making changes.

**Comment by uwe72** [comment]
> But the problem is, whenever scripts under `global` are modified the js-adapter restarts and rebuilds all scripts. Isn't there a way to just import it like any other `*.ts` file? I want to write tests for my modules and therefore import those files into my tests. Putting them into `global` would mean there is a great overhead whenever making changes.

Totally agree. I also miss this import feature in order to implement clean code.

**Comment by AlCalzone** [comment]
The Node.js feature that is necessary for doing this is not available yet without specific command-line flags.
So unfortunately it's not possible yet.

**Comment by theknut** [comment]
Whenever it is implemented on Nodes side, how would they import them. I
think the user scripts are not available on disk, are they?

AlCalzone ***@***.***> schrieb am Do., 14. Dez. 2023, 09:39:

**Comment by AlCalzone** [comment]
When the feature is available we can add something that allows users to define their own modules in the UI and then import them from scripts or other modules.

This will probably take some time though. The feature has been experimental since Node.js 13.

**Comment by uwe72** [comment]
> But the problem is, whenever scripts under `global` are modified the js-adapter restarts and rebuilds all scripts. Isn't there a way to just import it like any other `*.ts` file? I want to write tests for my modules and therefore import those files into my tests. Putting them into `global` would mean there is a great overhead whenever making changes.

I think this solutions goes in your direction:
https://forum.iobroker.net/topic/69840/erledigt-typescript-viele-common-global-scripte-cpu/43

But it is not so simple as u (and me want), because the java script/Type script files are extern

**Comment by theknut** [comment]
I'm aware of this way of importing it, but as you mentioned, not my type of
programming.

Am Do., 14. Dez. 2023 um 22:21 Uhr schrieb uwe72 ***@***.***>:
