### ISSUE TITLE
Bei Fehler im Script: Zeilennummern stimmen nicht (viel zu hoch)

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.javascript#4]
Bei Fehler im Script: 

Die im Log aufgeführten Zeilennummern stimmen nicht (viel zu hoch). Man findet anhand der Angabe die Stelle im Script mit dem Fehler nicht.

**Comment by Apollon77** [comment]
Nutzt Du globale Skripte? Die Globalen werden vor jedes andere Skript davorgebaut bei der Ausführung - damit kommen ggf solche hohen Nummern zustande. Passt es wenn DU die Anzahl der Zeilen der globalen Skripte einrechnest

**Comment by ldittmar81** [comment]
Cool wäre es, wenn es bei der Fehlermeldung die globale Skripte nicht berücksichtigt werden würden und wenn der Fehler dann im globalen Teil geworfen wurde, dann im Log den Namen der globale JS + Zeile ausgeben würde. Man kann aber z.Z. ein globalen Skript erstellen, der z.B. 10 oder 100 Zeilen hat und diese dann abziehen.

**Comment by GermanBluefox** [comment]
Das Problem ist mir bekannt, aber ich konnte keine Lösung finden.

2017-01-20 15:31 GMT+01:00 ldittmar <notifications@github.com>:

**Comment by ldittmar81** [comment]
Kein Problem. Ich werde mich mal ein bisschen in der Thematik einarbeiten und kann dann vielleicht hier und da mal helfen. Dann schaue ich mir mal diese Problematik an. ;-)

**Comment by GermanBluefox** [comment]
Eigentlich sollte (laut https://nodejs.org/api/vm.html#vm_script_runincontext_contextifiedsandbox_options) lineOffset gehen. 
Und das mache ich sogar:
https://github.com/ioBroker/ioBroker.javascript/blob/master/javascript.js#L2436

Aber geht nicht.

**Comment by GermanBluefox** [comment]
Sollte jetzt gefixt sein. BItte nachtesten

**Comment by Apollon77** [comment]
Bitte erneut öffnen wenn noch ein problem
