### ISSUE TITLE
Using \r\n in sendTo telegram

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.javascript#40]
`sendTo` in Blockly replaces `\r\n` from parameter values with `\\r\\n`, which of course does not work as an line break in Telegram for example.

This
![unbenannt](https://user-images.githubusercontent.com/29343914/29945200-833b90ac-8ea0-11e7-81dd-84a212898385.JPG)

becomes this
```
sendTo("telegram.0", "send", {
   "text": 'Lorem ipsum\\r\\ndolor sit amet.'
});
```

Please make `\r\n` immune to rewrite.

**Comment by Apollon77** [comment]
I would be more on the side to introduce a "add line break" block, so that you can build that text with three blocks

**Comment by AlCalzone** [comment]
What about an option "raw" for the text block to make the entire block non-rewritable?

**Comment by EvilEls** [comment]
***bump***
we need line breaks! ;)

**Comment by BuZZy1337** [comment]
Bluefox added a Blockly "new line" block with commit https://github.com/ioBroker/ioBroker.javascript/commit/ff1b57678f1a43e9c6e1925cbdf8cb841b07bb59
( https://forum.iobroker.net/viewtopic.php?f=21&t=4012&start=60#p141709 )

If that is not suitable for you, please reopen this issue.
Thanks!
