### ISSUE TITLE
Selector doesn't get some states

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.javascript#401]
I tried to use the blockly shown below to get all the event data from the ical adapter but only the datapoints which parent object is a channel are selected.
E.g. the contents of the folder `1` are selected and I can work with these but the content of the folder `10` is not selected and therefor I can't work with it.

The issue is reproduceable if you install the ical adapter and set it up to create preview states for more than 3 days (including "today"). From the fourth day onwards there doesn't seem to be a channel and not even a way to change the folder to a channel. This is an issue I already reported for the ical adapter but nevertheless this is an issue in the js adapter that the states aren't selected.

![image](https://user-images.githubusercontent.com/13995942/62821052-b476ec00-bb6e-11e9-9f81-d0664a9b11a3.png)
![image](https://user-images.githubusercontent.com/13995942/62821060-eb4d0200-bb6e-11e9-9951-50fa3c26684b.png)

**Comment by Apollon77** [comment]
Are they existing after you restarted the JavaScript Adapter?

**Comment by AlCalzone** [comment]
Have you tried without "channel" in the selector?

**Comment by BuZZy1337** [comment]
https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#---selector

You can select channels, states or devices.. You are selecting channels.. And it looks like "10" doesn't have the channel attribute set.. Maybe that's an issue of the iCal adapter?

**Comment by Xyolyp** [comment]
My bad: using `state[state.id=ical.0.events.*.*]` works just like I want it to.
