### ISSUE TITLE
4.1.14 Typescript, some commands are marked as errors, but work as expected

### ISSUE THREAD

**Issue by neopholus** [ioBroker/ioBroker.javascript#402]
Hi,

I use adapter version 4.1.14 and have a typescript that works.
Nevertheless, some commands are underlined in red and corresponding warnings are shown in the log:

With the following command I read all possible values of a Homematic system variable of type "Werteliste"/"value list":
> let possibleValues:string[]= Object.values(getObject('hm-rega.0.40027').common.states);

The following errors are displayed in the editor (and the log):
- ![grafik](https://user-images.githubusercontent.com/39877538/63130699-a5070100-bfbb-11e9-90b9-2a7766b6664c.png)
- ![grafik](https://user-images.githubusercontent.com/39877538/63130742-c9fb7400-bfbb-11e9-8700-c6fbcbbcc021.png)

With the following command I read active delays for a data point:
> var activeDelays = getStateDelayed('hm-rega.0.26907.ProgramExecute');

Should be ok as it is also described [here](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#getstatedelayed).

The following error is shown in the editor (and in the log):
![grafik](https://user-images.githubusercontent.com/39877538/63131040-ab49ad00-bfbc-11e9-9c57-4ea2016317d9.png)

Best regards
Stefan

**Comment by AlCalzone** [comment]
getStateDelayed: The definitions are missing
Object.values: Probably the wrong NodeJS definitions are used (or wrong ES version targeted)

common.states: `getObject` returns a generic ioBroker Object, because the method cannot know if it is a device, channel or state object. The easy solution is changing the line to
```ts
... (getObject("id") as iobJS.StateObject).common.states
```

**Comment by neopholus** [comment]
@AlCalzone:
Thank you for your analysis. I fixed the common.states problem as you described. It fixed this specific problem. Looking forward to the bugfix :)

**Comment by neopholus** [comment]
Just an addition: The function "setTimeout" is also not known.
Error message in editor: Cannot find name 'setTimeout'.

**Comment by AlCalzone** [comment]
Ok then there's something really wrong. It used to work and does for me in a slightly older version.

**Comment by neopholus** [comment]
Just to add some more information: The "setTimeout"-issue was already reported as issue #389.
Carsten reported also that is worked correctly before version 4.1.13. 
Thus at least a part of this issue is a Duplicate of #389.
