### ISSUE TITLE
Installation ohne Blockly ermöglichen

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#403]
Da sich der RAM-Bedarf einer JS-Instanz seit Version 3.6.4 mehr als verdoppelt hat, wäre es gut, man könnte JS auch ohne Blockly installieren

**Comment by AlCalzone** [comment]
Wie schließt du darauf, dass Blockly den RAM-Bedarf erhöht?

**Comment by paul53** [comment]
Es ist sicherlich nicht nur Blockly, aber gerade Blockly wurde im letzten Jahr stetig erweitert.

**Comment by AlCalzone** [comment]
Soweit ich das verstehe, läuft Blockly nur beim User im Browser, nicht auf dem Host. Hinter den Kulissen wird der Code schließlich in JS umgewandelt und das ausgeführt.

Interessant wäre es dennoch zu wissen, was ursächlich für den RAM-Bedarf ist.

**Comment by Apollon77** [comment]
Korrekt. JavaScript ram bedarf entwickelt sich mit der Anzahl an Skripten und Anzahl an States und Objekten weil der Adapter alle werte lokal vorhält. 

Hat mit blockly nichts zu tun.

**Comment by Apollon77** [comment]
Weiterhin: nodejs Version?

**Comment by paul53** [comment]
node v8.16.0: beide Systeme - Produktivsystem mit JS 3.6.4 (70 MB RAM), Testsystem mit JS 4.1.14 (2 * 140 MB RAM). Im Produktivsystem laufen etwa 5 mal so viele (und wit umfangreichere) Skripte als auf dem Testsystem. Vergleich der 
Dateien objects.json und states.json
Produktiv   2,5 MB      71 kB
Test           2,9 MB     224 kB

**Comment by AlCalzone** [comment]
States.json ist auf dem test system 3x so groß. Das könnte eine Ursache sein

**Comment by paul53** [comment]
Der Unterschied ist ca. 150 kB, nicht 70 MB.

**Comment by AlCalzone** [comment]
Das ist richtig, allerdings hängen im RAM noch einige Informationen mehr an einem Zustand. Wie viele Zustände sind es denn auf den beiden Systemen?

**Comment by paul53** [comment]
Zahl der Zustände
Produktiv: 530
Test: 790

**Comment by AlCalzone** [comment]
Ok das sind zwar deutlich mehr, aber noch keine Verdopplung. Hast du Möglichkeiten, über einen Memory Profiler anzuschauen, wie sich der RAM-Verbrauch verteilt?

**Comment by paul53** [comment]
Soweit reichen meine Linux-Kenntnisse nicht.

**Comment by AlCalzone** [comment]
Glaube auch nicht dass die nötig sind. Ich dachte da an:
* Node ausführen mit --inspect flag
* Per Chrome oder anderen Dev-Tools an den Prozess anhängen
* im Profiler RAM-Verbrauch anschauen

**Comment by GermanBluefox** [comment]
Es ist definitiv nicht nicht wegen Blockly. Blockly wird nur im Browser ausgeführt.
