### ISSUE TITLE
Script Import (zip Datei) klappt nicht

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.javascript#404]
https://forum.iobroker.net/topic/24504/script-import-zip-datei-klappt-nicht

**Comment by Apollon77** [comment]
Can you please add an affected zip file here or in Forum Thread.

**Comment by bahnuhr** [comment]
Hallo Ingo,
Ich werde nicht meine sämtlichen Scripte hier oder anderswo einstellen.
Dort sind zahlreiche Passwörter, etc. enthalten.
Diese Aufforderung geht m.e. zu weit.
Mfg
Dieter

**Comment by Apollon77** [comment]
Kannst Du es dann mit ein paar testskripten nachstellen und das hier posten? Irgendetwas was der Entwickler direkt nutzen kann um es anzusehen

**Comment by bahnuhr** [comment]
Hallo,
ich habe es ja hinbekommen mit einem downgrade. Nun sind ja alle Scripte geladen worden.
Ein Export einzelner Scripte per zip ins nicht möglich.
mfg

**Comment by AlCalzone** [comment]
Eine Fehlermeldung aus dem Log oder Browser-Konsole wäre sicher auch hilfreich

**Comment by GermanBluefox** [comment]
Should be fixed in 4.1.15

**Comment by fbeister** [comment]
Hier ein "me too", aber für Adapterversion 4.1.16 unter Linux, getestet mit Chrome 76.0.3809.100 und Firefox 68.0.2

Ich habe ein ZIP exportierd und dann versucht es direkt wieder zu importieren. Weder per Drag&Drop noch per Dialog wird die Datei akzeptiert. Es bleibt bei der Anzeige "Legen Sie einige Dateien hier ab"

Browser Konsole sagt nix was nach Fehler aussieht. Wenn es für den OP jetzt funktioniert, kann ich gerne noch ein weiteres Issue aufmachen anstatt mich hier anzuhängen.

**Comment by GermanBluefox** [comment]
Ich kann leider den Fehler nicht reproduzieren....

**Comment by bahnuhr** [comment]
Schade

**Comment by Aquasolar** [comment]
der Fehler liegt am Export der Zipdatei. Zu Jahresbeginn exportierte Scripten kann ich importieren. Die mit V 4.1.12 nicht.

**Comment by fbeister** [comment]
Könntest du aus der Zipdatei mal die Metadateien hochladen? Vielleicht sieht man dann schon, welcher Eintrag das Problem verursacht. Ich benutze den Import so dass ich meine extern editierten Skripte zusammenpacke und mit händisch erstellten Metadateien versehe. Ich würde dann einfach Eintrag für Eintrag durchgehen und immer wieder versuchen zu importieren bis es klappt.

**Comment by Aquasolar** [comment]
der Bug ist in js-controller 2.* behoben. Den muss man sich aber von
Github ziehen, da die aktuell freigegebene Version 1.5.14 ist.

**Comment by GermanBluefox** [comment]
js-controller 2.0.x is now in latest

**Comment by fbeister** [comment]
Habe gerade JS-Controller 2.1 mit Script Engine 4.3.3 ausprobiert. Chrome und Firefox auf GNOME3 Ubuntu 18.04 (clientseitig) funktionieren nicht. Die gleiche Datei (frisch exportiert) funktioniert mit einem Firefox clientseitig unter Windows. Ich werde gerade mal selber auf Bugsuche gehen ;-)

**Comment by GermanBluefox** [comment]
Fixed?

**Comment by Aquasolar** [comment]
JaAm 03.02.2020 18:10 schrieb Bluefox <notifications@github.com>:Fixed?
