### ISSUE TITLE
Blockly "Actual time as month as text" shows wrong text in October

### ISSUE THREAD

**Issue by dalgoist** [ioBroker/ioBroker.javascript#408]
As it's the first of october I noticed that the Output of the "Actual time as" block is wrong in october when you select the output "as month as text". This appears when you select English, German or Russian as output. The english output is "Octctctober", the russian "Октктктябрь" and the german "Oktktktober". There is always the second and third letter three times in a row instead of one time.

**Comment by padrino-x** [comment]
Confirmed. Just stumbled over this, when my Echo started to stutter...

**Comment by GermanBluefox** [comment]
Closed?
