### ISSUE TITLE
Can not open script tab in admin

### ISSUE THREAD

**Issue by twonky4** [ioBroker/ioBroker.javascript#41]
Why is this MSG object there?
https://github.com/ioBroker/ioBroker.javascript/blob/87874409023fcd921cc87fc9bb64dcc4b9d14292/admin/tab.js#L1786

I get a javascript error: 
> Uncaught ReferenceError: MSG is not defined
>    at tab.js:1777
>    at loadScripts (tab.js:1721)
>    at loadCustomBlockly (tab.js:1749)
>    at Scripts.init (tab.js:1776)
>    at tab.js:1769

And the scripts tab in admin doesn't opened.

If I add a `var MSG = new Object();` before this line the scripts tab opened. But I don't if it is correct.

Can you please check this?

**Comment by GermanBluefox** [comment]
Should be fixed with https://github.com/ioBroker/ioBroker.javascript/commit/57ff729b0304030c0f8910101cab4ef385d136e8

**Comment by twonky4** [comment]
Yes, issue was fixed. Thx
