### ISSUE TITLE
Skripte geben immer die Meldung " Instanz ist deaktiviert"

### ISSUE THREAD

**Issue by EduardSarjadjuk** [ioBroker/ioBroker.javascript#410]
Hallo,
folgende ist mir aufgefallen:
Alle Skripte geben mir die Meldung die "Instanz ist deaktiviert". 
Die Skripte scheinen dennoch zu funktionieren. 
Ist das ein Fehler ? Bei der Version 4.1.16 kam die Meldung nur für paar Sekunden und ist dann verschwunden. 
Würde mich über ein kurzes Feedback freuen. 
Danke im Voraus!

**Comment by GermanBluefox** [comment]
Wo denn?

**Comment by Apollon77** [comment]
see also: https://forum.iobroker.net/topic/25179/aufruf-js-controller-2-0-beta-test/725

**Comment by Diginix** [comment]
Ich habe noch JS-Controller 1.5.14 und auch den Fehler.

**Comment by GermanBluefox** [comment]
Closed now?

**Comment by Diginix** [comment]
Works for me with 4.3.1

**Comment by EduardSarjadjuk** [comment]
yes
