### ISSUE TITLE
JS error with many languages on "send to"

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.javascript#411]
If I choose Portuguese as the language for the ioBroker, I can not open "Send to". A JS error message appears in the console.

<img width="482" alt="Screenshot_6" src="https://user-images.githubusercontent.com/9552828/66598665-ca6e5080-eba1-11e9-98fa-4ad36c7b2c7a.png">

**Comment by ldittmar81** [comment]
Deutsch und Englisch geht... sonst nicht

**Comment by ldittmar81** [comment]
Sorry.. its a bug on email adapter

**Comment by GermanBluefox** [comment]
ON email, on iot, on cloud....
please add "pt" here: 
https://github.com/ioBroker/ioBroker.iot/blob/master/admin/blockly.js#L8
https://github.com/iobroker-community-adapters/ioBroker.email/blob/master/admin/blockly.js#L8
