### ISSUE TITLE
Anderes Log-Verhalten seit Update auf 4.3.0

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.javascript#412]
Hallo,
seit dem Update auf die V4.3.0, muss bei Log-Ausgaben explizit die Severity 'info' angegeben werden sonst erfolgt kein Log-Eintrag. Severity 'warn', 'error', usw. sind davon nicht betroffen.
Siehe auch hier im Forum:
https://forum.iobroker.net/topic/25702/update-scripte-engine-auf-4-3-0-kein-logging-mehr
Gruß Steffen

**Comment by Steff42** [comment]
works fine!!
thx Steffen

**Comment by Mic-M** [comment]
Works fine for me as well, many thanks for the rush fix!

**Comment by truegreyhound** [comment]
javasvript v4.3.4

Es hat sich leider noch etwas geändert. Ich habe diverse Ausgaben in meinen Skripten wie
`(loglevel == 'debug') log('Test', 'debug')`
Unabhängig davon, ob der Loglevel des Scriptadapters auf 'info' oder 'warn' stand, sind die Skriptausgaben geschrieben worden. Steht jetzt der Loglevel auf 'info' erfolgt nur eine Ausgabe  für Severity == ''|'info'|'error'|'warn'", 'debug' und 'silly' werden unterdrückt.
Wenn ich meine Skripte debugge, möchte ich nicht auch noch die ganzen Ausgaben des Adapters im Log haben. Bitte das "alte" Verhalten wieder herstellen!
