### ISSUE TITLE
search/filter in scripts doesn't work

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#414]
The search/filter function in scripts (javascript, blockly ...) doesn't has any effect on the tree.
Until version 4.1 searched words leads to a reduced tree with only the scripts that contains the searched word.

javascript 4.3.0 & 4.3.1
nodejs 10.16.3
npm 6.9.0
js-controller 1.5.14

**Comment by aleks-83** [comment]
Same problem here. Javascript adapter 4.3.1.
Win10 = Node.js v10.16.3 = NPM 6.9.0 = JS Controller 2.0.29 =

**Comment by Ilovegym66** [comment]
same here, Linux Mint 18.3, Nodejs v10.16.3, NPM 6.11.3, js-controller 2.0.33, javascript adapter 4.31.
In older Versions this works fine and we need it for bugfixing, and if a object was not found and you don't know the script name. ( I've about 300 scripts and more..  I use the search function daily..)

**Comment by Diginix** [comment]
With v4.3.2 and maybe even 4.3.1 the first 3 times after instance restart the search/filter works. But after third or fourth usage nothing happens anymore. Maybe this helps to find the bug.

**Comment by GermanBluefox** [comment]
With 3 times it could be a solution, but I still cannot reproduce it.
Has any one steps sequence to reproduce the error?

**Comment by Ilovegym66** [comment]
since js-controller 2.0.38 and javascript 4.3.2 it works fine, I cant reproduce it, too... any more..

**Comment by GermanBluefox** [comment]
But I can :(  Just enter search and then change some file. After that search does not work any more
