### ISSUE TITLE
Tab "script" only opens with Administrator, but not with other users having admin rights

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.javascript#415]
Logged in with Administrator: Tab _Script_ opens as expected --> everything fine
Logged in with another user having admin rights: Tab _Script_ stays in opening modus. The "circle" is shown  until leaving the page.

Circle:
![image](https://user-images.githubusercontent.com/54232526/66892623-7a055180-efec-11e9-8574-8888c8aa14e9.png)

**Comment by Apollon77** [comment]
How the user is configured? Please try to create a second  Admin group with all rights and assign user to this. Does it work then?

**Comment by GermanBluefox** [comment]
Do you have spaces or Upper letters in username?

**Comment by HGlab01** [comment]
> Do you have spaces or Upper letters in username?

no upper letters no spaces, just just 5 characters, no special characters

**Comment by HGlab01** [comment]
> How the user is configured? Please try to create a second Admin group with all rights and assign user to this. Does it work then?

The user is assigned to the group _system.group.administrator_
I created a new group _testadmin_ and assigned all rights to this group and added the user to this group. Same behavior.

**Comment by HGlab01** [comment]
Chrome JS log looks like. Maybe this helps.
I am using Authentifikaton and https.

`
clear
Connection.js:250 Subscribe logs
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}.
`

**Comment by GermanBluefox** [comment]
Can you test it with latest js-controller?

**Comment by HGlab01** [comment]
Well, I would be great not to take this risk. I would prefer not to be a first mover.

**Comment by Apollon77** [comment]
The js-Controller 2.0 is in latest repo since 2 weeks and installed >1900 times ... decide yourself ... else you need to wait till you might get a fix. Your choice.

**Comment by HGlab01** [comment]
Fair enough!
I will wait until I move to new hardware. 
I guess it is i quit common issue, see ticket #373

**Comment by HGlab01** [comment]
Updated to js-controller 2.0.35
Tab "Script" works now with non-root user!

by the way: installation of new js-controller worked not  in a first step. Fixer script did not help.
I had to create manually the folder _/home/iobroker_ and change the owner to _iobroker:iobroker_
Before I did this the following issue happend:
```
npm install ioBroker/ioBroker.js-controller
[sudo] Passwort for xxxx:
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/iobroker
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/iobroker'
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/iobroker']
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, mkdir '/home/iobroker'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: '/home/iobroker' },
npm ERR!   stack: 'Error: EACCES: permission denied, mkdir \'/home/iobroker\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/iobroker' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

**Comment by Apollon77** [comment]
Add as which user you installed it?

**Comment by HGlab01** [comment]
> Add as which user you installed it?

Standard user (not as root)
node: v10.16.3
npm: v6.11.2
OS: Ubuntu 18.04.3 LTS

**Comment by GermanBluefox** [comment]
Please reopen issue if still exist in js-controller.
