### ISSUE TITLE
Suggestion: Check syntax when datapoints are changed/moved/deleted.

### ISSUE THREAD

**Issue by aleks-83** [ioBroker/ioBroker.javascript#416]
Hi,

i have a suggestion for optimizing the javascript adapter.

Some of my scripts are not running all the time.
So when i move or delete a datapoint (maybe by uninstalling another adapter), my scripts doesn't recognize that the datapoint is gone.
Not before the script is started or triggered, there will be a error shown in the log.
I would like to prevent this behaviour.

**So the soulution could be that the scripts are checked for bad syntax when a datapoint is moved/changed/deleted.**
But maybe the javascript adapter won't recognize that there is a change at the datapoints.
So maybe there could be a handshake between Javascript adapter and ioBroker!?

Sorry, i am not a programmer, these are just my thoughts about a possible optimization.

**Comment by GermanBluefox** [comment]
UNable to implement
