### ISSUE TITLE
JS function in blockly not work properly?

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.javascript#423]
![Скриншот 23-10-2019 165449](https://user-images.githubusercontent.com/6728198/67460956-f29b8c00-f644-11e9-88fd-1279fc39bf4e.jpg)
![Скриншот 23-10-2019 165526](https://user-images.githubusercontent.com/6728198/67460971-f92a0380-f644-11e9-905a-fc5096dbf7ce.jpg)
When i try copy-paste this code ````sendTo('onvif.0', 'saveFileSnapshot', { "id": "onvif.0.192_168_1_10_80", "file": "/opt/iobroker/onvif/snapshot1.jpg" }, (data) => {
        console.log('image1 принят: ' + data);
        if (data === "OK")
            sendTo('telegram.0', { text: '/opt/iobroker/onvif/snapshot1.jpg', caption: caption1 });
    });```` i don't can save, when i click "Save" button..( 
It's my mistake or blockly?

**Comment by AlCalzone** [comment]
Please provide an example why you think its not working properly.

**Comment by itProfi** [comment]
Already..)

**Comment by itProfi** [comment]
> Please provide an example why you think its not working properly.
I can't close this window (with click on Save button) - can't close..( And it's NOT save my function..

**Comment by GermanBluefox** [comment]
Fixed in 4.3.2
