### ISSUE TITLE
Is it possible add "switch construction" in blockly?

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.javascript#425]
It would be very convenient if blockly will have switch - case construction - 
![Скриншот 24-10-2019 130433](https://user-images.githubusercontent.com/6728198/67475573-1f5c9d00-f65f-11e9-9f5a-33f58780f93f.jpg)

**Comment by GermanBluefox** [comment]
Have you code somewhere?

**Comment by itProfi** [comment]
No, it's just jpg, but i will find..

**Comment by AlCalzone** [comment]
BTW I would not have a check box for break but rather Fallthrough (no break).
Breaking after each case should be default.

**Comment by GermanBluefox** [comment]
I will not implement it myself, so we will take what we have, if we will have it.
but actually it is a duplicate to https://github.com/ioBroker/ioBroker.javascript/issues/182
