### ISSUE TITLE
Is there a reason, why stable version (4.1.12) is nearly 8 months old?

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.javascript#426]
The version provided by iobroker is from March 07, 2019.
There are a lot of newer versions with improvements. Why these versions are not published as stable versions?

![image](https://user-images.githubusercontent.com/54232526/67519478-3aeb9600-f6a7-11e9-92b5-0f6cb2508234.png)

**Comment by Apollon77** [comment]
many new features came in and there were also some issues reported and so we did not considered it ready for stable from our feeling. Especially for this central adapter where errors bring big problems for all users we are "better safe then sorry" ;-) I think the new version will come to stable soon

**Comment by HGlab01** [comment]
Thanks for explanation!
