### ISSUE TITLE
Copy & paste - one space at the beginning

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.javascript#432]
I do not know if that belongs to the adapter Javascript, because it is overarching. When I copy an object from an object tree and then enter it into the search field, there is a space at the beginning so that the object is not found.

![image](https://user-images.githubusercontent.com/35403739/67838736-4816e380-faf2-11e9-9552-27a0de2c9ed2.png)

**Comment by AlCalzone** [comment]
I've noticed something like this pretty often in browsers in general that they copy surrounding spaces. However this seems like an issue for the admin adapter ==> After pasting text in the search boxes, that text should be trimmed of surrounding whitespace.

/cc @Apollon77

**Comment by GermanBluefox** [comment]
I don't know how to solve it. By copy to clipboard the new line char is added at the start and at the end of copied text
