### ISSUE TITLE
Logfenster unter Skript gibt keine Ausgabe

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#433]
Seit 4.3.x erhalte ich immer mal keine Logausgabe unterhalb vom Skript. Allein ein Neuspeichern/Restart vom Skript gibt i.d.R. 3 Zeilen aus und auch diese fehlen. Das Skript läuft aber und wird auch gespeichert.
Wenn ich den Browsertab mit dem Javascript Adapter (#tab-javascript) nochmal neu lade (Strg+R o.ä.) funktioniert es danach. Daher gehe ich davon aus, dass beim vorherigen Laden des Fensters noch irgendwelche Dinge nicht korrekt geladen waren.

npm 6.9.0
nodejs 10.17.0
js-controller 1.5.14

**Comment by ajeder** [comment]
Hallo,
ich kann das Verhalten bestätigen. Bei mir ist es so, dass wenn ich parallel einen 2. Skript-Tab öffne, zum ersten zurück gehe und dann das Skript reloade, dann kommt eine Ausgabe im Logfenster unterhalb des Skriptfensters.

Ich benutze:
JSE 4.3.3, 
Node.js: v10.16.3
NPM: 6.9.0

**Comment by m-s-b** [comment]
Hallo,
bei mir ebenso.
JSE 4.3.3
Node.js v10.17.0
NPM 6.11.3

**Comment by Diginix** [comment]
Problem still exists with
javascript adater version 4.5.1
JS-Controller 3.0.20
nodejs 10.20.1
