### ISSUE TITLE
script export error 404 not found

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#434]
since 4.3.x the export of the scripts doesn't work any more, take a look please:
( in iobroker the error: file date-scripts.zip.zip not found, and in the webconsole the GET command ends with 404 not found )

![image](https://user-images.githubusercontent.com/36229898/67941922-f005dd00-fbd6-11e9-906c-f9051fab4763.png)

**Comment by Apollon77** [comment]
which js-controller?

**Comment by Ilovegym66** [comment]
js-controller 2.0.39, javascript 4.3.32, admin 3.6.10, node 10.16.3, npm 6.12.0

**Comment by Ilovegym66** [comment]
with javascript 4.3.3 the same..

**Comment by Apollon77** [comment]
Ich habe nochmal Code angeschaut wegen dem Export Problem und glaube die Ursache gefunden.

De JavaScript Adapter hat eine Liste der hosts und sucht sich daraus den ersten der aktiv ist raus. Der bekommt den Auftrag den Export zu machen und der speichert das dann in seinem eigenen Bereich. Dann wird die Download url erstellt und dem Browser übergeben. die url geht dann an den Admin Adapter in dem JavaScript gerade läuft. Der nimmt „seinen“ Host und versucht den Export zu lesen.

Na habt ihr ne Idee was passieren kann? 😉 und dass ist der Grund warum es nur manchmal bzw bei einigen Nicht tut ...

Auflösung: Der erste gefundene Host im JavaScript Adapter ist einfach ein anderer als der auf dem Admin läuft ;-(
Aber das kann man fixen.

**Comment by Ilovegym66** [comment]
Ich habe meine iobroker VM geclont, dort ohne die Clients ( standen natürlich durch die neue IP auf rot ), lief der Export sofort .
Melde ich einen Client dort an, gehts wieder nicht. Wenn ich jetzt also meine ganzen Scripte exportieren will, muss ich nur alle Clients abmelden..  :-)

**Comment by GermanBluefox** [comment]
Geht mit 4.3.5?

**Comment by Apollon77** [comment]
Und auch Admin 3.7.8 nutzen!

**Comment by Ilovegym66** [comment]
Mit Admin 3.7.8 und Javascript 4.3.5 geht's, super, Danke! 
Getestet von unterwegs mit vpn und Firefox und Chrome.
