### ISSUE TITLE
Add support for schedules from Fullcallendar

### ISSUE THREAD

**Issue by zone01-org** [ioBroker/ioBroker.javascript#437]
Hi i want to write a script where I disable all schedules from from e certain fullcalendar instance.
It is possible to set enabled a schedule with this:
```javascript
var sched = getObject('fullcalendar.0.2019-11-02T22_05_251');
log(JSON.stringify(sched,null,2))
log("enabled: " + sched.common.enabled)
sched.common.enabled = true
setObject('fullcalendar.0.2019-11-02T22_05_251', sched, function (err) {
    if (err) log('Cannot write object: ' + err);
});
```

But i had no luck getting all schedules with the [$ - Selector](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#---selector). 
Only States are returned by this script:
```javascript
var cacheSelectorState  = $('[id=fullcalendar.0.*]');
log(JSON.stringify(cacheSelectorState))
```

```json
{
  "0": "fullcalendar.0.info.lastConfiguredEvent",
  "1": "fullcalendar.0.info.lastEvent","length"
}
```

The schedule objects in Admin look like this:
![image](https://user-images.githubusercontent.com/6494583/68082854-21beb400-fe22-11e9-8f28-725074153bd2.png)

```json
{
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1572728725849,
  "common": {
    "name": "WZ to 23°C",
    "enabled": true
  },
  "native": {
    "type": "double",
    "oid": "hm-rpc.0.##########",
    "startValue": "23",
    "color": "#3A87AD",
    "endValue": "20",
    "cron": "0 17 ? * 0,6",
    "id": 1572728725633,
    "durationEditable": false,
    "intervals": [
      {
        "timeOffset": 19800000,
        "value": "20"
      }
    ]
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "fullcalendar.0.2019-11-02T22_05_251",
  "type": null
}
```

**Comment by GermanBluefox** [comment]
That must be a bug of fullcallender, becasue "type": null is not allowed

**Comment by GermanBluefox** [comment]
I just checked my fullcalendar and I have `"type": "schedule",`

**Comment by GermanBluefox** [comment]
See: https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#---selector
`$('schedule[id=*65]').each(function (id, i) {log(id);});  //print all schedules with 65 at the end`
