### ISSUE TITLE
Blockly Pushover Priorität falsch

### ISSUE THREAD

**Issue by xai1** [ioBroker/ioBroker.javascript#44]
Hi,
wie scheint ist beim Pushover Element die Priorität falsch.
Wenn still/silent ausgewählt wird erscheint im Code 1 und sobald Hohe Priorität ausgewählt wird -1
Sollte das nicht genau umgekehrt sein?
https://pushover.net/api

**Comment by GermanBluefox** [comment]
Please test new pushover version 1.0.3 (latest)

**Comment by xai1** [comment]
Vielen Dank! Ist bei mir leider noch falsch. Muss nach dem Adapter Update zusätzlich noch etwas getan werden?

**Comment by Apollon77** [comment]
Bitte ein 
iobroker upload pushover
iobroker upload vis
iobroker restart vis 

an Kommandozeile machen.

**Comment by xai1** [comment]
Jetzt passt es.
Vielen Dank
