### ISSUE TITLE
diverse anregungen

### ISSUE THREAD

**Issue by ltsalvatore** [ioBroker/ioBroker.javascript#440]
Hallo zusammen, 

eigentlich sind dies mehr Anregungen für ein nächstes update statt issues. 
und nach dem ich mittlerweile schon fast 2 jahre mit Javascript Script Engine (hauptsächlich blockly) in iobroker arbeite und sich in der hinsicht leider nichts getan hat, muss ich es doch mal anregen, denn ich finde das wäre eine große bereicherung und viele user wären sehr dankbar dafür. 

und zwar... 

1. scrollen = wieso ist es nicht möglich in dem scriptfenster **(Blockly)** mit dem mausrad zu scrollen, anstatt dabei die linke maustaste gedrückt halten und ziehen zu müssen?
bei sehr langen schripten wäre es mit dem mausrad um einiges einfacher
2. split view = wäre es nicht möglich das rechte fenster, wo gescriptet wird, auszudocken, sodass man dieses auf einem zweiten monitor im fullscreen sich anzeigen lassen könnte?
3. seit dem neuen design, ist die ansicht der tabs und der script bezeichnungen sehr unübersichtlich geworden... könnte man das nicht auch optimieren, sodass man ein paar mehr zeilen der scrpitnamen links als auch bei den tabs sehen könnte.. 

wie gesagt, das sind anregungen, die das arbeiten sehr erleichern würden und würde mich freuen, wenn das ein oder andere evtl. bei einem nächsten update umgesetzt werden könnte.

danke schon mal für die tolle arbeit soweit

**Comment by AlCalzone** [comment]
1. Funktioniert schon, ich brauche es ständig.

Was für einen Browser nutzt du?

**Comment by ltsalvatore** [comment]
> 1. Funktioniert schon, ich brauche es ständig.
> 
> Was für einen Browser nutzt du?

Hi AlCalzone
ich benutze Google Chrome in Kombination mit einer Logitech MX Master und Logitech Options Software.

**Comment by AlCalzone** [comment]
Im Firefox funktioniert es mit der gleichen Maus ;) 
Chrome müsste eigentlich auch problemlos gehen, zumindest funktioniert es hier bei mir: https://microsoft.github.io/monaco-editor/index.html (darauf basiert der Editor)

Gibt es irgendwelche Fehler in der Browser-Konsole, wenn du scrollst?

**Comment by obodeldog** [comment]
Kann es sein, dass ihr von zwei unterschiedlichen Dingen redet? Das scrollen der Skriptauflistung (also die Liste, in denen die ganzen Skripte stehen) geht. Nur IN blockly geht das scrollen mit dem Mausrad nicht. Das wäre auch für mich neu, wenn das geht. Sowohl Chrome wie auch Firefox lässt sich auch bei mir nichts scrollen.

**Comment by AlCalzone** [comment]
> Nur IN blockly geht das scrollen mit dem Mausrad nicht

Ohhh... Blockly... Das hab ich wohl überlesen, sorry! Wenn jemand von Skripten spricht, verstehe ich darunter nicht Klicki-Bunti :smile:

**Comment by ltsalvatore** [comment]
haha... sorry.... bin ein noob...☺️

aber ja ich meinte in Blockly

**Comment by GermanBluefox** [comment]
> 1. scrollen = wieso ist es nicht möglich in dem scriptfenster **(Blockly)** mit dem mausrad zu scrollen, anstatt dabei die linke maustaste gedrückt halten und ziehen zu müssen?
>    bei sehr langen schripten wäre es mit dem mausrad um einiges einfacher

Bitte hier issue erzeugen: https://github.com/google/blockly

**Comment by ltsalvatore** [comment]
> > 1. scrollen = wieso ist es nicht möglich in dem scriptfenster **(Blockly)** mit dem mausrad zu scrollen, anstatt dabei die linke maustaste gedrückt halten und ziehen zu müssen?
> >    bei sehr langen schripten wäre es mit dem mausrad um einiges einfacher
> 
> Bitte hier issue erzeugen: https://github.com/google/blockly
> Oder vielleicht geht das schon, nun kenne ich die Einstellungen nicht.

hab ich für punkt 1 nun gemacht. danke

**Comment by ltsalvatore** [comment]
ok.. jetzt war jemand so nett und hat das ganze in blockly scheinbar implementiert.. 

https://developers.google.com/blockly/guides/configure/web/move


ich kenn blockly nur in verbindung mit iobroker und ich weis jetzt leider auch nicht viel mehr als vorher.. 
deswegen frage ich mich gerade, wo ich diese einstellungen vornehmen müsste, damit das scrollen über mausrad nun funktioniert..

kann mir da vielleicht jemand hilfestellung geben.. 
muss ich da irgendwo auf meinem iobroker server gewisse dateien mit dem neuen code editieren?

**Comment by ltsalvatore** [comment]
ob mir da jemand vielleicht noch hilfestellung zu geben könnte?

**Comment by sbormann** [comment]
Ja, das wäre toll! Das Ziehen mit der Maus ist wirklich nervig bei großen Scripten. Anscheinen muss ja nur die Einstellung geändert werden.

**Comment by GermanBluefox** [comment]
Bei mir geht es in Chrome mit 4.6.11. Da wurde Blockly upgedatet

**Comment by GermanBluefox** [comment]
Punkt 2 ist technisch nicht möglich.
Punkt 3. Da brauche ich einen Design-Vorschlag. Ich komme mit meinen Design-Kenntnissen nicht weiter. Es ist schon klar, dass IMMER einen Text finden kann, der nicht passt?
