### ISSUE TITLE
Blockly Import (Blockly mit Funktionen) schlägt fehl

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.javascript#441]
In Version 4.3.2. schlägt der Import von Blocklys mit Funktionen fehl bzw. der Import klappt noch, aber es läßt sich nicht speichern.
Mit 4.3.1 funktioniert es.

Siehe hier im Forum
https://forum.iobroker.net/post/319085
oder auch hier
https://forum.iobroker.net/post/321480
oder hier
https://forum.iobroker.net/post/321581

**Comment by BramTown** [comment]
das Verhalten ist auch in v4.3.3 noch vorhanden

**Comment by chefrocker** [comment]
Kann ich bestätigen, mit einem Downgrade des Javascript Engine auf 4.3.1 läuft aber alles wieder störungsfrei

**Comment by Ilovegym66** [comment]
Ist mit der 4.3.4 behoben, gestern getestet.
