### ISSUE TITLE
Import aller exportierten Scripte mit 4.3.2 funktioniert nicht

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.javascript#442]
Der Import aller exportierten Scripte/Blocklys in 4.3.2. funktioniert nicht. Ich bin zurück bis auf 3.6.4, da funktionierte der Import.

Siehe Forum
https://forum.iobroker.net/post/319085

**Comment by Ilovegym66** [comment]
Hast du Clients am iobroker? Falls ja, beende diese einfach mal... ich kann keine Scripte exportieren(also ALLE Scripte exportieren-Funktion ) - das geht nur, wenn KEIN Client connected ist.

**Comment by BramTown** [comment]
auch hier der gleiche Hinweis ... in v4.3.3 ist das Problem auch noch vorhanden.
Ein (blockly) Beispielscript, welches eine Fehlermeldung hervorruft und sich nicht specihern läßzt habe ich angefügt
[telegramMenu_blockly.txt](https://github.com/ioBroker/ioBroker.javascript/files/3851336/telegramMenu_blockly.txt)

**Comment by GermanBluefox** [comment]
Vielleicht das? https://github.com/ioBroker/ioBroker.javascript/issues/434

**Comment by GermanBluefox** [comment]
> auch hier der gleiche Hinweis ... in v4.3.3 ist das Problem auch noch vorhanden.
> Ein (blockly) Beispielscript, welches eine Fehlermeldung hervorruft und sich nicht speichern läßt habe ich angefügt. In v4.3.1 funktioniert der Import einwandfrei (daher bin ich derzeit auf die v4.3.1 zurückgegangen)
> [telegramMenu_blockly.txt](https://github.com/ioBroker/ioBroker.javascript/files/3851336/telegramMenu_blockly.txt)

Ist telegram adapter installiert?

**Comment by BramTown** [comment]
ja, der telegram Adapter ist installiert
Und in den Einstellungen des javascript-Adapters ist "mytelegrammenu" als zusätzliches npm Modul eingetragen
![javascript](https://user-images.githubusercontent.com/30980239/69006506-e3e88200-092f-11ea-9e18-96d36994722a.png)

**Comment by GermanBluefox** [comment]
Läuft mit 4.3.5?

**Comment by GermanBluefox** [comment]
Admin 3.7.9, Javascirpt 4.3.5, js-controller 2.2.x => Dann muss funktionieren
