### ISSUE TITLE
interval functions not recognized

### ISSUE THREAD

**Issue by DanielWeeber** [ioBroker/ioBroker.javascript#443]
All interval functions are underlined in red, "Cannot find name" - even though they are working fine.

https://forum.iobroker.net/topic/22351/settimeout-setinterval-clearinterval-werden-angeblich-nicht-gefunden

**Comment by AlCalzone** [comment]
The issue has been fixed in https://github.com/ioBroker/ioBroker.javascript/pull/419 and https://github.com/ioBroker/ioBroker.javascript/pull/418
I'm not sure if that is already released. If not, it will be included in the next version.
