### ISSUE TITLE
Script Backup mit GIT

### ISSUE THREAD

**Issue by lkleen** [ioBroker/ioBroker.javascript#445]
Ich würde meine Scripte gerne über ein Git Repository verwalten. Dazu wollte ich im ersten Schritt einfach ein Repository für den Ordner anlegen in dem die Scripte liegen. Allerdings scheint alles in einer einzelnen json file gespeichert zu sein, so dass das nicht ohne Weiteres möglich ist. Könnte man eventuell die Export Funktionalität so erweitern, dass eine Synchronisation mit einem Git Repository möglich ist?

**Comment by Apollon77** [comment]
Mal die mirror function in JavaScript 4.3.x versucht?

**Comment by Ilovegym66** [comment]
...hab mich mangels dokumentation noch nicht getraut.... :-)  
was kann man da eintragen?

**Comment by Apollon77** [comment]
Einen lokalen Pfad wo die Skripte alle als Files gespeichert werden. Alle änderungen dort werden in die Skripte gesynct und anders herum

**Comment by AlCalzone** [comment]
Filtert der js Adapter denn das .git verzeichnis raus?

**Comment by Apollon77** [comment]
Das wäre zu testen ... Ansonsten kann man ja eine Verzeichnisebene zusätzlich nutzen :-) .git ist ja nur auf "Root" ... also ein vertzeichnis drin und da alles rein und es wäre ok denke ich

**Comment by cyptus** [comment]
Funktioniert soweit ganz gut bei mir.
mirror in den Order `/home/iobroker/files/scripts`
während das git Verzeichnis auf `/home/iobroker/files` liegt

Worauf man achten muss, ist dass man mit dem richtigen user in das Verzeichnis `git pull` ausführt, damit die Berechtigungen der files weiter passen.

Beim git pull dauert es manchmal etwas bis ein modifiziertes Script wieder im admin Portal zu sehen ist, außerdem wird es durch den pull gestoppt und muss manuell wieder gestartet werden.

**Comment by GermanBluefox** [comment]
Rechte-Problem sollte mit 4.3.4 weg sein
