### ISSUE TITLE
extendObject(id, obj, callback) in Javascript does not work as described

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#447]
Die Funktion extendObject des Javascript-Adapters erweitert das Objekt nicht mehr, sondern ersetzt es. [Siehe Forum](https://forum.iobroker.net/post/326583)

**Comment by Apollon77** [comment]
Ok, options we identified so far:
* js-controller patch to use a different extend method for deep merges that is not checking the constructor
* find a way to patch "javascript" adapter to inject a different extend lib or modify "is.hash" accordingly (and replace extend lib in controller 2.2 later)

Other ideas?

**Comment by Apollon77** [comment]
PS: If it is really VM2 related then the problem should exists since javascript 3.7 according to changelog (or when VM2 was really added and activated for all?)

**Comment by Apollon77** [comment]
ooook guys, we have it :-)

Options to fix for current installations:
* manally update iobroker.objects-redis to 1.2.7 (execute in node_modules/iobroker.js-controller)
OR
* update javascript to GitHub (release hopefully comes soonish)

One of these should be enough.

please check and verify
