### ISSUE TITLE
it is not possible to start new scripts in javascript instance 1 

### ISSUE THREAD

**Issue by CKMartens** [ioBroker/ioBroker.javascript#448]
I upgraded to js-controller 2.1.0. I also have two instances of the java script adapter in version 4.3.3. Instance 0 runs on the master ioB01. Instance 1 on the slave ioB02.

When I create a new script on instance 1, the script does not start. No matter if the script is created with blockly or javascript. It also appears in the log as just under the javascript.0 as stops:
`javascript.0 2019-11-18 07: 15: 19.383 info (1606) Stop script script.js.Heating.tadoBoost`

Even if the script is created in instance 0 - where the script works - and then moved to instance 1, the script then stops working.

Scripts created and launched before the js-controller upgrade in instance 1 are not affected.

**Comment by GermanBluefox** [comment]
Duplicate https://github.com/ioBroker/ioBroker.javascript/issues/449
