### ISSUE TITLE
renameFile implementieren

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.javascript#451]
Ich habe die Bitte dass Ihr renameFile in den Javascript-Adapter implementiert. Apollon meinte der js-controller könnte das der Javascript Adapter aber noch nicht und ich solle ein Issue erstellen was ich hiermit tue.

Danke Steffen

**Comment by truegreyhound** [comment]
siehe auch ioBroker.js2fs-community, Issue #14

**Comment by Apollon77** [comment]
@truegreyhound You mix things here! This issue is to make the "renameFile" methd available for the internal ioBroker file store ... this has nothing to do with JavaScript syncing/mirroring!

**Comment by Apollon77** [comment]
Please try GitHub version
