### ISSUE TITLE
Logfenster rechts neben Scriptfenster statt darunter?

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.javascript#452]
Jemand eine Idee, wie man das Logfenster wieder unter das Script bekommt, wenn es nur noch rechts neben dem Script angezeigt wird?
Manchmal hilft ein Neustart des Javascript Adapters. Manchmal hilft ein Neustart vion ioBroker und machmal hilft gar nichts.
JS 4.1.12

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/69379984-cd388700-0cb1-11ea-8286-1f4fdc63255c.png)

**Comment by JayVee2** [comment]
Wie erreiche ich die Menüleiste mit dem Menüpunkt "Application"?
