### ISSUE TITLE
Warnings Object xxxx does not exist - but there are deleted objects...

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#453]
Hi :-) 
since js-controller 2.1 and javascript 4.3.4  I get this warnings, if the javascript-adapter starts(only at start, then never again):
`
javascript.0 | 2019-11-22 09:24:17.387 | warn | (2244) Object "mihome.0.devices.gateway_4cf8c9121f4" does not exist
-- | -- | -- | --
javascript.0 | 2019-11-22 09:24:17.363 | warn | (2244) Object "javascript.0.Rolladen.Test-Wohn" does not exist
javascript.0 | 2019-11-22 09:24:17.363 | warn | (2244) Object "javascript.0.Rolladen.Test-Schlaf" does not exist
javascript.0 | 2019-11-22 09:24:17.363 | warn | (2244) Object "javascript.0.Rolladen.WohnzimmerEGprozent" does not exist
javascript.0 | 2019-11-22 09:24:17.362 | warn | (2244) Object "javascript.0.Rolladen.BueroEGprozent" does not exist
javascript.0 | 2019-11-22 09:24:17.348 | warn | (2244) Object "javascript.0.system.TVBox-an-aus" does not exist
javascript.0 | 2019-11-22 09:24:17.332 | warn | (2244) Object "sonoff.0.LichtTouch2C1" does not exist
javascript.0 | 2019-11-22 09:24:17.192 | warn | (2244) Object "sonoff.0.EGLichtWohnz" does not exist
javascript.0 | 2019-11-22 09:24:17.139 | warn | (2244) Object "fhem.0.vitoconnect100" does not exist
`
This Objects are very old and there are deleted ...  and my scripts are all green and I checked every point and the objects..

**Comment by Apollon77** [comment]
Problem mainly comes from "expired states do not have a value and thaty why this error is thrown" ... maybe one logging line is enough :-)
