### ISSUE TITLE
Update to 4.3.4 - Adapter wont start anymore - Coffeescript error

### ISSUE THREAD

**Issue by mikepiko** [ioBroker/ioBroker.javascript#454]
Just updated from 4.3.3 to 4.3.4 (nothing else in between)

Adapter keeps staying in red status.

Log throws Errors:
`

host.iobroker | 2019-11-22 12:25:33.143 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2019-11-22 12:25:33.142 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iobroker | 2019-11-22 12:25:33.142 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.iobroker | 2019-11-22 12:25:33.142 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js:7:10)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
host.iobroker | 2019-11-22 12:25:33.141 | error | Caught by controller[0]: Error: Cannot find module 'coffee-script'
host.iobroker | 2019-11-22 12:25:33.140 | error | Caught by controller[0]: ^
host.iobroker | 2019-11-22 12:25:33.140 | error | Caught by controller[0]: throw err;
host.iobroker | 2019-11-22 12:25:33.140 | error | Caught by controller[0]: internal/modules/cjs/loader.js:638

`
Iobroker: 2.1.0
Node.js: v10.16.3
NPM: 6.10.3

Even going back to older Version of javascript won´t start anymore.

Any hints how to solve this ?!

Thanks 

Mike

**Comment by mikepiko** [comment]
Solved by myself by doing a :

`npm install coffee-script`

But have no idea why that was missing and the Adapter was running before.

**Comment by AlCalzone** [comment]
https://github.com/ioBroker/ioBroker.javascript/blob/fe0688ee5db56001215f59c5fc90ac10734da54b/package.json#L33

That must have been a problem during installation of the adapter. `coffee-script` is in the dependencies.
