### ISSUE TITLE
JSHINT: Cannot recdeclare block-scoped variable '...'

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.javascript#455]
Recently the editor produces the warning 
JSHINT: Cannot recdeclare block-scoped variable '...'
for any constant defined.

I reduced the code to just constant defintions. Warnings disappear and show up again after a while.
Any idea?
js-controller 2.1.1
scipt-engine: 4.1.12

**Comment by GermanBluefox** [comment]
Screenshot will help a lot

**Comment by JayVee2** [comment]
I made a couple of reboots today and for any reason the warnings do not show up anymore even code is not changed at all.
