### ISSUE TITLE
Das Bearbeiten mit einem SmartPhone geht nicht

### ISSUE THREAD

**Issue by ymicky** [ioBroker/ioBroker.javascript#458]
Hallo,
habe neuerdings Javaskripte statt blocklys laufen und mir ist aufgefallen, dass es mit dem SmartPhone nicht möglich ist diese zu bearbeiten.
Wenn man auf Skript bearbeiten geht zoomt es viel zu weit rein und ich bekomme keine tastatur wenn ich durchscrolle und auf eine Stelle tippe. Ist sehr schade, da man mit dem Smartphone javascript besser bearbeiten kann als blockly.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.javascript/issues/467
