### ISSUE TITLE
Javascript Editor - keine log("test") Ausgabe

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.javascript#459]
Hilfe!!!!!!
Ich suche heute schon Stunden incl. Image Rücksicherung, weil ich plötzlich
festgestellt habe, dass manche Scripte irgendwie **tot** wirken, ohne eine Fehlermeldung.
z.B. 1-Zeiler: log ("------- Test ------------")  bringt keine Ausgabe im Debug Fenster (unten rechts)
wohl aber im ioBroker Log.
Es fehlt auch der "Mülleimer" zum Löschen des Debug Fensters.
Einige andere Scripts verhalten sich dagegen ganz normal.

Ich bin auch schon zurück auf die JS Version 4.3.1, kein Erfolg.

Hoffentlich kann das einer der Schöpfer des JS Adapter fixen, sonst weiß ich
nicht mehr weiter, wenn man nicht mehr sicher sein kann, dass alle 40 Scripte auch
funktionieren.

Vielen Dank
hs

**Comment by AlCalzone** [comment]
Wenn die logs im iobroker system log erscheinen dann laufen die Skripte auch. Die Anzeige Fehler im admin tab haben erst mal mit der Funktion nichts zu tun

**Comment by Hans-Zwiesel** [comment]
Ist aber in jedem Fall beunruhigend, wenn die Meldungen im Editor plötzlich nicht mehr da sind.
Außerdem braucht man die ja auch zum debuggen.
