### ISSUE TITLE
Sendto and Pushover not work

### ISSUE THREAD

**Issue by JB1985** [ioBroker/ioBroker.javascript#463]
Javascript Version: 4.3.4
pushover:1.1.1

I cant add (in blockly) a Sendto with Pushover. See screenshot:

![image](https://user-images.githubusercontent.com/9932751/70695040-25671580-1cc1-11ea-8908-3baf02e11804.png)

The Menu to add a Sendto with Pushover is not working well. Please fix this bug.

**Comment by GermanBluefox** [comment]
It must be the error message in browser console. Can you provide it?

**Comment by JB1985** [comment]
I close this request as it is fixed. I don't know which update fixed it but the problem no longer exists.
