### ISSUE TITLE
TypeScript, log('Test', 'debug') kein Output mehr, javascript 4.3.4

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#464]
Es hat sich leider noch etwas geändert. Ich habe diverse Ausgaben in meinen Skripten wie
(loglevel == 'debug') log('Test', 'debug')
Unabhängig davon, ob der Loglevel des Scriptadapters auf 'info' oder 'warn' stand, sind die Skriptausgaben geschrieben worden. Steht jetzt der Loglevel auf 'info' erfolgt nur eine Ausgabe für Severity == ''|'info'|'error'|'warn'", 'debug' und 'silly' werden unterdrückt.
Wenn ich meine Skripte debugge, möchte ich nicht auch noch die ganzen Ausgaben des Adapters im Log haben. Bitte das "alte" Verhalten wieder herstellen!

**Comment by kago76** [comment]
Ich habe das gleiche Problem. 
Das ist aber unabhängig von TypeScript. Es tritt auch in Javascript auf. Issue #459
Duplicate of #459

**Comment by truegreyhound** [comment]
js-controller: 2.2.7
javascript 4.3.4
Admin: 3.7.7

Habe inzwischen den neuen Button "Debug-Optionen" im Admin auf dem Script-Tab (ganz rechts) gefunden. Leider funktioniert das nicht so wie erwartet. Wo gibt es eine aktuelle Bechreibung dazu?

**Comment by truegreyhound** [comment]
okay, habe das Problem vor dem Bildschirm gefunden. Hatte meinen log-Wrapper falsch umgebaut und übersehen, dass console.log richtig als 'info' loggen muss und 'debug' nur ein Bestandteil der Nachricht ist.
