### ISSUE TITLE
Problem with selector

### ISSUE THREAD

**Issue by vvfrwl** [ioBroker/ioBroker.javascript#466]
A Selector with ENUM for 0_userdata.0 is working with errors.
Problem exists for 0_userdata.0 only.
For example:
`on({id: 'telegram.0.communicate.request', change: "any"}, function (obj) {
$('state(rooms=mbrwc)').each(function (id, i) {
    log(id,'warn');
    });
});`

Result Log (* We got objects from the room "chwc" too: 4 and 5 lines):

1. 12/28/2019, 11:39:26 PM.140	[info ]: javascript.0 (32608) Start javascript script.js.Developing.Test3
2. 12/28/2019, 11:39:26 PM.143	[info ]: javascript.0 (32608) script.js.Developing.Test3: subscribe: {"pattern":{"id":"telegram.0.communicate.request","change":"any","q":0},"name":"script.js.Developing.Test3"}
3. 12/28/2019, 11:39:26 PM.144	[info ]: javascript.0 (32608) script.js.Developing.Test3: registered 1 subscription and 0 schedules
4. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: 0_userdata.0.CHWC_Fan_Auto_enable
5. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: 0_userdata.0.CHWC_Fan_enable
6. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_Auto_enable
7. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_enable
8. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: megadd.0.p18_MBRWC_FH
9. 12/28/2019, 11:39:32 PM.995	[warn ]: javascript.0 (32608) script.js.Developing.Test3: megadd.0.p22_MBRWC_Fan
10. 12/28/2019, 11:39:32 PM.996	[warn ]: javascript.0 (32608) script.js.Developing.Test3: megadd.0.p7_MBRWC_FHTemp1
11. 12/28/2019, 11:39:32 PM.996	[warn ]: javascript.0 (32608) script.js.Developing.Test3: megadd.0.p8_MBRWC_FHTemp2
12. 12/28/2019, 11:39:32 PM.996	[warn ]: javascript.0 (32608) script.js.Developing.Test3: mihome.0.devices.sensor_ht_158d0001f4fdbc.humidity
13. 12/28/2019, 11:39:32 PM.996	[warn ]: javascript.0 (32608) script.js.Developing.Test3: mihome.0.devices.sensor_ht_158d0001f4fdbc.temperature

My ENUMs\Objects:
![userdata 0](https://user-images.githubusercontent.com/59322588/71550711-4167f800-29df-11ea-8cba-34e4876109d7.jpg)
![Enums](https://user-images.githubusercontent.com/59322588/71550712-4167f800-29df-11ea-8dfb-529ed2069ebb.jpg)
|Hardwaresystem:| Khadas VIM3 Pro|
|Arbeitsspeicher:| 4GB |
|Festplattenart:| 32Gb eMMC |
|Betriebssystem:| Armbian|
|Node-Version:| 10.17.0 |
|Nodejs-Version:| 10.17.0 |
|NPM-Version:| 6.13.4 |
|Installationsart:| Skript|
|Image genutzt:| No |
|Ort&#x2F;Name der Imagedatei:| Link |
|Script Engine version:| 4.3.4 |
|Admin version:| v3.6.12 |
|js-controller:| 2.1.1 |

**Comment by Apollon77** [comment]
And when you restart JavaScript? Do it happens too?

**Comment by vvfrwl** [comment]
I have restarted JavaScript adapter from admin web console several times: not helped.
I have deleted and created new ENUMs (with the same names): not helped.
I have created a new script for other instance JavaScript: not helped.
* I have not restarted the server.

I have restarted the Java Script adapters from CLI today.
Result logs for the same script (It looks like ok with room "mbrwc"):

1. 12/29/2019, 9:46:31 AM.686	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_Auto_enable
2. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_enable
3. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p18_MBRWC_FH
4. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p22_MBRWC_Fan
5. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p7_MBRWC_FHTemp1
6. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p8_MBRWC_FHTemp2
7. 12/29/2019, 9:46:31 AM.687	[warn ]: javascript.0 (2035) script.js.Developing.Test3: mihome.0.devices.sensor_ht_158d0001f4fdbc.humidity
8. 12/29/2019, 9:46:31 AM.688	[warn ]: javascript.0 (2035) script.js.Developing.Test3: mihome.0.devices.sensor_ht_158d0001f4fdbc.temperature
9. 

...But I have changed the room in the script and checked again.
`on({id: 'telegram.0.communicate.request', change: "any"}, function (obj) {
$('state(rooms=chwc)').each(function (id, i) {
    
    log(id,'warn');
    });
});`
Log(we have extra room "mbrwc" again: 8,9 lines ):

1. 12/29/2019, 9:47:23 AM.316	[info ]: javascript.1 (2059) Stop script script.js.Developing.Test3
2. 12/29/2019, 9:47:23 AM.320	[info ]: javascript.0 (2035) Stop script script.js.Developing.Test3
3. 12/29/2019, 9:47:23 AM.345	[info ]: javascript.0 (2035) Start javascript script.js.Developing.Test3
4. 12/29/2019, 9:47:23 AM.394	[info ]: javascript.0 (2035) script.js.Developing.Test3: subscribe: {"pattern":{"id":"telegram.0.communicate.request","change":"any","q":0},"name":"script.js.Developing.Test3"}
5. 12/29/2019, 9:47:23 AM.396	[info ]: javascript.0 (2035) script.js.Developing.Test3: registered 1 subscription and 0 schedules
6. 12/29/2019, 9:47:30 AM.676	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.CHWC_Fan_Auto_enable
7. 12/29/2019, 9:47:30 AM.678	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.CHWC_Fan_enable
8. 12/29/2019, 9:47:30 AM.679	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_Auto_enable
9. 12/29/2019, 9:47:30 AM.681	[warn ]: javascript.0 (2035) script.js.Developing.Test3: 0_userdata.0.MBRWC_Fan_enable
10. 12/29/2019, 9:47:30 AM.682	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p10_CHWC_FHTemp1
11. 12/29/2019, 9:47:30 AM.683	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p17_CHWC_FH
12. 12/29/2019, 9:47:30 AM.684	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p21_CHWC_Fan
13. 12/29/2019, 9:47:30 AM.686	[warn ]: javascript.0 (2035) script.js.Developing.Test3: megadd.0.p9_CHWC_FHTemp2

**Comment by vvfrwl** [comment]
And one more strange situation for this case.
I have 2 Java Script instances.
Configuration while testing:
javascript.0 - 1 script only
javascript.1 - all scripts paused.

If I restart both JS instances at once I get different result from Selector.
Selector: $('state(rooms=living_room)(functions=light)').each(function (id, i)
I get a list of objects from sonoff.0 with an empty room and functions fields too .

If I restart one javascript.0 (it has the script) only I have the result without objects with an empty room, functions fields.

**Comment by xCruziX** [comment]
Gibt es hier schon Neuigkeiten?
Würde auch gerne in userdata suchen können, gerade wenn man jetzt nicht mehr javascript.x verwendet.

**Comment by GermanBluefox** [comment]
Nein
