### ISSUE TITLE
Version 4.3.4: "Cannot find module 'request'"

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.javascript#471]
Hi,

The script and the `require('request')` work fine ([link to script](https://github.com/Mic-M/iobroker.control-ms-windows/blob/master/control-ms-windows.js)). However, the editor does not recognize 'request'. See screenshot:
![us](https://user-images.githubusercontent.com/39859059/71920633-7c102400-3187-11ea-9222-6cd71115a6a5.png)

 - js-controller version: 2.2.7
 - JavaScript adapter version: 4.3.4

Thanks

**Comment by AlCalzone** [comment]
The variable request is preloaded and thus does not need to be required. Just delete the line.
