### ISSUE TITLE
Comparing Times

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.javascript#472]
Comparing identical times results in `false` ?

![image](https://user-images.githubusercontent.com/29343914/72015508-2c525b00-3262-11ea-87ad-f98196fa5558.png)

**Comment by AlCalzone** [comment]
First line: the times are not identical but a couple of microseconds different, since two different dates are created shortly after another

Second line: those are strings, not date/time values

**Comment by EvilEls** [comment]
First line: 
I'm not comparing timestamps in milliseconds. It compares `SS:mm` which are identical
![image](https://user-images.githubusercontent.com/29343914/72018566-3b3c0c00-3268-11ea-85f8-f66b9080bcdf.png)

Second line:
The time compare accepts `string`
![image](https://user-images.githubusercontent.com/29343914/72018656-6292d900-3268-11ea-8dc7-9c55ddae49fa.png)

Also failing:
![image](https://user-images.githubusercontent.com/29343914/72018900-dcc35d80-3268-11ea-96ba-a1efbd0e3248.png)

**Comment by AlCalzone** [comment]
Wir können auch deutsch reden. Zeig mir mal den JavaScript-Code, der für das Blockly generiert wird.
