### ISSUE TITLE
setObject() function: callback not working as intended.

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.javascript#474]
Hi,
This issue is about the [setObject() function](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#setobject): `setObject(id, obj, callback);`

Per the documentation, we would expect that a certain function, which is provided to the callback parameter of "setObject()", is executed AFTER completion of setObject(). However, it seems that this is not working.
Please see ioBroker Forum Thread [[Vorlage] Skript: Erstellen von User-Datenpunkten](https://forum.iobroker.net/topic/26839/vorlage-skript-erstellen-von-user-datenpunkten/).

[This forum post](https://forum.iobroker.net/post/334331)  initially mentions an issue with setObject. If you scroll further down, you'll see more info on it.

**Per my tests I have made, I can confirm that the callback is being executed like immediately, and not after setObject() function completion.**
My environment: JavaScript adapter version: 4.3.4 // js-controller 2.2.7

Thanks guys! Let me know if you need any further info or tests.

**Comment by Apollon77** [comment]
> Per my tests I have made, I can confirm that the callback is being executed like immediately, and not after setObject() function completion.

This is not completely correct ... The topic is that new Objects/States are registered by JavaScript Adapter  when they are published in the system. This happens asynchronously after the setObject.

I think it is no problem  to already store the object data when the callitself was successull...

**Comment by AlCalzone** [comment]
I'm confused... What is correct now?

**Comment by Mic-M** [comment]
Hi @Apollon77,
I don't understand either. [Per node.js](https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/): 
> Node.js, being an asynchronous platform, doesn't wait around for things like file I/O to finish - Node.js uses callbacks. **A callback is a function called at the completion of a given task**

The given task is to set an object through (setObject()), and at the completion, the callback() should apply. I may be wrong with my understanding, and look forward to further explanation. Thanks.

**Comment by Apollon77** [comment]
You are all right and I wanted to do exactly the same ... I just described the reason for it and provided a potential solution. So, yes it is a bug :-)

**Comment by Mic-M** [comment]
Many thanks @Apollon77.  Now I do fully understand your previous response :-)

**Comment by GermanBluefox** [comment]
I still do not understand, what is wrong

**Comment by Apollon77** [comment]
@GermanBluefox setObject is only calling setForeignObject but is not registering the obejct in the internal "objects cache from javascript adapter". This "registration only happens once the objectChange event is coming in. Because of the async nature this will normally happen AFTER the callback of the setObject is called ... so when you want to access the object directly in the callback you might get an error because it is missing in the internal object cache
