### ISSUE TITLE
Einige Datenpunkte kann ich nicht speichern

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.javascript#475]
Blockly weigert sich den folgenden Datenpunkt weiter zu verarbeiten:
{ "type": "state", "common": { "name": 1, "desc": "aussentemperatur", "unit": "°C", "role": "value", "id": "w_temperatur", "type": "number", "read": true, "write": false, "custom": { "influxdb.0": { "enabled": true, "changesOnly": true, "debounce": "", "retention": "31536000", "changesRelogInterval": "1800", "changesMinDelta": 0, "storageType": "Number", "aliasId": "Aussentemperatur" } } }, "native": {}, "from": "system.adapter.wiffi-wz.0", "user": "system.user.admin", "ts": 1566662224431, "_id": "wiffi-wz.0.root.192_168_1_142.w_temperatur", "acl": { "object": 1636, "owner": "system.user.admin", "ownerGroup": "system.group.administrator", "state": 1636 } }

Bei diesem Wert geht es:
{ "type": "state", "common": { "read": true, "write": false, "desc": "regen_mm_gestern", "unit": "mm", "role": "value", "id": "w_regen_mm_gestern", "name": "27", "type": "number" }, "native": {}, "from": "system.adapter.wiffi-wz.0", "user": "system.user.admin", "ts": 1566662224436, "_id": "wiffi-wz.0.root.192_168_1_142.w_regen_mm_gestern", "acl": { "object": 1636, "state": 1636, "owner": "system.user.admin", "ownerGroup": "system.group.administrator" } }

Warum ist das so?
Wenn ich den ersten Wert per js-in einen eigenen DP "umsetze", kann ich ihn verarbeiten!

**Comment by Apollon77** [comment]
Was genau bedeutet „blockly weigert sich zu verarbeiten“?

**Comment by Apollon77** [comment]
Common.name ist oben eine Zahl. Name muss ein String sein

**Comment by AlCalzone** [comment]
@Apollon77 `"name": "27"` sieht für mich nach dem String `"27"` aus ;)

**Comment by guergen1** [comment]
Sobald ich den oberen DP in Blockly eintrage kann ich ihn nicht speichern, beim unteren geht es.

**Comment by guergen1** [comment]
> Common.name ist oben eine Zahl. Name muss ein String sein

Ok, dann sag ich dem Entsprechenden Menschen Bescheid

**Comment by Apollon77** [comment]
"common": { "name": 1, ...

**Comment by Apollon77** [comment]
Das "27" ist in dem unteren wo es ja auch tut :-) Aber oben ist es eine Zahl.

Also hier ggf Issue beim wiffi adapter anlegen das "common.name" bitte immer als String gesetzt wird

**Comment by guergen1** [comment]
Ok, wird im wiffi Adapter geregelt!
