### ISSUE TITLE
TypeError: getState(...).val.trim is not a function

### ISSUE THREAD

**Issue by slimline33** [ioBroker/ioBroker.javascript#479]
With a simple timer which I want to create via cron with the following blockly I get YXXXXXXX as error message. 

After some research I found out that this worked with an earlier Javascript instance.
Error in log:

`

javascript.0 | 2020-01-17 21:46:51.966 | error | (11143) at processImmediate (timers.js:658:5)
-- | -- | -- | --
javascript.0 | 2020-01-17 21:46:51.966 | error | (11143) at tryOnImmediate (timers.js:676:5)
javascript.0 | 2020-01-17 21:46:51.966 | error | (11143) at runCallback (timers.js:705:18)
javascript.0 | 2020-01-17 21:46:51.966 | error | (11143) at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:224:41)
javascript.0 | 2020-01-17 21:46:51.965 | error | (11143) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4745:37)
javascript.0 | 2020-01-17 21:46:51.962 | error | (11143) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:429:25)
javascript.0 | 2020-01-17 21:46:51.962 | error | (11143) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1061:38)
javascript.0 | 2020-01-17 21:46:51.961 | error | (11143) at Object.<anonymous> (script.js.Sonstiges.ical_Trigger.Kaffemaschine-Timer-Variabel:8:114)
javascript.0 | 2020-01-17 21:46:51.960 | error | (11143) Error in callback: TypeError: getState(...).val.trim is not a function

`

Javascript version: 4.3.2

**Comment by slimline33** [comment]
following export from blockly:

`<block xmlns="http://www.w3.org/1999/xhtml" type="schedule_create" id="EQ,qo=]`anY~EMm63.QB" x="-450.9865608215332" y="-99">
  <field name="NAME">einschalten</field>
  <value name="SCHEDULE">
    <shadow type="field_cron" id="p`;Fto%v*:kPJ=1J-J*|">
      <field name="CRON">* * * * *</field>
    </shadow>
    <block type="cron_builder" id="Jl`MNY%fG1tpF*neqa|~">
      <mutation seconds="false" as_line="false"></mutation>
      <field name="LINE">FALSE</field>
      <field name="WITH_SECONDS">FALSE</field>
      <value name="DOW">
        <shadow type="text" id="9#lW|oI-1O`~:mWvG,Z#">
          <field name="TEXT">*</field>
        </shadow>
      </value>
      <value name="MONTHS">
        <shadow type="text" id="!VVpQT$7lP+a~ar(Hti/">
          <field name="TEXT">*</field>
        </shadow>
      </value>
      <value name="DAYS">
        <shadow type="text" id="OG6lD7,LE*TMO#8b-~XS">
          <field name="TEXT">*</field>
        </shadow>
      </value>
      <value name="HOURS">
        <shadow type="text" id="%rs[Uge-SXRK?6puVla@">
          <field name="TEXT">*</field>
        </shadow>
        <block type="get_value" id="G/XD-x}(bG?|;0LGwC,O">
          <field name="ATTR">val</field>
          <field name="OID">00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Stunde</field>
        </block>
      </value>
      <value name="MINUTES">
        <shadow type="text" id="w-)i$y:y`Yr)u(:P$**e">
          <field name="TEXT">*</field>
        </shadow>
        <block type="get_value" id="$5kQ5$hfvdAm%XrFfM#V">
          <field name="ATTR">val</field>
          <field name="OID">00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Minute</field>
        </block>
      </value>
    </block>
  </value>
  <statement name="STATEMENT">
    <block type="telegram" id="q[@qU?*e~%ky]/TcR^p!">
      <field name="INSTANCE"></field>
      <field name="LOG"></field>
      <field name="SILENT">FALSE</field>
      <field name="PARSEMODE">default</field>
      <value name="MESSAGE">
        <shadow type="text" id=";fNEmsl*A#1u!NSw|acA">
          <field name="TEXT">Kaffemaschine Test</field>
        </shadow>
      </value>
      <next>
        <block type="control" id="?xG-_FhzlDe-UzFK/$/," disabled="true">
          <mutation delay_input="false"></mutation>
          <field name="OID">sonoff.0.GOS-SOF-Kaffee.POWER</field>
          <field name="WITH_DELAY">FALSE</field>
          <value name="VALUE">
            <block type="logic_boolean" id="8+:)eon2,(#am_1Rs9s.">
              <field name="BOOL">TRUE</field>
            </block>
          </value>
          <next>
            <block type="control" id="oo_Z;|eOFDU}eRtv=~c}">
              <mutation delay_input="true"></mutation>
              <field name="OID">00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Aktiv</field>
              <field name="WITH_DELAY">TRUE</field>
              <field name="DELAY_MS">1000</field>
              <field name="UNIT">ms</field>
              <field name="CLEAR_RUNNING">FALSE</field>
              <value name="VALUE">
                <block type="logic_boolean" id="Dr2%dm?ad.]^*h`v{U^x">
                  <field name="BOOL">FALSE</field>
                </block>
              </value>
              <next>
                <block type="control" id="b6HiIheQU!`[.*{jL^rW">
                  <mutation delay_input="true"></mutation>
                  <field name="OID">00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Minute</field>
                  <field name="WITH_DELAY">TRUE</field>
                  <field name="DELAY_MS">1000</field>
                  <field name="UNIT">ms</field>
                  <field name="CLEAR_RUNNING">FALSE</field>
                  <value name="VALUE">
                    <block type="text" id="q0*C]:K6R;}#X3N/YBd8">
                      <field name="TEXT"></field>
                    </block>
                  </value>
                  <next>
                    <block type="control" id="Hz@FQw_@$e2m^xHd3K7~">
                      <mutation delay_input="true"></mutation>
                      <field name="OID">00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Stunde</field>
                      <field name="WITH_DELAY">TRUE</field>
                      <field name="DELAY_MS">1000</field>
                      <field name="UNIT">ms</field>
                      <field name="CLEAR_RUNNING">FALSE</field>
                      <value name="VALUE">
                        <block type="text" id="n`^0s~]CN8~.D}j{_M2J">
                          <field name="TEXT"></field>
                        </block>
                      </value>
                    </block>
                  </next>
                </block>
              </next>
            </block>
          </next>
        </block>
      </next>
    </block>
  </statement>
</block>`

<blockquote class="imgur-embed-pub" lang="en" data-id="a/IYFj4jR"  ><a href="//imgur.com/a/IYFj4jR">blockly timer cron</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Apollon77** [comment]
This is acoding error. You assume that getState().val is ALWAYS a string ... is this really the case?

Please show the generated Javascript by this blockly

**Comment by slimline33** [comment]
I don't know. I'm just use minutes and hours inside the "Kaffeemaschine-Timer-Stunde" and "Kaffeemaschine-Timer-Minute"

`
var einschalten;


on({id: '00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Aktiv', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Aktiv").val == true) {
    einschalten = schedule(getState("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Minute").val.trim() + ' ' + getState("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Stunde").val.trim() + ' ' + '*'.trim() + ' ' + '*'.trim() + ' ' + '*'.trim(), function () {
      sendTo("telegram", "send", {
          text: 'Kaffemaschine Test'
      });
      setStateDelayed("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Aktiv"/*Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Aktiv*/, false, 1000, false);
      setStateDelayed("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Minute"/*Kaffeemaschine-Timer-Minute*/, '', 1000, false);
      setStateDelayed("00-ZUHAUSE.0.Zeitsteuerung.Kaffeemaschine.Kaffeemaschine-Timer-Stunde"/*Kaffeemaschine-Timer-Stunde*/, '', 1000, false);
    });
    (function () {if (einschalten) {clearSchedule(einschalten); einschalten = null;}})();
  }
});

`

**Comment by slimline33** [comment]
Okey. No more error...

The object ID have to be formatted as string 💯  thanks.
