### ISSUE TITLE
ReferenceError: <name> is not defined

### ISSUE THREAD

**Issue by Nedogin** [ioBroker/ioBroker.javascript#480]
Hallo,

ich bin zurzeit dabei  meinen Code ein wenig intelligenter zu gestalten. Ich schreibe hierfür globale Klassen und instantiiere diese dann auch global, um in den Skripten die z. B. im Ordner "common" liegen auf die Objekte zuzugreifen. Dies scheitert aber daran, dass der Fehler "ReferenceError: <NameDerKlasse> is not defined" geworfen wird.

Ich habe mit der Klasse Lampe angefangen. Bei der geht alles und ich kann das Objekt problemlos nutzen. (Obwohl der Klassenname rot markiert wird)
![image](https://user-images.githubusercontent.com/46285622/73122350-117f2680-3f84-11ea-8cb2-790fbe541dd1.png)

hier das globale Objekt:
![image](https://user-images.githubusercontent.com/46285622/73122358-35426c80-3f84-11ea-9901-a1b1e0ed759b.png)

geht problemlos....

Allerdings nicht mehr bei folgender Klasse: (ich packe hier mal das Klassen Skript und das Objekt Skript nebeneinander... der generelle auf bau ist ja klar)
![image](https://user-images.githubusercontent.com/46285622/73122504-15ac4380-3f86-11ea-9050-d233e3e232b3.png)

hier bekomme ich folgenden Fehler "ReferenceError: Steckdose is not defined"

.... während ich das hier geschrieben habe, habe ich noch ein wenig getestet. Durch mehr maliges ein uns auskommentieren und speichern kommt der Fehler jetzt nicht mehr. Ich kann das Objekt aber immer noch nicht ansprechen.
![image](https://user-images.githubusercontent.com/46285622/73122666-afc0bb80-3f87-11ea-8f33-fc13c24cea3a.png)

füge ich händisch ".getState()" hinzu, funktioniert es. (Telegram gibt mir "true" zurück)

Gibt es eine Möglichkeit das zu fixen? Komme so nicht weiter )-: Mein beschriebener "workaround" von oben ist nicht reproduzierbar und war Zufall. Ich möchte noch einige weiter Klassen dieser Art anlegen und möchte nur ungerne stundenlang "try and error" betreiben. 

Danke im Voraus.
Lukas

**Comment by Nedogin** [comment]
ps: ich nutze die aktuelle Adapterversion
![image](https://user-images.githubusercontent.com/46285622/73122903-442c1d80-3f8a-11ea-99d3-6d4a4a2bcd07.png)

**Comment by Apollon77** [comment]
Ich bin mir nicht sicher das du das wirklich so willst. Globale Skripte werden quasi textural aneinandergehangen (wobei es keine Garantie einer Reihenfolge gibt!!) und vor jedes „nicht global“ Skript gegangen. 

Damit wird dieser ganze Code und klasseninitialisierung bei jedem Skript gemacht und deine Skripte werden alle riesig. Von RAM und Performance mal nicht angefangen.

Zu deinem Problem: kann es sein das einfach die Skripte in der falschen Reihenfolge zusammengehangen werden und du deswegen Fehler hast?

**Comment by Nedogin** [comment]
Vielen dank für die Antwort. Da habe ich wohl das System hinter dem global Ordner nicht ganz richtig erfasst. Ist also mein Denkfehler und kein issue.
