### ISSUE TITLE
[solved] if option “Do not subscribe all states on start” enabled, getState cannot find a data point

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#483]

**Comment by Apollon77** [comment]
Please show the code. When this option is set to "No" you need to use getState with the callback to get the data!

**Comment by truegreyhound** [comment]
was a misunderstanding, wanted to get the value from the callback in its own wrapper function getStateX, which of course (so easy) is not possible. Should prevent me from major code changes

`    gLoglevel = getState(idInfoLoglevel).val,`
`    mnWaittime = toInt(getState(idPresenceDetection_Waittime).val);`
`    mbDeviceStateChangeAccept = parseBool(getState(idDeviceStateChangeAccept).val);`
`    . . .'

is the only way to cascade the individual gets here?

`    getState(idInfoLoglevel, function (error, state) {`
`       gLoglevel = state.val;`
`    `
`       getState(idPresenceDetection_Waittime, function (error, state) {`
`          mnWaittime = toInt(state.val);`
`    `
`          getState(idDeviceStateChangeAccept, function (error, state) {`
`             mbDeviceStateChangeAccept = parseBool(state.val);`
`    `
`              . . .'
`          });`
`       });`
`    });`

**Comment by Apollon77** [comment]
ok, then I close here :-)
