### ISSUE TITLE
deleteObject is missing

### ISSUE THREAD

**Issue by Coalado** [ioBroker/ioBroker.javascript#484]
There is setObject and extendObject, but no deleteObject.

There is deleteState, which only deletes states created by createState on the javascript adapter, but as far as I can see, there is no deleteObject, that can actually delete Objects in any Namespace created by setObject

**Comment by GermanBluefox** [comment]
Done in 4.3.6 https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#deleteobject
