### ISSUE TITLE
Logo dreht sich im Kreis

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.javascript#490]
Nach Update auf:
Web 3.0.0
Socketio 3.0.0
Admin 4.0.0

hängt Skripte, das Logo dreht ewig.

![Screenshot (1588)](https://user-images.githubusercontent.com/41079106/73998845-2041e200-4963-11ea-84dd-aadbac19f841.png)

https://forum.iobroker.net/topic/29855/wichtig-updates-von-socketio-web-admin-latest-vorerst/24

Platform: Windows
Node.js: v10.16.3
js-controller : 2.2.8
Javascript Script Engine: 4.3.4
NPM: 6.9.0
Admin: 4.0.0

Edit:
Mal geht es mal wieder nicht. Auf jeden Fall langsamer als vorher.

Edit 2 :
Geht auch mit FF nicht

![Screenshot (1591)](https://user-images.githubusercontent.com/41079106/74043308-6c277200-49c9-11ea-8e5e-501268788c86.png)

Edit 3:

Javascript Script Engine: 4.3.8
Keine Besserung

**Comment by sky-it** [comment]
Schließe mich hier mit an.
Android 9 auf Smartphone (Stock) und Tablet (lineageos). Browser Firefox und Chrome.
Mal zeigt er was an (dauert länger), überwiegend dreht sich jedoch das Logo.

**Comment by MK-66** [comment]
Auch ich schließe mich hier an, speziell bei Chrome tritt das Problem bei mir auf, meistens geht es nicht. Unter F12 wird bei Chrome angezeigt: DevTools failed to parse SourceMap: http://192.168.xxx.xx:8081/adapter/min-maps/vs/loader.js.map

Platform: Raspi Pi4
Nodejs: 10.19.0
js-controller : 2.2.8
Javascript Script Engine: 4.3.4
NPM: 6.13.4
Admin: 4.0.0
socket.io: 3.0.0
web: 3.0.0

**Comment by mameier1234** [comment]
Admin 4.0.1 hat bei mir gerade das Problem behoben...

**Comment by Apollon77** [comment]
Bitte Admin 4.0.1 mit Javascript 4.4.0 vom GitHub testen!

**Comment by BlueBook4** [comment]
Sorry, für die Anfängerfrage - bin nicht so der Unix-Crack.
Hab hier das gleiche Problem.
Mit welchem Befehl bekomm ich nun die GutHub-Version über die Console installiert?

**Comment by Apollon77** [comment]
@BlueBook4 Hm ... Also als blutiger ANfänger solltest du eher die Finger von Github versionen und so lassen. Admin sollte ausreichen. De weiteren s´bestand das Thema VOR EINEM JAHR - DU hast dich hier an ein seit einem Jahr gefixtes issue gehngt - daher ist der Grund bei dir vermutlich was ganz anderes gewesen ...

**Comment by BlueBook4** [comment]
@Apollon77 Sorry, bin noch nicht ganz in 2021 angekommen - hab ich das Gefühl.
Die Fehlerbeschreibung passte zu gut ;)
Dann war es wohl wirklich was anderes...
Nun gut, läuft wieder, sorry für die Störung :>
