### ISSUE TITLE
Missing longtitude latitude after start of Adapter

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#492]
Since Update 4.3.6 and Higher the Error :
`
javascript.0 | 2020-02-09 09:52:51.566 | error | (5521) Longitude or latitude does not set. Cannot use astro
`

Astro Setup was okay, the Checkmark "use Admin" was set., The map Show the correct address.

**Comment by Diginix** [comment]
+1
javascript 4.4.0
But I had this error first time after update to socketio 3.0.0 and admin 4.0.1 on 7 Feb.
With javascript 4.3.8 and older socketit+admin all was ok. Maybe it's caused by the admin adapter?

js-controller 2.2.8

**Comment by realwax** [comment]
+1 Longitude or latitude does not set. Cannot use astro - same here.

Dadurch wird astro nicht verfügbar und somit klappen alle astrotimes in scripten nicht.

**Comment by Apollon77** [comment]
Wie ist denn die EInstellung im Adapter bei Euch gesetzt bezüglich "Systemkoordinaten nutzen" ?

**Comment by Diginix** [comment]
Diese Einstellung ist beim Javascript Adapter aktiviert. Und in den Admin Einstellungen sind die korrekten Koordinaten hinterlegt.

**Comment by Apollon77** [comment]
Ich habs. Bitte Javascript 4.4.1 vpm GitHub versuchen und rückmeldung geben

**Comment by Diginix** [comment]
Bekomme kein Fehler mehr mit 4.4.1 und Nutzung der System-Geo-Koordinaten.

**Comment by Apollon77** [comment]
Frage ist ja auch ob die astro Funktionen noch tun

**Comment by Diginix** [comment]
Das hat in meinem Testskript eben leider nicht funktioniert. 
Interessanterweise hat es aber heute 17:30 Uhr sogar mit dem Fehler mit Version 4.4.0 bei mir funktioniert. Denn da wurde ein Datenpunkt abhängig von Sonnenuntergang aktualisiert und auch die Alexa Ausgabe dass die Rollläden geschlossen werden kam nachweislich. Also mit "fehlenden" Koordinaten ging es und jetzt ohne Logfehler im Test nicht. 
Hab bestimmt 10 mal ein Astrotrigger mit Sonnenuntergang und 3xx Minuten Offset der 22:xx Uhr hätte eine Debugausgabe bringen sollen getestet. Sollte aber mal noch jemand gegentesten.

**Comment by Apollon77** [comment]
Ich bin nicht sicher ob ein "forward offset" so tut wenn der zeitpunkt schon abgelaufen ist

**Comment by Diginix** [comment]
Deswegen bin ich mir auch nicht sicher mit dem Test. Du meinst er muss zum Zeitpunkt des Eintretens (Sonnenuntergang) anspringen und dann wartet er den Offset bis zu Ausführung?
Ich meine aber dass es früher als ich Astrotrigger getestet habe so ging. Aber ich werde es morgen genau wissen.

**Comment by Apollon77** [comment]
alles klar danke!
