### ISSUE TITLE
Javascript adapter does not start on mutlihost after update

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.javascript#494]
2020-02-09 19:06:30.209  - error: host.ioBrokerPIB3 startInstance system.adapter.javascript.1: required adapter "admin" not found!

**Comment by realwax** [comment]
Erst nach installation eines admin adapters am multihost slave lässt er sich starten.

**Comment by Apollon77** [comment]
Ja Mist ... es gibt leider gerade keinen anderen Weg sicherzustellen das nur User mit Admin 4.0.1+ die neue JavaScript Version installieren dürfen. :-( das hat leider diesen Nebeneffekt

**Comment by realwax** [comment]
Danke @Apollon77 ! Ich habe sie installiert, aber sie müssen auch laufen, sonst klappts nicht. Zumindest bei mir. Nimms vielleicht in die Github doc... unter den rlsnts. Danke!

**Comment by Apollon77** [comment]
An sich sollte ne Instanz auf dem Host reichen auch wenn nicht aktiv.

**Comment by realwax** [comment]
danke ich versuche es...
