### ISSUE TITLE
Continues restart loops

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.javascript#495]
javascript.0 | 2020-02-09 19:32:14.184 | info | (17785) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
javascript.0 | 2020-02-09 19:32:14.183 | info | (17785) terminating
javascript.0 | 2020-02-09 19:32:14.182 | warn | (17785) Got terminate signal. Checking desired PID: 18007 vs own PID 17785

(17546) Got terminate signal. Checking desired PID: 17785 vs own PID 17546
--

Adapter auf debug zeigt leider nicht mehr her...

**Comment by Apollon77** [comment]
Which js-Controller? Please stop instance. Wait 10s and start again.

**Comment by realwax** [comment]
2.2.8 
Now it seems stable. After the update it did mess around. Restarted iobroker itself. Behaviour did not disappear but after the second restart. Multihost redis/redis..
