### ISSUE TITLE
SetState gelingt nicht immer (geht als Update durch Kombination mit deconz) 

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.javascript#496]
Seit 4.4.0 habe ich den Effekt, dass setState aus blockly heraus also der Steuere Block manchmal wie ein Update/aktualisieren aber ohne steuern funktioniert. Dabei ist der Wert im iobroker geschrieben, aber am Gerät nicht gesetzt / geschaltet.  Erst ein mehrfaches schalten oder die selbe Steueranweisung 2 mal hintereinander führt zum Erfolg. So habe ich ein paar scripte mit einem hotfix versehen. wenn man die Zeitsteuerung/delay nutzt hat es den selben Effekt. 

Ein manuelles schalten im Objektkatalog über den iobroker admin klappt reibungslos. Der Effekt viele lichter bleiben an, obwohl ausgeschaltet....
Danke für fix/Hilfe. Kann gerne morgen weiter debugen.

**Comment by Apollon77** [comment]
Gibts da logs! Vllt mal einen solchen state subscriben und loggen inkl ack flag. Bzw im entsprechenden script debug einschalten. Oder hat deconz ein log der die state changes zeigt?

**Comment by realwax** [comment]
Könnte es sein, dass es mit der socket.io zu tun hat? Dies betrifft ja auch den deconz adapter, wenn ich richtig verstehe. Ich habe nun intensiv gelogt und getestet. Es geschieht nicht jedesmal. Hin und wieder, wenn eine Gruppe ausgeschalten wird, nachdem der Bewegungsmelder (presence) auf false geht, wird ausgeschalten. Von 5 mal, klappt es einmal nicht. 


Das script dreht das licht mit einem "recall" button in deconz auf und ruft zugleich die Szene auf. Mit der "on" Variable wird ausgeschalten.

Log verbose vom script:

12:17:48.205 | info | javascript.1 (10313) script.js.light.BW_GZ: setForeignState(id=deconz.0.Groups.46.Scene_1.recall, state=true)
-- | -- | --
12:19:47.898 | info | javascript.1 (10313) script.js.light.BW_GZ: getState(id=javascript.0.Lights.Gisizimmer.off, timerId=undefined) => {"val":false,"ack":true,"ts":1581241313629,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1581241313629}
12:19:47.898 | info | javascript.1 (10313) script.js.light.BW_GZ: getState(id=deconz.0.Sensors.31.presence, timerId=undefined) => {"val":false,"ack":true,"ts":1581333587878,"q":0,"from":"system.adapter.deconz.0","user":"system.user.admin","lc":1581333587878}
12:19:47.899 | info | javascript.1 (10313) script.js.light.BW_GZ: getState(id=deconz.0.Sensors.31.presence, timerId=undefined) => {"val":false,"ack":true,"ts":1581333587878,"q":0,"from":"system.adapter.deconz.0","user":"system.user.admin","lc":1581333587878}
12:19:47.899 | info | javascript.1 (10313) script.js.light.BW_GZ: getState(id=javascript.0.Lights.Gisizimmer.off, timerId=undefined) => {"val":false,"ack":true,"ts":1581241313629,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":1581241313629}
12:19:47.900 | info | javascript.1 (10313) script.js.light.BW_GZ: setForeignState(id=deconz.0.Groups.46.on, state=false)

Log vom javscript.1 debug


javascript.1 | 2020-02-10 12:19:47.900 | info | (10313) script.js.light.BW_GZ: setForeignState(id=deconz.0.Groups.46.on, state=false)
-- | -- | -- | --
javascript.1 | 2020-02-10 12:19:47.899 | info | (10313) script.js.light.BW_GZ: getState(id=javascript.0.Lights.Gisizimmer.off, timerId=undefined) => {"val":false,"ack":true,"ts":1581241313629,"q":0,"from":"system.adapter.javascript.0","user":"syste
javascript.1 | 2020-02-10 12:19:47.899 | info | (10313) script.js.light.BW_GZ: getState(id=deconz.0.Sensors.31.presence, timerId=undefined) => {"val":false,"ack":true,"ts":1581333587878,"q":0,"from":"system.adapter.deconz.0","user":"system.user.adm
javascript.1 | 2020-02-10 12:19:47.898 | info | (10313) script.js.light.BW_GZ: getState(id=deconz.0.Sensors.31.presence, timerId=undefined) => {"val":false,"ack":true,"ts":1581333587878,"q":0,"from":"system.adapter.deconz.0","user":"system.user.adm
javascript.1 | 2020-02-10 12:19:47.898 | info | (10313) script.js.light.BW_GZ: getState(id=javascript.0.Lights.Gisizimmer.off, timerId=undefined) => {"val":false,"ack":true,"ts":1581241313629,"q":0,"from":"system.adapter.javascript.0","user":"syste
javascript.1 | 2020-02-10 12:17:48.205 | info | (10313) script.js.light.BW_GZ: setForeignState(id=deconz.0.Groups.46.Scene_1.recall, state=true)

Log von deconz debug:


deconz.0 | 2020-02-10 12:19:48.040 | debug | (10743) getGroupAttributes: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":"1","xy":[0,0]},"devicemembership":[],"etag":"76c5e2c38692c7a37026e57cb08a
-- | -- | -- | --
deconz.0 | 2020-02-10 12:19:48.037 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.035 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.032 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.029 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.026 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.017 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.014 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.011 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.007 | debug | (10743) getGroupScenes for Groups.undefined: undefined
deconz.0 | 2020-02-10 12:19:48.003 | debug | (10743) getGroupAttributes: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":"1","xy":[0,0]},"devicemembership":[],"etag":"76c5e2c38692c7a37026e57cb08a
deconz.0 | 2020-02-10 12:19:47.994 | debug | (10743) getLightState: {"ctmax":65535,"ctmin":0,"etag":"76c5e2c38692c7a37026e57cb08a3bbe","hascolor":true,"manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E27 WS opal 1000lm","name":"GZ Dec
deconz.0 | 2020-02-10 12:19:47.972 | debug | (10743) getLightState: {"ctmax":65535,"ctmin":0,"etag":"76c5e2c38692c7a37026e57cb08a3bbe","hascolor":true,"manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E27 WS opal 1000lm","name":"GZ Dec
deconz.0 | 2020-02-10 12:19:47.963 | debug | (10743) Websocket message: {"e":"changed","id":"46","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"}
deconz.0 | 2020-02-10 12:19:47.959 | debug | (10743) Websocket message: {"e":"changed","id":"46","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"}
deconz.0 | 2020-02-10 12:19:47.958 | debug | (10743) Websocket message: {"e":"changed","id":"37","r":"lights","state":{"alert":null,"bri":37,"colormode":"xy","ct":398,"on":false,"reachable":true},"t":"event","uniqueid":"14:b4:57:ff:fe:52:8b:db-0
deconz.0 | 2020-02-10 12:19:47.951 | debug | (10743) Websocket message: {"e":"changed","id":"37","r":"lights","state":{"alert":null,"bri":37,"colormode":"xy","ct":398,"on":false,"reachable":true},"t":"event","uniqueid":"14:b4:57:ff:fe:52:8b:db-0
deconz.0 | 2020-02-10 12:19:47.949 | debug | (10743) setGroupState BODY: [{"success":{"/groups/46/action/on":false}}]
deconz.0 | 2020-02-10 12:19:47.947 | debug | (10743) setGroupState STATUS: 200
deconz.0 | 2020-02-10 12:19:47.921 | debug | (10743) dp: on; id:Groups.46
deconz.0 | 2020-02-10 12:19:47.920 | debug | (10743) stateChange Groups.46 {"val":false,"ack":false,"ts":1581333587911,"q":0,"from":"system.adapter.javascript.1","user":"system.user.admin","lc":1581333587911}

Vergleichslog deconz wenn schalten klappt:

deconz.0 | 2020-02-10 12:17:26.264 | debug | (10743) getGroupAttributes: {"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":"1","xy":[0,0]},"devicemembership":[],"etag":"d45029e9746ca6e7d08305b51fab
-- | -- | -- | --
deconz.0 | 2020-02-10 12:17:26.242 | debug | (10743) getLightState: {"ctmax":65535,"ctmin":0,"etag":"d45029e9746ca6e7d08305b51fabedde","hascolor":true,"manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E27 WS opal 1000lm","name":"GZ Dec
deconz.0 | 2020-02-10 12:17:26.234 | debug | (10743) getLightState: {"ctmax":65535,"ctmin":0,"etag":"d45029e9746ca6e7d08305b51fabedde","hascolor":true,"manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E27 WS opal 1000lm","name":"GZ Dec
deconz.0 | 2020-02-10 12:17:26.212 | debug | (10743) Websocket message: {"e":"changed","id":"46","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"}
deconz.0 | 2020-02-10 12:17:26.211 | debug | (10743) Websocket message: {"e":"changed","id":"46","r":"groups","state":{"all_on":false,"any_on":false},"t":"event"}
deconz.0 | 2020-02-10 12:17:26.208 | debug | (10743) Websocket message: {"e":"changed","id":"37","r":"lights","state":{"alert":null,"bri":1,"colormode":"xy","ct":398,"on":false,"reachable":true},"t":"event","uniqueid":"14:b4:57:ff:fe:52:8b:db-01
deconz.0 | 2020-02-10 12:17:26.206 | debug | (10743) Websocket message: {"e":"changed","id":"37","r":"lights","state":{"alert":null,"bri":1,"colormode":"xy","ct":398,"on":false,"reachable":true},"t":"event","uniqueid":"14:b4:57:ff:fe:52:8b:db-01
deconz.0 | 2020-02-10 12:17:26.204 | debug | (10743) setGroupState BODY: [{"success":{"/groups/46/action/on":false}}]
deconz.0 | 2020-02-10 12:17:26.203 | debug | (10743) setGroupState STATUS: 200
deconz.0 | 2020-02-10 12:17:26.186 | debug | (10743) dp: on; id:Groups.46
deconz.0 | 2020-02-10 12:17:26.185 | debug | (10743) stateChange Groups.46 {"val":false,"ack":false,"ts":1581333446177,"q":0,"from":"system.adapter.javascript.1","user":"system.user.admin","lc":1581333446177}



Fazit: 
Was ich so sehe gehen die Befehle durch, aber es wird nicht geschalten. Ein Vergleich im deconz log  wenn es klappt sieht nicht anders aus. Somit vermute ich fast, da es erst durch das update in Zusammenhang mit Socket.io autritt muss ich dies eher im deconz adapter als ticket erstellen/verlinken. Sehe ich das richtig? Und wenn kann es mit der socket.io zusammenhängen? 
Danke Ingo!

**Comment by realwax** [comment]
Scheint am 1.2.4 iobroker.deconz zu liegen und wie es momentan aussieht ist es in 1.2.5 gelöst.
