### ISSUE TITLE
JavaScript Engine startet nicht nach Update von 4.3.4 nach 4.4.1

### ISSUE THREAD

**Issue by J-Paul0815** [ioBroker/ioBroker.javascript#497]
Problem
JavaScript Engine startet nicht nach Update von 4.3.4 nach 4.4.1
(oder auch 4.4.0) Instanz javascript.0 wird nicht grün

Node.js v10.19.0, NPM 6.13.4, js-controller 2.2.8, Admin 4.0.1

Fehler im Log

2020-02-10 05:17:01.991 - error: host.iobroker startInstance system.adapter.javascript.0: required adapter "admin" has wrong version. Installed "3.7.7", required ">=4.0.1"!

Gesamter Log
https://pastebin.com/KB6Wc9dv

Install Log 

https://pastebin.com/zZEBhHmS

update done
Adapter    "admin"         : 4.0.1    , installed 4.0.1
Adapter    "alexa2"        : 3.0.7    , installed 3.0.7
....
Adapter    "habpanel"      : 0.4.0    , installed 0.3.4 [Updateable]
Adapter    "influxdb"      : 1.7.0    , installed 1.7.0
Adapter    "info"          : 1.5.7    , installed 1.5.7
....
Adapter    "iot"           : 1.3.1    , installed 1.2.1 [Updateable]
Adapter    "iqontrol"      : 0.2.16
Adapter    "javascript"    : 4.4.0    , installed 4.3.4 [Updateable]

**Comment by Apollon77** [comment]
Iobroker restart also tried? Normally he should catch up new version Infos but ... 

Bzw: single host or multi host Environment?

**Comment by J-Paul0815** [comment]
Of course I tried several times to restart, iobroker as well as VM. Also update, upgrade. I have not set up a multihost.

**Comment by J-Paul0815** [comment]
A repeated upload from the admin solved the problem. Thanks

**Comment by Apollon77** [comment]
If you can still find the install log from Admin Adapter I would love to see it ... (and some lines before and afterwards) . I want to verify something
