### ISSUE TITLE
Work through a reverse proxy.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.javascript#499]
Same issues, but now in script tab
 https://github.com/ioBroker/ioBroker.iot/issues/111 
![image](https://user-images.githubusercontent.com/37106885/74150014-27dee080-4c1a-11ea-8415-e3d85d2a6c0e.png)

**Comment by Apollon77** [comment]
Please try 4.4.2 that should have the same fix as iot.
