### ISSUE TITLE
Last line in editor window missing

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#502]
Beim Scrollen nach unten reicht der Scrollbereich nicht weit genug, so dass die letzte Zeile nicht sichtbar ist (siehe [Forum](https://forum.iobroker.net/topic/30093/skripteditor-letzte-skriptzeile-fehlt)).

**Comment by Apollon77** [comment]
Hatte ich auch gestern

**Comment by paul53** [comment]
Inzwischen werden die letzten 3 Zeilen beim Scrollen ausgeblendet (Version 4.6.22).

**Comment by GermanBluefox** [comment]
Must be fixed with 4.8.5
