### ISSUE TITLE
Blockly extremst langsam

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.javascript#504]
Wie mit Apollon besprochen ist die Bearbeitung von Blockly extrem langsam geworden bei größeren Skripten. Hardwareresourcen sind sowohl beim Nuc (ioBroker) als auch beim Client (iMac) im grünen Bereich. 

Forumlink Problembehandlung: https://forum.iobroker.net/topic/21553/script-engine-java-script-adapter-4-1-12-blockly-bearbeitung-langsam/14 

Hier ein Export vom schlimmsten Skript. 

[ProblemSkript.rtf.zip](https://github.com/ioBroker/ioBroker.javascript/files/4208270/ProblemSkript.rtf.zip)

**Comment by Apollon77** [comment]
Bitte mal JS 4.4.3 versuchen (Achtunf Admin 4.0.5 nötig)
