### ISSUE TITLE
Aliases not usable in Blockly

### ISSUE THREAD

**Issue by Supermicha81** [ioBroker/ioBroker.javascript#505]
If I try to select one of the created devices in a blockly code, iobroker freezes completely.
It happens every time when I click on a device under alias.0 in the devices-browser of the script-editor.

'top' shows alternately the admin-adapter and the js-controller with cpu-loads around 50-60%
and I see on all opend browser-tabs only the turning circle.

the lof-file is completely empty.

After deleting all devices under alias.0 everything wents fine.

Debian 9 VM auf Proxmox
Node.js v10.17.0
NPM 6.11.3
Script Engine 4.3.4
Admin 3.7.1

**Comment by GermanBluefox** [comment]
Do you still have a Problem?

**Comment by Supermicha81** [comment]
I don't use aliases at the moment but i testet a bit and it seems that the problem is gone.
I'm able to select every alias i have created.
