### ISSUE TITLE
Admin >=4.0.1 not in stable repos

### ISSUE THREAD

**Issue by WLAN-Kabel** [ioBroker/ioBroker.javascript#507]
The admin (>=4.0.1) dependency is not in the stable repos. Therefore, users can't update to the last stable version of the javascript adapter if they don't use the latest repos.

**Comment by Apollon77** [comment]
The stable version of JavaScript has a dependency to admin 3.x and not to admin 4. where it gets shown that admin 4 is required?

**Comment by COMHOME** [comment]
![Bildschirmfoto 2020-02-20 um 21 20 58](https://user-images.githubusercontent.com/24495786/74975184-f1c60b80-5426-11ea-86f3-a30e01722ec8.png)
<img width="1440" alt="Bildschirmfoto 2020-02-20 um 21 20 58 2" src="https://user-images.githubusercontent.com/24495786/74975187-f25ea200-5426-11ea-9a7d-faa5b72a59c2.png">

**Comment by COMHOME** [comment]
![Bildschirmfoto 2020-02-20 um 21 22 31](https://user-images.githubusercontent.com/24495786/74975297-21751380-5427-11ea-9ffd-584b8fb317d0.png)

**Comment by Apollon77** [comment]
We had such reports too and I still do not understand ist ... thats why it would be great if we could dig deeper here.

When you installed Admin 3.7.8? Just now or earlier?
Do you have the log from this admin install?

Please execute "iobroker upload admin" ... is the error then still sthere?

**Comment by COMHOME** [comment]
I made a clean install a few weeks ago, Debian Buster, everything’s fine till this javascript Adapter not updating. I‘m not a developer, but if you‘re interested in investigating, PM me, and you can dig in yourself remotely.

**Comment by Apollon77** [comment]
Yes I found it ... reasone is: https://github.com/ioBroker/ioBroker.repositories/issues/621
