### ISSUE TITLE
Make setState update state chache so that getState returns correct value

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.javascript#511]
If adapter is configured to subscribe to all states development "feels" synchronous to developers. But setState still is asynchronous. That leads to issues if you do a setState(id, val) and (without releasing control) do a getState(id, val) afterwards. -> it will still show the old state, because the setState was not handled yet, at least not the eventhandler for the state change in javascript adapter.

If we update id to val in the state chache, getState will return the right value, even if used right after setState.

Applications for this are (appart from obviously not so experienced developers) loops that process a lot of states after one state change. In this cases currently exceptions for handling setState are necessary. In the last week I saw two people having trouble with this situation.

**Comment by GermanBluefox** [comment]
Fixed in 4.4.4
