### ISSUE TITLE
getIdByName('Name with Blank') does not work

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.javascript#512]
Mehtod getIdByName() delivers "undefined" as result  if state name is like
"Abc efg" [includes blank ]or "Abc_efg" [includes underline] but "Abc-efg" [includes minus] works.

JS-Controller: 2.2.9
Admin: 4.0.2
JS Script Engine: 4.4.2
Node/Node.js: 10.19.0
OS: Linux Ubuntu 18.04.3 LTS
Hardware: x64, Intel Core i3

**Comment by paul53** [comment]
Das kann ich nicht nachvollziehen, denn bei mir funktioniert es mit Leerzeichen im Namen.
`log(getIdByName('Rollo Küche Schaltzeit 2'));`
Log:
`script.js.common.Test: 0_userdata.0.EG_Kueche.Rollo.Schaltzeit2`

**Comment by HGlab01** [comment]
Bsp:
```
const shellyID = 'shelly.0.SHSW-25#68844F#1';
var FensterName = getObject(shellyID).common.name;
console.log(FensterName + ': ' + getIdByName(FensterName));
```

Console:
```
19:55:17.636 | info | javascript.0 (10267) script.js.R_Südfenster_rechts: Südfenster rechts: undefined
-- | -- | --
```

**Comment by paul53** [comment]
Die Ursache sind sicherlich nicht die Leerzeichen im Namen, sondern die unzulässigen Zeichen # in der ID.

**Comment by HGlab01** [comment]
An den Leerzeichen liegt es wohl wirklich nicht, an den '#' in den IDs aber auch nicht:

```
const FensterName = getObject(shellyID).common.name;
console.log('Fenstername|ID|Result: [' + FensterName + '][' + shellyID + '][' + getIdByName(FensterName) +']');
```

**Log für  "Südfenster links":**
`Fenstername|ID|Result: [Südfenster links][shelly.0.SHSW-25#C4E314#1][shelly.0.SHSW-25#C4E314#1]
`

**Log für "Südfenster rechts":**
`Fenstername|ID|Result: [Südfenster rechts][shelly.0.SHSW-25#68844F#1][undefined]`

**Log für "Ankleidefenster":**
`Fenstername|ID|Result: [Ankleidefenster][shelly.0.SHSW-25#E66EB3#1][shelly.0.SHSW-25#E66EB3#1]`

**Log für "Westfenster":**
`Fenstername|ID|Result: [Westfenster][shelly.0.SHSW-25#68CFD4#1][undefined]`

Ich erkenne hier kein Pattern. Auch die Raw-Data gibt keinen Aufschluss.
```
{
  "type": "device",
  "common": {
    "name": "Südfenster rechts",
    "read": true
  },
  "native": {},
  "from": "system.adapter.shelly.0",
  "user": "system.user.admin",
  "ts": 1582119219083,
  "_id": "shelly.0.SHSW-25#68844F#1",
  "acl": {
    "object": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

{
  "type": "device",
  "common": {
    "name": "Südfenster links",
    "read": true
  },
  "native": {},
  "from": "system.adapter.shelly.0",
  "user": "system.user.admin",
  "ts": 1582119225766,
  "_id": "shelly.0.SHSW-25#C4E314#1",
  "acl": {
    "object": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by HGlab01** [comment]
Update: Log-Stufe auf "Debug" geändert, nun geht es für alle. Muss jetzt weg sehe mir am Abend an ob vielleicht nur der Restart vom JS-Adapter ausgereicht hat.

**Comment by HGlab01** [comment]
Nach dem Restart des JS-Adapters funktioniert es nun (einstweilen). Scheint aber so als wäre JS Script Engine: 4.4.2 noch nicht 100% stabil.
