### ISSUE TITLE
Instanz ist deaktiviert

### ISSUE THREAD

**Issue by tonibert** [ioBroker/ioBroker.javascript#513]
![image](https://user-images.githubusercontent.com/47660393/75632037-67d12c00-5bf8-11ea-8e9e-2851c18a6d6e.png)

Admin:3.7.8
Node v10.19.0
HomeMatic ReGaHSS 2.5.4
Script Engine 3.4.3
Zigbee 1.0.2

**Comment by Apollon77** [comment]
Kommt das nur kurz zum Start oder immer oder wie?

**Comment by tonibert** [comment]
Es steht bei alles Skripten.
Entschuldige bitte wenn meine Informationen so wenige sind. Ich melde via Github meinen ersten Fehler.Wenn ich dir helfen kann..immer gern

**Comment by tonibert** [comment]
Meine Javascriptinstanz ließ sich nicht mehr starten: 
Aktuell läuft es so:
Admin 4.0.5
Node v10.19.0
ReGaHSS 2.5.4.
Java Script 4.4.3
Zigbee 1.0.2

**Comment by GermanBluefox** [comment]
Sorry ich verstehe gar nichts mehr? 
Wenn "Meine Javascriptinstanz ließ sich nicht mehr starten:" dann "Instanz ist deaktiviert" ist völlig OK.
