### ISSUE TITLE
Aufzählungen: Javascript Neustart bei Änderungen notwendig

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.javascript#515]
Hallo,

Wenn man bei den Aufzählungen eine Änderung vornimmt, dann muß der JS Adapter neu gestartet
werden, weil sonst die Änderungen im Script nicht berücksichtigt werden.
Manchmal auch, wenn bei den Objekten ein anderer Raum ausgewählt wurde.
Das hat mich schon Stunden an Fehlersuche gekostet.

    Raumnamen mit Umlauten werden nicht gefunden.

Meine Bitte an die Spezialisten: Bitte bei Gelegenheit diesen lästigen Fehler beseitigen.
Danke.

Node.js: v10.19.0, admin: v4.0.5

**Comment by GermanBluefox** [comment]
Ist der Fehler "Raumnamen mit Umlauten werden nicht gefunden." oder dass Aufzählungen mit Änderungen ohne Neustart nicht gefunden werden?

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Ist der Fehler "Raumnamen mit Umlauten werden nicht gefunden." oder dass Aufzählungen mit Änderungen ohne Neustart nicht gefunden werden?

Folgende Fehler habe ich bisher gefunden:
- Raumnamen mit Umlauten werden nicht gefunden
- Raumnamen oder Funktionen werden ohne JS Neustart nicht im Script berücksichtigt
- Objekte ohne Funktion werden mit aufgeführt:
  https://github.com/ioBroker/ioBroker.javascript/issues/523
