### ISSUE TITLE
Multi and/or

### ISSUE THREAD

**Issue by LiveSide** [ioBroker/ioBroker.javascript#516]
Hallo Zusammen,
mir ist aufgefallen, dass es sehr schnell, sehr unübersichtlich wird, wenn man mehr als 2 und bzw oder Parameter benötigt.
(Siehe bild
![image](https://user-images.githubusercontent.com/25540062/75900160-ca1a6e80-5e3c-11ea-81bc-c23101d68253.png))
ist es möglich ein "Parameterfenster" zu setzten, an der die Anzahl der Input definiert werden kann?

Siehe Beispiel (Sorry für schlechtes Paint)
![image](https://user-images.githubusercontent.com/25540062/75900511-4e6cf180-5e3d-11ea-9a0c-70cf62511354.png)

Grüße
Live Side

**Comment by wolltswurm** [comment]
Würde ich auch begrüßen 👍🏻

**Comment by obodeldog** [comment]
ebenfalls :-)

**Comment by DutchmanNL** [comment]
This option should be available in all AND & OR statements.

Suggestion, adjust Block in same way as current multiselector blocks with multiple input.

If we use the principle from functions and “build text with” it’s almost intuitive for end user how to add multiple items.

**Comment by GermanBluefox** [comment]
Please extend blockly project and then I will merge it into javascript: https://github.com/google/blockly
