### ISSUE TITLE
Javascript adapter does not start on slave server in multi-host mode

### ISSUE THREAD

**Issue by asutpshnik** [ioBroker/ioBroker.javascript#518]
My conf multihost:
**master:** name smarthome x86 mini PC with debian 10 OS
**slave:** name cubietruck ARM board PC with armbian
Error in slave server log:
`error: host.cubietruck startInstance system.adapter.javascript.1: required adapter "admin" not found!`
But admin adapter is ready and stopped because this server is slave.
![2020-03-07_19-00-08](https://user-images.githubusercontent.com/60661789/76146679-ecfb8b80-60a5-11ea-96f3-38ce6b21834e.png)

**Comment by Apollon77** [comment]
yes, you need to install Admin and create minimum one instance (do not need to run) on the slave too. We needed to add a dependency and this has this effect at the moment. Sorry
