### ISSUE TITLE
wrong time output when formatted

### ISSUE THREAD

**Issue by dercaptainbc** [ioBroker/ioBroker.javascript#520]
current version : 4.4.3

`console.log(getState("deconz.0.Sensors.20.lastupdated").val);`
`console.log(formatDate(getDateObject(getState("deconz.0.Sensors.20.lastupdated").val), "hh:mm:ss"));`

timestamp | level | message
-- | -- | --
09:00:07.937 | info | javascript.0 (1787) script.js.common.004_Telegram.WarnungLüften: 2020-03-13T08:44:24.000Z
09:00:07.937 | info | javascript.0 (1787) script.js.common.004_Telegram.WarnungLüften: 09:44:24

**Comment by Apollon77** [comment]
What is wrng there? A Date object without a timezone should be UTC and so this is correct, or ?!

see https://stackoverflow.com/questions/33114386/datetime-iso-8601-without-timezone-component

It is about the string ending with "Z"

**Comment by dercaptainbc** [comment]
No but before updating to version 4.4.3 it shows the correct time. it only formatted the format to (hh:mm:ss) but not changed the timezone. 

How I can set the timezone that I see the correct time without adding one hour?

**Comment by Apollon77** [comment]
Should be ...Z+01:00 when i remember correctly.

**Comment by GermanBluefox** [comment]
It depends on js-controller and not javascript.
