### ISSUE TITLE
ASTRO does not works all the time

### ISSUE THREAD

**Issue by apla2016** [ioBroker/ioBroker.javascript#527]
I am struggling with ASTRO for a long time, It was working for a while, now it again does not work the way I want it to work. 

To test ASTRO operation I have a simple script requesting warning message on ALL ASTRO times (total 14)

```
schedule({astro: "sunrise", shift: 0}, function () {
  console.warn('astro_on_sunrise');
});
schedule({astro: "sunriseEnd", shift: 0}, function () {
  console.warn('astro_on_sunrise_end');
});
schedule({astro: "goldenHourEnd", shift: 0}, function () {
  console.warn('astro_on_golden_hour_end');
});
schedule({astro: "solarNoon", shift: 0}, function () {
  console.warn('astro_on_solar_noon');
});
schedule({astro: "goldenHour", shift: 0}, function () {
  console.warn('astro_on_golden_hour');
});
schedule({astro: "sunsetStart", shift: 0}, function () {
  console.warn('astro_on_sunset_start');
});
schedule({astro: "sunset", shift: 0}, function () {
  console.warn('astro_on_sunset');
});
schedule({astro: "dusk", shift: 0}, function () {
  console.warn('astro_on_dusk');
});
schedule({astro: "nauticalDusk", shift: 0}, function () {
  console.warn('astro_on_nautical_dusk');
});
schedule({astro: "night", shift: 0}, function () {
  console.warn('astro_on_night');
});
schedule({astro: "nightEnd", shift: 0}, function () {
  console.warn('astro_on_night_end');
});
schedule({astro: "nauticalDawn", shift: 0}, function () {
  console.warn('astro_on_nautical_dawn');
});
schedule({astro: "dawn", shift: 0}, function () {
  console.warn('astro_on_dawn');
});
schedule({astro: "nadir", shift: 0}, function () {
  console.warn('astro_on_nadir');
});
```
I am monitoring log for many days. During each 24 hour period I see only 3 warning messages, not 14 as expected. For some reason I am getting warning messages only for nadir, nautical_dusk and night.

My system is based on Intel platform with all latest adapters and modules:
Node.js 10.19.0
Controller 2.2.10
Script Engine 4.4.3 
I tried script adapter ASTRO setting as system, as well as specific to my location, rebooted computer a few times, but nothing helps.

**Comment by Apollon77** [comment]
Where are you located? nadir especially is sometiomes a weired one, also see issues like https://github.com/mourner/suncalc/issues/70 ... so it could be just "because it do not exists" And lso without your log of cases it is not easy to understand the exact problem you have. Could you please add more and more exact details?

**Comment by apla2016** [comment]
Thank you for quick response. Here are details, let me know if more are needed:
I am in CT, USA. My coordinates as shown in script adapter ASTRO settings: latitude 41.87576, longitude -72.801375
Complete ASTRO messages from yesterday log:
2020-04-05 00:55:09.255 - warn: javascript.0 (1897) script.js.Light_New: astro_on_nadir
2020-04-05 20:24:10.954 - warn: javascript.0 (1897) script.js.Light_New: astro_on_nautical_dusk
2020-04-05 20:59:16.069 - warn: javascript.0 (1897) script.js.Light_New: astro_on_night

**Comment by apla2016** [comment]
Another details about ASTRO work. 
1) As I reported on forum, ASTRO may work properly after fresh controller reboot and then continue to work incorrectly.
2) Since my test script above continuously work at least for nautical dusk, I decided to use ASTRO nautical disk in my real script with time shift, see below. It worked once after reboot and then gets ignored - I see no evidence of it in log file

schedule({astro: "nauticalDusk", shift: -90}, function () {
  console.warn('astro_on_nautical_dusk-90m');
  // Florida Room
  setState("zwave.0.NODE7.SWITCH_MULTILEVEL.Level_1"/*Level*/, 99);
  // Living
  setState("zwave.0.NODE2.SWITCH_BINARY.Switch_1"/*Switch*/, true);
  // TV Room
  setState("zigbee.0.000b57fffebcfc39.state"/*TRADFRI bulb E26 W opal 1000lm Switch state*/, true);
  // Office
  setState("zigbee.0.90fd9ffffe2bad6b.state"/*TRADFRI bulb E26 W opal 1000lm Switch state*/, true);
});
schedule({astro: "nauticalDusk", shift: -60}, function () {
  console.warn('astro_on_nautical_dusk-60m');
  // Outside
  setState("zwave.0.NODE11.SWITCH_BINARY.Switch_1"/*Switch*/, true);
  // Front Door
  setState("zigbee.0.d0cf5efffe7d475c.state"/*TRADFRI bulb E26 W opal 1000lm Switch state*/, true);
});

**Comment by GermanBluefox** [comment]
You can check here if you should have "night" and everything else: http://suncalc.net/#/41.5837,-71.839,6/2020.05.19/11:16

There is a time in the year on some places, where there is no astronomical night

**Comment by apla2016** [comment]
Thank you Bluefox, very useful link, but I am aware of this. For a long while I am reporting that ASTRO function works inconsistently, for example here is number of ASTRO events registered within 24 hrs/day by simple ASTRO TEST script:
5/12 - 5
5/13 - 6
5/14 - 6
5/15 - 8
5/16 - 6
5/17 - 6
5/18 - 6

**Comment by GermanBluefox** [comment]
> Thank you Bluefox, very useful link, but I am aware of this. For a long while I am reporting that ASTRO function works inconsistently, for example here is number of ASTRO events registered within 24 hrs/day by simple ASTRO TEST script:
> 5/12 - 5
> 5/13 - 6
> 5/14 - 6
> 5/15 - 8
> 5/16 - 6
> 5/17 - 6
> 5/18 - 6
> 5/19 - 8
> 5/20 - 6
> 5/21 - 6
> 5/22 - 8

Sorry apla. I cannot fix suncalc. Please create a issue in the according repo.
