### ISSUE TITLE
Monaco editor should use system language/locale

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.javascript#533]
For whatever reason the menus in the Monaco editor are showing in French for me:

![image](https://user-images.githubusercontent.com/3794098/79604575-a199bb80-80ee-11ea-8ab5-612c999cbd2b.png)

I can only assume some sort of geo-location is happening as I am currently in France. However, *all* my system locale, languages, etc. are set to English and that has always been the case.

**Comment by AlCalzone** [comment]
Haha that is funny. I'm not aware of any geo-location stuff but maybe that is happening in the monaco package.

**Comment by AlCalzone** [comment]
Can you please open the browser console (F12) and show me the output of this:
```js
var lang = navigator.language || navigator.userLanguage;
console.log(lang)
```

**Comment by raintonr** [comment]
This looks as it should be:

```
console.log(navigator.languages);
["en-GB", "en-AU", "en", "fr", "it"]
navigator.language
"en-GB"
navigator.userLanguage
undefined
```

**Comment by AlCalzone** [comment]
Your browser is reporting "fr" as one of the possible locales. Since we were missing "en" (which requires no translation), the loader took "fr" as the first supported localization.

I've raised #540 to fix this.

**Comment by raintonr** [comment]
> Your browser is reporting "fr" as one of the possible locales.

I removed that language to confirm and English menus are now displayed. So yes, that is the problem.

But as you correctly say, "en" really should have been used in preference. Thx.
