### ISSUE TITLE
mirror only works for instance 0

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.javascript#534]
Mirror function works only for instance 0. This is enforced here https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/mirror.js#L16

Question: Is there a known reason for that? Is this valid in multihost systems? Should I look into that more?

Adapter should definitively not fail silently. I'll at least add an error to the log output there. (I spent at least one hour experimenting with different paths and user rights before having a look in the code... *sigh*). 
An even better approach would be to check instance number in index_m.html, hide the input if !== 0 and display a hint instead.

**Comment by Apollon77** [comment]
This should be normal. All scripts only exist globally and so only instance 0 cares about this global start. 

Other instances are „just“ executing assigned scripts. 

So it is by design

**Comment by Garfonso** [comment]
I do not really get what you are saying. I removed the check and instance 3 creates the file mirror just fine (also the check was only added October 2019).

I know that scripts exist only globally, but why should a different instance fail to sync them with disk?

**Comment by Apollon77** [comment]
Ok. Yes basically works. As soon as someone starts changing one script on host a and at the same time on host b you can create funny effects. But yes this is then User specific. Make a PR and we can remove that limitation.

**Comment by Garfonso** [comment]
Maybe we can find a way to enforce that only one mirror is defined without forcing it to be 0?

**Comment by AlCalzone** [comment]
> Maybe we can find a way to enforce that only one mirror is defined without forcing it to be 0?

Sounds more intuitive. Maybe it can be done in a way that the first running instance takes care of this. When it is stopped, another can take over.

**Comment by Garfonso** [comment]
> 
> 
> > Maybe we can find a way to enforce that only one mirror is defined without forcing it to be 0?
> 
> Sounds more intuitive. Maybe it can be done in a way that the first running instance takes care of this. When it is stopped, another can take over.

That is probably not a good idea in a multihost system (which is basically my use case here, for me instance 3 is on my development system, where I can make good use of the mirror but instance 0 is on the server and I do not really need the mirror there, apart from backup or something). 

Not sure what the error cases we want to prevent are with enforcing instance 0. 
If I have two instances mirroring to the same path, that probably can cause issues. One way to prevent that would be to write lock files (like .javascript0.lock or something) into the folder and then the idea @AlCalzone proposed could even be implemented.

If we have two instances mirroring on different hosts, then we might run into conflict situations, i.e. on both hosts a file is changed at the same time. That should be a very special case and should be understandable for the users that something like this can cause issues (what can we expect here? Only overwritten changes? Or file corruption?).

The worst thing could be some kind of endless sync-loop (i.e. the sync off instance a triggers sync of instance b which triggers sync of instance a, ...). Not sure if that can happen at all, though.

**Comment by Apollon77** [comment]
Yes you are right. The problem case (that might end in such a loop) would be two instances on same host that have sync enabled to the same location. So one instance per host using mirror is ok. Question is how to prevent that in a understandable was for the user.

**Comment by AlCalzone** [comment]
So we need like a lock state in the adapter context that prevents the other instances from reacting to the change

**Comment by Apollon77** [comment]
Or we need to find a way to do "file system locks" as you normally do in such cases.If I can not get the lock then I do not write.
maybe like https://github.com/moxystudio/node-proper-lockfile (but no idea if all that mtime updates make probs on sd cards)

**Comment by AlCalzone** [comment]
But wouldn't we need a database lock to avoid synchronizing from multiple hosts?

**Comment by Garfonso** [comment]
In which scenario would you need a database lock? The update in db should be atomic, not? -> so database should be a complete version. A lock would help, if we want to implement some kind of "conflict detected -> save copy somewhere else" logic (what for example dropbox has). But I think that is a bit too much.
If you sync on multiple hosts and change the same script on multiple hosts at the same time, you'll have one of the versions in the db. I think that is understandable for the user and easiest to prevent by the user himself.

**Comment by Apollon77** [comment]
In fact we need a "file system lock" to make sure that the same local directory can only be used by ONE JS instance on the same host. This is the problematic topic in my eyes.

An other scenario with multiple instances (and here we would need to really check the sync logic on start) is: If on start of an instance all files are checked and pot resynced and maybe objects get overwritten in DB then an "out of sync" host can create huge damage

**Comment by Garfonso** [comment]
> In fact we need a "file system lock" to make sure that the same local directory can only be used by ONE JS instance on the same host. This is the problematic topic in my eyes.

I agree with that. But I'm no expert at file system locks, sadly. Can we check that by comparing ioBroker configurations? One could use getForeignObject to see the paths of other instances, right? Is there a way to see what host an instance is running on? 

> An other scenario with multiple instances (and here we would need to really check the sync logic on start) is: If on start of an instance all files are checked and pot resynced and maybe objects get overwritten in DB then an "out of sync" host can create huge damage

on start all files are checked and potentially synced. There is a datapoint in ioBroker db which stores the lastsync time. Also the adapter seems to check the lastchanged timestamp of the script objects with the modification time from the files, here: https://github.com/ioBroker/ioBroker.javascript/blob/58a93d0b582e6378f8c78783d369878843fa5e14/lib/mirror.js#L214
But this sure is a scenario that needs to be tested.

**Comment by Apollon77** [comment]
Now that I see that the 2s check is weired ... I think also when writing the file we shuld use https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback to afterwards set the "mtime" to a correct value according to the DB object.

The other code would mean: IF the js adapter (whyever) needs >2s after object change to persist that the file is immediately synced back to db (which is completely unneeded)

**Comment by AlCalzone** [comment]
> In fact we need a "file system lock" to make sure that the same local directory can only be used by ONE JS instance on the same host. This is the problematic topic in my eyes.

Maybe I'm misunderstanding. Wouldn't the different hosts read and write the files on their respective systems? So the issue would be syncing from two different hosts into the same database, no?

**Comment by Apollon77** [comment]
@AlCalzone I think this is relatively easy ... changes will be synced to disk from disk ... this is easy.

In my eyes the only issue will happen if I really have two instances syncing on the same host into the same directory

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/95590308-30f0ad80-0a46-11eb-86dd-084eaf26c2a2.png)
Implemented
