### ISSUE TITLE
new Date(); gibt mit v4.3.4 UTC aus?

### ISSUE THREAD

**Issue by SliX185** [ioBroker/ioBroker.javascript#535]
Hallo,
Hab gerade ein Update von 4.1.12 auf 4.3.4 gemacht und musste festellen, dass ich nur noch die UTC Zeit als Ausgabe bekomme?

`const datum= new Date();
log(datum);`

bei 4.1.12:
`javascript.0	2020-04-18 15:34:52.129	info	(608) script.js.common.Test.Dachrinnenheizung_Test: Sat Apr 18 2020 15:34:52 GMT+0200 (GMT+02:00)`

bei 4.3.4:
`javascript.0	2020-04-18 15:43:12.679	info	(769) script.js.common.Test.Dachrinnenheizung_Test: '2020-04-18T13:43:12.678Z'`

Ist das ein Bug oder ein neues "Feature"?

Als Workaround mit .toLocaleString() geht natürlich, ich brauch aber ein object, also muss ich wieder konvertieren und vorher ging es ja...

Danke im voraus!

**Comment by Apollon77** [comment]
Vorher ging das anders?? Ehrlich?

**Comment by SliX185** [comment]
Servus Apollon,

Jep, wie geschrieben.... Code bleibt identisch, Ausgabe ändert sich.

Bin jetzt wieder von 4.3.4 runter auf 4.1.12 und alles wieder beim alten mit GMT Ausgabe.

**Comment by SliX185** [comment]
...weitere Erkenntnis:

lib\sandbox.js
hat sich von 4.1.12 auf 4.1.12 geändert.
wenn ich in bei installierter 4.1.13 die sandbox.js von 4.1.12 einfüge, bekomme ich wieder GMT Zeit.

**Comment by SliX185** [comment]
... und weiter gehts:
lib\sandbox.js (v4.1.13)

Zeile: 864 - 866:
`            if (typeof msg === 'object') {
                msg = JSON.stringify(msg).replace(/"/g,'\'');
            }`

wird diese entfernt, funktioniert GMT?!

**Comment by Apollon77** [comment]
Ok, basically it is 

https://github.com/ioBroker/ioBroker.javascript/commit/e05e890374ffb509190309491871659842021ca9 from @paul53 with a fix commit 

https://github.com/ioBroker/ioBroker.javascript/commit/e3d3f20dc40cfca84591ab465ee5e87316b365e9 from @GermanBluefox 

The main question is also:
* why?
* and even IF: The change is roughly a year ago and noone noticed so far ... do we change it back?

**Comment by paul53** [comment]
Die Änderung wurde gemacht, um den Inhalt von "normalen" Objekten und Arrays im Log zu sehen und nicht nur object[object]. Ist es möglich zu testen, ob es ein Date-Object ist ?

**Comment by Apollon77** [comment]
sollte an sich mit "instance of Date" gehen oder ?!

**Comment by paul53** [comment]
Danke, PR ist gemacht.

**Comment by GermanBluefox** [comment]
Closed?

**Comment by SliX185** [comment]
funktioniert leider nicht....


`            if (typeof msg === 'object' && !(msg instanceof Date)) {
                msg = JSON.stringify(msg).replace(/"/g,'\'');
            }`

javascript.0 | 2020-04-20 16:43:04.400 | info | (9206) starting. Version 4.5.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v10.19.0
-- | -- | -- | --
javascript.0 | 2020-04-20 16:43:05.233 | info | (9206) script.js.common.Test.Dachrinnenheizung_Test: '2020-04-20T14:43:05.233Z'
-- | -- | -- | --

frisch von Github geladen, Änderungen in der sandbox.js sind vorhanden.

**Comment by SliX185** [comment]
Fehler gefunden...
if (typeof msg === 'object' && !(msg instanceof Date)) { msg = JSON.stringify(msg).replace(/"/g,'\''); }
Ausrufezeichen flasch gesetzt.
if (typeof msg === 'object' && (!msg instanceof Date)) { msg = JSON.stringify(msg).replace(/"/g,'\''); }

PR gemacht.

**Comment by paul53** [comment]
Das Ausrufezeichen ist schon richtig vor der Klammer gesetzt, denn sonst werden "normale" Objekte nicht mehr richtig angezeigt. Ein Test in der Javascript-Instanz hat ergeben, dass die Prüfung funktioniert. Wenn sie an der Stelle im Adapter nicht funktioniert, muss das `Date object` vorher schon verändert worden sein.

**Comment by SliX185** [comment]
Jep, sorry hast natürlicht Recht!
Das übersteigt dann wohl mein JS wissen und lass lieber mal die machen, was auch Ahnung davon haben. 
Also nochmal Sorry fürs zwischen "Pfuschen"

Nichts desto trotz, gibts trozdem ne Lösung?

**Comment by paul53** [comment]
Keine Lösung, aber ein Workaround: Einen Leerstring davor oder dahinter verketten
`log(new Date()+'');`

**Comment by SliX185** [comment]
Danke, funktioniert.
Ich dachte allerdings das meine Funktion:

function test() {
    let time = new Date();
    let timeStart = new Date(); timeStart.setHours(07,40,0);
    let timeEnd = new Date(); timeEnd.setHours(18,35,0);
    
if ((time >= timeStart && time <= timeEnd)) {
        log (time);
    }
else {
        log('OutOfRange')
    }
}
nicht mehr funktionert, oder ich die Zeiten Sommer wie Winter umrechnen muss.... Nö, funktioniert lustigerweise trotzdem.
Nur die geloggte Zeit ist halt UTC


`
18:34:57.860 | info |  javascript.0 (13462) script.js.common.Test.Dachrinnenheizung_Test: '2020-04-20T16:34:57.859Z'
`

`
18:36:36.394 | info | javascript.0 (13462) script.js.common.Test.Dachrinnenheizung_Test: OutOfRange
`
heißt: 

funktion wie gehabt i.O nur der log hat mich verwirrt.

Also Sorry für den ganzen Aufriss und schönen Abend noch!

**Comment by Apollon77** [comment]
Also nehmen wir die Änderungen wieder raus? Oder funktioniert es so wie es jetzt im
Master ist?

**Comment by SliX185** [comment]
Die Änderung macht keinen Unterschied.
GMT Zeit in der log Ausgabe funktioniert nur mit dem Workaround
`log(new Date()+'');`
also kann sie von mir aus wieder entfernt werden.

**Comment by GermanBluefox** [comment]
OK. I found the solution `msg && typeof msg.getMonth !== 'function'`.

We could use `Object.prototype.toString.call(msg) === '[object Date]'` too,
but first code is 4 times faster:
![image](https://user-images.githubusercontent.com/4582016/79784133-16b0ff00-8342-11ea-8b11-8a200c6c9d2d.png)

**Comment by paul53** [comment]
@GermanBluefox: Funktioniert leider nicht
`

host.fred-internet | 2020-04-20 20:17:10.501 | error | Caught by controller[0]: SyntaxError: Unexpected token )
-- | -- | -- | --
host.fred-internet | 2020-04-20 20:17:10.501 | error | Caught by controller[0]: ^
host.fred-internet | 2020-04-20 20:17:10.501 | error | Caught by controller[0]: if (typeof msg === 'object' && typeof msg.getMonth !== 'function')) {
host.fred-internet | 2020-04-20 20:17:10.500 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:959


`

**Comment by SliX185** [comment]
Bei mir schon?! 
javascript.0 | 2020-04-20 20:16:47.080 | info | (18414) script.js.common.Test.Dachrinnenheizung_Test: Mon Apr 20 2020 20:16:47 GMT+0200 (GMT+02:00)
-- | -- | -- | --
javascript.0 | 2020-04-20 20:16:47.079 | info | (18414) script.js.common.Test.Dachrinnenheizung_Test: {'a':1,'b':2}

**Comment by paul53** [comment]
Sorry, hatte einen Fehler eingebaut (Klammer zuviel). Jetzt funktioniert es auch bei mir.

**Comment by SliX185** [comment]
Close?
