### ISSUE TITLE
./node_modules/iobroker.javascript/lib/javascript.d.ts, Fehler bei setState für Selektor

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#538]
Nach meiner Meinung ist in den letzten Versionen der javascript.d.ts ein Fehler in der Definition des Interfaces für  QueryResult für setState. Hier dürfte als Parameter keine Definition für die ID enthalten sein (Zeile 396):
setState<T extends StateValue>(<del>id: string, </del>state: T | State<T> | Partial<State<T>>, ack?: boolean, callback?: SetStateCallback): this;

Die Folge ist, dass einige Skripte mit Selektor-Anweisungen nicht kompiliert werden können.
Ob die Definition mit "id" für andere Befehle notwendig ist kann ich nicht beurteilen, angemeckert wird es jedenfalls nicht.

script engine 4.5.1

**Comment by AlCalzone** [comment]
Ich schau mal, klingt nach nem Bug
