### ISSUE TITLE
Layout-Fehler in Version 4.5.1

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.javascript#542]
Hallo Zusammen,

ich habe den Javascript-Adapter auf die o.g. Version upgedatet. Hier gibt es einen kleinen Layout-Fehler beim Erstellen von Blocklys. Wenn ich das Layout so wähle, dass die Debug-Ausgabe unten sitzt und dann z.B. das Blockly-Menü z.B. der "Listen" wähle, dann wird der letzte auswählbare Block nicht korrekt angezeigt und kann auch nicht hoch gescrollt werden. Hier ein Bild zur Verdeutlichung:

![image](https://user-images.githubusercontent.com/47712364/80279998-6b1cfb80-8701-11ea-9d51-493ed6083871.png)

Erst wenn ich das Debug-Fenster schmaler mache wird der letzte Punkt "numerisch aufsteigend - sortieren" angezeigt. Das ist mir so vorher nicht aufgefallen.

![image](https://user-images.githubusercontent.com/47712364/80280058-d797fa80-8701-11ea-9a42-55b0f916d69f.png)

Verwende den aktuellsten Chrome, habe das Problem unter dem aktuellsten Edge Chromium **nicht**, da wird korrekt gescrollt, egal wie hoch das Debug-Fenster ist!!!

![image](https://user-images.githubusercontent.com/47712364/80280184-d87d5c00-8702-11ea-87ea-a92aee4aeb94.png)

**Comment by GermanBluefox** [comment]
Das ist leider nicht so einfach. An dieser Stelle muss ich sagen Zoom vom Browser benutzen
