### ISSUE TITLE
Blockly error when using sayit

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.javascript#547]
Using sayit in blockly does not work if the volume is set by a data point. If the volume is set by a number it works fine.

`setState("sayit.1.tts.text", "en-US_CLOUD_Female;getState("0_userdata.0.Test.teststring").val;" + 'test');`

`
  |   |   |  
-- | -- | -- | --
javascript.0 | 2020-05-03 02:36:32.148 | error | (1876) at processTicksAndRejections (internal/process/task_queues.js:97:5)
javascript.0 | 2020-05-03 02:36:32.148 | error | (1876) at runMicrotasks (<anonymous>)
javascript.0 | 2020-05-03 02:36:32.148 | error | (1876) at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
javascript.0 | 2020-05-03 02:36:32.148 | error | (1876) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2020-05-03 02:36:32.147 | error | (1876) at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33
javascript.0 | 2020-05-03 02:36:32.147 | error | (1876) at /opt/iobroker/node_modules/iobroker.javascript/main.js:1055:17
javascript.0 | 2020-05-03 02:36:32.147 | error | (1876) at /opt/iobroker/node_modules/iobroker.javascript/main.js:1464:17
javascript.0 | 2020-05-03 02:36:32.147 | error | (1876) at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1411:37)
javascript.0 | 2020-05-03 02:36:32.143 | error | (1876) at compile (/opt/iobroker/node_modules/iobroker.javascript/main.js:1188:28)
javascript.0 | 2020-05-03 02:36:32.143 | error | (1876) at Object.createScript (vm.js:263:10)
javascript.0 | 2020-05-03 02:36:32.143 | error | (1876) at new Script (vm.js:88:7)
javascript.0 | 2020-05-03 02:36:32.142 | error | (1876) SyntaxError: missing ) after argument list
javascript.0 | 2020-05-03 02:36:32.142 | error | (1876) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
javascript.0 | 2020-05-03 02:36:32.141 | error | (1876) setState("sayit.1.tts.text", "en-US_CLOUD_Female;getState("0_userdata.0.Test.teststring").val;" + 'test');
javascript.0 | 2020-05-03 02:36:32.140 | error | at script.js.Test.Skript_1:1
javascript.0 | 2020-05-03 02:36:32.140 | error | (1876) script.js.Test.Skript_1 compile failed:
`

**Comment by Apollon77** [comment]
Ist der js Code wirklich so wie oben? Der ist komplett kaputt. Wird der von blockly so generierte? Ode hast du den geschrieben?

**Comment by MC-1984** [comment]
Der Code wurde von Blockly so generiert. Ich habe dort nichts manuell angepasst oder verändert.

**Comment by Apollon77** [comment]
Zeig mal das blockly bitte als screenshot

**Comment by MC-1984** [comment]
Um alle anderen Fehlerquellen auszuschließen hab ich es in ein separates Skript kopiert:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/58948938/80910536-514a6c80-8d30-11ea-926a-7421a19b5bfb.png">

**Comment by Apollon77** [comment]
Jupp. Bitte issue I’m sayit adspter öffnen. Das blockly ist falsch und muss dort gefixt werden.

**Comment by MC-1984** [comment]
Mach ich, danke!
