### ISSUE TITLE
Java 4.6.0

### ISSUE THREAD

**Issue by michihorni** [ioBroker/ioBroker.javascript#548]
Hallo ich habe Javascript 4.6.0 geupdated. Bei der Scriptausführung hatte ich bislang unter Protokoll immer meine LOG's gesehen. Jetzt nicht mehr, hat das evtl. mit der neuen Version zu tun?
Gruß
Michael

**Comment by Ilovegym66** [comment]
das Update ist mir gar nicht angezeigt worden, bzw. wird es nicht, daher nicht ins latest gepusht worden???

**Comment by michihorni** [comment]
ich habe es gestern im iobroker über die Auswahl von Github installiert.


 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Mittwoch, 06. Mai 2020 um 17:24 Uhr
Von: "Ilovegym66" <notifications@github.com>
An: "ioBroker/ioBroker.javascript" <ioBroker.javascript@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.javascript] Java 4.6.0 (#548)


 

das Update ist mir gar nicht angezeigt worden, bzw. wird es nicht, daher nicht ins latest gepusht worden???

**Comment by Apollon77** [comment]
Nein, die 4.6.0 ist noch nur auf GitHub

**Comment by Apollon77** [comment]
@GermanBluefox

**Comment by GermanBluefox** [comment]
Fixed in 4.6.6
