### ISSUE TITLE
Unable to switch Instances with 3.5.0 adapter

### ISSUE THREAD

**Issue by dusares88** [ioBroker/ioBroker.javascript#55]
see also: http://forum.iobroker.net/viewtopic.php?f=17&t=9467 (including video)

I was not able to switch between instances on 3.5.0. Switching back to 3.4.0 everything worked fine again. It would always directly switch back to instance0 and execute the script there.

Node v6.10.3
JavaScript Controller 1.2.3
ioBroker Admin 3.0.1
Script had Exec Command and Send to Object enabled.

I did not try to update to 3.5.0 again yet, if that issue only exists for me then it might have been a failed installation. Will see if I can check that again the next days.

**Comment by GermanBluefox** [comment]
No more relevant with 4.x
