### ISSUE TITLE
v4.6.1 kaskadierte Bereiche fehlen in Blockly

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#554]
So wie hier mit 4.5.1 zu sehen fehlt der Bereich nach Aktivierung von "mit Ergebnissen" komplett. 

![image](https://user-images.githubusercontent.com/39678667/81648885-b6d4e200-942f-11ea-878a-2e4611d46152.png)

Wenn das Blockly mit 4.5.1 oder älter erzeugt wurde und solche Teile enthält, werden diese auch weiterhin ausgeführt. Aber im Blockly selbst sind sie mit 4.6.1 unsichtbar. Ob sie beim Speichern mit 4.6.1 dann zerstört würden, habe ich nicht getestet.

javascript adapter 4.6.1
JS-Controller 3.1.4
nodejs 10.20.1

**Comment by Apollon77** [comment]
Ist das nur beim Request Blockly oder auch bei anderen?
Irgendwelche Ausgaben in der Browser Konsole?

**Comment by Apollon77** [comment]
Bitte 4.6.1 auf GitHub testen!

**Comment by Apollon77** [comment]
meine 4.6.2

**Comment by Diginix** [comment]
Bug besteht weiterhin.

![image](https://user-images.githubusercontent.com/39678667/81845935-98670780-9551-11ea-9135-0a74d19820ae.png)

Mit 4.5.1 sieht das so aus:
![image](https://user-images.githubusercontent.com/39678667/81846535-889bf300-9552-11ea-9282-d7033ff00d91.png)

**Comment by Apollon77** [comment]
You did a shift reload after update

**Comment by Diginix** [comment]
Ja, und parallel noch in einem separaten Chrome Gast Fenster komplett frisch aufgerufen.
Anbei das Console Log. K.a. ob es was brauchbares enthält.
[javascript_adapter_blockly_cosole.log](https://github.com/ioBroker/ioBroker.javascript/files/4624105/javascript_adapter_blockly_cosole.log)

**Comment by GermanBluefox** [comment]
Please try again. From Github

**Comment by Diginix** [comment]
Now the javascript adapter doesn't load and shows only the splash animation forever.
[javascript_adapter_cosole.log](https://github.com/ioBroker/ioBroker.javascript/files/4624225/javascript_adapter_cosole.log)

Is it not possible for you to reproduce this on your machine?
I need the adapter productive and would stay on 4.5.1.

**Comment by sigi2345** [comment]
> Now the javascript adapter doesn't load and shows only the splash animation forever.

I have the same Problem.
I'm back on version 4.5.1 , and it works.

**Comment by GermanBluefox** [comment]
I could reproduce an error and fixed it. Can you test 4.6.2 from github again please?

**Comment by sigi2345** [comment]
Hallo, Adapter startet wieder, aber Fehler noch da.

**Comment by Diginix** [comment]
The bug is also fixed for me.
Some scripts says that it has changed after first opening (save & cancel button appears). I saw that the header and variable definition is new. But not for all scripts... Strange but all >70 scripts seems to work from what I can say after 20 minutes.

Thanks!
