### ISSUE TITLE
Delay/Verzögerung funktioniert nicht mehr >4.6

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.javascript#555]
Wenn man bei setState die Verzögerung aktiviert kommt im Script nur "NaN"
Es kommt keine Möglichkeit, die Verzögerung einzustellen.

Downgrade auf 4.5.1 und es funktioniert wieder.

**Comment by Apollon77** [comment]
Bitte script auf verbose log stellen und zeigen. Welche Version war vorher installiert 4.5.1? Wo kommt NaN?

**Comment by BassT23** [comment]
4.6.0
<img width="733" alt="1" src="https://user-images.githubusercontent.com/30832786/82033320-da509480-969c-11ea-80bd-5d0c81673a8e.PNG">
<img width="410" alt="2" src="https://user-images.githubusercontent.com/30832786/82033335-df154880-969c-11ea-9b45-f44499f721a1.PNG">

4.6.3
<img width="718" alt="3" src="https://user-images.githubusercontent.com/30832786/82033912-b8a3dd00-969d-11ea-9fb6-cc1e0163a0da.PNG">

**Comment by Apollon77** [comment]
Bitte mal 4.6.4 vomGithub testen

**Comment by Apollon77** [comment]
oder wie sieht es bei der 4.6.3 aus das generierte Skript?

**Comment by BassT23** [comment]
auch mit 4.6.4
<img width="443" alt="1" src="https://user-images.githubusercontent.com/30832786/82083816-997f6c80-96ea-11ea-89f8-8264c7b501b5.PNG">
<img width="349" alt="2" src="https://user-images.githubusercontent.com/30832786/82083792-92f0f500-96ea-11ea-9ccf-6765321c9747.PNG">
Anstelle von NaN sollte die Verzögerungszeit stehen

**Comment by GermanBluefox** [comment]
Fixed in 4.6.6
