### ISSUE TITLE
Fehler astro Funktion 

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.javascript#556]
Hi,

ich habe ein kleines blockly das mir in der Nacht die aktuellen Astrozeiten in Datenpunkte schreibt. Vor ein paar Tagen habe ich gesehen das es damit Probleme gibt,

2020-05-15 13:56:50.017 - error: javascript.0 (29647) Cannot get astro date for "nightEnd"
2020-05-15 13:56:50.026 - error: javascript.0 (29647) Cannot get astro date for "night"

Bei Sichtung der Fehler war 4.5.1 installiert, habe gerade auf 4.6.3 upgedated jedoch leider ohne Besserung. 

Danke

**Comment by GermanBluefox** [comment]
Manche NordStädte haben keine Nacht im Sommer. Ist das vielleicht dein Fall?

**Comment by MMeinhardt1** [comment]
Das ist eine gute Frage. Bislang war es allerdings so das die Werte immer geschrieben wurden, der Fehler wird erst seit ein paar Tagen ausgegeben. 
Kann man das irgendwo nachlesen?

**Comment by GermanBluefox** [comment]
Hier kann man nachschauen: http://suncalc.net/#/53.5636,9.9652,7/2020.05.18/14:43
![image](https://user-images.githubusercontent.com/4582016/82214697-87821180-9916-11ea-8d5a-388182f33168.png)
