### ISSUE TITLE
Textwert im ODER geht nicht

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#557]
Hallo,
folgende Zeile funktioniert .. aber sobald ich den Text ver-ODERN möchte .. haftet das Blockly nicht mehr.

![wert sprenger an](https://user-images.githubusercontent.com/4311558/82111088-adef5380-9742-11ea-87d0-45e4cd5bd5fb.png)

**Comment by daniel-lo** [comment]
Wenn ich das ODER nach vorne stelle geht es. Vielleicht ist das "by design" so .. bin nicht sicher.

**Comment by Apollon77** [comment]
Der oder Block ist der wo du die relevanten Blöcke reinhängst. Oder wie versuchst du es? Wenn Blöcke nicht „haften“ heißt das an sich das es so nicht geht.

**Comment by daniel-lo** [comment]
Der Oder-Block sollte dort hin wo jetzt "sprenger an" steht .. und dann wollte ich zwei Texte dahinter hängen. Oder direkt an Falls hängen funktioniert .. ich glaube das meinst Du.

**Comment by Apollon77** [comment]
Es muss direkt an false und dann quasi

Falls - oder - wert von ne1 / wert von nr 2

**Comment by daniel-lo** [comment]
danke für's feedback
