### ISSUE TITLE
Blockly Fehler mit 4.6.7

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.javascript#560]
habe auch bei Blockly ein Problem mit 4.6.7

Das 18:00ist ein Phantom. Soll dort nicht sein, geht auch nicht zum löschen, hat aber zumindest keine Funktion.
Blockly funktioniert trotz dem Phantom.

Mit 4.6.9 aus Git besteht das Phänomen noch immer.

![javascript - ioBroker](https://user-images.githubusercontent.com/45309436/82130572-d2900d80-97cc-11ea-81f4-6667190e7398.png)

Thread im Forum: https://forum.iobroker.net/topic/33419/script-engine-update-nach-4-6-4

**Comment by GermanBluefox** [comment]
Gefixt in 4.6.10
