### ISSUE TITLE
V 4.6.4 Aussprachefehler aus dem Script heraus

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.javascript#561]
Da ich Alexa per Scripte Zustände ansagen lasse, hab ich die Fehler bemerkt:
Eine Ansage so lange ausgeführt wird, bis ich den Adapter stoppe.
Bei einer 2.ten Ansage wird das Wort "er" zu "e" "r".
Dia Aussprache ist abgehackt

**Comment by Apollon77** [comment]
Seit wann passiert das? Mehr Details bitte. Wie sieht das Skript aus? Passiert der gleiche Effekt wenn du per Admin das ganze machst und nickender Skript?

Was Aussprache angeht hat Amazon wohl die letzten Tage dinge geändert. Da sind unsere Adapter raus ...

**Comment by guergen1** [comment]
Das ganz passiert seit gestern, nach dem Update vom javascript auf 4.6.4.
`on({id: 'mihome-vacuum.0.info.state', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("mihome-vacuum.0.info.state").val == 6 && getState("mihome-vacuum.0.info.error").val == 0) {
    setState("alexa2.0.Echo-Devices.G090LF1174170RP2.Commands.speak"/*speak*/, (['Saugi ist fertig. Er hat ',getState("mihome-vacuum.0.info.cleanedtime").val,' Minuten gebraucht. Dabei hat er ',getState("mihome-vacuum.0.info.cleanedarea").val,' Quadratmeter gereinigt. Akkustand ',getState("mihome-vacuum.0.info.battery").val,' Prozent'].join('')));
    sendTo("telegram", "send", {
        text: (['Saugi ist fertig. Er hat ',getState("mihome-vacuum.0.info.cleanedtime").val,' Minuten gebraucht. Dabei hat er ',getState("mihome-vacuum.0.info.cleanedarea").val,' Quadratmeter gereinigt. Akkustand ',getState("mihome-vacuum.0.info.battery").val,' Prozent'].join('')),
        user: 'Ralf'
    });
  }
});`

**Comment by guergen1** [comment]
Diee Ansage läuft, bis ich den Adapter stoppe, das hat vorher alles sehr gut funktioniert; mindestens ein Jahr

`var Lautst_C3_A4rke_zwischenspeichern;


on({id: 'alexa2.0.History.summary', change: "any"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if ((obj.state ? obj.state.val : "").indexOf('fernsehe') + 1 >= 1 && ((obj.state ? obj.state.val : "").indexOf('an') + 1 >= 1 || (obj.state ? obj.state.val : "").indexOf('einschalten') + 1 >= 1)) {
    setState("sonoff.0.TV-Steckdose.POWER1"/*TV-Steckdose POWER1*/, true);
    setState("enigma2.0.main_command.WAKEUP_FROM_STANDBY"/*Wakeup form Standby*/, true);
    Lautst_C3_A4rke_zwischenspeichern = getState("alexa2.0.Echo-Devices.G090LF1174170RP2.Commands.speak-volume").val;
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak-volume"/*Volume to use for speak commands*/, 50, 100, false);
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak"/*speak*/, ('Der Fernseher ist jetzt an'), 1000, false);
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak-volume"/*Volume to use for speak commands*/, Lautst_C3_A4rke_zwischenspeichern, 3000, false);
  } else if ((obj.state ? obj.state.val : "").indexOf('fernsehe') + 1 >= 1 && ((obj.state ? obj.state.val : "").indexOf('aus') + 1 >= 1 || (obj.state ? obj.state.val : "").indexOf('ausschalten') + 1 >= 1)) {
    setState("sonoff.0.TV-Steckdose.POWER1"/*TV-Steckdose POWER1*/, false);
    setState("enigma2.0.main_command.STANDBY"/*Standby*/, true);
  }
});`

**Comment by Apollon77** [comment]
Naja bau doch mal logging ein was genau wann gesetzt wird oder stell das Skript auf verbose log dann siehst du was passiert. 

Ob es am js Adapter liegt kannst mit einem downgrade auf 4.5.1 rausfinden.  Kann mir den Effekt jetzt so nicht direkt erklären
