### ISSUE TITLE
Seid Java Engine (ioBroker) Update auf 4.6.4 laufen meine Blockly Skripte nicht mehr

### ISSUE THREAD

**Issue by Brootmann** [ioBroker/ioBroker.javascript#563]
![IMG_1361](https://user-images.githubusercontent.com/65487547/82140788-99d64f80-9831-11ea-983d-104930bd762d.JPG)
![IMG_1362](https://user-images.githubusercontent.com/65487547/82140793-a2c72100-9831-11ea-9099-7ad3225e1cb3.jpg)

**Comment by Xenon-s** [comment]
gleiches Problem, nach einem Downgrade auf 4.5.1 kann man das Blockly auch nicht mehr öffnen

**Comment by GermanBluefox** [comment]
Das wurde in 4.6.9 gefixt

**Comment by DenwoT** [comment]
Habe das gleiche Problem mit den Timeouts in allen Scripten.

Version: 4.6.4
Version: 4.6.9 (vom GIT)

Beide Versionen beinhalten bei mir den Fehler.

**Comment by DenwoT** [comment]
Mit Version 4.6.10 läuft es bei mir wieder. Timeouts werden richtig dargestellt. Danke dir
