### ISSUE TITLE
Cannot load socket.io.js (4.6.10)

### ISSUE THREAD

**Issue by BassT23** [ioBroker/ioBroker.javascript#564]
nach Update von 4.6.9 und auch auf 2. Testsystem von 4.5.1 kommt nach dem Update ein "Cannot load socket.io.js" 

Kein laden der Scrip Seite

socket.io ist auf 3.0.7 (aktuellste)
Bis 4.6.9 war das noch nicht

**Comment by Negalein** [comment]
bei 4.6.10 ist er auch noch vorhanden

**Comment by Apollon77** [comment]
Mit der Meldung ist nicht der Adapter gemeint

**Comment by BassT23** [comment]
Bin leider kein coder 🙃

**Comment by fu-zhou** [comment]
Sobald ich auf Skripte klicke, kommt bei mit auch die Meldung
![Bildschirmfoto vom 2020-05-17 21-45-53](https://user-images.githubusercontent.com/11984960/82158451-3a575e80-9888-11ea-9cdf-267f541c66e4.png)

**Comment by Garfonso** [comment]
Ich bekomme einen solchen Fehler nicht angezeigt, sehe aber in der Konsole das hier:
![javascript-error](https://user-images.githubusercontent.com/620860/82160619-fddf2f00-9896-11ea-9a66-e842170e7557.JPG)

und sehe ebenfalls keine Skripte. (Bin im Firefox unterwegs normalerweise). Ganz witzig ist, dass es manchmal hilft den Browser zu wechseln oder F5 zu drücken.
Javascript version 4.6.4.

**Comment by GermanBluefox** [comment]
Fixed in 4.6.11
