### ISSUE TITLE
keine Eingabe der Verzögerung mehr möglich nach Update auf 4.6.4

### ISSUE THREAD

**Issue by ajeder** [ioBroker/ioBroker.javascript#565]
Hallo,
nach dem Update auf Ver. 4.6.4 kann man zwar das Verzögerungshäkchen setzen, aber eine Eingabe des Wertes ist nicht mehr möglich.
Intern werden die Skripte aber mit Verzögerung ausgeführt, der Wert ist also nicht weg, man kommt lediglich nicht mehr dran. (siehe Screenshot)

Grüße,
Axel
![verzögerung](https://user-images.githubusercontent.com/57416993/82174934-87f8b900-98d2-11ea-9c12-deb04f032e2e.jpg)

**Comment by BassT23** [comment]
wurde von @GermanBluefox gefixt.
Update auf 4.6.11 Hilft

**Comment by ajeder** [comment]
..perfekt! Alles wieder da in 4.6.11

Vielen Dank
