### ISSUE TITLE
Vorgegebener Zeitplan-Bezeichner sollte nicht schedule sein

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#567]
Beim Zeitplan wird der Bezeichner _schedule_ für die Variable vorgegeben, was dazu führt, dass sich der Zeitplan nicht stoppen läßt, da die Funktion den gleichen Bezeichner hat.

**Comment by GermanBluefox** [comment]
Nichts verstanden. Hast du Screenshot?

**Comment by paul53** [comment]
Ja, [im Forum](https://forum.iobroker.net/post/425793)

**Comment by Apollon77** [comment]
fixed in 4.6.14
