### ISSUE TITLE
Debug-Output merkwürdig

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#568]
Hallo allerseits, mich wundert, dass die Debug-Ausgabe dreifach vorkommt .. und auch, dass mein Speak-Objekt nicht gefunden werden soll. Diesen Echo gibt es gar nicht mehr .. und das Speak-Objekt ist mit dem richtigen Device/Objekt Verbunden. Außerdem sollte er gar nicht in den Schleifenteil gelangen.

![2020-05-19_063129 Skript](https://user-images.githubusercontent.com/4311558/82285082-dbced500-999a-11ea-8e22-e6e193a581a8.png)
![2020-05-19_063057 log](https://user-images.githubusercontent.com/4311558/82285087-de312f00-999a-11ea-8774-6db12c70aa21.png)

**Comment by Apollon77** [comment]
Bitte das State in blockly nochmal neu setzen  Irgendwie István der alte state noch drin und das sagt die Fehlermeldung.

**Comment by daniel-lo** [comment]
Oje .. wenn ich das verstehen würde?!

**Comment by GermanBluefox** [comment]
> Bitte das State in blockly nochmal neu setzen Irgendwie István der alte state noch drin und das sagt die Fehlermeldung.

Nein @daniel-lo meint, dass `script.js.common.Bewässetung: Zeit OK` 3 mal vorkommt.
Das kann sein wenn:
- State mit `ack:false` und `ack:true` beschrieben wird.
- Du hast 3 Javascript Instanzen am laufen. Hier hilft neustart.

**Comment by daniel-lo** [comment]
OK .. neustart wird gemacht.
Was ist denn mit dem verwaisten Echo .. das im Skript überhaupt nicht verwendet wird?
Und .. warum überhaupt ein Echo im Log erscheint? Wo doch der Zweig "Zeit OK" verwendet wird.

**Comment by Apollon77** [comment]
Wenn das Skript meckert dann ist es verwendet. DU kannst im Blockyl immer anschauen was das generierte Javascript enthält, schau doch da nach.

**Comment by daniel-lo** [comment]
Auch im JS finde ich die Alexa-Kennung nicht.

**Comment by Apollon77** [comment]
Dann sollte aber das Skript beim Start nicht darüber meckern. Bitte mal den javacript adapter neu starten

**Comment by daniel-lo** [comment]
Scheint jetzt ok zu sein .. jetzt gibt es nur noch die Dreifach-Debugs. Muss ich beobachten .. bin grad in der anderen Schleife.
