### ISSUE TITLE
Block "steuere": Haken bei "löschen falls läuft" hat keinen Einfluss auf Javascript-Code

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#569]
Bei den Blöcken "aktualisiere" und "umschalten" wird "lösche falls läuft" berücksichtigt.
Version 4.6.13

**Comment by GermanBluefox** [comment]
"nicht" berücksichtigt ??

**Comment by paul53** [comment]
Bei "aktualisiere" und "umschalten" wird der richtige Javascript-Code erzeugt, bei "steuere" nicht.

**Comment by paul53** [comment]
Der Fehler ist in Version 4.6.15 leider immer noch vorhanden.

**Comment by GermanBluefox** [comment]
Please test 4.6.16.

**Comment by paul53** [comment]
Version 4.6.16 von Github:
`// ohne "löschen falls läuft"
setStateDelayed("Object ID", , 1000, false);
// mit "löschen falls läuft"
setStateDelayed("Object ID", , 1000, true);`
