### ISSUE TITLE
invalid date provided ?

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.javascript#570]
since 4.6.13 this error message is in the logfile:

`
javascript.0 | 2020-05-19 17:31:00.003 | error | (11238) script.js.common.Message.Uhrzeit: Invalid date object provided: "2020-05-19T15:31:00.003Z"
-- | -- | -- | --
`

Invalid date object from what/where/who ?? How can I find the reason / script?

**Comment by paul53** [comment]
lib/sandbox.js: delete lines 2313 - 2315

**Comment by Apollon77** [comment]
try 4.6.14 please

**Comment by paul53** [comment]
Die Fehlermeldung (s.o) kommt weiterhin (bei mir wieder). Den Grund hat Bluefox selbst beschrieben: 
> // we cannot use here (msg instanceof Date) because vm converts object to something else, but Date.

**Comment by Ilovegym66** [comment]
@paul53 thank you, I've commented the lines out, the error message is gone. :-) and the time is correct now.
@apollon77 sorry, not fixed, before I commented out, I've installed and uploaded latest git version from now 09.00 o'clock local time.

**Comment by Apollon77** [comment]
should be by 4,6,15 soon-ish

**Comment by Ilovegym66** [comment]
Error is gone in 4.6.15.
Thanks @paul53 for the workaround!
