### ISSUE TITLE
Neues Script erstellen erzeugt Script in neuem Ordner

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.javascript#571]
Hallo, ich möchte ein neues Script erstellen mit dem Namen "Anwesenheitskontrolle ueber radar2  Adapter V2.0" im Ordner "Anwesenheit"

![image](https://user-images.githubusercontent.com/47712364/82366340-5981f780-9a12-11ea-8101-cf32e4a626a9.png)

Anwesenheit ist dazu blau hinterlegt. Ich drücke auf das "+" oben für neues Script und gebe den Namen ein. Das Ergebnis ist aber:

![image](https://user-images.githubusercontent.com/47712364/82366566-a960be80-9a12-11ea-816a-c7d793233e65.png)

Es wird ein neuer Ordner und der Eintrag für ein neues Script erstellt...

Installiert ist 4.6.13 über git, node 12.16.3

**Comment by GermanBluefox** [comment]
Punkte in Namen sind verboten

**Comment by Apollon77** [comment]
better handled by 4.6.14

**Comment by XxJooO** [comment]
> Punkte in Namen sind verboten

Ok, ich versuche 4.6.14

Danke!!!
