### ISSUE TITLE
V 4.6.13 Fehlermeldungen im LOG

### ISSUE THREAD

**Issue by michihorni** [ioBroker/ioBroker.javascript#572]
Hallo ich habe heute die 4.6.13 installiert. Ich habe plötzlich im LOG einige Fehler die ich mir nicht erklären kann.
![Unbenannt](https://user-images.githubusercontent.com/27429377/82373860-7f14fe00-9a1e-11ea-93f4-b0541f8021ec.JPG)
Gruß
Michael

**Comment by Apollon77** [comment]
Bitte prüfe das angegebene Skript, da ist ein Syntaxfehler drin. Der Editor sollte das anzeigen
