### ISSUE TITLE
Blockly - Keine Umlaute in Timeout und Intervall möglich

### ISSUE THREAD

**Issue by winnyschuster** [ioBroker/ioBroker.javascript#578]
Beim Verwenden eines Intervalls/Timeouts mit z.B. dem Namen Grün werden die Variablen falsch gesetzt. 

**Beispiel:**

var **Gr_C3_BCn**;

Grün = setInterval(function () {
  console.log('Intervall');
}, 1000);

**Comment by winnyschuster** [comment]
Die Fehler sind mit 4.6.15 verschwunden, jedoch werden die Variablen immer noch 'seltsam' umgewandelt. **Falls dies notwendig ist, könnte das issue geschlossen werden**.

var **Gr_C3_BCn**;
**Gr_C3_BCn** = setInterval(function () {
console.log('Intervall');
}, 1000);

Sollte es nicht so aussehen?
var **Grün**;
**Grün** = setInterval(function () {
console.log('Intervall');
}, 1000);

**Comment by Apollon77** [comment]
Nein, Umlaute sind keine erlaubten Zeichen für Variablennamen, Von daher passt schon so
