### ISSUE TITLE
"mit Ergebnissen" bei sendTo (Blockly) funktioniert nicht mehr

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.javascript#579]
Bei der Aktuellen Version kann man den haken "mit Ergebnissen" beim SendTo Block nicht mehr anhaken.

Das Loglevel wird beim Klick zurückgesetzt auf 'keins'

Script: 4.6.14
JS-Controller: 3.1.4
Admin: 4.1.1
NodeJS: v10.20.1

**Comment by Omega236** [comment]
Bei bestehenden Skripten existiert der "result" Code noch, aber in der Blockly-Ansicht ist "mit Ergebnissen" auch abgehakt. sobald man etwas verändert wird der "result" Code auch gelöscht

**Comment by GermanBluefox** [comment]
Please test 4.6.16.
The shape of block is slightly changed. Don't be scared.

**Comment by Omega236** [comment]
Funktioniert. Danke
