### ISSUE TITLE
4.6.15: Cannot extract Blockly code!

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.javascript#580]
Hallo, nach dem Update von 4.6.14 auf 4.6.15 kommt die Meldung "Cannot extract Blockly code!" und das Blockly Script wird nicht angezeigt.
![Bildschirmfoto vom 2020-05-24 10-58-31](https://user-images.githubusercontent.com/11984960/82750070-10cd9400-9dae-11ea-94a6-75a44ee19032.png)
Das passiert nur mit Skripten die "Timeout" enhalten. Ein Downgrade auf 4.6.14 behebt das Problem nicht. Ich bin im Moment von der Ferne über Pro (Cloud) auf dem System. Ich weiß allerdings nicht, ob das Problem über die Cloud bei 4.6.14 schon bestand.
Beim Umschalten auf JavaScript wird der Code angezeigt.

**Comment by GermanBluefox** [comment]
Cloud hat noch alte Version von Javascript. Und ja, erst wenn javascript in stable wird, wird auch cloud upgedatet. Also wenn Blockly unbedingt über cloud editiert sein sollte, dann kein latest verwenden.
