### ISSUE TITLE
Trigger - Astro Nachtende funktioniert nicht mehr

### ISSUE THREAD

**Issue by 7egacy** [ioBroker/ioBroker.javascript#581]
Ich habe verschiedene Astro Trigger die problemlos funktionieren, jedoch geht seit ein paar Tagen der Astro Trigger Nachtende nicht mehr. Ist hierzu etwas bekannt?

RPi4
Node.js v10.20.1
NPM 6.14.4
Script Engine 4.6.15
js Controller 3.1.4

**Comment by Apollon77** [comment]
naja ... vllt bringt das die Lösung? https://github.com/ioBroker/ioBroker.javascript/issues/556

Bitte prüfen und ggf schliessen

**Comment by 7egacy** [comment]
Danke, das war das Problem
