### ISSUE TITLE
Warnung im eingeklappten Blocky Baustein

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.javascript#582]
verweise auf https://forum.iobroker.net/post/438103
![image](https://user-images.githubusercontent.com/41550245/82754385-de7f5f00-9dcc-11ea-8cd5-6ccfe09b8c77.png)

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren: 
![image](https://user-images.githubusercontent.com/4582016/82755454-decf2880-9dd3-11ea-8630-7af7186ef05d.png)

Gibt es export xml?

**Comment by crunchip77** [comment]
Ja, siehe https://forum.iobroker.net/post/436840

**Comment by crunchip77** [comment]
habe heute ein Script importiert, abgespeichert, kein Fehler. Nach anpassen der Variablen auf die eigene ObjektID, erschien allerdings nach speichern des Script wieder die Warnung im eingeklappten Block. siehe https://forum.iobroker.net/post/438581 bzw  https://forum.iobroker.net/post/438565

**Comment by GermanBluefox** [comment]
https://github.com/google/blockly/pull/3915

**Comment by GermanBluefox** [comment]
Minimal test case:
```
<block xmlns="https://developers.google.com/blockly/xml" type="on_ext" id="SX%6!fqcVoVlD@SU-7Y4" x="162" y="63">
  <mutation xmlns="http://www.w3.org/1999/xhtml" items="1"></mutation>
  <field name="CONDITION">ne</field>
  <field name="ACK_CONDITION"></field>
  <value name="OID0">
    <shadow type="field_oid" id=";0_S:)AqTJF$]lRUv@gx">
      <field name="oid">default</field>
    </shadow>
    <block type="text" id="M^,86XR;qj#RRcuTOHSJ">
      <field name="TEXT">a</field>
    </block>
  </value>
  <statement name="STATEMENT">
    <block type="debug" id=":kTgv24Gf3Nv%Et[;yQy">
      <field name="Severity">log</field>
      <value name="TEXT">
        <shadow type="text" id="z2k)pj#6ydcho|)AD*(?">
          <field name="TEXT">test</field>
        </shadow>
        <block type="on_source" id="k0G9$$9#3Q(k]iwF`h}S">
          <field name="ATTR">id</field>
        </block>
      </value>
    </block>
  </statement>
</block>
```

**Comment by crunchip77** [comment]
habe ich gerade versucht, block importiert, auf speichern gedrückt, blockly verschwunden und Ladekreis, danach leer
![image](https://user-images.githubusercontent.com/41550245/82806314-cddeef80-9e85-11ea-8f0a-ed0d7d702561.png)
wenn ich umschalte auf javascript, erscheint dieses
![image](https://user-images.githubusercontent.com/41550245/82806382-f961da00-9e85-11ea-92f3-0b84f047c027.png)

**Comment by Diginix** [comment]
Problem mit falschen Warnungen ist bei mir mit 4.6.17 gelöst.

**Comment by crunchip77** [comment]
bei mir auch, funktioniert wieder
