### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by tsvsj** [ioBroker/ioBroker.javascript#583]
Hi,

since today I get the error message `TypeError: Cannot read property 'default' of undefined` while loading scripts within admin. This message is generated by `2.38f4fe4b.chunk.js:2`. After the error is generated the script stops to work and the JS UI is not loaded - just a white screen.

I've updated to js-controller 3.1.4 yesterday, but the issue occured after updating admin to 4.1.11 and enabling reactJS. Turning off reactJS and downgrading to 4.0.10 didn't solve the issue. I'm at the most recent adapter version 4.6.16, released today. The issue exists on 4.6.15 as well. I've updated the adapter to 4.6.16 just an hour ago.

Any ideas?

**Comment by Apollon77** [comment]
reactJS is that early in 4.1.11 ... please do not use it right now ... it is most probably a problem in Admin with the new reactJS which is way too early

**Comment by tsvsj** [comment]
I've already downgraded admin to 4.0.10 and disabled reactJS, but the issue persists. After disabling reactJS the source script of the error message changed to the one mentioned above.

**Comment by Apollon77** [comment]
which javascript version you use? Did you cleared browser cache and such?

**Comment by tsvsj** [comment]
As mentioned above I'm using 4.6.16. But deleting the cache solved my issue. Thank you very much!
