### ISSUE TITLE
Cannot extract Blockly code!

### ISSUE THREAD

**Issue by TomSC1984** [ioBroker/ioBroker.javascript#584]
Hallo Habe seit update auf 4.6.16 das Problem dass machne skripts sich nicht mehr öffnen lassen. 
Als Fehlermeldung kommt dann :    Cannot extract Blockly code! 

Gruß Thomas

**Comment by Apollon77** [comment]
Über cloud aufgerufen oder direkt im Browser?
Bitte mal unter Objekte für Filter entfernen (vor allem Typ) und dann dort die Skript Objekte suchen (scripts.js.*) und so eine Skript raussuchen. Dann rechts auf den Stift und das json unter raw hier posten.

**Comment by TomSC1984** [comment]
ich rufe über die Cloud auf. 
`{
  "from": "system.adapter.admin.0",
  "ts": 1590306873208,
  "user": "system.user.admin",
  "common": {
    "name": "Befuellung",
    "engineType": "Blockly",
    "source": "var befuellung, Verz_C3_B6gerung, timeout;befuellung = 0;on({id: 'hm-rpc.0.OEQ1017814.1.STATE', change: ",
    "engine": "system.adapter.javascript.0",
    "enabled": true,
    "debug": false,
    "verbose": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "script.js.Logik.Pond.Befuellung",
  "type": "script"
}`

**Comment by TomSC1984** [comment]
wenn ich das script mit einem anderen funktionierendem vergleiche sind da schon unterschiede. Hier mal eins das funktioniert.
`{
  "common": {
    "name": "Berechnungen",
    "expert": true,
    "engineType": "Blockly",
    "engine": "system.adapter.javascript.0",
    "source": "on({id: \"knx.0.Weiher.Stromverbrauch.Pumpe_Stromwert\"/*Pumpe Stromwert*/, change: \"ne\"}, function (obj) {\n  var value = obj.state.val;\n  var oldValue = obj.oldState.val;\n  setState(\"javascript.0.Berechungen.Leistung_Pumpe\"/*Berechungen.Leistung_Pumpe*/, (getState(\"knx.0.Weiher.Stromverbrauch.Pumpe_Stromwert\").val * 0.23), true);\n});\n\n//JTNDeG1sJTIweG1sbnMlM0QlMjJodHRwJTNBJTJGJTJGd3d3LnczLm9yZyUyRjE5OTklMkZ4aHRtbCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMm9uJTIyJTIwaWQlM0QlMjJPJTdENE1sZTBYRSUzQiUyNVpXdG1pXzYlMjNZJTIyJTIweCUzRCUyMi0xMzclMjIlMjB5JTNEJTIyMTMlMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0VrbnguMC5XZWloZXIuU3Ryb212ZXJicmF1Y2guUHVtcGVfU3Ryb213ZXJ0JTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJDT05ESVRJT04lMjIlM0VuZSUzQyUyRmZpZWxkJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyQUNLX0NPTkRJVElPTiUyMiUzRSUzQyUyRmZpZWxkJTNFJTNDc3RhdGVtZW50JTIwbmFtZSUzRCUyMlNUQVRFTUVOVCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMnVwZGF0ZSUyMiUyMGlkJTNEJTIyJTNEWCUzQnhxJTJCT1RMXyU1RSUzQTdqISUyQm5xJTNBWiUyMiUzRSUzQ211dGF0aW9uJTIwZGVsYXlfaW5wdXQlM0QlMjJmYWxzZSUyMiUzRSUzQyUyRm11dGF0aW9uJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT0lEJTIyJTNFamF2YXNjcmlwdC4wLkJlcmVjaHVuZ2VuLkxlaXN0dW5nX1B1bXBlJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJXSVRIX0RFTEFZJTIyJTNFRkFMU0UlM0MlMkZmaWVsZCUzRSUzQ3ZhbHVlJTIwbmFtZSUzRCUyMlZBTFVFJTIyJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIybWF0aF9hcml0aG1ldGljJTIyJTIwaWQlM0QlMjIxRzclNUJVRXQlMjRGcnRzNmZFYThnLmolMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPUCUyMiUzRU1VTFRJUExZJTNDJTJGZmllbGQlM0UlM0N2YWx1ZSUyMG5hbWUlM0QlMjJBJTIyJTNFJTNDc2hhZG93JTIwdHlwZSUzRCUyMm1hdGhfbnVtYmVyJTIyJTIwaWQlM0QlMjJHUWFxNSU0MHhUJTVFKHElNjBTJTNGJTIzJTJDR1gyXyUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMk5VTSUyMiUzRTElM0MlMkZmaWVsZCUzRSUzQyUyRnNoYWRvdyUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmdldF92YWx1ZSUyMiUyMGlkJTNEJTIyfjFFWGgqdnZzJTVCTWMlM0Q1NmFKdjElN0IlMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJBVFRSJTIyJTNFdmFsJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0VrbnguMC5XZWloZXIuU3Ryb212ZXJicmF1Y2guUHVtcGVfU3Ryb213ZXJ0JTNDJTJGZmllbGQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnZhbHVlJTNFJTNDdmFsdWUlMjBuYW1lJTNEJTIyQiUyMiUzRSUzQ3NoYWRvdyUyMHR5cGUlM0QlMjJtYXRoX251bWJlciUyMiUyMGlkJTNEJTIySTlzZH4xJTJDcUM0VGxlJTNCSm5OUVZrJTIyJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyTlVNJTIyJTNFMC4yMyUzQyUyRmZpZWxkJTNFJTNDJTJGc2hhZG93JTNFJTNDJTJGdmFsdWUlM0UlM0MlMkZibG9jayUzRSUzQyUyRnZhbHVlJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZzdGF0ZW1lbnQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnhtbCUzRQ==",
    "debug": false,
    "verbose": false,
    "enabled": true
  },
  "type": "script",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1590381207647,
  "_id": "script.js.Logik.Pond.Berechnungen",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

**Comment by Apollon77** [comment]
Wenn über Cloud ---> https://github.com/ioBroker/ioBroker.javascript/issues/580 dann duplicate
