### ISSUE TITLE
Neues Script Datenpunkt wird geleert mit 4.6.16

### ISSUE THREAD

**Issue by mark77-DE** [ioBroker/ioBroker.javascript#585]
Moin,

ich habe mit dem Adapter 4.6.16 (mit Version 4.6.15 auch) ein neues Script erstellt (zur Fehlersuche, vereinfacht, nur so):

`var state = '0_userdata.0.Status.Updates';
createState(state, {def: "", type: "string", name: "available Updates"});
console.log("html");
setState(state, "html");`

Wird dieses ausgeführt bleibt der angelegte Datenpunkt leer, die Log Ausgabe funktioniert.

Wechsele ich das Script auf einen "Slave", mit der Version 4.5.1, steht der gewünschte Wert im DP,
wieder zurück gwechselt, auf dem master, wird der Wert wieder gelöscht.

Master/Slave:
node 10.20.1
npm 6.14.4
controller: 3.1.4

**Comment by Apollon77** [comment]
Ich tippe auf asynchronität! In der 4.6.0 sind einige Fixes drin die jetzt sicherstellen das "default" Werte beim anlegen auch wirklich angelegt werden. 
Ich tippe das dein "setState(html) ausgeführt wird und ggf vom default wert überschrieben wird.

Richtiger code wäre in dem Fall zu warten bis das create State durch ist!

```
var state = '0_userdata.0.Status.Updates'; 
createState(state, {def: "", type: "string", name: "available Updates"}, () => {
    console.log("html"); 
    setState(state, "html");
}); 
```

... oder das def: "" aus dem createState rausnehmen - aber auch dann könnte dies passieren!

Bitte mal verifizieren

**Comment by mark77-DE** [comment]
Moin,

ja, hast recht. Ein entfernen des def: reicht schon aus. 

Danke für die Aufklärung!

Gibt es eine Art "if state exists" oder ein besseres Vorgehen, wenn mehrere States beim Start erstellt werden sollen?

**Comment by Apollon77** [comment]
Ja gibt es https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#existsState

**Comment by mark77-DE** [comment]
Danke!

Übrigens das entfernern von def: reicht doch nicht aus (ich hatte noch nicht auf den Master gewechselt), es funktioniert nur die von dir beschrieben Variante!!!

**Comment by Apollon77** [comment]
Hm ... das ist komisch. Das sollte macximal einmlig passieren können wenn es das state/Objekt noch gar nicht gibt. Sobald es schon da ist sollte das nicht passieren!
