### ISSUE TITLE
CANVAS node-pre-gyp Fehler

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.javascript#586]
Hallo,

seit Update auf js-Controller 3.1.4 erhalte ich bei jedem Start der Javascript Instanz folgende Fehlermeldung:
`

javascript.0 | 2020-05-25 10:03:29.944 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
-- | -- | -- | --
javascript.0 | 2020-05-25 10:03:29.918 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:03:29.854 | error | (739) In file included from ../../nan/nan.h:56, from ../src/backend/Backend.h:6, from ../src/Backends.h:3, from ../src/init.cc:17: ../src/init.cc: At
javascript.0 | 2020-05-25 10:03:29.592 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/Backends.h:3, from ../src/init.cc:17: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan
javascript.0 | 2020-05-25 10:03:27.060 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:27.036 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/ImageData.h:5, from .
javascript.0 | 2020-05-25 10:03:26.913 | error | (739) In file included from ../src/ImageData.h:5, from ../src/ImageData.cc:3: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’: ../../nan/nan.h:2294:62: wa
javascript.0 | 2020-05-25 10:03:23.159 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:23.135 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/Image.h:8, from ../sr
javascript.0 | 2020-05-25 10:03:22.678 | error | (739) In file included from ../src/Image.h:8, from ../src/Image.cc:3: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’: ../../nan/nan.h:2294:62: warning: c
javascript.0 | 2020-05-25 10:03:18.237 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:18.212 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:03:17.949 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/Canvas.h:5, from ../src/closure.h:5, from ../src/closure.cc:1: ../../nan/nan.h: I
javascript.0 | 2020-05-25 10:03:10.418 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:10.392 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:03:09.536 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/Canvas.h:5, from ../src/CanvasRenderingContext2d.h:6, from ../src/CanvasRendering
javascript.0 | 2020-05-25 10:03:07.255 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:07.223 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/CanvasPattern.h:6, fr
javascript.0 | 2020-05-25 10:03:06.760 | error | (739) In file included from ../src/CanvasPattern.h:6, from ../src/CanvasPattern.cc:3: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’: ../../nan/nan.h:229
javascript.0 | 2020-05-25 10:03:04.344 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:03:04.320 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/CanvasGradient.h:5, f
javascript.0 | 2020-05-25 10:03:04.078 | error | (739) In file included from ../src/CanvasGradient.h:5, from ../src/CanvasGradient.cc:3: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’: ../../nan/nan.h:2
javascript.0 | 2020-05-25 10:02:58.141 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:58.117 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:57.988 | error | (739) ../src/Canvas.cc:520:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcas
javascript.0 | 2020-05-25 10:02:57.983 | error | (739) ../src/Canvas.cc:479:79: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcas
javascript.0 | 2020-05-25 10:02:57.977 | error | (739) ../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’: ../src/Canvas.cc:415:26: warning: comparison of integer expressions
javascript.0 | 2020-05-25 10:02:57.282 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/Canvas.h:5, from ../src/Canvas.cc:3: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan:
javascript.0 | 2020-05-25 10:02:55.535 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:55.511 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:55.252 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/Backends.h:3, from ../src/Backends.cc:1: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(
javascript.0 | 2020-05-25 10:02:51.746 | error | (739) ../src/bmp/BMPParser.cc:204:27: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare] E(ptr - data + imgdSize > len, "
javascript.0 | 2020-05-25 10:02:51.744 | error | (739) ../src/bmp/BMPParser.cc: In member function ‘void BMPParser::Parser::parse(uint8_t*, int, uint8_t*)’: ../src/bmp/BMPParser.cc:189:16: warning: comparison of integer expressions of different sign
javascript.0 | 2020-05-25 10:02:50.708 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:50.685 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:50.424 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/backend/SvgBackend.h:3, from ../src/backend/SvgBackend.cc:1: ../../nan/nan.h: In function ‘void Na
javascript.0 | 2020-05-25 10:02:48.368 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:48.343 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:48.077 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/backend/PdfBackend.h:3, from ../src/backend/PdfBackend.cc:1: ../../nan/nan.h: In function ‘void Na
javascript.0 | 2020-05-25 10:02:45.900 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:45.875 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:45.758 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/backend/ImageBackend.h:3, from ../src/backend/ImageBackend.cc:1: ../../nan/nan.h: In function ‘voi
javascript.0 | 2020-05-25 10:02:43.796 | error | (739) /home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P =
javascript.0 | 2020-05-25 10:02:43.767 | error | (739) In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63, from ../../nan/nan.h:56, from ../src/backend/Backend.h:6,
javascript.0 | 2020-05-25 10:02:43.638 | error | (739) In file included from ../src/backend/Backend.h:6, from ../src/backend/Backend.cc:1: ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’: ../../nan/nan.h
javascript.0 | 2020-05-25 10:02:39.320 | error | (739) WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v64-linux-glibc-arm.tar.gz node-pre-gyp WARN Pre-built binaries not fo
javascript.0 | 2020-05-25 10:02:39.319 | error | (739) node-pre-gyp
javascript.0 | 2020-05-25 10:02:39.063 | error | (739)
javascript.0 | 2020-05-25 10:02:39.062 | error | (739) WARN Using request for node-pre-gyp https download
javascript.0 | 2020-05-25 10:02:39.060 | error | (739) node-pre-gyp

`
Folgende Befehle habe ich im Ordner /opt/iobroker ausgeführt, leider bleiben die Fehler:
1. npm rebuild canvas 
2. sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
3. sudo npm install canvas --unsafe-perm=true

Danke vorab für Unterstützung!

**Comment by Apollon77** [comment]
Nope, canvas does not come from javascript adapter, so most likely comes from iot adapter
