### ISSUE TITLE
BLOCKLY - nach Installation 4.6.17 keinen zuasmmenfügen von "oder" und Zahlen

### ISSUE THREAD

**Issue by Plasmachef** [ioBroker/ioBroker.javascript#587]
Hallo,
nach der Installation der Version 4.6.17 lässt sich an das Logik-Element "und/oder" keine Zahl und auch kein Text-Element mehr anknüpfen.
Das Logik-Element "=" lässt sich einfügen.

**Comment by Plasmachef** [comment]
Erweiterung:
wenn ein "und/oder"-Element in ein "="-Element eingefügt wurde, dann nimmt die andere Seite des "="-Elements auch keine Zahlen mehr an.

**Comment by Apollon77** [comment]
Hast Du ein Beispiel?

**Comment by Plasmachef** [comment]
- nimm ein leeres Blockly 
- zieh ein "und/oder"-Element rein
- zieh jetzt ein Zahl-Mathe-Element auch in das Blockly
- versuche jetzt die Zahl in das "und/oder" entweder vorne oder hinten einzufügen

--> geht nicht ... das Maul leuchtet nicht und es wird nicht aufgenommen

**Comment by ihavenonick** [comment]
Du kannst da nur true und fals rein packen, oder eben die Objekt die die Zustände haben. Das ist ne Logik und 2 UND 3, so wie DU es willst ist ne Addition und keine Logik ;-)

**Comment by paul53** [comment]
Das trifft auch auf den falls-Block zu. Erlaubt Blockly keine implizite Typwandlung mehr, wenn der Typ festgestellt werden kann ?

**Comment by Plasmachef** [comment]
> Du kannst da nur true und fals rein packen, oder eben die Objekt die diese Zustände haben. Das ist ne Logik und 2 UND 3, so wie Du es willst ist ne Addition und keine Logik ;-)

da könnte was dran sein!
Danke für die Erklärung ... du hast da schon recht :-)
