### ISSUE TITLE
BLOCKLY Switch warnt bei Verwendung von "Wert" aus Trigger

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.javascript#589]
Wenn an den neuen Switch Block der Wert Block mit dem Wert vom Trigger angehängt wird erscheint ein JS alert mit einem Text `logic_switch_case: (obj.state ? obj.state.val : "") is not a variable name`

**Comment by paul53** [comment]
Es erscheint nicht nur die Warnung, sondern der Block wird nicht übersetzt (kein Javascript-Code).

**Comment by Xyolyp** [comment]
Das Problem besteht weiterhin
