### ISSUE TITLE
blockly wird mehrfach ausgeführt

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#592]
Hallo .. mich wundert, dass das Blockly mehrfach ausgeführt wird .. obwohl sich am Sonoff-Status nichts ändert plappert die Alexa alle x-minuten .. die Pumpe ist aus. Ist das ok so? 

![blockly](https://user-images.githubusercontent.com/4311558/83447487-d2d90b80-a450-11ea-8901-cce515f9e24b.png)

**Comment by daniel-lo** [comment]
Ich hab das auch am Objekt überprüft .. dort gibt es keine Aktualisierung .. trotzdem die Sprachausgabe. Irgendwas verstehe ich da falsch .. mit wahr ist es dasselbe.

Ich könnte schwören, dass es vor Kurzem noch anders war .. hmmm.

**Comment by Apollon77** [comment]
logge doch mal mit wann es getriggert wird

**Comment by daniel-lo** [comment]
bin nicht sicher wie das geht .. ich kann so ein debug schnippsel einfügen .. aber das schreibt doch nur ins log was ich sehen möchte. Oder wäre das debug auf den adapter .. und dann  warten bis die Meldung kommt?

**Comment by Apollon77** [comment]
Es gibt einen Debug Log Block, den einbauen, dann Logfile anschauen

**Comment by daniel-lo** [comment]
Anbei das Logfile .. nach meinem Verständnis hätte aus dem Timer genau eine Aktion folgen müssen:


07:47:43.692 | info | javascript.0 (1715) script.js.common.Bewässerung: setTimeout(ms=10000)
-- | -- | --
07:47:43.738 | info | javascript.0 (1715) script.js.common.Bewässerung: setTimeout(ms=10000)
07:47:43.790 | info | javascript.0 (1715) script.js.common.Bewässerung: setTimeout(ms=10000)
07:47:53.692 | info | javascript.0  (1715) script.js.common.Bewässerung:  getState(id=hm-rpc.0.KEQ0221439.2.POWER, timerId=undefined) =>  {"val":417.83,"ack":true,"ts":1591249671913,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1591249671913}
07:47:53.692 | info | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus")
07:47:53.693 | warn | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus") - wurde nicht ausgeführt, während der  Debug-Modus aktiv ist
07:47:53.739 | info | javascript.0  (1715) script.js.common.Bewässerung:  getState(id=hm-rpc.0.KEQ0221439.2.POWER, timerId=undefined) =>  {"val":417.83,"ack":true,"ts":1591249671913,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1591249671913}
07:47:53.739 | info | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus")
07:47:53.740 | warn | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus") - wurde nicht ausgeführt, während der  Debug-Modus aktiv ist
07:47:53.790 | info | javascript.0  (1715) script.js.common.Bewässerung:  getState(id=hm-rpc.0.KEQ0221439.2.POWER, timerId=undefined) =>  {"val":417.83,"ack":true,"ts":1591249671913,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1591249671913}
07:47:53.791 | info | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus")
07:47:53.791 | warn | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist nicht aus") - wurde nicht ausgeführt, während der  Debug-Modus aktiv ist
07:48:17.238 | info | javascript.0 (1715) script.js.common.Bewässerung: setTimeout(ms=10000)
07:48:27.239 | info | javascript.0  (1715) script.js.common.Bewässerung:  getState(id=hm-rpc.0.KEQ0221439.2.POWER, timerId=undefined) =>  {"val":1.32,"ack":true,"ts":1591249674914,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1591249674914}
07:48:27.239 | info | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist aus")
07:48:27.239 | warn | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist aus") - wurde nicht ausgeführt, während der  Debug-Modus aktiv ist
07:53:17.278 | info | javascript.0 (1715) script.js.common.Bewässerung: setTimeout(ms=10000)
07:53:27.279 | info | javascript.0  (1715) script.js.common.Bewässerung:  getState(id=hm-rpc.0.KEQ0221439.2.POWER, timerId=undefined) =>  {"val":1.34,"ack":true,"ts":1591249896146,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":1591249896146}
07:53:27.279 | info | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist aus")
07:53:27.279 | warn | javascript.0  (1715) script.js.common.Bewässerung:  setForeignState(id=alexa2.0.Echo-Devices.G091470400150342.Commands.speak,  state="Pumpe ist aus") - wurde nicht ausgeführt, während der  Debug-Modus aktiv ist

**Comment by daniel-lo** [comment]
Könnte ich hierzu ein Feeback bekommen? Sitzt der Fehler vor der Tastatur oder im JS Adapter? VG

**Comment by Apollon77** [comment]
Javascript instanz auch mal neu gestartet? bzw stoppe mal das skript und schaue ob es dann immer noch läft ...

**Comment by daniel-lo** [comment]
hab inzwischen den iobroker mehrfach neu gestartet und gefixed .. aber ändert nichts. Mit dem letzten Hosts update hat sich offenbar was verändert .. jetzt schwatzt ein anderer Skriptblock unaufhörlich .. und ohne nachvollziehbaren grund.

**Comment by GermanBluefox** [comment]
Ich sehe keine Logs, die zu sonoff gehören. "Ack egal" ist aber schlechte Option
