### ISSUE TITLE
Blockly "spinnt"

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.javascript#595]
Moin moin,

seit einiger Zeit ärgert mich Blockly wie folgt. Das Phänomen habe ich auch bereits auf anderen Systemen live gesehen. Auch bei Facebook waren ein paar Benutzer davon betroffen.

https://m.facebook.com/groups/440499112958264?view=permalink&id=1198375907170577&comment_id=1198739313800903&notif_t=group_comment&notif_id=1591694506902479&ref=m_notif

Leider kann man im Log keine Meldungen dazu erkennen. Das System läuft als Docker auf einer DS918+ mit 16GB RAM. 

Wie das aussieht im folgenden Video.

https://youtu.be/8xzSyNybIWo
https://youtu.be/YTQ7s-uODog

**Comment by capitaenz** [comment]
Ist bekannt:
[https://github.com/ioBroker/ioBroker.javascript/issues/487](https://github.com/ioBroker/ioBroker.javascript/issues/487)
Ich bin auch betroffen.

**Comment by GermanBluefox** [comment]
Duplicate
