### ISSUE TITLE
createState() in "0_userdata.0" overwrites existing state

### ISSUE THREAD

**Issue by BoehserWolf** [ioBroker/ioBroker.javascript#597]
A user created state in "0_userdata.0" with createState() gets overwritten on next script restart although state already exists. The forceCreate parameter may implicitely be set or exclicitely be set to false - no change in behaviour.

This is confirmed with JS-controller 2.2.9 and 4.6.17 (see [forum thread)](https://forum.iobroker.net/topic/34136/m%C3%B6glicher-bug-im-javascript-adapter-bei-createstate/4).

Test script to confirm:
`createState(
    '0_userdata.0.test.state1', 
    {name: 'test state1'}, 
    function() { log('created'); });

createState(
    '0_userdata.0.test.state2', 
    0,
    false,  // force
    {name: 'test state2'}, 
    function() { log('created (force:false)'); });
`

Run script once to create the states. Run script next time(s) to confirm states being overwritten.

**Comment by paul53** [comment]
sandbox.js, Zeile 1842: Kann man Datenpunkte unter "0_userdata.0" mit _adapter.getObject()_ prüfen ?

**Comment by paul53** [comment]
Ich würde Zeilen 1842 bis 1916 ersetzen durch (bitte prüfen):
`            let id = adapter.namespace + '.' + name;
            if (name.match(/^javascript\.\d+\./) || name.startsWith('0_userdata.0.')) {
                id = name;
            }

            adapter.getForeignObject(id, function (err, obj) {
                if (err || !obj || forceCreation) {
                    // todo: store object in objects to have this object directly after callback
                    // create new one
                    adapter.setForeignObject(id, {
                        common: common,
                        native: native,
                        type:   'state'
                    }, function (err) {
                        err && adapter.log.warn('Cannot set object "' + id + '": ' + err);

                        if (initValue !== undefined) {
                            if (isObject(initValue) && initValue.ack !== undefined) {
                                adapter.setForeignState(id, initValue, callback);
                            } else {
                                adapter.setForeignState(id, initValue, true, callback);
                            }
                        } else if (!forceCreation) {
                            adapter.setForeignState(id, null, true, callback);
                        } else {
                            if (typeof callback === 'function') {
                                try {
                                    callback.call(sandbox, id);
                                } catch (e) {
                                    errorInCallback(e); //adapter.log.error('Error in callback: ' + e)
                                }
                            }
                        }
                    });
                } else {
                    if (!adapter.config.subscribe && !states[id]) {
                        states[id] = {val: null, ack: true};
                    }
                    // state yet exists
                    if (typeof callback === 'function') {
                        try {
                            callback.call(sandbox, id);
                        } catch (e) {
                            errorInCallback(e); //adapter.log.error('Error in callback: ' + e)
                        }
                    }
                }
            });
`

**Comment by Apollon77** [comment]
Hm ... ja sowas in der Art ... muss nochmal genau drüber nachdenken.

**Comment by Apollon77** [comment]
Bitte in Javascript 4.6.19 versuchen

**Comment by paul53** [comment]
Ist in Javascript 4.6.19 nicht behoben.

**Comment by Apollon77** [comment]
Ok, JETZT hab ichs verstanden :-) 4.6.20 incoming

**Comment by paul53** [comment]
Funktioniert in Version 4.6.20

**Comment by Apollon77** [comment]
Thx
