### ISSUE TITLE
export button geht nicht

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#60]
man kann keine Scripte mehr exportieren über den Export Button

**Comment by GermanBluefox** [comment]
Bei mir geht es... Man muss nur ein bisschen warten.

**Comment by Rantanplan01** [comment]
Mit Firefox funktioniert es.
Mit Chrome geht es nicht. Keine Fehlermeldung in der Console.
Meldung von Chrome "Download Fehler-Netzwerkfehler"

**Comment by Matten-Matten** [comment]
Dem kann ich mich nur anschließen, habe das selbe Problem, genauso wie das speichern von blockly skripten funktioniert nur sehr selten mit GOOGLE Chrome. das auch erst seit dem ich geupgradet hab, ein downgrade brachte leider kein erfolg.

**Comment by GermanBluefox** [comment]
Chrome kann keine große Dateien behandeln. Das ist Eigenschaft von Chrome.

**Comment by Rantanplan01** [comment]
Ca. 300 kb sind wohl keine großen Dateien.
Und als die Funktion in Admin v3 eingeführt wurde hat es ja einige Versionen lang funktioniert.

**Comment by naesle** [comment]
Export geht bei mir wunderbar auch mit Chrome aber Import geht nicht mehr

**Comment by Ilovegym66** [comment]
auch mit Firefox kein Import unter 4.05 möglich

**Comment by GermanBluefox** [comment]
Bitte noch mal Probieren

**Comment by Rantanplan01** [comment]
v4.1.0
Firefox:
Export funktioniert.
Import funktioniert nicht. (gelöschtes Script wurde nicht wieder hergestellt.)

Chrome:
Export funktioniert nicht. (Fehlermeldung Chome: "Fehler - Netzwerkfehler"
Import funktioniert nicht, (gelöschtes Script wurde nicht wieder hergestellt)

Import jeweils probiert über Drag&Drop und Dateidialog.

**Comment by GermanBluefox** [comment]
Test mit 4.1.5 ?

**Comment by Rantanplan01** [comment]
mit 4.1.5 erledigt. Getestet mit Firefox.

in Chrome habe ich immer noch den Fehler. Da scheine ich aber der Einzige zu sein.
Kann, von mir aus, geschlossen werden.

**Comment by FRYYYYYY** [comment]
Ich hab das Problem im Chrome auch. Aber ich kann nicht sagen seit wann. Würde behaupten so ca. einen Monat.

Chrome: 76.0.3809.100
js-controller: 1.5.14
javascript: 4.1.14

Ein Download der Scripte funktioniert nicht und bricht mit "Netzwerkfehler" ab.

**Comment by sigi2345** [comment]
Nimm Firefox.........

Am Mo., 19. Aug. 2019 um 22:04 Uhr schrieb FRYYYYYY <
notifications@github.com>:

**Comment by FRYYYYYY** [comment]
Es ist aber ein Fehler in Verbindung mit Chrome. Den FF zu nehmen ist nur ein Workaround.

**Comment by sigi2345** [comment]
> Es ist aber ein Fehler in Verbindung mit Chrome. Den FF zu nehmen ist nur ein Workaround.

Ja das stimmt, mir ist auch aufgefallen, dass der Export von Projekten unter Chrome nicht geht.
Noch was,  hat irgendwas mit der Größe des Projekts oder der Skripte zu tun.
Mehrfach getestet, macht man ein neues Projekt oder man hat nur wenige Skripte dann geht es auch mit Chrome......... 
Mit FF hatte ich in dieser Hinsicht noch nie Probleme.
