### ISSUE TITLE
Scripts getting yellow.

### ISSUE THREAD

**Issue by MeisterQ** [ioBroker/ioBroker.javascript#601]
Hello,

my scripts always getting "yellow" after a while.

If i stop them, and turn them on back, they are green. But after a while they get yellow again. 

The log does not show anything and scripts still working.

**Comment by Apollon77** [comment]
"my scripts" ? Do you mean the javascript adapter? Please provide logs

**Comment by MeisterQ** [comment]
Yes. Javascript Adapter.

Logs show nothing on debug. 

I watched the whole day, stopped and started, and when the scripts turned yellow, nothing happend.

**Comment by Apollon77** [comment]
Are scripts enabled on this javascriptz instance? It is yellow when NO script is actively running. Could it be this?

**Comment by MeisterQ** [comment]
![javascript](https://user-images.githubusercontent.com/39710886/84696635-1a7d8e00-af4d-11ea-9539-a7e7db6a0176.JPG)

**Comment by Apollon77** [comment]
Ok, please set the javascript instance to debug mode and let it run until it shows "yellow" ... then send the log

**Comment by MeisterQ** [comment]
I stopped and started a script, so it was green. Then i deleted all the log from today, changed log to debug before and watched.

Even after it turned yellow, nothing was written inside the debug log

**Comment by GermanBluefox** [comment]
> I stopped and started a script, so it was green. Then i deleted all the log from today, changed log to debug before and watched.
> 
> Even after it turned yellow, nothing was written inside the debug log

"Yellow" that some error was reported in the log by this script
