### ISSUE TITLE
deleteState per Script unter javascript.0 funktioniert nicht

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.javascript#604]
löschen von States per Script unter javascript.0 funktioniert nicht. (Not found)

Unter 0_userdata.0 funktioniert das löschen per Script.
Siehe https://forum.iobroker.net/post/447909

**Comment by paul53** [comment]
Ich würde in sandbox.js, Zeile 1925 ändern in
`            if ((id.startsWith('0_userdata.0.') || id.startsWith(adapter.namespace)) && objects[id]) {
`

**Comment by Apollon77** [comment]
@paul53 makes sense!

**Comment by Apollon77** [comment]
Bitte in Javascript 4.6.19 versuchen

**Comment by dslraser** [comment]
Funktioniert bei mir mit 4.6.19 
Danke

**Comment by alexhk** [comment]
Ich bekomme es mit 4.6.23 immer noch nicht hin.

javascript.0.GosundMON.Gosund-2.RESET wurde von javascript.**0** erstellt.

Versuche ich von javascript.**1** mit deleteState(id) oder auch deleteState(id.substring(13)) zu löschen, bekomme ich folgendes:

```
(9039) Cannot delete state "javascript.0.GosundMON.Gosund-2.RESET": Not found
(9039) Cannot delete state "GosundMON.Gosund-2.RESET": Not found
```

Die anderen von javascript.1 erstellten States (.POWER, etc) kann ich ohne Probleme löschen. Das .RESET Flag wird eben von einem anderen Script auf einer anderen Instanz gesetzt.

Ich kann natürlich mein Script in javascript.0 laufen lassen, aber ich wollte den Rat in den Docs befolgen und auf einer separaten Instanz entwickeln bis alles stabil läuft.

Oder geht das Löschen von "fremden" States grundsätzlich nicht und ich habe das falsch verstanden?

**Comment by paul53** [comment]
Laut [Doku](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#deletestate): 
Delete state and object in javascript space, e.g. "javascript.0.mystate". States from other adapters cannot be deleted.

Lösche mit _deleteObject(id)_. Es muss die vollständige ID verwendet werden.
