### ISSUE TITLE
Javascript Adapter - Instanz ist deaktiviert

### ISSUE THREAD

**Issue by Sansibari** [ioBroker/ioBroker.javascript#606]
Nach Update auf aktuelle Versionen lassen sich keine Scripts mehr starten. Die javascript.0 geht auf rot.
Keine aktivierten Scripts laufen mehr.

Fehlermeldung im Log:

host.rasp04 | 2020-06-22 15:25:47.835 | info | Restart adapter system.adapter.javascript.0 because enabled
host.rasp04 | 2020-06-22 15:25:47.834 | info | instance system.adapter.javascript.0 terminated with code NaN ()
host.rasp04 | 2020-06-22 15:25:47.834 | warn | instance system.adapter.javascript.0 terminated due to SIGABRT
host.rasp04 | 2020-06-22 15:25:47.833 | error | Caught by controller[0]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

nach dem automatischen Restart geht der Adapter gleich wieder auf rot.

**Comment by Apollon77** [comment]
An der Stelle ist das ein Out of Memory ... Am besten per Admin alle Skripte deaktvieren, eins nach dem anderen starten bis Du das gefunden hast was die Ursache ist. ggf mal mit zwei Javascript Instanzen versuchen

**Comment by wschiro** [comment]
Ich habe die gleiche Meldung. Nach paar sec startet der Adapter in im Protokoll ist zu sehen, dass ein script im Hintergrund läuft, auf das ich keinen Zugriff kriege. Hab iob gefixt, diag , nichts hilft. Wenn ich eine 2. Instanz installiere, is alles gleich 2x da. Nach Neuinstallation des adapters sind alle scripte sofort wieder da, krieg ich nicht weg
