### ISSUE TITLE
Blockly Fehler beim verschieben von Funktionsvariable

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.javascript#608]
Entstanden aus:
https://forum.iobroker.net/topic/31020/javascript-blockly-wird-oft-nicht-gespeichert/100

#zip#

@apollon77 ich konnte das Problem nun bei mir mehrfach wie folge reproduzieren. Hab davon mal ein Video gemacht und das Log aus der Console angehängt. Vielleicht hilft es.

Video

Log

#zip#

helpers.ts:110 Uncaught TypeError: Cannot read property 'dragBlock' of null
at Blockly.TouchGesture.Blockly.Gesture.handleMove (blockly_compressed.js:433)
at Blockly.TouchGesture.handleMove (blockly_compressed.js:730)
at HTMLDocument.h (blockly_compressed.js:866)
at HTMLDocument.r (helpers.ts:85)

**Comment by GermanBluefox** [comment]
That must be fixed with latest javascript version. Please test and reopen if still reproducable.
