### ISSUE TITLE
Trigger is not executed when state expires

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#609]
https://forum.iobroker.net/topic/34677/triggern-dp-ohne-wert-nicht-m%C3%B6glich-true-leer-stiebel-isg/54

The adapter in question uses the expire feature when calling setState
https://github.com/unltdnetworx/ioBroker.stiebel-isg/blob/master/main.js#L159-L162
but the trigger in the script is not being executed when the state expires.

**Comment by Apollon77** [comment]
Strange, code wise it should
* main.js L443+ detect that set state as empty object and create an "change event object"
* then this is checked and callbacks called

needs further testing

**Comment by andiling** [comment]
Hab das selbe Problem! Es wird beim Expire das ja den state ändert kein event ausgelöst. Somit bekommt man den statechange auf expired überhaupt nicht mit.

**Comment by GermanBluefox** [comment]
> Hab das selbe Problem! Es wird beim Expire das ja den state ändert kein event ausgelöst. Somit bekommt man den statechange auf expired überhaupt nicht mit.

Redis or file?

**Comment by andiling** [comment]
Redis!

**Comment by GermanBluefox** [comment]
Bad news: 
![image](https://user-images.githubusercontent.com/4582016/131832571-6ac32d6a-8833-406a-ad95-cbee614d2283.png)

**Comment by Apollon77** [comment]
@GermanBluefox but this should not be anissue or be an issue of some ms to seconds ... the controller is listening for them and we verified that this is working in genral and then state is set publised with null value

**Comment by Apollon77** [comment]
I finally got it!!!!!!

All subscriptions on state changes default to "q: 0" ... means "best quality state  change from the device". A deleted state do not have any quality and so it is not triggered.

If you set "q: '*'" in your subscription pattern object then you will also get state deletions. it basically works with change: any and ne (default)

```
on({id: 'javascript.0.X.Y', q: '*'}, data => {
    console.log('data change: ' + JSON.stringify(data));
})
```

I will update documentation

**Comment by AlCalzone** [comment]
> All subscriptions on state changes default to "q: 0"

Waiiiiit, what?! Is that part of the thing where `on("id", ...)` and `on({id: "id"}, ...)` behave differently (change ne vs change any)?

**Comment by Apollon77** [comment]
Yes code is defaulting to this since ages ... was only not documented :-) 

https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/sandbox.js#L1132-L1134

I have now documented it also in the docs ...

And for change:
* change: any -> value NOT checked at all, means any value triggers it
* change: ne -> oldval !== newVal

And my info above for "a state gets deleted" in fact eany and ne behave the same.
