### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#61]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by robdg80** [comment]
In the Module Input Field changes currently not saved
![image](https://user-images.githubusercontent.com/12692680/35486988-7076dade-0476-11e8-8a58-3042e7885ab5.png)
After save & close and reopen
![image](https://user-images.githubusercontent.com/12692680/35486992-7e5a660c-0476-11e8-8291-c52f6a4eb505.png)

**Comment by GermanBluefox** [comment]
You must press ENTER after you enter something.

2018-01-28 21:59 GMT+01:00 Robert <notifications@github.com>:

**Comment by robdg80** [comment]
I already have written:
You need to press "Enter" after input a module. - I have taken a while to find this out :(

Please can you also take changes when the input field looses the focus?
