### ISSUE TITLE
blockly - blocks not on the same workspace

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.javascript#613]
hatte einen xhr-poll fehler und habe in chrome in den entwicklertools folgende fehler gefunden - @Apollon77  hat um neues issue gebeten

interessant war (vielleicht) das browser fenster war nur offen - habe nicht darun gearbeitet

![1594586293326-x-fehler2](https://user-images.githubusercontent.com/18462890/87284481-b4a60700-c4f6-11ea-8da6-5fe92d9565a5.png)

**Comment by Apollon77** [comment]
So, wir haben mal ein bissl an den socket.io ping/pong timeouts rumgespielt ... Dazu checkt bitte mal Admin 4.1.6 ... Also: Admin installieren, Javascript am besten so lassen wie es probleme machte. Dann Auf jeden Fall mal im browser reloaden (hart) ode rbrwoser zu und auf und so ... ... Besser?

Die 4.1.6 NICHT auf GitHub installieren, das geht nicht so simpel ... also kurz warten bis es im Latest Repo auftaucht bitte! Repo Update ist angestossen ... kann aber 1-2h dauern

**Comment by GermanBluefox** [comment]
Closed, because no action
