### ISSUE TITLE
[Feature request] Javascript via Visual Studio Code bearbeiten

### ISSUE THREAD

**Issue by DerT94** [ioBroker/ioBroker.javascript#616]
Leider kann ich den Aufwand dahinter nicht abschätzen wollte es aber trotzdem mal anbringen.
Der Browser JavaScript Editor ist zwar schön hat aber seine Problemchen.
z.B.: Es wird in allen Tabs gleichzeitig gescrollt

Gibt es eine Möglichkeit Visual Studio Code anzubinden? Aktuell kopiere ich meine Skripte zwischen ioBroker und VSCode hin und her.

**Comment by Apollon77** [comment]
Also was geht ist über das "Mirroring" Feature alle Javascripts alle Files im Filesystem zu haben. Ich nutze dann sftp/ssh Sync plugins in meiner IDE um es zu syncen

**Comment by DerT94** [comment]
Okay.
Das Feature kenne ich noch nicht.
Nach was muss ich suchen um Infos dazu zu finden?
Wenn ich nach "visual studio code Mirroring" google finde ich leider nichts.

**Comment by Apollon77** [comment]
Nein, der javascript Adapter hat eine Funktion namens "Mirroring". In den Adapter Einstellungen kannst Du ein Mirror-Verzeichnis angeben

**Comment by DerT94** [comment]
Danke nochmal.
Hab das ganze mal eingerichtet stoße aber auf einen Fehler.
Der javascript Adapter legt die Skripte mit den Folgenden Berechtigungen ab.
-rwxr-xr-x  1 iobroker iobroker    0 Jul 28 11:43 permtest.js*

Was bedeutet, nur der Benutzer iobroker hat Zugriff darauf.
Ich kann die Berechtigung zwar anpassen, müsste das aber bei jedem neuen Skript machen.
Wie hast du das gelöst?

**Comment by AlCalzone** [comment]
> Ich kann die Berechtigung zwar anpassen, müsste das aber bei jedem neuen Skript machen.
> Wie hast du das gelöst?

Du könntest den User, der Zugriff braucht in die iobroker-Gruppe hinzufügen.

**Comment by DerT94** [comment]
Leider funktioniert das nicht da die Gruppe auf die Dateien auch nur lesend Zugreifen darf.

Bei mir werden die Rechte "-rwxr-xr-x 1" gesetzt.
-rwxr-xr-x 1 iobroker iobroker 0 Jul 28 11:43 permtest.js*

rwx --> iobroker Benutzer darf lesen und schreiben.
r-x  --> iobroker Gruppe darf nur lesen
r-x  --> andere dürfen nur lesen.

**Comment by AlCalzone** [comment]
Laut Code sollten die Permissions auf dem Ordner und Dateien 777 sein. Liegt der sync-Ordner ggf. innerhalb /opt/iobroker? Dann würden ggf. die Permissions geerbt.
Wenn ja, würde ich ihn zum Testen mal aus /opt/iobroker rausschieben und die permissions auf 777 setzen.

**Comment by GermanBluefox** [comment]
Gibt es hier was neues?
