### ISSUE TITLE
Objekt ID keine Objekte mehr

### ISSUE THREAD

**Issue by marne1** [ioBroker/ioBroker.javascript#619]
Script Engine 4.6.22 
Bei Blockly werden keine Objekte bei der Objekt ID mehr angezeigt.

Neustart und Script Engine entfernen/neu installieren hat auch nicht geholfen.

![Screenshot_2020-08-08 javascript - ioBroker](https://user-images.githubusercontent.com/15924401/89713254-cc0dce00-d996-11ea-8ed7-f46817c31a9b.png)

**Comment by Apollon77** [comment]
Es sind Filter gesetzt laut Screenshot ... Die entfernen hilft nicht?

**Comment by marne1** [comment]
Wie kann man den Filter entfernen? Habe nichts gemacht.

**Comment by marne1** [comment]
> Es sind Filter gesetzt laut Screenshot ... Die entfernen hilft nicht?

Wie kann man den Filter entfernen? Habe nichts gemacht

**Comment by marne1** [comment]
Danke, habe es gefunden. Werden den Beitrag löschen
