### ISSUE TITLE
log level 'debug' disappears? (4.6.17)

### ISSUE THREAD

**Issue by alexhk** [ioBroker/ioBroker.javascript#624]
Am I misunderstanding something or is the 'debug' log level being sent to nirvana?

    log('1 debug','debug');
    log('2 info','info');
    log('3 warn','warn');
    log('4 error','error');

Output:

    [..] info	javascript.0 (5279) Start javascript script.js.Sandbox
    [..] info	javascript.0 (5279) script.js.Sandbox: 2 info
    [..] warn	javascript.0 (5279) script.js.Sandbox: 3 warn
    [..] error	javascript.0 (5279) script.js.Sandbox: 4 error
    [..] info	javascript.0 (5279) script.js.Sandbox: registered 0 subscriptions and 0 schedules
    [..] info	javascript.0 (5279) Stop script script.js.Sandbox

**Comment by alexhk** [comment]
Forgot to mention, it doesn't make a difference if I enable debug in the debug options within the editor (top right over code input window).

**Comment by foxriver76** [comment]
The whole js instance needs to run on debug or silly level else it’s not visible. So as designed

**Comment by alexhk** [comment]
@foxriver76 thanks! that makes absolute sense.

if you believe it or not, out of nowhere, not even at my computer, I realized this just yesterday night myself - I just didn't get to try it yet.

Closing issue.
