### ISSUE TITLE
getObject(<id>, "true") returns no enumerations

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#625]
according to the description it is possible to get all enumarations for an id like 
`getObject(<id>, "true")`

I get the rooms with enumName = "rooms" and I get " the functions with enumName = "functions", but no enumerations with enumName = "true".

**Versions:**  
 - Adapter version: 4.6.23
 - JS-Controller version: 3.1.6
 - Node version: 10.18.0
 - Operating system: Debian GNU/Linux 8 (jessie), 3.10.104+ #1 SMP PREEMPT armv7l

**Comment by paul53** [comment]
`getObject(id, true)`
is correct to get all enumIds (no string "true").

**Comment by Apollon77** [comment]
So issue is wrong?

**Comment by paul53** [comment]
Yes, issue is wrong.

**Comment by truegreyhound** [comment]
No, the issue is not wrong!
But what?
The description?
[https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#getobject](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#getobject)
> You can define "true" as enumName to get back all enumerations.

The definition in typescript.d.ts?
> function getObject(id: string, enumName?: string): iobJS.Object;

The definition for javasacript?
![image](https://user-images.githubusercontent.com/24899637/91661154-7383a980-eada-11ea-8052-92f5e9a201f2.png)
![image](https://user-images.githubusercontent.com/24899637/91661463-8eefb400-eadc-11ea-8882-920b05438fe2.png)

The implemention in ioBroker?

When I use true (instead 'true') under javascript, then I get what I want. But, under TypeScript I get a compile error!

Please fix this in the documentation and definition or in the implementation!

**Comment by Apollon77** [comment]
Can you please open a new issue to fix the ts definition?! Info: @AlCalzone

**Comment by AlCalzone** [comment]
done
