### ISSUE TITLE
Textfelder

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#626]
Hallo, ich fänd es nützlich neben Blocklies Textfelder setzen zu können die auch umbrechen. Ich schreibe mir ab und an Texte daneben oder kopiere was aus dem Netz was hilfreich/Informativ ist. Die aktuellen Kommentarfelder reichen höchstes als Label da sie auch nur ein paar Zeichen zeigen. VG

**Comment by darkiop** [comment]
![image](https://user-images.githubusercontent.com/205119/91283378-d13a8d80-e78a-11ea-94fd-2cdabac24eb5.png)

Das geht heute schon - Rechte Maustaste auf den Kommentarblock -> Kommentar hinzufügen

**Comment by daniel-lo** [comment]
@darkiop 
Krass .. danke!
