### ISSUE TITLE
Error by canceling scheduled job

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.javascript#629]
Beschreibung siehe hier:
https://forum.iobroker.net/topic/36315/error-by-canceling-scheduled-job

admin: 4.0.10
js: 4.6.17

Die Error Meldung bekam ich bei stop einer Instanz.

Nach einem Neustart von iob Dienst (Windows) war die Meldung weg.

mfg
Dieter

**Comment by Apollon77** [comment]
Very strange ... Auch nach Check von code in node-schedule kann der Fehler nur kommen wenn der Job quasi ungültig ist und damit nicht gestoppt werden kann. Wie das beidem JS passieren soll ... interessant

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren
