### ISSUE TITLE
typescript.d.ts, error in type definition for enumName in getObject

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#634]
**typescript.d.ts, error in type definition for enumName in getObject**  

siehe auch [getObject(<id>, "true") returns no enumerations](https://github.com/ioBroker/ioBroker.javascript/issues/625l)

Please fix the documentation for [getobject](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#getobject)
> You can define "true" as enumName to get back all enumerations.  **to**
> You can define true as enumName to get back all enumerations.

Please fix the typescript.d.ts to
`function getObject(id: string, enumName?: string|boolean): iobJS.Object;`

**Comment by AlCalzone** [comment]
typescript definition is fixed :+1:
