### ISSUE TITLE
Admin UI crashes with TypeError e.palette.background is undefined

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#638]
**Describe the bug**  

**To Reproduce**  
Open Script Editor

**Expected behavior**  
Editor shows

**Screenshots & Logfiles**  
Empty screen and error in the log:
![grafik](https://user-images.githubusercontent.com/17641229/92080361-bb981a00-edc1-11ea-947f-a9723926d7b2.png)

**Versions:**  
 - Adapter version: 4.6.26
 - JS-Controller version: 3.1.6
 - Node version: This is a frontend issue
 - Operating system: This is a frontend issue

**Comment by GermanBluefox** [comment]
Pleas test 4.7.0

**Comment by AlCalzone** [comment]
works fine :)
