### ISSUE TITLE
Update 4.7.1 - cannot extract blockly code

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.javascript#639]
many blockly scripts are affected. i get the error "cannot extract blockly code".
shows no blockly code or messed up code after update.

flag button throws message blocks are not connected properly.

**Comment by dslraser** [comment]
> many blockly scripts are affected. i get the error "cannot extract blockly code".
> shows no blockly code or messed up code after update.
> 
> flag button throws message blocks are not connected properly.

Hier die gleiche Fehlermeldung.

**Comment by skvarel** [comment]
Es scheint nur die Blocklys mit Telegram Blöcke zu betreffen

**Comment by quorle** [comment]
Selbes Problem. Aber mir ist aufgefallen, dass die Datenpunkte in den Programmen anscheinlich nicht mehr verknüpft sind. Bin wieder zurück auf die 4.7.0, habe aber jetzt das gleiche Problem.

**Comment by w6larry** [comment]
Alle Skripte die Sendto verwenden lassen sich nicht mehr extrahieren, funktionieren aber weiterhin. Wenn man ein neues blockly startet ist das Register sendto leer.

**Comment by alikarabacak** [comment]
Betrifft nur die scripte mit telegram.
Die anderen laufen. 
Scripte laufen auch normal aber halt keine Bearbeitung

**Comment by Ajimaru** [comment]
Stimmt, zurück auf Version 4.7.0 hilft nicht, Skripte mit Telegram Funktionen lassen sich nicht als Blockly anzeigen.

**Comment by skvarel** [comment]
Ich bin zurück auf die stable .. da läuft alles.

![grafik](https://user-images.githubusercontent.com/1114419/92306719-a07c0480-ef91-11ea-9991-95c6ad265357.png)

**Comment by w6larry** [comment]
> 
> 
> Ich bin zurück auf die stable .. da läuft alles.
> 
> ![grafik](https://user-images.githubusercontent.com/1114419/92306719-a07c0480-ef91-11ea-9991-95c6ad265357.png)

Bei mir leider erfolglos, der Fehler ist nach wie vor da. :-(  hast du sonst noch etwas zurückgesetzt?

**Comment by alikarabacak** [comment]
würde gerne auch downgraden aber 
mit

```
cd /opt/iobroker
npm i iobroker.javascript@4.6.17 --production
iobroker upload javascript
iobroker restart javascript
```
hat sich nichts getan hab immer noch die 4.7.1

**Comment by skvarel** [comment]
> 
> 
> > Ich bin zurück auf die stable .. da läuft alles.
> > ![grafik](https://user-images.githubusercontent.com/1114419/92306719-a07c0480-ef91-11ea-9991-95c6ad265357.png)
> 
> Bei mir leider erfolglos, der Fehler ist nach wie vor da. :-( hast du sonst noch etwas zurückgesetzt?

Nein, ich habe sonst nichts gemacht, nur das Downgrade des JavaScript Adapters

**Comment by skvarel** [comment]
> 
> 
> würde gerne auch downgraden aber
> mit
> 
> ```
> cd /opt/iobroker
> sudo npm i iobroker.javascript@4.6.17 --production
> sudo iobroker upload javascript
> sudo iobroker restart javascript
> ```
> 
> hat sich nichts getan hab immer noch die 4.7.1

Ich habe einfach die Funktion über den ioBroker genutzt

![grafik](https://user-images.githubusercontent.com/1114419/92308550-b512c980-ef9e-11ea-8320-392cb792d5b8.png)

**Comment by backfisch88** [comment]
Klappt. 

Allerdings gehen die Skripte mit Blockly Plus weiterhin nicht

**Comment by w6larry** [comment]
Ja, so hat es funktioniert. Danke.

**Comment by alikarabacak** [comment]
![Screenshot_20200905_190915](https://user-images.githubusercontent.com/70542890/92310114-63bd0700-efab-11ea-8291-b9d725b85a69.jpg)

Downgrade wird bei mir nicht angezeigt

**Comment by DutchmanNL** [comment]
Issue entsteht durch blockly plus, habe dort issue erstellt 

https://github.com/excal-foley/ioBroker.blockly-plus/issues/5

**Comment by winnyschuster** [comment]
> Issue entsteht durch blockly plus, habe dort issue erstellt

ich hatte noch nie Blockly+, aber trotzdem die beschriebenen Fehler in 4.7.0 + 4.7.1

**Comment by quorle** [comment]
> Issue entsteht durch blockly plus, habe dort issue erstellt
> 
> [excal-foley/ioBroker.blockly-plus#5](https://github.com/excal-foley/ioBroker.blockly-plus/issues/5)

Habe umsichtig kein Blockly Plus und das selbe Problem. Schein ein allgemeines Problem  zu sein.

**Comment by backfisch88** [comment]
Ja.. wenn ihr downgraded klappt alles wieder normal. (Stable) Blockly Plus bleibt aber defekt

**Comment by backfisch88** [comment]
es geht wieder (auch Blockly Plus)! für alle mit gleiche problem
Backup muss vorhanden sein (Habe eins vom Vortag)
Aktiver Verwahrungsort auf stable stellen
Javascript Adapter löschen und Blockly Plus löschen
schauen, ob auch alles gelöscht ist (winscp in /op/iobroker/node_modules) - löschen
javascript adapter ausm stable installieren
Backup einspielen
