### ISSUE TITLE
Update 4.7.1 - killed all of my blocklys

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.javascript#640]
As the title says, had to restore from a backup.
All triggers and objects showed up as missing links to objects, even though in the structure they are still there.
![Blockly](https://user-images.githubusercontent.com/18654629/92311817-cd90dd00-efba-11ea-8ea4-c7a1bc25a00a.jpg)

**Comment by Apollon77** [comment]
4.7.3 should have fixed it

**Comment by Speedbreaker12** [comment]
The issue still persists on 4.7.3

**Comment by Apollon77** [comment]
Also after using a backup of an older version of your scripts?
