### ISSUE TITLE
Update 4.7.1 - cannot extract blockly code - wohl auch bei Blockly Plus Blöcken 

### ISSUE THREAD

**Issue by backfisch88** [ioBroker/ioBroker.javascript#641]
Nicht nur Telegram Blöcke sondern auch die & oder Blöcke von Blokcly Plus sind betroffen. Dort hilft auch kein downgrade

**Comment by itProfi** [comment]
![изображение](https://user-images.githubusercontent.com/6728198/92309353-7fc1a800-efad-11ea-8566-eb7d11a41048.png)
Same problem!

**Comment by backfisch88** [comment]
For normal you Clan downgrade to stable!

This helps For all scripts With sendto Blocks inside


But not for Blockly Plus blocks

**Comment by GermanBluefox** [comment]
Please test 4.7.3
