### ISSUE TITLE
Design availability increased but no more dark background in Blocklyeditor 4.7.1

### ISSUE THREAD

**Issue by Rushmed** [ioBroker/ioBroker.javascript#642]
Hi.

In previous versions up to 4.6.26 the dark editor look was pretty nice.
Dark backgrounds for all menues and Blocklyeditor.
![grafik](https://user-images.githubusercontent.com/59259796/92312815-cf5f9e00-efc4-11ea-808a-30d83f2f6a66.png)

Now there are multiple designs but no one with dark or black Blocklyeditor
![grafik](https://user-images.githubusercontent.com/59259796/92312898-b0add700-efc5-11ea-8955-0455a083b6dd.png)

For me the 4.6.26 dark design is more eyepleasing than the black ones

**Comment by GermanBluefox** [comment]
Fixed in 4.8.4
