### ISSUE TITLE
Object Editor Wrong Querries

### ISSUE THREAD

**Issue by MiniAdnim** [ioBroker/ioBroker.javascript#643]
**Describe the bug**  
After update to 4.7.1 all Links to Object in  Blockys shown as Wrong . Blockys are running anyway. No Blocky Plus here.

**To Reproduce**  
1. Update
2.goto Skript Tab
3. Scroll down to 'a Blocky
4.Open Object Editor'

**Comment by Apollon77** [comment]
Test 4.7.3 please
