### ISSUE TITLE
Version 4.7.2 Verknüpfte States werden bei Öffnen nicht mehr angezeigt

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#644]
Habe nach dem Problem von Version 4.7.1 einmal die 4.7.2 installiert.
Nun sehe ich die ganzen Blöcke in Blockly wieder. Aber nun kommt das Problem:

Die States werden mit dem kompletten Pfad angezeigt.
![Unbenannt](https://user-images.githubusercontent.com/38273154/92323482-69612e00-f039-11ea-8643-35867191b8a2.PNG)

Wenn man nun auf einen State klickt, öffnet sich das Auswahlfenster, aber die States sind nicht mehr verknüpft!
![Unbenannt](https://user-images.githubusercontent.com/38273154/92323497-98779f80-f039-11ea-99e5-81466e5babc0.PNG)

Die Programme laufen weiter, aber man müsste jetzt alles neu Verknüpfen, oder sehe ich das falsch?

**Comment by Apollon77** [comment]
Bitte 4.7.3 testen

**Comment by BobBruni** [comment]
Problem bleibt bestehen!

Version 4.7.3
![image](https://user-images.githubusercontent.com/58072812/92478833-0ad7b380-f1e3-11ea-9978-a789deed4f55.png)


Version 4.6.26
![image](https://user-images.githubusercontent.com/58072812/92478907-26db5500-f1e3-11ea-9739-752720c0f72c.png)

**Comment by senger1985** [comment]
In der 4.8.1 immernoch der Fehler.

**Comment by Berchemer** [comment]
In der aktuell über Default verteilten Version v4.6.17 ist es noch richtig und im Blockly werden Namen statt ID angezeigt.
Ich Versuche mal einzugrenzen, ab wann es sich zwischen 4.6.17 und 4.8.1 geändert hat

**Comment by Berchemer** [comment]
Bei mir sieht es so aus, dass die 4.6.26 des JavaScript-Adapters in Blockly die Namen der Objekte anzeigt und ab der 4.7.0 die IDs statt der Namen angezeigt werden.
![js-issue-03-Unbenannt](https://user-images.githubusercontent.com/44316663/93663982-d4642900-fa6b-11ea-9788-6741a0b4e163.PNG)
![js-issue-04-Unbenannt](https://user-images.githubusercontent.com/44316663/93663984-d75f1980-fa6b-11ea-95a0-65bb7b81354a.PNG)

**Comment by GermanBluefox** [comment]
Fixed in 4.8.3
