### ISSUE TITLE
Missing Names in Object-ID-Selection List.

### ISSUE THREAD

**Issue by ITCrowdIOB** [ioBroker/ioBroker.javascript#645]
Missing Names in Object-ID-Selection List.

![Bild1](https://user-images.githubusercontent.com/64137907/92330237-a0e9cd80-f06d-11ea-9c5d-fa761a794520.PNG)

Shown under Objects:
![Bild2](https://user-images.githubusercontent.com/64137907/92330240-a47d5480-f06d-11ea-90ef-71b0cf1f754d.PNG)

 - JS-Controller version: 4.7.3
 - Node version: v12.18.3
 - Operating system: Debian 10
 - NPM:    6.14.6

**Comment by syberx** [comment]
Das selbe ...
js-1.7.4 ( auch 2-3 alte Versionen versucht )
node: v10.20.1
NPM: 6.14.4

**Comment by DutchmanNL** [comment]
habt ihr mal den browser cache gelöscht ? Ich habe javascript adapter 4.7.3 drauf und es sieht so aus : 

Bitte auch angaben mit richtige Versionen ergänzen : 

@syberx 
- JS-1.7.4 ? (meinst du den JS-Controller, wen ja solltest du mal schleunigst auf JS-Controller 3.x 1,7 ist absah uralt)

@ITCrowdIOB 
- JS-Controller 4.7.3 gibt es nicht, denke mal du meinst javascript adapter ?
Welche JS-Controller und admin version hast du drauf

![Schermafbeelding 2020-09-08 om 12 03 05](https://user-images.githubusercontent.com/7318445/92462812-436b9300-f1cb-11ea-9b27-dea1dfcfc4ca.png)

**Comment by syberx** [comment]
ich meine natürlich javascript Adapter : 4.7.3 ( Vertippt ).
Cache wurde gelöscht. Getestet an einem WIN und Linux System. Chrome und Firefox. Aktuell finde ich keine Lösung.

**Comment by DutchmanNL** [comment]
hmm ich kan es in safari und chrome nicht reproduzieren, von git installiert oder Admin ?

<img width="371" alt="Schermafbeelding 2020-09-08 om 10 14 42" src="https://user-images.githubusercontent.com/7318445/92466001-b840cc00-f1cf-11ea-95fd-ffe1f68af1ad.png">

**Comment by syberx** [comment]
Habe ebenfalls admin und socket.io auf eine ältere Version zurück keine auswirkung. Auch per Git geupdatet nichts.
Kann so das Blockly kaum nutzen . Was genau ist den für diese Auflistung zuständig ? 
Über VIS geht die Objektlist.

**Comment by syberx** [comment]
zum teil werden namen ja angezeigt. Oben stimmt es aber z.n der Order vom Gerät Zigbee da gibt es keine Namen 
![222](https://user-images.githubusercontent.com/15252627/92473945-94838300-f1db-11ea-8842-5f1c52b4aa6d.png)
![111](https://user-images.githubusercontent.com/15252627/92473959-96e5dd00-f1db-11ea-8339-41e571db907a.png)

**Comment by AlCalzone** [comment]
Für mich sieht das aus als hätten die States Namen, die Geräte/Channel aber nicht.

**Comment by galegro** [comment]
Bei mir dasselbe: Die Namen fehlen. Ich verwende Safari/MacOS.

Was ich unternommen habe ..

- Rega neu gestartet
- hmrpc neu eingelesen
- Safari Cache gelöscht
- ioBroker neu gestartet

**Comment by DutchmanNL** [comment]
> Bei mir dasselbe: Die Namen fehlen. Ich verwende Safari/MacOS.

mal bitte screenshot deer Datenpunkte und  screenshot wie es im blockly browser aussieht

**Comment by galegro** [comment]
Und so sieht's bei mir aus ..

<img width="708" alt="Bildschirmfoto 2020-09-09 um 10 13 58" src="https://user-images.githubusercontent.com/70838532/92584523-07503500-f294-11ea-9d38-fb7531df78ab.png">
<img width="902" alt="Bildschirmfoto 2020-09-09 um 10 02 59" src="https://user-images.githubusercontent.com/70838532/92584526-08816200-f294-11ea-8b16-085fc7d839b6.png">

**Comment by DutchmanNL** [comment]
@galegro zeig mal bitte screenshot dieser Ordner in den Objekten

**Comment by galegro** [comment]
Habe ich oben ergänzt.

**Comment by DutchmanNL** [comment]
@AlCalzone ok ich ka es reproduzieren sorry fürs viele nachfragen ....

Problem : Devices & channels Namen werden nicht angezeigt, fuer states wohl.

Objecte im object browser : 
<img width="570" alt="Schermafbeelding 2020-09-09 om 12 09 17" src="https://user-images.githubusercontent.com/7318445/92585474-4b900500-f295-11ea-9dd7-a562fa467eb7.png">

Selbe im Javascript. Browser : 
<img width="768" alt="Schermafbeelding 2020-09-09 om 12 10 41" src="https://user-images.githubusercontent.com/7318445/92585620-7d08d080-f295-11ea-9157-72103ad5869c.png">


Die Sortierung ist. auch kaputt : 

Jetzt : Alles auf Alphabetische Reihenfolge Ordner und states
Sollte :  Erst Ordner dan states

**Comment by galegro** [comment]
Sollte der Fehler nicht im Update von _javascript_ zu suchen sein? Bei mir trat nach diesem Update der Fehler erstmalig auf.

**Comment by syberx** [comment]
Kann man es irgendwie zurücksetzen das man wieder dran arbeiten kann ?

**Comment by AlCalzone** [comment]
Wie wäre ein Downgrade auf die stable-Version?

**Comment by syberx** [comment]
vom Javascript Adapter ? Bringt nichts

**Comment by AlCalzone** [comment]
Auch anschließend nen Upload gemacht zur Sicherheit?

**Comment by syberx** [comment]
Upload ?

**Comment by AlCalzone** [comment]
> Upload ?

https://www.iobroker.net/#de/documentation/tutorial/adapter.md?uploadvonadapterdateien

**Comment by syberx** [comment]
Danke das habe ich nicht gemacht aber nun ausgeführt. Kein erfolg hab nun "4.7.0" drauf selber fehler

**Comment by AlCalzone** [comment]
Hmm, da die Änderung in 4.7.0 gekommen ist, macht es natürlich nur Sinn auf 4.6.x zu gehen :)
![grafik](https://user-images.githubusercontent.com/17641229/92718966-d12db680-f362-11ea-8c00-5e371e308c9b.png)

**Comment by galegro** [comment]
Ich bin auf 4.6.26 zurück. Dort funktioniert noch alles.

**Comment by syberx** [comment]
Stimmt aber komisch dann muss ich letztens ein großen Sprung gemacht haben. Hab den fehler erst vor ein paar Tagen entdeckt. 
Nun 4.6.26 klappt es wieder danke

**Comment by DocGame69** [comment]
Wird eigentlich an dem Problem gearbeitet. Bin schweren Herzens auch wieder auf 4.6.26.
Ohne aussagekräftige Namen habe ich keine Chance in meinen Blocklys durchzublicken...

**Comment by liv-in-sky** [comment]
bei mir kam das heute auch - blockly-arbeit nicht mehr möglich  - muss wohl auch wieder downgraden :-(

**Comment by FabianHM** [comment]
> 
> 
> Wird eigentlich an dem Problem gearbeitet? Bin schweren Herzens auch wieder auf 4.6.26.
> Ohne aussagekräftige Namen habe ich keine Chance in meinen Blocklys durchzublicken...

Ich hab leider das gleiche Problem. Derzeit kann man an Blocklys leider nicht mehr arbeiten da unlesbar.
Auf welche stable Version macht es denn Sinn zurück zu gehen?

**Comment by galegro** [comment]
Wurde doch oben mehrmals geschrieben: 4.6.26

**Comment by galegro** [comment]
Leider funktioniert die heutige Version 4.7.6 auch nicht. Nach wie vor fehlen die Objektnamen.

**Comment by AlCalzone** [comment]
Woher habt ihr 4.7.6? Die gibts noch nicht mal auf Github...
https://github.com/ioBroker/ioBroker.javascript#changelog
Letzter Commit ist 5 Tage her.

**Comment by galegro** [comment]
Die hatte ich heute Nachmittag ganz normal als Update installieren können.

**Comment by winnyschuster** [comment]
> Die hatte ich heute Nachmittag ganz normal als Update installieren können. Diese Version steht bei mir nach wie vor zum Update bereit.

Also bei mir wird 4.7.4 angezeigt, auch ein Download von GitHub bringt nur diese Version

> Vor frei Wochen bin ich von Qivicon zu ioBroker (regelrecht) geflüchtet. Daher bin ich jeden Tag damit beschäftigt, mein System auszugestalten. Vermutlich bemerken die meisten gar nicht, dass hier etwas nicht stimmt.

Das wurde im Forum mehrfach erwähnt und ist auch hier zu lesen. 

Was mich pers. etwas nervt ist das fehlende Feedback der Entwickler: Ich konnte bisher nichts davon lesen, dass daran gearbeitet wird, dass das überhaupt als issue gesehen wird. Dass eine Bearbeitung nicht immer sofort erfolgen kann, versteht sich bei so wenigen Entwicklern von selbst, damit habe ich kein Problem. Aber eine kurze, zeitnahe Notiz zu jedem issue wäre schon sehr wünschenswert, manchmal sind die issues über Wochen nicht kommentiert und man weiss nicht wie das eingeordnet wird. Es geht ja auch nicht um die Funktionalität, dafür gibt es die Stable Versionen, aber Beta testing ist erwünscht und notwendig, diese issues sind erwünscht. And so is feedback from developers :-)

**Comment by galegro** [comment]
@winnyschuster 

Wenn die Entwickler statt hier die Seiten zu füllen, lieber im Hintergrund die Entwicklung vorantreiben, so ist dies mir ehrlich gesagt gar nicht so unrecht. ;-)

Bei Qivicon wartete ich über vier Jahre vergeblich auf eine [Garagentorsteuerung](https://telekomhilft.telekom.de/t5/Smart-Home/Garagentorsteuerung/ta-p/2402318). Was soll mich da noch erschüttern? ;-( Da trage ich dann auch einmal gerne (vergeblich) mit Testen der 4.7.6 zu dem Genzen bei, die übrigens jetzt auch bei mir wieder verschwunden ist. 4.7.4 ist nunmehr wider die letzte Version.

Ohne deinen Argumenten widersprechen zu wollen, rate ich zur Geduld.

**Comment by AlCalzone** [comment]
> Was mich pers. etwas nervt ist das fehlende Feedback der Entwickler: Ich konnte bisher nichts davon lesen, dass daran gearbeitet wird, dass das überhaupt als issue gesehen wird.

Soweit ich weiß, arbeitet an diesen Dialogen (und gefühlt 1000 anderen Dingen) genau eine Person: @GermanBluefox 
Wenn er neben dem Job und Familie seine Zeit damit verbringt, sämtliche Issues zu kommentieren, geht es bei der Entwicklung nicht weiter.
Also: Geduld bitte... Die stable Version läuft und die Beta (latest) wird auch irgendwann gefixt.

**Comment by Apollon77** [comment]
Nochmal so gefragt: In der 4.7.4 ist das issue mit der Auswahl immer noch? BF hatte das an sich in der 47.4 angegangen ... oben steht überall nur 4.7.3 ... und ja da war der Bug ...

**Comment by Negalein** [comment]
Ja, auch in 4.7.4 noch vorhanden.
![javascript - ioBroker (4)](https://user-images.githubusercontent.com/45309436/93322410-9371d780-f813-11ea-8a6d-39c6c71ca00c.png)
![javascript - ioBroker (3)](https://user-images.githubusercontent.com/45309436/93322415-94a30480-f813-11ea-8c71-dfeb3052a5d3.png)

**Comment by Speedbreaker12** [comment]
> 
> 
> Nochmal so gefragt: In der 4.7.4 ist das issue mit der Auswahl immer noch? BF hatte das an sich in der 47.4 angegangen ... oben steht überall nur 4.7.3 ... und ja da war der Bug ...

Bei mir hat die 4.7.4 die nicht verknüpften Objekte in den Skripten gefixed! Danke dafür. Trotzdem bin ich auf die 4.6.26 zurück, weil im Auswahldialog keine Namen neben den Objekten mehr angezeigt werden. Das macht das arbeiten mit blockly fast unmöglich.

**Comment by GermanBluefox** [comment]
Bitte 4.8.1. ausprobieren, da gibt jetzt Einstellungen für Spaltenbreiten
![image](https://user-images.githubusercontent.com/4582016/93617512-5b66c200-f9d6-11ea-877c-5a4329f89116.png)

**Comment by GermanBluefox** [comment]
> > Nochmal so gefragt: In der 4.7.4 ist das issue mit der Auswahl immer noch? BF hatte das an sich in der 47.4 angegangen ... oben steht überall nur 4.7.3 ... und ja da war der Bug ...
> 
> Bei mir hat die 4.7.4 die nicht verknüpften Objekte in den Skripten gefixed! Danke dafür. Trotzdem bin ich auf die 4.6.26 zurück, weil im Auswahldialog keine Namen neben den Objekten mehr angezeigt werden. Das macht das arbeiten mit blockly fast unmöglich.

Ich vermute, es hat was mit Screen-Breite zu tun... Wie breit ist dein Browser-Fenster?

**Comment by Negalein** [comment]
>Bitte 4.8.1. ausprobieren, da gibt jetzt Einstellungen für Spaltenbreiten

Punkt 2 (in deinem Screenshot) konnte Auto nicht deaktiviert werden

Nach neuerlicher Auswahl eines DP blieb die DP-Auswahl grau

wieder zurück auf 4.8.0 war die Auswahl (mit altem DP-Problem) wieder möglich.

**Comment by DocGame69** [comment]
Auto kann nicht deaktiviert werden. Manuelle Eingabe ändert zwar die Breite, der Name der ID ist aber weiterhin nicht sichtbar. Nur die Namen der States.
4.8.1:
![JS 4 81](https://user-images.githubusercontent.com/43096454/93627968-1054ab00-f9e6-11ea-9c16-6ea3ce57a0f8.JPG)
4.6.26:
![JS 4 6 26](https://user-images.githubusercontent.com/43096454/93627986-18144f80-f9e6-11ea-89bf-45d431dfd73d.JPG)

**Comment by galegro** [comment]
In der soeben getesteten Version 4.8.0 ist nicht einmal die Schaltfläche für die Spaltbreiten vorhanden. Mithin kann ich alles Weitere auch nicht ausprobieren. Die Version 4.8.1 wird mir nicht angeboten.

**Comment by Speedbreaker12** [comment]
> 
> 
> > > Nochmal so gefragt: In der 4.7.4 ist das issue mit der Auswahl immer noch? BF hatte das an sich in der 47.4 angegangen ... oben steht überall nur 4.7.3 ... und ja da war der Bug ...
> > 
> > 
> > Bei mir hat die 4.7.4 die nicht verknüpften Objekte in den Skripten gefixed! Danke dafür. Trotzdem bin ich auf die 4.6.26 zurück, weil im Auswahldialog keine Namen neben den Objekten mehr angezeigt werden. Das macht das arbeiten mit blockly fast unmöglich.
> 
> Ich vermute, es hat was mit Screen-Breite zu tun... Wie breit ist dein Browser-Fenster?

Ich denke nicht, dass es was mit der Spaltenbreite zu tun hat, bei States werden die Namen ja angezeigt, aber bei Devices z.B. nicht und bei den kryptischen IDs von z.B. Zigbee oder Sonoff Geräten ist man dann aufgeschmissen und muss einen zweiten Browser öffnen um die ID dann im Objektbrowser nachzuschlagen.
![ids](https://user-images.githubusercontent.com/18654629/93640976-cd053700-f9fb-11ea-8816-0a871659aba8.JPG)

**Comment by Apollon77** [comment]
Ahhhh ... es fehlen also die Namen von Channels und Device Objekten

**Comment by DocGame69** [comment]
Es passt vielleicht nicht 100% hierher. Seit einem Update beim Scenen-Adapter vor einiger Zeit ist dort das gleiche. Mich hat das zwar generft, ich habe daraufhin die paar Scenen, die ich anlegen wollte in Blockly gemacht. Ich habe die Befürchtung, wenn die Umstellung auch anderer Adapter in dieser Form weitergeht ein bedienen des ioBrokers nicht mehr vernünftig möglich ist. Ich hoffe, das das Problem bals generell lokalisiert wird und Channels, States usw. wieder mit den Angelegten Namen sichtbar sind(auch in anderen Adaptern die auf diese Bibliothek zugreifen.
Hier ein Screenshot vom Scenen-Adater:
![scenen](https://user-images.githubusercontent.com/43096454/93662158-2ef68880-fa5e-11ea-8c13-f0ca8a489b73.JPG)

**Comment by Berchemer** [comment]
Bin mir nicht sicher, ob hier alle vom gleichen Problem sprechen. Mich interessierte dieses Issue wegen des o.g. Problems von Negalaein von vor 3 Tagen und Galegro von vor 10 Tagen, weil auch ich in der Blockly-Darstellung nicht die Namen der Objekte angezeigt bekomme, sondern ihre ID.
Sollte es sich bei Meinem um ein anderes Problem handeln, mache ich gerne ein neues Issue auf.

**Comment by Ilovegym66** [comment]
Kann ich bestätigen, seit ein paar Versionen werden die Namen der Objekte nicht mehr angezeigt, ist auch in V4.8.1 so. 
Das Auswahlfenster wurde in 4.8.1 gefixed, da sieht man wieder alles.
Nur werden die Blocklys unübersichtlich, da der ganze ID angezeigt wird, bzw. ein Teil davon.. siehe hier:
![grafik](https://user-images.githubusercontent.com/36229898/93662677-3e77d080-fa62-11ea-8bc0-3b80e191e029.png)

js-controller 3.16, Node 12.8.4, Javascript-Adapter 4.8.1

**Comment by Speedbreaker12** [comment]
> 
> 
> Kann ich bestätigen, seit ein paar Versionen werden die Namen der Objekte nicht mehr angezeigt, ist auch in V4.8.1 so.
> Das Auswahlfenster wurde in 4.8.1 gefixed, da sieht man wieder alles.
> Nur werden die Blocklys unübersichtlich, da der ganze ID angezeigt wird, bzw. ein Teil davon.. siehe hier:
> ![grafik](https://user-images.githubusercontent.com/36229898/93662677-3e77d080-fa62-11ea-8bc0-3b80e191e029.png)
> 
> js-controller 3.16, Node 12.8.4, Javascript-Adapter 4.8.1

Bei mir ist es ganu andersrum! Seit der 4.7.4 werden bei mir in den Blocklys die Namen wieder korrekt angezeigt und darum geht es hier in dieser Issue aber nicht, sondern um die fehlenden Namen von Channels und Devices im Auswahldialog, siehe ersten Beitrag.

**Comment by Berchemer** [comment]
Ok. Dann mach ich ein neues Issue auf, weil es bei mir mit der 4.8.0 immer noch nicht in Blockly klappt.

**Comment by Negalein** [comment]
> Ok. Dann mach ich ein neues Issue auf, weil es bei mir mit der 4.8.0 immer noch nicht in Blockly klappt.

gerade gesehen, dass es bereits eins gibt.
https://github.com/ioBroker/ioBroker.javascript/issues/644

**Comment by Berchemer** [comment]
Danke für die Info.
Hatte dieses Issue gar nicht gesehen :-(
Dann erspare ich mir das Neuerstellen ;-)

**Comment by ITCrowdIOB** [comment]
Soeben 4.8.1 installiert. Diese produziert wieder ein leeres Fenster wenn man in Blockly eine Objekt-ID auswählen will.

**Comment by winnyschuster** [comment]
> Soeben 4.8.1 installiert. Diese produziert wieder ein leeres Fenster wenn man in Blockly eine Objekt-ID auswählen will.
> Zurück auf 4.8.0.

Auf meinem Hauptsystem kann ich dieses Verhalten bestätigen, auf einem Testsystem (mit weniger installierten Adaptern) jedoch nicht. Auf beiden Systemen sind jeweils die aktuellsten Versionen aus Latest und node 12.8.4 und npm 6.14.8

**Comment by GermanBluefox** [comment]
Please check the 4.8.2:
![image](https://user-images.githubusercontent.com/4582016/93710756-465e7000-fb49-11ea-9699-9354ea01b743.png)

**Comment by winnyschuster** [comment]
> Please check the 4.8.2:
looks good, empty window when trying to selecting states is also gone

**Comment by DocGame69** [comment]
Die Auswahlbox sieht jetzt gut aus. 
In den Blocklys ist leider immer noch nicht der Name wie vor 4.6.26 vorhanden und macht das ganze recht schwer bei Änderungen.
![JS4 8 2](https://user-images.githubusercontent.com/43096454/93713816-b0354480-fb5e-11ea-9ed3-13f20b520536.JPG)

**Comment by FabianHM** [comment]
> 
> In den Blocklys ist leider immer noch nicht der Name wie vor 4.6.26 vorhanden und macht das ganze recht schwer bei Änderungen.
> ![JS4 8 2](https://user-images.githubusercontent.com/43096454/93713816-b0354480-fb5e-11ea-9ed3-13f20b520536.JPG)

Das Problem besteht bei mir leider auch weiterhin

**Comment by ITCrowdIOB** [comment]
Die fehlenden Namen sind wieder da. Nettes Upgrade, das Spalten konfigurieren. 
Danke fürs Patchen.

P.S: Objekt ID Bezeichnung. Bug oder Feature :)

**Comment by Apollon77** [comment]
Wenn es in bestehenden Blocklies noch nicht geht (wobei es zwei Themen sind hier!!) Bitte nochmal das Objekt neu zuweisen. passt es danach?

**Comment by DocGame69** [comment]
Habe gerade 4.6.26draufgemacht. Als ich vorhin getestet habe, hat aber auch die neu angewählten States im Blockly nur mit der ID benannt. Muss jetzt leider weg und kann heute nicht weiter testen. 
Klar sind das unterschiedliche Themen und ich habe sogar andere Adapter ins Spiel gebracht. Irgendwie scheint mir das aber ein generelles Problem mit dem neuen Look zu sein.

**Comment by Berchemer** [comment]
> > In den Blocklys ist leider immer noch nicht der Name wie vor 4.6.26 vorhanden und macht das ganze recht schwer bei Änderungen.
> > ![JS4 8 2](https://user-images.githubusercontent.com/43096454/93713816-b0354480-fb5e-11ea-9ed3-13f20b520536.JPG)

Gleiches auch für mich. Namen in der Objektauswahlliste bei 4.8.2 wieder wie früher zu sehen. Also soweit Danke @Bluefox für den Fix. Andere Bereiche außerhalb des Blockly habe ich bisher nicht getestet. 

Nur im Blockly auch mit neuer Zuweisung nur die ID statt des Namens. Aber hierfür steht ja auch eher Issue 644 oder?

**Comment by GermanBluefox** [comment]
Fixed in 4.8.3

**Comment by Speedbreaker12** [comment]
Mega gut! Vielen Dank, funktioniert perfekt!

**Comment by Ilovegym66** [comment]
@GermanBluefox  Top, vielen Dank! Bist unser Held 🙂👍👍

**Comment by Negalein** [comment]
@GermanBluefox 
Thx Ingo
![javascript - ioBroker (9)](https://user-images.githubusercontent.com/45309436/93720205-de7b4a00-fb87-11ea-976f-00c401207f9c.png)

**Comment by galegro** [comment]
Leider scheint die 4.8.3 noch nicht (für alle) verfügbar zu sein. Mir wir zum Update nur 4.8.1 angeboten.

**Comment by Negalein** [comment]
> Leider scheint die 4.8.3 noch nicht (für alle) verfügbar zu sein. Mir wir zum Update nur 4.8.1 angeboten.

Über die Katze --> von Git-Hub
![adapters - ioBroker (1)](https://user-images.githubusercontent.com/45309436/93722008-04a6e700-fb94-11ea-923e-48dee4504898.png)

**Comment by Berchemer** [comment]
Danke. 4.8.3 hat auch meine Probleme gefixt :-)
