### ISSUE TITLE
No "send to" available anymore

### ISSUE THREAD

**Issue by dkmouk** [ioBroker/ioBroker.javascript#646]
Since the last update i cant open my Blockly scripts where i used the pushover and email sendto.

In the blockly adapter i have also at "send to" nothing available anymor. Its empty.

Version: Script Engine 4.7.1

**Comment by Apollon77** [comment]
Please test 4.7.2/3

**Comment by dkmouk** [comment]
Its working again with 4.7.3.
Thank you
