### ISSUE TITLE
V4.7.3 Blockly: JS-Funktionsblock erlaubt keine Code-Eingabe und -Änderung mehr

### ISSUE THREAD

**Issue by winnyschuster** [ioBroker/ioBroker.javascript#647]
Wenn man auf die drei Punkte zur Eingabe des JS codes klickt erscheint nur ein leerer Bildschirm. Dies passiert sowohl bei bestehenden JS-Funktionen als auch bei neu zu erstellenden JS-Funktionen.

Ein Downgrade auf 4.6.26 behebt das Problem

**Comment by GermanBluefox** [comment]
Please test 4.7.4

**Comment by winnyschuster** [comment]
Thank you for fixing this, issue is gone in 4.7.4
