### ISSUE TITLE
Script Editor in den JS-Blocklys zeigt nur noch eine einfarbigen Fläche 

### ISSUE THREAD

**Issue by ITCrowdIOB** [ioBroker/ioBroker.javascript#648]
Der Aufruf des Script Editors in den JS-Blocklys (Funktionen) zeigt nur noch eine einfarbigen Fläche ohne Inhalt.

Keine Fehlermeldung im LOG.

 - JS-Controller version: 4.7.3
 - Node version: v12.18.3
 - Operating system: Debian

Downgrade auf 4.7.1 behebt den Fehler nicht.

**Comment by itProfi** [comment]
Same bug!

**Comment by GermanBluefox** [comment]
Duplicate https://github.com/ioBroker/ioBroker.javascript/issues/647
