### ISSUE TITLE
Think about native integration of Blockly Plus to JavaScript Core source

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.javascript#649]
Quite some useful blocks have been developed with blocky plus, but as its an plugin and not native updates can break code.

Would be great to adopt these blocks native to our adapter : https://github.com/excal-foley/ioBroker.blockly-plus

**Comment by itProfi** [comment]
I support! Please, integrate it!

**Comment by GermanBluefox** [comment]
Why should it be integrated?
It could be used as adapter, isn't it?

**Comment by itProfi** [comment]
I am not author, but i think (and i try but not work for me) today is it standalone npm module..https://github.com/excal-foley/ioBroker.blockly-plus/issues/8

**Comment by DutchmanNL** [comment]
> Why should it be integrated?
> It could be used as adapter, isn't it?

it could, but there is no progress in development and updates of javascript adapter can break it so having it in one would be more efficient for end-user.

Looking at usability for end-user und future/update proof concept.

**Comment by PeterVoronov** [comment]
Looks like very promosing, the better is a default feature, instead of separate adapter ...
