### ISSUE TITLE
$ selector implies wildcard at the beginning and the end of the idfilter

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#652]
**Describe the bug**  
`$` implies a wildcard at the start and the end of the state query, which is undocumented behavior and also makes state filtering overly hard (i.e. you have to filter again in the `each` function).

**To Reproduce**  
1. Given some states that contain the word `state`
2. `$('state[id=STATE]').each(state => log(state));` logs/returns
    ```
    hm-rpc.1.00135BE992528C.5.ACTIVITY_STATE
    hm-rpc.1.00135BE992528C.6.ACTIVITY_STATE
    hm-rpc.2.INT0000001.1.VALVE_STATE
    hm-rpc.2.INT0000001.1.WINDOW_STATE
    hm-rpc.2.INT0000001.3.STATE
    hm-rpc.2.INT0000001.4.STATE 
    ```

**Expected behavior**  

None of the above states should be returned. As per the [docs](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#---selector), the "idfilter" can (i.e. *may*) have wildcards '*'. My query did not have wildcards, yet, they are implied.

**Versions:**  
 - Adapter version: 4.7.4
 - JS-Controller version: 3.1.5
 - Node version: 12
 - Operating system: docker

**Additional context**

Also consider the first example from the docs:

> `$('state[id=*.STATE]')` or `$('state[state.id=*.STATE]')` or `$('*.STATE')` - select all states where id ends with ".STATE".

is actually true, but if the wildcard is not at the beginning of the string the "ends with" part no longer holds true:

```js
$(`state[id=calendar.0.*.events]`).each(state => log(state));
=>
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.0.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.0.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.1.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.1.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.10.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.10.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.11.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.11.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.12.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.12.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.13.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.13.eventsNumber
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.14.events
calendar.0.NmUyNjFmODY3MmNhMy9iYXNpYy5pY3.14.eventsNumber
```

**Comment by AlCalzone** [comment]
The first part of your issue seems to be a bug, but ...

> the "ends with" part no longer holds true

this looks like a misunderstanding on your part. These three examples you mentioned all have `*.` at the start of the selector and then something, so that something must only appear at the end of the ID.

**Comment by AlCalzone** [comment]
@agross 
could you try the following version from #658 please?
```
cd /opt/iobroker
npm i ioBroker/ioBroker.javascript#selector-no-wildcard
```

**Comment by agross** [comment]
> this looks like a misunderstanding on your part.

If I understand correctly: This means wildcards are only supported as the first or last character, but not as infix?

**Comment by agross** [comment]
#658 appears to fix the query.

The API is still not optimal, IMHO. By transforming the string to a regex but only handling anchors and wildcards you can construct something that uses regex characters like cardinality, but these won't be escaped.

I find it a bit unfortunate to hide the fact that internally regexes are used. Don't pretend to match against strings when the rest of the string may contain something of importance to the regex engine.

Consider this:
* `$('state[id=*STATE\\d]')`: Tests will be made against `/.*STATE\d$/`, i.e. you will find `STATE1` but not `STATE\d`.
* `$('state[id=*STATE?]')`: Will find `STAT` and `STATE`.

Instead of hiding that regexes are used internally, embrace it as a feature. I suggest having to APIs instead, one matching against plain strings and another one to match against regexes only and without special handing of chars. The latter option will provide the most flexibility.

**Comment by AlCalzone** [comment]
> If I understand correctly: This means wildcards are only supported as the first or last character, but not as infix?

They are supported in the middle of the selector. But the example you posted above (`*.STATE`) should only match IDs that end with `.STATE`. So your comment 
> if the wildcard is not at the beginning of the string the "ends with" part no longer holds true

does not really make sense in that context.

---

> By transforming the string to a regex but only handling anchors and wildcards you can construct something that uses regex characters like cardinality, but these won't be escaped.

Using a regex is the nicest way to match multiple wildcards in the middle of a string without resorting to custom string splitting and parsing logic. The "clean" way IMO would be escaping the stuff that has a special meaning in Regexes. 

> I suggest having to APIs instead, one matching against plain strings and another one to match against regexes only

I think this would be cool. The question is what syntax do we use to say "treat this as a regex"? Maybe:
* `$('state[id=*STATE?]')` - matched as a string (with handling for wildcards only)
* `$('state[id~=^.*\\.STATE?$]')` - matched as a regex (nothing will be escaped)

However, parsing the selector string is going to get real ugly if you need to consider square brackets in the regex, e.g. when using `[A-Z]oot` as a regex.

**Comment by agross** [comment]
> does not really make sense in that context.

I came to that conclusion because from the docs (and without knowing the internals) I thought that the query `state[id=calendar.0.*.events]` means "states starting with `calendar.0.` and ending with `.events`" (i.e. no wildcard at the end). But this selector found more than expected because the old implementation didn't anchor (`$`) the end of the string.

**Comment by agross** [comment]
> I think this would be cool.

I believe tracking this as a new issue would be a good idea.

Another idea to add to this would be to have an easy way to get all matches as an array. Right now one needs to `push` all elements into an empty array in the `each`.

> `$('state[id~=^.*\\.STATE?$]')`

I'd prefer `=~` as [Ruby](https://ruby-doc.org/core-2.5.1/Regexp.html#method-i-3D~) does it.

> parsing the selector string is going to get real ugly

I think implementing the parser as a state machine might be a good solution to this.

**Comment by AlCalzone** [comment]
> But this selector found more than expected because the old implementation didn't anchor (`$`) the end of the string.

Ok, now I understand. You were talking about the actual (buggy) behavior while I thought you referenced the documentation.

I agree that we should track the regex selector feature in a separate issue. If you have a good idea for the parser, feel free to go ahead and create a PR :)

Regarding the array-like behavior: The returned object currently includes a length property and indexed access, so you can at least loop through it in a for loop. I'm not sure why an object is returned instead of an array, but we can't break backwards compatibility here.
My suggestion would be implementing the `[Symbol.iterator]` property on the result object, so you can easily iterate over it with `for-of` or spread it into an array with `[...result]`.
