### ISSUE TITLE
save button color in script

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.javascript#653]
the new design for javascript looks very good 

would it be possible to change the color of the save button in the script editor to another color e.g. red or orange - the blue one is "not jumping" in the eye

**Comment by GermanBluefox** [comment]
Orange could be good. :)

**Comment by liv-in-sky** [comment]
👍

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/93762245-75d7b000-fc0f-11ea-9cae-a408ebe5a920.png)

**Comment by liv-in-sky** [comment]
yeah - this is really burning - thanx
