### ISSUE TITLE
Bug in Datum / Zeit Blockly

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.javascript#656]
Verwendet man im Skripte Editor unter Blockly den Baustein "Aktuelle Zeit ist - ZWISCHEN - xx:xx und yy:yy", kann man diesen nicht Fehlerfrei kopieren (strg+C). Schon beim ziehen, dieses Blocklys, ergibt sich ein "Geister Block" welcher die Uhrzeit 18:00 fest eingetragen hat.

Versucht man nun diesen Block zu kopieren, wird diese "18:00 Uhr" in den Vordergrund geholt und der Block ist nicht mehr bedienbar - siehe Screenshot

![2020-09-28 20_07_48-javascript - ioBroker](https://user-images.githubusercontent.com/44617472/94470876-8c11dd00-01c8-11eb-9f22-fbdb93a469ea.png)
![2020-09-28 20_07_19-Greenshot capture form](https://user-images.githubusercontent.com/44617472/94470877-8caa7380-01c8-11eb-963b-dc67ca6e97ec.png)

JS-Skript Engine ist  4.8.4 - alles andere siehe Screenshot

![2020-09-27 09_05_59-info - ioBroker](https://user-images.githubusercontent.com/44617472/94470968-b06db980-01c8-11eb-966f-b7b1f68fbb10.png)

**Comment by winnyschuster** [comment]
Das kann ich nur optisch nachvollziehen. Bedienbar im Sinne von Modus wechseln(kleiner als, größer als, etc.) oder andere Uhrzeiten eintragen funktioniert. Schon der Wechsel zu einem anderen Skript oder zur Ansicht als Javascript und zurück behebt diesen optischen Fehler. Ist natürlich trotzdem nicht schön, die Funktionalität ist bei mir nicht beeinträchtigt(Node 12.18.4)

**Comment by GermanBluefox** [comment]
Da es um optischen Fehler geht und Blockly selbst von Google entwickelt wird... Ist es schwer zu fixen.
