### ISSUE TITLE
Unable to trigger blockly script with schedule

### ISSUE THREAD

**Issue by ahnungsbefreit** [ioBroker/ioBroker.javascript#660]
**Describe the bug**  
"Zeitplan" schedule as a trigger for a blockly does not work. Classical "CRON" format is not affected.

**To Reproduce**  
1. Create a blockly with schedule "Zeitplan" Wizzard or simple as trigger (see screenshot)
2. Watch the console when executing the script and you will see "0 schedules"

**Expected behavior**  
Should trigger not only with CRON.

**Screenshots & Logfiles**  
See attached

**Versions:**  
 - Adapter version: 4.8.4
 - JS-Controller version: 3.1.6
 - Node version: 12.8.4
 - Operating system: Linux

**Additional context**  
![image](https://user-images.githubusercontent.com/72397840/95092387-d85ca000-0727-11eb-988a-9944e9109d15.png)

![image](https://user-images.githubusercontent.com/72397840/95092416-e27e9e80-0727-11eb-9688-bcf172d12284.png)

**Comment by GermanBluefox** [comment]
Can you please show the configuration of "Zeitplan"?

**Comment by ahnungsbefreit** [comment]
Not sure what you need in addition to the screenshot?

**Comment by ahnungsbefreit** [comment]
Just tested again, e.g. this one does not create a subscription
![image](https://user-images.githubusercontent.com/72397840/95605277-02c89900-0a59-11eb-98bc-d08180a33042.png)

**Comment by GermanBluefox** [comment]
I think it is just a log text issue. Fixed in next version.
![image](https://user-images.githubusercontent.com/4582016/97992160-9c7a3080-1de2-11eb-8510-622c73ba0e6b.png)
