### ISSUE TITLE
$ selector should be iteratable

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#661]
Results of a `$()` selector query are currently hard to transform into an array:

```js
const arr = [];
$('something').each(x => arr.push(x))
```

**Describe the solution you'd like**

```js
const arr = [...$('something')]
```

**Additional context**

https://github.com/ioBroker/ioBroker.javascript/issues/652#issuecomment-704059791

**Comment by GermanBluefox** [comment]
I have no Idea, how to implement this.

**Comment by AlCalzone** [comment]
> I have no Idea, how to implement this.

I do
