### ISSUE TITLE
getAttr function seems no longer to work properly

### ISSUE THREAD

**Issue by CommanderXXL** [ioBroker/ioBroker.javascript#664]
I use a script which gets the names of different objects with " CurrentDeviceName = getAttr((objectFromID(DeviceParentID)), 'common.name');"
Where the DeviceParentID is a string containing the ioBroker object name and the method "objectFromID" is defined as:
async function objectFromID(id) {
    return getObject(id);
}

Since the update to Adapter version 4.9.0
all i get from the above call is a "null" object:

![image](https://user-images.githubusercontent.com/49292478/95647755-3562a800-0ad2-11eb-94ba-2b328a98c274.png)

for the output i use "console.log(CurrentDeviceName);"

**Comment by GermanBluefox** [comment]
To be honest, I don't understand, how it works before, as it missing important `await` before `objectFromID' call.

```
CurrentDeviceName = getAttr((await objectFromID(DeviceParentID)), 'common.name');
```

**Comment by CommanderXXL** [comment]
Alles klar, das habe ich soweit verstanden. Gibt es auch eine Möglichkeit das mit "Blockly" zu machen, also ohne das "async" oder dem getAttr das await mitzugeben? Das war nämlich der Grund wieso es so ist, ich hatte alles mit Blockly gebaut und seit dem 4.9.0 update hast du wohl etwas mit dem await geändert.

**Comment by GermanBluefox** [comment]
Ist das Blockly oder JS Code? Wie sieht Blockly aus? (Falls es Blockly ist)

**Comment by CommanderXXL** [comment]
Also ja, das ist blockly: sieht so aus:
![image](https://user-images.githubusercontent.com/49292478/95708928-d6ca3500-0c5d-11eb-856c-051b84ece6d2.png)
Und das Ganze im JS (mit umschalt Button oben Rechts) dann so:
![image](https://user-images.githubusercontent.com/49292478/95708980-f95c4e00-0c5d-11eb-8c68-c9a152df9296.png)

Der Code hat bis zum 4.9.0 Update einwandfrei funktioniert. Ich kann allerdings nicht mehr sagen ob da auch schon "async" vor der Function gestanden hat oder nicht. Das await war sicher nicht drin und ist es jetzt durch Blockly auch immer noch nicht. Leider habe ich keine Option gefunden das "async" vor der Function wegzumachen ausser durch komplette Komvertierung in JS was ich eigentlich nicht wollte.

**Comment by GermanBluefox** [comment]
Ok. Bitte 4.9.1 testen

**Comment by CommanderXXL** [comment]
Ich habe es mit 4.9.3 probiert (Nehme mal an da waren noch andere Sachen die du gefixt hast). Damit funktioniert es wieder einwandfrei. Viele herzlichen Dank.
