### ISSUE TITLE
TypeError: fs.watch is not a function 4.8.4

### ISSUE THREAD

**Issue by nooxnet** [ioBroker/ioBroker.javascript#668]
I wanted to use `fs.watch()` and got the error "TypeError: fs.watch is not a function". Initially I used TypeScript with `import * as fs from 'fs';` but it's the same in JavaScript with `var fs = require('fs');` Other fs-functions work (readFile, copyFile, mkdir, ...). As I saw similar issues with other fs-functions in the past I assume it's a bug in the script engine. For `fs.watchFile` I get the same error.

**Reproduce**
`

var fs = require('fs');
try {
    var e = fs.existsSync('abc'); // other fs-functions work
    log(e.toString());
    var watcher = fs.watch('abc', (event, fileName) => {});
} catch(error) {
    log(error.stack);
}
`

**Error/Stack Trace**
javascript.0 (28197) script.js.common.TestScript: TypeError: fs.watch is not a function at script.js.common.TestScript:79:22 at Script.runInContext (vm.js:130:18) at Script.runInNewContext (vm.js:135:17) at execute (/opt/iobroker/node_modules/iobroker.javascript/main.js:1320:27) at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1504:38) at /opt/iobroker/node_modules/iobroker.javascript/main.js:1559:17 at /opt/iobroker/node_modules/iobroker.javascript/main.js:1140:17 at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33 at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23) at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49

**Versions:**  
 - Adapter version: 4.8.4, updated to 4.9.0 - same error
 - JS-Controller version: 3.1.6
 - Node version: v12.18.4
 - Operating system: raspian

**Additional context**  
When I start a similar script as above in the console with node directly the watch function complains about the missing file.

**Comment by GermanBluefox** [comment]
Will be fixed in the next version 4.9.3
