### ISSUE TITLE
No top-level await for TypeScript

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#669]
**Describe the bug**  

As far as I understand c12eb2952d8b54f4c35a866789b81fffbaa9ddd9 and 2acf28ecd6c54ee880d36d0711f07f951e9e51f1 top-level awaits should work now. The TypeScript compiler barfs at `await` at the top-level because the TypeScript compilation target [is still ES5](https://github.com/ioBroker/ioBroker.javascript/blob/435463f464cb84006431c47edf38a2e8f31fe891/main.js#L115).

**To Reproduce**  
1. Create a new TypeScript script with the following contents:
   ```ts
   await getStateAsync('foo')
   ```
2. See compilation error in log:
   ```
   script.js.Automation.Script_1: TypeScript compilation failed: await getStateAsync('foo') ; ^ ERROR: Top-level 'await' 
   expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set
   to 'es2017' or higher.
   ```

**Expected behavior**  

Script should compile.

**Versions:**  
 - Adapter version: 4.9.0
 - JS-Controller version: 3.1.5
 - Node version: 12
 - Operating system: docker

**Comment by GermanBluefox** [comment]
Can you check 4.9.2 please?

**Comment by agross** [comment]
4.9.2 works, but the `await` still gets a red squiggly underline in the editor.

**Comment by AlCalzone** [comment]
> but the `await` still gets a red squiggly underline in the editor.

I'm not sure we can fix this. To make the editor shut up about the top level await, we need to change the ES version and module type, which will definitely break other stuff.

**Comment by agross** [comment]
@AlCalzone Isn't this exactly what happened in https://github.com/ioBroker/ioBroker.javascript/commit/3d5ea24f8d3fa8604cdb0799fe5e3d6b05885ce7#diff-7a9076d6d94e62c13d641aa71f19ae8e?

I mostly code in VS Code, so the red squiggly is no issue for me. Just wanted to let you know.

**Comment by AlCalzone** [comment]
@agross yes but that change was not good. Not targeting ES5 breaks scripts that use `import ... from` syntax, because the Node.js VM does not support that.

**Comment by agross** [comment]
@AlCalzone The problem is that if you revert back to targeting ES5 TypeScript won't compile top-level awaits anymore.

**Comment by AlCalzone** [comment]
If you look at my changes you'll see that there are no top-level awaits. Just like in JS, the compiled code is wrapped in an immediately invoked async function.

**Comment by agross** [comment]
@AlCalzone If I understand correctly that means code gets wrapped before compiling it? If this is the case I would need to have a local (VS Code) tsconfig.json that will locally syntax-check and compile ES2017. The results won't probably be the same, but it's worth noting that the environments will differ and probably lead to other issues down the line. (If I compile locally against ES5 top-level await would cause compilation errors.)

**Comment by AlCalzone** [comment]
Correct. However you could wrap the code yourself locally to achieve the same result.
