### ISSUE TITLE
Suchfunktion in 4.9.0 findet nur die Suchbegriffe in den Scriptnamen

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.javascript#671]
**Describe the bug**  
Gibt man einen Suchbegriff ein erscheinen nur die Scripte in denen im Namen der Suchbegriff auftaucht.

**To Reproduce**  
1. Klick auf dem Suchsymbol
2. Eingabe vom Suchbegriff

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![grafik](https://user-images.githubusercontent.com/68483974/95782973-3281d600-0cd1-11eb-8371-8a097ae517e1.png)

in 4.8.4 sieht es so aus:
![grafik](https://user-images.githubusercontent.com/68483974/95783386-ff8c1200-0cd1-11eb-8090-a3010449f6ef.png)

**Versions:**  
 - Adapter version: 4.9.0
 - JS-Controller version: 3.1.6
 - Node version: v12.18.4
 - Operating system: linux arm PI4B

**Additional context**

**Comment by GermanBluefox** [comment]
Should work in the latest version
