### ISSUE TITLE
#670/4.9.3 broke TypeScript imports

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#672]
**Describe the bug**  

TypeScript imports cannot be contained in function scope. Because all the stuff that is compiled is wrapped in an extra async function, one can no longer use `import`s.

**To Reproduce**  
1. Create TypeScript script that uses an import
2. Observe errors:
   ```
   TypeScript compilation failed: (async () => {import { concat, EMPTY, Observable, of } from 'rxjs'; ^ ERROR: An import declaration can only be used in a namespace... blah blah blah
   ```

**Expected behavior**  

TypeScript imports should be possible.

**Versions:**  
 - Adapter version: 4.9.3

**Additional context**  
I get the impression a test suite is in order.

**Comment by AlCalzone** [comment]
Damn it :D

**Comment by AlCalzone** [comment]
I'll provide a fix later.
