### ISSUE TITLE
Blockly: Leerzeichen im Zeitplan-Namen werden im Stop Zeitplan Block nicht konvertiert

### ISSUE THREAD

**Issue by winnyschuster** [ioBroker/ioBroker.javascript#676]
**Describe the bug**  
Im Stop Zeitplan Block werden Leerzeichen im Namen nicht konvertiert, im Zeitplan werden sie durch **_**(underscore) ersetzt

**To Reproduce**  
Erstelle einen Zeitplan mit Namen **Mein Zeitplan**
Wähle im Stop Zeitplan diesen Namen

Beim Start des Skripts erfolgt eine Fehlermeldung
![issue](https://user-images.githubusercontent.com/7774086/96184382-b689c700-0f38-11eb-9e04-0366d04b17de.PNG)

`
(function () {if (Mein Zeitplan) {clearSchedule(Mein Zeitplan); Mein Zeitplan = null;}})();

Mein_Zeitplan = schedule('* * * * *', async function () {
});
`

**Comment by GermanBluefox** [comment]
Fixed in 4.9.9
