### ISSUE TITLE
$ selector with anchor '$' don't work with lattest update

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.javascript#678]
**Describe the bug**  
in many scripts I get certain data points via a selector.
E.g. 
`const idState: string = 'javascript.0.scripts.cams-ctrl.CDPversion';  
`
`
const objState = $('state[state.id=' + idState + '$]');
`
`
log(' objState: ' + JSON.stringify(objState) + '; type: ' + typeof objState + '; length: ' + objState.length);
`
Before the last update, the execution of the selector was successful, now I have to omit anchor, which can lead to unwanted results.

**To Reproduce**  
see my code above

**Expected behavior**  
With the anchor '$' the selector should find my state

**Versions:**  
 - Adapter version: 4.9.3
 - JS-Controller version: 3.1.6
 - Node version: v10.18.0
 - Operating system: debian jessie

**Comment by AlCalzone** [comment]
> which can lead to unwanted results.

Can you describe HOW this actually leads to unwanted results? The previous behavior was buggy and should be fixed now.
If you are not using wildcards, the state ID now matches the entire string (implying ^ and $ in the regex).

**Comment by truegreyhound** [comment]
an example would be the following data points:
`javascript.0.watering.duration`
`javascript.0.watering.duration_min`
`javascript.0.watering.duration_max`
`javascript.0.watering.duration_day`
`javascript.0.watering.duration_lastday`

in the version before I have get with `$('state[state.id=javascript.0.watering.duration$]');` exactly this state, now without anchor, ok I need to review and adjust all of my scripts.

I continued testing with the following results:
$('state[state.id=javascript.0.watering.duration*] - I get all 5 states, expected 5 - ok
$('state[state.id=javascript.0.watering.duration*y$] - I get 0 states, expected 2
$('state[state.id=javascript.0.watering.duration*y] - I get 2 states
that actually means, the anchors are set with and without a wildcard

I don't understand why the following selectors can't find anything:
$('state[state.id=javascript.**?**.watering.duration]
$('state[state.id=javascript.**\***.watering.duration]

**Comment by AlCalzone** [comment]
> ('state[state.id=javascript.0.watering.duration_y$] - I get 0 states, expected 2_

You are now searching for a state with the exact ID `javascript.0.watering.duration_y$`. I wouldn't expect any of the above states to match that.

> $('state[state.id=javascript.0.watering.durationy]

Really? Even with the old Regex behavior I wouldn't expect any state to match that.

> $('state[state.id=javascript.?.watering.duration]

dito

> $('state[state.id=javascript.*.watering.duration]

That **should** match the very first DP. If it doesn't I need to check.

**Comment by AlCalzone** [comment]
I edited your post because the formatting was messed up.

Let's discuss your assumptions:
> `$('state[state.id=javascript.0.watering.duration*y$]')`

matches a state that starts with `javascript.0.watering.duration` and ends with `y$` which none of your states do. So 0 states is correct.

> `$('state[state.id=javascript.0.watering.duration*y]')`

matches a state that starts with `javascript.0.watering.duration` and ends with `y` which 2 of your states do (`_day` and `_lastday`).

> that actually means, the anchors are set with and without a wildcard

Why? These examples all include wildcards.

> `$('state[state.id=javascript.**?**.watering.duration]')`

You don't have a state that includes a `?` so what should this match?

> `$('state[state.id=javascript.**\***.watering.duration]')`

You don't have a state that includes a `*` so what should this match?

**Comment by AlCalzone** [comment]
Labelling this as "working as intended" unless you provide an example that is not.

**Comment by truegreyhound** [comment]
"**?** - in the preview I saw this as bold star, it should be ?, also **\*** should be *

I have rechecked this on an other machine, yes `*`works and with the knowledge `*` is the only allowed wildcard, it's work as intendes.
