### ISSUE TITLE
scriptEnabled-Datenpunkte werden nicht zuverlässig gelöscht

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#680]
**Describe the bug**  
Es kann vorkommen, dass scriptEnabled-Datenpunkte übrig bleiben, obwohl die zugehörigen Skripte nicht mehr existieren. Beispiel:
![grafik](https://user-images.githubusercontent.com/17641229/96490897-c1e33800-1241-11eb-8767-2fae2d2d8ba8.png)

**To Reproduce**  
nicht sicher

**Expected behavior**  
scriptEnabled-Datenpunkte sollten gelöscht werden, wenn ein Skript gelöscht wird. Mindestens beim Neustart könnte man prüfen, ob unnötige DPs (ohne zugehöriges Skript) vorhanden sind und diese löschen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 4.9.3 (github version)
 - JS-Controller version: 3.1.5
 - Node version: 12.19.0
 - Operating system: Windows 10

**Comment by Apollon77** [comment]
could be retested once https://github.com/ioBroker/ioBroker.javascript/pull/964 is merged
