### ISSUE TITLE
Running `gulp` deletes the `admin/vs` dir

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#683]
I noticed this because I wanted to update `monaco-editor` to a version that supports `setExtraLibs`. To reproduce:
1. check out the branch from https://github.com/ioBroker/ioBroker.javascript/pull/684
1. run `gulp monaco-update --version=0.21.2`
2. notice that there are many changed files in `admin/vs`
3. run `gulp`
4. notice that most (all) of the changed files are now missing

**Comment by GermanBluefox** [comment]
The version of monaco-editor must be set to 0.21.2 too:
https://github.com/ioBroker/ioBroker.javascript/blob/master/src/package.json#L15
