### ISSUE TITLE
[AdminV3] Script Log empty

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.javascript#69]
under Scripts in Admin log is everytime empty:
![image](https://user-images.githubusercontent.com/12692680/35696460-d6ff4e1c-0787-11e8-9797-7e238b25c691.png)

Used:
Admin 3.1.6
Javascript 3.6.1

This was working properly under Admin Version 2.x.

**Comment by AlCalzone** [comment]
I can confirm. After a fresh reboot, it works, but sometime along the way it starts to break.

**Comment by roe19xx** [comment]
I can confirm too with Admin Adapter 3.2.3 (and Javascript Adapter 3.6.4)

**Comment by peterbaumert** [comment]
Can confirm, was driving me nuts that my script is broken till I realized its the log :D

**Comment by Hypnos3** [comment]
seems to work now
