### ISSUE TITLE
Blockly 4.9.4: In Blockly definierte Funktionen haben kein `async` Keyword

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.javascript#691]
Hier wird in der Version 4.9.4 ein "compile failed" beim Blockly Start gemeldet. Mit 4.6.26 läuft das Blockly. 
Hier der Forum Link mit Fehlerbeschreibung (und einige folgende Beiträge)

https://forum.iobroker.net/post/510192

**Comment by AlCalzone** [comment]
Problem gefunden. Blockly-Funktionen generieren Code wie diesen:

```js
function Batterien_voll_leer_zaehlen() {
  // ^ kein `async`
  liste_Batterien_aktiv_voll_leer.push(String(await getParentName(Batterien_aktiv_voll_leer)) + ' fast leer');
  // ^ Man achte auf das `await`
  // ...
}
```

**Comment by GermanBluefox** [comment]
> Blockly-Funktionen generieren Code wie diesen:

Eigentlich nicht: 
```
// Beschreibe diese Funktion …
async function objectFromID(id) {
    return getObject(id);
}
```

**Comment by AlCalzone** [comment]
Ich konnte es mit dem im Forum bereit gestellten Skript unter 4.9.4 reproduzieren. Oder hattest du das schon im master geändert?

**Comment by GermanBluefox** [comment]
Kannst du die mir exportieren? Als XML?

**Comment by AlCalzone** [comment]
Hab ich :) Link ist im letzten Post

**Comment by AlCalzone** [comment]
@GermanBluefox fixed in 4.9.7?

**Comment by GermanBluefox** [comment]
Sollte jetzt gefixt sein.

**Comment by dslraser** [comment]
mit 4.9.7 habe ich keine Fehlermeldung mehr. Das Blockly macht was es soll

**Comment by sigi2345** [comment]
Kann ich bestätigen.
