### ISSUE TITLE
Function calls don't work anymore from Blockly

### ISSUE THREAD

**Issue by mediaDS** [ioBroker/ioBroker.javascript#693]
**Describe the bug**  
Parameters have been deleted from all function calls. This happened after updating to 4.9.7 - everything worked perfectly before.

**To Reproduce**  
this has been described with screenshots here:
https://forum.iobroker.net/topic/38103/javascript-funktionen-ergeben-undefined

**Expected behavior**  
i.e. a function call to getcolor(new,old) has been set to getcolor() - deleting the parameters. So the functions only return undefined.

**Screenshots & Logfiles**  
https://forum.iobroker.net/topic/38103/javascript-funktionen-ergeben-undefined

**Versions:**  
 - Adapter version: 4.9.7
 - JS-Controller version: 3.1.6
 - Node version:  12.19.0
 - Operating system: Linux Arm64

**Comment by mediaDS** [comment]
Additional information:

Even after adding all the parameters by hand all(!) function calls return _undefined_. So something is very wrong there.

**Comment by Diginix** [comment]
I have the same problem with 4.9.7. Rollback to 4.9.4 and all blockly scripts with functions are working again.

Some screenshots that may help:
![2020-10-29_blockly_function_issue](https://user-images.githubusercontent.com/39678667/97635005-f2438700-1a36-11eb-9bbe-e79b5c524b39.jpg)
![2020-10-29_blockly_function_issue3](https://user-images.githubusercontent.com/39678667/97635039-ff607600-1a36-11eb-9dcd-fde8e4e708ca.jpg)

Somehow the variable definition is broken.

`var ausgabe, echos, ssml;

// Beschreibe diese Funktion …
async function Alexa(ausgabe, echos, ssml) {
  setState("alexa2.0.Echo-Devices.G090U50984841UJE.Commands.announcement"/*announcement*/, ausgabe);
}


await Alexa();
`

**Comment by sbormann** [comment]
Same for me. Even simple function calls are broken (in fact they are called withour their arguments: await alexa();)

**Comment by Zefau** [comment]
Same for javascript functions stored in `global` and called from `common`.

**Comment by mediaDS** [comment]
There was an update today to 4.9.8 - did this fix the problems?

(I wonder why there is no communication from the dev(s) here)

**Comment by MCepheus** [comment]
I've had the same problem since this morning. Today the shutters didn't work anymore.
Error message in the log: script.js.Haus.OG.Rolladensteuerung_OG: setForeignState: undefined is not a valid state value

Yesterday everything worked without complaint.
I installed the 4.9.8.

Is it either a problem with the functions or the variables are not passed correctly?

**Comment by mediaDS** [comment]
In other words - the bug (a real showstopper) is still in there with the latest 4.9.8. Thank you for cleraring that up. I wonder when there will be a working update.

**Comment by Diginix** [comment]
@mediaDS: Be patient and do a rollback to 4.9.4 and all is working without missing something.
Latest repo is beta and there is no claim for anything.

**Comment by mediaDS** [comment]
That's what I did, of course. And yes, there is no claim for anything, no need to lecture me about that :) Good luck and have fun.

**Comment by Diginix** [comment]
If you know all that then you should also know that all is volunteer work of the devs. In this case there is a rule: If you don't pay for it, don't ask for ETA. ;-)

**Comment by mediaDS** [comment]
Point taken ;)

**Comment by MCepheus** [comment]
That wasn't my intention either.
For me it was just about identifying and narrowing down a source of error.
I think it is clear that everyone here appreciates the work that is done voluntarily.

**Comment by GermanBluefox** [comment]
Fix will be done tonight

**Comment by mediaDS** [comment]
Works. Thank so much.
