### ISSUE TITLE
Icons im Suchen-Dialog fehlen

### ISSUE THREAD

**Issue by Harry-58** [ioBroker/ioBroker.javascript#697]
Im Javascript-Editor werden im Suchen-Dialog (ctrl-F) keine Icons angezeigt.

![iobroker_suche](https://user-images.githubusercontent.com/56926733/97842703-53de4c80-1ce8-11eb-9793-22ab27c48c0d.jpg)

Egal mit welchem Browser (Firefox, Chrome auf Win10 oder Chrome auf Android), es fehlen immer die Icons. 

**Versions:**  
 - Adapter version:  Javascript 4.9.8   (alles auf aktuellem Stand aus latest)
 - JS-Controller version: 3.1.6
 - Node version: v12.19.0
 - Operating system: linux (Rasberry pi4 auf aktuellem Stand)

**Comment by pepp86** [comment]
Same here. All icons are missing

Adapterversion 4.9.8
JS-Controller 3.1.6
node 12.18.3
OS: Ubuntu 20.04.1 LTS

**Comment by GermanBluefox** [comment]
Cannot reproduce. Can any one from devs see that?

**Comment by Ilovegym66** [comment]
yes, here with Adapter 4.9.8, js-controller 3.1.6, node 12.19.0, debian 10, lxc.
![grafik](https://user-images.githubusercontent.com/36229898/98099766-406de580-1e90-11eb-9920-583a9af3ca89.png)

auch mit anderem Style in Hell:
![grafik](https://user-images.githubusercontent.com/36229898/98099889-6a270c80-1e90-11eb-93c9-a581f1e75cc2.png)

**Comment by Harry-58** [comment]
Ich habe zum Test ein altes iobroker-backup (komplettes Image) geladen.
Adapter version: Javascript 4.5.1 
Node version: v10.20.1

Damit werden die Icons richtig angezeigt.
Allerdings auf eine andere Art als in der aktuellen Version, nämlich als svg-Hintergrundimage:
![io1](https://user-images.githubusercontent.com/56926733/98108103-c3e10400-1e9b-11eb-9c9e-a9a7b9ef7fa9.jpg)

In der aktuellen Version werden die Icons über css-content und den entsprechenden Unicode angezeigt:
![io2](https://user-images.githubusercontent.com/56926733/98108217-e6731d00-1e9b-11eb-9ed6-076397cc1706.jpg)
Wenn auf dem Rechner kein Zeichensatz installiert ist, der den Unicode kennt, wird auch das Icon nicht dargestellt.
Ich habe jetzt auf 3 Rechnern (2x Win10-Pro und 1x Win10-Home) und auf einem Tablet mit Android V8 getestet.
Auf keinem ist der entsprechende Zeichensatz installiert.

Laut dieser Tabelle: [https://unicode-table.com/de/#private-use-area](url)
wird der Bereich "E000-F800" als "Private Use Zone" bezeichnet. Es ist also höchst unwahrscheinlich, dass der entsprechende Zeichensatz auf einem Rechner installiert ist.
Wenn UTF-Codes aus dem Bereich 2190-21FF (Pfeile)  verwendet würden, würden die Icons sicher auf allen PC angezeigt werden.

**Comment by GermanBluefox** [comment]
Please check 4.10.1

**Comment by Harry-58** [comment]
Auch in 4.10.1 fehlen die Icons

**Comment by Ilovegym66** [comment]
same with 4.10.2

![grafik](https://user-images.githubusercontent.com/36229898/98270945-b2792400-1f8f-11eb-95d6-bbd335719fdd.png)

**Comment by GermanBluefox** [comment]
You get this error if you run out of memory when loading the fontfile or if there is something wrong with the layout (contents) of the fontfile. This is a protection against bad or malicious font files. It is probably possible to disable the sanitizer by setting the pref gfx.downloadable_fonts.sanitize to false in about:config but then you are no longer protected. Use at your own risk.

**Comment by SliX185** [comment]
Dosen't matter wich browser you use...  using 4.10.2
Chrome:
![codeicon2 png](https://user-images.githubusercontent.com/47434006/98450048-89949280-2139-11eb-8992-ec88da1e1ecb.jpg)
What's wrong with the codicon.ttf file?

**Comment by Harry-58** [comment]
Die vorgeschlagene Lösung mit Wert in config:about funktioniert nicht. (Firefox 82.0.2)
Den Paramter "gfx.downloadable_fonts.sanitize" gibt es nicht. Auch wenn ich ihn manuell anlege keine Änderung.
Es gibt einen ähnlichen Parameter "gfx.downloadable_fonts.sanitize_omt", aber auch damit keine Änderung!
Ich habe auch jedes mal den Cache gelöscht und neu gestartet.
Und wie "SliX185" ja schreibt tritt der Fehler auch bei Chrome auf.
Es scheint also wirklich die codicon.ttf fehlerhaft zu sein.
![grafik](https://user-images.githubusercontent.com/56926733/98459023-bc20a880-2196-11eb-883c-d44fe50725ca.png)

Es hat ja in älteren Versionen (siehe oben) funktioniert! Warum wird nicht wieder auf die alte Lösung zurück gegangen?

**Comment by Ilovegym66** [comment]
hier nachvollziehbar, auch in Chrome und Edge ist der Fehler, nicht nur in Firefox.

**Comment by SliX185** [comment]
Gehts in Deutsch oder Englisch weiter?!

@GermanBluefox Welchen Browser benutzt du?
Ist die codicon.ttf von VSCode oder? 
Hab gerade die codicon.ttf von [https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf](url)
auf mein System nachinstalliert und nun geht's in Chrome (und Edge /Chromium Basis) 
Firefox, was ich normal benutze, funktioniert trotzdem nicht.

Fakt ist, die codicon.ttf vom Adapter hat irgend ein Problem.

**Comment by Harry-58** [comment]
Habe jetzt mit 3 verschiedenen codicon.ttf getestet
61.018 codicon.ttf-iobroker
61.944 codicon.ttf-vscode
62.324 codicon.ttf-winFonts
Vorne steht die jeweilige Dateigröße, hinten habe ich die Herkunft angehängt.
Kopiert und wieder in den codicon.ttf umbenannt habe ich die Dateien in den Ordner
/opt/iobroker/iobroker-data/files/javascript.admin/vs/base/browser/ui/codicons/codicon/
Mit allen 3 Dateien fehlen die Icons.
Auf meinem Win-Rechner in vs-code werden im Suchendialog die Icons richtig angezeigt.

**Comment by SliX185** [comment]
@GermanBluefox 
Probier einfach mal im repo 
[https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf](https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf) 
die ttf zu öffnen, du wirst einen Fehler bekommen.
Jedoch kannst du 
[https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf](https://github.com/microsoft/vscode-codicons/blob/master/dist/codicon.ttf)
diese öffnen.
@Harry-58 
Es gibt noch weitere Speicherorte von codicon.ttf, jedoch hab ich schon alle ersetzt und es funktioniert mit Firefox trotzdem nicht ?!?

![Screenshot 2020-11-08 140927](https://user-images.githubusercontent.com/47434006/98465849-230c8480-21cc-11eb-8733-93ed7e82d6f2.jpg)

**Comment by Harry-58** [comment]
@SliX185
Die anderen Speicherorte habe ich auch ausprobiert.
Aber nur der Speicherort
 /opt/iobroker/iobroker-data/files/javascript.admin/vs/base/browser/ui/codicons/codicon/
scheint relevant zu sein. 
Getestet, indem ich codicon.ttf zunächst gelöscht habe. Nur wenn ich in obigem Ordner lösche wird die ttf nicht mehr gefunden.

**Comment by Harry-58** [comment]
Habe auf 4.10.3 aktualisiert.
Damit sind die Icons wieder vorhanden.
Danke GermanBluefox für die Problemlösung

**Comment by SliX185** [comment]
@Harry-58 
Bei Dir funktioniert's?
Hab leider keine Änderung, obwohl offensichtlich die ttf ausgetauscht wurde...

[https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true](https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true)

Kannst du die ttf mit Windows öffnen? oder kommt ein Fehler?

**Comment by Ilovegym66** [comment]
bei mir auch keine Änderung mit der 4.10.3, sorry.. :-(
weder mit Chrome, Firefox, Edge.. Cache gelöscht, Upload des Adapter gemacht, gewartet, bis er mit allem durch war.. hmm 

![grafik](https://user-images.githubusercontent.com/36229898/98472491-b3aa8b00-21f3-11eb-93d5-4b1656c5ed6d.png)

**Comment by SliX185** [comment]
@GermanBluefox 
leider reicht ein "reupload" der funktionierende ttf anscheinend nicht?!

Hab gerade geforked, im fork ttf upload und ersetzt = keine Änderung!

Danach die ttf aus den repo gelöscht und danach nochmal upgeloaded, jetzt funktioniert es wie es soll...
Warum auch immer?!

Zum testen:
Mein Fork:
[https://github.com/SliX185/ioBroker.javascript/blob/master/src/public/vs/base/browser/ui/codicons/codicon/codicon.ttf](https://github.com/SliX185/ioBroker.javascript/blob/master/src/public/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true)
Ohne Fehlermeldund beim öffnen

main repo:
[https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf](https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true)
Kann nicht geöffnet werden.

**Comment by Harry-58** [comment]
@SliX185
Die ttf aus deinem Fork kann geladen werden.
Beim laden der ttf aus "main" kommt in der Konsole folgende Meldung:
![grafik](https://user-images.githubusercontent.com/56926733/98506804-9bbb2180-225c-11eb-853a-88a438330564.png)

**Comment by SliX185** [comment]
@GermanBluefox 
Danke für's mergen...., aber der Spaß funktioniert trotzdem nicht. Bei mir im Fork dagegen schon.
Ich glaube Github löscht die codicon.ttf nicht richtig?! Nur wenn die Datei manuell gelöscht wird und nochmal hochgeladen wird.

**Comment by SliX185** [comment]
@GermanBluefox
Ich will wirklich nicht lästig sein, weil es sicher andere Sachen zu erledigen gibt... 
Und zudem sind die Leute mit dem genannten issue sicher nicht viele (Firefox User + aktuellen Adapter)
Aber die .ttf funktioniert leider so immer noch nicht. (immer noch ein Fehler beim öffnen der Datei)
Ich wäre sehr dankbar, wenn das noch gefixed werden würde.
