### ISSUE TITLE
"variables.isDayTime" funktioniert nicht wie erwartet?

### ISSUE THREAD

**Issue by SliX185** [ioBroker/ioBroker.javascript#699]
Hallo,
leider funtkioniert bei mir die Variable "isDayTime" vom Adapter nicht richtig?!
Astro Einstellungen wurden im Adapter konfiguriert. Hab heute mal kurz geloggt und sah,
`
2020-11-02 06:54:57.004  - info: javascript.0 (31232) script.js.common.Test.#TEST2: ##### ----isDayTime = true
2020-11-02 06:55:00.005  - info: javascript.0 (31232) script.js.common.Test.#TEST2: ##### ----isDayTime = false`

dass nach 3 sek. die Variable wieder auf "false" geht...
So bleibt Sie dann den ganzen Tag, bis zum nächsten SunriseEvent, wo dann das selbe abläuft.

Mach ich was falsch, oder läuft was falsch, oder verstehe ich was falsch?
Ich denke "isDayTime" sollte von sunrise bis sunset auf "true" stehen oder?

Danke im Voraus.

![Astro](https://user-images.githubusercontent.com/47434006/97907375-7ce0fa80-1d45-11eb-92f0-ec698ca8d484.jpg)

**Versions:**  
 - Adapter version: 4.8.4
 - JS-Controller version: 3.1.6
 - Node version: 12.18.1
 - Operating system: ubuntu

**Comment by GermanBluefox** [comment]
Bitte mit 4.10.0 nachtesten

**Comment by SliX185** [comment]
@GermanBluefox 
Danke, ich log morgen nochmal mit.

...allerdings hab ich jetzt auch das issue #697 und keine Symbole mehr
![codeicon](https://user-images.githubusercontent.com/47434006/98159891-a03ead80-1edd-11eb-8fff-37e440e414d1.png)

**Comment by SliX185** [comment]
@GermanBluefox 

close
