### ISSUE TITLE
[Future] Support coffeescript v2 (requires NodeJS 6+)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#70]
Installing outputs the following warning:
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```
However we cannot just switch the package name because https://github.com/alexgorbatchev/coffee-compiler also has the old module dependency. 
Do you know if there's a possibility to tell NodeJS to actually load "coffeescript" when requiring "coffee-script"? If so, we could support CoffeeScript v2.

Of course we could just fork the coffee-compiler, change the dependency and use our fork - but I'm not sure if that's worth the effort.

**Comment by GermanBluefox** [comment]
No. I don't know if this possibility exists.

2018-02-02 13:03 GMT+01:00 AlCalzone <notifications@github.com>:

**Comment by Apollon77** [comment]
Yes,  you could use https://www.npmjs.com/package/mock-require ... I use this to moch ak´wy serialport with virtual-serialport in some tests for my libraries ... so it is meaned to be used for such, but should work here too.

```
var mock = require('mock-require');
mock('coffee-script', 'coffeescript');
```

... could work if you want to "force" it

**Comment by Apollon77** [comment]
Do you asked the owner of coffee-compiler to update the dep or at least prepare an PR :-)) sometimes the easiest way

**Comment by AlCalzone** [comment]
That package was last updated 4-5 years ago, I didn't even bother ;)
Rewiring the require also wouldn't change anything because that package still has `coffee-script` as a dependency.
I guess I'll file this under _never change a running system_.

**Comment by WolfspiritM** [comment]
Just saw that...I don't really care about coffeescript but:
I'm wondering...why even bothering using that old compiler at all?
According to the coffeescript docs the official coffeescript package can do pretty much the same...
```js
let CoffeeScript = require('coffeescript');
let js = CoffeeScript.compile(obj.common.source, { sourceMap: false, bare: true });
```
Should be similar to:
https://github.com/ioBroker/ioBroker.javascript/blob/37e7dc2ace81b1862d1bff124d9c24ee4f9594f4/javascript.js#L435-L438

Just not in an async way but I doubt that compiling the code can be done async anyway...

**Comment by AlCalzone** [comment]
Hmm, that looks very similar indeed. Not sure if the v1 version could not do that or why the additional package was necessary. Maybe I'll give it a 2nd look.

**Comment by AlCalzone** [comment]
coffeescript v2 requires at least NodeJS 6, so this is on hold until we drop support for NodeJS 4.

**Comment by AlCalzone** [comment]
Now that we have dropped support for NodeJS 4, do you guys think we should pursue this issue further?

**Comment by GermanBluefox** [comment]
I think that it is OK

сб, 9 июн. 2018 г., 13:48 AlCalzone <notifications@github.com>:

**Comment by Apollon77** [comment]
Just to say it: did we really dropped Support officially? For latest repo I think yes ;-))
Stable we still need to communicate and such

**Comment by GermanBluefox** [comment]
I removed coffeescript
