### ISSUE TITLE
async functions cannot access script scope

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#705]
**Describe the bug**  
@AlCalzone, you probably know what needs to be done. Consider this:

```ts
const foo = 42;

async function bar():Promise<void> {
    return new Promise<void>(() => log(foo.toString()));
}

await bar();
```

```
2020-11-06 19:50:21.803 - error: javascript.0 (21621) script.js.Script_1: TypeScript compilation failed:
--
return new Promise(() => log(foo.toString()));
^
ERROR: Cannot find name 'foo'.
```

This fails with the same error:

```ts
const foo = 42;

async function bar() {
    log(foo.toString());
}

await bar();
```

Thanks!

**Comment by agross** [comment]
If you do not `await` `bar` the script compiles.

**Comment by AlCalzone** [comment]
I'll have to check how the transformed script looks like. Thanks for the report

**Comment by AlCalzone** [comment]
This is the transformed script:
```ts
async function bar(): Promise<void> {
    return new Promise<void>(() => log(foo.toString()));
}
(async () => {
    const foo = 42;
    await bar();
})();
export {};
```
We currently don't wrap the function statements, because you couldn't use functions from global scripts if they are inside the async wrapper. I'll change this behavior for non-global scripts.

**Comment by agross** [comment]
Thank you, the issue has been fixed.
