### ISSUE TITLE
Skript lässt sich nicht löschen/stoppen/umbenennen

### ISSUE THREAD

**Issue by Paulehst40** [ioBroker/ioBroker.javascript#707]
Hallo, kann ein Skript nicht stoppen/löschen/umbenennen. 

![Unbenannt-2](https://user-images.githubusercontent.com/44838931/98482969-2f610380-2205-11eb-854d-0cb002f7d2d9.jpg)

**Comment by GermanBluefox** [comment]
Please provide more information. 
May be Browser console outputs?

**Comment by Paulehst40** [comment]
Okay, here is the Console Output.

![Unbenannt-2](https://user-images.githubusercontent.com/44838931/98579202-92fb3780-22be-11eb-848f-ec93f8730770.jpg)

**Comment by GermanBluefox** [comment]
What is shown under the arrow?
![image](https://user-images.githubusercontent.com/4582016/99180267-ffde5980-2724-11eb-832b-0a4651bf9d99.png)

**Comment by Paulehst40** [comment]
![Unbenannt-2](https://user-images.githubusercontent.com/44838931/99274714-ee7f7500-282a-11eb-912a-6ce34ca32967.jpg)

**Comment by Paulehst40** [comment]
The point at the end is the problem, right? But how can I rename the script now?

**Comment by Paulehst40** [comment]
No Idea?
