### ISSUE TITLE
Kommentar mehr Zeichen erlauben

### ISSUE THREAD

**Issue by MCepheus** [ioBroker/ioBroker.javascript#712]
Hi, erst einmal herzlichen Dank für dieses tolle Tool, ohne das viele sicher nicht so einen einfachen Einstieg in die Skriptprogrammierung haben würden!
Es gibt aber eine Sache die mich immer wieder stört. Ich schreib gerne etwas ausführlichere Kommentare in die Skripte. Ihr habt da scheinbar 50 Zeichen für vorgesehen. Diese übersteige ich dann schon mal - meist nur um ein paar Zeichen. Der Kommentar erscheint dann natürlich nur abgeschnitten im Feld und ist auch dann erst lesbar wenn man ihn zum editieren auswählt.
Gibt es hier vielleicht die Möglichkeit mehr Zeichen zuzulassen oder einen automatischen Zeilenumbruch zu aktivieren oder den kompletten Text beim Überfahren des Kommentars mit dem Mauszeiger anzeigen zu lassen?
Das hat keine Dringlichkeit, die Funktionalität ist ja gegeben. Wäre nur ein "nice to have".
Gruß
MCepheus

**Comment by GermanBluefox** [comment]
Um Welche Kommentare geht es? Blockly, JS Skript?

**Comment by MCepheus** [comment]
Hi, ich meine den gelben Kommentarblock unter Blockly.

**Comment by ckoop** [comment]
Das kann ich nur bestätigen. Gerade bei umfangreichen Blockyskripten ist die Kommentarfunktion die einzige Möglichkeit, aus meiner Sicht, das Script zur dokumentieren.

**Comment by matthias882** [comment]
Schade dass bei diesem Problem nicht weiter gemacht wurde. Ich finde es auch jedes mal blöd die Kommentare so kurz zu halten. Ausführliches kommentieren ist das A und O einer übersichtlichen Programmierung...

**Comment by Diginix** [comment]
@matthias882 Als workaround einfach weiter Kommentar Blöcke nutzen. Oder meinst du die Kommentarfunktion jedes Blockes?
Tipp: In javascript kannst du unbegrenzt kommentieren. ;-)

**Comment by Diginix** [comment]
Dann ist die Kommentarfunktion des Funktionsblockes der Workaround. Die Sprechblase davon kannst du in Breite und Höhe skalieren und bei Bedarf auch minimieren um die Übersicht zu bewahren.

**Comment by matthias882** [comment]
@Diginix Jawoll, die Block-Kommentarfunktion hatte ich bisher wirklich noch nicht gekannt und auch noch nirgends gesehen. Perfekt! Vielen lieben Dank für den Hinweis!
