### ISSUE TITLE
Fehlermeldung Fritzbox.

### ISSUE THREAD

**Issue by McWoolf** [ioBroker/ioBroker.javascript#716]
Hallo Leute!

Ich habe heute meine Heizungssteuerung mittels blockly erstellt.
seitdem bekomme ich immer Fehlermeldungen der Fritzbox und habe auch kontrolliert ob die Benutzerangaben passen.
Dennoch zeigt auch die FB  dass die Anmeldung zurückgesetzt wurde.
Vielleicht kann mir hier ja jemand einen Tipp geben, was ich falsch gemacht habe.
Danke schon mal für eure Unterstützung.

[script.txt](https://github.com/ioBroker/ioBroker.javascript/files/5565083/script.txt)
![blockly](https://user-images.githubusercontent.com/73942255/99634721-41cb1080-2a41-11eb-9d7d-979347eeb4d8.PNG)
[error.txt](https://github.com/ioBroker/ioBroker.javascript/files/5565084/error.txt)

**Comment by Apollon77** [comment]
Bitte solche Fragen im Forum stellen!
Ggf waren es ziuviele ANfragen - dann sperrt die FB gern auch maluser
