### ISSUE TITLE
Accessing multidimensional array lead to error

### ISSUE THREAD

**Issue by KnallerRaphael** [ioBroker/ioBroker.javascript#717]
The multidimensional array that i defined is somewhat broken. I can use `log()` to print the values out in the console and they are there, but right after the log i get an error.

Here the code:
```javascript
//Array
var array= [
    [6, 22],
    [6, 22],
    [6, 22],
    [6, 22],
    [6, 22],
    [6, 22],
    [6, 22]
];
for(var i = 1; i <8; i++){
log(array[i][0]);
}
```

The log:
javascript.0 (5263) script.js.Skript_1: 6
javascript.0 (5263) at script.js.Skript_1:49:48

 - Adapter version: 4.8.4
 - JS-Controller version: 4.0.10
 - Node version: v12.18.4
 - Operating system: Ubuntu

I know that the problem is the second array with the index of 0, but i don't see a problem with that.

**Comment by Apollon77** [comment]
Hm ... you have an array with 7 entries ... they start with index 0 and you count from 1..8 ... means at index 7 you access [0] of undefined ...

**Comment by KnallerRaphael** [comment]
Thank you. I realy messed something up. My original code for the script was different, but the mistake with "i < 8" was the problem. The original began with i = 0. The log was from my original code.
