### ISSUE TITLE
Regression (?): Global TS constants/functions are not defined in JS scripts

### ISSUE THREAD

**Issue by zaunermax** [ioBroker/ioBroker.javascript#721]
**Describe the bug**  

I seem to have the same problem as in #687 again :thinking: 

After upgrading to the latest scripting engine, all my scripts broke again. However by migrating them to JavaScript files, i got my scripts working again.

**Expected behaviour**

all defined constants/functions in global typescript files should be defined in other scripts.

**Versions:**  
 - Adapter version: 4.10.5
 - JS-Controller version: 3.1.6
 - Node version: 10.20.0
 - Operating system: docker - debian

**Comment by AlCalzone** [comment]
Please show an example of affected scripts so I can check :)

**Comment by zaunermax** [comment]
Like in my previous issue my actions to reproduce are:
- Create TS script in global folder
- Create a `const foo = 'foo'` and a `const testFn = () => console.log('test')` in the test ts script
- Try to reference `foo` and `testFn` in any other js script

Maybe it's a TS to JS issue? :thinking: Because my other scripts are not TS, only my global scripts

**Comment by zaunermax** [comment]
Never mind, I tried it once again and now I cannot reproduce it, sorry for bothering you.

If I encounter the problem again, I try to find out how it is reproducible.
