### ISSUE TITLE
getting state of function group does not seem to work 

### ISSUE THREAD

**Issue by zokkai** [ioBroker/ioBroker.javascript#739]
Iobroker 3.1.6
Node 12.20.0
Java Script Engine. 4.10.8
Raspberry4 
Blockly 

After updating to version 4.10.x state updates on feature groups by "IDs from selector $" does not seem to work anymore.

in Blockly 
![image](https://user-images.githubusercontent.com/49320831/103001296-ff5b8e80-452c-11eb-8373-091bb72903e1.png)

here the the relevant code 

on({id: Array.prototype.slice.apply($("state[id=opened](functions=fenster)")), change: "ne"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  console.log('Wert Fenster geändert ');

**Comment by MeisterTR** [comment]
kann ich bestätigen

**Comment by MeisterTR** [comment]
hab jetzt mal downgegraded. die letzte version´vo es geht ist die 4.8.4

**Comment by zokkai** [comment]
in der Konfiguration scheint man auch generell keine neuen Aufzählungen anlegen zu können.

**Comment by zokkai** [comment]
[state.id=*opened](functions=fenster)

damit funktioniert es jetzt wieder. keine ahnung, warum der * so wichtig ist.
