### ISSUE TITLE
[Typings] check signature of createState

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#74]
http://forum.iobroker.net/viewtopic.php?p=122624#p122624

**Comment by Apollon77** [comment]
Siehe auch meine frage als pn von vorhin.  War auch createstate betroffen

**Comment by Apollon77** [comment]
Details: Und mit code:


```
    createState('javascript.' + instance + '.Multimedia.Steuerung.' + logic, {'type': 'boolean', 'read': true, 'write': true, 'role': 'button', 'def': false}, function(err, id) {
});

```
kommt als Fehler: Argument of type '(err: any, id: any) => void' is not assignable to parameter of type 'boolean'.
