### ISSUE TITLE
Feature request: Mirroring ignore files / folders

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.javascript#744]
An option to ignore files and folders from the mirroring option would be nice.

Background is, that i created a git repository in the mirrored folder, to handle changes of the single script files.
At the moment the .git folder will always be synced by the Mirroring.

**Comment by Apollon77** [comment]
Workarounf atm is to use a subdir in the repo so that .git is one level above :-)

**Comment by Scrounger** [comment]
> Workarounf atm is to use a subdir in the repo so that .git is one level above :-)

As always a very good tip from you, thanks :-)

**Comment by Apollon77** [comment]
For real fix would it be the way to not sync directories starting with "." in general?

**Comment by Scrounger** [comment]
yes for example. Or add an input field, where the user can define files / folders by his own.
E.g. i have jsconfig.json and *.code-workspace files in the script folder, because i us vs code for the scripts

**Comment by GermanBluefox** [comment]
It is strange, because all folders starting with '.' will be ignored: https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/mirror.js#L64

**Comment by Apollon77** [comment]
yes but not on watch

https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/mirror.js#L77-L79
