### ISSUE TITLE
Copy issue with "date and time" block in blockly

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.javascript#745]
Node.js v12.20.0
NPM 6.14.8
Script engine 4.10.8

See the picture:

![image](https://user-images.githubusercontent.com/47712364/104104185-d1a17400-52a6-11eb-9059-b570128d09be.png)

When I copy this "date and time" block I get and GUI issue while the JS is correct:

`if (compareTime('08:00', '23:59', "between", null)) {
}

compareTime('08:00', '23:59', "between", null);
`

When I switch to another script and back to this one it is ok again:

![image](https://user-images.githubusercontent.com/47712364/104104358-c864d700-52a7-11eb-870f-8b4f0be9b529.png)

But in my case it is reproducable in several scripts...

**Comment by unstressable** [comment]
have this issue too.
It just happens by copying with CTRL+C. If you copy with the Block with the export/import option menu it does not appear.

**Comment by GermanBluefox** [comment]
This is bug from google. I am not able to fix it myself.
