### ISSUE TITLE
Scheduld 0 0 doesn't work with 4.10.9

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.javascript#748]
`
schedule('0 0 * * *', function () {
});
`

funktioniert scheinbar seit der neuesten Release 4.10.9 nicht mehr.
Ich hätte da einige Sachen die um diese Zeit abgearbeitet werden sollen, aber nichts passiert. Auch die Heizungssteuerung geht nicht. um 00:05 zb funktioniert es schon wieder.
Ist jetzt die 2te Nacht hintereinander
Achja und in den Logs ist absolut nichts zu sehen davon. 

![1610779584767-adbb9ed2-de48-44ab-a9ab-4ae68cafb012-image](https://user-images.githubusercontent.com/43374575/104808285-6e9f6800-57e5-11eb-922b-38cd1ddda212.png)

**Comment by Steff42** [comment]
Hmm...
...habe auch die 4.10.9 am laufen und mehrere Schedule die um 0:00 Uhr triggern, die funzen aber alle.
Werde aber mal heute Nacht genauer schauen und morgen berichten.

**Comment by homecineplexx** [comment]
ich hab jetzt schon die 2te Nacht, wo kein einziger meiner greift

**Comment by Steff42** [comment]
Komisch,
habe jetzt mal genauer geschaut, also meine Schedule gehen alle.
