### ISSUE TITLE
"Error while checking script folders for id xxx is: null " mit Adapterversion 4.10.11

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#750]
Seit dem Update auf Java Script Engine 4.10.11 kommt bei jedem Start der Instanz folgende Fehlermeldung

`javascript.0: Error while checking script folders for id "script.js.global.isTimeInRange": null`

Das Skript existiert
![grafik](https://user-images.githubusercontent.com/25422320/105615759-4d391000-5dd3-11eb-86b0-ceaa80be77a9.png)

Mit der Adapterversion 4.10.10 wird der Fehler nicht geworfen.

Versionen
js-controller 3.2.8
Java Skript Adapte 4.10.11

**Comment by Apollon77** [comment]
Yes and this is by intend because before there were potential crash cases ... I will enhance the error message a bit on next update, mabe we can then better analyze what heppens in general

**Comment by winnyschuster** [comment]
ich habe diese Meldung auch(nur eine Warnung für ein einziges Skript). Wenn ich dieses Skript jedoch in einen anderen Folder bewege, dann wird eine Fehlermeldung für das alphabetisch nächste Skript erzeugt(nur bei Instanzstart). Bewege ich das vorherige Skript zurück, verbleibt die Fehlermeldung aber beim letzten monierten Sript. Beim Move dieses Skriptes springt die Fehlermeldung dann zum nächsten, wie beschrieben. Vielleicht hilft das ja etwas

**Comment by Apollon77** [comment]
Bitte Fehlermeldung mit nächsten javascript adapter Update nochmals checken und posten, dann suchen wir mal :-)

**Comment by Apollon77** [comment]
... bzw für die Fälle mit "null" am ende ist die Meldung mit nächstem Update weg. War zuviel geloggt. Sorry

**Comment by Feuer-sturm** [comment]
Mit 4.10.13 tritt das Problem nicht mehr auf. 
Danke @Apollon77
