### ISSUE TITLE
Suchfunktion -> Grafikfehler

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.javascript#751]
Hi.
Wenn ich innerhalb eines Skriptes strg-F betätige dann erscheint das Suchfenster mit Grafikfehlern.
Das ist jetzt schon mehreren Versionen so.

![Suchfunktion](https://user-images.githubusercontent.com/17569151/105629220-02a2ac80-5e42-11eb-81b6-a97d00cea4f2.png)

Ich bin derzeit auf Version 4.10.13
Ich bin mir nicht mehr sicher aber ich glaube der Fehler kam mit einem großen Blockly-update

Gruß
Johnny

**Comment by ente34** [comment]
Von 4.10.6 nach 4.10.7 hat sich u.a die Datei node_modules\iobroker.javascript\admin\vs\base\browser\ui\codicons\codicon\codicon.ttf geändert
Benutzt man die Datei von 4.10.6 mit "iobroker upload javascript" sind die Icons beim Suchen/Ersetzen wieder da.
Ich habe natürlich KEINE Ahnung, ob dann an anderer Stelle Icons fehlen oder verändert sind
