### ISSUE TITLE
selector funktioniert nicht mehr in  Version V 4.10.13

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.javascript#752]
Ich benutze den Channel Selektor, um im Beispiel unten meine Echo Lautsprecher zu Parsen.
Der Code funktioniert mit V 4.8.3 mit V 4.10.13 nicht mehr. 
Der selector ist leer.

`  
var selector = $('channel[state.id=alexa2.0.Echo-Devices]');
   selector.each(function (id, i) {
   log("ID: " + id);
   });`

**Comment by Apollon77** [comment]
Bitte wie im Forum beschrieben Selector fixen.
