### ISSUE TITLE
jsonataExpression fails

### ISSUE THREAD

**Issue by ChristianH99** [ioBroker/ioBroker.javascript#753]
**Describe the bug**  
The jsonata function fails when used with blockly or JS

**To Reproduce**  
Create new script that uses jsonata
`var test = jsonataExpression('{"example": [{"value": 4},{"value": 7},{"value": 13}]}',"example[0].value"));
console.log(test);`
(Example from Docu)

**Screenshots & Logfiles**  
javascript.0 | 2021-01-29 21:44:28.628 | error | (2348) at processTicksAndRejections (internal/process/task_queues.js:97:5)
javascript.0 | 2021-01-29 21:44:28.628 | error | (2348) at runMicrotasks (<anonymous>)
javascript.0 | 2021-01-29 21:44:28.627 | error | (2348) at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
javascript.0 | 2021-01-29 21:44:28.627 | error | (2348) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
javascript.0 | 2021-01-29 21:44:28.627 | error | (2348) at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:616:17
javascript.0 | 2021-01-29 21:44:28.626 | error | (2348) at /opt/iobroker/node_modules/iobroker.javascript/main.js:1140:17
javascript.0 | 2021-01-29 21:44:28.626 | error | (2348) at /opt/iobroker/node_modules/iobroker.javascript/main.js:1559:17
javascript.0 | 2021-01-29 21:44:28.625 | error | (2348) at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1503:37)
javascript.0 | 2021-01-29 21:44:28.625 | error | (2348) at createVM (/opt/iobroker/node_modules/iobroker.javascript/main.js:1280:28)
javascript.0 | 2021-01-29 21:44:28.625 | error | (2348) at Object.createScript (vm.js:261:10)
javascript.0 | 2021-01-29 21:44:28.624 | error | (2348) at new Script (vm.js:88:7)
javascript.0 | 2021-01-29 21:44:28.624 | error | (2348) SyntaxError: Unexpected token ')'
javascript.0 | 2021-01-29 21:44:28.623 | error | (2348) ^
javascript.0 | 2021-01-29 21:44:28.623 | error | (2348) var test = jsonataExpression('{"example": [{"value": 4},{"value": 7},{"value": 13}]}',"example[0].value"));
javascript.0 | 2021-01-29 21:44:28.622 | error | (2348) script.js.test.test compile failed: at script.js.test.test:1

**Versions:**  
 - Adapter version: 4.8.4
 - JS-Controller version:  3.1.6
 - Node version: v12.20.1
 - Operating system: Raspbian

**Comment by Apollon77** [comment]
Naja, der Editor sollte den Fehler anzeigen oder? Du machstst eine "Klammer" zuviel Zug. EInfach ungültoges Skript

**Comment by ChristianH99** [comment]
Aah da hast du recht, hatte mich auch schon etwas gewundert. Aber das war wohl nur das Problem bei dem Skript, das ich extra als test angelegt habe. Tatsächlich ist das Problem nämlich gewesen, dass bereits des Editor die Funktion "jsonataExpression" nicht findet. Die wird dann auch rot markiet mit dem Fehler "Cannot find name 'jsonataExpression'".

Ich habe die Logs und den Befehl oben mal korrigiert.

**Comment by Apollon77** [comment]
Was ist denn jsonataExpression? EIn eigenes Moduls? Es ist kein nodejs standard

**Comment by ChristianH99** [comment]
So wie ich das sehe ruft die Funktion einfach nur die Standard Implementierung für JSONata auf
`jsonataExpression: function (data, expression) {`
`    return jsonata(expression).evaluate(data);`
`}`

https://github.com/jsonata-js/jsonata

**Comment by winnyschuster** [comment]
> Was ist denn jsonataExpression? EIn eigenes Moduls? Es ist kein nodejs standard

Das ist die Implementierung in Blockly und der Aufruf funktioniert auch mit dem im Editor gezeigten Fehler. Das 'Problem' hier ist die falsche Verwendung, der erste Parameter muss ein Objekt sein, kein String wie im obigen Beispiel

**Comment by ChristianH99** [comment]
![image](https://user-images.githubusercontent.com/13631551/106386983-ebcaff80-63d7-11eb-927c-a5e5120fae53.png)
Aber wie verwende ich den JSONata block denn dann richtig?

**Comment by winnyschuster** [comment]
> Aber wie verwende ich den JSONata block denn dann richtig?

indem du den Ausdruck zuvor in ein Objekt umwandelst
![jsonata](https://user-images.githubusercontent.com/7774086/106387404-d22ab780-63d9-11eb-8119-c586463c7c1b.PNG)

**Comment by ChristianH99** [comment]
Ja okay, ich verstehe.. Vielen dank!
