### ISSUE TITLE
Misleading sample code for getAstroDate()

### ISSUE THREAD

**Issue by neteddie** [ioBroker/ioBroker.javascript#754]
The sample code for function `getAstroDate()` in  ioBroker.javascript/docs/en/javascript.md contains the following lines:
```javascript
var today = new Date();
var tomorrow = today.setDate(today.getDate() + 1);
var tomorrowNigh = getAstroDate("night", tomorrow);
```
In my opinion this has the following disadvantages:

- The variable name `today` suggests that it holds today's date. This is not true: The `setDate()` method call in the initialization of variable `tomorow` **alters the underlying Date object** which was probably not intended.  
- The uniformity of the variable definitions suggests that both `today` and `tomorrow` are of same type. This is not true: `setDate()` returns the number of milliseconds between 1970-01-01 00:00:00 UTC and the modifed date. Therefore, while `today` is an object of type `Date`, `tomorrow` is simply a `number`.

I think that a thoughtless takeover of the sample code into new scripts could lead to hard to find errors and malfunctions.

I suggest the following as a replacement
```javascript
var today = new Date();
var tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate()+1);
var tomorrowNigh = getAstroDate("night", tomorrow);
```

While we're at it: Maybe the typo in `tomorrowNigh` could be changed as well. ;-)

**Comment by GermanBluefox** [comment]
Done
