### ISSUE TITLE
getSchedules

### ISSUE THREAD

**Issue by FNIO** [ioBroker/ioBroker.javascript#758]
**Describe the bug**  
getSchedules is not working

**To Reproduce**  
try to start example of functional discription

const list = getSchedules(true);
list.forEach(schedule => console.log(JSON.stringify(schedule)));

**Screenshots & Logfiles**  
see Sreenshot

LogFile:
![Screenshot 2021-02-14 165510](https://user-images.githubusercontent.com/69968778/107882004-4dff2680-6ee7-11eb-87e5-a0b109b315fd.png)

avascript.0 | 2021-02-14 17:06:48.020 | error | (2701)     at Script.runInContext (vm.js:130:18) -- | -- | -- | --
javascript.0 | 2021-02-14 17:06:48.019 | error | (2701)     at script.js.Auflistung_Scheduls:4:3
javascript.0 | 2021-02-14 17:06:48.018 | error | (2701)     at script.js.Auflistung_Scheduls:1:14
javascript.0 | 2021-02-14 17:06:48.017 | error | (2701)     at getSchedules (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1408:46)
javascript.0 | 2021-02-14 17:06:48.017 | error | (2701)     at Array.forEach (<anonymous>:null:null)
javascript.0 | 2021-02-14 17:06:48.016 | error | (2701)     at /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1409:53
javascript.0 | 2021-02-14 17:06:48.015 | error | (2701) script.js.Auflistung_Scheduls: TypeError: Cannot read property 'forEach' of undefined

**Versions:**  
  - JS-Controller version: 4.10.8
  -  Node version: v12.20.1
 - Operating system: docker container auf QNAP

**Comment by Apollon77** [comment]
should be fixed in 4.11.0
