### ISSUE TITLE
Script is not really stopped and object will not be destroyed (starting / stopping webserver requires to restart the adapter)

### ISSUE THREAD

**Issue by Boldie** [ioBroker/ioBroker.javascript#760]
**Describe the bug**  
If one will for e.g. add a webserver in the script the webserver will not be restarted nor stopped correctly.

**To Reproduce**  

Create the following JavaScript file and run / stop and rerun it:

```
const express = require('express');
const app = express();
app.listen(1111);
```

**Expected behaviour**  
Script is fully shut down and content is cleared.

**Screenshots & Logfiles**  

...
22:21:15.818 | info | javascript.0 (1885) Stop script script.js.common.TestStop

... Second round
22:21:16.640 | info | javascript.0 (1885) Start javascript script.js.common.TestStop
22:21:16.646 | info | javascript.0 (1885) script.js.common.TestStop: registered 0 subscriptions and 0 schedules
22:21:16.646 | error | javascript.0 (1885) script.js.common.TestStop: Error: listen EADDRINUSE: address already in use :::1111
22:21:16.647 | error | javascript.0 (1885)     at script.js.common.TestStop:3:5
22:21:16.647 | error | javascript.0 (1885)     at script.js.common.TestStop:4:3

**Versions:**  
 - Adapter version: 4.11.0

**Comment by Apollon77** [comment]
Yes, please use https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#onstop to cleanup such resources
