### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.javascript#761]
![image](https://user-images.githubusercontent.com/11523624/108387311-0f979d80-7240-11eb-8941-c5ccf1d758a8.png)
![image](https://user-images.githubusercontent.com/11523624/108387564-45d51d00-7240-11eb-864c-ec77d68284cd.png)
![image](https://user-images.githubusercontent.com/11523624/108387256-00185480-7240-11eb-9203-d1b5effbce5a.png)

**Comment by itProfi** [comment]
Confirm. The same problem
![Скриншот 18-02-2021 191841](https://user-images.githubusercontent.com/6728198/108387726-e9add100-721e-11eb-88bc-8532751581db.jpg)

**Comment by Harry-58** [comment]
Kann ich nur bestätigen!
Erhalte folgende Fehlermeldung:
`downloadable font: post: table overruns end of file (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.221:8081/adapter/javascript/vs/base/browser/ui/codicons/codicon/codicon.ttf
downloadable font: rejected by sanitizer (font-family: "codicon" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.221:8081/adapter/javascript/vs/base/browser/ui/codicons/codicon/codicon.ttf`
Behelfe mir damit:
iobroker stoppen
Im Ordner \opt\iobroker\iobroker-data\files\javascript.admin\vs\base\browser\ui\codicons\codicon die codicon.ttf durch eine funktionierende ersetzen.
iobroker starten
leider ist diese Prozedur nach jedem Update wieder notwendig.
Eine funktionierende codicon habe ich hier abgelegt: [https://github.com/Harry-58/codicon/blob/main/codicon.ttf](https://github.com/Harry-58/codicon/blob/main/codicon.ttf)

**Comment by SliX185** [comment]
Ich häng mich auch mal wieder mit dran.... Wie schon beim Issue  #697. 
Die codicon.ttf im Repo is leider nach wie vor korrupt.

**Comment by gsicilia82** [comment]
Tja, jetzt hat es dieser Bug bis in Stable Release geschafft... Schade.

**Comment by GermanBluefox** [comment]
Bei mir geht's. Verwendet ihr vielleicht Safari?

**Comment by Harry-58** [comment]
Ich verwende Firefox. 
Aber auch wenn ich die codicon mit irfanView oder der "Windows-Schriftartanzeige" öffne kommt eine Fehlermeldung.

**Comment by SliX185** [comment]
@GermanBluefox wie schon gesagt, genau gleich wie im Issue #697
Probier die ttf vom repo zu öffnen, du wirst einen Fehler bekommen. 
Chromium basierte Browser gehen wohl anders mit den Fehler um und greifen auf die lokal installierte Schrift zurück?!
Oder lösche einfach die codicon.ttf aus deinen lokalen Schriften und es funktioniert bei dir auch nicht mehr.

**Comment by gsicilia82** [comment]
Ich verwende Google Chrome und sehe nicht die Icons. Muss die Console mal begutachten, ob bzw was für ein Fehler angezeigt wird.

**Comment by SliX185** [comment]
@gsicilia82 Hast du denn die codicon.ttf als Systemschrift installiert?
Wenn nicht, probiers mal installierter .ttf
(diese: https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf?raw=true)

**Comment by gsicilia82** [comment]
> @gsicilia82 Hast du denn die codicon.ttf als Systemschrift installiert?
> Wenn nicht, probiers mal installierter .ttf
> (diese: https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf?raw=true)

Verwende ioBroker im Docker Container. Muss die ttf im Guest oder auf dem Host installiert werden?

**Comment by SliX185** [comment]
@gsicilia82 
auf dem System wo du auf dein iobroker Webinterface (Admin) mit deinem Browser zugreifst...
Was schätzungsweise dein Windows PC ist. 

@GermanBluefox 
Die ganze Diskussion ist hier eigentlich überflüssig, da alles schon im issue #697 durchgekaut wurde.
Fakt ist, die codicon.ttf aus dem Repo:

https://github.com/ioBroker/ioBroker.javascript/blob/master/src/public/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true
lässt sich nicht öffnen
![fehler](https://user-images.githubusercontent.com/47434006/110857571-4dc13380-82b9-11eb-9586-fa04d0730f0a.jpg)
wobei sich diese:
https://github.com/microsoft/vscode-codicons/blob/main/dist/codicon.ttf?raw=true
öffnen lässt
![fehlerfrei](https://user-images.githubusercontent.com/47434006/110857624-5e71a980-82b9-11eb-96b5-d45bb2152142.jpg)

Es muss eigentlich "nur" die korrupte Datei im Repo ersetzt werden.

**Comment by Harry-58** [comment]
Auch in der neuesten Version 5.0.14 ist  die codicon.ttf korrupt :-(

**Comment by SliX185** [comment]
@GermanBluefox 
Ich sehe, dass Du laut History die codicon.ttf gelöscht und wieder hochgeladen hast (was bei mir im Fork den gewünschten Erfolg gebracht hat)
Nur leider verstehe ich nicht, warum das hier keinen Erfolg bringt?!
wobei noch eine codicon.ttf in /src/public/vs/base/browser/ui/codicons/codicon liegt, die noch alt ist. (vergessen?)

Wie Du sicher schon weißt, sind die .ttf im Repo immer noch korrupt... Aber wieso?

**Comment by gsicilia82** [comment]
@SliX185 
Danke für deinen Hinweis bzgl. manueller Installation. Nun sind bei mir die Icons wieder sichtbar. Dies war auch mit v5.0.14 nicht der Fall.

**Comment by arturDUS** [comment]
Was kann ich als Anfänger denn machen damit die Symbole wieder korrekt angezeigt werden? Wohin muss ich was auf der Linux Installation des Adapters kopieren? Habe extra Version 5.0.14 installiert in der Hoffnung das die Symbole wieder da sind weil im Changelog stand das die Schrift korrigiert wurde ...
Gibt es ein Workaround?

**Comment by mesche** [comment]
@arturDUS ja gibt es. Nachdem mit das Problem auch schon länger beschäftigt, hab ich einen möglichen Workaround hier kurz beschrieben.

[Workaround: Script-Editor – Icons werden nicht angezeigt – Codicon Font defekt](https://www.blogging-it.com/workaround-script-editor-icons-werden-nicht-angezeigt-codicon-font-defektdefekt/hausautomatisierung-smart-home/iobroker.html)

**Comment by arturDUS** [comment]
@mesche  Viele Dank! Das hat funktioniert!

**Comment by instalator** [comment]
5.1.3 fixed
