### ISSUE TITLE
variables don't work

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.javascript#762]
check this script for work. On version 4.11.0, subscribing to variable changes does not lead to anything.
![image](https://user-images.githubusercontent.com/37106885/108635040-f71cc280-748d-11eb-9e8e-7a63e025d8f1.png)
[var.txt](https://github.com/ioBroker/ioBroker.javascript/files/6018283/var.txt)

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Xeon(R) CPU E31265L @ 2.40GHz
RAM: 15.71 GB
Node.js: v12.20.2
NPM: 6.14.11
Model: ARMv7 Processor rev 4 (v7l)
RAM: 924.84 MB
Node.js: v12.20.2
NPM: 7.5.4
JS-Controller (1): 3.2.16
Admin: 4.2.1
Script Engine: 4.11.0

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Pleaseshow the generated javascript code

**Comment by Anzic23** [comment]
```
var testValue, testValue2;


on({id: "0_userdata.0.Tests.bool"/*булен*/, change: "gt"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  testValue = true;
  console.log(('Test boolen TRUE. testValue is ' + String(testValue)));
});

on({id: "0_userdata.0.Tests.bool"/*булен*/, change: "lt"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  testValue = false;
  console.log(('Test boolen FALSE. testValue is ' + String(testValue)));
});

on({id: new RegExp(testValue + "|" + testValue2), change: "ne"}, async function (obj) {
    console.log('Скажи хоть что ни будь');
});
```

**Comment by Apollon77** [comment]
You can not "subscribe" to local variables ... only to ioBroker states.
