### ISSUE TITLE
Script nach Umbenennen verschwunden 

### ISSUE THREAD

**Issue by ente34** [ioBroker/ioBroker.javascript#763]
s. [hier](https://forum.iobroker.net/topic/42605/script-nach-umbenennen-verschwunden?_=1614104523554)

**Versions:**  
 - Adapter version: 4.11.0
 - js-controller
 - JS-Controller version:  3.2.16
 - Node version: 12.21.0
 - Operating system: Windows/Linux

**Comment by Voodoo2man** [comment]
Habe das gleiche Problem. Es geht auch um Script ohne Punkt im Namen. Beim umbennen wird mein Script entfernt.

**Comment by winnyschuster** [comment]
> Habe das gleiche Problem. Es geht auch um Script ohne Punkt im Namen. Beim umbennen wird mein Script entfernt.

hast den neuen Admin 5.x installiert? Dann liegt es daran und es gibt auch ein issue dazu

**Comment by Chiller2019** [comment]
Selbige ist wenn du ein Ordner versuchst anzulegen.

Wo ist denn das benannte Issue?

**Comment by Marsx79** [comment]
> s. [hier](https://forum.iobroker.net/topic/42605/script-nach-umbenennen-verschwunden?_=1614104523554)
> 
> **Versions:**
> 
> * Adapter version: 4.11.0
> * js-controller
> * JS-Controller version:  3.2.16
> * Node version: 12.21.0
> * Operating system: Windows/Linux

Bei mir verschwinden die auch beim umbenennen und verschieben in einen anderen Ordner

**Comment by GermanBluefox** [comment]
What about 5.2.x versions?

**Comment by ente34** [comment]
No change

**Comment by GermanBluefox** [comment]
Please test 5.2.10

**Comment by ente34** [comment]
Fixed!
Thanks
