### ISSUE TITLE
ioBroker Blockly Zeitsteuerung Intervall via nautischen Informationen

### ISSUE THREAD

**Issue by Foinob** [ioBroker/ioBroker.javascript#765]
Hallo,

ich möchte ein Licht mit einem Zeitsteuerungsintervall steuern und zwar nicht anhand vorgegebener Zeiten sondern möchte dafür nautische angaben nutzen.

Kann mir hierbei jemand helfen?

**Comment by Apollon77** [comment]
Bei Nutzungs- und Scriptfragen bitte im ioBroker Forum oder Discord melden. DIe Community unterstützt da sehr gern!
