### ISSUE TITLE
Rules: ne und any werfen Fehler

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.javascript#766]
![rules001](https://user-images.githubusercontent.com/11257222/109393378-9116bc00-7921-11eb-98b4-c1e5a6d61bfb.png)
javascript.0 | 2021-02-27 17:26:46.342 | error | (18276) at Script.runInContext (vm.js:143:18)
-- | -- | -- | --
javascript.0 | 2021-02-27 17:26:46.339 | error | (18276) at script.js.Test_Rule001:57:3
javascript.0 | 2021-02-27 17:26:46.336 | error | (18276) at script.js.Test_Rule001:1:56
javascript.0 | 2021-02-27 17:26:46.331 | error | (18276) script.js.Test_Rule001: ReferenceError: any is not defined
javascript.0 | 2021-02-27 17:26:46.308 | info | (18276) script.js.Test_Rule001: registered 0 subscriptions and 0 schedules
javascript.0 | 2021-02-27 17:26:46.209 | info | (18276) Start javascript script.js.Test_Rule001
javascript.0 | 2021-02-27 17:26:46.068 | info | (18276) Stop script script.js.Test_Rule001
javascript.0 | 2021-02-27 17:22:12.739 | error | (18276) at Script.runInContext (vm.js:143:18)
javascript.0 | 2021-02-27 17:22:12.737 | error | (18276) at script.js.Test_Rule001:57:3
javascript.0 | 2021-02-27 17:22:12.734 | error | (18276) at script.js.Test_Rule001:1:56
javascript.0 | 2021-02-27 17:22:12.728 | error | (18276) script.js.Test_Rule001: ReferenceError: ne is not defined

Auch nach Wechsel von on change nach on update

```
on({id: "info.0.sysinfo.cpu.temperature.main", change: ne}, async function (obj) {
    if (await getStateAsync("").val >= 40) {
		await setStateAsync("sonos.0.root.192_168_138_59.state", "play", false);
    } else {
		
    }
});
/*const demo = {
  "triggers": [
    {
      "id": "TriggerState",
      "acceptedBy": "triggers",
      "_id": 1614440684814,
      "tagCard": "on change",
      "oid": "info.0.sysinfo.cpu.temperature.main",
      "oidRole": "value",
      "oidType": "number",
      "oidUnit": "°C",
      "oidWrite": false,
      "oidRead": true
    }
  ],
  "conditions": [
    [
      {
        "id": "ConditionState",
        "acceptedBy": "conditions",
        "_id": 1614440679588,
        "tagCard": ">=",
        "oid": "",
        "value": "40",
        "useTrigger": false
      }
    ]
  ],
  "actions": {
    "then": [
      {
        "id": "ActionSetState",
        "acceptedBy": "actions",
        "_id": 1614440691115,
        "tagCard": "control",
        "oid": "sonos.0.root.192_168_138_59.state",
        "value": "play",
        "oidRole": "media.state",
        "oidType": "string",
        "oidWrite": true,
        "oidRead": true,
        "oidDef": "stop"
      }
    ],
    "else": []
  }
};*/

//{"triggers":[{"id":"TriggerState","acceptedBy":"triggers","_id":1614440684814,"tagCard":"on change","oid":"info.0.sysinfo.cpu.temperature.main","oidRole":"value","oidType":"number","oidUnit":"°C","oidWrite":false,"oidRead":true}],"conditions":[[{"id":"ConditionState","acceptedBy":"conditions","_id":1614440679588,"tagCard":">=","oid":"","value":"40","useTrigger":false}]],"actions":{"then":[{"id":"ActionSetState","acceptedBy":"actions","_id":1614440691115,"tagCard":"control","oid":"sonos.0.root.192_168_138_59.state","value":"play","oidRole":"media.state","oidType":"string","oidWrite":true,"oidRead":true,"oidDef":"stop"}],"else":[]}}
```

**Comment by Apollon77** [comment]
fixed in 5.0.2
