### ISSUE TITLE
Rules: Enhance the left hand "menu" by adding "mouse over hints"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#768]
On the three main icons to tell "Triggers to define when the script is started", "Condition defines if the action is executed", "Action desfined what should be done" ...
And also all the available blocks should get a sentence that describes what they can do

Additionally: think about if the "flash" icon should be really used in two different places

**Comment by GermanBluefox** [comment]
Done in 5.0.4

**Comment by Apollon77** [comment]
MUCH BETTER!!

@GermanBluefox WOuld it also be possible to add mouse overs to the 3 "block type selection" icons on the top?

(Additionally: maybe rename "Save script" to "Start script"?)

**Comment by GermanBluefox** [comment]
Done
