### ISSUE TITLE
Rules: Allow type changes/Consition change also on the icon on left side 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.javascript#770]
... of the block additionally to the "Reiter" on top

**Comment by Apollon77** [comment]
@GermanBluefox works for e.g. string ... but for booleans do not work?

**Comment by GermanBluefox** [comment]
> @GermanBluefox works for e.g. string ... but for booleans do not work?

Because there are only 2 options. It works up to 4 options

**Comment by Apollon77** [comment]
But then the icon could "toggle" is the same way as the "Reiter" ;-)

**Comment by GermanBluefox** [comment]
:(

**Comment by GermanBluefox** [comment]
Done
