### ISSUE TITLE
Rules: sayit falsche Ausgabe

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.javascript#783]
Beim Versuch einer Sprachausgabe mittels sayit, erfolgt jedoch **nicht der hinterlegte Text**, sondern der Wetterbericht, der zuvor als letzte Sprachausgabe erfolgte. Dabe ist es egal, welche Sprache ich im Script hinterlege. In der sayit Instanz ist als Sprache AWS Polly-Deutsch-Vicki, AWS Region eu-west-1 hinterlegt.
`on({id: "sonoff.0.Buerolicht.POWER", change: "any"}, async function (obj) {
    const _cond = true;
    if (_cond) {
		await setStateAsync("sayit.0.tts.text", "_;50;Bewegung erkannt".replace(/%s/g, obj.state.value).replace(/%id/g, obj.id));
    } else {
		
    }
});
/*const demo = {
  "triggers": [
    {
      "id": "TriggerState",
      "_id": 1614540356590,
      "acceptedBy": "triggers",
      "tagCard": "on update",
      "oid": "sonoff.0.Buerolicht.POWER",
      "oidRole": "switch",
      "oidType": "boolean",
      "oidWrite": true,
      "oidRead": true
    }
  ],
  "conditions": [
    []
  ],
  "actions": {
    "then": [
      {
        "id": "ActionSayText",
        "_id": 1614540439172,
        "acceptedBy": "actions",
        "instance": "sayit.0",
        "language": "_",
        "volume": 50,
        "text": "Bewegung erkannt"
      }
    ],
    "else": []
  },
  "justCheck": true
};*/

//{"triggers":[{"id":"TriggerState","_id":1614540356590,"acceptedBy":"triggers","tagCard":"on update","oid":"sonoff.0.Buerolicht.POWER","oidRole":"switch","oidType":"boolean","oidWrite":true,"oidRead":true}],"conditions":[[]],"actions":{"then":[{"id":"ActionSayText","_id":1614540439172,"acceptedBy":"actions","instance":"sayit.0","language":"_","volume":50,"text":"Bewegung erkannt"}],"else":[]},"justCheck":true}`

![grafik](https://user-images.githubusercontent.com/41550245/109433970-4d9c7a80-7a13-11eb-812a-4a1116ecab84.png)

**Comment by GermanBluefox** [comment]
Please retry with latest 5.0.5 version

**Comment by crunchip77** [comment]
@GermanBluefox richtiger Text wird nun ausgegeben, wenn ich z.b. einen Türsensor (onChange )als trigger nehme.

Allerdings beim BWM (onUpdate) siehe oben im Script, kommt die Ausgabe  **doppelt** bei **einmaliger** Bewegung. Der BWM selbst, aktualisiert  sich innerhalb von 5sec nur einmalig, heisst, eine weitere Bewegung wird erst nach 5sec erkannt.
Getestet hab ich mit beiden Varianten (on condition/just check)
![grafik](https://user-images.githubusercontent.com/41550245/109515739-b59ca080-7aa7-11eb-9526-41eb0d1e4bc4.png)

**Comment by Apollon77** [comment]
Log doch mal den Wert ... nicht das der true ... false macht

**Comment by crunchip77** [comment]
@Apollon77 ganz so falsch war deine Idee nicht. 
er macht doppelt true??
![grafik](https://user-images.githubusercontent.com/41550245/109525023-66f40400-7ab1-11eb-9da0-2856c6bbde02.png)

**Comment by Apollon77** [comment]
Naja ok, damit trigger der zigbee doppelt. SOllte aber dann mit "nut bei condition change" nicht passieren

**Comment by crunchip77** [comment]
tut es aber, hatte ich ja getestet, desweiteren frag ich mal beim Zigbee nach, warum der doppelt kommt
