### ISSUE TITLE
RULES: setStateDelayed fehlt

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.javascript#784]
Die Funktion setStateDelayed fehlt wohl.

**Comment by Apollon77** [comment]
Would "pause" and "setState" an idea?

**Comment by Apollon77** [comment]
But yes the "auto stop update when new comes it" might be beneficial for full support

**Comment by GermanBluefox** [comment]
I thought about it, but, yes, you can use Pause and KISS (keep it super simple) won

**Comment by Apollon77** [comment]
As said: the only topic would be that a second change within the wait time could make things strange

**Comment by GermanBluefox** [comment]
Implemented

**Comment by MarkSau** [comment]
Hi, it looks like that the new code does not run correctly in my very simple script.

`javascript.0 (6065) script.js.80_Infrastruktur.Kameras.Vorgarten.02_1_Cam_Neustart compile failed: at script.js.80_Infrastruktur.Kameras.Vorgarten.02_1_Cam_Neustart:6
`

`
let cond0 = false;

setInterval(async function (obj) {
    const _cond = ();
    if (_cond) {
		await setStateAsync("sonoff.0.Steckdose04.POWER1", false, false);
		setStateDelayed("sonoff.0.Steckdose04.POWER1", true, false, 10000, true);
    } else {
		
    }
}, 6 * 3600000);
`
