### ISSUE TITLE
Rules: Baustein deaktivieren

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.javascript#785]
Wäre es denkbar/sinnvoll, eine Möglichkeit einzubauen, so dass man einen Baustein deaktivieren kann?

**Comment by Apollon77** [comment]
Was wäre der Use case?

**Comment by crunchip77** [comment]
Use case...selbe wie beim Blockly. Beim Aufbau eines Scriptes, funktioniert z.b. etwas nicht wie gewollt bzw  möchte testweise etwas abändern, bleibt bisher als Möglichkeit nur, den/die  Baustein/e zu löschen und muss sich anschliessend wieder durchklicken und seine state's erneut auswählen. Zumindest ging es mir gestern so , als ich ein blockly mittels Rules nachbauen wollte.

**Comment by GermanBluefox** [comment]
Ich möchte die GUI nicht überladen. Also möglich, aber wird zu viel

**Comment by crunchip77** [comment]
Ok
