### ISSUE TITLE
Rules: "on true" und "on false" in States-Tab (When)

### ISSUE THREAD

**Issue by DocGame69** [ioBroker/ioBroker.javascript#787]
Ich wollte eine simple When (Taster gedrückt) und ein Then( Lampe toggle) ohne Bedingung testet.
Da der Taste aber nur kurz auf true geht geht die Lampe sofort wieder aus, da nur "on Change" und "on update" implimentiert ist.
Wäre hier ein zusätzlicher Punkt "on true" oder sogar "on false"(nicht ganz so wichtig) möglich?
Dadurch könnte man sich die Statusabfrage der Lampe( oder so was) im and-Block sparen.
Nachtrag: Habe gerade das "Use Trigger Value" in State condion entdeckt. Damit geht es natürlich (Wenn auch mit einer Bedingung mehr)

**Comment by GermanBluefox** [comment]
Warum willst du condition nicht benutzen?
![image](https://user-images.githubusercontent.com/4582016/109568017-91ac7f80-7ae6-11eb-81a1-e99da3d48277.png)
