### ISSUE TITLE
Rules - Add Time and Astro condition block

### ISSUE THREAD

**Issue by tccflash** [ioBroker/ioBroker.javascript#790]
Es wäre sehr hilfreich, wenn man in den Conditions direkt Monate auswählen könnte z.B.
WENN Terrassentür = open
**UND Monat = März bis August / ODER = Dezember**
DANN = schalte Licht

Kannst du das implementieren? Wäre ein tolles Feature.

**Comment by Apollon77** [comment]
I think generaly "time conditions" ... also "time on hour, minute, day level ... not only months

**Comment by Apollon77** [comment]
Cases like:
* between April and July
* between 2 and 4 o'clock
* when astro is "nauticDust..."

**Comment by tccflash** [comment]
Maybe you can in this case built in a timer function too?🤔 Like:
When: light off
And: button pressed
Than: Start timer <name> 5min. 

So we can interact with the specific timer Name in an other Flow? Do you think that's possible? Should I do a new request for this feature?

**Comment by Apollon77** [comment]
@tccflash Sorry but I think  "no". If you want to do such fancy stuff use Blockly ... Rules is there for a specific target group and use cases and if we now "Blow" that up again we end in "no one understands it anymore" :-)

**Comment by tccflash** [comment]
All right. That's fine... Was just an idea 😅 I used Homey before I switched to iobroker. That's the same procedere as your rules System there. If you like I can sent you some Screenshots from Homey useability in the iobroker forum!?

**Comment by Apollon77** [comment]
>  If you like I can sent you some Screenshots from Homey useability in the iobroker forum!?

lets say it that way: if you "Miss" stuff simply create issues here and add screenshots there so that we can see what was usefull on homey and you miss here :-)

**Comment by GermanBluefox** [comment]
> All right. That's fine... Was just an idea 😅 I used Homey before I switched to iobroker. That's the same procedere as your rules System there. If you like I can sent you some Screenshots from Homey useability in the iobroker forum!?

Would be intersting

**Comment by GermanBluefox** [comment]
Please check 5.0.10
