### ISSUE TITLE
Blockly Umsetzung von TriggerBlock mit mehreren Objekten in JS als regex

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.javascript#792]
![image](https://user-images.githubusercontent.com/14924590/110205086-c61d9400-7e76-11eb-9cce-d482864fa7c6.png)

![image](https://user-images.githubusercontent.com/14924590/110205113-ef3e2480-7e76-11eb-97f5-aacd572bf6e8.png)

Die Objekt IDs mit dem namen alive sind vom ping adapter. Die id hat die ip adresse im Namen wie man sieht. Da einzelne Objekte als Regex in JS umgesetzt werden, wird das script nicht nur von 10.0.0.4 getriggert, sondern auch von 10.0.0.40, da die regex erfüllt ist. 

Das sollte maximal geschehen, wenn ich selbst die regex eingebe, aber nicht dedizitierte Objekte angebe, denke ich mal.

DANKE & LG 
W

**Comment by Apollon77** [comment]
Naja da muss ein "$" ans ende...

**Comment by Apollon77** [comment]
... oder noch besser in ein array umgestellt ... dann brauchts keine regex

**Comment by realwax** [comment]
Ja ganz genau, aber da es ja blockly ist muss ich dich bitten es umzusetzen. Danke Dir!

**Comment by GermanBluefox** [comment]
Please check 5.0.11

**Comment by realwax** [comment]
![image](https://user-images.githubusercontent.com/14924590/110243555-330a5a00-7f5b-11eb-8515-1896ecbd4f9e.png)

`
15:37:43.942 | error | javascript.0 (32126) script.js.light.Bürolicht_&_PC compile failed: at script.js.light.Bürolicht_&_PC:1
-- | -- | --

`
![image](https://user-images.githubusercontent.com/14924590/110243731-ea9f6c00-7f5b-11eb-8e4c-651403db620d.png)


Es kommt jetzt zu einem compile error. $ ist drinnen. 
Der Fehler, denke ich ist die Umsetzung am letzten Eintrag siehe screentshot:

richtig:
on({id: new RegExp('ping\\.1\\.ioBrokerPIB3\\.10_0_0_4' + "$|" + 'ping\\.1\\.ioBrokerPIB3\\.10_0_0_8' + "$"), change: "ne"}, async function (obj) {


Danke für die rasche Lösung vorhin!

**Comment by Apollon77** [comment]
5.0.12 is available

**Comment by realwax** [comment]
Testing ok! Fix/solution confirmed!
