### ISSUE TITLE
Blockly does not work with version 5.0.11

### ISSUE THREAD

**Issue by FredF63** [ioBroker/ioBroker.javascript#793]
Blockly in Version 4.8.4 as js-script:
`on({id: new RegExp('0_userdata\\.0\\.Neues_Objekt1' + "|" + '0_userdata\\.0\\.Neues_Objekt2'), change: "ne"}, function (obj) {
  });`

same Blockly in Version 5.0.11:
`on({id: new RegExp('0_userdata\\.0\\.Neues_Objekt1' + "$|" + '0_userdata\\.0\\.Neues_Objekt2'$), change: "ne"}, async function (obj) {
  });
`

**Comment by AlexanderGruenstetter** [comment]
kann ich so bestätigen. Da wurde wohl verschlimmbessert :)

**Comment by hanan070893** [comment]
auch ich kann dieses bestätigen.

**Comment by Siggi0904** [comment]
Hier auch so. Tritt nur mit mehr als ein Auslöser am Trigger auf.
Wie kann man das beheben? Oder muss man auf eine neue Version des Adapters warten?

**Comment by Apollon77** [comment]
Downgrade to 5.0.9 till fix is available

**Comment by hanan070893** [comment]
Im Admin zurück auf Version 5.0.9.
Danach den Mehrfach-Trigger-Block löschen, zweischenspeichern und neu 
anlegen.

hanan070893

------ Originalnachricht ------
Von: "Mario Siegmann" <notifications@github.com>
An: "ioBroker/ioBroker.javascript" 
<ioBroker.javascript@noreply.github.com>
Cc: "hanan070893" <andy.haenggi@bluewin.ch>; "Comment" 
<comment@noreply.github.com>
Gesendet: 07.03.2021 16:10:02
Betreff: Re: [ioBroker/ioBroker.javascript] Blockly does not work with 
version 5.0.11 (#793)

**Comment by Apollon77** [comment]
5.0.12 with the fix should be on npm

**Comment by AlexanderGruenstetter** [comment]
Und läuft wieder. DANKE!!

**Comment by Siggi0904** [comment]
Funktioniert nicht.
Zweiten Auslöser hinzu und gespeichert.
Dann tritt der Fehler wieder auf.

![grafik](https://user-images.githubusercontent.com/4992106/110247281-bd5aba00-7f6b-11eb-87e3-7c70e11504c0.png)

**Comment by AlexanderGruenstetter** [comment]
Ich habe den Triggerblock mal ganz gelöscht, gespeichert und dann den Trigger neu angelegt. So hats funktioniert.

**Comment by Siggi0904** [comment]
Ja, stimmt, dann funktioniert es.

Kann geschlossent werden.
