### ISSUE TITLE
Aktualisierung der Übersetzung

### ISSUE THREAD

**Issue by Siggi0904** [ioBroker/ioBroker.javascript#794]
1. Die Übersetzung des Hauptmenüs der Skripte im IOBroker klingt nach einer automatischen Übersetzung von Google.

![grafik](https://user-images.githubusercontent.com/4992106/110242737-ad38df80-7f57-11eb-91c9-8884f06622ed.png)

Das sollte aktualisiert werden.

2. Trigger im Blockly 
In den Triggern sollte im Popup des Bereichs "anerkannt ist" eine Korrektur der Übersetzung erfolgen.
"anerkannt ist" ändern -> Auslösung durch
Besser wäre anstatt Update -> bestätigte Änderung
Und bei Befehl -> unbestätigte Änderung

Siehe Screenshot:
![grafik](https://user-images.githubusercontent.com/4992106/110242847-246e7380-7f58-11eb-82ce-77d654a2d28e.png)

Vielleicht ist dies ja möglich. Hierdurch wäre diese Option in den Triggern besser verständlich,

**Comment by GermanBluefox** [comment]
Please test 5.0.14
![image](https://user-images.githubusercontent.com/4582016/110835245-d7173c80-829e-11eb-88c8-5886b5d83ccf.png)

**Comment by Siggi0904** [comment]
Sounds, great.

Is that for all triggers with these option available?
Please update this to all triggers.

Great thanks, I'll test it.

**Comment by klein0r** [comment]
Das wurde bereits im PR vor einiger Zeit geändert. https://github.com/ioBroker/ioBroker.javascript/pull/755
