### ISSUE TITLE
with 5.12 some RegExpr. not working anymore

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.javascript#796]
some RegExpr. are not working anymore.

Beispiel:
let SelectorU = $('channel[state.id=hm*.UNREACH$]');
funktioniert nicht mehr.
let SelectorU = $('channel[state.id=hm*.UNREACH]');
funktioniert.

More information at iobroker Forum:

https://forum.iobroker.net/topic/43013/problem-mit-selector-seit-update-auf-javascript-5-0/15?_=1615139559967

**Comment by Apollon77** [comment]
Which version was used before? Change in 5.0 can not be ... There was a change fpr selectors and wildcards some time ago ... @AlCalzone could it be the same?

**Comment by AlCalzone** [comment]
Yeah that's the same thing we changed a while ago.
The selectors were never meant to be regex. Now they are behaving exactly as documented.

**Comment by gieselbert918** [comment]
$('channel[state.id=hm*.UNREACH$]')

also matches nothing in 5.0.12, i used 4.11.0 before.

**Comment by Apollon77** [comment]
@gieselbert918 Did you read what @AlCalzone wrote direct in post above yours?

**Comment by gieselbert918** [comment]
I think i wrote exactly channel[state.id=hm*.UNREACH$] like AlCalzone

**Comment by gieselbert918** [comment]
Sorry, I missunderstod. 
Now i know the $ is not necesarry.

**Comment by gieselbert918** [comment]
$('channel[state.id=hm*.STATE](functions=Aktoren)(functions=funcHeating)')

but this Selector matches also nothing now, and i don't see any misstake.
With Version 4.11.0 this works fine.

**Comment by gieselbert918** [comment]
`$('channel[state.id=hm*.STATE](functions=Aktoren)(functions=funcHeating)')`

works fine with Version 4.11.0, and now with 5.0.12 doesn't match anything

**Comment by JayVee2** [comment]
` $('channel[state.id=*.ENERGY_COUNTER$]');`

doesn't match anything anymore. 

Previous Version 4.8.4 was OK.

**Comment by Apollon77** [comment]
@JayVee2 Please also you: READ ABOVE PLEASE!!

**Comment by AlCalzone** [comment]
FYI, the change I'm talking about was added in 4.9.0:
https://github.com/ioBroker/ioBroker.javascript/pull/658

**Comment by Coalado** [comment]
Guys... could you please stop breaking things? Even if this was just was a workaround, there are scripts out there that use this workaround. It is REALLY annoying, that we have to start crawling boards and github and fixing things after every update.

**Comment by AlCalzone** [comment]
Guys... could you please stop using undocumented stuff and then complain when it gets fixed?
