### ISSUE TITLE
Logik Visualisierung

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.javascript#797]
Hallo,
inzwischen ist die Steuerung meiner Heizung recht umfangreich (js 4.5.12)
Die Visualisierung erfolgt mit VIS.

Manchmal fragt man sich jedoch, wieso startet der Brenner nicht oder wieso geht die
Vorlauftemperatur nicht hoch.
Man kämpft sich im Script durch mehrere verschachtelte if-then-else bzw. &&,|| ||,<,> durch und
dann kontrolliert man die logs, bzw. fügt in das entsprechende Script log('Test: ....') usw. ein,
in der Hoffnung, die Ereignisse haben sich nicht verändert.

1.)
Mein Traum wäre hier eine spezielle Logic-Visualisierung, wo die Logik als Graphik darstellbar ist und
der jeweilige Status einer Verzweigung bzw. Werte einer >,<,== Bedingung angezeigt wird.
Node-Red habe ich ausprobiert, wird aber bei komplizierteren Verzweigungen schnell unübersichtlich,
da ist js wesentlich kompakter und jedenfalls für mich leichter lesbar.

2.)
Auch sehr hilfreich wäre, wenn im js-Editor der aktuelle Wert einer Variablen im Kontext angezeigt werden würde,
so wie es ja bei den Konstanten auch gemacht wird.
----------------  Hier eine dringende Bitte an die Entwickler! --------------------------

VG

**Comment by Apollon77** [comment]
1.) Wäre ein Adapter Request bzw ein Feature Request für einen neuen Script typ. Das ist was sehr aufwändiges. Es gab mal mit ScriptGUI so einen Ansatz, aber leider wird das nicht mehr weiterentwickelt. Damit ist node-red noch das was an "visuelle Programmierung" (vor allem für Komplexe dinge) rankommt

2.) geht nicht weil der Skript editor ja kein Debugger ist undd amit das Skript nicht "läuft".
heisst ggf was Du brauchst ist eine Art Debug-Modus im JavaScrit adapter ... oder ?!

**Comment by Hans-Zwiesel** [comment]
Hallo Apollon77,
vielen Dank für die Antwort.
1.) Ich wäre schon damit zufrieden, wenn es ein "Logik-VIS" geben würde, wo man ählich einem Flussdiagramm einige
     kritische Stellen im Skript nur zur Anzeige nachbildet und die Variablen angezeigt bekommt.
2.) Ich meine, wenn der Skript editor ein Skript offen hat, dann wird das Script ja deswegen immer noch ausgeführt - richtig?
     Ob das dann gleich ein Debug-Modus sein muss, weiß ich nicht. Es geht nur darum, denn Wert einer Variablen anzuzeigen,
     so wie es ja jetzt schon mit den Konstanten möglich ist.

**Comment by Apollon77** [comment]
1.) naja das ist alles andere als Simpel ... javascript code visualisieren ... ich denke das geht nicht sooo simpel wie Du dir das vorstellst
2.) Naja der editor hat halt Null komma null Zugriff auf die Daten des Skripts ... 

Also ich denke, so schön es auch wäre, so schwierig bis unmöglich ist es

**Comment by Hans-Zwiesel** [comment]
Ich bin da schon einige Zeit weg von dieser Technik, aber Du wirst es wissen:
Wird der js code compiliert oder interpretiert, oder wie wird js ausgeführt?

**Comment by Apollon77** [comment]
ich denke inzwischen "Just-In-Time" compiled internally :-)

**Comment by GermanBluefox** [comment]
Es ist "quasi" unmöglich oder wird mir 1 Jahr Entwicklung kosten. Die Zeit habe ich nicht

**Comment by Hans-Zwiesel** [comment]
Sieht so aus, als ob sich ioBroker in Richtung Anfänger bzw. Spielzeug entwickeln soll.
Denke da an das neue Feature "RULES".

Ich weiß natürlich nicht, wer hier die Entscheidungen trifft,
meine aber, das ist die falsche Richtung.

**Comment by GermanBluefox** [comment]
> Sieht so aus, als ob sich ioBroker in Richtung Anfänger bzw. Spielzeug entwickeln soll.
> Denke da an das neue Feature "RULES". Blockly reicht doch.
> 
> Ich weiß natürlich nicht, wer hier die Entscheidungen trifft,
> meine aber, das ist die falsche Richtung.

Das war meine Entscheidung. Blockly ist immer noch kompliziert für die Anfänger.
Du fragst nach einer Feature, die fast unmöglich zu implementieren ist und dann wenn ich sage dass es so ist, nennst du ioBroker Spielzeug. Ich sehe die Logik nicht: "Ah ihr könnt die Teleportation von Objekten nicht bauen, dann ist das nur ein Spielzeug und kein Fahrzeug."

**Comment by Hans-Zwiesel** [comment]
Nein Nein. Das meine ich nicht.
So etwas wie ioBroker habe ich mir immer vorgestellt, ioBroker übertrifft das, ist wirklich super.
Ich meine die Richtung die "Rules" einschlägt, geht in Richtung Spielerei.
Ihr seid die Macher.
Wenn Ihr das so für gut findet, dann solls so sein.
Mir wäre jedoch eine andere Richtung lieber gewesen.

**Comment by Apollon77** [comment]
Es geht in die Richtung was die User wollen und andere Systeme anbieten!
Das fehlte noch.

**Comment by Hans-Zwiesel** [comment]
Bitte entschuldigt, wenn ich das etwas direkt rüberbringe.
Ich mag es nicht, meine Meinung mit Blümchen zu garnieren.

**Comment by Apollon77** [comment]
@Hans-Zwiesel Bitte 5.1 ansehen, hat jetzt vollständige Debug optionen für Skripte drin.
