### ISSUE TITLE
ASTRO longitude and latitude are not used

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.javascript#800]
**Describe the bug**  
if "Instanzen -> Javascript.0 -> Konfiguration -> ASTRO-EINSTELLUNGEN -> "Verwenden Sie die Systemeinstellungen" is ticked, the values from "System -> Haupteinstellungen -> Breitengrade & Längengrad" are not used. It does only work, if this checkbox is unchecked and the values are entered by hand.

**To Reproduce**  
see above,
add following script:
`
const suncalc = require('suncalc');
const jsa = getObject("system.adapter.javascript.0");
const lat = jsa.native.latitude;
const long = jsa.native.longitude;
`

**Expected behavior**  
values from "System -> Haupteinstellungen -> Breitengrade & Längengrad" will be used also if "Verwenden Sie die Systemeinstellungen" is ticked.

**Screenshots & Logfiles**  
`
const jsa = getObject("system.adapter.javascript.0");
log("jsa: " + JSON.stringify(jsa));
`

gives:

`(...) {"latitude":"","longitude":"", (...)`

**Versions:**  
 - Adapter version: Script Engine v5.0.12
 - JS-Controller version:  v3.2.16
 - Node version: v12.21.0
 - Operating system: linux

**Additional context**  
see also https://forum.iobroker.net/topic/43018/gel%C3%B6st-l%C3%A4ngen-und-breitengrade/5?_=1615306524865

**Comment by Apollon77** [comment]
Hm ... Do I get it right: You access the javascript adapter object and expect that the sytem settings are included in this? It is not working that way!

The setting you mention is for all "astro" methods that the javascript adapter provides itself like astro triggers and such ... as soon as you want to calculate own stuff use own values please
