### ISSUE TITLE
New Block "timeout running"

### ISSUE THREAD

**Issue by jaschkopf** [ioBroker/ioBroker.javascript#801]
**Is your feature request related to a problem? Please describe.**
Often timeouts are startet multiple times what causes uncalculated problems in the script.

**Describe the solution you'd like**
To prevent double starting a timeout it would be nice to hava a block "timeout running" that gives true/false back. This could be used with a "if" block to prevent double starting the timeout. 

**Describe alternatives you've considered**
At the moment I use a separate boolean that is switched to "true" when the timeout is startet and changes to "false" when the timeout stops. That prevents me from double starting, but is extra work and needs additional variables. 

**Additional context**

![Unbenannt](https://user-images.githubusercontent.com/21341916/110954791-3467c800-8349-11eb-912d-1a9a088fc225.PNG)

**Comment by Apollon77** [comment]
Atre you sure that the timeout name is not already existing as a variable?

**Comment by jaschkopf** [comment]
Nope sadly not. Someone in iobroket forum told me to compare the timeout variable ==0 but the variable is not created. Creating the variable manually is not possible because name already exists? Makes no sense to me
