### ISSUE TITLE
Simple rule not working

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.javascript#803]
**Describe the bug**  
I have a simple script.

![rules_issue](https://user-images.githubusercontent.com/1212934/111193727-c32f4b80-85ba-11eb-84c0-c07fc78ed63c.png)

which translates to:

```
let cond0 = false;

on({id: "hm-rpc.2.0026DA49A8294B.1.STATE", change: "ne"}, async function (obj) {
    const _cond = obj.state.val == true;
    if (cond0 === false && _cond) {
        cond0 = true;    
		await setStateAsync("ham.0.UVC-G4-Dome.UVC-G4-Dome-Doorbell-Trigger.On", true, false);
    } else if (cond0 === true && !_cond) {
        cond0 = false;    
		
    }
});
```

This is not working/doing anything. I have another script:

```
on({ id: 'hm-rpc.2.0026DA49A8294B.1.STATE'/*Haustür Klingel STATE*/, change: "ne" }, function (obj) {
    var state = obj.state.val;
    if (state) {
        setState('ham.0.UVC-G4-Dome.UVC-G4-Dome-Doorbell-Trigger.On'/*On*/,true);
    } 
});
```

This works and set the desired state and I get the notification on my phone.

**To Reproduce**  
Create simple rule.

**Expected behavior**  
The state will be set and I get the Notification on my phone.

**Versions:**  
 - Adapter version: 5.0.15
 - JS-Controller version: 3.2.16
 - Node version: v14.16.0
 - Operating system: debian buster

**Comment by Apollon77** [comment]
Can you please add logging. I would not see any reason that the script should not work
