### ISSUE TITLE
Links "Mehr erfahren" in the pop-up window for new scripts lead to wrong pages

### ISSUE THREAD

**Issue by ahnungsbefreit** [ioBroker/ioBroker.javascript#804]
**Describe the bug**  
When selecting "+" for the creation of a new script, a pop-window with 4 options appears: Rules, Blockly, JavaScript and Typescript. Each of them has a link "Mehr erfahren" but most of them lead to wrong or not existing pages:

* For "Rules" the link points to the blockly doc
* For Blockly the link also pointsto the blockly doc (which is correct)
* For Javascript and Typescript, it leads to an "Page not found" error page

**To Reproduce**  
See above

**Expected behavior**  
Even if we don't have a doc for a language yet, the user should never see the 404 error page but at least a placeholder page with some explanation e.g. "under construction". For Javascript, we should point to [the correct  page](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md)

**Screenshots & Logfiles**  
n/a

**Versions:**  
 - Adapter version: 5.0.14

**Comment by GermanBluefox** [comment]
Fixed in 5.2.9

**Comment by Feuer-sturm** [comment]
@GermanBluefox Everything ok with 5.2.10
