### ISSUE TITLE
BLOCKLY - setStateDelayed funktioniert bei Verzögerungen nicht korrekt

### ISSUE THREAD

**Issue by Plasmachef** [ioBroker/ioBroker.javascript#806]
Seit einigen Tagen funktioniert bei Blockly "setStateDelayed" die Auswertung der Verzögung nicht mehr, wenn es sich um eine Variable oder ein einen Ausdruck handelt.
Als Codeumwandlung wird immer 
`setStateDelayed('Object ID', true, false, 0, false);`
ausgegeben.
Soll heißen wenn Ausdrücke, Variablen oder Formeln angedockt werden, wird immer die "0" im Script verwendet.

Zur Verdeutlichung mit Bildern usw siehe:
[https://forum.iobroker.net/topic/43338/setstatedelayed-funktioniert-nicht-bei-verzögerung](https://forum.iobroker.net/topic/43338/setstatedelayed-funktioniert-nicht-bei-verz%C3%B6gerung)
_Link korrigiert!_

Version 5.0.7 ist noch alles i. O. - mit Version 5.0.8 Fehler nachvollziehbar.
Aktuell Version 5.0.14

**Comment by GermanBluefox** [comment]
Will be fixed in next version
