### ISSUE TITLE
Warning at getState from id with null value

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.javascript#809]
The Adapter scenes is not started, so the value for the id is null. 
To get the info, whether the adapter is started, i only can get with getState?
So if i check it with getState i always get an warning.

var id = 'system.adapter.scenes.0.alive';
console.log(getObject(id)); //(OK)
console.log(getState(id));  // warnings

01:16:48.319 | info | javascript.0 (1659) script.js.HAUS.ALLGEMEIN.InstanzenNeustart: {'_id':'system.adapter.scenes.0.alive','type':'state','common':{'name':'scenes.0 alive','type':'boolean','read':true,'write':true,'role':'indicator.state'},'native':{},'from':'system.host.pi4-2.cli','ts':1603205592119,'acl':{'object':1636,'state':1636,'owner':'system.user.admin','ownerGroup':'system.group.administrator'}}
-- | -- | --
01:16:48.321 | warn | javascript.0 (1659) at etwas_tun (script.js.HAUS.ALLGEMEIN.InstanzenNeustart:7:17)
01:16:48.321 | warn | javascript.0 (1659) at script.js.HAUS.ALLGEMEIN.InstanzenNeustart:184:7
01:16:48.321 | warn | javascript.0 (1659) at script.js.HAUS.ALLGEMEIN.InstanzenNeustart:196:3
01:16:48.322 | info | javascript.0 (1659) script.js.HAUS.ALLGEMEIN.InstanzenNeustart: {'val':null,'notExist':true}

Is there option to get the info about the value without any warning?

**Versions:**  
 - Adapter version: 5.0.15
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: linux

**Comment by Apollon77** [comment]
maybe use existsState method to check before using it? :-)
