### ISSUE TITLE
$ Selector changed behavior in  5.0.14

### ISSUE THREAD

**Issue by Waly-de** [ioBroker/ioBroker.javascript#810]
Since the last update of Javascript (5.0.14) the following selection does not work anymore.
Previously I was able to query all States and Level(dimmer) and Sonoff devices.
Since the update this search pattern returns nothing.

Problem seems to be the "or" link. "state.id=*.STATE" alone works as always.

Has something been changed? Is it supposed to be like this? 
And why are no regex possible there at all? That would make things much easier 🙂 .

To try it out:

//Geht nicht:
`$("state[state.id=*.STATE|.POWER|.LEVEL](functions=Licht)").each(function(id,i) {`
`   log(i + ": " +id); `
`});`

//Geht:
`$("state[state.id=*.STATE](functions=Licht)").each(function(id,i) {`
`	log(i + ": " +id);`
`});`
`

I found a workaround to make my script working again:

`$("*.STATE|.POWER|.LEVEL(functions=Licht)").each(function(id,i) {`
`	log(i + ": " +id);`
`});`

will this syntax still work in the future for sure?

**Comment by Apollon77** [comment]
Please see infos in https://github.com/ioBroker/ioBroker.javascript/pull/658 ... in fact it was an unexpected behaviour before and never intended to work that way
