### ISSUE TITLE
File tab_m.html not found

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.javascript#813]
Links im Reiter Vorlage(TypeScript) lässt sich nicht aufrufen, siehe Screen
Admin 4.2.1
Script Engine v5.1.3
![image](https://user-images.githubusercontent.com/41550245/112950066-2c29ce00-913a-11eb-85c7-36597e1c509c.png)

**Comment by Apollon77** [comment]
@AlCalzone @GermanBluefox I would not have known that this tab comes from this Adapter ...so no idea from which it comes

**Comment by AlCalzone** [comment]
Das sieht aus wie Überreste eines Adapter-Templates.

**Comment by GermanBluefox** [comment]
Sorry, Javascipt hat nichst damit zutun
