### ISSUE TITLE
SIGSEGV with versions > 4.8.4 while using cryptian

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.javascript#816]
I am using cryptian to en-/decrypt km200 http requests. (In former versions I used  mcrypt which is now depreciated)

Until javascript adapter version 4.8.4 the cryptian module works as expected. 
On any higher version > 4.8.4   I get SIGSERV error-messages and adapter restarts.

Node.js: v12.22.0
NPM: 6.14.11

**Comment by Apollon77** [comment]
Full logs please

**Comment by tp1de** [comment]
I only get these entries in my log:


host.iobroker | 2021-04-07 14:19:46.369 | info | Restart adapter system.adapter.javascript.1 because enabled
-- | -- | -- | --
host.iobroker | 2021-04-07 14:19:46.368 | info | instance system.adapter.javascript.1 terminated with code NaN ()
host.iobroker | 2021-04-07 14:19:46.367 | warn | instance system.adapter.javascript.1 terminated due to SIGSEGV

**Comment by Apollon77** [comment]
SIGSEGV is a segmentation fault means a memory access error. Which nodejs version you use?

**Comment by tp1de** [comment]
Node.js: v12.22.0
NPM: 6.14.11

**Comment by Apollon77** [comment]
hm ... mostly uptodate (in 12.22.1 from yesterday there are some openssl fixes) ... maybe related

Other then that try nodejs14

in 4.8.4 several changes were done ... no idea if we can find out ewhat interferes here with the library ... should be relatively irrelevant

**Comment by tp1de** [comment]
Thanks for the reply  ... I will test the nodejs versions.

**Comment by tp1de** [comment]
On my Windows Testsystem with Node.js: v14.16.0 & NPM: 6.14.11 I get the following message:
instance system.adapter.javascript.0 terminated with code 3221225477 (3221225477)

Any idea?

**Comment by tp1de** [comment]
nodejs 12.22.1 does'nt work either on my production system.  I have to stick to javascript 4.8.4 or find any other solution for replacing cryptian ...

**Comment by Apollon77** [comment]
Error code 0xc0000005 (3221225477) means access violation ... so in fact equivalent with the SIGSEGV on linux :-(

**Comment by tp1de** [comment]
I can identify that the problem is linked to JSON.parse function. 
Is this functionality different in the different versions of the javascript-adapter?

The access violation seems to be linked to a string to be converted with JSON.parse:
Just the JSON.parse statement of the decoded string results in the access violation for the javascript adapter versions > 4.8.4.

**Comment by Apollon77** [comment]
JSON comes from nodejs itself and not really from the adapter. Maybe it is a strange effect with the javascript sandbox  used to encapsulate the running javascripts in the adapter, but also this was not really changed between the versions

**Comment by tp1de** [comment]
At the end the access violation is triggered by request (http) after using cryptian decryption. After a couple of requests and decryption the access violation happens. Just a loop of decryption does not produce the error.

Finally I went from _cryptian_ module to _rijndael-js_ and the SIGSEGV errors does'nt happen actually anymore.
When stable for tomorrow I will close the issue.
