### ISSUE TITLE
Pictures missing

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.javascript#818]
I updated all adapters and js-controller
But the java script editor still is missing some icons:
![image](https://user-images.githubusercontent.com/11745094/114935639-b8770900-9e3b-11eb-97c3-156f1e8c1fe1.png)

**Comment by Apollon77** [comment]
which version?

**Comment by derrapf** [comment]
5.0.14:
![image](https://user-images.githubusercontent.com/11745094/115027914-970e2f80-9ec4-11eb-9fb1-0b23d3c03232.png)
