### ISSUE TITLE
Experten Button in Scripten

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#82]
Sehr viele Neulinge speichern ihre Scripte unter "global".
Ist es möglich einen "Experten Button" einzurichten und den Ordner "global" nur anzuzeigen, wenn der "Experten Modus" aktiv ist?

**Comment by Xyolyp** [comment]
Alternativ eine Erklärung wenn man das erste Mal ein Skript im Ordner global speichert.
