### ISSUE TITLE
System Latitude/Longitude missing in Javascript 

### ISSUE THREAD

**Issue by woessmich** [ioBroker/ioBroker.javascript#824]
Use systemsettings: checked
Map: Shows correct location as in Admin

Coordinates in Javascript: empty => After manual entry and restart (unchecked system settings): entered coordinates are available => back to system settings and restart: coordinates not updated; script still shows manually enterd coordinates

=> Coordinates in adapter are not updated from admin settings

javascript:  5.1.3
admin: 4.2.1

**Comment by Apollon77** [comment]
I do not know what you mean/expect?

The adapter values will NEVER be updated from system values. You just define if the system ones should be used or coordinates entered in javascript.

So what exactly is the issue?

**Comment by woessmich** [comment]
The expectation is that if use system settings is ticked, coordinates from admin adapter are used instead of those in the javascript adapter.

**Comment by Apollon77** [comment]
Yes they should be USED, but this is not updating the values shown in the Javascript config. So: Are they not being used at all or do you just "Miss" to "see" the other values in the javascript config screen?

**Comment by woessmich** [comment]
They are not used.
But the config screen shows the correct position on the map.

**Comment by GermanBluefox** [comment]
> => Coordinates in adapter are not updated from admin settings

Do you mean that astro events will not be calculated in this case?

**Comment by woessmich** [comment]
But with getObject('system.adapter.javascript.0').native.latitude) it does not use the system settings, even if set to use them in the javascript adapter settings. Only the latitude and longitude as set manually in the javascript adapter are used. Even if not active because it is set to use system settings.
I did not try the Astro events, but I assume they also will be calculated based on this and this only.

**Comment by GermanBluefox** [comment]
> But with getObject('system.adapter.javascript.0').native.latitude) it does not use the system settings, even if set to use them in the javascript adapter settings. Only the latitude and longitude as set manually in the javascript adapter are used. Even if not active because it is set to use system settings.

Works as designed.

> I did not try the Astro events, but I assume they also will be calculated based on this and this only.

No. The position for astro will be taken from system.config: https://github.com/ioBroker/ioBroker.javascript/blob/master/main.js#L1895
