### ISSUE TITLE
Clicking on the Tab "Scripts" does not open the Scripts-Editor

### ISSUE THREAD

**Issue by moobid** [ioBroker/ioBroker.javascript#827]
**Describe the bug**  
In IO Broker, clicking on the Tab "Scripts" does not open the Scripts-Editor. The page stays empty.

**Expected behavior**  
The Scripts-Editor should appear

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/5289345/116365235-5936d280-a805-11eb-8ceb-d6a152f34b3f.png)

**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1 // I recently updated this
 - Operating system: Linux raspberrypi4 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

**Additional context**  
I recently updated node.
Tested and verified on Chrome, Vivaldi and Edge.
Restarting the rasperrypi and scripts editor didn't help

**Comment by Apollon77** [comment]
Whixch Admin version?
What does Browser console tell?

**Comment by Apollon77** [comment]
... it also seems that some scripts and files are blocked in loading. Please check for the reasons

**Comment by moobid** [comment]
> Whixch Admin version?
Admin version: 4.2.1
> What does Browser console tell?
Browser console when clicking on Scripts:
Looks like about the same infos as in the Network tab:
![image](https://user-images.githubusercontent.com/5289345/116371809-1c220e80-a80c-11eb-987a-c0e175cd9c52.png)

**Comment by moobid** [comment]
> ... it also seems that some scripts and files are blocked in loading. Please check for the reasons
Yes, there are 6 files which return 404 NOT_FOUND. I dont know why.

**Comment by Apollon77** [comment]
please try "iobroker upload javascript" and a restart of iobroker including admin adapter

**Comment by moobid** [comment]
Thanks @Apollon77 ,
I executed `iobroker upload javascript`. No restart required and it works as expected:
The 404 errors in browser console are gone 👍 and the Scripts page shows up.

Du you like explain what happend and how `iobroker upload javascript` fixed the issue?

The output of the command (if someone is interested)
`> iobroker upload javascript
upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/html/htmlMode.js vs/language/html/htmlMode.js application/javascript
upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.it.js vs/editor/editor.main.nls.it.js application/javascript
upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/basic-languages/javascript/javascript.js vs/basic-languages/javascript/javascript.js application/javascript
upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/js/main.305439ec.chunk.js static/js/main.305439ec.chunk.js application/javascript
upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/index_m.html index_m.html text/html
upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/de.js google-blockly/own/msg/de.js application/javascript
upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/blocks_sendto.js google-blockly/own/blocks_sendto.js application/javascript
upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/msg/js/it.js google-blockly/msg/js/it.js application/javascript
upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handopen.cur google-blockly/media/handopen.cur null
upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handdelete.cur google-blockly/media/handdelete.cur null
upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handclosed.cur google-blockly/media/handclosed.cur null
upload [17] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/dropdown-arrow.svg google-blockly/media/dropdown-arrow.svg image/svg+xml
upload [16] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.wav google-blockly/media/disconnect.wav audio/wav
upload [15] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.ogg google-blockly/media/disconnect.ogg audio/ogg
upload [14] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.mp3 google-blockly/media/disconnect.mp3 audio/mpeg
upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.wav google-blockly/media/delete.wav audio/wav
upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.ogg google-blockly/media/delete.ogg audio/ogg
upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.mp3 google-blockly/media/delete.mp3 audio/mpeg
upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.wav google-blockly/media/click.wav audio/wav
upload [9] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg
upload [8] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.mp3 google-blockly/media/click.mp3 audio/mpeg
upload [7] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/1x1.gif google-blockly/media/1x1.gif image/gif
upload [6] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/javascript_compressed.js google-blockly/javascript_compressed.js application/javascript
upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blocks_compressed.js google-blockly/blocks_compressed.js application/javascript
upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blockly_compressed.js google-blockly/blockly_compressed.js application/javascript
upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/LICENSE google-blockly/LICENSE null
upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/asset-manifest.json asset-manifest.json application/json
upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript
Update "system.adapter.javascript.0"`

**Comment by BassT23** [comment]
+1
same error here, and also fixed with "iobroker upload javascript"

THX
