### ISSUE TITLE
kein blocky

### ISSUE THREAD

**Issue by Sylany** [ioBroker/ioBroker.javascript#829]
Hallo. Ich bin neu im Thema. Neuinstallation auf Himbeer-Pi 4 und Installation nur des Javascript-Adapters.
Nach dem Eingeben des Blocks werden keine Blöcke angezeigt, als ob der Block fehlt.

raspberrypi
Plattform
Linux
ACHSE
Linux
Die Architektur
Arm
Prozessoren
4
Geschwindigkeit
600 MHz
Modell
ARMv7-Prozessor Version 3 (v7l)
Widder
3,74 GB
Systemverfügbarkeit
01:36:31
Node.js
v12.22.1
NPM
6.14.13
Festplattengröße
116,95 GB
Freier Festplattenspeicher
114,78 GB
Adapter zählen
340
Arbeitszeit
00:31:55
Aktive Reden
5
Hostname
raspberrypi

**Comment by Apollon77** [comment]
Irgendwelche Fehler in der Browser Konsole?
