### ISSUE TITLE
Sendto Objekt

### ISSUE THREAD

**Issue by nicknick25** [ioBroker/ioBroker.javascript#83]
Das Sendto Objekt lässt sich nicht ins Script hinein ziehen. Es verschwindet immer wieder

EDIT by BuZZy1337:
Duplicate of https://github.com/ioBroker/ioBroker.javascript/issues/46

**Comment by GermanBluefox** [comment]
Screenshot? Browser console errors?

**Comment by moneyadmin** [comment]
![image](https://user-images.githubusercontent.com/10677129/37252157-a1126e2e-252d-11e8-9597-c9b448b05063.png)

**Comment by BuZZy1337** [comment]
Ist das hier noch aktuell @moneyadmin oder @nicknick25 ?
Kann den Fehler bei mir nicht nachstellen.
Falls Fehler noch vorhanden:
Welcher Block wird genau versucht zu verwenden? (Screenshot von der Blockauswahl?)

Danke.

**Comment by nicknick25** [comment]
Also bei mir ist es noch aktuell ich kann in Blockly den Block Sendto nicht in das Feld hineinziehen.

**Comment by BuZZy1337** [comment]
Hab alle durchprobiert welche unter SendTo zur Auswahl stehen. Funktionieren bei mir ohne Probleme.
Welcher Block ist das ganz genau den du da versuchst ins Feld zu ziehen?
Der, der auf meinem Screenshot oben Links zu sehen ist, also der "echte sendTo Block"?

Welche Javascript Adapter Version hast du installiert?

![image](https://user-images.githubusercontent.com/6979405/38805720-36de767c-4177-11e8-94cd-7e3f34e58917.png)

**Comment by nicknick25** [comment]
Wenn ich "Sendto" auswähle passiert das:

![unbenannt](https://user-images.githubusercontent.com/10033211/38809136-d12c9c26-4182-11e8-9caa-03ffec4e2040.PNG)


Ich kann keine Objekte im Block "Sendto" auswählen sobald ich nun versuche ein Objekt anzuklicken verschwindet die Auswahl.

**Comment by BuZZy1337** [comment]
Achsooo.. :smile: 
Kannst du mal bitte die Ausgabe von `iobroker list instances` auf der Kommandozeile hier posten?

**Comment by BuZZy1337** [comment]
Hast du das Problem schon immer gehabt dass die sendto Blöcke nicht korrekt angezeigt werden?
Oder ist es erst irgendwann "später" aufgetaucht?

**Comment by nicknick25** [comment]
Das hatte ich noch nicht immer gehabt das irgendwann aufgetaucht ich kann leider auch nicht mehr sagen wann weil ich ja nicht jeden Tag an die Scripte gehe.

**Comment by BuZZy1337** [comment]
Hast du noch irgendwelche Scripte auf dem System wo du eventuell den sendTo Block drin hast?
Eventuell ein Script mit dem sendTo Block mit einer Instanz die du gar nicht mehr installiert hast?

**Comment by nicknick25** [comment]
Nein keine Scripte mehr vorhanden.

**Comment by BuZZy1337** [comment]
Hast du irgendwelche Adapter zum Testen installiert gehabt und diese dann wieder deinstalliert gehabt?
Hab im Forum ein Beitrag gelesen wo einer das Problem hatte .. dann hat er den Cloud Adapter wieder installiert und das Problem war weg?

**Comment by nicknick25** [comment]
Eigentlich nicht

**Comment by Apollon77** [comment]
Vllt mal sicherheitshalber ein 

iobroker upload all 

Machen. Dann?

**Comment by nicknick25** [comment]
Apollon das geht leider auch nicht...

**Comment by BuZZy1337** [comment]
Fehler liegt denke ich hier:
https://github.com/ioBroker/ioBroker.javascript/blob/master/admin/google-blockly/own/blocks_sendto.js#L71

Eventuell sollten wir mit catch error den Fehler auffangen und bei Fehler auf Text input umschwenken wie es im else Abschnitt gemacht wird..?

Ich probiere zuhause mal ein bisschen was aus.

**Comment by BuZZy1337** [comment]
@nicknick25 bist du im ioBroker Forum?

Würde mir das Problem hier gerne mal noch genauer ansehen und brauche dich für 2-3 Tests.. :smile:

**Comment by nicknick25** [comment]
Moin joa ich bin unter dem Name Nicolas im Forum zu finden :)

**Comment by BuZZy1337** [comment]
Danke, habe dir eine Nachricht im Forum zukommen lassen. :relaxed:

**Comment by nicknick25** [comment]
Ich darf leider im Forum keine PN schreiben....

Deswegen schicke ich es dir hier 


![fehler](https://user-images.githubusercontent.com/10033211/38995017-2dcbe006-43e8-11e8-8f94-ffac934821b2.PNG)

**Comment by BuZZy1337** [comment]
@nicknick25 kein Problem.

Okay, habe nochmal was geändert.
Bitte nochmal genau so wie ich es in der Nachricht beschrieben habe nochmal drüber installieren.
(mit der gleichen URL)

Dann bitte nochmal testen und die Ausgabe der Console posten.

**Comment by GermanBluefox** [comment]
Es ist fast unmöglich da was zu finden. Welche Zusatz Module, die in
Blockly auftauchen, hast du? Telegram, Email?


Mach mal "iobroker upload all"

чт, 19 апр. 2018 г., 16:21 nicknick25 <notifications@github.com>:

**Comment by nicknick25** [comment]
Also Telegram hatte ich mal habe ich aber wieder Deinstalliert.

**Comment by BuZZy1337** [comment]
Dann installier mal Telegram Testweise wieder und versuch es nochmal.
Wie weiter oben schon geschrieben, hab im Forum irgendwo gelesen dass Leute Probleme hatten mit gelöschten Adaptern und Blockly..

**Comment by nicknick25** [comment]
Leider keine besserung

**Comment by 19Homer73** [comment]
Gibt es hier schon Neuigkeiten?
Habe leider das selbe Problem.

**Comment by nicknick25** [comment]
Moin zusammen gibt es schon Neuigkeiten bezüglich meines Problems?

**Comment by BuZZy1337** [comment]
@nicknick25 hast du das ( https://forum.iobroker.net/viewtopic.php?f=22&t=7302&p=129938&hilit=sendto+blockly#p129938 ) schon mal probiert?

**Comment by GermanBluefox** [comment]
Ist noch offen?

**Comment by BuZZy1337** [comment]
Nein, Fehler wurde in den Adaptern behoben.

War kein Fehler vom javascript Adapter.
