### ISSUE TITLE
Handling of objets in datapoints has to changed, because new js-controller only allows JSON

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#830]
[Änderungen im js-controller](https://github.com/ioBroker/ioBroker.js-controller/pull/1319) machen es erforderlich, die Behandlung von Datenpunkten vom Typ "object" und "array" zu ändern.

**Comment by Apollon77** [comment]
Wir könnten auch überlegen ob wir es im JS adapter intern konvertieren, sodass es für den user more convenient ist

**Comment by paul53** [comment]
Dann sollte es aber in beide Richtungen konvertiert werden, also auch bei getState() und on().

**Comment by JBSullivan** [comment]
Hat diese Meldung ggf. den gleichen Hintergrund?

`

javascript.0 | 2021-05-02 11:44:56.432 | info | (12856) State value to set for "javascript.0.scriptEnabled.Aktiv.BWM_Waschkueche" has to be type "boolean" but received type "undefined"
-- | -- | -- | --
javascript.0 | 2021-05-02 11:44:56.423 | info | (12856) State value to set for "javascript.0.scriptEnabled.Aktiv.BWM_Waschkueche" has to be type "boolean" but received type "undefined"

`

Hier der Blockly Code dazu - oder resultiert dieses aus den Meldungen die der Sonoff und der Alexa2.0 Adapter verursachen?

`<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="on_ext" id="xLsTqtSz$I0D[y|miT}]" x="-6663" y="-1037">
    <mutation xmlns="http://www.w3.org/1999/xhtml" items="1"></mutation>
    <field name="CONDITION">any</field>
    <field name="ACK_CONDITION"></field>
    <value name="OID0">
      <shadow type="field_oid" id="|[i9X!~,7B]as5deabD?">
        <field name="oid">zigbee.0.00158d000450b83b.occupancy</field>
      </shadow>
    </value>
    <statement name="STATEMENT">
      <block type="controls_if" id="{ybM5g3J.;.1lJ1?Mr1!">
        <mutation else="1"></mutation>
        <value name="IF0">
          <block type="logic_operation" id="hz8ac~*c0hfXD;b|Oa~4" inline="false">
            <field name="OP">AND</field>
            <value name="A">
              <block type="logic_compare" id="~X(i-uCif07|(M67{!n+">
                <field name="OP">EQ</field>
                <value name="A">
                  <block type="get_value" id="F64,B6`Ef072|mvq]Q/)">
                    <field name="ATTR">val</field>
                    <field name="OID">sonoff.0.Waeschetrockner.POWER</field>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_boolean" id="aBbjc-jJ~eTBop!.nnQ$">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
              </block>
            </value>
            <value name="B">
              <block type="logic_compare" id="FUSUsS*P0-hIn68(soc~">
                <field name="OP">EQ</field>
                <value name="A">
                  <block type="get_value" id="?I:r{B@ocgvA8F5VuUu$">
                    <field name="ATTR">val</field>
                    <field name="OID">zigbee.0.00158d000450b83b.occupancy</field>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_boolean" id="q(o%xSlD`+{0n$8N%Fj1">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
              </block>
            </value>
          </block>
        </value>
        <statement name="DO0">
          <block type="control" id="geD`MZW@lKU*luEHSOOQ">
            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
            <field name="OID">alexa2.0.Echo-Devices.G090XG0793042LJN.Commands.speak-volume</field>
            <field name="WITH_DELAY">FALSE</field>
            <value name="VALUE">
              <block type="math_number" id="j(YxDm+qyA2AF1Bs6tq:">
                <field name="NUM">25</field>
              </block>
            </value>
            <next>
              <block type="control" id="[My??KfjW|j@qB~[Tn+E">
                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                <field name="OID">alexa2.0.Echo-Devices.G090LF1071851DTD.Commands.announcement</field>
                <field name="WITH_DELAY">FALSE</field>
                <value name="VALUE">
                  <block type="text" id="t.w=LkOqQhhWDO,qGZ46">
                    <field name="TEXT">Wäschetrockner Steckdose ist bereits aktiv</field>
                  </block>
                </value>
              </block>
            </next>
          </block>
        </statement>
        <statement name="ELSE">
          <block type="control" id="pX?R?;MwH8d)(fW[PP$?">
            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
            <field name="OID">sonoff.0.Waeschetrockner.POWER</field>
            <field name="WITH_DELAY">FALSE</field>
            <value name="VALUE">
              <block type="logic_boolean" id="D,RzD73Ib@#NzBud+d$*">
                <field name="BOOL">TRUE</field>
              </block>
            </value>
            <next>
              <block type="control" id="tAW})d*~ru#U519U_m]w">
                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                <field name="OID">alexa2.0.Echo-Devices.G090XG0793042LJN.Commands.speak-volume</field>
                <field name="WITH_DELAY">FALSE</field>
                <value name="VALUE">
                  <block type="math_number" id="KO!BHwfixVn)!)[{}V/|">
                    <field name="NUM">25</field>
                  </block>
                </value>
                <next>
                  <block type="control" id=".Ro;0NJYFeoUL4?9^-g+">
                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                    <field name="OID">alexa2.0.Echo-Devices.G090LF1071851DTD.Commands.announcement</field>
                    <field name="WITH_DELAY">FALSE</field>
                    <value name="VALUE">
                      <block type="text" id="HE*ab4CM/*.zPs8]Woqo">
                        <field name="TEXT">Wäschetrockner Steckdose wurde aktiviert</field>
                      </block>
                    </value>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </statement>
        <next>
          <block type="controls_if" id="s9tiSveI$x=YG3S6k-y,">
            <mutation else="1"></mutation>
            <value name="IF0">
              <block type="logic_operation" id="3MZG`}u00UC0bw}VG4w|" inline="false">
                <field name="OP">AND</field>
                <value name="A">
                  <block type="logic_compare" id="@JpUOgLB$lj)8S7|@.Nv">
                    <field name="OP">EQ</field>
                    <value name="A">
                      <block type="get_value" id="fV[os@Z)2Bda,_2`gt%s">
                        <field name="ATTR">val</field>
                        <field name="OID">sonoff.0.Waschmaschine.POWER</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="logic_boolean" id="x@Y0%x+hKktywfeJ0zQH">
                        <field name="BOOL">TRUE</field>
                      </block>
                    </value>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_compare" id="@I)_U3`Z%?`RxEG|?$UE">
                    <field name="OP">EQ</field>
                    <value name="A">
                      <block type="get_value" id="pNZw0pDKgfAq)VdwDu![">
                        <field name="ATTR">val</field>
                        <field name="OID">zigbee.0.00158d000450b83b.occupancy</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="logic_boolean" id="@crNR;ZN.$2ci04YOX(+">
                        <field name="BOOL">TRUE</field>
                      </block>
                    </value>
                  </block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="control" id="G7WVwW:/3E?u@+lz-e|Q">
                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                <field name="OID">alexa2.0.Echo-Devices.G090XG0793042LJN.Commands.speak-volume</field>
                <field name="WITH_DELAY">FALSE</field>
                <value name="VALUE">
                  <block type="math_number" id="Y#bc{i]/ESSgK^HAJ*on">
                    <field name="NUM">25</field>
                  </block>
                </value>
                <next>
                  <block type="control" id="zvq.4*C]1GuJfef})6mI">
                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                    <field name="OID">alexa2.0.Echo-Devices.G090LF1071851DTD.Commands.announcement</field>
                    <field name="WITH_DELAY">FALSE</field>
                    <value name="VALUE">
                      <block type="text" id="?=9t6^o}crOHiaPiY=.I">
                        <field name="TEXT">Waschmaschinen Steckdose ist bereits aktiv</field>
                      </block>
                    </value>
                  </block>
                </next>
              </block>
            </statement>
            <statement name="ELSE">
              <block type="control" id="Y^9%!X@UHrYv72;Auf(8">
                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                <field name="OID">sonoff.0.Waeschetrockner.POWER</field>
                <field name="WITH_DELAY">FALSE</field>
                <value name="VALUE">
                  <block type="logic_boolean" id="KP7)k|.}8lsO74_;xa_U">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
                <next>
                  <block type="control" id="G:vU%`@?F_?XFO:ZCPv;">
                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                    <field name="OID">alexa2.0.Echo-Devices.G090XG0793042LJN.Commands.speak-volume</field>
                    <field name="WITH_DELAY">FALSE</field>
                    <value name="VALUE">
                      <block type="math_number" id="qG+exWKVC]!a`j#w7(QO">
                        <field name="NUM">25</field>
                      </block>
                    </value>
                    <next>
                      <block type="control" id="FBjvLg;-3c0FteQdFsyl">
                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                        <field name="OID">alexa2.0.Echo-Devices.G090LF1071851DTD.Commands.announcement</field>
                        <field name="WITH_DELAY">FALSE</field>
                        <value name="VALUE">
                          <block type="text" id="o5k:b+%xOH[~[4L=vvD9">
                            <field name="TEXT">Waschmaschinen Steckdose wurde aktiviert</field>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </statement>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="controls_if" id="Q,sE5Z=#=!Bmr}[L_Y*," x="-6213" y="-487"></block>
</xml>`

**Comment by Apollon77** [comment]
Ne der Fehler ist was amderes in JS Adapter intern und hat mit dem Skript selst zu tun. siehe #828  In dem Issue geht es um was anderes
