### ISSUE TITLE
Keine Anzeige mehr der Objekte nach admin Update auf 5

### ISSUE THREAD

**Issue by Chiller2019** [ioBroker/ioBroker.javascript#832]
**Describe the bug**  
Nachdem das Update von admin auf 5 gelungen ist, werden neu angelegte Scripte und Ordner angezeigt. Existieren tuen sie aber wenn ich alles exportieren lasse.
Man sieht übrigens auch das definitiv Ordner erstellt wurden (an der Zahl hinter dem Ordner)

**To Reproduce**  
1. JavaScript im Menü aufmachen
2. Ordner oder Skript erstellen (egal wo)
3. Fehler dann vorhanden

**Versions:**  
 - Adapter version: v 5.1.3
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: raspberrypi 5.10.17-v7l+

**Comment by Chiller2019** [comment]
Hat jemand vielleicht eine Temporäre Lösung?

**Comment by Apollon77** [comment]
Checke bitte nochmal den text ... der macht für mich keinen sinn. Bitte ggf Screenshot hinzufügen. Bitte auch Browser-Konsole nach Fehlern prüfen.

Welche Admin Version ist installiert?

**Comment by Chiller2019** [comment]
Das funktioniert jetzt leider nicht mehr. Beim fixen hab ich meine Image gekillt.

Aber dieser Fehler lässt sich definitiv reproduzieren.
Das war die aktuellste Admin-Version ... 5.0.10 und auch bei 5.0.12

Ein ähnliches Problem gibt es schon, dort wurde die Datei unbenannt und war auch nicht mehr sichtbar.

**Comment by Apollon77** [comment]
Letzteres sollte mit 5.0.12 gefixt gewesen sein

**Comment by Chiller2019** [comment]
So, jetzt hab ich alles auf Stable-Version. Frischer Raspberry bzw. iobroker.
Ein Ordner erstellt ... Siehe einfach an dem Bild und der "1".
![Clipboard01](https://user-images.githubusercontent.com/50303399/116826940-ea57d180-ab96-11eb-84bd-b20fe08b2be2.jpg)

**Comment by Chiller2019** [comment]
Fehler Gefunden, liegt am Browser. Mit dem Webkit funktioniert es.
