### ISSUE TITLE
Timeout not cleared with 5.1.3

### ISSUE THREAD

**Issue by sub0ne** [ioBroker/ioBroker.javascript#835]
**Describe the bug**  
Blocky script: Event A starts Timeout A to Execute in 10 minutes, Event B clears Timeout A, after 10 minutes Timeout A is executed anyway.

**Expected behavior**  
Time A should not be executed if cleared by Event B.

**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.2.16
 - Node version: v12.16.3 
 - Operating system: Raspbian Buster

**Comment by sub0ne** [comment]
`
// Katzen-Modus erkennen
on({id: 'deconz.0.Sensors.6.open', val: true}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  catModeTimeout = setTimeout(async function () {
    setState("javascript.0.custom.Keller.CatMode"/*CatMode*/, true);
  }, 600000);
});
on({id: 'deconz.0.Sensors.6.open', val: false}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  setState("javascript.0.custom.Keller.CatMode"/*CatMode*/, false);
  (function () {if (catModeTimeout) {clearTimeout(catModeTimeout); catModeTimeout = null;}})();
});
on({id: 'javascript.0.custom.Keller.CatMode', val: true}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  setState("deconz.0.Groups.2.on"/*Kellerbeleuchtung on*/, false);
});
`

**Comment by paul53** [comment]
Getestet mit JS Version 5.1.3: clearTimeout() arbeitet korrekt.
Verwende andere Trigger-Bedingungen!

**Comment by GermanBluefox** [comment]
Can you still reproduce it?

**Comment by paul53** [comment]
Kann geschlossen werden, da [geklärt](https://forum.iobroker.net/post/625558).
