### ISSUE TITLE
getIdByName returns undefined even if state with given name is available

### ISSUE THREAD

**Issue by tillsteinbach** [ioBroker/ioBroker.javascript#840]
**Describe the bug**  
I'm using getIdByName in my scripts and noticed after updating the controller that it always returns undefined

**To Reproduce**  
write script that contains getIdByName for a state with name that exists, check return value

```
function main() {
    console.log('return value:' + getIdByName('alive', true), 'debug');
}

setTimeout(main, 500);   // Zum Skriptstart ausführen
```

**Expected behavior**  
Expected to get array of ids
```
09:01:13.720 | info | javascript.0 (25270) Start javascript script.js.tests
09:01:13.725 | info | javascript.0 (25270) script.js.tests: setTimeout(ms=500)
09:01:13.725 | info | javascript.0 (25270) script.js.tests: registered 0 subscriptions and 0 schedules
09:01:14.226 | info | javascript.0 (25270) script.js.tests: getIdByName(name=alive, alwaysArray=true) => undefined
09:01:14.227 | info | javascript.0 (25270) script.js.tests: return value:undefined
```

**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.3.8
 - Node version: v12.22.0
 - Operating system: Linux a13bc9cf65eb 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 GNU/Linux
 - On Docker!

**Comment by Apollon77** [comment]
Which controller Update you mean? from 3.1.x to 3.2.16?
Nothing was really changed for that since longer time ... Can you show your Javascript adapter config please?

**Comment by Apollon77** [comment]
Can you please post the raw object JSON from an object you expect to be found there?

**Comment by GermanBluefox** [comment]
> Yes, but I think the problem is somewhere else:
> It now works again.
> What I did when it wasn't working is: I deleted the states and let the adapter recreate those. When I used the states I got undefined. Now I restarted the whole docker container and the same states are found.
> So it looks like getIdByName was not able to find those newly crated states

Do you understand the difference between two console outputs?
```
createState('point', {name: 'Point5'}, () => {
    // 1. here State "point" with name "Point5" does exist
    console.log(JSON.stringify(getIdByName('Point5', true))); // => ["javascript.0.point"]
});
// 2. Here the state does not exist
console.log(JSON.stringify(getIdByName('Point5', true))); // => undefined
```

**Comment by Apollon77** [comment]
could beb retested after https://github.com/ioBroker/ioBroker.javascript/pull/964 got merged

**Comment by Apollon77** [comment]
Please check with 5.4.x
