### ISSUE TITLE
 Handling of themes for Admin5 React UI and javascript editor

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#841]
Admin 5.0.21
Javascript Adapter: 5.1.3
Previous discussion: https://github.com/ioBroker/ioBroker.admin/issues/868

With Admin 5 it is possible to change the theme of the ReactUI (dark, light)

The Javascript Adapter supports in the editor as well the possibility to change the theme for the editor independently from Admin5 settings.

Is there still a need to have both possiblities to change the theme? Otherwise I would suggest that the javascript editor uses the same theme which is chosen in Admin5 UI.

**Comment by Feuer-sturm** [comment]
Admin v5.1.25
 Javascript Adapter: 5.2.8

With the mentioned configuration of Admin5 and Javascript Adapter it is possible to change the theme by clicking on the theme button of admin -> ok

From my point of view there is no need to have this menu in Javascript Adapter in the futue because the theme can be changed by Admin5 theme button.
![grafik](https://user-images.githubusercontent.com/25422320/130367912-77a27609-7f07-4ba8-9a89-9f33b3c6069e.png)

**Comment by Apollon77** [comment]
Correct, now with Admin5 it can be removed here together with Expertmode
