### ISSUE TITLE
Fehlermeldung bei LOGIC-Block: Der Fall ist..

### ISSUE THREAD

**Issue by marios774** [ioBroker/ioBroker.javascript#842]
Beim Einfügen des Blocks: Der Fall ist.. kommt es zu Fehlermeldungen wenn ich ein -Wert von Block-ID- Block andocken möchte.

<img width="528" alt="Bildschirmfoto 2021-05-15 um 15 31 33" src="https://user-images.githubusercontent.com/32393760/118363024-b915d300-b592-11eb-8e76-719712ddc3f9.png">

<img width="631" alt="Bildschirmfoto 2021-05-15 um 15 31 48" src="https://user-images.githubusercontent.com/32393760/118363031-c03ce100-b592-11eb-9641-dd6a680f21af.png">

Das passiert sowohl mit ausgewählter Variable, als auch als leerer Block.

Versions:
 - Adapter version: v5.1.3
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0 
 - Operating system: linux x64 (Parallels-VM)

**Comment by GermanBluefox** [comment]
Should be fixed now
