### ISSUE TITLE
States Wert in common

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.javascript#846]
Typen Überprüfung prüfen

![image](https://user-images.githubusercontent.com/25475385/119832914-ee111680-befe-11eb-91af-66f5f011bf3c.png)

**Comment by GermanBluefox** [comment]
@AlCalzone Do you know how to fix it?

**Comment by duczzz** [comment]
Okay thanks, its a Javascript

**Comment by AlCalzone** [comment]
FYI this should work without warnings when #878 is merged and released.
