### ISSUE TITLE
Please move block "bind object ..." from System to Trigger

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#855]
Da der Block "binde object ..." einen Trigger enthält, führt das zu Verwirrungen, wenn er unter "System" angeboten wird.

**Comment by GermanBluefox** [comment]
Hm... Die Idee dahinter ein ID mit anderen zu verbinden. Was hat mit Trigger zu tun?

**Comment by paul53** [comment]
Ist das kein Trigger?
`on({id: 'Object ID 1', change: "ne"}, function (obj) {
  setState('Object ID 2', obj.state.val);
});`

**Comment by paul53** [comment]
Nein. Das Wesentliche ist der Trigger auf "Object ID 1". Anfänger erkennen dies nicht und verwenden diesen Block innerhalb von Triggern.
