### ISSUE TITLE
Scripts are shown in script.js with deactivated expert mode

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#856]
Admin 5.1.9
js-controller 3.3.14
Javascript Adatper 5.1.3

Bug: Scripts are shown partially in script.js with deactivated expert mode

![grafik](https://user-images.githubusercontent.com/25422320/123474713-a911fa00-d5fa-11eb-9509-1e67f287c076.png)

Expert mode activated:
![grafik](https://user-images.githubusercontent.com/25422320/123474813-d2cb2100-d5fa-11eb-9a57-7ebe3fc8842b.png)

Expected behavior:
If expert mode is not activated no scripts are shown in " script.js "

First analysis from @Apollon77 :+1: 
- Device/Channel Objects shall be created with "expertOnly" Flag 
- Skripts needs to be updated on startup if no expert flag is set

Discussion in forum: https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/830

Additional informations:
fresh installation with ioBrokder Admin 5.1.9, js-controller 3.3.14, javascript 5.1.3 and no scripts are available:
![grafik](https://user-images.githubusercontent.com/25422320/123473122-6e0ec700-d5f8-11eb-88bf-a55773c992b2.png)

Two scripts created and expert mode is deactivated: 
![grafik](https://user-images.githubusercontent.com/25422320/123473196-84b51e00-d5f8-11eb-88d1-3acb0d6d9a17.png)

Activate expert mode:
![grafik](https://user-images.githubusercontent.com/25422320/123473244-972f5780-d5f8-11eb-8dfa-840e0694c9c7.png)

**Comment by GermanBluefox** [comment]
Das ist das Problem vom admin

**Comment by Feuer-sturm** [comment]
@GermanBluefox Soll ich das Ticket hier zu machen und beim Admin einstellen?

**Comment by Apollon77** [comment]
@GermanBluefox really admin?
@Feuer-sturm Could you please check the objects and check is the "expertsonly" is present in the objects that are displayed? If yes then yes it is an admin issue. If it is messing I personally more see it as Javascript issue to fix existing/older objects

**Comment by Feuer-sturm** [comment]
Testsetup Admin 5.1.9, js-controller 3.3.14, Javascript Adatper 5.1.3
Here is a channel and a skript which is shown with deactivated expert mode

```
{
  "common": {
    "name": "Kalender",
    "expert": true
  },
  "type": "channel",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1610052973647,
  "_id": "script.js.Skripte.Kalender",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```
```
{
  "_id": "script.js.Skripte.Kalender.ical_4_ToHtmlTable",
  "common": {
    "name": "ical_4_ToHtmlTable",
    "engineType": "JavaScript/js",
    "source": "// Script stammt von ...... \r\n ",
    "enabled": true,
    "engine": "system.adapter.javascript.0",
    "debug": false,
    "verbose": false
  },
  "type": "script",
  "native": {},
  "ts": 1616985737241,
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```


 fresh installation with ioBrokder Admin 5.1.9, js-controller 3.3.14, javascript 5.1.3 
Here is a channel and a skript which is NOT shown with deactivated expert mode
```
{
  "common": {
    "name": "ToDo",
    "expert": true
  },
  "type": "channel",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1624574359975,
  "_id": "script.js.ToDo",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```
```
{
  "common": {
    "name": "test2",
    "expert": true,
    "engineType": "Javascript/js",
    "engine": "system.adapter.javascript.0",
    "source": "",
    "debug": false,
    "verbose": false
  },
  "type": "script",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1624574367620,
  "_id": "script.js.ToDo.test2",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by GermanBluefox** [comment]
I think it is superfluous to modify existing scripts, as the issue is not critical.
After the script is modified, it will have expert flag in 5.2.9
