### ISSUE TITLE
Blockly - Textausgabe Wochentag als Text immer Donnerstag

### ISSUE THREAD

**Issue by zokkai** [ioBroker/ioBroker.javascript#857]
Wochentag wird über Datenpunkt erzeugt und wird über _Wochentag als Text_ ausgegeben.
Egal welche Zahl übergeben wird, die Textausgabe ist **IMMER** _Donnerstag_. 

![image](https://user-images.githubusercontent.com/49320831/123548045-7cc5bd00-d763-11eb-9026-cff9076019d8.png)

 - Adapter version: 5.1.4
 - JS-Controller version: 3.3.11
 - Node version: 14.17.0
 - Operating system: Raspberry / Buster

**Comment by GermanBluefox** [comment]
Welcher Wert is in "Next week day Bio Tonne"?

![image](https://user-images.githubusercontent.com/4582016/131827298-0838dd74-4de3-4c15-9ed5-c872ba2290b4.png)
