### ISSUE TITLE
Script Editor öffnet nicht

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.javascript#861]
Hallo.

Beim Versuch den Script Editor zu starten wird nur das animierte ioBroker Logo angezeigt, es öffnet sich nicht der Editor.

![Nur ioBroker Logo](https://user-images.githubusercontent.com/17329042/124418803-91561680-dd5c-11eb-8786-5f5ae1e8a5c2.jpg)

Im Log erscheinen keine Fehlermeldungen.

**Versions:**  
 - Adapter version: 5.2.0
 - JS-Controller version: 3.3.14
 - Node version: 12.22.2, NPM: 6.14.13
 - Operating system: Windows 10
 - Admin Version: 4.2.1

**Comment by Apollon77** [comment]
Steht in der Browser Konsole irgendwas?

**Comment by Apollon77** [comment]
For me it works with Admin5 ...

**Comment by UweRP** [comment]
@Apollon77 was meinst du mit Browser Konsole?

Was ich danach versucht habe, ist die Version 5.1.3 wieder zu installieren was aber mit einer Fehlemeldung beendet wurde.
Habe dann versucht auf die 5.1.0  zu gehen was laut Log ohne Fehler beendet wurde, allerdings startete dann der Adapter nicht mehr und ich habe das Backup meiner Installation zurück gespielt/kopiert.
Wir können nun gerne nach deiner Anleitung spielen/versuchen.
Aktuell bin ich mit dem Adapter auf 5.1.3 durch zurückkopieren des Backups. Läuft nun wieder ohne Auffälligkeiten.

**Comment by Apollon77** [comment]
Ich lass emal was prüfen, aber meine Vermutung ist das eine Änderung in Javascript Adapter jetzt Admnin 5 voraussetzt ...

Und mit Browser-Konsole meine ich die ENtwickelrtool sim Browser und dort die Fehlerkonsole

**Comment by UweRP** [comment]
@Apollon77 Ok, danke für die schnelle Info

**Comment by Apollon77** [comment]
I checked the changes and they normally do not look breaking ... can you please try to install 5.2.0 again and see what the browser console tells you on error?

**Comment by Apollon77** [comment]
Ok, we will rely on admin 5 with javascript 5.2 ... I will adjust that for 5.2.1

**Comment by UweRP** [comment]
Ich setzte die Ausgabe der Browser Konsole trozdem mal hier ein, vielleicht hilfts noch :-)

`admin.js:1489 clear
DevTools failed to load source map: Could not load content for https://10.111.112.39:8081/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:20 iobroker.javascript@5.2.0 using theme "colored"
instrument.ts:129 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

instrument.ts:129 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
instrument.ts:129 Help us to create open source project with reactJS!
instrument.ts:129 See you :)
DevTools failed to load source map: Could not load content for chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/lib/tp/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://10.111.112.39:8081/adapter/min-maps/vs/loader.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://10.111.112.39:8081/adapter/min-maps/vs/editor/editor.main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
fetch.ts:138 POST https://sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7 403 (Forbidden)
(anonymous) @ fetch.ts:138
e @ syncpromise.ts:34
(anonymous) @ fetch.ts:137
e.add @ promisebuffer.ts:29
t._sendRequest @ fetch.ts:135
t.sendSession @ fetch.ts:100
e.sendSession @ basebackend.ts:108
e._sendSession @ baseclient.ts:262
e.captureSession @ baseclient.ts:164
e._sendSessionUpdate @ hub.ts:465
e.captureSession @ hub.ts:405
(anonymous) @ sdk.ts:208
g @ sdk.ts:95
451 @ index.js:37
l @ tab.html:1
t @ tab.html:1
r @ tab.html:1
(anonymous) @ main.c0c3eab2.chunk.js:1
DevTools failed to load source map: Could not load content for https://10.111.112.39:8081/adapter/min-maps/vs/editor/editor.main.nls.de.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

**Comment by Apollon77** [comment]
Hm ... no relevant error ...strange

**Comment by UweRP** [comment]
Ich habe es ausprobiert und Admin 5 nun installiert. Damit funktioniert der Aufruf des Editors des Script Adapters >5.1.3 auch bei mir.
Damit kann dann hier endgültig zu gemacht werden.
