### ISSUE TITLE
Info Adapter Warnmeldungen nach Update auf 5.2.0

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.javascript#862]
Nach dem Update auf 5.2.0 schmeißt der Info Adapter bei mir jede Menge Warnmeldungen raus:

`
<html><body>

javascript.0 | 2021-07-05 10:57:34.334 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
javascript.0 | 2021-07-05 10:57:34.334 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.333 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 | 2021-07-05 10:57:34.325 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token ,  in JSON at position 8
javascript.0 | 2021-07-05 10:57:34.325 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.324 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.324 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 | 2021-07-05 10:57:34.322 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token ,  in JSON at position 8
javascript.0 | 2021-07-05 10:57:34.315 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.315 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.314 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 | 2021-07-05 10:57:34.313 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token ,  in JSON at position 10
javascript.0 | 2021-07-05 10:57:34.312 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.312 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.311 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 | 2021-07-05 10:57:34.284 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token ,  in JSON at position 10

</body>
</html>`

Downgrade auf 5.1.3 behebt das Problem.

Admin: 5.1.9
Info: 1.7.15
JS-Controller: 3.2.16
Node: 12.22.2

**Comment by Apollon77** [comment]
Was ist denn der Inhalt des Angemeckerten States

info.0.sysinfo.disks.fsSize.fs0.used_hist ?

**Comment by Apollon77** [comment]
Effektiv bedeutet der Fehler das ein Adapter einen State inkorrekt schreibt und damit der Wert nicht geparst werden kann. Ist erstmal nur eine Warnung

**Comment by Speedbreaker12** [comment]
> 
> 
> Was ist denn der Inhalt des Angemeckerten States
> 
> info.0.sysinfo.disks.fsSize.fs0.used_hist ?
Das hier: 
`4237189120,4237189120,4237189120,4237189120,4237189120,4235051008,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237197312,4237197312,4237197312,4237197312,4237197312,4237197312`

**Comment by Apollon77** [comment]
Wie vermitet. ist ein falscher Inhalt für den Objekttyp "array". Bitte beim Info Adapter ein Issue öffnen.

Jetzt ist die Farge wie wir da mit dem Logging umgehen - ggf loggen ohne stack trace und nur als Info ... aber loggen würde ich es

**Comment by Speedbreaker12** [comment]
> 
> 
> Wie vermutet. ist ein falscher Inhalt für den Objekttyp "array". Bitte beim Info Adapter ein Issue öffnen.
> 
> Jetzt ist die Farge wie wir da mit dem Logging umgehen - ggf loggen ohne stack trace und nur als Info ... aber loggen würde ich es

Der falsche Objekttyp ist ja wirklich ein Fehler des Info Adapters, darum sollte es auch gelogged werden.
Ich habe ein Issue beim Info Adapter ist erstellt und warte erstmal mit dem Update auf 5.2.0 bis das behoben wurde.

**Comment by Apollon77** [comment]
Ich ändere im JavaScript adapter das logging (5.2.1 kommt später) ... adapterfehler werden dann nicht mehr geloggt - darum muss sich der controller kümmern. Er loggt es als info für javascript.* oder 0_userdata.0* state ids - die kommen vom user :-)

**Comment by Apollon77** [comment]
5.2.1. on the way
