### ISSUE TITLE
Cannot install npm packet: setbject

### ISSUE THREAD

**Issue by CreamyCewie22** [ioBroker/ioBroker.javascript#867]
**Describe the bug**  
I try to add "setObject" Module to js-adapter and recieve the following error:

> javascript.0 | 2021-07-11 20:17:32.440 | error | (9706) Cannot install npm packet: setObject
> -- | -- | -- | --
> javascript.0 | 2021-07-11 20:17:32.439 | error | (9706) Cannot install setObject: 1
> javascript.0 | 2021-07-11 20:17:32.428 | error | npm ERR!     /home/iobroker/.npm/_logs/2021-07-11T18_17_32_416Z-debug.log
> javascript.0 | 2021-07-11 20:17:32.428 | error | (9706) npm ERR! A complete log of this run can be found in:
> javascript.0 | 2021-07-11 20:17:32.426 | error | (9706)
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404 tarball, folder, http url, or git url.
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404 Note that you can also install from a
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404  1. name can no longer contain capital letters
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404 Your package name is not valid, because
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404  'setObject@latest' is not in the npm registry.
> javascript.0 | 2021-07-11 20:17:32.415 | error | npm ERR! 404
> javascript.0 | 2021-07-11 20:17:32.415 | error | (9706) ERR! 404 Not Found - GET https://registry.npmjs.org/setObject - Not found
> javascript.0 | 2021-07-11 20:17:32.412 | error | (9706) npm
> javascript.0 | 2021-07-11 20:17:32.403 | error | (9706)  ERR! code E404
> javascript.0 | 2021-07-11 20:17:32.401 | error | (9706) npm
> javascript.0 | 2021-07-11 20:17:30.459 | info | (9706) npm install setObject --production (System call)
> 

Output of log-file:

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/usr/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   'setObject',
> 1 verbose cli   '--production'
> 1 verbose cli ]
> 2 info using npm@6.14.12
> 3 info using node@v12.22.1
> 4 verbose npm-session f96373c813c83a9e
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 404 https://registry.npmjs.org/setObject 209ms
> 8 http fetch GET 404 https://registry.npmjs.org/setObject 42ms
> 9 silly fetchPackageMetaData error for setObject@latest 404 Not Found - GET htt$
> 10 timing stage:rollbackFailedOptional Completed in 3ms
> 11 timing stage:runTopLevelLifecycles Completed in 647ms 
> 12 verbose stack     at processTicksAndRejections (internal/process/task_queues$
> 13 verbose statusCode 404
> 14 verbose pkgid setObject@latest
> 15 verbose cwd /opt/iobroker/node_modules/iobroker.javascript
> 16 verbose Linux 5.10.17-v7l+
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "setObject" "--product$
> 18 verbose node v12.22.1
> 19 verbose npm  v6.14.12
> 20 error code E404
> 21 error 404 Not Found - GET https://registry.npmjs.org/setObject - Not found
> 22 error 404
> 23 error 404 'setObject@latest' is not in the npm registry.
> 24 error 404 Your package name is not valid, because
> 25 error 404 1. name can no longer contain capital letters
> 26 error 404 Note that you can also install from a
> 27 error 404 tarball, folder, http url, or git url.
> 28 verbose exit [ 1, true ]

**To Reproduce**  
1. Add "setObject" to js-adapter
2. Restart js-adapter
3. go to iobroker-logs

**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: Raspbian

**Comment by Apollon77** [comment]
Ok, how does your config look like? Could it be that you entered "setObject" in the list of npm packages to install?
