### ISSUE TITLE
[Problem] Problem when moving script groups

### ISSUE THREAD

**Issue by roe19xx** [ioBroker/ioBroker.javascript#87]
I'amnot sure if this issue is a issue of the javascript adapter or the admin adapter. Please move it if it is a admin issue.

When creating a new child group this is working fine. If i will move this new group to top level (choosing "no group" as parent group) then i will see this new goup in top level but it is still existing as a child group (it is existing twice).
This isn't just a browser cache issue. I have to remove the child group in group menu then to get a clean solution.

Tested with Admin 3.2.3 and Javascript 3.6.4
Browser: Firefox 58.0.2 (64-Bit)

Steps:
![grafik](https://user-images.githubusercontent.com/36137769/37239774-82d71f46-2441-11e8-9e93-79b2f44c5117.png)

![grafik](https://user-images.githubusercontent.com/36137769/37239782-9e4e17ca-2441-11e8-8296-4ab2e6dcbd58.png)

![grafik](https://user-images.githubusercontent.com/36137769/37239810-da69aac6-2441-11e8-84b9-b1d9f2e05a55.png)

**Comment by GermanBluefox** [comment]
Not more relevant, because new interface
