### ISSUE TITLE
WARN  Scripts don't work!!!!!!!!!!!

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.javascript#871]
`
<html>
<body>

javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at Timer.processTimers (timers.js:223:10)
-- | -- | -- | --
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at listOnTimeout (timers.js:263:5)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at tryOnTimeout (timers.js:300:5)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at ontimeout (timers.js:436:11)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:510:7)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:552:11
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at Job.nodeSchedule.scheduleJob [as job] (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1301:34)
javascript.0 | 2021-08-02 11:47:00.028 | warn | (424) at Object.<anonymous> (script.js.Кондиционер:49:13)
javascript.0 | 2021-08-02 11:47:00.027 | warn | (424) at result (script.js.Кондиционер:58:9)
javascript.0 | 2021-08-02 11:47:00.027 | warn | (424) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1427:20)
javascript.0 | 2021-08-02 11:47:00.024 | warn | (424) You are assigning a boolean to the state "mqtt.0.haier.Power" which expects a string. Please fix your code to use a string or change the state type to boolean. This warning might become an erro

</body>
</html>`

![image](https://user-images.githubusercontent.com/11523624/127805855-a749a92f-6273-47cf-952b-fd901278315e.png)

Why is Iob not converting types?

**Comment by Apollon77** [comment]
Because auto conversion can lead to more issues then it solves? (At least in my opinion)
