### ISSUE TITLE
createState do not stringify object types correctly

### ISSUE THREAD

**Issue by sinky** [ioBroker/ioBroker.javascript#872]
**Describe the bug**  
With createState the date is stored as "Date"-Object and shown in objects like this
![1](https://user-images.githubusercontent.com/822246/129489165-39318a5a-55b0-4078-8d7d-b1e28dc1383b.png)

On subsequently runs, setState stores the date with quotes and shown in objects like this
![grafik](https://user-images.githubusercontent.com/822246/129489184-2d4465dd-d051-4476-8c7e-e34320cdc563.png)

And now can't be used on VIS Date Widget

**To Reproduce**  
Run this script two times and 
```
if ( !existsState('0_userdata.0.testDate') ) {
  createState('0_userdata.0.testDate', new Date(), {name: 'testDate',  type: 'object', role: 'value'}); 
} else {
  setState('0_userdata.0.testDate', new Date());
}
```
**Expected behavior**  
createState and setState should save the same data exactly the same

**Versions:**  
 - Adapter version: 5.2.8
 - JS-Controller version: 3.3.15
 - Node version: v12.22.1
 - Operating system: Raspbian GNU/Linux 10

**Comment by Apollon77** [comment]
Lets say it that way: createState has the bug. Objects needs to be stored stringified and setState is doing that correctly as required, it seems that createState was mnot adjusted.

And BTW: To store a date better use a type "string" with role date or "Number" with date (see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#common) ...

**Comment by sinky** [comment]
ok sting/date works for me

**Comment by GermanBluefox** [comment]
In 5.2.9 the createState uses the same function as setState
