### ISSUE TITLE
Rules: "unexpected char im JSON" after drop action on a rules block

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.javascript#876]
das Ziehen eines Zeitrigers verursacht einen weissen Bildschirm.. wie es im Video zu sehen ist

![video](https://user-images.githubusercontent.com/6681528/131246258-408fdeca-cd5b-4fdb-9bc7-4ae211c1e362.mp4)

entsprechend in der Console ist der Fehler 

![grafik](https://user-images.githubusercontent.com/6681528/131246243-5dde2f8d-2311-4a14-a350-7ae4df014980.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.2.9
