### ISSUE TITLE
Addition Blocky

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.javascript#879]
Beim Versuch zwei Werte zu addieren wird die Zahl an die vorhandene angehängt anstatt zu addieren.
Kann das jemand nachvollziehen, ist das normal?

![Addition](https://user-images.githubusercontent.com/17329042/132114056-88955e22-ea03-4acb-b36e-b47bd2eb8ff2.jpg)

Objektdaten
```
{
  "common": {
    "name": "javascript.0.Steuerungsflags.Azimut",
    "role": "state",
    "type": "mixed"
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.javascript.1",
  "user": "system.user.admin",
  "ts": 1630810728019,
  "_id": "javascript.0.Steuerungsflags.Azimut",
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

```
System ist Windows 10 mit Node 12.22.6, javascript Adapter 5.2.9.

**Comment by Apollon77** [comment]
Naja ... wenn "Azimut ein String ist dann wäre das genau das erwartete verhalten in JavaScript... Sicher das da eine Zahl (typ number" drun steht? Der eine wo es geht mit "nahZahl" zeigt meinen Verdacht ... da steht ein String drin.

Also schau was Du da reinschreibst

**Comment by UweRP** [comment]
Ja Ingo, in JavaScript mag das so sein. Aber Ich nutze Blockly, da sollte ich doch erwarten, wenn ich einen **Mathematik** Baustein benutze, dass dann auch gerechnet wird oder ein Fehler kommt wenn der Typ nicht stimmt zumal die Multiplikation und Subtraktion wie erwartet funktioniert und gerechnet wird.

Leider kann ich kein JavaScript daher benutze ich Blockly.
Azimut wird von folgendem Script geschrieben, habe ich so aus dem ioBroker Forum.

```
/* System Sonnenstand

Sonne Azimut und Elevation in Variablen schreiben

erstellt: 06.07.2015 nach ioBroker Forum http://forum.iobroker.net/viewtopic.php?f=21&t=975&sid=6f0ba055de5f82eed6809424f49ca93b#p7635
*/
var Elevation = "javascript.0.Steuerungsflags.Elevation";
var Azimut = "javascript.0.Steuerungsflags.Azimut";

var suncalc = require('suncalc'),
    result = getObject("system.adapter.javascript.0"),
    lat = 1.00000 // zum posten verfälscht result.native.latitude,
    long = 1.0000 // zum posten verfälscht result.native.longitude;



createState(Elevation, 0) ; // , {unit: 'Â°'});
createState(Azimut, 0) ; // , {unit: 'Â°'});

function Sonnenstand_berechnen () {
    var now = new Date();
        

    var sunpos = suncalc.getPosition(now, lat, long);

    var h = sunpos.altitude * 180 / Math.PI,
        a = sunpos.azimuth * 180 / Math.PI + 180;

     setState(Elevation,h.toFixed(1)); /*sonne_elevation*/
     setState(Azimut,a.toFixed());  /*sonne_azimut*/
      
}

schedule("*/5 * * * *", Sonnenstand_berechnen); // aal 5 Minuten zur vollen Minute
Sonnenstand_berechnen(); // bei Scriptstart


```

**Comment by GermanBluefox** [comment]
Geändert. Jetzt wird parseFloat gemacht.
