### ISSUE TITLE
[Problem] Scriptname and Code will be remove when switching Instances

### ISSUE THREAD

**Issue by roe19xx** [ioBroker/ioBroker.javascript#88]
Same here. Not sure if it is related to Javascript or Admin Adapter. Please move this issue if required.

Problem:
When creating a new script (javascript), i fill in scriptname, put in my code. Then before i've saved this new script i will script javascript instance (because i use 0 for TEST and 1 for PRD).
When switching the instance, then scriptname will be set to default name "Skript1" and code was removed.

Tested in Admin 3.2.3 and Javascript Adapter 3.6.4

![grafik](https://user-images.githubusercontent.com/36137769/37239895-e0c7ee4a-2442-11e8-83f1-87db9a4a9828.png)

![grafik](https://user-images.githubusercontent.com/36137769/37239902-ff704ee6-2442-11e8-9bed-9e440d3ae135.png)

When testing the same in another ioBroker Installation with Admin 3.2.0 and Javascript Adapter 3.5.1 then the Instance Switch won't remove Scriptname or Coding.

Browser: Firefox 58.0.2 (64-Bit) for both Testscenarios.

**Comment by GermanBluefox** [comment]
Not more relevant because of new interface
