### ISSUE TITLE
Nach Update auf 5.2.11 Fehler in setTimeout()

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.javascript#881]
Nach Update auf 5.2.11 werden setTimeout() und clearTimeout() als unbekannt angezeigt. Werfen auch entsprechende Fehler aus.

Wobei ich dieses Update ca. 5 mal durchgeführt habe weil er auf .10 stehen geblieben ist.

**Comment by Apollon77** [comment]
bitte log zeigen

**Comment by Apollon77** [comment]
which version you had before?

**Comment by ticaki** [comment]
vorher hatte ich 5.2.10

Skriptcode:
`            if (j[a].sleep === undefined) return;
            if (j[a].wake==0) {
                j[a].wake=new Date();
                if (timeout) clearTimeout(timeout);
                timeout = setTimeout(function(){
                    sendTelegram(j[a], j);
                },5*60*1000);
            }
`
log:
`
2021-09-12 11:37:04.951 - error: javascript.0 (1627) Error in callback: TypeError: Cannot read property 'sleep' of undefined
--
2021-09-12 11:37:04.952 - error: javascript.0 (1627) at sendTelegram (script.js.common.Schlafenszeit_&_Nachmodus:60:96)
2021-09-12 11:37:04.952 - error: javascript.0 (1627) at Object. (script.js.common.Schlafenszeit_&_Nachmodus:36:21)
2021-09-12 11:37:04.952 - error: javascript.0 (1627) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2119:34)
2021-09-12 11:37:04.953 - error: javascript.0 (1627) at listOnTimeout (internal/timers.js:554:17)
2021-09-12 11:37:04.953 - error: javascript.0 (1627) at processTimers (internal/timers.js:497:7)
`

**Comment by Apollon77** [comment]
Liess mal die Fehler meldung richg!!

> TypeError: Cannot read property 'sleep' of undefined

Das musst du fixen. der Timeout und sowas tut

j[a] is undefined und daher wirt der zugriff auf j[a].sleep einen fehler

**Comment by ticaki** [comment]
Möglich, das Skript läuft schon seit rund 1,5 Jahren ohne Probleme und beim überprüfen mit .11 wurde mir clearTimeout und setTimeout als unbekannt angezeigt.

**Comment by Apollon77** [comment]
zeit gavon mal einen Screenshot bitte - und auch: Wenn es in der Web IDE rot unterkringelt wird heisst das erstmal nicht soo viel ... abe rja DAS müssen wir ansehen - dann ist was in den typings blöd.

Aber der Fehler kommt definieiv aus deinem Skript! Du musst vor dem Zugriff prüfen das Datenstrukturen da sind. Diesnbezüglich sollte ch n .11/12 nchs gändert

**Comment by ticaki** [comment]
Das dieses Json undefiniert ist wird vorher schon abgefragt, aber der Fehler lies sich nicht reproduzieren. Damit ist er nicht existent. :)

hier ein Foto von .11 ich war heute vormittag zurück gegangen auf .9 und dort wurde setTimeout() nicht als Fehler angezeigt.
![Bildschirmfoto 2021-09-12 um 16 54 56](https://user-images.githubusercontent.com/59184294/132992839-2f039871-334e-458f-aa9a-7c42935f21e8.png)

**Comment by Apollon77** [comment]
> Das dieses Json undefiniert ist wird vorher schon abgefragt, aber der Fehler lies sich nicht reproduzieren. Damit ist er nicht existent. :)

Du meins Die Zeile mit j[a].sleep === undefined?? Darum geht es nicht!!  j[a] ist undefined!!

**Comment by Apollon77** [comment]
@AlCalzone @GermanBluefox Please check the screenshot above

**Comment by AlCalzone** [comment]
Der Adapter kann die Typdeklarationen für Node.js nicht laden. Ich hätte schwören können, ich habe das in https://github.com/ioBroker/ioBroker.javascript/pull/878 gefixt, aber die betroffene Datei scheint da nicht enthalten zu sein.

**Comment by AlCalzone** [comment]
PR up at https://github.com/ioBroker/ioBroker.javascript/pull/882
![grafik](https://user-images.githubusercontent.com/17641229/133004804-98396e57-d049-40a2-b45f-2e93bb543bf9.png)

**Comment by ticaki** [comment]
> Du meins Die Zeile mit j[a].sleep === undefined?? Darum geht es nicht!! j[a] ist undefined!!
ok, danke.
