### ISSUE TITLE
Trying to update from 5.2.10 to 5.2.11

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.javascript#884]
The result of this update is the offer of an update. 

`

javascript.0 | 2021-09-14 21:35:04.591 | error | WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
-- | -- | -- | --
javascript.0 | 2021-09-14 21:35:04.589 | error | npm
javascript.0 | 2021-09-14 21:35:04.526 | error | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
javascript.0 | 2021-09-14 21:35:04.483 | error | WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
javascript.0 | 2021-09-14 21:35:04.482 | error | npm
javascript.0 | 2021-09-14 21:35:04.390 | error | WARN deprecated node-inspect@2.0.0: This module is part of Node.js core and does not need to be installed separately. It is now unmaintained.
javascript.0 | 2021-09-14 21:35:04.388 | error | npm
javascript.0 | 2021-09-14 21:35:04.240 | error | WARN deprecated har-validator@5.1.5: this library is no longer supported
javascript.0 | 2021-09-14 21:35:04.237 | error | npm
dwd.0 | 2021-09-14 21:35:02.616 | info | starting. Version 2.7.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.22.6, js-controller: 3.3.18
host.ioBrokerVM | 2021-09-14 21:35:01.887 | info | iobroker exit 0
host.ioBrokerVM | 2021-09-14 21:35:00.815 | info | iobroker Adapter "javascript" updated
host.ioBrokerVM | 2021-09-14 21:35:00.752 | info | iobroker upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript
host.ioBrokerVM | 2021-09-14 21:35:00.690 | info | iobroker upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/asset-manifest.json asset-manifest.json application/json
host.ioBrokerVM | 2021-09-14 21:35:00.619 | info | iobroker upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
host.ioBrokerVM | 2021-09-14 21:35:00.557 | info | iobroker upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/LICENSE google-blockly/LICENSE null
host.ioBrokerVM | 2021-09-14 21:35:00.490 | info | iobroker upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blockly_compressed.js google-blockly/blockly_compressed.js application/javascript
host.ioBrokerVM | 2021-09-14 21:35:00.414 | info | iobroker upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blocks_compressed.js google-blockly/blocks_compressed.js application/javascript
host.ioBrokerVM | 2021-09-14 21:35:00.348 | info | iobroker upload [6] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/javascript_compressed.js google-blockly/javascript_compressed.js application/javascript
host.ioBrokerVM | 2021-09-14 21:35:00.264 | info | iobroker upload [7] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/1x1.gif google-blockly/media/1x1.gif image/gif
host.ioBrokerVM | 2021-09-14 21:35:00.178 | info | iobroker upload [8] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.mp3 google-blockly/media/click.mp3 audio/mpeg
host.ioBrokerVM | 2021-09-14 21:35:00.115 | info | iobroker upload [9] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg
host.ioBrokerVM | 2021-09-14 21:35:00.114 | info | instance system.adapter.dwd.0 started with pid 10620
host.ioBrokerVM | 2021-09-14 21:35:00.026 | info | iobroker upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.wav google-blockly/media/click.wav audio/wav
host.ioBrokerVM | 2021-09-14 21:34:59.958 | info | iobroker upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.mp3 google-blockly/media/delete.mp3 audio/mpeg
host.ioBrokerVM | 2021-09-14 21:34:59.900 | info | iobroker upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.ogg google-blockly/media/delete.ogg audio/ogg
host.ioBrokerVM | 2021-09-14 21:34:59.842 | info | iobroker upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.wav google-blockly/media/delete.wav audio/wav
host.ioBrokerVM | 2021-09-14 21:34:59.785 | info | iobroker upload [14] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.mp3 google-blockly/media/disconnect.mp3 audio/mpeg
host.ioBrokerVM | 2021-09-14 21:34:59.722 | info | iobroker upload [15] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.ogg google-blockly/media/disconnect.ogg audio/ogg
host.ioBrokerVM | 2021-09-14 21:34:59.664 | info | iobroker upload [16] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.wav google-blockly/media/disconnect.wav audio/wav
host.ioBrokerVM | 2021-09-14 21:34:59.605 | info | iobroker upload [17] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/dropdown-arrow.svg google-blockly/media/dropdown-arrow.svg image/svg+xml
host.ioBrokerVM | 2021-09-14 21:34:59.540 | info | iobroker upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handclosed.cur google-blockly/media/handclosed.cur null
host.ioBrokerVM | 2021-09-14 21:34:59.480 | info | iobroker upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handdelete.cur google-blockly/media/handdelete.cur null
host.ioBrokerVM | 2021-09-14 21:34:59.417 | info | iobroker upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handopen.cur google-blockly/media/handopen.cur null
host.ioBrokerVM | 2021-09-14 21:34:58.680 | info | iobroker upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/msg/js/it.js google-blockly/msg/js/it.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:58.093 | info | iobroker upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/blocks_sendto.js google-blockly/own/blocks_sendto.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:57.471 | info | iobroker upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/de.js google-blockly/own/msg/de.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:56.827 | info | iobroker upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/index_m.html index_m.html text/html
host.ioBrokerVM | 2021-09-14 21:34:52.238 | info | iobroker upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/js/main.8e727556.chunk.js static/js/main.8e727556.chunk.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:51.714 | info | instance system.adapter.javascript.0 started with pid 10593
host.ioBrokerVM | 2021-09-14 21:34:51.463 | info | iobroker upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/basic-languages/javascript/javascript.js vs/basic-languages/javascript/javascript.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:50.676 | info | iobroker upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.js vs/editor/editor.main.nls.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:50.064 | info | instance system.adapter.javascript.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.ioBrokerVM | 2021-09-14 21:34:49.570 | info | stopInstance system.adapter.javascript.0 killing pid 2014
javascript.0 | 2021-09-14 21:34:48.551 | error | Error by canceling scheduled job "<Anonymous Job 13 2021-09-13T20:45:24.585Z>"
javascript.0 | 2021-09-14 21:34:48.548 | error | Error by canceling scheduled job "<Anonymous Job 12 2021-09-13T20:45:24.491Z>"
javascript.0 | 2021-09-14 21:34:48.544 | error | Error by canceling scheduled job "<Anonymous Job 11 2021-09-13T20:45:24.455Z>"
javascript.0 | 2021-09-14 21:34:48.524 | error | Error by canceling scheduled job "<Anonymous Job 10 2021-09-13T20:45:24.378Z>"
javascript.0 | 2021-09-14 21:34:48.515 | error | Error by canceling scheduled job "<Anonymous Job 9 2021-09-13T20:45:24.318Z>"
javascript.0 | 2021-09-14 21:34:48.515 | error | Error by canceling scheduled job "<Anonymous Job 8 2021-09-13T20:45:24.316Z>"
javascript.0 | 2021-09-14 21:34:48.515 | error | Error by canceling scheduled job "<Anonymous Job 7 2021-09-13T20:45:24.314Z>"
javascript.0 | 2021-09-14 21:34:48.514 | error | Error by canceling scheduled job "<Anonymous Job 6 2021-09-13T20:45:24.313Z>"
javascript.0 | 2021-09-14 21:34:48.498 | error | Error by canceling scheduled job "<Anonymous Job 5 2021-09-13T20:45:24.269Z>"
javascript.0 | 2021-09-14 21:34:48.480 | error | Error by canceling scheduled job "<Anonymous Job 4 2021-09-13T20:45:23.053Z>"
javascript.0 | 2021-09-14 21:34:48.479 | error | Error by canceling scheduled job "<Anonymous Job 3 2021-09-13T20:45:23.021Z>"
javascript.0 | 2021-09-14 21:34:48.478 | error | Error by canceling scheduled job "<Anonymous Job 2 2021-09-13T20:45:22.961Z>"
javascript.0 | 2021-09-14 21:34:48.462 | error | Error by canceling scheduled job "<Anonymous Job 1 2021-09-13T20:45:22.896Z>"
host.ioBrokerVM | 2021-09-14 21:34:48.517 | info | iobroker upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsWorker.js vs/language/typescript/tsWorker.js application/javascript
host.ioBrokerVM | 2021-09-14 21:34:48.508 | info | stopInstance system.adapter.javascript.0 send kill signal
host.ioBrokerVM | 2021-09-14 21:34:48.411 | info | stopInstance system.adapter.javascript.0 (force=false, process=true)
host.ioBrokerVM | 2021-09-14 21:34:48.331 | info | iobroker Update "system.adapter.javascript.0"
host.ioBrokerVM | 2021-09-14 21:34:23.485 | info | iobroker npm install iobroker.javascript@5.2.11 --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBrokerVM | 2021-09-14 21:34:23.481 | info | iobroker NPM version: 7.20.4
host.ioBrokerVM | 2021-09-14 21:34:22.537 | info | iobroker Update javascript from @5.2.10 to @5.2.11
host.ioBrokerVM | 2021-09-14 21:34:19.768 | info | iobroker upgrade javascript

`

The log says update succesfull but after the process the version ist still 5.2.10

**Comment by Apollon77** [comment]
Known but there should be a 5.2.12 already that fixes this ... update your repo please

**Comment by winnyschuster** [comment]
> Known but there should be a 5.2.12 already that fixes this ... update your repo please

i can't see a 5.2.12 either, only .11 is offered, have also tried the live repo

**Comment by Dragon0501** [comment]
Same problem
No 5.2.12

**Comment by Apollon77** [comment]
Grmpf ... 5-2-13 on the way
