### ISSUE TITLE
CompareTime() zusammen mit Astro liefert falsches Ergebniss

### ISSUE THREAD

**Issue by Pittini** [ioBroker/ioBroker.javascript#887]
Ich wollte herausfinden ob die aktuelle Zeit zwischen Sonnenaufgang und Mittag oder zwischen Mittag und Sonnenuntergang ist. Dafür gibts ja compareTime(). Also mach ich folgendes gemäß der Doku:

```
log(compareTime('sunrise', 'solarNoon', 'between'));
log(compareTime('solarNoon', 'sunset', 'between'));
```

eines der beiden müßte jetzt (tagsüber) true sein, das andere false, es sind aber beide false. 

Mach ich dagegen folgendes:

    let sunset = getAstroDate("sunset");  
    let sunrise = getAstroDate("sunrise"); 
    let solarNoon = getAstroDate("solarNoon"); 

    log(compareTime(sunrise, solarNoon, 'between'));
    log(compareTime(solarNoon,sunset, 'between'));

ist das Ergebnis wie erwartet und korrekt. 

Da ich bevor ich ein Issue aufmach, erst mal noch andere frag  (um sicherzustellen dass ich mich nich einfach doof anstell), wurde das als Bug bestätigt mit folgender, evtl. zum Thema hilfreicher Aussage:

_"ist ein  bug, in der consts.js fehlt in der Liste astroList der Eintrag für solarNoon"_

**Comment by winnyschuster** [comment]
der Eintrag fehlt [hier](https://github.com/ioBroker/ioBroker.javascript/blob/9f8736753d0eb78c5e309aec48a38c8307b19909/lib/consts.js#L63), durch Nachtragen funktioniert das erste Skript auch

**Comment by Apollon77** [comment]
Macht einer Von Euch einen PR?

**Comment by winnyschuster** [comment]
> Macht einer Von Euch einen PR?

ich mache den zusammen mit #886, mein erster ever. Kommt morgen
