### ISSUE TITLE
Konfiguration: Der Bereich "Day time settings" wird nicht übersetzt

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#889]
- Adapter version: 5.2.13

**Comment by paul53** [comment]
Die Übersetzungen wurden am 23.04.2021 von UncleSamSwiss gelöscht.

**Comment by Apollon77** [comment]
Du meinst in https://github.com/ioBroker/ioBroker.javascript/commit/a95fd8d4aff9050a4fd085491eb1e341773dba3e#diff-7581654bd1845165edb9916abce3c9482b1e2fc9b165715e4c88a150fb12a60b ?! ... hm muss man wohl neu adden :-(

**Comment by FredF63** [comment]
Die Übersetzung erfolgt weiterhin nicht, kann man was helfen und wo?

**Comment by Apollon77** [comment]
@UncleSamSwiss Any idea what happend there?

**Comment by UncleSamSwiss** [comment]
Wasn't me! I have no clue, why Weblate would delete some strings. My best guess is, it was a weird merge in the repo. In the mentioned commit I can't see anything suspicious (I'm on my phone, so I might be missing something).
