### ISSUE TITLE
[Feature Request] Order in "Javascript Group Dropdown Field"

### ISSUE THREAD

**Issue by roe19xx** [ioBroker/ioBroker.javascript#89]
**Description (related to Admin 3.2.3/Javascript 3.6.4)**
I'd like to working with groups and different javascript instances for TEST and PRD.
Therefore i have groups were my PRD script are located and a have a group tree which is starting with _DEV and below i have the same groupname like in the PRD tree.

When i now want to move any script i have to use the group dropdown.
But in this group dropdown there is any other kind of order then in the group tree on the left side.

_Example:_
I have a group "Anwesenheit" which contains productive scripts and i have a group "Anwesenheit" in my "_DEV" group which contains presence scripts which are in development progress or testing.

When i have a look in the group dropdown i will see this two "Anwesenheit" groups one below the other. It is also no alphabetical order because this two group starting with "A" are in the middle of this dropdown.

![grafik](https://user-images.githubusercontent.com/36137769/37240251-49d55cbe-2449-11e8-9d00-7be7b430b83d.png)

**Feature Request**
Is it possible to use the same oder for groupname dropdown like for the group tree in script area?
In my example this means for a new dropdown order that my first group "Anwesenheit" will be at the top of this list (like in the left menu) and the second "Anwesenheit" group is below the "_DEV" group.
So it's easy to find out which group is the correct one without "try and error" method.

**Comment by AlCalzone** [comment]
Preferably we should mirror the structure by indenting the entries like in the tree view on the left.

**Comment by GermanBluefox** [comment]
Not more relevant because of new interface
