### ISSUE TITLE
You are assigning a number to the state "x" which expects a array. 

### ISSUE THREAD

**Issue by Grrzzz** [ioBroker/ioBroker.javascript#891]
**Describe the bug**  
I am using the script engine to set an array state which is defined as following:
**"states": "0: deactivated;1: pending;2:active;",**

This results in a warning msg 

**You are assigning a number to the state "xxx" which expects a array. Please fix your code to use a array or change the state type to number. This warning might become an error in future versions.**

no matter what i try.

**To Reproduce**  
Create an array state.

Try to set state via

**setStateDelayed('xxxx', 2, false, 1, 10), false);**

**Expected behavior**  
State is set with no warning.

**Versions:**  
 - Adapter version: 5.2.8
 - JS-Controller version: 3.3.15
 - Node version: 12.22.6

**Comment by Apollon77** [comment]
Please show the full object definition. I think also you misunderstood something: common.states allows to map display values to data number values. This means that the datatype of the state needs to be common.type: number

**Comment by Grrzzz** [comment]
Hi!
Thank you for pointing me this way. I was not aware that the mapping logic was working this way in iobroker.

Full object definition before:
`{
  "common": {
    "name": "Alarm status",
    "role": "state",
    "type": "array",
    "states": "0: deactivated;1: pending;2:active",
    "read": true,
    "write": true,
    "def": false
  },
  "type": "state",
  "_id": "0_userdata.0.Alarm.alarm_state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1632463949708
}`

Changing type from "**array**" to "**number**" fixed the problem:
`{
  "common": {
    "name": "Alarm status",
    "role": "state",
    "type": "state",
    "states": "0: deactivated;1: pending;2:active",
    "read": true,
    "write": true,
    "def": false
  },
  "type": "state",
  "_id": "0_userdata.0.Alarm.alarm_state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1632463949708
}`

Once again, thank you!!

**Comment by Apollon77** [comment]
PS: YOur style for "states " is officially not support and you should change it!!

It should be states: { 0: 'deactivated, 1: 'pending', ... }
