### ISSUE TITLE
Installation zusätzliches NPM-Modul Firebase nicht möglich

### ISSUE THREAD

**Issue by PortScanner** [ioBroker/ioBroker.javascript#892]
Seit kurzer Zeit funktioniert die Installation des NPM Moduls Firebase nicht mehr.
Zuvor ging das ohne Probleme.

**Comment by Apollon77** [comment]
Was sagen die Logs?

**Comment by PortScanner** [comment]
/bin/sh: 1: cmake: not found
script.js.xxxx.Firebase: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.javascript/lib/../../firebase'

Schaut nach cmake aus, anderen Module lassen sich aber einwndfrei installieren

**Comment by Apollon77** [comment]
Naja dann schlage ich vor "apt install cmake" ... scheinbar fangen jetzt module an das komplett untyüische cmake zu nutzen was in den normalen Build Tools nicht automatisch dabei ist

**Comment by PortScanner** [comment]
Habe ich natürlich, geht nicht. Danke für die schnellen Antworten

**Comment by Apollon77** [comment]
Ok, dann bitte echtes und mehr log

**Comment by Apollon77** [comment]
Und vllt auch mal das Skript zeigen wo Du es einbindest? Und wie es installiert wird. Ich tippe eher darauf das da irgendein Pfad falsch ist

**Comment by PortScanner** [comment]
Das Script ist bis zum neuen Aufsetzen des Brokers tadellos gelaufen.
Dazu musste ich nur in der JS-Instanz unter zusätzliche NPM Module "firebase" und zur Vorsicht "firebase-admin" einbinden.
Das Script reagiert nur auf das fehlende Modul. Das Problem ist das Modul, hier aber das Script:
`var firebase = require('firebase');

var firebaseConfig = {
    apiKey: "AIzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxx.firebaseapp.com",
    databaseURL: "https://xxxxxxxxxxxx.firebaseio.com",
    projectId: "xxxxxxxxx",
    storageBucket: "xxxxxxxxxx.appspot.com",
    messagingSenderId: "xxxxxxxxxx",
    appId: "1:538145xxxxxxxxxxxxxxxxxxxxxxxx"
}

if (firebase.apps.length === 0) {
    firebase.initializeApp(firebaseConfig);
}

var database = firebase.database();

database.ref('pos').on("value", function(snapshot) {
    var arr = snapshot.val().split(",");
    setState("javascript.0.GPS.Lat", arr[0]);
    setState("javascript.0.GPS.Lon", arr[1]);
}, function (errorObject) {
  //log("The read failed: " + errorObject.code);
});`

**Comment by Apollon77** [comment]
Yes it seems there was an update of the firebase module which coverted it to ESM, so you need to install an older version. @AlCalzone  knows more and will add some infos

**Comment by PortScanner** [comment]
Wäre nett, wenn man mir mitteilen könnte, wie/wo genau man eine ältere Version findet und installiert.
Dank für eure Hilfe!

**Comment by Apollon77** [comment]
> @AlCalzone knows more and will add some infos

Ein bissl Geduld bitte

**Comment by AlCalzone** [comment]
Ein ähnliches Problem hatten wir vor kurzem schon mit einem anderen Modul. Die Fehlermeldung ist irreführend, weil folgendes passiert:
1. Adapter versucht das Modul in `/opt/iobroker/node_modules/iobroker.javascript/node_modules` zu laden.
2. Das Modul ist dort, kann aber nur per `import`, nicht per `require` geladen werden. Fehler.
3. Adapter sucht eine Ebene weiter oben. Dort ist das Modul nicht.
4. Adapter sagt "kann nicht finden".

https://firebase.google.com/docs/web/modular-upgrade#benefits bestätigt meine Vermutung. Die neueste Version 9 ist mit dem Skript-Adapter inkompatibel.

Als Workaround:
1. Adapter stoppen
2. `firebase` in den Adaptereinstellungen aus den Modulen entfernen
3. Modul händisch deinstallieren:
   ```
   cd /opt/iobroker/node_modules/iobroker.javascript
   npm uninstall firebase
   ```
4. In den Adaptereinstellungen `firebase@8` eintragen
5. Adapter starten.

**Comment by PortScanner** [comment]
Vorab schon mal großen Dank für die Mühe. Genau so etwas hatte ich schon geahnt. Schade das in letzter Zeit immer mehr Sachen ohne Rücksicht auf Kompatibilität totoptimiert werden. Zum Test komme ich im Moment noch nicht, melde mich aber umgehend.
Gruß

**Comment by AlCalzone** [comment]
Naja, es war ja ein major increase, was per definition breaking ist. Blöd ist nur, dass der Adapter standardmäßig latest installiert, aber vorerst nicht in der Lage sein wird, diese neuen Module zu verstehen.

**Comment by PortScanner** [comment]
Moin, mein Script läuft wieder......
Herzlichen Dank!
