### ISSUE TITLE
Umlaute nach Script restore zerstört

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.javascript#898]
Nach einem manuellen Restore der Java-Scripte sind die Umlaute "zerstört" und die Datei damit doppelt:
![image](https://user-images.githubusercontent.com/50423935/135751927-b5b0b5e2-23e9-4fb8-a82b-7d7ba541fc5a.png)

Klar könnte man auf Umlaute verzichten, habe ich nunmal aber nicht ;)

Bitte bei Gelegenheit einbauen, wenn möglich.

**Comment by Apollon77** [comment]
Was ist denn ein "manueller Restore"?

**Comment by unstressable** [comment]
das hier:
![image](https://user-images.githubusercontent.com/50423935/135772151-098705cd-96ec-447b-85a6-04c41de3a28f.png)

**Comment by cdaerr** [comment]
Hallo,

ich hatte gerade das gleiche Problem.

Alle Skripte exportiert und wieder importiert. Danach waren alle Skripte mit Umlaute nochmal mit kryptischen Zeichen vorhanden. Es ging dann sogar soweit, dass ich den Script Editor nicht mehr öffnen konnte. Letzendlich half nur noch eine Rückkehr zum alten Raspberry Image.

Script-Engine: 5.4.2
JS-Controller version: 4.0.15
Node version: v14.19.0
Operating system: ubuntu 20.04

**Comment by klein0r** [comment]
Da der Issue hier super alt ist, mache ich zu. Bitte kurze Info, falls das Problem noch mit aktuellen Versionen bestellt

**Comment by unstressable** [comment]
Fehler wurde behoben, gerade getestet.
