### ISSUE TITLE
Trigger Sonnenuntergang tut nicht mehr

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.javascript#899]
Hi,

mein Script, dass seit Jahren fehlerfrei funktioniert, wird nicht mehr ausgeführt. Ich weiss nicht, welches Update das hervorgerufen hat. hate die 5.2.13 in Verdacht, was aber nicht sein kann, da es erst seit ca. 1 Woche nicht mehr geht.

![image](https://user-images.githubusercontent.com/22911084/135800791-79798711-c938-4949-8109-4d0eb6d363f7.png)

Das Gegenstück, bei Sonnenaufgang, funktioniert.

Node v14.18.0
npm: 6.14.15
js-controller: 3.3.18
Javascript: 5.2.13
Admin: 5.1.25

**Comment by spheara** [comment]
Hi, ich hab ähnliches festgestellt und bin zu dem Schluss gekommen, dass der Adapter den Wert für "steuere" bzw. "aktualisiere" nicht richtig übersetzt!
Wenn man mit der Schaltfläche oben rechts das Blockly in Java übersetzt kommt für "steuere" das: **"setState("chromecast.0.9c9d7e3290a5.player.play"/*Bad player play*/, true);"**
Es muss aber so:
**"setState("chromecast.0.9c9d7e3290a5.player.play"/*Bad player play*/, {val: true, ack: false});"**
aussehen!

**Comment by Apollon77** [comment]
siehe anderes issue: Nein das ist nicht der Fehler

**Comment by winnyschuster** [comment]
> mein Script, dass seit Jahren fehlerfrei funktioniert, wird nicht mehr ausgeführt. 

prüfe mal deine Astro-Settings im JS-Adapter, speziell die allerunterste Einstellung

**Comment by MarkSau** [comment]
> prüfe mal deine Astro-Settings im JS-Adapter, speziell die allerunterste Einstellung

Das hatte ich schon vor ein paar Tagen. Das sah da so aus (Anstatt dem roten Strich, war zu dem Zeitpunkt nichts ausgewählt, also leer)

![image](https://user-images.githubusercontent.com/22911084/135897377-d6ae50b7-e81b-4c44-a7da-86111da25609.png)

Ich habe dann es so geändert. Hat aber auch nicht geholfen

![image](https://user-images.githubusercontent.com/22911084/135897489-c5717778-d955-49e9-9fa3-ada169be0874.png)

Erst heute vormittag habe ich dann statt 18:00 die 17:00 eingetragen. Und, Huch,  soeben sind die Rollladen runtergefahren.
Also erst die Änderung des Eintrages hatte eine Auswirkung.

**Comment by winnyschuster** [comment]
eig. haben diese Einstellungen keinen Einfluss auf die Trigger, vielmehr auf javascript.0.variables.isDayTime. Habe ich eben noch getestet. Auch wenn die Änderung scheinbar Einfluss bei dir hatte würde ich es als non-issue bezeichnen. Bei mir steht das Setting schon 'immer' auf 18:00Uhr und die Astro-Trigger tun. Stehe aber mit diesen Einstellungen etwas auf Kriegsfuß und kann das nicht abschliessend bewerten...

**Comment by MarkSau** [comment]
heute ist ein Abend, an dem der Trigger wieder nicht funktioniert hat. Es war also wohl Zufall, das die o.g. Einstellungen was bewirkt haben könnten.
Was kann ich tun, wo kann ich nachschauen...Hilfe..wir fahren ein paar Tage weg und meine Rolladen gehen nicht runter..

**Comment by MarkSau** [comment]
Habe gerade mal den javascript adapter auf debug gestellt.
Bei den vielen Meldungen im Log sind mir die, zum Script gehörend, aufgefallen:
<html>
<body>


javascript.0 | 2021-10-06 20:10:33.350 | info | script.js.1_Homematic.Rolladensteuerung.2_Rolladen_Abends_Runter: registered 0 subscriptions and 1 schedule
-- | -- | -- | --
javascript.0 | 2021-10-06 20:10:33.350 | info | script.js.1_Homematic.Rolladensteuerung.2_Rolladen_Abends_Runter: setTimeout(ms=20966651)
javascript.0 | 2021-10-06 20:10:33.345 | info | Start javascript script.js.1_Homematic.Rolladensteuerung.2_Rolladen_Abends_Runter


</body>
</html>

der an angebenene Timeout (ms=20966651) wären dann ja 349min!? im Script stehen aber nur 20min...oder sehe ich da was falsch?

**Comment by MarkSau** [comment]
Jetzt verstehe ich gar nichts mehr...der Timeout verändert sich nach jedem Neustart des scripts vollkommen willkürlich.
Ich habe darauf hin mal das, Gott sei Dank, kleine Script komplett neu erstellt, das alte gelöscht und mit dem alten Namen versehen. Und! Beim Neustart erscheint der timeout nicht mehr...Kann mir jemand das erklären?

**Comment by MarkSau** [comment]
Irgendwas verhindert den Trigger Sunset...das ist in der Jahreszeit echt doof...

**Comment by winnyschuster** [comment]
> Irgendwas verhindert den Trigger Sunset...das ist in der Jahreszeit echt doof...

ich revidiere meine obige Aussage: Es besteht ein Problem mit der Datumsberechnung für die Astrozeiten wenn das Datum von UTC während der Berechnung ungleich dem lokalen Datum ist. Dies passiert zB wenn iobroker in der Zeit zwischen 00:00 und 02:00Uhr neu gestartet wird. Ich gehe davon aus dass bei Dir ein solcher Neustart in diesem Zeitraum erfolgt. Als Workaround bis zu einem Fix empfehle ich den Neustart auf nach 02:00Uhr zu verlegen. Ich probiere mich dann mal an einem PR dazu...

**Comment by MarkSau** [comment]
@winnyschuster ich starte iobroker nur dann neu, wenn ich muss. Daher trifft dein Ergebnis bei mir leider nicht zu.
Bei mir ist es auch so, dass das Script mal tut mal nicht.
Ich kann allerdings kein Muster erkennen.

**Comment by MarkSau** [comment]
Sorry für die späre Meldung...ich habe meinen Fehler gefunden, leider habe ich das schon vor einiger Zeit getan und weiss die Lösung nicht mehr. Soweit ich noch in Erinnerung habe, wurde um 0:00 einige Variablen gesetzt. Seitdem das erst um 5:00 läuft, funktionieren auch die Rolladen wieder. Aus meiner Sicht kann der Issue also geschlossen werden.
