### ISSUE TITLE
state.val

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.javascript#9]
Die Erweiterung der Abfrage abhängig vom **typeof state** ist nicht ausreichend, da in den nächsten Zeilen ein Vergleiche mit **state.val** vorgenommen wird.
Ich habe es so gelöst, dass vor allen Abfragen immer ein Objekt-Typ erzeugt wird mit

**if (!isAck) isAck = false;**

vor der Prüfung von isAck. Oder funktioniert es so nicht korrekt ?

**Comment by GermanBluefox** [comment]
Ich verstehe nicht um was es geht. 
Skripten oder Js core selbst

**Comment by paul53** [comment]
Das Problem hast Du mit Version 2.1.2 / 2.1.3 gelöst. Hat sich also erledigt.
