### ISSUE TITLE
[Problem] Javascript Instance Dropdown doesn't open sometimes

### ISSUE THREAD

**Issue by roe19xx** [ioBroker/ioBroker.javascript#90]
Description
When i try to switch Javascript Instances for Scripts which are part of a group then this doesn't work sometimes. It looks like that instance dropdown will open for a short moment and then close automatic again. This happen also if i try to do it multiple times. It's not possible to get instance dropdown open and choose an instance then.
When i close the group (tree) of this script one time and open it again then can change the instance without any problem.

Tested with Admin 3.2.3 and Javascript 3.6.4
Browser: Firefox 58.0.2 (64-Bit)

**Comment by GermanBluefox** [comment]
Not more relevant because of new interface
