### ISSUE TITLE
Die Funktion "steuere" geht nicht mehr

### ISSUE THREAD

**Issue by spheara** [ioBroker/ioBroker.javascript#900]
**Describe the bug**  
Der Adapter schreibt den Wert für "steuere" bzw. "aktualisiere" nicht richtig!
Wenn man mit der Schaltfläche oben rechts das Blockly in Java übersetzt kommt für "steuere" das: **"setState("chromecast.0.9c9d7e3290a5.player.play"/Bad player play/, true);"**
Es muss aber so:
**"setState("chromecast.0.9c9d7e3290a5.player.play"/Bad player play/, {val: true, ack: false});"**
aussehen!

**Versions:**  
 - Adapter version: <5.2.8>
 - JS-Controller version: <3.3.18> 
 - Node version: <12.22.6> 
 - Operating system: <debian>

**Comment by winnyschuster** [comment]
> Es muss aber so: 

nein, muss es nicht! [siehe die Doku](https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#setstate)

**Comment by Apollon77** [comment]
exakt, ack=false ist default wenn nicht gesetzt

**Comment by spheara** [comment]
> exakt, ack=false ist default wenn nicht gesetzt

Dann erklärt doch bitte, warum die eine Version funktioniert und die andere nicht!

**Comment by winnyschuster** [comment]
> Dann erklärt doch bitte, warum die eine Version funktioniert und die andere nicht!

ich kenne Dein System nicht, aber an dem von Dir **vermuteten** 'Fehler' liegt es jedenfalls nicht, denn das ist keiner. Das kannst Du leicht selbst prüfen, indem Du einfach nur steuerst, ohne Astro etc. wie woanders erwähnt

**Comment by Apollon77** [comment]
Also das einfachste erst einmal ist es zB mit dem History Adapter die State Changes mitzuloggen. Dann siehst Du wer was wie setzt. Kann es vllt am Chromecast adapter liegen? Geht alles noch wenn Du es manuell per Admin bedienst?

**Comment by spheara** [comment]
> Also das einfachste erst einmal ist es zB mit dem History Adapter die State Changes mitzuloggen. Dann siehst Du wer was wie setzt. Kann es vllt am Chromecast adapter liegen? Geht alles noch wenn Du es manuell per Admin bedienst?

Nun das wäre dann auch meine nächste Vermutung gewesen, der Chromecast.
Per Admin, manuell ging es.
Hab also aus dem Blockly ein Javascript gemacht und nun läuft es wieder.
Das aber jemand mit einem anderen Adapter ähnliches erlebt, macht mich stutzig.

**Comment by spheara** [comment]
> > Dann erklärt doch bitte, warum die eine Version funktioniert und die andere nicht!
> 
> ich kenne Dein System nicht, aber an dem von Dir **vermuteten** 'Fehler' liegt es jedenfalls nicht, denn das ist keiner. Das kannst Du leicht selbst prüfen, indem Du einfach nur steuerst, ohne Astro etc. wie woanders erwähnt

Sorry ich verwende bei meinem Script kein Astro, das war der andere! 🙃
