### ISSUE TITLE
Listen: "Liste aus Text erstellen mit Trennzeichen" TypeError: myFunc(...).split is not a function

### ISSUE THREAD

**Issue by TDCroPower** [ioBroker/ioBroker.javascript#903]
**Describe the bug**  
Wenn man den "Liste erstellen mit Trennzeichen" Operator verwendet und dem Wert einen Aufruf eines Skripts einfügt der einen einzelnen Wert erfragt erhält man folgende Fehlermeldung...
`
javascript.0 | 2021-10-17 10:09:06.058 | error | script.js.common.Batterie_checken: TypeError: getName(...).split is not a function
-- | -- | -- | --
`

**To Reproduce**  
1. Erstell eine "JS Funktion mit Ergebnis" mit folgendem Inhalt...
<img width="444" alt="Bildschirmfoto 2021-10-17 um 10 26 43" src="https://user-images.githubusercontent.com/6634116/137618632-7203ec5d-60db-4323-b7aa-29a603a17201.png">

`return getObject(ObjectID).common.name;`
2. benutze einen "Liste erstellen mit Trennzeichen" Operator
3. füge im Wert Feld einen Aufruf der JS Funktion hinzu, als Übergabewert z.B. die ID eines Objektes (hier -> values)
<img width="571" alt="Bildschirmfoto 2021-10-17 um 10 34 23" src="https://user-images.githubusercontent.com/6634116/137618892-3dea746d-c9be-4da1-bcd6-5ee98d9ae78b.png">

4. dadurch sollte die genannte Fehlermeldung im Log erscheinen...
`
javascript.0 | 2021-10-17 10:09:06.058 | error | script.js.common.Batterie_checken: TypeError: getName(...).split is not a function
-- | -- | -- | --
`

**Workaround:**
Lagert man den Aufruf der Funktion aus und schreibt den Wert in eine Variable und verwendet erst diese dann... funktioniert es.
<img width="484" alt="Bildschirmfoto 2021-10-17 um 10 35 23" src="https://user-images.githubusercontent.com/6634116/137619134-9da8cd30-3191-428f-a8aa-6fa0e8131f26.png">

**Versions:**  
 - Adapter version: 5.2.13
 - JS-Controller version: 3.3.15
 - Node version: V12.22.5
 - Operating system: Linux helios64 5.10.43-rockchip64 21.05.4 SMP PREEMPT Wed Jun 16 08:02:12 UTC 2021 aarch64 GNU/Linux

**Comment by TDCroPower** [comment]
"values" beinhaltet lediglich einen String mit den "Name" des Objektes, z.B. "Wohnzimmer-XiaomiTemp-AAA"
`{
  "type": "state",
  "common": {
    "role": "value",
    "read": true,
    "write": false,
    "name": "Wohnzimmer-XiaomiTemp-AAA",
    "desc": "Battery status of the sensor",
    "type": "number",
    "unit": "%"
  },
  "native": {},
  "_id": "ble.0.4c:65:a8:db:a6:70.battery",
  "acl": {
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "object": 1636,
    "state": 1636
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634317339805
}`

<img width="729" alt="Bildschirmfoto 2021-10-17 um 22 06 49" src="https://user-images.githubusercontent.com/6634116/137643260-24091035-c875-48c8-b006-a6294c680ced.png">

**Comment by TDCroPower** [comment]
habe ich im Initial Post drinnen unterhalb des Screenshots...

`return getObject(ObjectID).common.name;`

**Comment by winnyschuster** [comment]
_**Liste aus Text**_ erzeugt: `Liste = await getName(values).split('.');`
für split() würde aber `Liste = (await getName(values)).split('.');` benötigt, also `( await getName() )` geklammert

**Comment by TDCroPower** [comment]
Der Javacode dahinter...

```
// Beschreibe diese Funktion …
async function filterName(values) {
  listAll = null;
  listRoom = null;
  listName = null;
  listTyp = null;
  ObjektName = null;
  listAll = await getName(values).split('-');
  listRoom = listAll[0];
  listName = listAll[1];
  listTyp = listAll[2];
}
```
