### ISSUE TITLE
Trigger mit val Array triggert nicht mehr 

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.javascript#907]
Javascript V5.2.13
JS 3.3.18

Ein Trigger mit 
on({id: idTrocknerReady ,  change: 'ne', val: ['Ende','Abbruch']}, function (obj) {...
triggert nicht mehr 

on({id: idTrocknerReady ,  change: 'ne', val:'Ende'}, function (obj) {.. 
funktioniert.

Hat in einen der früheren Versionen funktioniert.

**Comment by Apollon77** [comment]
Korrekt ... Effektiv war dies nie wirklich supported ... richtig wäre

on({id: idTrocknerReady , change: 'ne', val: JSON.stringify(['Ende','Abbruch'])}, function (obj) {...

**Comment by Apollon77** [comment]
Ok was genau soll es denn bewirken? "not equal "einer der werte"?

**Comment by SurfGargano** [comment]
Richtig, am liebsten wäre mir diese Syntax:
on({id: idTrocknerReady , change: 'ne', val: ['Ende','Abbruch']}, function (obj) {...
oder auch
on({id: idTrocknerReady , change: 'ne', val: ["Ende","Abbruch"}, function (obj) {...

wobei auch integer Werte sein können
on({id: idTrocknerReady , change: 'ne', val: [1,5,8]}, function (obj) {...

**Comment by Apollon77** [comment]
Ehrlich ... ich wusste nicht mal das das geht ... muss man sich anschauen

**Comment by SurfGargano** [comment]
Wäre auch nicht schlimm, wenn es weiterhin nicht geht. Ich hab es inzwischen mit einer if -Abfrage gelöst. Meine Frau hat sich nur gewundert, daß keine Meldungen mehr auf Ihr Handy kam, daß der Trockner fertig ist.
