### ISSUE TITLE
cronjobs broken on Raspberry Pi 4

### ISSUE THREAD

**Issue by n0valis** [ioBroker/ioBroker.javascript#908]
I run serveral blockly scripts with timers.
None of the timers are on time.
Timers are supposed to be executed every full hour, here is how it looks:
javascript.1 2021-10-20 14:08:04.479 info script.js.common.TestTimer: 14:08:04 
javascript.1 2021-10-20 13:01:01.529 info script.js.common.TestTimer: 13:01:01 
javascript.1 2021-10-20 12:07:35.291 info script.js.common.TestTimer: 12:07:35 
javascript.1 2021-10-20 11:04:11.698 info script.js.common.TestTimer: 11:04:11 
javascript.1 2021-10-20 10:29:30.745 info script.js.common.TestTimer: 10:29:30

This looks pretty much the same every day.

Systemtime is not the issue. I checked that and it is always absolutely correct.
Also Systemload is no problem. CPU average is around 0.5
It seems that if I re-save my script shortly before the scheduled time, the timer would be executed correctly.
Here is a run from today where I resaved at 11:55
1006:2021-11-03 09:07:44.046 
1056:2021-11-03 10:03:42.375 
1123:2021-11-03 11:07:45.210 
1168:2021-11-03 12:00:43.556
1255:2021-11-03 13:08:08.309
1305:2021-11-03 14:07:04.664
1354:2021-11-03 15:07:10.997
1401:2021-11-03 16:07:11.249 
1454:2021-11-03 17:07:14.068
1477:2021-11-03 18:07:11.723 
1528:2021-11-03 19:06:57.383
1551:2021-11-03 20:07:03.875
1574:2021-11-03 21:07:00.036
1605:2021-11-03 22:07:04.160
1630:2021-11-03 23:07:02.976

This problem appears all over the place, but Ingo said I should post my script, so here is the one I made for demo purposes:

Timertest = schedule('0 * * * *', async function () 
{
  console.info(('TestTimer:' + String(formatDate(new Date(), "hh:mm:ss"))));
});

RPi 4 DietPi Bullseye
ioBroker 5.1.25
Nodejs 12.22.6
npm 6.14.15

**Comment by winnyschuster** [comment]
this is no valid script and also the provided log is not from it. Please post something that meets reality. i wonder, though, what the numbers in front of each line mean. If it is PID that would mean different processes. Please post output from script that you will provide. Is there a difference in timing if you schedule e.g. for every 30 seconds?

**Comment by Apollon77** [comment]
Additionally: What else runs in JavaScriot adapter? Are there any other heave scripts that do daat processing which is synchronous and not async and so blocks the eventloop maybe?

FY: javaScript and Nodejs is a single process and in fact such a timer will be put onto the event loop when the time is reached ... if an other script blocks for several seconds then it will be executed delayed. Best test by putting the script into an own JavaScript instance. If it also runs at "too late" times there it might be an issue ... if not ... one of your other scripts is causing this

**Comment by n0valis** [comment]
> this is no valid script and also the provided 2nd log is not from it. Please post something that meets reality. i wonder, though, what the numbers in front of each line mean. If it is PID that would mean different processes. Please post output from script that you will provide. Is there a difference in timing if you schedule e.g. for every 30 seconds?

Why is the script not valid? It is a blockly script that I made and that runs. So it is valid.
The output is automatcally extracted from the current logfile by a bash script. It should just show the delay of the timers.
The original lines in the logfile look like the first ones above. So they really give not much more information.

**Comment by n0valis** [comment]
>  Best test by putting the script into an own JavaScript instance. If it also runs at "too late" times there it might be an issue ... if not ... one of your other scripts is causing this

Ok, I will test that. But how would I put a script into an own js instance? Goto Adapters and create a new js instance and run the script in there?

**Comment by n0valis** [comment]
It must be something else. I created a new JS instance. Put my testscript in there. Deactivated the old instance with all the other scripts. Restarted iobroker.service. And have still the same outcome.

**Comment by n0valis** [comment]
So I did a good deal of testing now and I think I got the pattern.
iobrokers timers timing is getting async about 7 minutes per hour.
That is what an hourly timer (Timer1 0 * * * *) suggests. It is executed always 7 minutes to late. At the same time all timers are 'reset'. Meaning: getting synced with system time, which is correct at all time.
And after one hour it is again 7 minutes to late.
This can be confirmed by a second timer (Timer2 59 * * * *). If he is set to be executed lets say 1 minute before the hourly timer, the hourly timer would be executed correctly. Also if Timer2 was set to 30 * * * * Timer1 would have a delay of around 3 to 4 minutes. This is, of course, assuming that Timer2 is executed at the correct time (and not delayed).
If you increase the gaps between timer executions the gap of delay increases accordingly (approx. +7 min/h). About an hour+ and more in the morning if no timer was executed during night.
If I schedule a dummy timer */5 * * * * everything works pretty neat. Is that something I should accept? 

Or is this something that can be fixed?

**Comment by Apollon77** [comment]
It still seems that you are the only ine where that happens ... and this is more then strange :-(

**Comment by n0valis** [comment]
Ok. Still it is strange behaviour, don't you think.
Any idea why that is or what to do?
Because the Pi is running fine so far, everything seems allright. iobroker is the only major service on it and the cron issue the only misbehavior.
And from my experiments it looks like the cause is clearly coming from within iobroker/nodejs.
You know the underlyings better than many, so you should know possible reasons for that.
