### ISSUE TITLE
Adapter crash if socket adress cannot resolved

### ISSUE THREAD

**Issue by Stefan592** [ioBroker/ioBroker.javascript#909]
I send a UDP message to an client. If the host cannot resolved, javascript instance crashed.

LOG:

<html>
<body>

host.iobroker | 2021-11-05 21:23:09.084 | info | Restart adapter system.adapter.javascript.0 because enabled
-- | -- | -- | --
host.iobroker | 2021-11-05 21:23:09.083 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2021-11-05 21:23:09.082 | error | Caught by controller[0]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
host.iobroker | 2021-11-05 21:23:09.081 | error | Caught by controller[0]: Error: getaddrinfo ENOTFOUND Tablet-EG
javascript.0 | 2021-11-05 21:23:08.630 | error | Error: getaddrinfo ENOTFOUND Tablet-EG at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
javascript.0 | 2021-11-05 21:23:08.629 | error | Error: getaddrinfo ENOTFOUND Tablet-EG
javascript.0 | 2021-11-05 21:23:08.626 | error | An error happened which is most likely from one of your scripts, but the originating script could not be detected.
host.iobroker | 2021-11-05 21:22:53.724 | info | instance system.adapter.javascript.0 started with pid 29933

</body>
</html>

Code:

```
function global_sendUdp(host, command, Port = 1337){

    var dgram = require('dgram');
    var Message = new Buffer(command);
    var client = dgram.createSocket('udp4');

    try {

        client.send(Message, 0, Message.length, Port, host, function(err, bytes) {
            if (err) throw err;
            client.close();
        });

    }
    catch { };


}


```

**Versions:**  
 - Adapter version: 5.2.8
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: Docker container v5-latest by Buanet

**Comment by Apollon77** [comment]
you need to add aon client.on('error)', ....) error handler to awoid tzhe uncatchable exception
