### ISSUE TITLE
Blockly "Letzte Änderung" und "Zeitstempel" liefern gleiche Werte

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#91]
Wenn man in dem Baustein "Wert von..." "Zeitstempel" bzw. "Letzte Änderung" auswählt wird die gleiche Zeit ausgegeben.
Dafür zwei Auswahlen bereitzustellen macht nicht viel Sinn.
"vorherige letzte Änderung" wäre besser.

Zumal, wenn man einen Datenpunkt nicht triggert, keine Möglichkeit besteht "vorherige letzte Änderung" abzufragen.

**Comment by GermanBluefox** [comment]
Es geht darum wann das Wert geändert wurde und wann das Wert upgedatet
wurde.

13 мар. 2018 г. 14:43 пользователь "Rantanplan" <notifications@github.com>
написал:
