### ISSUE TITLE
Blockly funktioniert nicht mehr

### ISSUE THREAD

**Issue by s3618300** [ioBroker/ioBroker.javascript#910]
Hi, ich brauch mal euer Wissen. Nachdem mir der IOBroker komplett abgestürzt ist habe ich ihn auf meinem Raspberry 4 neu installiert und per Backitup Adapter aus einem Backup wieder hergestellt. Soweit so gut. Mein Problem ist nun das zwar alle Blockly Scripte wieder da sind und auch funktionieren, ich sie aber nicht mehr bearbeiten kann. Immer wenn ich ein Script öffne bleibt das Bearbeitungsfenster leer. Schalte ich oben rechts von Blockly auf Java sehe ich das Script im Java Format.
Auch wenn ich ein neues Script anlege kann ich mit Blockly nichts tun. die Leiste links, in der man die Blöcke (Trigger..etc) auswählt erscheint nicht.
Den Javascript Adapter habe ich auch schon gelöscht und neu installiert, leider ohne Erfolg.
Hat einer von Euch eventuell ne Idee ??

Danke im Voraus
Gruß
Thomas

**Comment by Apollon77** [comment]
Bitte mal den Inhalt einer solchen Skript Datei hier posten (also inklusive dem langen String unter dem Skript selbst)

**Comment by winnyschuster** [comment]
Mal einen Upload probiert? Im Expertenmodus in Adapter beim JS Editor auf das Pfeil-Hoch icon klicken. Zusätzlich einen Browser Refresh(Shift-F5) durchführen.

**Comment by Apollon77** [comment]
no answer
