### ISSUE TITLE
require in script no longer working

### ISSUE THREAD

**Issue by jlssmt** [ioBroker/ioBroker.javascript#914]
**Describe the bug**  
With 5.2.14 a require of a local module is no longer working.
const TestModule = require('../../../home/pi/iobroker/modules/test-module.js')(getState, setState, createState, createAndSetState, log);

**Expected behavior**  
I need a class in different scripts. 
See: https://forum.iobroker.net/topic/46611/eigene-klassen-importieren-und-an-mehreren-stellen-verwenden

**Screenshots & Logfiles**  
```
javascript.0 | 2021-11-18 23:37:19.734 | error | script.js.test: TypeError: require(...) is not a function
javascript.0 | 2021-11-18 23:37:19.730 | error | at Script.runInContext (vm.js:144:12)
javascript.0 | 2021-11-18 23:37:19.730 | error | at script.js.test:137:3
javascript.0 | 2021-11-18 23:37:19.729 | error | at script.js.test:65:18
javascript.0 | 2021-11-18 23:37:19.729 | error | at require (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:412:32)
javascript.0 | 2021-11-18 23:37:19.729 | error | at require (internal/modules/cjs/helpers.js:93:18)
javascript.0 | 2021-11-18 23:37:19.728 | error | at Module.require (internal/modules/cjs/loader.js:974:19)
javascript.0 | 2021-11-18 23:37:19.727 | error | script.js.test: Error: Cannot find module '../../../home/pi/iobroker/modules/test-module.js'
javascript.0 | 2021-11-18 23:36:18.649 | error | at Script.runInContext (vm.js:144:12)
javascript.0 | 2021-11-18 23:36:18.649 | error | at script.js.test:136:3
javascript.0 | 2021-11-18 23:36:18.648 | error | at script.js.test:65:74
```

**Versions:**  
 - Adapter version: 5.2.14
 - JS-Controller version: 3.3.19
 - Node version: v14.18.1
 - Operating system: Raspbian

**Comment by winnyschuster** [comment]
`require('../../../../../home/pi/iobroker/modules/test-module.js')` will do the job.
It is relative to `/opt/iobroker/node_modules/iobroker.javascript/lib`. Not sure but behaviour might have changed with newest version

**Comment by Apollon77** [comment]
Why you do not use absolute path's?

**Comment by jlssmt** [comment]
@Apollon77 
Ehm. Good point.
Works. Thanks.
Sorry, I'm dumb.
