### ISSUE TITLE
wann löst im Blockly ein Trigger aus (wahr/falsch)

### ISSUE THREAD

**Issue by ohle64** [ioBroker/ioBroker.javascript#916]
Hi,
ich habe mal ein Frage zum Verständnis:
Wenn ein Trigger auf einen eigenen Datenpunkt gesetzt wird und dieser bei wahr auslösen soll (Falls Objekt ... ist wahr... Auslösung egal), löst der dann nur beim wechsel von falsch/wahr aus oder auch bei der Aktualisierung von wahr?
Ich suche eine Möglichkeit, solche doppelten Auslösungen zu vermeiden - also Trigger löst nur bei Wechsel wahr/falsch aus aber nicht bei Aktualisierung von wahr.
Gruß Frank

**Comment by Apollon77** [comment]
ein on({id:'...', change: 'ne', val: true}, (state) => {...});

sollte genau das tun.  change:ne heisst "not equal"

**Comment by nicomania** [comment]
Hallo,
darf ich hier bitte nochmal einhaken? Als jemand, der mit Javascript auf Kriegsfuß steht, weil ich aus der C++ Ecke komme, ist mir die obige Erklärung leider nicht zweifelsfrei verständlich.

Verstehe ich es richtig, dass das hier 

![image](https://github.com/ioBroker/ioBroker.javascript/assets/35151132/5784f6a1-62d8-472a-97fa-b3a50c23ec51)

also gleichbedeutend mit dem hier ist?

![image](https://github.com/ioBroker/ioBroker.javascript/assets/35151132/40b7f888-7f8b-43eb-98af-14e3c4eed3f4)

Also nur bei "_Änderung_" anschlägt?

Vielen Dank für die Klarstellung.

**Comment by Apollon77** [comment]
Da ich in Blockly nicht so fit bin, zeig doch mal das generierte JavaScript. Dazu im Blockly fenster oben wo "BlocklyJS" steht kicken dann schaltet er um.

(SOnst: Auf ein 3 Jahre Altes issue zu antworten sieht zu 99,9% niemeld ... nur so btw)

**Comment by Diginix** [comment]
@nicomania Nein der obere Block löst auch aus wenn der state erneut auf true gesetzt wird. Ist zB bei buttons üblich. Die sind nie false. Der untere wäre mit dem oberen identisch wenn du dort "wurde aktualisiert" statt "wurde geändert" einstellst.

**Comment by nicomania** [comment]
> @nicomania Nein der obere Block löst auch aus wenn der state erneut auf true gesetzt wird obwohl er bereits true ist. Ist zB bei buttons üblich. Die sind nie false. Der untere wäre mit dem oberen identisch wenn du dort "wurde aktualisiert" statt "wurde geändert" einstellst.

Prima, danke, hab ich verstanden.
