### ISSUE TITLE
AND-Funktion with more than to Conditions

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.javascript#917]
Hey together,

it would be very nice if you could add:

-AND
-OR

Funktions with more than 2 conditions.

**Comment by Apollon77** [comment]
What exactkly you mean? You mean in the "Rules"? In Each area you can have multiple blocks that all will be "AND" and you have option to define "OR" block in the UI ... Or what exactly you mean? Maybe provide a screenshot to better describe it?

**Comment by unstressable** [comment]
Ich meine ein UND bzw. ODER mit 3 oder mehr Eingängen rechts.

**Comment by Apollon77** [comment]
Also Blockly? Bitte Screenshot zeigen sonst reden wir weiter aneinander vorbei. Der Javascript adapter erlaubt mindestesn zwei ARten um visuell Skripte zuerstellern. Rulez und Blockly

**Comment by unstressable** [comment]
Sowas hier
![Uploading 1CD29B23-A52C-4182-8382-83AA2C749502.png…]()

**Comment by unstressable** [comment]
Wurde geschlossen? Gibts den Block mit mehr als 2 ODER bzw. UND mittlerweile?

**Comment by klein0r** [comment]
Keine Ahnung. Wäre ja praktisch, wenn es irgendwo ein Log gäbe, was sich wann am Adapter in welcher Version geändert hat, oder?

**Comment by unstressable** [comment]
also ich hab den Adapter aktuell und sehe diese Mehrfach-Blöcke nicht.

**Comment by klein0r** [comment]
Aktuell = 7.8.0

https://github.com/ioBroker/ioBroker.javascript?tab=readme-ov-file#changelog

**Comment by unstressable** [comment]
ich bin auf 7.1.6 und er zeigt kein Update an, muss das wohl manuell machen, danke!

Hab gesehen, das du im changelog sogar selbst reingeschrieben hast :D

**Comment by Diginix** [comment]
@unstressable Wenn 7.1.6 bei dir als aktuell angezeigt wird, dann bist du im stable repo. 7.8.0 ist bisher nur in beta.

**Comment by unstressable** [comment]
ja das stimmt, will auch da bleiben, danke für den Hinweis.
