### ISSUE TITLE
Object "alias.0.Technische_Kontakte.xXx" does not exist

### ISSUE THREAD

**Issue by gelberlemmy** [ioBroker/ioBroker.javascript#927]
I can´t put the alias in "Objects" "Functions" and use it over the objects in a script. than i become this :

Object "alias.0.Technische_Kontakte.xXx" does not exist

otherwise i cant generate a alexa device in the adapter iot. Same problem.

![image](https://user-images.githubusercontent.com/20154913/146600291-829078b6-9126-4206-94e9-50fbd0205070.png)

**Comment by Apollon77** [comment]
lease show your script

**Comment by gelberlemmy** [comment]
Hi,
hier ist das Script. Alle anderen Datenpunkte sind auch Alias Datenpunkte.

Gruß André

[Script Timer Target.txt](https://github.com/ioBroker/ioBroker.javascript/files/7758046/Script.Timer.Target.txt)

**Comment by Apollon77** [comment]
In fact this script do not have proper error handling.

>                         if (typeof getObject(GetParentId(Targets[y]), "common").common.name == 'object') TargetNames[y] = getObject(GetParentId(Targets[y]), "common").common.name.de

The script assumes that the object exists ...but it seems that it is actually not ... In fact it is about alias.0.Technische_Kontakte.Gartenpumpe ... is it there? if yes restart javascript adapter ...

**Comment by gelberlemmy** [comment]
Good moring,

yes it´s the alias.0.Technische_Kontakte.Gartenpumpe. 
Restart results in no improvement. Recently i can no longer use alias data points. In the past this has always worked great. Since i don't often add data points to the script, i didn't notice it right away. Since an update this no longer works.

Regards André

**Comment by Apollon77** [comment]
Ok then please show me the Object definition of this object. Admin - Objects and use the pencil icon (maybe you need expert mode enabled) and copy the raw json

**Comment by gelberlemmy** [comment]
{
  "_id": "alias.0.Technische_Kontakte.Gartenpumpe.Relais_2",
  "type": "state",
  "common": {
    "name": "Gartenpumpe",
    "role": "switch",
    "type": "boolean",
    "desc": "Manuell erzeugt",
    "read": true,
    "write": true,
    "def": false,
    "alias": {
      "id": "zwave2.0.Node_066.Binary_Switch.targetValue_002"
    },
    "icon": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSEhMWFhUXFxYVGBgXGRUWFxcVFxUWFhcVFRYYHSggGBolHRUWITEhJikrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGi0iHyUuLS01Ky8tLS0tLS0uLy0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAMIBBAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAwQFBgcCAQj/xABOEAABAwICBQcFDQUGBQUAAAABAAIDBBESIQUGMUFRBxMiYXGBkTJSobHBFCMzQlNicpLC0dLh8BUkc6KyRIKDk6PxFjRDw+IXJVRjhP/EABkBAQADAQEAAAAAAAAAAAAAAAABAwQCBf/EACoRAQACAgIBAgQGAwAAAAAAAAABAgMREiEEMUETIjJRBTNxweHwFGGx/9oADAMBAAIRAxEAPwDcUIQgEIQgEKuaw18zZmRxvwAsLjk0kkE7yNluCTjNftEjbdbR6gEFnQoON9WM3PjOezCdlu3JcxVdcXW5uLDxu8exBPIUFNXVDZMJ5vYNmI7esgKZgkxNa7iAfEIFEIQgEISdROxjcT3BrRvcQB4lAohVyq11o2GweXn5oy8TZIx68QE5Nd6EFpQomk1hhktbEL7yMvEXUox4IuCCOIzCDpCEIBCEIBCEIBCEIBCEIBCEIBCEIBCEIBCEIBC5e8AEkgAZknIADeSox2slF/8ALp+Hw0X4kFDr9bop5jMwP5tocxrgwHE3PpWLgRtXbeU2lbcSPc3M/wDSd9klUjRNQ0Q4bi9lVdNeUUGyO5UNGHLnnf5cw9iktGcoej3Gzahp/uyD1tXzg5SugvLCDedMa1QY2yCaMgWyLsGw32vsFK6na1U9WDFG9pkja3E0OBuMhjbba2+XeFjGlW3j7lO8hEf75UHhBbxkafsoNvQhCCt6+6ze4KbnGtDpHuEcYPk4iCS51toABy3mwWIaT1iqJ3YpZXPOe05D6LRk0dQC0XlyHvVN9OT+kLEZqh6CWlr3A7f1/sbL2n0q4OzNx6/98vTxKZav6Kkq6mKnDsBkcG4jnbaSbDbsV91u5LW0NI6qbVukMeDE10bQHY3tj6JDrtsXA54tiCPh1jneC1jyxoyLh5RPAH4o6xnnuSujdN1MDxJFNJcbnPe9jup7XGxB47eBCgdEfB95+5PAf13BB9D6IrhPBHMBYSMa+3C4uR3HLuTtUrVfT7WUtNC1t3mNosLntJ4BWVk8p8wdx+9dcJV/FrvUJBCaCSTi3wP3rl1U4eb6Qo4p5wephprTMFJHztRII2FwaCb5uIJAFt9gfBeftMDa3wN1QOW289A0xAkRSiWQ7MLBHI3Eb7rvGxJrMEZKz6SnX8p2jRsmv2YR6yP1fgu4+UvRh8qfB1uBt3lt7fkeBXzM2QcePpFlL01HJUnmadhmkLXHAzN1rm5PAdIeKh2+sULxuwL1AIQhAIQhAIQhAIQhBm3L1pJ8WjmsYSOdnZG4jzQ18hHixqw+o0lI7C4nPA0E222GHPwW+8s+r8tZo+0LS6SKVswaNpaGuY4AbzZ5NupfP1Zo6ZlgYpAAALljwMh1jtQcY5fLzsdvqulKqAWBu7xXGj4JZXYGgkN8rgO1PtIwYRbgghTH1lSehKMveAHub2WUe5TWrfwgQS2nNEvjZf3Q85bDZO+T7XOn0W2WSSOSaaV2CzXNaGRMa0tPS3uc9/1Bs3oV8xfDzrjfETZvxQ29gOJOW3iVTqmr6Xwcf1T96Dao+XGE/wBjk/zYfaQnVFyyRSOwimcP8WI/0krCoqsfJxfVd7CpHQ9U0SsOBjczm0Pvk0neTfZ6UF/5Q9d4q3moRE+NzHON3FjgcTQLCxuNm8LNpSn+kJA+pbhubkbj6io2Vj97XeBQWXk5d/7pR/xfsOW0csT7aLlHF8A/1mH2LDdSZxBX008ptHHJieRdxAwOHktuTmRsC03lY1rpqigayB7nF00flRys6ID3ZF7QNoCDOtHH3sdp9ZTgOTWiPvbe/wBZSuJBsfJ/NSup2mL4RrWNkxeUHBv9JztZTNdpANWL6r6UdTVTDewd728dRyz7DY9y0iR5JzWqKdvNyZdRqEs3SjiEm6rJUFpnSHuemlmw4sDb4b2vu27hmqR/xtJ8k30/iSeNfVzSuTJHTUOdJUfp2h90QSQOc5okbhJba9rg7DtFwMlQoNdZHHKAOtmbG3pJNlZ9WNMmdxyIaWmzTtDgbEetImtvQtTJTuWRaX0BNSTiOYZE3Y9vkvbfa3geI2jwJt2pILNNUYaT0sYN87tMEhIz7FedZdENqIHRkZjpMPmvGwj1HqJWYjSr6WvhnjAxxh2HFsu6N7Dl2OKovTUtuHLzr36w+nELINVOUp8sogrAYy7JsjXENudgIJy7brQYdJPjdZxxD024g+xT8OT48RPcaTyFzFIHAOabg5grpVrwhCEAhCEAhCEAhCEGRa6aOcyrn5qUtD8MhaWsdZzh0rHbtz71mGm4ZATd4P8Adt7Vseu7f3t/8Nh9BWUawjpFBVXA8QpDRUsjLvaW9EF2YO4X3FMZNqe0h97k+g71FBJyyTCnjJLMBaCBY367ntuq/PK24vG079rx9pWKoFqWE3+I3I2I2bgVXZ6q1sozlvYw+xARTM+TH1n/AIlJaCcHVEIDQOmdhcfiu4lRkdWfNj/y4/uUxq5Jeph8na45NaPiHgEC2kpObq8dr4ST6CPb6EnpDWGWRuBxyBxbttjcjhu/QXWmqrDUPJG1Qs8mK5H+17oO2VjsQIOexSlfUzujY2XFgvdt9lwLZdx9KrqdU7yTtyGxBZqbyG9gSkbbkDibeJXDBYAdQ9S9ilDCHnY0hx7jdET6JnW+nDajE34xz+kN/f7FoVJJjY13nNafEAqia1RG+Lcc1bdV5cVNEeAw/VJHsW72eRed6k60zR87TTxefE9veWmyyTR1S0wtu25sDf8ARstriCxyhoXiaWJrMRimkbhtfotkNsuFreKoytXiT6w5bUsBBDLZEGxIvckg7d1999gVm1Hqhzuyw5w5cA8bPElRc0b/ACTTMaeyxzHb3pbV1ro5MxbY4f3T+a4xdWaPJjeOWpPYsS1rontq5gbmz3YeprukB4OW5uF8+OazDlErBBVZt8uNrvC7T/SF3k9Gfxur6UaN5xYXcLjtH5X8Atl1X0uZqdhcbuaMJO8lu/wssZfXc7KDa231ELQtQZ7YmdjvYfYusXdXPl9Ttb6/XN1AYjI0Op3vLX2vjjJHlN3EZG4tnxWitcCARmDmOxZFr7o501HI1jS54LXNA2lwcMh1nZ3rVdGwGOGOM5ljGNPa1oB9SqyxqV/i23TU+xyhCFW0hCEIBCEIBCEIM413/wCbf/DZ9pZTrAMytV14P70/+Gz7SyrT5zKCqy7U6gPvUn0Smsu1SWi6QytfG3a5pAvsvuugf1AHMRYCceBt7Ej4oUNMKjLCX7Bfpb9+9TekoXCFjJG4HNaGm+YyyuC26rdVALjpsGQ+U/AgcRip3uf9f/yUrq+JPdEWNxIu7a8OzwHdcqAihb8ozwk/AprVxrWyiTG0hoOwO2njiAQPnavS19d7mgLA9wc4GQua2zBc3LWk+hM9YtSKyifzc4YL+S5pcY3/AEHFouRnkbEcLFef8Ry09V7opn4JAHNDgGusHZHJ4I9CtdPygaVmp7Tx009OTgdJPBjYXG5a2QRvaAciAcI2cUGaPhINiu4nW2Kz1oifiLqWlaTvidWMt9FrpXNHhZQ7qRo/6ZPY8/cphEyUGmHcAvH17pAWADPLuTKSA7mEd90vQnC4A5XXVYjbm9pivTTKkCWiikuLhoBz3jL2KT1FlvC5vmvPgQD67rNhPDCHRy0LJTfoyc4WEeDc1c+TaqDi9oGEOaHBt72wm1r7/KWre3mXpqN/3/q/xLNdLRGLSlSPPDJR2GMA/wAzHLS2BUPX+Pm9IU026SIxk7rxvv6pT4KrJ6LfGnVzqi0eJImuOZLQ69yDdwvkf0FEGNzJg052OR4tcCRfru23cn9PUvhGENxsN7C+EtvtF94TOcue50jrAktsBuDTkOs7fFeb49ctMszaenueVfDkw6rHf6f3bStGvxQxu+aB3jL2LNuW2lypphxkjPeGvb/S5aBqw+9OBva4j2+1Gn9Ex1EYZI0OAcHC/GxHtK9O0b6eDS/HVnzxotnSur9qjJhmb84FvtHpCsE2oVPtY3CeIUQ/Rj6aRuLcQQeNjs7VZjrqNOc2Xm0Ak2DhtFnDtGY9IV6jeHAOGwgEdhzVHpc2BWvQcl4GfNuz6pIHoAVOWF/iW7mD9CEKhuCEIQCEIQCEIQZtr5/zT/4bPtLJ9OnMrVeUwubOHRsc4mMYr5NyJw4TtJOd8srDNY5pSqe51nRFme0nIeAQQ0hzU/qo7phQM7LOIuDbeNh7Lp7o2rdH0mjPdfYOvrQT+udU1tm3u4jIdXE9SqdNQPech4pd7iXF7iXOJuXHaSpfQ8wBF0CFPqxId/gE5GhJGAgXz7Ff9FTRkDYnVXDGRkgyeTQnapSTTTYqN1JzQDnuiIf0s+bcxxJuTn0CLC3lnJWiqpGqtaxUQMZttb0h3bfRdAk/WJ25kY7gk/8AiJ/mx/VULAy47EqIUExJp0nY2P6qjKutdLIzFhGeVgBnuuuBGvJYbhTE6lExuNLLo6arY9vuJ4xvbYsIYc99sZAKn9WW1jKtprG4XPxDY1oILdwaSNoVThfHJA1z3mNwPwgcWBp2G9iN4J71MaLpWQyxy/tGGchzeiJ3PftBNmuJWv3ebaOpj9v3as0LnSmhoaqLm52YgCHDMhzXDY5rhYg5nYlQE8p9hC5lzT1VxmpdLv5w/wCI/wC9L0mqVLG8Pa112m4xPe4X42JsVPCM8CuhEeBXPSzdvvJjo+mwPkA2Os8dux3s8U6lal44s7nsScgU7Rx1BrZMdK6ObMwtO3aDwO4qUES8MSmJcTXaH0ETgwu2gWPa3olWjV1/wjOsO+sLfZ9KjBA0HFbM7etOdFyhkzb7Hgs7/KHqPiub9xLvB8toWNCELO9IIQhAIQhAIQhBmHK0wPc2MtnlGEOMbXhkQsXWdYvGN1x5ptx3LIXUQYXPDcDhfoS3eHDblcFvqWw69xxVFU5rnPvExjLNe4C56Z6INj5Q3blAN1bb8JIL2za0ho7C/CBf9XQZpBotzum8WBzA2X+4InjsrnpWDaqrXMQRL0pBIQuZAvGoLDo7SLhkM++3sKn4K+Q7m/WP4VUKJ5vkbeA9JUzBKPjSf6gHqKCZkkkPmfzKNqmuO23pRz0W+T/Ud+JcOfFud/O770FZbFaQttbMi3qTrmCuqzKdpxXBLd+KwyBHrVlGjRwQVkU5XppzwVn/AGeMu0enL2r11COCCD0BIQZYgwOuA7CRe/G3X0R4p1RnRrbF/uxkgObRHGWg9RsDZLNgeypiwdHFdgd851vuK9qtI+53ujqKKCZ9yecMr2kjdfC1aaT8sMOWusk/7azo6XHFG/zmNPiApKj2lQGqVUJaSN4aGg4rNBJDRiNmgnaALKepTmpspofsXa4Yu7qte5KbSDNOSUk8ZqYRJIHqXhJ4epKsC6spc6Nu5NK9pDcTdrSHDtabj1KReElKy4I4iymHNo6T8Eoc1rhscA4dhF0oozVuTFTs6rt+q4gegBSazzGp09CluVYkIQhQ6CEIQCEIQYzT1TZauaU5kyyW7MZw+AspuulGFZ/BXc3LJuIkeD9Y5j9cFJ1GnARtQI6VftVTrypStrbqEqpLoGT0ndKPTzRUWPojCC6SNuIxtkIBbKTZpBv5IyCBtC8b/vUlDO0bz4fmpim0LgvJK5pYwuJaIIAXNa15ycL2N2i44FdS6LeyUR87G7oPfhbTxc67A2U2iYW2eDzeTsQ8oII9tcPnfy/iXrq8cHfyfiU1HQYScdUAzE1ocxkDcV5TGSOoHCT38E3rZCyNsjKiU3LS272AbISWFrcy73x+YyHN2O1BWtIvDntIvfrA3G+VietXX3dH5zfEJvqvo+jmhqpKnDiwvLCbgxuzwvYQbg4rdWdkxotJ0/NtL5bPt0gGNOfagkpK+O3lt3HaNxuj3bH57fEKPk03Bb4Z/c1oSjNJaPw3Lpbkm9wL9uSBHS9Qw4CJBYP2AjO4I9qkI4tIMc79nTPfCTfJtObcB74LqE0xXUTo3CMSF+E4SbAB24lXnk0cfc5PWPUr8X0zDH5PUxKY1Skn5g+6b88Hux3DQb2acw3Ibdyn6eTpBRFI/pS/xD/QxPYX9IK2YY4t2VqKYumDi1rmbDiYJABYZAHZnc9d162jF844LcBTjwxFvpsnTXpQOWeMURMz927/ACLTERqOjB1CbCwjBBvdkLGG42EPyLOO/ZbO6k5HrjEkZXruK6V3yTYrzh3W7yR7F5zruDfE/cm5kXPPLrSrkcmR3AeJ+5cmRNzMk3yqdImyZ1UPvThwkePUfappQuqY95ceMjj6h7FNLPf6pb8H5cfoEIQuVoQhCAQhCD5s1zozDWVUfCV7h9Fx51vocFXfdhWncumiHskjrGeRIBFJ1SNuWE/Sbcf3AN6yMlA9NQUk56QDl7iQeuK6insC0ta4Eg2dfa3EBsI84pIlc3QPI52/JReEn4k4jqw3yWwtuCDZsmYcC0g7ciCR3qPY4fo2SmJvA/W/8UDv3SN3Mj/BB9cZXprHWHSZlmLRMFuzoCyaB7fN9P5LsPHmf1IE5XHMBxF9tri44FI8x1n0LqV3S2W8faugUHBphxPoXvMN613dcucgVoIGmRotlv7FctH0lW/GaKp5qO+bXPDbHd8Q+tVbQbSZL2va3iT+SljTaPkLnVL3xSXN2thc4HifIPrWjHHyMeed3/jbRtWI5Ww2mfjkxuxOuHYjlncAX8FLGbCQVD6pwsbTRtjN2XdhNsN24jY4d2W5T0tOD1K1hnczOif7WA+KfFdDTI8w+P5JM6PHErz9nDifQmqo3cuNLX+L6fySkdVi3WTUUbRvKWjjAUah1E293c0pGzD3gn1EJPnz836p/EmekKkBwHV7Smoq1MQ5m/aUM56u5v5pN8yjnVS6piZHBjdrsh35KdaRuZnUL5qxHhpo+sF31nFw9BClFxBEGta0bGgNHYBYLtYpnc7e1SvGsQEIQodBCEIBCEII7WDQ8VXTyU0wuyRtr72kZte35zSAR2L5b1k0LNRVD6acWezYc8MjD5MjL7Wn0EEbQVpXKDWyirmHOyABwAaHuAAwjYAbKk630rnsjkGZHRJ37/yWWvlRN+OvfT0r/h1q4fi8vbelXD17jTzR9IxwdjviA48E1np7HorU81yXrnGk3AjI5Fc3QPYHfPA+t7AnHOH5cf6v4VFhy9xIJPnP/v8ADnPuXhlHyzj3P9pUbiXcQ3oFrkm5zXQKTuvboO8S5JXl0pTRF7g0d/UN6mI2iZ1G5Ter8JsDsJN78LbPUpKLSkTARPRNlffyzIW3G7PCk6aOwsMrCw9QUvo/9rMjAjtze0H3km282LgtnHURDzLW5WmZXDV63MxYW4Qcw297AuJtfftUhpPSDYWF7tgCZ6LyZHfbhF+3CoDXeouA3rCnXbPEnVRri6NjHFoJkc4NB2NDGtLibZk9No8U1dr5Nuji8Hn7YVc0yejSjrqT/LTphznV8Yt8CR7FnyWmLTEPRwYqzjiZhetE63SSzMjexlnnDdrXNIO43LzfssrRjWYasuvVRdUlv5brSA9d4pmY7Z/KrFLREIbTNe5sha17gABkHOA47imP7Sf8pJ9d/wB6ZadlJnf2geDQEwxFXdKOEymnVxO1xPaSfWVcuTygLi6ocMh0WdZ3lUbQWh5aqVsTN+bnbmN3uP3bytsoKNkMbYoxZrAAPvPWdqqy3jWoavGwfNyn2OEIQsr0AhCEAhCEAhCEGOa/aJnfVSuZDK7pAjCx7gRhGwgZqja5xTRxMa+GVmI7XsewG2ZALgL7l9OLMeXJl4aa/wAo/wDpGf64rLXxYi/Lfvt6NvxG9sPwte2tsQ0U1wuSMsPrK8mNiE5dLhBFkzk6Vj+thPsWp5yap9BS108VPBg5xzCRjJa3otxG5AJ2Dgp5vInpQ/HpR2yS+yJe8lU19K0xHmyN7uZeb+hfRCD5/ZyG1++opR2GU/YCcR8hVV8ashHYyQ+0LeEIPmTSPJbpSGQs9zmVt8nxOYWuHGxIcOwgJzWaOo6OOCRzXmfnX42PtYwlsjcJbucCG+JX0koXS+qdDUvElRTRyPAtcg7NudjmgwV+tVJupI/qt+5M6rWaAghlMxpIyIDQR17FvrdQ9Fj+w0/exp9aUdqTo0tw+4acA8ImNPc5oBHig+X6mtxCwCX0DTuxl1jay3jSPJPRuzgfJCeGUjPB3S/mUDUcmVXH8G+OUdRLHfVdl/MrcfGJ3tRlm811EKFVc3h5t7w3FnnYZDtT2n0BHha4VwcRmGYjcnzcpPYpev1ZqI/hqVxA34A9viLhR7XRBwwwxsINyWsa05bsgtO4lhnlWNdr1Tm3cPyVN1mmxSAdacSaaLWYuOQO4kbQCoLnnSSYiuoU1pMdy703/Zf/ANP/AGPuUWw5N+m71uT3S9SDLDGNrGSOPVzhFh4R370yafI+m77ax5frl6vj/lQldVj+9M/iO9EZ+5aAJxnms70E15lvGxz3gvIaxpc4kswDIZ7XBaXqvqnVOex9S0RxghxaSC91sw2wyA43N+pWYrRWvbN5OK2TJHH7IubUmuke5/NtAc4kXezYTlsJUho7k5mJHPPYwfNu93qA9K01CrnLZpjBSDDQ+iYqZmCJthtJObnHi4p+hCrXRGghCEAhCEAhCEAhCEAq9rnqqyviaxzzG5hLmOAxC5FiHN3jZvGxWFCDAtMclWkWfBtjmHzHhpt1tkw+AJUKOT7SdgPcUl8t8fmkbcdl9LoQYxyb6iV8FZDUTwiJkeInE9hcbxuaAAwne7fZbOhCAQhCAQhCAQhCAQhCATSs0XBL8LDG/wCmxrvWE7QgSFMzDgwNwWthsMNuGHZZUTXTk9dO5stA+KneAQ9hZaOQ7Wuu0dBwzubG9xwWgIUxMx6ImsT6w+dP/TnS0c5LqbnSbkvZJEWk2ttc5pHeAnNPyf6WOH90w2JJxSwbweDz53oX0EhQlmnJhqZV0k8k9U1jbsc1ga/GSXuBJNhYABg8epaWhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCAQhCD/2Q=="
  },
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1604592934890,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}

**Comment by Apollon77** [comment]
Nope das ist alias.0.Technische_Kontakte.Gartenpumpe.Relais_2 ... wir suchen alias.0.Technische_Kontakte.Gartenpumpe weil das besagt die Fehlewrmeldung

**Comment by gelberlemmy** [comment]
Der Ordner heisst Gartenpumpe. Der Fehler kommt wenn ich Relais 2 in die Funktion TimerTarget lege und dann das Skript nutzen will
![image](https://user-images.githubusercontent.com/20154913/147092123-bf02f1fd-7c4e-48af-83b3-3a904337cfed.png)

**Comment by gelberlemmy** [comment]
Kann es sein, dass das problem kommt, wenn ich unter "Technische Kontakte" noch einen Unterordner habe ?

**Comment by Apollon77** [comment]
Das ist es ... DU hast zwar ein "unterobjekt" aber genau das "Parentobjekt" fehlt und ist nicht angelegt. Und das bringt das Skript durcheinander weil kein Fehlerhandling da ist

**Comment by gelberlemmy** [comment]
Parentobjekt ? Kann ich da etwas nachbessern ? Die Ordnerstruktur möchte ich nicht ändern, da das wirklich viel Arbeit wäre

**Comment by winnyschuster** [comment]
Du kannst _Gartenpumpe_ manuell anlegen als _Verzeichnis_(musst nicht löschen vorher) oder du lässt [dieses Skript](https://forum.iobroker.net/post/660631) laufen. Nähere Infos finden sich auch in diesem Thread:
