### ISSUE TITLE
Timeplan (monthly) will generate an error

### ISSUE THREAD

**Issue by sonneimtal** [ioBroker/ioBroker.javascript#929]
The blockly module timeplan used with the wizard will generate an error "TypeError: sch.period.months.map is not a function" if I generate a monthly timeplan.

**To Reproduce**  
1. implement a blockly timeplan
2. use the Wizard -> timepoint 00.05 ->monthly (every month) -> start date 01.01.2022
3. click OK
4. error -> TypeError: sch.period.months.map is not a function

**Expected behavior**  
no error

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/23382426/146919634-4749eea6-3b0a-4413-918e-cb578f846ef7.png)
![image](https://user-images.githubusercontent.com/23382426/146919752-074d8b7e-fe71-46d9-9077-b2662781305c.png)

**Versions:**  
 - Adapter version: <5.2.18>
 - JS-Controller version: <3.3.22> 
 - Node version: <14.18.1> 
 - Operating system: <Ubuntu>

**Comment by Apollon77** [comment]
Please check with 5.4.2

**Comment by sonneimtal** [comment]
still the same issue, it is not possible to do a monthly scedule

Am Mi., 16. März 2022 um 09:06 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
Please try GitHub version ... I found another topic

**Comment by sonneimtal** [comment]
now it is working

Am Do., 17. März 2022 um 12:51 Uhr schrieb Ingo Fischer <
***@***.***>:
