### ISSUE TITLE
It is not possible to add additional modules in the settings

### ISSUE THREAD

**Issue by diman1234** [ioBroker/ioBroker.javascript#93]
ioBroker.javascript: 3.6.4
ioBroker.admin: 3.2.0

**Comment by Apollon77** [comment]
Do you pressed enter after entering the name and before submitting the form?

**Comment by Apollon77** [comment]
And please retry with current admin version 3.3.5

**Comment by diman1234** [comment]
thanks, it works for me when I press Enter. Unfortunately, it was not clear to me. Hidden feature :-)
