### ISSUE TITLE
JavaScript Adapter: Icons in search dialog missing (again)

### ISSUE THREAD

**Issue by Gaspode69** [ioBroker/ioBroker.javascript#931]
**Describe the bug**  
Issue #697 is back. After upgrading to Version 5.2.13 the icons are missin again as described in Issue #697.

Replacing codicon.ttf with the version from this fork and restarting ioBroker fixes the problem:
https://github.com/SliX185/ioBroker.javascript/blob/master/src/public/vs/base/browser/ui/codicons/codicon/codicon.ttf?raw=true

**To Reproduce**  
1. Open a script in Javascript editor
2. Open search dialog
3. The icons are missing

**Versions:**  
 - Operating system: Windows

**Additional context**  
It seams that in the corrupt file all occurrences of 0x0D 0x0A are replaced by 0x0A, which looks as if the file is handled as Windows ASCII file in the repository and Windows line endings are converted to Linux line endings.

**Comment by Apollon77** [comment]
should be fixed in the meantime
