### ISSUE TITLE
Corrupted run due to package installation

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#933]
Restarted javascript due to host restart and the only logging I've found was 

```
2021-12-25 09:54:58.024 - info: javascript.0 (425) starting. Version 5.2.13 in /opt/iobroker/node_modules/iobroker.javascript, node: v12.22.5, js-controller: 3.3.15
--
2021-12-25 09:54:58.044 - info: javascript.0 (425) npm install node-ssdp --production (System call)
```

where `node-ssdp` is a npm module added to the js adapter. No scripts were actually started so I have noticed, a few hours alter that none of the logic was working anymore. 

Guess of the `npm I` hangup: I think the installation failed, because there were no internet connection at this time.

This should not happen, so if the commands hangs to various reasons it should timeout or be handled in some fashion.

**Comment by Apollon77** [comment]
Question is "How" to detect this ... and what to do then ... because dependiong on the npm module and the system (e.g. raspi 1) it can really take ages. If the command is exited this would have been logged
