### ISSUE TITLE
Copy or move scripts between different JavaScript instances

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.javascript#934]
I think it would be nice if there was a way to copy or move Blockly and JS scripts between different JavaScript instances.
You could create and test scripts in a test instance and simply copy or move them from this test instance to a productive instance with a click.
And if you want to change or test something in the script, you can copy it to the test instance, edit it there, test it and, if it works, simply move it back to the productive instance or copy it.

**Comment by Apollon77** [comment]
Already possible ... in the script list there is a dropdown with a number .. this number is the instance the script runs on ... just select the other instance

**Comment by Berchemer** [comment]
Sorry but I don*t see a dropdown inside the "tab-javascript" 😢

I have two installed instances. The expert mode is switched on. In the left half with the names of all scripts, icjh see the icons for execute / stop, delete and edit next to the respective script.
For the presentation of the rest, I'll send you a hard copy.
![2021-12-27 - 13_44 - Tab-JavaScript](https://user-images.githubusercontent.com/44316663/147473133-f4b3dc95-794f-42cf-93ee-4a6d3e2906c0.PNG)

**Comment by Apollon77** [comment]
It is the [0] which sows the instance. Select the script, klick the pencil on top of the list - there yu can seect the instance
