### ISSUE TITLE
Include User-Agent for "Request" - Block

### ISSUE THREAD

**Issue by ScumbagSteve** [ioBroker/ioBroker.javascript#937]
[Some websites ](https://docs.helium.com/api/blockchain/introduction/#specify-a-user-agent) require an User-Agents in order to give a valid answer to a request. This seems to be in order to prevent spam-requests (even though I can not really understand how this is helping against spam).
It would greatly help if Blockly either sends a **default User-Agent** with the request, or (top notch solution) offers a text-input-connector to let the user define an own User-Agent. However I think the first solution will fit to 99% of the demands, as I don't see the general use-case for a custom User-Agent.
The professionals probably use JS anyway and therefore can specify whatever they need there.

**Comment by klein0r** [comment]
> It would greatly help if Blockly either sends a **default User-Agent** with the request

Already implemented in `httpGet` and `httpPost`
