### ISSUE TITLE
Warning about invalid id because of empty folder

### ISSUE THREAD

**Issue by macpo** [ioBroker/ioBroker.javascript#939]
**Describe the bug**  
The warning about an invalid id appeared in the past. After the last update of the javascript-adapter the message gave the correct hint to create an issue.
![image](https://user-images.githubusercontent.com/17279799/148065215-c0908f0b-4452-4126-8beb-a7433cbd245e.png)

The reason seams to be the folder without the name between the folders js and iobroker:
![image](https://user-images.githubusercontent.com/17279799/148065382-9a6b23ce-6ec3-4a52-b627-1c14622225f8.png)

The object _d_ has the following objectdata:
![image](https://user-images.githubusercontent.com/17279799/148065609-8c9538b6-52aa-484e-93c5-ac66678cd68b.png)

**To Reproduce** 
It appeared without any interaction.

**Expected behaviour**  
The reason for the warning shall be solved so the the warning will not appear.

**Versions:**  
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Raspberry Pi OS Bullseye

**Comment by macpo** [comment]
The warning appears again after the update from 5.2.19 to 5.2.21.
```
javascript.0 | 2022-01-24 09:58:22.363 | warn | Error while checking script folder script.js. for id "script.js..iobroker.types.javascript.d": Error: The id "script.js." is invalid. Ids are not allowed to end in "."
```

**Comment by Apollon77** [comment]
Nothing was different between 5.2.19 and 5.2.21 that can cause that...

And also: Where these strange folders from above come from? can you delete them and see if they come back? Maybe an od version was buggy and created that?

**Comment by macpo** [comment]
The first time the message appeared after the update from 5.2.13 to 5.2.19.

**Comment by Apollon77** [comment]
This could make smore sense. Can you try please what I told you above?

**Comment by macpo** [comment]
I deleted the folder and restarted the javascript instances. The warning did not appear again.
Also after I reverted to 5.2.13 and updated to 5.2.19 again the warning did not appear again.

One point as a notice: I reinstalled the system using a backup some weeks ago.

Thanks for the help.
