### ISSUE TITLE
Newly Created Folder in js ts not visible

### ISSUE THREAD

**Issue by lzimmermann** [ioBroker/ioBroker.javascript#942]
**Describe the bug**  
When I create a new Folder in the Scripts View the folder is created but not visible after creation.

**To Reproduce**  
1. Go to Scripts
2. Change view to JS or TS
2. Click on Create new Folder (+)
3. Name it MyFolder1 and save
4. Folder is created (visible in Folder Selection) but not visible in the items list with scripts in the root folder

**Expected behavior**  
The folder should be visible in the items list

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/12608081/149508636-e3187a2c-a6cb-4085-889b-c58f17d62335.png)

<img width="245" alt="image" src="https://user-images.githubusercontent.com/12608081/149508691-91926736-3beb-4cf4-b72b-fb67bd7bb9cd.png">
![image](https://user-images.githubusercontent.com/12608081/149508726-e4a777f8-7349-46d8-89c7-c1b327a22856.png)

**Versions:**  
 - Adapter version:  v5.2.3
 - JS-Controller version: <js-controller-version> 3.3.22
 - Node version: <node-version> v12.22.9
 - Operating system: Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l

**Additional context**

**Comment by klein0r** [comment]
Should be fixed in the latest versions (not reproducible)
