### ISSUE TITLE
Font for search/replace in v5.2.19 (german system settings) not working anymore, v5.2.18  did work!

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.javascript#943]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by frankjoke** [comment]
Another issue @5.2.19: On Windows I could see not any script window! The panels for script selection or javascript source were not existing, just menubar came up!. On Linux I could see the scripts but only the font for the search bar were wrong!

p.s.: Tested on two different PC's and Raspi's.

**Comment by macpo** [comment]
I have the same behaviour...
![image](https://user-images.githubusercontent.com/17279799/150762835-68321d0a-981f-4b49-8213-dc90b1506c3a.png)

**Comment by Apollon77** [comment]
5.23.21 should have fix for it

**Comment by macpo** [comment]
@Apollon77 If you mean 5.2.21 it is not solved yet...

**Comment by Apollon77** [comment]
@GermanBluefox ??

**Comment by Apollon77** [comment]
Please recheck

**Comment by frankjoke** [comment]
It's still not working in 5.2.21, I believe it worked in 5.2.20 but cannot test it anymore because I cannot go back to 5.2.20 (or .19) anymore!
So I use 5.2.18 which is the last one I could load where it was working!

**Comment by macpo** [comment]
same behaviour in my installation 5.2.21:
![image](https://user-images.githubusercontent.com/17279799/155725675-1e614fe7-75d5-426c-aa48-097221c5b036.png)

**Comment by SliX185** [comment]
....and again for me, too. 5.2.21
![errr](https://user-images.githubusercontent.com/47434006/157858867-116961b6-0311-4ae6-9717-6a4fcb316afd.JPG)

**Comment by macpo** [comment]
Works fine with 5.7.0
![image](https://user-images.githubusercontent.com/17279799/171050237-a59e6b7c-72d9-464d-8883-36488cddfd9d.png)
