### ISSUE TITLE
Feature Request: Add disable_web_page_preview for telegram?

### ISSUE THREAD

**Issue by peterimnetz** [ioBroker/ioBroker.javascript#945]
Hi,

I use the telegram adapter to push some http urls into my bots, but as the web preview takes a lot of space on the display I disabled the web view.

It is not possible to set "disable_web_page_preview: true" via blockly, so I have to convert it to JS and add this option manually - means I can't just use blockly for this case.

Would it be possible to add this? It would make usage much more convenient for this usecase.

**Comment by Apollon77** [comment]
Please open the isue in the telegram adapter because the blockly comes from there and is no standard blockly
