### ISSUE TITLE
Subscribe (on) liefert nur noch States, keine Objektdaten wie in der Doku

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.javascript#946]
` {"id":"0_userdata.0.Geraete.1.status.queryTime","newState":{"val":7.437,"ts":1643190335009,"ack":true,"lc":1643190335009,"from":"system.adapter.javascript.0","q":0},"oldState":{"val":7.281,"ts":1643190204570,"ack":true,"lc":1643190204570,"from":"system.adapter.javascript.0","q":0},"state":{"val":7.437,"ts":1643190335009,"ack":true,"lc":1643190335009,"from":"system.adapter.javascript.0","q":0}}`

in der Doku
`{
    	'_id' : 'javascript.0.myplayer',
    	'type' : 'state',
    	'common' : {
    		'def' :    0,
            'min'  :   0,
            'max'  :   6,
    		'type' :   'number',
    		'read' :   true,
    		'write' :  true,
    		'states' : { 0:'stop', 1:'play', 2:'pause', 3:'next', 4:'previous', 5:'mute', 6:'unmute'},
    		'role' :   'media.state',
    		'desc' :   'Player handling',
    		'name' :   'MyPlayer'
    	},
    	'native' : {},
    	'channelId' :   'channelID',
    	'channelName' : 'channelName',
    	'deviceId' :    'deviceID',
    	'deviceName' :  'deviceName',
    	'enumIds' : [],
    	'enumNames' : [],
    	'state' : {
    		'val' :  'new state',
    		'ts' :   1416149118,
    		'ack' :  true,
    		'lc' :   1416149118,
    		'from' : 'system.adapter.sonos.0'
    	},
    	'oldState' : {
    		'val' :  'old state',
    		'ts' :   1416148233,
    		'ack' :  true,
    		'lc' :   1416145154,
    		'from' : 'system.adapter.sonos.0'
    	}
    }`

**Comment by Apollon77** [comment]
true... I think this was removed several time abo ... SHould we add it back or fix the documentation? ;-)

**Comment by foxriver76** [comment]
I also have in mind, that it should emit the object too. Other question, how to listen to object changes if it is not emitted here?

**Comment by AlCalzone** [comment]
Honestly I've never seen it emit the whole object and I wouldn't expect it. Most scripts only need to subscribe to state changes. Maybe having a separate `subscribeObjects` method (or similar) would fit this purpose better?

**Comment by Apollon77** [comment]
In fact the object data are available ... so adding them would not be an issue (and with js >5.3.x it should be even more accurate, but in fact the issue is that always getting current object data is very costly and in fact there are slight chances because of the asynchronity that the object returned indeed is outdated ...

So adding it would only have a 99,99x% accuracy ... 

@AlCalzone it is even not about sibscribeObjects .. it is about "user needs to have the object to process the statechange ... so he simply csn do a getObject in the subscription trigger (which would indeed return the same 99,99x% accurate object) :-)

**Comment by AlCalzone** [comment]
Yeah, I'd say if you need an object in the state change handler, get the object yourself.

**Comment by foxriver76** [comment]
fine for me. But we need to adapt docs clearly, mostly it is stated like 
```javascript
on('id', obj => {
```

which suggests that an object would be emitted.

**Comment by AlCalzone** [comment]
> which suggests that an object would be emitted.

Yeah if you think about it that way. I've always considered it to be the state, which is a JS object, hence the name.

**Comment by Apollon77** [comment]
called it "data" now :-)
