### ISSUE TITLE
Can not compile Javascript anymore

### ISSUE THREAD

**Issue by aendue** [ioBroker/ioBroker.javascript#948]
Hi, after an update to version v5.2.13 I can not compile javascript anymore. 
EDIT: I installed older version 5.2.8. Still same issue.

Script:
`console.log("Hallo Welt!");`

Error:
<img width="1092" alt="Bildschirmfoto 2022-01-30 um 14 13 07" src="https://user-images.githubusercontent.com/8988228/151701189-4e0df369-b205-49c9-98ef-7b0e152c04bf.png">

**Comment by Apollon77** [comment]
Do you maybe have some global Scripts? They are prepended. n fact some error is in your script somewhere.

"var" is a reserved keybord and can not be used as a variable

**Comment by aendue** [comment]
HI, thanks for your answer. I had a few scripts inside root but because of troubleshooting I deleted them. Now it looks like this. Still gets the same error
<img width="1092" alt="Bildschirmfoto 2022-01-30 um 19 33 14" src="https://user-images.githubusercontent.com/8988228/151712650-930f4ab0-eb1d-4316-9d10-4cba89ae9c0f.png">
.

**Comment by aendue** [comment]
Sorry...found it...I switched to expert settings and found a script in global folder...

Thanks for your help...can be closed!
