### ISSUE TITLE
Blockly Zeitplan monatlich 1 Tag wird täglich ausgeführt

### ISSUE THREAD

**Issue by marlan99** [ioBroker/ioBroker.javascript#949]
i am using the blockly trigger scheduler in several variations (daily, monthly, yearly, once, intervall, specific time)
everything seems working instead the monthly one when used only on a single day.

for example: i want a schedule executed every first day of a month. But then it will be executed daily based

![Bildschirmfoto 2022-01-31 um 15 30 01](https://user-images.githubusercontent.com/42575841/151811791-a18f6dd8-95d3-4319-bb38-c064d0860960.png)

when i switch to the javascript code you can see the following:

`schedule('{"time":{"start":"00:00","exactTime":true},"period":{"months":1,"dates":"[1]"}}', async function () {
});`

it is working with the following workaround:

`schedule1 = schedule('0'.toString().trim() + ' ' + '0'.toString().trim() + ' ' + '1'.toString().trim() + ' ' + '*'.toString().trim() + ' ' + '*'.toString().trim(), async function () {`

![Bildschirmfoto 2022-01-31 um 15 34 21](https://user-images.githubusercontent.com/42575841/151812486-87881d84-a584-4a1a-85f6-9ac564bc74b4.png)

i am on following versions:
javascript: 5.2.21
NODE.JS: V14.18.3
NPM: 6.14.15
Admin: 5.2.3

**Comment by Apollon77** [comment]
Please try Github version

**Comment by marlan99** [comment]
installed github version and configured 2 version of a monthly task.
one which should be executed last night and one which should be not.

both are now working as expected. thanks for fixing the issue
