### ISSUE TITLE
Blocky for Telegram: setting user name field does not work

### ISSUE THREAD

**Issue by ramizh** [ioBroker/ioBroker.javascript#95]
So if you want to send a message to a specific person instead of everyone on Telegram you will have to type the specific user to the username field in blocky, however that does not work.
- First of for some reasonTelegram detects first name as username instead of the actual username its not reliable to use since its not unique.
- Even if I enter the username as Telegram detects to the user name field in Blocky it does not do anything, no one will receive a message.
- when switching blocky to written js it will work however from the 2nd or 3rd trial but not immediately.
- if I change "user" in the code to "chatId" and use the chatId for the specific person, it works normally and without troubles.

I think its more reliable to use the chatId since its unique and detected properly by the Adapter unlike the username.

Thanks in advance!

**Comment by ramizh** [comment]
`
on({id: "broadlink2.0.RM:192-168-1-15.L.tv_home"/*tv_home*/, change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  sendTo("telegram.0", "send", {
      text: 'Test',
      user: 'myfirstname'
  });
});
`

**Comment by ramizh** [comment]
and if I leave it like this, it wont work until i change it to normal text.
![blocky_1](https://user-images.githubusercontent.com/36566465/38148682-c6328f3e-3457-11e8-813e-a59d490caa3b.png)

**Comment by ramizh** [comment]
Update: seems like its a lottery to get the message sent to the specified person using "user", I don't know why but with "chatId" it works 100% of the time while with "user" (not as blocky though, that doesnt work at all) it sometimes does sometimes not.
Unfortunately this is out of the area of knowledge and I can not seem to figure the specific problem rather than I know what is working for me and what is not.
Hopefully someone can share a better insight on this.

**Comment by BuZZy1337** [comment]
I always use the username to send messages trough telegram... Never used the chatID and it always worked flawlessly for me.. But i never used blockly.. I also tried to recreate your blockly script.. I am always receiving the message when i use my Username.. So i cannot reproduce your issue..

Are you using the telegram adapter in "Server" or "Polling" mode?

Here is the entire script i created in Blockly.. As soon as i start the script, i receive the message "text" on my phone.. Every time.. Its not acting like a "lottery" at all .. :smile: 

![image](https://user-images.githubusercontent.com/6979405/38160999-5369446e-34c7-11e8-8da4-5ea702fd93e3.png)

'

**Comment by BuZZy1337** [comment]
If I were you I would try to set the telegram instance log level to "debug" and see what the adapter is throwing to the logs when you try to send messages with specific  usernames.

**Comment by ramizh** [comment]
I have decided last night to wipe everything out reinstall ioBroker and everything again. Now sure if I should use a backup I did 3 days ago or I should start clean. So I would not be able to check the debug of telegram but since for you it works normally, seems the problem is on my end, and if so hopefully this will solve it.
Thanks again, ill post an update later on and close this issue accordingly

**Comment by ramizh** [comment]
By the way answering your question about polling or server, I used polling. Never tried server.

**Comment by BuZZy1337** [comment]
https://github.com/ioBroker/ioBroker.telegram/pull/47 has just been merged.
Try to install the newest github version of the telegram Adapter.

**Comment by ramizh** [comment]
Yep I did try the pull request and it worked perfectly and forgot to close this issue. 
Thanks again for your effort, much appreciated!
