### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by patrickbs96** [ioBroker/ioBroker.javascript#956]
**Describe the bug**  
I recently upgraded to Node.js v16 and I now get error messages when starting javascript.

**Screenshots & Logfiles**  
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-inspect@2.0.0: This module is part of Node.js core and does not need to be installed separately. It is now unmaintained.
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```

**Versions:**  
 - Adapter version: <v5.2.21>
 - JS-Controller version: <v4.0.9>
 - Node version: <v16.14.0> 
 - Operating system: <linux>

**Comment by Apollon77** [comment]
Yes, please simply  ignore this. This should come from packages that you installed for your javascript instance (or other adapters).
