### ISSUE TITLE
Rules: Cron not working

### ISSUE THREAD

**Issue by JayJay68** [ioBroker/ioBroker.javascript#959]
**Describe the bug**  
If you use CRON as trigger, the configured values are **not** copied to the generated java script.

**To Reproduce**  
1. Create a new script with "Rules"
2. Configure CRON as trigger, eg.: "20 5 * * 1-5"
    
![grafik](https://user-images.githubusercontent.com/34628456/154844471-0505e8e5-2f42-4866-8f55-166e66a4ac19.png)

2. Click on '.Rules / JS' (at the top right corner)
3. Check the generated script code. You will see something like "0 * * * *"
![grafik](https://user-images.githubusercontent.com/34628456/154844639-c5732002-0d29-432c-8bba-ccc7201ef87a.png)

**Expected behavior**  
The generated script-code should looks like "schedule("20 5 * * 1-5", async fu...."

**Screenshots & Logfiles**  
see above

**Versions:**  
 - JavaScript - Adapter: 5.2.13
 - JS-Controller version: 3.3.23
 - Node version: 12.22.4
 - Operating system: Debian GNU/Linux 10 (buster) 4.14.78-cubox

**Additional context**  
-

**Comment by Apollon77** [comment]
@GermanBluefox and even worse ...
![Bildschirmfoto 2022-03-22 um 12 01 21](https://user-images.githubusercontent.com/11976694/159467445-713296e8-ada5-4474-b5e7-48446b25bc6c.png)

a cron like */1 renders the "comment" from rules config ineffective :-)))

**Comment by JayJay68** [comment]
Hi, with Javascript 5.7.0 this bug is still there. Is a bug fix planned?

**Comment by Apollon77** [comment]
Sure planned ...

**Comment by GermanBluefox** [comment]
Fixed in 7.x
