### ISSUE TITLE
Script Rules not working after a host update

### ISSUE THREAD

**Issue by louisvangeldrop** [ioBroker/ioBroker.javascript#961]
**Describe the bug**  
Script Rules not working after a host update

I have updated the host using the usual script:
iob stop
iob fix
iob update 
iob upgrade self
iob start

The result of updating the host forces me to restart all defined Script/Rules by hand.
After restarting all the Rules they do work as expected.

**Comment by Apollon77** [comment]
is there anything in your logs? If you manually restar the JavaScript instance is it happening again?

**Comment by louisvangeldrop** [comment]
I have restarted the Javascript instance and none of the Rules are restarted. The Javascript scripts do restart.

**Comment by Apollon77** [comment]
Please show screenshot of the config of the scripts ... what does log say about these scripts when you start the instance?

**Comment by louisvangeldrop** [comment]
This script switches the light off at 1:00 o'clock.

In JS-format:



schedule("00 01 * * *", async function (obj) {
    _sendToFrontEnd(1643928764598, {trigger: true});
    
    const _cond = true;
    
    
    
    if (_cond) {
		// set state alias.0.tuya.zitkamerlampen.state to false 
		const subActionVar1643928784875 = false;
		_sendToFrontEnd(1643928784875, {val: subActionVar1643928784875, ack: false});
		await setStateAsync("alias.0.tuya.zitkamerlampen.state", subActionVar1643928784875, false);

		// set state alias.0.tuya.eetkamerlampen.state to false 
		const subActionVar1643928790437 = false;
		_sendToFrontEnd(1643928790437, {val: subActionVar1643928790437, ack: false});
		await setStateAsync("alias.0.tuya.eetkamerlampen.state", subActionVar1643928790437, false);

		// set state alias.0.tuya.keukenlampen.state to false 
		const subActionVar1643928792194 = false;
		_sendToFrontEnd(1643928792194, {val: subActionVar1643928792194, ack: false});
		await setStateAsync("alias.0.tuya.keukenlampen.state", subActionVar1643928792194, false);

		// Log My device triggered
		const subActionVar1645465873989 = "My device triggered";
		_sendToFrontEnd(1645465873989, {text: subActionVar1645465873989});
		console.log(subActionVar1645465873989);
    } else {
		
    }
});
/*const demo = {
  "triggers": [
    {
      "id": "TriggerScheduleBlock",
      "_id": 1643928764598,
      "acceptedBy": "triggers",
      "tagCard": "at",
      "cron": "0 1 * * *",
      "text": "* 1 * * *",
      "addText": "Every minute of 1st hour",
      "at": "01:00",
      "dow": [
        "_",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "0"
      ]
    }
  ],
  "conditions": [
    []
  ],
  "justCheck": true,
  "actions": {
    "then": [
      {
        "id": "ActionSetState",
        "_id": 1643928784875,
        "acceptedBy": "actions",
        "tagCard": "control",
        "oid": "alias.0.tuya.zitkamerlampen.state",
        "value": false,
        "oidRole": "state",
        "oidType": "boolean",
        "oidWrite": true,
        "oidRead": true,
        "toggle": false
      },
      {
        "id": "ActionSetState",
        "_id": 1643928790437,
        "acceptedBy": "actions",
        "tagCard": "control",
        "oid": "alias.0.tuya.eetkamerlampen.state",
        "value": false,
        "oidRole": "scene.state",
        "oidType": "boolean",
        "oidWrite": true,
        "oidRead": true,
        "toggle": false
      },
      {
        "id": "ActionSetState",
        "_id": 1643928792194,
        "acceptedBy": "actions",
        "tagCard": "control",
        "oid": "alias.0.tuya.keukenlampen.state",
        "value": false,
        "oidRole": "scene.state",
        "oidType": "boolean",
        "oidWrite": true,
        "oidRead": true,
        "toggle": false
      },
      {
        "id": "ActionPrintText",
        "_id": 1645465873989,
        "acceptedBy": "actions",
        "text": "My device triggered"
      }
    ],
    "else": []
  }
};*/

//{"triggers":[{"id":"TriggerScheduleBlock","_id":1643928764598,"acceptedBy":"triggers","tagCard":"at","cron":"0 1 * * *","text":"* 1 * * *","addText":"Every minute of 1st hour","at":"01:00","dow":["_","1","2","3","4","5","6","0"]}],"conditions":[[]],"justCheck":true,"actions":{"then":[{"id":"ActionSetState","_id":1643928784875,"acceptedBy":"actions","tagCard":"control","oid":"alias.0.tuya.zitkamerlampen.state","value":false,"oidRole":"state","oidType":"boolean","oidWrite":true,"oidRead":true,"toggle":false},{"id":"ActionSetState","_id":1643928790437,"acceptedBy":"actions","tagCard":"control","oid":"alias.0.tuya.eetkamerlampen.state","value":false,"oidRole":"scene.state","oidType":"boolean","oidWrite":true,"oidRead":true,"toggle":false},{"id":"ActionSetState","_id":1643928792194,"acceptedBy":"actions","tagCard":"control","oid":"alias.0.tuya.keukenlampen.state","value":false,"oidRole":"scene.state","oidType":"boolean","oidWrite":true,"oidRead":true,"toggle":false},{"id":"ActionPrintText","_id":1645465873989,"acceptedBy":"actions","text":"My device triggered"}],"else":[]}}

**Comment by louisvangeldrop** [comment]
![image](https://user-images.githubusercontent.com/10716245/155017229-1792b1c3-8815-4b22-a8d7-87b095328088.png)

**Comment by louisvangeldrop** [comment]
![image](https://user-images.githubusercontent.com/10716245/155017311-0513cfe4-ad26-4e42-8945-1dd91dfc83a6.png)

**Comment by louisvangeldrop** [comment]
There is no mention in the log-file about the started Rules. The other Javascript scripts are logged as expected.

**Comment by louisvangeldrop** [comment]
When I press the "Pause script" button the rule is stopped. Pressing the "Run script" button does nothing. Only pressing "Restart" starts the rule

**Comment by Apollon77** [comment]
Please check with 5.4.2 (in Beta channel)

**Comment by louisvangeldrop** [comment]
I am using the beta repository of iobroker, but "iob update" does not show the 5.4.2 update

**Comment by Diginix** [comment]
@louisvangeldrop Wait some more time or use the github URL if you can't wait.

**Comment by louisvangeldrop** [comment]
Just installed the 5.4.2 version. The log shows the restart of the Rules.  
Thanks for all the good work that  you are doing with ioBroker.
