### ISSUE TITLE
iobroker-data/files/javascript.admin/static is full of old static files - hundreds of Megabytes

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.javascript#962]
**Describe the bug**  
Folder `iobroker-data/files/javascript.admin/static` is not cleared from old static files, after installing new version of adapter.

**To Reproduce**  
Install adapter and made several upgrades of version

**Expected behavior**  
Only actual static files have to be in 

**Screenshots & Logfiles**  
![javascript admin](https://user-images.githubusercontent.com/66964358/155282503-4ae883cd-dbee-402f-8da4-a04f5ab95824.png)
![javascript admin css](https://user-images.githubusercontent.com/66964358/155283408-f9881814-90a7-4e14-aec1-ac9ccdd5e7de.png)

**Versions:**  
 - Adapter version: 5.2.11
 - JS-Controller version: 4.0.9
 - Node version: 14.18.2
 - Operating system: Debian 11

**Comment by Apollon77** [comment]
Could you pelase rectreate this issue in js-controller repo? I can not transfer it, but it is a general topic of js-controller

**Comment by Diginix** [comment]
Interesting discovery!
I have also over 400MB obsolete static/js stuff (269 files) in at least these 3 adapter directories.
293 MB  /opt/iobroker/iobroker-data/files/javascript.admin/static/js/
57 MB   /opt/iobroker/iobroker-data/files/web.admin/static/js/
52 MB   /opt/iobroker/iobroker-data/files/modbus.admin/static/js/

Some more adapter contains obsolete files as well, but below 30 MB in sum.

**Comment by Apollon77** [comment]
I remembered thta we had the topic again but could not find any issue in controller ... maybe it came under some wheels ... thats why good to get a controller issue for it. it is a very valid thing and also is relevant for "www"

**Comment by PeterVoronov** [comment]
> Could you pelase rectreate this issue in js-controller repo? I can not transfer it, but it is a general topic of js-controller

sure, no prob

**Comment by Apollon77** [comment]
HA, I was wrong :-) js-controller already does it ... just the adapter needs to add a flag: like https://github.com/ioBroker/ioBroker.iot/pull/169/files#diff-6ef04a9e675def1145dff7cc57420b1ea8bb3f6f5a5e4502cc5da0281981b472R194
