### ISSUE TITLE
Time for scripts are not correct if you install the adapter before setting the timezone 

### ISSUE THREAD

**Issue by Maschine20** [ioBroker/ioBroker.javascript#965]
**Describe the bug**  
Time for scripts are not correct if you install the adapter before setting the timezone. The scripts are then running to the UTA Time instead of the local time.

**To Reproduce**  
1. Install iobroker
2. Install the javascript adapter
3. Set the timezone in the unix terminal from iobroker to Europe/Berlin
4. Run a script with according to a timestamp.
5. The script is then following a wrong time (UTA not Local Time).

Solution:

Set an other settings in the adapter settings in astro settings. Save then and then set "use system settings". Save and restart from the adapter. 
Then the times for the scripts are right.

**Comment by Apollon77** [comment]
Please restart the javascript adapter once after fixing the timezone. This shoud be enough
