### ISSUE TITLE
Update Deps - deprecated node-inspect

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.javascript#975]
`WARN deprecated node-inspect@2.0.0: This module is part of Node.js core and does not need to be installed separately. It is now unmaintained.`

**Comment by Apollon77** [comment]
I'm not able to find since when the package is included in node.js ... I would assume nodejs 14 ... becsiuee the javascript adapter still supports node.js 12 (and even 10) it is still in the deps .. thank you for reporting it
