### ISSUE TITLE
Does not show console message to console when Script is first run

### ISSUE THREAD

**Issue by asutpshnik** [ioBroker/ioBroker.javascript#976]
**Describe the bug**  
Does not show console message to console when Script is first run

**To Reproduce**  
Create new script wirh cide:
`console.log("test");`
Run script Run button click - no message "test" in console
Restart running script - all ok, mess "test" in console
See attached gif-file

**Versions:**  
 - Adapter version: 5.3.1
 - JS-Controller version: 4.0.18
 - Node version: 14.18.2
 - NPM version: 6.14.15
 - Operating system: Debian GNU/Linux 10 (buster)
 
![js-script](https://user-images.githubusercontent.com/60661789/156899767-634bc540-7954-45f1-bf1f-57072904a59d.gif)

**Comment by Apollon77** [comment]
fixed in 5.3.2
