### ISSUE TITLE
Script won't execute on enabeling (since version 5.3.0) (works with 5.2.21)

### ISSUE THREAD

**Issue by danieldriessen** [ioBroker/ioBroker.javascript#978]
**Describe the bug**  
I have a few scripts (blockly) that are always in stop and will be started on demand (via button in vis). Once started the script executes (no triggers, just set state blocks). Within the script my last command is to stop the script again.
Since version 5.3.0 however the scripts won't execute on startup anymore.
I confirmed that it is working with version 5.2.21.
If I open a script, edit and save it while it is still running it gets executed as it always used to be.

**Comment by krobipd** [comment]
hey, I just wanted to post the same problem.
i also have some script that I manually start and stop. but when starting they won't get registered and so they don't work.

javascript 5.3.1
js-controller 4.0.19

**Comment by Apollon77** [comment]
Ok, then please provide more details ... what exactly you do to "enable" or "start" or whatever the script?

If I understand oyu correct then you enable an already enabled script?

**Comment by krobipd** [comment]
I enable a disabled script.

Auf deutsch: wenn das Skript deaktiviert ist und man es aktiviert dann wird es nicht ausgeführt. Auch fehlt jegliche Info im log zb Skript gestartet, Skript registriert.

Von meinem iPhone gesendet

**Comment by Apollon77** [comment]
Ok, bitte mal die relevanten Script objekte (script.js.xxxx - vorher expertenmodus im admin aktivieren)  hier posten und genau sagen WIE du es aktivierst (einzige aussage war "per vis" ...). per set tre auf "scriptEnabled" ? oder wie?

**Comment by krobipd** [comment]
Ich denke dass es das selbe wie hier ist https://github.com/ioBroker/ioBroker.javascript/issues/976

bei mir ist es auf „Play“ drücken bzw im scriptenabled das Script auf True stellen. Hat vorher Monate lange funktioniert.

**Comment by Apollon77** [comment]
Yes, I found the issue ... fix comes later today

**Comment by Apollon77** [comment]
fixed in 5.3.2
