### ISSUE TITLE
Error im Log

### ISSUE THREAD

**Issue by evolvo187** [ioBroker/ioBroker.javascript#979]
**Describe the bug**  
Fehlermeldung im Log

**To Reproduce**  
sporadisch (ca 10 mal in der Stunde)

**Expected behavior**  
kein Fehlverhalten zu beobachten
die Datei /shepherd.db ist vorhanden
die Datei /shepherd.db **.tmp** ist nicht vorhanden

**Screenshots & Logfiles**  
<html>
<body>

javascript.0 | 2022-03-07 11:23:19.779 | error | Cannot read file /opt/iobroker/iobroker-data/zigbee_0/shepherd.db.tmp: Error: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/zigbee_0/shepherd.db.tmp'
-- | -- | -- | --

</body>
</html>

![Screenshot22](https://user-images.githubusercontent.com/33641213/157013747-1381e412-e92b-45a4-971c-68d51ba17df8.png)

![Screenshot23](https://user-images.githubusercontent.com/33641213/157014143-ed4c4470-82bc-43cb-8583-a3bdbe63939e.png)

**Versions:**  
Adapterversion: 5.2.21
JS-Controller-Version: 4.0.15
Knotenversion: 14.19.

**Additional context**  
**Muss ich diesen Fehler beachten?**
**Wie könnte ich diesen Fehler beseitigen?**

Gruß Heiko

**Comment by Apollon77** [comment]
Kann es sein das du als "Mirror" Verzeichnis /opt/iobroker/iobroker-data" angegeben hast? Dann wäre das absolut verständlich und solltest Du stark überdenken und besser ein EIGENES Verzeichnis nehmen was nicht noch anderennInhalt hat, sonst kann dir das wer weiss was passieren ...
