### ISSUE TITLE
Abfrage Skript-Status (ein/aus) liefert sporadisch falsche Ergebnisse

### ISSUE THREAD

**Issue by magnustillig** [ioBroker/ioBroker.javascript#981]
**Describe the bug**  
Folgende Funktion ist verfügbar:

Scripts activity
There is a possibility to enabled and disable scripts via states. For every script the state will be created with name javascript.INSTANCE.scriptEnabled.SCRIPT_NAME. Scripts can be activated and deactivated by controlling of this state with ack=false

Bei der Abfrage des Skript-Status' werden teilweise falsche Ergebnisse geliefert, d. h. das Skript läuft, jedoch kommt als Ergebnis der Abfrage "false" zurück.

Beispiel:

`console.log(getState("javascript.0.scriptEnabled.Ordnername.Skript1").val);`

--> Es wird ins Log "false" geschrieben, obwohl das Skript läuft. Sowohl in der Skripte-Ansicht wird es als aktiv/ein dargestellt wie auch in der Objekte-Ansicht steht der state auf "true".

Das Problem tritt jedoch nicht immer auf. Manchmal braucht es mehrere Neustarts bis das Problem auftritt. Dann kann es wieder sein, dass es bei fünf Neustarts nacheinander auftritt.

Weitere Infos: https://forum.iobroker.net/topic/53166/fehler-ein-aus-zustand-switch-active-skript

**To Reproduce**  
1. Mitthilfe von folgendem Befehl den Status eines Skripts abfragen:
`console.log(getState("javascript.0.scriptEnabled.Ordnername.Skript1").val);`
2. Mehrere Neustarts von ioBroker durchführen
4. Irgendwann steht im Log "false", obwohl das Skript läuft.

**Expected behavior**  
Ich erwarte als Ausgabe "true", da das Skript ja aktiv ist.

**Screenshots & Logfiles**  
Situation: Skript läuft

Abfrage: `console.log(getState("javascript.0.scriptEnabled.Ordnername.Skript1").val);`

Ausgabe im Log: `script.js.Ordnername.Skript2: `false`

**Versions:**  
 - Adapter version: 5.2.21
 - JS-Controller version: 4.0.19
 - Node version: v14.19.0
 - Operating system: Raspbian GNU/Linux 10 (buster) 5.10.103-v7l+

**Additional context**  
Andere Personen haben das gleiche Problem.

**Comment by Apollon77** [comment]
Please check current Beta version 5.3.3 ... issue the same there?

**Comment by magnustillig** [comment]
> Please check current Beta version 5.3.3 ... issue the same there?

Das Problem besteht auch mit der Adapter-Version 5.3.3

Ich habe nun noch etwas getestet und mir ist Folgendes aufgefallen:

Dieses Problem besteht nur bei Skripten, die schon älter sind. In meinem Fall heißt das Folgendes:

Ich habe aktuell vier Skripte (3x Blockly, 1x JavaScript) am laufen.

1 Blockly-Skript und 1 JavaScript-Skript wurden zeitlich zum gleichen Zeitpunkt erstellt (ca. August 2021). Die anderen beiden Blockly-Skripte wurden erst später erstellt.

Nur bei den beiden Skripten, die im August 2021 erstellt wurden tritt das Problem auf.

Lese ich den Status der "neueren" Skripte aus, funktioniert es immer problemlos. Wenn ich ein altes Skript, bei dem der Fehler auftritt, lösche und neu anlege ist der Fehler für dieses Skript auch weg.

**Comment by Apollon77** [comment]
Haben die Skripte wo es nicht tut ein scriptsEnabled Objekt? Falls nicht bitte einmal starten ... ab dann korrekt?

**Comment by magnustillig** [comment]
> Haben die Skripte wo es nicht tut ein scriptsEnabled Objekt? Falls nicht bitte einmal starten ... ab dann korrekt?

Ich glaube, ich habe die Frage nicht ganz verstanden.

Also ein Objekt (state) im scriptEnabled-Ordner gibt es, wie soll ich sonst denn den Status des Skritps abfragen.

Falls du das meinst...

**Comment by Apollon77** [comment]
Ok, so you want to say that the scriptEnabled states do not always show correct values? Can you find out when this happens?

Code wise it is set to "true" when the script starts and to false when it is stopped ... Please try to reproduce when it is not that way in your case. I can not reproduce it

**Comment by magnustillig** [comment]
> Ok, so you want to say that the scriptEnabled states do not always show correct values? Can you find out when this happens?
> 
> Code wise it is set to "true" when the script starts and to false when it is stopped ... Please try to reproduce when it is not that way in your case. I can not reproduce it

Ja, fast. Wenn man die scriptEnabled-Objekte bspw. über Skripte weiterverarbeitet, werden falsche Werte ausgelesen.

Folgend mal ein Beispiel:

Ich habe eine Skript "Skript1".

Dann habe ich ein Skript "Skript2". Skript 2 hat folgenden Inhalt:

`var Intervall;


Intervall = setInterval(async function () {
  console.log(getState("javascript.0.scriptEnabled.Testordner.Skript1").val);
}, 10000);`

Skript 2 schreibt mir also alle 10 Sekunden den Wert des Objektes "javascript.0.scriptEnabled.Testordner.Skript1" in das Log/Protokoll.

Nun führe ich beispielsweise einen Neustart von ioBroker (iobroker stop / iobroker start) oder einen Neustart meines Raspberry Pi (es ist egal ob ich nur einen Neustart von ioBroker oder von dem kompletten Raspberry Pi durchführe, das Problem tritt in beiden Fällen auf) durch. Beim Start von ioBroker sehe ich dann im Log, dass beide Skripte (Skript1 & Skript2) gestartet werden. Nach 10 Sekunden schreibt das Skript 2 in das Log/Protokoll: false

Wenn ich nun in ioBroker aber auf den Reiter "Skripte" wechsle, läuft das Skript, d. h. die zwei grünen "Skript stoppen"-Button sind sichtbar. Auch wenn ich in ioBroker auf die Objekte-Ansicht wechsle und in den entsprechenden Ordner wechsle, erscheint als Wert des scriptEnabeld-Objektes von Skript1 "true". Das bedeutet, dass nur das Auslesen des scriptEnabled-Objektes bspw. über ein anderes Skript nicht richtig funktioniert bzw. falsche Werte liefert.

Das Problem besteht jedoch nicht immer. Manchmal starte ich neu und die Ausgabe im Log/Protokoll ist "true". Wenn ich bspw. 10 Mal ioBroker neustarte kann es sein, dass fünf Mal true in das Log geschrieben wird und fünf Mal false. Jedoch habe ich bisher noch keine Abhängigkeit gefunden. Die Neustarts von ioBroker führe ich immer genau gleich durch.

Das Einzige was mir bisher aufgefallen ist, das habe ich oben ja auch schon beschrieben, dass das Problem nur bei "alten" Skripten besteht, sprich sie wurden mit einer älteren Version von ioBroker bzw. einer älteren Version des javascript-Adapters erstellt. Jedoch kann ich nicht sagen mit welcher Version das war. Nur den Zeitraum kann ich grob eingrenzen (siehe oben). Theoretisch könnte man das irgendwie herausfinden, weil ich meinen ioBroker eigentlich sehr aktuell halte, d. h. man müsste schauen welche Version von ioBroker bzw. dem javascript-Adapter im oben genannten Zeitraum im stable-Repo war. Wenn ich nämlich den Status von "neueren" bzw. kürzlich erst erstellten Skripten auslese und mir in das Log/Protokoll schreiben lasse, passt alles.

Ich bin nun zum Beispiel mal testweise hergegangen und habe neu gestartet bis der Fehler aufgetreten ist. Als der Fehler dann da war habe ich in Skript2 statt dem scriptEnabled-Objekt "javascript.0.scriptEnabled.Testordner.Skript1" das scriptEnabled-Objekt "javascript.0.scriptEnabled.Testordner.Skript3" hinterlegt. Skript3 hat genau den gleichen Inhalt wie Skript1, Skript3 wurde jedoch erst vor ein paar Tagen erstellt. Nach der Änderung in Skript2 wird direkt true in das Log/Protokoll geschrieben. Stelle ich nun wieder um auf das scriptEnabled-Objekt von Skript1 wird wieder false in das Log/Protokoll geschrieben. Wenn ich dann aber hergehe und das Skript1 einmal händisch (also über den Start/Stop-Button in der Skripte-Ansicht) neustarte, passt die Ausgabe, dann wird true in das Log/Protokoll geschrieben.

Haben Sie zur Reproduzierung des Problems ein altes Skript verwendet oder eher ein Neueres? Es geht darum, dass das Skript, von dem der Wert des scriptEnabled-Objektes in das Log geschrieben wird älter ist. Das Skript, welches die Log-Ausgabe schreibt kann ruhig neuer bzw. neu erstellt sein.

Hilft es Ihnen weiter, wenn ich Ihnen das Problem bspw. über TeamViewer zeige?

**Comment by Apollon77** [comment]
Ok, diese Infos helfern schon: Jezzt noch eine Preisfrage ...Wenn das Skrpt wie oben fälschlicherweise "false" liefert ... Wenn du jetzt im Admin unter Objekt den Wert schaust ... ist das auch false oderist es true?

Ich habe da eine Vermutung - nämlich das es ein Timeing issue ist was speziell beim Start des Adapters passiert das quasi die Skripte die zuerst gestartet werden ggf ihren gecachten Status nicht aktualisiert bekommen weil starten zu schnell ist quasi ... ist es korrekt das der status richtig ist sobald du nach dem start vom adapter das skript was falsche Werte hatte einmal stoppst und neu startest?

**Comment by magnustillig** [comment]
> Ok, diese Infos helfern schon: Jezzt noch eine Preisfrage ...Wenn das Skrpt wie oben fälschlicherweise "false" liefert ... Wenn du jetzt im Admin unter Objekt den Wert schaust ... ist das auch false oderist es true?
> 
> Ich habe da eine Vermutung - nämlich das es ein Timeing issue ist was speziell beim Start des Adapters passiert das quasi die Skripte die zuerst gestartet werden ggf ihren gecachten Status nicht aktualisiert bekommen weil starten zu schnell ist quasi ... ist es korrekt das der status richtig ist sobald du nach dem start vom adapter das skript was falsche Werte hatte einmal stoppst und neu startest?

Im Admin unter Objekte steht das scriptEnabled-Objekt auf "true", also stimmt mit der Ansicht unser Skripte (Admin / Skripte) überein.

Nur die Ausgabe im Log/Protokoll ist falsch.

Ja, sobald ich das Skript einmal stoppe und wieder starte passt die Log-Ausgabe.

**Comment by Apollon77** [comment]
Kannst Du bitte mal GitHub Version vom Adapter installieren? Das müssen wir jetzt austesten. Ich kann es so nicht nachstellen. nach Install bitte Adapter manuell neu starten falls es nicht automatisch passiert ist. Hilft das schon?

**Comment by Apollon77** [comment]
PS: Habe gerade eben (ca. 16:00) nochmal ein update gepoistet ... falls du schon versucht hast bitte ggf nochmal das aktuellste nehmen

**Comment by magnustillig** [comment]
> Kannst Du bitte mal GitHub Version vom Adapter installieren? Das müssen wir jetzt austesten. Ich kann es so nicht nachstellen. nach Install bitte Adapter manuell neu starten falls es nicht automatisch passiert ist. Hilft das schon?

Das wird etwas schwierig... ich weiß leider nicht wie ich einen Adapter aus GitHub installiere?

Des Weiteren tritt der Fehler auf meinem Produktiv-System auf, da würde ich eigentlich ungern Test-Versionen installieren. Die Adapter-Version aus dem beta-Repo war schon so ne Sache...

Gibt es keine andere Möglichkeit?

**Comment by Apollon77** [comment]
Ich habs nachstellen können... bin nochmal dran. Kommt dann offizielles Update

**Comment by magnustillig** [comment]
> Ich habs nachstellen können... bin nochmal dran. Kommt dann offizielles Update

Ok, perfekt.

Ich hätte wirklich gerne geholfen, das Blöde ist nur, dass der Fehler auf meinem Test-System nicht auftritt, da ich das vor Kurzem erst aufgesetzt habe.

Vielen Dank!
