### ISSUE TITLE
Anlegen von Blocklys scheitert zu 95% im 1. Versuch

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.javascript#983]
PlatformBetriebssystem:win32
Architektur:x64
CPUs:4
Geschwindigkeit:1995 MHz
Modell:Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM:7.9 GB
Node.js:v14.16.0
Adapter-Anzahl:486
NPM:6.14.11
Javaskript Adapter 5.3.3

Ich möchte mal auf zwei BUGs(?) im Skript Editor hinweisen.

1.) Das anlegen von neuen Skripten (kann nur von Blocklys berichten) über das "+" Symbol, schlägt in 95% aller Versuche fehl. Drückt man OK, kann man Glück haben und ein leeres Blockly wird angelegt - wie gesagt, in 95% der Fälle funktioniert dieses aber erst beim 2. oder 3. mal.

![image](https://user-images.githubusercontent.com/44617472/157818403-26704d83-9f5e-430d-8f18-b1b52ad94220.png)

2.) Wenn man beim Editor mit einem markierten Blockly Block zu dicht an den Linken Rand ran kommt, wird der gesamte Block incl. des anhängigen Baums gelöscht. Das ist sehr ärgerlich bei großen und verschachtelten Blöcken die noch nicht gespeichert wurden.

Leider gibt es keinen "Rückgängig" Button, sodaß man die Blöcke wieder zurück holen könnte. 

![image](https://user-images.githubusercontent.com/44617472/157819272-6e78df09-601a-4f49-8a9f-c051b5b22b9b.png)

**Comment by Apollon77** [comment]
zu 1.) Was passiert wenn es nicht geht? Gibt es Fehler in der Browser Javascript konsole?

**Comment by JBSullivan** [comment]
DAs hier wird im Editor angezeigt, nachdem man OK, für den Namen eines neuen Skriptes angeklickt hat.
![image](https://user-images.githubusercontent.com/44617472/158012531-dc1c286a-2499-48ab-9697-10540dca1b53.png)

.... und das alles kommt unter F12

`iobroker.admin@5.3.1
instrument.ts:125 [2022-03-12T09:28:41.810Z] Try to connect
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
index.js:20 iobroker.javascript@5.3.3 using theme "dark"
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:59 [2022-03-12T09:28:49.460Z] Try to connect
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1          Failed to load resource: the server responded with a status of 403 ()
instrument.ts:125 Detected custom blockly: email
instrument.ts:125 Detected custom blockly: iot
instrument.ts:125 Detected custom blockly: telegram
instrument.ts:125 Socket: true
instrument.ts:125 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jl (2.b35d4219.chunk.js:2:3224284)
    at 2.b35d4219.chunk.js:2:3172606
    at Po (2.b35d4219.chunk.js:2:3184243)
    at Go (2.b35d4219.chunk.js:2:3188876)
    at qo (2.b35d4219.chunk.js:2:3188580)
    at Ki (2.b35d4219.chunk.js:2:3229525)
    at Ll (2.b35d4219.chunk.js:2:3215693)
    at Cl (2.b35d4219.chunk.js:2:3215621)
    at jl (2.b35d4219.chunk.js:2:3215484)
    at gl (2.b35d4219.chunk.js:2:3212450)
    at vl (2.b35d4219.chunk.js:2:3209798)
    at eu (2.b35d4219.chunk.js:2:3225937)
    at 2.b35d4219.chunk.js:2:3227325
    at Ol (2.b35d4219.chunk.js:2:3212828)
    at ou (2.b35d4219.chunk.js:2:3227310)
    at Object.t.render (2.b35d4219.chunk.js:2:3234789)
    at HTMLScriptElement.a.onload (main.55d1a215.chunk.js:1:518485)
(anonym) @ instrument.ts:125
react-dom.production.min.js:260 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jl (2.b35d4219.chunk.js:2:3224284)
    at 2.b35d4219.chunk.js:2:3172606
    at Po (2.b35d4219.chunk.js:2:3184243)
    at Go (2.b35d4219.chunk.js:2:3188876)
    at qo (2.b35d4219.chunk.js:2:3188580)
    at Ki (2.b35d4219.chunk.js:2:3229525)
    at Ll (2.b35d4219.chunk.js:2:3215693)
    at Cl (2.b35d4219.chunk.js:2:3215621)
    at jl (2.b35d4219.chunk.js:2:3215484)
    at gl (2.b35d4219.chunk.js:2:3212450)
    at vl (2.b35d4219.chunk.js:2:3209798)
    at eu (2.b35d4219.chunk.js:2:3225937)
    at 2.b35d4219.chunk.js:2:3227325
    at Ol (2.b35d4219.chunk.js:2:3212828)
    at ou (2.b35d4219.chunk.js:2:3227310)
    at Object.t.render (2.b35d4219.chunk.js:2:3234789)
    at HTMLScriptElement.a.onload (main.55d1a215.chunk.js:1:518485)
4instrument.ts:125 Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
(anonym) @ instrument.ts:125
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1          Failed to load resource: the server responded with a status of 403 ()
sentry.iobroker.net/api/56/store/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1          Failed to load resource: the server responded with a status of 403 ()
instrument.ts:125 Translate: easy
instrument.ts:125 Translate: for programmers
instrument.ts:125 Translate: for professionals
instrument.ts:125 Translate: Empty name is not allowed
33instrument.ts:125 Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
(anonym) @ instrument.ts:125
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1          Failed to load resource: the server responded with a status of 400 ()
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://10.122.60.87:8081/adapter/min-maps/vs/loader.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://10.122.60.87:8081/adapter/min-maps/vs/editor/editor.main.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://10.122.60.87:8081/adapter/min-maps/vs/editor/editor.main.nls.de.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für http://10.122.60.87:8081/adapter/javascript/plugins/popper.js.map: HTTP-Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE konnte nicht geladen werden`

**Comment by Apollon77** [comment]
Ok, scheint irgendewas im Frontend zu sein. Ich kann es bei mir nicht nachstellen

**Comment by cdaerr** [comment]
Fehler 2, das mit den verschwindenden Blöcken, kann ich bestätigen. Das passiert bei mir auch, aber hauptsächlich bei umfangreicheren Skripten. Hier kommt es sogar zu selbständigem Verschieben der Blöcke, insbesondere wenn ich weitere Trigger oder IF-Else Bedingungen über das Zahnrad hinzufüge.

**Comment by Apollon77** [comment]
Es ist halt unpraktisch zwei Grundvershiedene Themen in einem "issue" zu haben ... am besten auftrennen

**Comment by Apollon77** [comment]
ok, bitte getrennte Issues anlegen
