### ISSUE TITLE
Multiple trigger does not react when ID contains '+' in Folder

### ISSUE THREAD

**Issue by cdaerr** [ioBroker/ioBroker.javascript#984]
**Describe the bug**  
Two bolean datapoint in userdata are created. Trigger 2 contains a '+' in the ID, and Trigger 2 does not:
![grafik](https://user-images.githubusercontent.com/98185044/158049727-c2a7901f-54bb-42d4-aefd-ee705ea21ce4.png)

The following Blockly Script is used to display the trigger events. On the left side singel trigger events are used and on the right side a multiple trigger is used:
![grafik](https://user-images.githubusercontent.com/98185044/158049781-59919777-3fd9-4641-a710-383c32c5cfb4.png)

At 7:51:46 Trigger 1 was set to TRUE.
At 7:52:19 Trigger 2 was set to TRUE.
The log output shows that the multiple trigger did not react on Trigger 2, it only reacts on Trigger 1:
![grafik](https://user-images.githubusercontent.com/98185044/158049923-11074eab-5a7e-4a2f-8b33-cc9d2d8fa013.png)

**Expected behavior**  
The multiple trigger should also react on Trigger 2.

**Export**
Export of datapoints and blockly script attached as ZIP:  
[TriggerTest.zip](https://github.com/ioBroker/ioBroker.javascript/files/8239132/TriggerTest.zip)

**Versions:**  
 - Adapter version: 5.2.21
 - JS-Controller version: 4.0.15
 - Node version: v14.19.0
 - Operating system: ubuntu 20.04

**Comment by Apollon77** [comment]
Please show the generated JavaScript of that blockly

**Comment by cdaerr** [comment]
The script is included in ZIP file.

**Comment by Apollon77** [comment]
It would be easierr if you show me the generated JS of that affected blockly ... I have an idea and just need to proof it ...

**Comment by cdaerr** [comment]
I don't know what you mean. The code included in ZIP is the only I have.

**Comment by Apollon77** [comment]
In the javascript Editor you can click on the Blockly|JS graphic and then the editor switches and shows the generated JavaScriüt

**Comment by cdaerr** [comment]
![grafik](https://user-images.githubusercontent.com/98185044/158062542-52e97199-dc4f-4dbb-b436-6676515dc4d4.png)

**Comment by Apollon77** [comment]
Ok, as thought, the # needs to be escaped ...

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by cdaerr** [comment]
Wich version?

Is there a new beta Version?

**Comment by Apollon77** [comment]
You can install from GitHub right now ... (Admin - expert mode - the github icon ... second tab) ... or you wait for the beta release

**Comment by cdaerr** [comment]
It does not work:
![grafik](https://user-images.githubusercontent.com/98185044/158109633-bbc8b3bb-66de-4b6b-9414-48df39f70c33.png)


![grafik](https://user-images.githubusercontent.com/98185044/158109638-68aa6cdd-634b-4a7b-8389-5bfa8292ff1a.png)


So Please reopen the ticket.

**Comment by Apollon77** [comment]
Please da small adjustment to the blockly so that the code gets regenerated ... it should now look different

**Comment by cdaerr** [comment]
Yes I did so.

Do you tried with the script porvided in ZIP File?

**Comment by Apollon77** [comment]
@cdaerr Did you retried with updated version?

**Comment by cdaerr** [comment]
Thanks,

it works well with version 5.4.2.
