### ISSUE TITLE
Probleme mit Trigger "Falls Objekt"

### ISSUE THREAD

**Issue by technik242** [ioBroker/ioBroker.javascript#986]
Bei neuen unter JS 5.4.0 erstellten Skripten funktioniert der "Falls Trigger" nicht, d.h. Wird nicht ausgelöst.
Da sind im Code wohl ein paar Anführungszeichen zuviel:
`on({id: ["'0_userdata.0.Anwesenheit.Switchbot'","'0_userdata.0.Anwesenheit.Tag'"], change: "ne"}, async function (obj) {
    console.error('Geschaltet.');
});`

**Comment by Diginix** [comment]
Hehe, genau so habe ich es auch gelöst.
Wenn man alle Skripte als ZIP exportiert und in der ZIP in den Dateien nach `on({id: ["'` sucht und fündig wird, ist noch ein Skript inkorrekt.

**Comment by Apollon77** [comment]
GitHub updated, 3.4.1 comes to npm/beta soon ,.. if someone want to test:install from GitHub and "touch" blockly again ...now the additional " should be gone. Does it work?

**Comment by Diginix** [comment]
First test with 5.4.2 looks good for me. Can be closed imho.
