### ISSUE TITLE
From Value to Value Blockly

### ISSUE THREAD

**Issue by 69paulus** [ioBroker/ioBroker.javascript#989]
"from value to value(between)" (example: temperature "from 0 degrees to 25 degrees")
or what concerns me is brightness (example : "from 10000 lux to 20000 lux")
For "time" there is (example) : Current time Between : 10:00 and 14:00

Best regards

**Comment by Apollon77** [comment]
duplicate #974 ??

**Comment by 69paulus** [comment]
Sorry, i justt tried to put this in english, in german no one answer me . I hopped for an answer?

**Comment by Apollon77** [comment]
It is flagged as enhancement ... so now you need to wait until someone have time for it  ... all "good"
