### ISSUE TITLE
Exception: No such file or directory

### ISSUE THREAD

**Issue by timomatrixer** [ioBroker/ioBroker.javascript#990]
**To Reproduce**  
Every time, when backitup adapter want to backup data.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/40664333/159225925-cf0d27d6-9eb4-4233-a187-559304289d30.png)

**Versions:**  
 - Adapter version: 5.2.21
 - JS-Controller version: 3.3.22
 - Node version: 12.22.6
 - Operating system: Linux Server 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64

**Comment by Apollon77** [comment]
Could it be that you use monitoring and have set /opt/iobroekr as the mirrot directory??? Ver y baaad idea. Then it is monutoring all data inside this and might stumpble over other processes doing stuff

**Comment by timomatrixer** [comment]
you mean mirroring?
![image](https://user-images.githubusercontent.com/40664333/159227706-7d832f3e-e32d-43c1-9524-760f05f95225.png)
So I'm not allowed to use mirroring and backitup together?

**Comment by Apollon77** [comment]
if you use backitup then the scripts are saved as the objects ... but you should not use the backup folder as target for mirroring. I will fix the crash but also add security measures against this
