### ISSUE TITLE
existsState mit 5.4.5 Fehler

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.javascript#991]
Seit dem update auf die Version 5.4.5 bekomme ich einen Fehler im Log:

`getState "tradfri.0.G-131074.position" not found (3) states[id]=null`

Die Abfrage dazu lautet:

`var id_Rollo = 'tradfri.0.G-131074.position'/*Blind position*/;
var Rollo = existsState(id_Rollo) ? getState(id_Rollo).val : ((Rollo_1 + Rollo_2 + Rollo_3 + Rollo_4 + Rollo_5) /5);`

Grundsätzlich ist die Logausgabe nicht falsch da das Feld zu dem Zeitpunkt leer ist. Allerdings gab es dazu vorher keine Meldung im Log.

Im Versionsverlauf steht eigentlich bei 5.4.5 das Fehler mit existsState behoben wurden. Das scheint bei mir nicht funktionieren. 

Hinweis: Die Scripte laufen schon sehr sehr lange ohne die Fehlermeldung. Ich vermute es hängt also mit dem Update zusammen.
Vorher hatte ich die 5.3.3

**Comment by Apollon77** [comment]
Good catch. Please try GitHub version of JavaScript adapter. Should be fixed there

**Comment by Baenker** [comment]
Das ging schnell. Fehlermeldung scheint weg zu sein. Vielen Dank
