### ISSUE TITLE
Nach javascript Adapter 5.5.0 Update = EPERM wieder da

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.javascript#992]
Heute Morgen das Adapter Update auf 5.5.0 durchgeführt. Sofort nach dem Neustart des Adapters kam die Meldung unten. Nach dem Update des JS-controller auf 4.x.x. trat diese Meldung wochenlang nicht mehr auf.

Betriebssystem ist Windows

PlatformBetriebssystem:win32
Architektur:x64
CPUs:4
Geschwindigkeit:1995 MHz
Modell:Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM:7.9 GB
NPM:6.14.11

 

<html>
<body>

host.GLT(GLT) | 2022-03-23 14:02:59.148 | error | cannot check file: C:\iobroker\GLT\log\iobroker.2022-03-16.log - EPERM: operation not permitted, lstat 'C:\iobroker\GLT\log\iobroker.2022-03-16.log'
-- | -- | -- | --
host.GLTGLT) | 2022-03-23 14:02:59.148 | error | host.GLT(GLT) cannot check file: C:\iobroker\GLT\log\iobroker.2022-03-16.log - EPERM: operation not permitted, lstat 'C:\iobroker\GLT\log\iobroker.2022-03-16.log'

</body>
</html>

**Comment by Apollon77** [comment]
Hm ... Yes but the 5.5.0 do not include any change to logging because logging only comes from controller ... so seems like the issue ther eis not fixed :-(

**Comment by Apollon77** [comment]
PS: So we should reopen the isue in js.controlelr we had for that
